### DISCUSSION TITLE
Provisioning fails, missing Instance Profile

### DISCUSSION THREAD

**Discussion by afolarin** [weaveworks/eksctl#4750] [Q&A] [answered]
Hi,
I'm using eksctl to deploy and configure Karpenter

```yaml
# cluster.yaml
# A cluster 
# - with 1 managed nodegroups and Karpenter
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: prod-cluster
  region: eu-west-2
  tags:
    Project: foo
    karpenter.sh/discovery: prod-cluster
  version: "1.21"

# cluster AZs must be set explicitly for single AZ nodegroup example to work
availabilityZones: ["eu-west-2a", "eu-west-2b", "eu-west-2c"]

karpenter:
  version: '0.6.0'
  createServiceAccount: true

iam:
  withOIDC: true

managedNodeGroups:
  - name: medium-mng-1
    instanceType: m5.large
    minSize: 1
    maxSize: 10
    desiredCapacity: 1 
    volumeSize: 100
    volumeType: gp3
    availabilityZones: ["eu-west-2b"]
    ssh:
      enableSsm: true
    labels: { nodegroup-func: karpenter-nodes}
    tags:
      nodegroup-func: karpenter-nodes
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true
        ebs: true
        #fsx: true
        efs: true


# Cloudwatch logging
cloudWatch:
  clusterLogging:
    enableTypes: ["audit", "authenticator", "controllerManager"]
    logRetentionInDays: 60

```
This all deploys the eks cluster fine, Karpenter deployed and seemingly configured etc.

However, testing the pause container / inflate example: https://karpenter.sh/v0.6.0/getting-started/#provisioner
I get this error on scaling the containers `kubectl scale deployment inflate --replicas 5`

```sh
2022-02-04T22:24:55.322Z	ERROR	controller.provisioning	Could not launch node, launching instances, getting launch template configs, getting launch templates, neither spec.provider.instanceProfile nor --aws-default-instance-profile is specified	{"commit": "62c4546", "provisioner": "default"}
```

Sounds like Karpenter may not be discovering the instance profile 
https://karpenter.sh/v0.6.0/getting-started/#create-the-karpenternode-iam-role 
which states:
> "Karpenter discovers the InstanceProfile using the name `KarpenterNodeRole-${ClusterName}`"

But using eksctl cluster config the InstanceProfile ends up with `eksctl-` prepended (i.e. `eksctl-KarpenterNodeRole-${ClusterName}`
