### DISCUSSION TITLE
eksctl without IAM:CreateRole permissions

### DISCUSSION THREAD

**Discussion by ecpullen** [weaveworks/eksctl#5423] [Q&A]
I am trying to setup eksctl for cluster creation using existing service roles and instance profiles.
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name:  eksctl-test
  region: us-west-2

iam:
  serviceRoleArn: arn:aws:iam::***************:role/*********************
```
Whenever I use `eksctl create cluster` it errors with.
```
AWS::IAM::Role/ServiceRole: CREATE_FAILED – "API: iam:CreateRole User: arn:aws:sts::*********:assumed-role/********** is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::*********:role/eksctl-<cluster_name>-cluster-ServiceRole-10FMX3LU9UVU because no identity-based policy allows the iam:CreateRole action"
```
Is it possible to use eksctl without creating a role?
