### DISCUSSION TITLE
EKSCTL Private Subnets created with Routing to IGW for IPv6 ?

### DISCUSSION THREAD

**Discussion by hajdukda** [weaveworks/eksctl#6199] [Q&A]
Hello,

Our VPC config looks like this:
```
vpc:
  cidr: "10.XX.0.0/16"
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
  publicAccessCIDRs: ...
  nat:
    gateway: HighlyAvailable
  autoAllocateIPv6: true
```

For w/e reason eksctl creates private subnets with routing:
::/0 - igw-43243243242 

This causes creation of managed node groups to fail due to AWS thinking those subnets are public and should have public IP assigned to nodes.

How to change the configuration to override subnet configuration to not assigne IGW to Private Subnets ?

From https://aws.amazon.com/premiumsupport/knowledge-center/configure-private-ipv6-subnet/ I could conclude that EKSCTL should have created Private Subnets with IPv6 Egress-Only Internet Gateways - instead it attached regular IGW to all Subnets.
