### DISCUSSION TITLE
How to add additional flags to kubelet with eksctl?

### DISCUSSION THREAD

**Discussion by karma-git** [weaveworks/eksctl#7026] [Q&A]
Hello everyone!

I'm new with eksctl and looking for help. Trying to provision a cluster with the following command and scirpt:

```yaml
# eksctl create cluster -f cluster.yaml
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ahorbach-eksctl-v2
  version: '1.23'
  region: eu-west-1


## ref: https://eksctl.io/usage/container-runtime/#managed-nodes
managedNodeGroups:
  - name: m-ng-1
    amiFamily: AmazonLinux2
    ami: ami-0946bd4772222cd06
    instanceType: t3.medium
    overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh ahorbach-eksctl-v2 --allowed-unsafe-sysctls="net.ipv4.tcp_fin_timeout,net.ipv4.tcp_tw_reuse"
```

But as I see on nodes, my flag with unsafe-sysctls does not applies

```shell
# /usr/bin/kubelet --config /etc/kubernetes/kubelet/kubelet-config.json --kubeconfig /var/lib/kubelet/kubeconfig --container-runtime docker --network-plugin cni --image-credential-provider-config /etc/eks/image-credential-provider/config.json --image-credential-provider-bin-dir /etc/eks/image-credential-provider --node-ip=192.168.29.80 --pod-infra-container-image=602401143452.dkr.ecr.eu-west-1.amazonaws.com/eks/pause:3.5 --v=2 --cloud-provider=aws
```

Thank you
