### ISSUE TITLE
Create cluster: panic: runtime error with eksctl version 0.1.39

### ISSUE THREAD

**Issue by dbluxo** [weaveworks/eksctl#1003]
**What happened?**
Panic: runtime error: invalid memory address or nil pointer dereference

**What you expected to happen?**
After switching from 0.1.38 to 0.1.39 `eksctl create cluster -f cluster.yaml` is broken for me

**How to reproduce it?**
Used config (cluster.yaml):
```
 apiVersion: eksctl.io/v1alpha5
 kind: ClusterConfig

 metadata:
   name: dev-eks
   region: eu-central-1

 vpc:
   subnets:
     private:
       eu-central-1a: {id: subnet-00000000000000000}
       eu-central-1b: {id: subnet-00000000000000001}
       eu-central-1c: {id: subnet-00000000000000002}

 nodeGroups:
   - name: ng-1a
     ami: ami-0b7127e7a2a38802a
     instanceType: t3.medium
     desiredCapacity: 1
     availabilityZones: ["eu-central-1a"]
     privateNetworking: true
     ssh:
       publicKeyName: bla.bla
     iam:
       attachPolicyARNs:
         - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
         - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
         - arn:aws:iam::000000000000:policy/ManageRoute53HostedZone
```
**Versions**
Please paste in the output of these commands:
```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.1.39"}
```

**Logs**
```
eksctl create cluster -f cluster.yaml
[ℹ]  using region eu-central-1
[✔]  using existing VPC (vpc-xxx) and subnets (private:[subnet-0... subnet-1... subnet-2...] public:[])
[!]  custom VPC/subnets will be used; if resulting cluster doesn't function as expected, make sure to review the configuration of VPC/subnets
[ℹ]  nodegroup "ng-1a" will use "ami-0b7127e7a2a38802a" [AmazonLinux2/1.13]
[ℹ]  using EC2 key pair "bla.bla"
[ℹ]  using Kubernetes version 1.13
[ℹ]  creating EKS cluster "dev-eks" in "eu-central-1" region
[ℹ]  1 nodegroup (ng-1a) was included
[ℹ]  will create a CloudFormation stack for cluster itself and 1 nodegroup stack(s)
[ℹ]  if you encounter any issues, check CloudFormation console or try 'eksctl utils describe-stacks --region=eu-central-1 --name=dev-eks'
[ℹ]  2 sequential tasks: { create cluster control plane "dev-eks", create nodegroup "ng-1a" }
[ℹ]  building cluster stack "eksctl-dev-eks-cluster"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x20ac393]

goroutine 51 [running]:
github.com/weaveworks/eksctl/pkg/cfn/builder.(*ClusterResourceSet).addOutputsForVPC(0xc00011a280)
	/src/pkg/cfn/builder/vpc.go:160 +0x103
github.com/weaveworks/eksctl/pkg/cfn/builder.(*ClusterResourceSet).AddAllResources(0xc00011a280, 0xc00011a280, 0xc000550e80)
	/src/pkg/cfn/builder/cluster.go:49 +0xac
github.com/weaveworks/eksctl/pkg/cfn/manager.(*StackCollection).createClusterTask(0xc000354f60, 0xc0000407e0, 0x60, 0x0)
	/src/pkg/cfn/manager/cluster.go:33 +0x329
github.com/weaveworks/eksctl/pkg/cfn/manager.(*taskWithoutParams).Do(0xc00010f100, 0xc0000407e0, 0xc0000407e0, 0x1)
	/src/pkg/cfn/manager/tasks.go:132 +0x34
github.com/weaveworks/eksctl/pkg/cfn/manager.doSingleTask(0xc000040780, 0x3a86800, 0xc00010f100, 0x0)
	/src/pkg/cfn/manager/tasks.go:185 +0xec
github.com/weaveworks/eksctl/pkg/cfn/manager.doSequentialTasks(0xc000040780, 0xc00010f160, 0x2, 0x2)
	/src/pkg/cfn/manager/tasks.go:215 +0x70
created by github.com/weaveworks/eksctl/pkg/cfn/manager.(*TaskTree).DoAllSync
	/src/pkg/cfn/manager/tasks.go:115 +0x246
```

**Comment by errordeveloper** [comment]
This will be fixed in the next PR. Please try the following work-around:

```
 apiVersion: eksctl.io/v1alpha5
 kind: ClusterConfig

 metadata:
   name: dev-eks
   region: eu-central-1

 vpc:
   nat:
      gateway: Disable
   subnets:
     private:
       eu-central-1a: {id: subnet-00000000000000000}
       eu-central-1b: {id: subnet-00000000000000001}
       eu-central-1c: {id: subnet-00000000000000002}
```
