### ISSUE TITLE
how to define kubernetes version at config file

### ISSUE THREAD

**Issue by tkang007** [weaveworks/eksctl#1047]
Hi,
How to specify kubernetes version at aws eks cluster at config file ?

**Comment by cPu1** [comment]
Hi @tkang007,

The Kubernetes version is specified in `metadata.version`. The supported versions are 1.11, 1.12 and 1.13.

```yaml
 apiVersion: eksctl.io/v1alpha5
 kind: ClusterConfig

 metadata:
   name: test-cluster
   version: "1.11"

# more fields
# ...

```
