### ISSUE TITLE
SSH Access Security Group Customization / Whitelist for unmanaged nodegroups

### ISSUE THREAD

**Issue by chasemaier** [weaveworks/eksctl#1048]
**What feature/behavior/change do you want?**

Currently the config file allows you to specify node-group configurations regarding SSH such as:

```yaml
    ssh:
      allow: true
      publicKeyName: existing-key-name
```

This results in allowing global unrestricted access to port 22. I'd like to be able to limit the scope of that allowance by providing a set of IPs/CIDRs to explicitly white-list that SSH access to.

Since cluster creation is making a new VPC, the existing Security Group with these allowances (that I happen to have in my case) can't be used in the new VPC.

I'd like some method for specifying the scope(s) of the SSH access, or importing them from an existing security group in a different VPC. E.g.

```yaml
    ssh:
      allow: true
      publicKeyName: existing-key-name
      ipWhitelist:
      - x.x.x.x/32
      - y.y.y.y/29
```

OR

```yaml
    ssh:
      allow: true
      publicKeyName: existing-key-name
      ipWhitelistSecurityGroupTemplate: sg-XXXXXX # A security group in a different VPC to clone rules from.
```

I'd prefer to not have to define this once for every node group, but rather just once per cluster, if possible.

**Why do you want this feature?**

This would would help to reduce the exposure of making SSH publicly available to nodes by imposing an IP whitelist.

---

I realize this can probably be fairly easily accomplished by waiting for cluster creation and using other tooling to add rules to the shared security group, but having it live closer to the source would make things much cleaner and less error prone.

This may be somewhat covered by https://github.com/weaveworks/eksctl/issues/735? -- but I anticipate that having a more complex / flexible syntax where this would be scoped specifically for SSH access that already has configs.
