### ISSUE TITLE
DeleteOnTermination

### ISSUE THREAD

**Issue by cdenneen** [weaveworks/eksctl#1058]
Already have
```
volumeSize: 20
volumeType: gp2
```

Looking for something like:
```
volumeDelete: true
```
that equates to `DeleteOnTermination`
```
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              Encrypted: false
              VolumeSize: 20
              VolumeType: gp2
              DeleteOnTermination: true
```
