### ISSUE TITLE
cannot validate certificate for because it doesn't contain any ip sans

### ISSUE THREAD

**Issue by hieu29791** [weaveworks/eksctl#1060]
Hi,
I created cluster on AWS with eksctl, using ubuntu image. Everything is fine, but when I type **kubectl logs**  or **helm ls**, error show like this:

> cannot validate certificate for because it doesn't contain any ip sans. I don't know what wrong

Here is my config file:  
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: TestCluster
  region: ap-southeast-1
  version: "1.12"
vpc:  
  nat:
    gateway: Single

#IAM of ServiceRole
iam:
  serviceRoleARN: "arn:aws:iam::*******:role/eksServiceRole"

nodeGroups:
  - name: Worker-Nodes-Group
    instanceType: t3.large
    desiredCapacity: 2
    minSize: 2
    maxSize: 10
    volumeSize: 100
    volumeType: gp2
    ami: ami-01168bce413d4be53
    amiFamily: Ubuntu1804
    volumeEncrypted: true
    privateNetworking: true
    ssh:
      publicKeyName: *******
    iam:
      attachPolicyARNs:
        - arn:aws:iam::*******:policy/k8s-asg-policy
        - arn:aws:iam::aws:policy/Amazon*******
        - arn:aws:iam::aws:policy/Amazon*******
        - arn:aws:iam::aws:policy/Amazon*******
      withAddonPolicies:
        autoScaler: true
        albIngress: true
```
I create some deployment/pod,  state is running, seem like ok, no error appear.
