### ISSUE TITLE
Creating new Nodegroup fails when using spotInstances

### ISSUE THREAD

**Issue by MyNameIsOka** [weaveworks/eksctl#1072]
Hi everybody,
still in the learning process of k8s and EKS, so please bear with me.

**What happened?**
When running `eksctl create nodegroup -f eksctl-mixed.yaml`, the CloudFormation process starts but gets stuck at NodeGroup  AutoScaling Group
![image](https://user-images.githubusercontent.com/18796117/62179552-ebd3e480-b387-11e9-9267-9690a24dfc5f.png)
The Autosacling group stays in that state:
![image](https://user-images.githubusercontent.com/18796117/62179572-fc845a80-b387-11e9-83a6-494ac6f3dd77.png)

eksctl create nodegroup --config-file=eksctl-mixed.yaml` starts the creation process, but CloudFormation gets stuck in NodeGroup AWS::AutoScaling::AutoScalingGroup
![image](https://user-images.githubusercontent.com/18796117/62178908-a1516880-b385-11e9-98ae-f0c15e253b96.png)
The YAML file looks like this:
```
# An example of ClusterConfig showing nodegroups with mixed instances (spot and on demand):
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
    name: btc-k8s
    region: ap-northeast-1

availabilityZones: ["ap-northeast-1a", "ap-northeast-1d"]

nodeGroups:
    - name: ng-1-spot2
      minSize: 2
      maxSize: 2
      volumeSize: 8
      instancesDistribution:
        maxPrice: 0.05
        #instanceTypes: ["t3.medium", "t2.medium"] # At least two instance types should be specified
        instanceTypes: ["m5.xlarge", "m5a.xlarge"] # At least two instance types should be specified
        onDemandBaseCapacity: 0
        onDemandPercentageAboveBaseCapacity: 0
        spotInstancePools: 2
      tags:
        k8s.io/cluster-autoscaler/enabled: 'true'
      labels:
        lifecycle: Ec2Spot
      availabilityZones: ["ap-northeast-1a", "ap-northeast-1d"]
```

**What you expected to happen?**
Create a new Nodegroup ng-1-spot2 with other spot instance types. 

**How to reproduce it?**
See "What happened?"

**Anything else we need to know?**
Using Ubuntu 18.04, eksctl version
`version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.2.0"}`

What OS are you using, are you using a downloaded binary or did you compile eksctl, what type of AWS credentials are you using (i.e. default/named profile, MFA) - please don't include actual credentials though!

**Versions** 
$ eksctl version
`version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.2.0"}`
$ kubectl version
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:18:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-eks-c57ff8", GitCommit:"c57ff8e35590932c652433fab07988da79265d5b", GitTreeState:"clean", BuildDate:"2019-06-07T20:43:03Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**
Include the output of the command line when running eksctl. If possible, eksctl should be run with debug logs. For example:
`eksctl create nodegroup -f eksctl-mixed.yaml ` log:
```
using region ap-northeast-1
will use version 1.13 for new nodegroup(s) based on control plane version
nodegroup "ng-1-spot2" will use "ami-0fde798d17145fae1" [AmazonLinux2/1.13]
1 nodegroup (ng-1-spot2) was included
exclude rules: ng-1-spot
no nogroups were excluded by the filter
will create a CloudFormation stack for each of 1 nodegroups in cluster "btc-k8s"
1 task: { create nodegroup "ng-1-spot2" }
building nodegroup stack "eksctl-btc-k8s-nodegroup-ng-1-spot2"
deploying stack "eksctl-btc-k8s-nodegroup-ng-1-spot2"
[✖]  unexpected status "CREATE_IN_PROGRESS" while waiting for CloudFormation stack "eksctl-btc-k8s-nodegroup-ng-1-spot2"
[ℹ]  fetching stack events in attempt to troubleshoot the root cause of the failure
[ℹ]  1 error(s) occurred and nodegroups haven't been created properly, you may wish to check CloudFormation console
[ℹ]  to cleanup resources, run 'eksctl delete nodegroup --region=ap-northeast-1 --cluster=btc-k8s --name=<name>' for each of the failed nodegroup
[✖]  waiting for CloudFormation stack "eksctl-btc-k8s-nodegroup-ng-1-spot2" to reach "CREATE_COMPLETE" status: RequestCanceled: waiter context canceled
caused by: context deadline exceeded
[✖]  failed to create nodegroups for cluster "btc-k8s"
```
