### ISSUE TITLE
Support CNI Custom Networking

### ISSUE THREAD

**Issue by lilley2412** [weaveworks/eksctl#1096]
**Why do you want this feature?**

Proposed feature request to support [AWS CNI custom networking](https://docs.aws.amazon.com/eks/latest/userguide/cni-custom-network.html).  There is an existing [WIP PR 786 here](https://github.com/weaveworks/eksctl/pull/786), opening a feature for discussion because I think it's a big lift and implementation approach could greatly vary; I'm using custom CNI extensively to increase VPC IP space for pods on a corporate-connected VPCs and would like to start using eksctl for cluster provisioning.

CNI custom networking supports 3 main use cases:

1. Save IP space in a VPC.  VPC's connected to a corporate network with VPN or DirectConnect often have limited CIDR sizes, and with each pod taking an IP they run out fast.
2. Enable nodes in public subnets with pods in private subnets by externalizing SNAT (disable aws-node SNAT).
3. Run pods in security groups different than nodes.

Custom CNI can be enabled outside of eksctl today, but requires manual intervention after eksctl builds the cluster.

Important Concepts:
- Each node primary ENI is created in a non-pod subnet (i.e. the public or private subnets)
- Node secondary ENI's are created in pod subnets
- The node primary ENI and secondary ENI subnets must be in the same AZ
- Pod ENIs require a security group assignment (it can be same as nodes or different but must be specified)
- Behavior is driven by a ENIConfig CRD that must exist before node registers
- The aws-node daemonset must be patched before node registers to enable the custom CNI feature
- Use of custom CNI custom networking effectively removes IP capacity of 1 ENI from the node; this is because no secondary IP's of the primary ENI are used for pods.  As of today the EKS optimized AMI uses a static file to set max-pods, max-pods must be overriden when custom networking is used to prevent the scheduler from adding pods that cannot get an IP.  See [AWS CNI issue 527](https://github.com/aws/amazon-vpc-cni-k8s/issues/527). 

**What feature/behavior/change do you want?**

I'm proposing limited initial functionality to get the feature enabled for existing VPCs, then add more complex implementations as new features ... I think the lift is big enough that it needs to be split up (maybe I'm wrong, but in my own experience I think most using this feature would also be doing a custom network setup anyway).

- **Support CNI custom networking for pre-existing VPCs** by adding a new ClusterSubnet type "pod":
    ```
    vpc:
    #############################################################
    # existing functionality to specify existing vpc and subnets
    id: "vpc-1"  
    cidr: "10.0.0.0/16"       
    subnets:
        private:
        us-east-1a:
            id: "subnet-1"
            cidr: "10.0.0.0/24"

        us-east-1b:
            id: "subnet-2"
            cidr: "10.0.1.0/24"

        #############################################################
        # new functionality to specify existing pod subnets
        pod:
        us-east-1a:
            id: "subnet-1"
            cidr: "100.64.0.0/16"

        us-east-1b:
            id: "subnet-2"
            cidr: "100.65.0.0/16"

    ``` 
- **Custom CNI networking is enabled either by specifying pod subnets for a pre-existing VPC or by specifying customCniPodCidr for a new VPC (see proposed future enhancements for new VPC use case)**.
- **Config validations**:
  - A pod subnet must exist in each AZ that has a public or private subnet (this is a requirement of ENI allocation, CNI creates a primary ENI in node subnet and secondary ENIs in pod subnets on the same EC2 node, so the AZ's must match).
- **Use ClusterSharedNodeSecurityGroup as the pod SG**, I think this is a reasonable first-version approach.  Adding a dedicated pod SG falls under use case 3, but this would require additional cluster-level configs for attaching pre-existing SG's or creating new POD sg's (not sure there is value in a flag to create a new pods SG, how would the rules different from the shared node sg? Maybe allowing attachment of existing is enough.).
- **Use ENI_CONFIG_LABEL_DEF to auto-apply ENIConfig to nodes**. See "patch the aws-node daemonset" below under implementation notes.  If the auto-apply setting is used, nodeGroups do not need to be labeled, and the setting works for all AZs, but it means all nodeGroups use customNetworking.
  - To configure custom CNI networking per-nodeGroup, ENI_CONFIG_LABEL_DEF cannot be used.  We'd need to add a new flag like `useCustomCniNetworking` to nodeGroup, and **require each nodeGroup be limited to one AZ**, then add a label `k8s.amazonaws.com/eniConfig=<config-name>` that matches the AZ.  I don't think this is a good idea so would opt to stick with ENI_CONFIG_LABEL_DEF, or at least make this a future option.
- **Provide a warning for nodeGroup kubeletExtraConfig max-pods**.  See [AWS CNI issue 527](https://github.com/aws/amazon-vpc-cni-k8s/issues/527). 
  - When CNI custom networking is enabled, nodeGroup kubeletExtraConfig must have --max-pods set to ((#ENI-1)*(IP-per-ENI)) based on instance type.  
  - I'm not aware of any cli or api-based method to determine # of ENI and max IP per ENI programmatically, so my instinct is to not try to handle setting it in eksctl (if we did, I think it would require using a static file ([like this one](https://github.com/awslabs/amazon-eks-ami/blob/master/files/eni-max-pods.txt))).
  - If it's not handled by eksctl, output a warning if --max-pods is not set on a nodeGroup when CNI custom networking is enabled?  Or maybe a hard error?  

*Implementation Notes*

Resources should be created in this order, if nodes register prior to custom CNI being fully configured, node ENIs will immediately get secondary ENIs assigned from non-pod subnets, requiring the nodes (or kubelet process) to be re-started after CNI is configured (or nodeGroup re-creation).

- Create / validate VPC
- Create cluster (includes ClusterSharedNodeSecurityGroup)
- patch the aws-node daemonset:
    ```
        spec:
        containers:
        - env:
            - name: AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG
            value: "true"
            - name: ENI_CONFIG_LABEL_DEF
            value: failure-domain.beta.kubernetes.io/zone
    ```
- Create ENIConfig CRD
    ```s
    apiVersion: apiextensions.k8s.io/v1beta1
    kind: CustomResourceDefinition
    metadata:
    name: eniconfigs.crd.k8s.amazonaws.com
    spec:
    scope: Cluster
    group: crd.k8s.amazonaws.com
    version: v1alpha1
    names:
        plural: eniconfigs
        singular: eniconfig
        kind: ENIConfig
    ```
- Create 1 ENIConfig resource per AZ, using ClusterSharedNodeSecurityGroup, named by the AZ (to support auto-apply using ENI_CONFIG_LABEL_DEF):
    ```
    apiVersion: crd.k8s.amazonaws.com/v1alpha1
    kind: ENIConfig
    metadata: 
    name: <az-name>
    spec: 
    securityGroups: 
        - <ClusterSharedNodeSecurityGroup ID>
    subnet: <pod subnet ID>
    ```

**Proposed Future Enhancements**

- Allow pod sg's that are different than node sg's (requires new config at cluster level).
- Support external SNAT (nodes in public subnets with pods in private subnets) - requires new config setting and further patching of aws-node [see aws docs]([see aws docs](https://docs.aws.amazon.com/eks/latest/userguide/external-snat.html)).
- Support CNI custom networking for new VPCs with a property that defines a custom CNI pod cidr pool. The CIDR can be the same as the VPC or different (if different, can't overlap).  The common setup for use case 1 (in my experience) is to use a private CIDR range to provide large IP capacity for pods:
    ```
    vpc:
        cidr: "10.0.0.0/16"
        customCniPodCidr: "100.64.0.0/10"  # should support sizes greater than /16
        # could also be the same as the VPC as a way to enable custom
        # CNI without adding an addtional boolean flag:
        # customCniPodCidr: "10.0.0.0/16"
    ```
    - For new VPC creation:
      - Determine number of pod subnets (1 for each AZ used for public / private subnets)
      - Divide customCniPodCidr into N CIDRs of no larger than /16 (this is a requirement of VPC secondary CIDR size) and assign secondary CIDRs to VPC

**Comment by tiffanyfay** [comment]
@lilley2412 Great writeup!

Do you think there's any scenario in which someone might want to use public subnets for the pod? I always used private, but when starting to code it previously I was wondering if it should have the option of both or not.
```
    # new functionality to specify existing pod subnets
    pod:
    us-east-1a:
        id: "subnet-1"
        cidr: "100.64.0.0/16"

    us-east-1b:
        id: "subnet-2"
        cidr: "100.65.0.0/16"
```
For `customCniPodCidr` do you think there'd only be one? @errordeveloper and I had discussed having an array of cidrs. I think we need to think about it for eksctl creating subnets too (thus far my code creates them). It would also be more of a future thing, but this way with multiple cidrs, and having a group inside of pod subnets for each CIDR, then different groups can be assigned to different nodegroups. And obviously we only need some things at first, but it does affect the layout of the yaml and it'd be better if it doesn't drastically change.

> Use ClusterSharedNodeSecurityGroup as the pod SG
Agreed

**Comment by lilley2412** [comment]
@tiffanyfay thanks for the feedback

> Do you think there's any scenario in which someone might want to use public subnets for the pod?

I can't think of a good reason use custom CNI with public pod subnets, all the use cases for custom CNI lend themselves to security or saving public/routable IP space, so public pod subnets just don't seem to make sense.  That doesn't mean someone won't want it one day, so I also see no strong reason to prohibit it.  Not sure the cleanest way, maybe simply pod-public and prod-private for subnets?  ex:
```
    # import a public pod subnet
    pod-public:
    us-east-1a:
        id: "subnet-1"
        cidr: "100.64.0.0/16"

    # import a private pod subnet
    pod-private:
    us-east-1b:
        id: "subnet-2"
        cidr: "100.65.0.0/16"
``` 

> For customCniPodCidr do you think there'd only be one? @errordeveloper and I had discussed having an array of cidrs

I think this makes sense, it's more flexible and possibly even less work than I was thinking, if one wanted to use larger than /10 from the 100.64 range they could just add multiple cidrs as /16's or smaller.  I will edit the request to reflect this.

**Comment by tiffanyfay** [comment]
@lilley2412  Yah, I can't think of a case, but who knows...can always handle public later if it's asked for. What do you think in terms of how to specify which set is for which nodegroup?

What we had so far in terms of specifying, in the same naming scheme as yours, is 
```
pod-private:
    group1:
        cidr: (optional)
        us-east-1a:
            id: "subnet-1"
            cidr: "100.64.0.0/16"
    group2:
        cidr: (optional)
        us-east-1a:
            id: "subnet-1"
            cidr: "100.65.0.0/16"
```
This way if `ng1` wants `group1` and `ng2` wants `group2`. 
Then nodegroups would need some sort of designation to which to use.

**Comment by tiffanyfay** [comment]
@lilley2412 For the case when it creates all the subnets and cluster, there's also the case there of we will need to be able to set a worker node CIDR for the case that they want it to be a non-RFC1918.

@Currently running into issues with getting `make` to update my zz_generated.deepcopy.go in the api.

**Comment by lilley2412** [comment]
@tiffanyfay 

> What do you think in terms of how to specify which set is for which nodegroup?

At first I thought this wasn't required because ENIConfig just has to match the AZ of the node.  

Poking around I found https://github.com/weaveworks/eksctl/issues/806 and https://github.com/weaveworks/eksctl/issues/475#issuecomment-498995479 (@errordeveloper indicated this suggestion would be implemented).  If it's implemented this way, I think maybe it makes sense to extend on that config by nesting the pod subnets under the respective node subnets, because a pod subnet is meaningless without a corresponding node subnet.  Something like this .. it would also take care of private / public and any supported combo of IP ranges, and doesn't require re-specifying the AZ to match the node:

```
vpc:
  subnets:
    private:
      data-access-subnet:
         cidr: 10.1.0.0/16
         az: us-east-1a
         pod-subnet:
            cidr: 100.64.0.0/16
      high-level-subnet:
         cidr: 10.2.0.0/16
         az: us-east-1a
         pod-subnet:
            cidr: 100.65.0.0/16
```

This would change how ENIConfig is resolved, since nodes don't have a subnet label already, something like:

- ENI_CONFIG_LABEL_DEF=cni-networking/pod-subnet-id on aws-node daemonset
- name ENIConfig by pod subnet id
- set label cni-networking/pod-subnet-id on nodeGroup creation

This may need to also allow he same pod subnets to be used for two different node subnets, not sure if that is a useful use case though.

**Comment by tiffanyfay** [comment]
@lilley2412 
Also, if you have two node groups and two custom subnet groups then you would need to specify which you want. 

Hmm...This is what I had shared with @errordeveloper and he said something like that and to discuss naming later. 

```
pod-private: #which could just be custom
    group1:
        cidr: (optional)
        us-east-1a:
            id: "subnet-1"
            cidr: "100.64.0.0/16"
    group2:
        cidr: (optional)
        us-east-1a:
            id: "subnet-1"
            cidr: "100.65.0.0/16"
```
And had figured for the nodegroup it would have a field for subnet groups. But then again, this doesn't cover the case of using these for worker node subnets...

It sounds like we need to check with Ilya as to whether he wants it specifically like https://github.com/weaveworks/eksctl/issues/475#issuecomment-498995479, but he is pretty swamped with IAM for pods.

The way you have it seems different. Her way seems to imply each named group is a single subnet. But that has the issue that you covered with if you want to make a group and have them created based on a cidr block. So would it create for every az if only the CIDR is listed. Seems really nested though.

**Comment by lilley2412** [comment]
> Also, if you have two node groups and two custom subnet groups then you would need to specify which you want

For current-state eksctl I only see the ability to specify an AZ list on a nodeGroup, I don't see any way to specify a subnet, so that's why my first reaction is that it doesn't matter, if you can only specify AZ on the nodeGroup, then the node -> AZ -> ENConfig -> subnet association is enough because there is no way to control nodeGroup -> subnet (without doing it in the ASG outside of eksctl).  So I was thinking this is only a concern if some of the other feature requests are getting implemented to add a subnet property to nodeGroup.

However it ends up I personally don't care too much so long as it's clear, so the approach you show is fine I think, but like I said unless I'm missing something I don't see the ng -> subnet association yet.

> Also, are you in any of the slack groups?

I am not, but will take a look to catch up on the discussions.

**Comment by lilley2412** [comment]
@tiffanyfay thinking about this more, I guess the point of what you and @errordeveloper where proposing is even If nodeGroup -> worker subnet is not implemented yet, let's support for pod subnets with this feature?  It probably makes sense to keep them decoupled even if it means two subnet properties on nodeGroup (or refactoring when worker subnets are implemented?)

So think it makes sense 

```
pod-private: #which could just be custom
    group1:
        cidr: (optional)
        us-east-1a:
            id: "subnet-1"
            cidr: "100.64.0.0/16"
    group2:
        cidr: (optional)
        us-east-1a:
            id: "subnet-1"
            cidr: "100.65.0.0/16"
```

+ some way to specify ng -> subnet

So I guess this also means don't use failure zone label for ENIConfig, it would just have to be a node label based on the specified subnet on the ng.
