### ISSUE TITLE
preBootstrapCommands and bootstrapCommand are run synchronously

### ISSUE THREAD

**Issue by Timboo89** [weaveworks/eksctl#1099]
**What is the goal to achieve**
I am trying to give worker nodes a custom pre bootstrapping script which installs a self-signed CA certificate. We need to install the certificate because the nodes (later pods like KIAM) need to be able to communicate with internet (AWS) services like IAM/STS. Because of enterprise security guidelines the worker nodes need to be behind a transparent proxy which's ca certificate the nodes need to trust.

**What happened?**
The pre bootstrapping script got executed, the node can communicate to all internet endpoints the proxy allows without a certificate issue, but the node doesn't register with the cluster (masters) anymore. `kubectl get nodes` just tells "No resources found."
```
# cluster.yaml
--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: PoC
  region: eu-central-1
vpc:
  id: "vpc-xxx" 
  subnets:
    private:
      eu-central-1a:
        id: "subnet-xxx"
      eu-central-1b:
        id: "subnet-xxx"
      eu-central-1c:
        id: "subnet-xxx"
nodeGroups:
  - name: private-nodes
    instanceType: m5.large
    desiredCapacity: 1
    privateNetworking: true
    securityGroups: 
      withShared: true
      withLocal: true
      AttachIDs: ["sg-xxx"]
    minSize: 1
    maxSize: 8
    volumeSize: 100
    volumeType: gp2
    volumeEncrypted: true
    ssh: # import public key from file
      publicKeyPath: ./keys/id_rsa.pub
    iam:
      withAddonPolicies:
        ebs: true
        autoScaler: true
    preBootstrapCommands:
      - sudo yum install ca-certificates -y
      - sudo update-ca-trust force-enable
      - echo -n "<base64Cert>" | base64 --decode > tmp.crt
      - chmod 644 tmp.crt
      - sudo mv tmp.crt /etc/pki/ca-trust/source/anchors/corp_proxy.crt
      - sudo update-ca-trust extract
```

**How to reproduce it?**
Insert Security Groups, Subnets and VPC in the config above and run `eksctl create cluster -f cluster.yaml`

**Anything else we need to know?**
Commands on the node:
```
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
$ ls -Al /etc/kubernetes/manifests/
insgesamt 0
$ sudo ls -Al /etc/cni
ls:  /etc/cni: No such file or directory
```

**Versions**
eksctl: `[ℹ]  version.Info {BuiltAt:"", GitCommit:"", GitTag:"0.2.1"}`
kubectl: 
```Client Version: version.Info {Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T14:25:20Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info {Major:"1", Minor:"13+", GitVersion:"v1.13.8-eks-a977ba", GitCommit:"a977bab148535ec195f12edc8720913c7b943f9c", GitTreeState:"clean", BuildDate:"2019-07-29T20:47:04Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**
[on the node] 
```journalctl -f -u kubelet
Aug 06 07:42:57 ip-100-64-2-35.xxx  kubelet[3560]: E0806 07:42:57.496249    3560 kubelet.go:2266] node "ip-100-64-2-35.eu-central-1.compute.internal" not found
Aug 06 07:42:57 ip-100-64-2-35.xxx  kubelet[3560]: W0806 07:42:57.556434    3560 cni.go:203] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 06 07:42:57 ip-100-64-2-35.xxx  kubelet[3560]: E0806 07:42:57.556563    3560 kubelet.go:2192] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 06 07:42:57 ip-100-64-2-35.xxx  kubelet[3560]: E0806 07:42:57.596381    3560 kubelet.go:2266] node "ip-100-64-2-35.eu-central-1.compute.internal" not found
Aug 06 07:42:57 ip-100-64-2-35.xxx  kubelet[3560]: E0806 07:42:57.614647    3560 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:444:  Failed to list *v1.Service: Unauthorized
Aug 06 07:42:57 ip-100-64-2-35.xxx  kubelet[3560]: E0806 07:42:57.660203    3560 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:453:  Failed to list *v1.Node: Unauthorized
Aug 06 07:42:57 ip-100-64-2-35.xxx  kubelet[3560]: E0806 07:42:57.696509    3560 kubelet.go:2266] node "ip-100-64-2-35.eu-central-1.compute.internal" not found
Aug 06 07:42:57 ip-100-64-2-35.xxx  kubelet[3560]: E0806 07:42:57.796621    3560 kubelet.go:2266] node "ip-100-64-2-35.eu-central-1.compute.internal" not found
Aug 06 07:42:57 ip-100-64-2-35.xxx  kubelet[3560]: E0806 07:42:57.896746    3560 kubelet.go:2266] node "ip-100-64-2-35.eu-central-1.compute.internal" not found
Aug 06 07:42:57 ip-100-64-2-35.xxx  kubelet[3560]: E0806 07:42:57.947983    3560 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47:  Failed to list *v1.Pod: Unauthorized
```

**Comment by Timboo89** [comment]
Just for completenes, I saw this issue: https://github.com/weaveworks/eksctl/issues/784
But didn't see this as the same issue, as because my commands did take effect, but the proBootstrapCommands destroy something else apparently.

**Comment by whereisaaron** [comment]
@Timboo89 your errors are similar to this report, but it could just be two different ways to break network bootstrapping 😄 
Ref: https://github.com/awslabs/amazon-eks-ami/issues/306

**Comment by Timboo89** [comment]
@whereisaaron you appear to be right, I found some way to break network bootstrapping and maybe even bootstrapping the credentials share. Just for testing, I started the same cluster without preBootstrapCommands in subnets with "direct" natted internet access (cluster.yaml below) and am getting the same picture. "No resources found."

On the other hand, when I create the cluster without preBootstrapCommands in the subnets with filtered internet access nodes are joining the cluster, but staying in NotReady.

**Summary:**
A) Filtered internet without preBootstrapCommands = no internet => Nodes stay on "NotReady" but join the cluster.
B) Filtered internet + preBootstrapCommands = internet => Nodes don't join cluster "No resources found."
C) NAT internet without preBootstrapCommands = internet => Nodes don't join the cluster "No resources found."

**cluster.yaml of A anf C**
```
# An advanced example of ClusterConfig object with customised nodegroups:
--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: testcluster
  region: eu-central-1
vpc:
  id: "vpc-xxx" 
  subnets:
    private:
      eu-central-1a:
        id: "subnet-xxx"
      eu-central-1b:
        id: "subnet-xxx"
      eu-central-1c:
        id: "subnet-xxx"
nodeGroups:
  - name: private-nodes
    instanceType: m5.large
    desiredCapacity: 1
    privateNetworking: true
    securityGroups: 
      withShared: true
      withLocal: true
      AttachIDs: ["sg-xxx"]
    minSize: 1
    maxSize: 8
    volumeSize: 100
    volumeType: gp2
    volumeEncrypted: true
    ssh: # import public key from file
      publicKeyPath: ./keys/id_rsa.pub
    iam:
      withAddonPolicies:
        ebs: true
        autoScaler: true
```

journatctl -u kubelet:
```
Aug 07 04:02:13 ip-100-64-1-170.coms-dev.aws.de.pri.o2.com kubelet[3548]: E0807 04:02:13.775958    3548 eviction_manager.go:247] eviction manager: failed to get summary stats: failed to get node info: node "ip-100-64-1-170.eu-central-1.compute.internal" not found
Aug 07 04:02:13 ip-100-64-1-170.coms-dev.aws.de.pri.o2.com kubelet[3548]: W0807 04:02:13.806991    3548 cni.go:203] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 07 04:02:13 ip-100-64-1-170.coms-dev.aws.de.pri.o2.com kubelet[3548]: E0807 04:02:13.807105    3548 kubelet.go:2192] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 07 04:02:14 ip-100-64-1-170.coms-dev.aws.de.pri.o2.com kubelet[3548]: E0807 04:02:14.471602    3548 kubelet_node_status.go:94] Unable to register node "ip-100-64-1-170.eu-central-1.compute.internal" with API server: Unauthorized
Aug 07 04:02:17 ip-100-64-1-170.coms-dev.aws.de.pri.o2.com kubelet[3548]: E0807 04:02:17.212388    3548 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:444: Failed to list *v1.Service: Unauthorized
Aug 07 04:02:17 ip-100-64-1-170.coms-dev.aws.de.pri.o2.com kubelet[3548]: E0807 04:02:17.212425    3548 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Unauthorized
Aug 07 04:02:17 ip-100-64-1-170.coms-dev.aws.de.pri.o2.com kubelet[3548]: E0807 04:02:17.387443    3548 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:453: Failed to list *v1.Node: Unauthorized
```

**Comment by Timboo89** [comment]
What I am just wondering. Might the VPC CIDR be the problem? I have to use the 100.64.x addresses. Is EKS using these by default as well? If so: How to change them?
The only information that could be related to that, I find in the [schema description](https://eksctl.io/usage/schema/). But that doesn't tell me much. What does the CIDR object look like? The reference leads nowhere.

```
Network:
  additionalProperties: false
  properties:
    cidr:
      $ref: '#/definitions/IPNet'
      $schema: http://json-schema.org/draft-04/schema#
    id:
      type: string
  type: object
```

**Comment by Timboo89** [comment]
@whereisaaron @gemagomez 
Okay, I found something extremely awkward while testing. For terminating one possible problem source I started testing in subnets with "direct" internet access via AWS managed NAT.

The nodes could not join with THESE two config files:
**With(out) preBootstrapCommands**
```diff
--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: test-eks
  region: eu-central-1
vpc:
  id: "vpc-xxx" 
  subnets:
    private:
      eu-central-1a:
        id: "subnet-xxx"
      eu-central-1b:
        id: "subnet-xxx"
      eu-central-1c:
        id: "subnet-xxx"
nodeGroups:
  - name: private-nodes
    instanceType: m5.large
    desiredCapacity: 1
    privateNetworking: true
    securityGroups: 
      withShared: true
      withLocal: true
      AttachIDs: ["sg-xxx"]
    minSize: 1
    maxSize: 8
    volumeSize: 100
    volumeType: gp2
    volumeEncrypted: true
    ssh: # import public key from file
      publicKeyPath: ./keys/id_rsa.pub
    iam:
      withAddonPolicies:
        ebs: true
        autoScaler: true
+    preBootstrapCommands:
+      - sudo yum install ca-certificates -y
+      - sudo update-ca-trust force-enable
+      - echo -n "<b64cert>" | base64 --decode > tmp.crt
+      - chmod 644 tmp.crt
+      - sudo mv tmp.crt /etc/pki/ca-trust/source/anchors/squid.crt
+      - sudo update-ca-trust extract
```

So I started throwing all out of the config, that was not required for the cluster to start. Also throwing out `privateNetworking: true`, what was not a good idea, as not even the CloudFormation template could finish without it. Funny thing.
Anyway I put it back at a different position, I found more fitting than the old position, as I thought "`desiredCapacity`, `minSize`, `maxSize` should be in one block, for better reading". And the cluster could start. WOW! The config was looking like this now:
**Cluster starts with changed position for `privateNetworking`**
```diff
--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: test-eks
  region: eu-central-1
vpc:
  id: "vpc-xxx" 
  subnets:
    private:
      eu-central-1a:
        id: "subnet-xxx"
      eu-central-1b:
        id: "subnet-xxx"
      eu-central-1c:
        id: "subnet-xxx"
nodeGroups:
  - name: private-nodes
    instanceType: m5.large
+    privateNetworking: true
    desiredCapacity: 1
-    privateNetworking: true
    minSize: 1
    maxSize: 8
    volumeSize: 100
    volumeType: gp2
    ssh: # import public key from file
      publicKeyPath: ./keys/id_rsa.pub
    iam:
      withAddonPolicies:
        ebs: true
        autoScaler: true
```
Than I thought... No way in hell... is it the `volumeEncrypted` option?! So I added it. No, still all working. Cluster started, Node got Ready. So now I was thinking about things I wouldn't want to believe, so I tested it. I put back `privateNetworking` where it was before like this:
**privateNetworking between autoscaling config**
```diff
--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: test-eks
  region: eu-central-1
vpc:
  id: "vpc-xxx" 
  subnets:
    private:
      eu-central-1a:
        id: "subnet-xxx"
      eu-central-1b:
        id: "subnet-xxx"
      eu-central-1c:
        id: "subnet-xxx"
nodeGroups:
  - name: private-nodes
    instanceType: m5.large
    desiredCapacity: 1
!    privateNetworking: true
    minSize: 1
    maxSize: 8
    volumeSize: 100
    volumeType: gp2
    volumeEncrypted: true
    ssh: # import public key from file
      publicKeyPath: ./keys/id_rsa.pub
    iam:
      withAddonPolicies:
        ebs: true
        autoScaler: true
``` 
You wanna guess? **The nodes cannot join the cluster** In other words: The position of an option is breaking eksctl?!

Okay than, I went further to reach my goal and added the other options again like this:
**With all options unsorted**
```
--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: test-eks
  region: eu-central-1
vpc:
  id: "vpc-xxx" 
  subnets:
    private:
      eu-central-1a:
        id: "subnet-xxx"
      eu-central-1b:
        id: "subnet-xxx"
      eu-central-1c:
        id: "subnet-xxx"
nodeGroups:
  - name: private-nodes
    instanceType: m5.large
    privateNetworking: true
    desiredCapacity: 1
    minSize: 1
    maxSize: 8
    securityGroups: 
      withShared: true
      withLocal: true
      AttachIDs: ["sg-xxx"]
    volumeSize: 100
    volumeType: gp2
    volumeEncrypted: true
    ssh: # import public key from file
      publicKeyPath: ./keys/id_rsa.pub
    iam:
      withAddonPolicies:
        ebs: true
        autoScaler: true
    preBootstrapCommands:
      - sudo yum install ca-certificates -y
      - sudo update-ca-trust force-enable
      - echo -n "<b64cert>" | base64 --decode > tmp.crt
      - chmod 644 tmp.crt
      - sudo mv tmp.crt /etc/pki/ca-trust/source/anchors/squid.crt
      - sudo update-ca-trust extract
```
As you can imagine by now: The nodes did not join the cluster.... (but the preBootstrapCommands were executed at least.)
So I resorted again, leaning a bit on the [schema](https://eksctl.io/usage/schema/). 
**Resorted config along schema**
```diff
--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: test-eks
  region: eu-central-1
vpc:
  id: "vpc-xxx" 
  subnets:
    private:
      eu-central-1a:
        id: "subnet-xxx"
      eu-central-1b:
        id: "subnet-xxx"
      eu-central-1c:
        id: "subnet-xxx"
nodeGroups:
  - name: private-nodes
    instanceType: m5.large
-    privateNetworking: true
    desiredCapacity: 1
    minSize: 1
    maxSize: 8
    securityGroups: 
      withShared: true
      withLocal: true
      AttachIDs: ["sg-xxx"]
-    volumeSize: 100
-    volumeType: gp2
-    volumeEncrypted: true
    ssh: # import public key from file
      publicKeyPath: ./keys/id_rsa.pub
    iam:
      withAddonPolicies:
        ebs: true
        autoScaler: true
    preBootstrapCommands:
      - sudo yum install ca-certificates -y
      - sudo update-ca-trust force-enable
      - echo -n "<b64cert>" | base64 --decode > tmp.crt
      - chmod 644 tmp.crt
      - sudo mv tmp.crt /etc/pki/ca-trust/source/anchors/squid.crt
      - sudo update-ca-trust extract
+    privateNetworking: true
+    volumeSize: 100
+    volumeType: gp2
+    volumeEncrypted: true
```
To my very surprise the node was able to join the freaking cluster by just reordering the options in the config. It's the very same config as the first, just reordered.

So, I was going ahead putting it back into the subnets behind the proxy. Unfortunately again I am getting this error by ECR being available over a VPC Endpoint (so no proxy in between):
```
Aug 08 05:06:01 ip-100-64-2-140.coms-dev.aws.de.pri.o2.com kubelet[3559]: E0808 05:06:01.480150    3559 pod_workers.go:190] Error syncing pod 22c2a077-b999-11e9-b492-02028ac68600 ("kube-proxy-d9mt8_kube-system(22c2a077-b999-11e9-b492-02028ac68600)"), skipping: failed to "CreatePodSandbox" for "kube-proxy-d9mt8_kube-system(22c2a077-b999-11e9-b492-02028ac68600)" with CreatePodSandboxError: "CreatePodSandbox for pod \"kube-proxy-d9mt8_kube-system(22c2a077-b999-11e9-b492-02028ac68600)\" failed: rpc error: code = Unknown desc = Error response from daemon: Get https://602401143452.dkr.ecr.eu-central-1.amazonaws.com/v2/eks/pause-amd64/manifests/3.1: no basic auth credentials"
```

Any clues? 
I will do another test by reordering everything strictly by the schema, but in this case I don't think it'll help. Well,... I wouldn't have imagined it to help in the first place, so let's see.

**Comment by Timboo89** [comment]
Unfortunately resorting 100% like the schema didn't work in this case. I would be very open for any suggestions, why the node does have the issue `Aug 08 05:06:01 ip-100-64-2-140.coms-dev.aws.de.pri.o2.com kubelet[3559]: E0808 05:06:01.480150    3559 pod_workers.go:190] Error syncing pod 22c2a077-b999-11e9-b492-02028ac68600 ("kube-proxy-d9mt8_kube-system(22c2a077-b999-11e9-b492-02028ac68600)"), skipping: failed to "CreatePodSandbox" for "kube-proxy-d9mt8_kube-system(22c2a077-b999-11e9-b492-02028ac68600)" with CreatePodSandboxError: "CreatePodSandbox for pod \"kube-proxy-d9mt8_kube-system(22c2a077-b999-11e9-b492-02028ac68600)\" failed: rpc error: code = Unknown desc = Error response from daemon: Get https://602401143452.dkr.ecr.eu-central-1.amazonaws.com/v2/eks/pause-amd64/manifests/3.1: no basic auth credentials"`

**Comment by Timboo89** [comment]
[Uploading logs.txt…](journalctl -u kubelet)

**Comment by Timboo89** [comment]
[journalctl -u kubelet](https://github.com/weaveworks/eksctl/files/3480336/logs.txt)

**Comment by Timboo89** [comment]
Well... that sounds unhealthy:
```

Aug 08 06:59:41 ip-100-64-2-146.local kubelet[3583]: E0808 06:59:41.844970    3583 aws_credentials.go:194] while requesting ECR authorization token RequestError: send request failed
Aug 08 06:59:41 ip-100-64-2-146.local kubelet[3583]: caused by: Post https://api.ecr.eu-central-1.amazonaws.com/: x509: certificate signed by unknown authority
```
I cannot even find `aws_credentials.go` in your repository :-/ 
Anyway. Might it be that kubelet is started BEFORE the bootstrap script is being run? Because, when I curl the endpoint https://api.ecr.eu-central-1.amazonaws.com/ from the node (with the certficate installed) I don't get this error. While I do get the error, when the certificate is NOT installed.

**Comment by errordeveloper** [comment]
Question: why do you need certificates on the nodes and not in a container image of your apps, or in a configmap that you can mount in any pod where you don't control the image?

**Comment by Timboo89** [comment]
Because by security compliance of our company we have to filter all outgoing internet traffic through a central squid proxy, which allows certain endpoints (for example that we don't do bitmining on the ec2 instances). This happens on a route table basis. Hence, all requests not vpc internally are routed and filtered by this proxy which has a self signed ca certificate. When kubelet starts it tries to communicate to the ECR API which is not routable via a vpc endpoint and on the whitelist of the proxy, but kubelet does not know the certificate.

Wouldn't kubelet need that, I guess we could also just install the cert in each container.

**Comment by Timboo89** [comment]
I've just did a test. This is my current preBootstrapScript:
```
      - echo "Timos Testing starts"
      - systemctl is-active --quiet kubelet; if [ "$?" -eq "0" ]; then echo "Timo - kubelet is running before preBootstrapCommands"; else echo "Timo - kubelet is not running before preBootstrapCommands"; fi
      - sudo yum install ca-certificates -y
      - sudo update-ca-trust force-enable
      - echo -n "<b64cert>" | base64 --decode > tmp.crt
      - chmod 644 tmp.crt
      - sudo mv tmp.crt /etc/pki/ca-trust/source/anchors/tetra.crt
      - sudo update-ca-trust extract
      - systemctl is-active --quiet kubelet; if [ "$?" -eq "0" ]; then echo "Timo - kubelet is running between preBootstrapCommands"; else echo "Timo - kubelet is not running between preBootstrapCommands"; fi
      - echo "Timos Testing ends"
```

And here is the cloud-init-output.log:
```diff
Cloud-init v. 18.2-72.amzn2.0.7 running 'init-local' at Thu, 08 Aug 2019 14:10:31 +0000. Up 10.44 seconds.
Cloud-init v. 18.2-72.amzn2.0.7 running 'init' at Thu, 08 Aug 2019 14:10:33 +0000. Up 12.50 seconds.
ci-info: +++++++++++++++++++++++++++++++++++++++Net device info++++++++++++++++++++++++++++++++++++++++
ci-info: +--------+------+-----------------------------+-----------------+--------+-------------------+
ci-info: | Device |  Up  |           Address           |       Mask      | Scope  |     Hw-Address    |
ci-info: +--------+------+-----------------------------+-----------------+--------+-------------------+
ci-info: |  eth0  | True |         100.64.3.11         | 255.255.255.128 | global | 0a:d8:38:88:34:94 |
ci-info: |  eth0  | True | fe80::8d8:38ff:fe88:3494/64 |        .        |  link  | 0a:d8:38:88:34:94 |
ci-info: |   lo   | True |          127.0.0.1          |    255.0.0.0    |  host  |         .         |
ci-info: |   lo   | True |           ::1/128           |        .        |  host  |         .         |
ci-info: +--------+------+-----------------------------+-----------------+--------+-------------------+
ci-info: +++++++++++++++++++++++++++++++Route IPv4 info++++++++++++++++++++++++++++++++
ci-info: +-------+-----------------+------------+-----------------+-----------+-------+
ci-info: | Route |   Destination   |  Gateway   |     Genmask     | Interface | Flags |
ci-info: +-------+-----------------+------------+-----------------+-----------+-------+
ci-info: |   0   |     0.0.0.0     | 100.64.3.1 |     0.0.0.0     |    eth0   |   UG  |
ci-info: |   1   |    100.64.3.0   |  0.0.0.0   | 255.255.255.128 |    eth0   |   U   |
ci-info: |   2   | 169.254.169.254 |  0.0.0.0   | 255.255.255.255 |    eth0   |   UH  |
ci-info: +-------+-----------------+------------+-----------------+-----------+-------+
ci-info: +++++++++++++++++++Route IPv6 info+++++++++++++++++++
ci-info: +-------+-------------+---------+-----------+-------+
ci-info: | Route | Destination | Gateway | Interface | Flags |
ci-info: +-------+-------------+---------+-----------+-------+
ci-info: |   9   |  fe80::/64  |    ::   |    eth0   |   U   |
ci-info: |   11  |    local    |    ::   |    eth0   |   U   |
ci-info: |   12  |   ff00::/8  |    ::   |    eth0   |   U   |
ci-info: +-------+-------------+---------+-----------+-------+
Cloud-init v. 18.2-72.amzn2.0.7 running 'modules:config' at Thu, 08 Aug 2019 14:10:35 +0000. Up 14.29 seconds.
Loaded plugins: priorities, update-motd
 --> curl-7.61.1-11.amzn2.0.2.x86_64 from amzn2-core removed (updateinfo)
 --> curl-7.61.1-9.amzn2.0.1.x86_64 from installed removed (updateinfo)
 --> docker-18.06.1ce-8.amzn2.x86_64 from @amzn2extra-docker removed (updateinfo)
 --> docker-18.06.1ce-10.amzn2.x86_64 from amzn2extra-docker removed (updateinfo)
 --> libcurl-7.61.1-9.amzn2.0.1.x86_64 from installed removed (updateinfo)
 --> libcurl-7.61.1-11.amzn2.0.2.x86_64 from amzn2-core removed (updateinfo)
No packages needed for security; 3 packages available
Resolving Dependencies
Cloud-init v. 18.2-72.amzn2.0.7 running 'modules:final' at Thu, 08 Aug 2019 14:10:39 +0000. Up 18.32 seconds.
Created symlink from /etc/systemd/system/multi-user.target.wants/kubelet.service to /etc/systemd/system/kubelet.service.
+Timos Testwelt starts
+Timo - kubelet is running before preBootstrapCommands
Loaded plugins: priorities, update-motd
Existing lock /var/run/yum.pid: another copy is running as pid 3278.
Another app is currently holding the yum lock; waiting for it to exit...
  The other application is: yum
    Memory : 100 M RSS (315 MB VSZ)
    Started: Thu Aug  8 14:10:36 2019 - 00:06 ago
    State  : Running, pid: 3278
Package ca-certificates-2018.2.22-70.0.amzn2.noarch already installed and latest version
Nothing to do
+Timo - kubelet is running between preBootstrapCommands
+Timos Testwelt ends
Cloud-init v. 18.2-72.amzn2.0.7 finished at Thu, 08 Aug 2019 14:10:45 +0000. Datasource DataSourceEc2.  Up 24.31 seconds
```

proving that kubelet is running before preBootstrapCommands

**Comment by errordeveloper** [comment]
@Timboo89 could you please confirm whether this log was from first boot of that particular EC2 instance?

**Comment by errordeveloper** [comment]
To be clear, `eksctl` wouldn't function correctly if `kubelet` was running throughout bootstrap process, we must explicitly start it, so that it uses correct flags and environment variables that we enforce. In theory it's possible for it to be running prior to our bootstrap script, but I doubt it is the case.

https://github.com/weaveworks/eksctl/blob/9a9391f9ad84efa5161ff9c280e537905c4d1fe9/pkg/nodebootstrap/assets/bootstrap.al2.sh#L29-L31

If you inspect the cloud-init config, you should see that your `preBootstrapCommands` come before the bootstrap script, and we have tests that ensure this behaviour doesn't break.

https://github.com/weaveworks/eksctl/blob/9a9391f9ad84efa5161ff9c280e537905c4d1fe9/pkg/cfn/builder/api_test.go#L1694-L1700

**Comment by errordeveloper** [comment]
@Timboo89 I think it's possible kubelet is just not picking up your CA certificate somehow, did you try getting it to work manually on a node? What would it take to make it work on the node that you just logged in to? (I am guessing you might need to pass some flags, or possibly replace `/etc/eksctl/ca.crt` with your certificate, do take a look in `/etc/eksctl` in general, that's where kubelet configs live, you will need to restart kubelet everytime you change something there; there is also systemd dorp-in unit that you might want to inspect - `/etc/systemd/system/kubelet.service.d/10-eksclt.al2.conf`).

**Comment by Timboo89** [comment]
> @Timboo89 could you please confirm whether this log was from first boot of that particular EC2 instance?

Yes, it was the very first boot.

**Comment by Timboo89** [comment]
So this is interesting! The test below is showing, that 
A: The BootstrapCommand is running AFTER the preBootstrapCommands
B: That still the BootstrapCommand somehow starts kubelet before executing the preBootstrapCommands, as you can see, kubelet does not run during the preBootstrapCommands.

**cluster.yaml**
```
--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-overwrite
  region: eu-central-1
vpc:
  id: "vpc-xxx" 
  subnets:
    private:
      eu-central-1a:
        id: "subnet-xxx"
      eu-central-1b:
        id: "subnet-xxx"
      eu-central-1c:
        id: "subnet-xxx"
nodeGroups:
  - desiredCapacity: 1
    iam:
      withAddonPolicies:
        ebs: true
        autoScaler: true
    instanceType: m5.large
    maxSize: 8
    minSize: 1
    name: private-nodes-overwrite
    overrideBootstrapCommand: 'echo "Timo - OwnBootstrap"; systemctl is-active --quiet kubelet; if [ "$?" -eq "0" ]; then echo "Timo - kubelet is running before preBootstrapCommands"; else echo "Timo - kubelet is not running before preBootstrapCommands"; fi; echo "Timo - OwnBootstrap end"'
    preBootstrapCommands:
      - echo "Timos Testwelt starts"
      - systemctl is-active --quiet kubelet; if [ "$?" -eq "0" ]; then echo "Timo - kubelet is running before preBootstrapCommands"; else echo "Timo - kubelet is not running before preBootstrapCommands"; fi
      - sudo yum install ca-certificates -y
      - sudo update-ca-trust force-enable
      - echo -n "<b64cert>" | base64 --decode > tmp.crt
      - chmod 644 tmp.crt
      - sudo mv tmp.crt /etc/pki/ca-trust/source/anchors/tetra.crt
      - sudo update-ca-trust extract
      - systemctl is-active --quiet kubelet; if [ "$?" -eq "0" ]; then echo "Timo - kubelet is running between preBootstrapCommands"; else echo "Timo - kubelet is not running between preBootstrapCommands"; fi
      - echo "Timos Testwelt ends"
    privateNetworking: true
    securityGroups: 
      withShared: true
      withLocal: true
      AttachIDs: ["sg-xxx"]
    ssh: # import public key from file
      publicKeyPath: ./keys/id_rsa.pub
    volumeEncrypted: true
    volumeSize: 100
    volumeType: gp2
```

**cloud-init-output.log**
Yellow being BootstrapCommand
Green being preBootstrapCommand
```diff
Cloud-init v. 18.2-72.amzn2.0.7 running 'init-local' at Thu, 08 Aug 2019 17:53:00 +0000. Up 7.44 seconds.
Cloud-init v. 18.2-72.amzn2.0.7 running 'init' at Thu, 08 Aug 2019 17:53:03 +0000. Up 9.63 seconds.
ci-info: +++++++++++++++++++++++++++++++++++++++Net device info++++++++++++++++++++++++++++++++++++++++
ci-info: +--------+------+-----------------------------+-----------------+--------+-------------------+
ci-info: | Device |  Up  |           Address           |       Mask      | Scope  |     Hw-Address    |
ci-info: +--------+------+-----------------------------+-----------------+--------+-------------------+
ci-info: |  eth0  | True |         100.64.2.165        | 255.255.255.128 | global | 06:73:93:3e:c9:78 |
ci-info: |  eth0  | True | fe80::473:93ff:fe3e:c978/64 |        .        |  link  | 06:73:93:3e:c9:78 |
ci-info: |   lo   | True |          127.0.0.1          |    255.0.0.0    |  host  |         .         |
ci-info: |   lo   | True |           ::1/128           |        .        |  host  |         .         |
ci-info: +--------+------+-----------------------------+-----------------+--------+-------------------+
ci-info: ++++++++++++++++++++++++++++++++Route IPv4 info+++++++++++++++++++++++++++++++++
ci-info: +-------+-----------------+--------------+-----------------+-----------+-------+
ci-info: | Route |   Destination   |   Gateway    |     Genmask     | Interface | Flags |
ci-info: +-------+-----------------+--------------+-----------------+-----------+-------+
ci-info: |   0   |     0.0.0.0     | 100.64.2.129 |     0.0.0.0     |    eth0   |   UG  |
ci-info: |   1   |   100.64.2.128  |   0.0.0.0    | 255.255.255.128 |    eth0   |   U   |
ci-info: |   2   | 169.254.169.254 |   0.0.0.0    | 255.255.255.255 |    eth0   |   UH  |
ci-info: +-------+-----------------+--------------+-----------------+-----------+-------+
ci-info: +++++++++++++++++++Route IPv6 info+++++++++++++++++++
ci-info: +-------+-------------+---------+-----------+-------+
ci-info: | Route | Destination | Gateway | Interface | Flags |
ci-info: +-------+-------------+---------+-----------+-------+
ci-info: |   9   |  fe80::/64  |    ::   |    eth0   |   U   |
ci-info: |   11  |    local    |    ::   |    eth0   |   U   |
ci-info: |   12  |   ff00::/8  |    ::   |    eth0   |   U   |
ci-info: +-------+-------------+---------+-----------+-------+
Cloud-init v. 18.2-72.amzn2.0.7 running 'modules:config' at Thu, 08 Aug 2019 17:53:04 +0000. Up 10.83 seconds.
Loaded plugins: priorities, update-motd
Existing lock /var/run/yum.pid: another copy is running as pid 3310.
Another app is currently holding the yum lock; waiting for it to exit...
  The other application is: yum
    Memory :  30 M RSS (319 MB VSZ)
    Started: Thu Aug  8 17:53:04 2019 - 00:00 ago
    State  : Sleeping, pid: 3310
Another app is currently holding the yum lock; waiting for it to exit...
  The other application is: yum
    Memory :  78 M RSS (367 MB VSZ)
    Started: Thu Aug  8 17:53:04 2019 - 00:02 ago
    State  : Running, pid: 3310
 --> curl-7.61.1-11.amzn2.0.2.x86_64 from amzn2-core removed (updateinfo)
 --> curl-7.61.1-9.amzn2.0.1.x86_64 from installed removed (updateinfo)
 --> docker-18.06.1ce-8.amzn2.x86_64 from @amzn2extra-docker removed (updateinfo)
 --> docker-18.06.1ce-10.amzn2.x86_64 from amzn2extra-docker removed (updateinfo)
 --> libcurl-7.61.1-9.amzn2.0.1.x86_64 from installed removed (updateinfo)
 --> libcurl-7.61.1-11.amzn2.0.2.x86_64 from amzn2-core removed (updateinfo)
No packages needed for security; 3 packages available
Resolving Dependencies
Cloud-init v. 18.2-72.amzn2.0.7 running 'modules:final' at Thu, 08 Aug 2019 17:53:09 +0000. Up 16.00 seconds.
+Timos Testwelt starts
+Timo - kubelet is not running before preBootstrapCommands
+Loaded plugins: priorities, update-motd
+Package ca-certificates-2018.2.22-70.0.amzn2.noarch already installed and latest version
+Nothing to do
+Timo - kubelet is not running between preBootstrapCommands
+Timos Testwelt ends
!Timo - OwnBootstrap
!Timo - kubelet is not running before preBootstrapCommands
!Timo - OwnBootstrap end
Cloud-init v. 18.2-72.amzn2.0.7 finished at Thu, 08 Aug 2019 17:53:10 +0000. Datasource DataSourceEc2.  Up 17.27 seconds
```

What the hell?! This I do not understand 🤔
