### ISSUE TITLE
Yaml anchors in config file

### ISSUE THREAD

**Issue by eritikass** [weaveworks/eksctl#1104]
**Why do you want this feature?**

eksctl config is written in YAML file and using YAML anchors it would be a really nice way to avoid repeating configs. 

**What feature/behavior/change do you want?**

while go yaml yaml parser supports that out of box, it can't be used here due very strict validation.

```yml
# example anchor to share similar node groups settings

x-node-shared: &node-shared
  privateNetworking: true
  ssh:
    allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key

nodeGroups:
  - name: ng-1
    <<: *node-shared
    instanceType: t3.medium
    desiredCapacity: 1
  - name: ng-2
    <<: *node-shared
    instanceType: t3.small
    desiredCapacity: 2
    maxSize: 3
    minSize: 1
```

however it is not possilbe - as when try to use this config file with eksctl error will come

```
[✖]  loading config file "cluster.yaml": error unmarshaling JSON: while decoding JSON: json: unknown field "x-node-shared"
```

**Comment by errordeveloper** [comment]
This looks like a limitation of the parser, and I'm afraid there is not much we can do about this at present. However, we will keep this open and hopefully look into it eventually. In the meantime, I'd recommend looking into [jk](https://jkcfg.github.io/), which allows even greater configuration reusability.

**Comment by errordeveloper** [comment]
I take it back. We could consider disabling strict parsing with a flag, but there will need to be another reason to do it, and I cannot think of one right now.

**Comment by lwimmer** [comment]
You can actually achieve this already like this:
```yaml
nodeGroups:
  - <<: &node-shared
      privateNetworking: true
      ssh:
        allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
    name: ng-1
    instanceType: t3.medium
    desiredCapacity: 1
  - name: ng-2
    <<: *node-shared
    instanceType: t3.small
    desiredCapacity: 2
    maxSize: 3
    minSize: 1
```
It's possible to define your shared object directly in the merge key, therefore there is no need for the illegal `x-node-shared` key.
