### ISSUE TITLE
Support for Fn::ImportValue or reference value from existing CloudFormation stack in the cluster config file

### ISSUE THREAD

**Issue by neelakansha85** [weaveworks/eksctl#1141]
**Why do you want this feature?**
eksctl allows us to specify an existing VPC in the config file, however its values need to be statically assigned and can not be referenced dynamically from another CloudFormation stack which manages VPC and output's all required values. This will help allowing manage network and other VPC related resources in a separate network stack without having to manually change the static values when their value changes or need to use similar config files for multiple AWS Accounts. This helps create cross-stack reference that CloudFormation already supports.  

**What feature/behavior/change do you want?**
Support for using `Fn::ImportValue` function or similar templating options to allow passing values to it in underlying CloudFormation template. Something like few options below:
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-eks-1
  region: us-east-1

vpc: 
  id: 
    Fn::ImportValue: "test-network-stack-us-east-1-vpc-VPCID"
  cidr: !ImportValue "test-network-stack-us-east-1-vpc-VPCCIDR"
  subnets:
    private:
      us-east-1a:
        id: 
          Fn::ImportValue: "test-network-stack-us-east-1-vpc-PrivateSubnet1ID"
        cidr: !ImportValue: "test-network-stack-us-east-1-vpc-PrivateSubnet1CIDR"
      us-east-1b:
        id:
          Fn::ImportValue: "test-network-stack-us-east-1-vpc-PrivateSubnet2ID"
        cidr: !ImportValue: "test-network-stack-us-east-1-vpc-PrivateSubnet2CIDR"
```
