### ISSUE TITLE
Single Region & Zone failure

### ISSUE THREAD

**Issue by bmshouse** [weaveworks/eksctl#1142]
**What happened?**
When I try to deploy a cluster into a single region and zone, I get the following error message.
```
[✖]  insufficient number of subnets, at least 2x public and/or 2x private subnets are required
[✖]  failed to create cluster "ucb-rc-jh-trial"

```

**What you expected to happen?**
From reading old bug reports, it seems like this should deploy a new cluster into in a single AZ.

**How to reproduce it?**
Below is my config file:
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ucb-rc-jh-trial
  region: us-west-2

nodeGroups:
  - name: ucb-rc-jh-hub-trial
    instanceType: m5ad.xlarge
    availabilityZones: ["us-west-2b","us-west-2b"]
    minSize: 1
    maxSize: 2
    labels:
      role: hub
    desiredCapacity: 1
    privateNetworking: true
    preBootstrapCommands:
        # Replicate what --enable-docker-bridge does in /etc/eks/bootstrap.sh
        # Enabling the docker bridge network. We have to disable live-restore as it
        # prevents docker from recreating the default bridge network on restart
       - "cp /etc/docker/daemon.json /etc/docker/daemon_backup.json"
       - "echo -e '.bridge=\"docker0\" | .\"live-restore\"=false' >  /etc/docker/jq_script"
       - "jq -f /etc/docker/jq_script /etc/docker/daemon_backup.json | tee /etc/docker/daemon.json"
       - "systemctl restart docker"

availabilityZones: ["us-west-2b","us-west-2b"]

```

**Anything else we need to know?**
What OS are you using, are you using a downloaded binary or did you compile eksctl, what type of AWS credentials are you using (i.e. default/named profile, MFA) - please don't include actual credentials though!

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.3.1"}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T12:00:00Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**
Include the output of the command line when running eksctl. If possible, eksctl should be run with debug logs. For example:
`eksctl get clusters -v 4`
Make sure you redact any sensitive information before posting.
If the output is long, please consider a Gist.
```
2019-08-13T17:05:32-06:00 [ℹ]  using region us-west-2
2019-08-13T17:05:33-06:00 [▶]  role ARN for the current session is "arn:aws:sts::758156455206:assumed-role/Shibboleth-OIT-SysAdmin/shouse@colorado.edu"
2019-08-13T17:05:33-06:00 [▶]  VPC CIDR (192.168.0.0/16) was divided into 8 subnets [192.168.0.0/19 192.168.32.0/19 192.168.64.0/19 192.168.96.0/19 192.168.128.0/19 192.168.160.0/19 192.168.192.0/19 192.168.224.0/19]
2019-08-13T17:05:33-06:00 [ℹ]  subnets for us-west-2b - public:192.168.0.0/19 private:192.168.64.0/19
2019-08-13T17:05:33-06:00 [ℹ]  subnets for us-west-2b - public:192.168.32.0/19 private:192.168.96.0/19
2019-08-13T17:05:33-06:00 [▶]  resolving AMI using StaticGPUResolver for region us-west-2, instanceType m5ad.xlarge and imageFamily AmazonLinux2
2019-08-13T17:05:33-06:00 [▶]  can't resolve AMI using StaticGPUResolver as instance type m5ad.xlarge is non-GPU
2019-08-13T17:05:33-06:00 [▶]  resolving AMI using StaticDefaultResolver for region us-west-2, version 1.13, instanceType m5ad.xlarge and imageFamily AmazonLinux2
2019-08-13T17:05:33-06:00 [ℹ]  nodegroup "ucb-rc-jh-hub-trial" will use "ami-03a55127c613349a7" [AmazonLinux2/1.13]
2019-08-13T17:05:33-06:00 [ℹ]  using Kubernetes version 1.13
2019-08-13T17:05:33-06:00 [ℹ]  creating EKS cluster "ucb-rc-jh-trial" in "us-west-2" region
2019-08-13T17:05:33-06:00 [▶]  cfg.json = \
{
    "kind": "ClusterConfig",
    "apiVersion": "eksctl.io/v1alpha5",
    "metadata": {
        "name": "ucb-rc-jh-trial",
        "region": "us-west-2",
        "version": "1.13"
    },
    "iam": {},
    "vpc": {
        "cidr": "192.168.0.0/16",
        "subnets": {
            "private": {
                "us-west-2b": {
                    "cidr": "192.168.96.0/19"
                }
            },
            "public": {
                "us-west-2b": {
                    "cidr": "192.168.32.0/19"
                }
            }
        },
        "autoAllocateIPv6": false,
        "nat": {
            "gateway": "Single"
        }
    },
    "nodeGroups": [
        {
            "name": "ucb-rc-jh-hub-trial",
            "ami": "ami-03a55127c613349a7",
            "amiFamily": "AmazonLinux2",
            "instanceType": "m5ad.xlarge",
            "availabilityZones": [
                "us-west-2b",
                "us-west-2b"
            ],
            "privateNetworking": true,
            "securityGroups": {
                "withShared": true,
                "withLocal": true
            },
            "desiredCapacity": 1,
            "minSize": 1,
            "maxSize": 2,
            "volumeSize": null,
            "volumeType": "gp2",
            "volumeName": "/dev/xvda",
            "volumeEncrypted": false,
            "volumeIOPS": null,
            "labels": {
                "alpha.eksctl.io/cluster-name": "ucb-rc-jh-trial",
                "alpha.eksctl.io/nodegroup-name": "ucb-rc-jh-hub-trial",
                "role": "hub"
            },
            "ssh": {
                "allow": false
            },
            "iam": {
                "withAddonPolicies": {
                    "imageBuilder": false,
                    "autoScaler": false,
                    "externalDNS": false,
                    "certManager": false,
                    "appMesh": null,
                    "ebs": false,
                    "fsx": false,
                    "efs": false,
                    "albIngress": false,
                    "xRay": false,
                    "cloudWatch": false
                }
            },
            "preBootstrapCommands": [
                "cp /etc/docker/daemon.json /etc/docker/daemon_backup.json",
                "echo -e '.bridge=\"docker0\" | .\"live-restore\"=false' \u003e  /etc/docker/jq_script",
                "jq -f /etc/docker/jq_script /etc/docker/daemon_backup.json | tee /etc/docker/daemon.json",
                "systemctl restart docker"
            ]
        }
    ],
    "availabilityZones": [
        "us-west-2b",
        "us-west-2b"
    ]
}

2019-08-13T17:05:33-06:00 [ℹ]  1 nodegroup (ucb-rc-jh-hub-trial) was included
2019-08-13T17:05:33-06:00 [ℹ]  will create a CloudFormation stack for cluster itself and 1 nodegroup stack(s)
2019-08-13T17:05:33-06:00 [ℹ]  if you encounter any issues, check CloudFormation console or try 'eksctl utils describe-stacks --region=us-west-2 --name=ucb-rc-jh-trial'
2019-08-13T17:05:33-06:00 [ℹ]  CloudWatch logging will not be enabled for cluster "ucb-rc-jh-trial" in "us-west-2"
2019-08-13T17:05:33-06:00 [ℹ]  you can enable it with 'eksctl utils update-cluster-logging --region=us-west-2 --name=ucb-rc-jh-trial'
2019-08-13T17:05:33-06:00 [ℹ]  2 sequential tasks: { create cluster control plane "ucb-rc-jh-trial", create nodegroup "ucb-rc-jh-hub-trial" }
2019-08-13T17:05:33-06:00 [▶]  started task: create cluster control plane "ucb-rc-jh-trial"
2019-08-13T17:05:33-06:00 [ℹ]  building cluster stack "eksctl-ucb-rc-jh-trial-cluster"
2019-08-13T17:05:33-06:00 [▶]  failed task: create cluster control plane "ucb-rc-jh-trial" (will not run other sequential tasks)
2019-08-13T17:05:33-06:00 [ℹ]  1 error(s) occurred and cluster hasn't been created properly, you may wish to check CloudFormation console
2019-08-13T17:05:33-06:00 [ℹ]  to cleanup resources, run 'eksctl delete cluster --region=us-west-2 --name=ucb-rc-jh-trial'
2019-08-13T17:05:33-06:00 [✖]  insufficient number of subnets, at least 2x public and/or 2x private subnets are required
2019-08-13T17:05:33-06:00 [✖]  failed to create cluster "ucb-rc-jh-trial"
```
