### ISSUE TITLE
eksctl update cluster --config-file=config.yaml panic

### ISSUE THREAD

**Issue by sagivegh** [weaveworks/eksctl#1160]
**What happened?**
```
eksctl update cluster --config-file=config.yaml
```
When I try to update cluster and I'm getting  a panic message
```
[ℹ]  using region us-west-2
[!]  NOTE: config file is used for finding cluster name and region
[!]  NOTE: cluster VPC (subnets, routing & NAT Gateway) configuration changes are not yet implemented
[ℹ]  re-building cluster stack "eksctl-k8s-prd-cluster"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2162353]

goroutine 1 [running]:
github.com/weaveworks/eksctl/pkg/cfn/builder.(*ClusterResourceSet).addOutputsForVPC(0xc0008cc0f0)
        /src/pkg/cfn/builder/vpc.go:160 +0x103
github.com/weaveworks/eksctl/pkg/cfn/builder.(*ClusterResourceSet).AddAllResources(0xc0008cc0f0, 0xc0008cc0f0, 0xc00067b858)
        /src/pkg/cfn/builder/cluster.go:49 +0xac
github.com/weaveworks/eksctl/pkg/cfn/manager.(*StackCollection).AppendNewClusterStackResource(0xc00089faa0, 0xc00058f301, 0xc0004d8600, 0xc00089faa0, 0x38e1380)
        /src/pkg/cfn/manager/cluster.go:86 +0x6c4
github.com/weaveworks/eksctl/pkg/ctl/update.doUpdateClusterCmd(0xc000276e80, 0xb, 0xc0000898c0)
        /src/pkg/ctl/update/cluster.go:101 +0x344
github.com/weaveworks/eksctl/pkg/ctl/update.updateClusterCmd.func1(0xc00022a900, 0xc000669ce0)
        /src/pkg/ctl/update/cluster.go:22 +0x2a
github.com/weaveworks/eksctl/pkg/ctl/cmdutils.run(0xc000300dc0)
        /src/pkg/ctl/cmdutils/cmd.go:105 +0x2b
github.com/weaveworks/eksctl/pkg/ctl/cmdutils.(*Cmd).SetRunFuncWithNameArg.func1(0xc000357180, 0xc000301990, 0x0, 0x1)
        /src/pkg/ctl/cmdutils/cmd.go:100 +0x83
github.com/spf13/cobra.(*Command).execute(0xc000357180, 0xc000301970, 0x1, 0x1, 0xc000357180, 0xc000301970)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:766 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xc00016cc80, 0xc0003018f0, 0x1, 0x1)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:850 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:800
main.main()
        /src/cmd/eksctl/main.go:71 +0x3fc
```

**How to reproduce it?**
Running this command:
```
envsubst <config.template.yaml > config.yaml
eksctl update cluster --config-file=config.yaml
```
config.template.yaml
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ${CLUSTER}
  region: us-west-2
  version: "${EKS_VERSION}"

vpc:
  subnets:
    private:
      us-west-2a:
        id: ${PRIVATE_SUBNET1}
      us-west-2b: 
        id: ${PRIVATE_SUBNET2}
      us-west-2c: 
        id: ${PRIVATE_SUBNET3}
```

**Anything else we need to know?**
I using codebuild to create/update the cluster with IAM Role

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.4.0"} 
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-29T16:15:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"} 
```

**Logs**
```
eksctl update cluster --config-file=config.yaml -v 4
2019-08-19T15:09:31+03:00 [ℹ]  using region us-west-2
2019-08-19T15:09:32+03:00 [▶]  role ARN for the current session is 
2019-08-19T15:09:33+03:00 [▶]  cluster = {
  Arn: "",
  CertificateAuthority: {
    Data: ""
  },
  CreatedAt: 2019-08-19 08:23:12 +0000 UTC,
  Endpoint: "",
  Logging: {
    ClusterLogging: [{
        Enabled: false,
        Types: [
          "api",
          "audit",
          "authenticator",
          "controllerManager",
          "scheduler"
        ]
      }]
  },
  Name: "k8s-prd",
  PlatformVersion: "eks.2",
  ResourcesVpcConfig: {
    EndpointPrivateAccess: false,
    EndpointPublicAccess: true,
    SecurityGroupIds: ["sg-12345678"],
    SubnetIds: ["subnet-1","subnet-2","subnet-3"],
    VpcId: "vpc-1"
  },
  RoleArn: "",
  Status: "ACTIVE",
  Version: "1.13"
}
2019-08-19T15:09:33+03:00 [!]  NOTE: config file is used for finding cluster name and region
2019-08-19T15:09:33+03:00 [!]  NOTE: cluster VPC (subnets, routing & NAT Gateway) configuration changes are not yet implemented
2019-08-19T15:09:37+03:00 [▶]  cfg.json = \
{
    "kind": "ClusterConfig",
    "apiVersion": "eksctl.io/v1alpha5",
    "metadata": {
        "name": "k8s-prd",
        "region": "us-west-2",
        "version": "1.13"
    },
    "iam": {},
    "vpc": {
        "id": "vpc-1",
        "cidr": "10.81.48.0/22",
        "securityGroup": "sg-12345678",
        "subnets": {
            "private": {
                "us-west-2a": {
                    "id": "subnet-1",
                    "cidr": "10.69.80.0/23"
                },
                "us-west-2b": {
                    "id": "subnet-2",
                    "cidr": "10.69.82.0/23"
                },
                "us-west-2c": {
                    "id": "subnet-3",
                    "cidr": "10.69.84.0/23"
                }
            }
        },
        "sharedNodeSecurityGroup": "sg-12345678"
    },
    "nodeGroups": [
        {
            "name": "KubeSystem",
            "ami": "ami-12345678",
            "amiFamily": "AmazonLinux2",
            "instanceType": "m5.xlarge",
            "privateNetworking": true,
            "securityGroups": {
                "withShared": true,
                "withLocal": true
            },
            "desiredCapacity": 1,
            "volumeSize": null,
            "volumeType": "gp2",
            "volumeIOPS": null,
            "labels": {
                "role": "kubesystem"
            },
            "ssh": {
                "allow": false
            },
            "iam": {
                "withAddonPolicies": {
                    "imageBuilder": false,
                    "autoScaler": false,
                    "externalDNS": false,
                    "certManager": false,
                    "appMesh": null,
                    "ebs": false,
                    "fsx": false,
                    "efs": false,
                    "albIngress": false,
                    "xRay": false,
                    "cloudWatch": false
                }
            }
        }
    ],
    "availabilityZones": [
        "us-west-2c",
        "us-west-2a",
        "us-west-2b"
    ],
    "status": {
        "endpoint": "",
        "certificateAuthorityData": "",
        "arn": ""
    }
}

2019-08-19T15:09:37+03:00 [ℹ]  re-building cluster stack "eksctl-k8s-prd-cluster"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2162353]

goroutine 1 [running]:
github.com/weaveworks/eksctl/pkg/cfn/builder.(*ClusterResourceSet).addOutputsForVPC(0xc00096a4b0)
        /src/pkg/cfn/builder/vpc.go:160 +0x103
github.com/weaveworks/eksctl/pkg/cfn/builder.(*ClusterResourceSet).AddAllResources(0xc00096a4b0, 0xc00096a4b0, 0xc000509858)
        /src/pkg/cfn/builder/cluster.go:49 +0xac
github.com/weaveworks/eksctl/pkg/cfn/manager.(*StackCollection).AppendNewClusterStackResource(0xc000ae4210, 0xc000161901, 0xc000582680, 0xc000ae4210, 0x38e1380)
        /src/pkg/cfn/manager/cluster.go:86 +0x6c4
github.com/weaveworks/eksctl/pkg/ctl/update.doUpdateClusterCmd(0xc000583280, 0xb, 0xc000146000)
        /src/pkg/ctl/update/cluster.go:101 +0x344
github.com/weaveworks/eksctl/pkg/ctl/update.updateClusterCmd.func1(0xc00012f600, 0xc00069bce0)
        /src/pkg/ctl/update/cluster.go:22 +0x2a
github.com/weaveworks/eksctl/pkg/ctl/cmdutils.run(0xc0002f6ab0)
        /src/pkg/ctl/cmdutils/cmd.go:105 +0x2b
github.com/weaveworks/eksctl/pkg/ctl/cmdutils.(*Cmd).SetRunFuncWithNameArg.func1(0xc000158c80, 0xc0003a80f0, 0x0, 0x3)
        /src/pkg/ctl/cmdutils/cmd.go:100 +0x83
github.com/spf13/cobra.(*Command).execute(0xc000158c80, 0xc0003a8060, 0x3, 0x3, 0xc000158c80, 0xc0003a8060)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:766 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xc00034bb80, 0xc0002f70c0, 0x1, 0x1)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:850 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:800
main.main()
        /src/cmd/eksctl/main.go:71 +0x3fc
```

**Comment by cPu1** [comment]
@sagivegh thanks for the bug report. This has been fixed in [0.4.1](https://github.com/weaveworks/eksctl/releases/tag/0.4.1)

**Comment by errordeveloper** [comment]
@cpu1 didn't you reopen this intentionally?

**Comment by underyx** [comment]
Still seems to be happening for me
```bash
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.4.2"}
$ eksctl update cluster -f foo.yml
[ℹ]  using region us-east-2
[!]  NOTE: config file is used for finding cluster name and region
[!]  NOTE: cluster VPC (subnets, routing & NAT Gateway) configuration changes are not yet implemented
[ℹ]  re-building cluster stack "eksctl-foo-cluster"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x15619e3]

goroutine 1 [running]:
github.com/weaveworks/eksctl/pkg/cfn/builder.(*ClusterResourceSet).addOutputsForVPC(0xc00028c780)
	/src/pkg/cfn/builder/vpc.go:160 +0x103
github.com/weaveworks/eksctl/pkg/cfn/builder.(*ClusterResourceSet).AddAllResources(0xc00028c780, 0xc00028c780, 0xc000371858)
	/src/pkg/cfn/builder/cluster.go:49 +0xac
github.com/weaveworks/eksctl/pkg/cfn/manager.(*StackCollection).AppendNewClusterStackResource(0xc0005904e0, 0xc0003c6a01, 0xc0003cdb80, 0xc0005904e0, 0x2ce1a20)
	/src/pkg/cfn/manager/cluster.go:83 +0x612
github.com/weaveworks/eksctl/pkg/ctl/update.doUpdateClusterCmd(0xc0003cc100, 0xb, 0xc00066d200)
	/src/pkg/ctl/update/cluster.go:101 +0x344
github.com/weaveworks/eksctl/pkg/ctl/update.updateClusterCmd.func1(0xc000672400, 0xc000389ce0)
	/src/pkg/ctl/update/cluster.go:22 +0x2a
github.com/weaveworks/eksctl/pkg/ctl/cmdutils.run(0xc000086f40)
	/src/pkg/ctl/cmdutils/cmd.go:105 +0x2b
github.com/weaveworks/eksctl/pkg/ctl/cmdutils.(*Cmd).SetRunFuncWithNameArg.func1(0xc000676280, 0xc00066efe0, 0x0, 0x2)
	/src/pkg/ctl/cmdutils/cmd.go:100 +0x83
github.com/spf13/cobra.(*Command).execute(0xc000676280, 0xc00066efa0, 0x2, 0x2, 0xc000676280, 0xc00066efa0)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:766 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002d5900, 0xc0003fa4b0, 0x1, 0x1)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:850 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:800
main.main()
	/src/cmd/eksctl/main.go:71 +0x3fc
```

**Comment by errordeveloper** [comment]
@underyx could please show the contents of 'foo.yml'?

**Comment by errordeveloper** [comment]
@underyx could you please show the contents of `foo.yml`?

**Comment by cPu1** [comment]
I tried reproducing this using different VPC configs but to no avail.

@underyx could you please share the config file (`foo.yml`)?

**Comment by underyx** [comment]
Hey again, really sorry, but by the time I saw your comments I already rewrote the cluster config from scratch (for unrelated reasons) and I don't have the failing one anymore. If I remember correctly, it looked something like this:

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

vpc:
  subnets:
    private:
      us-east-2a: { id: subnet-0608•••••••••6c63 }
      us-east-2b: { id: subnet-08a2•••••••••2f09 }
      us-east-2c: { id: subnet-09be•••••••••7dd5 }

metadata:
  name: foo
  region: us-east-2

nodeGroups:

  - name: persistent
    labels: { pool: persistent }
    instanceType: t3.small
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    privateNetworking: true
    iam:
      withAddonPolicies:
        autoScaler: true

  - name: spot
    instanceType: mixed
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    privateNetworking: true
    instancesDistribution:
      maxPrice: 0.1
      onDemandPercentageAboveBaseCapacity: 0
      instanceTypes:  # get from https://aws.amazon.com/ec2/spot/instance-advisor/
        - r3.xlarge
        - r4.large
        - r4.xlarge
        - r5.large
        - r5.xlarge
    iam:  # access isn't needed, but this labels the group as a scaling target
      withAddonPolicies:
        autoScaler: true
```

I created the cluster with `eksctl create cluster -f foo.yml`.

**Comment by nlowe** [comment]
I've got a panic on 5.1:

```bash
~/projects/eksctl-clusters [☸ nlowe@test-cluster.us-east-1.eksctl.io:default]$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.5.1"}
```

```bash
~/projects/eksctl-clusters [☸ nlowe@test-cluster.us-east-1.eksctl.io:default]$ eksctl update cluster --config-file .\test-cluster.yaml
[ℹ]  using region us-east-1
[!]  NOTE: config file is used for finding cluster name and region
[!]  NOTE: cluster VPC (subnets, routing & NAT Gateway) configuration changes are not yet implemented
[ℹ]  re-building cluster stack "eksctl-test-cluster-cluster"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x15f619a]

goroutine 1 [running]:
github.com/weaveworks/eksctl/pkg/cfn/builder.(*ClusterResourceSet).addOutputsForVPC(0xc0006c60a0)
        /src/pkg/cfn/builder/vpc.go:160 +0x10a
github.com/weaveworks/eksctl/pkg/cfn/builder.(*ClusterResourceSet).AddAllResources(0xc0006c60a0, 0xc0006c60a0, 0xc0007d3868)
        /src/pkg/cfn/builder/cluster.go:49 +0xb3
github.com/weaveworks/eksctl/pkg/cfn/manager.(*StackCollection).AppendNewClusterStackResource(0xc00054e150, 0xc0003d9901, 0xc0000d2580, 0xc00054e150, 0x2dbb5e0)
        /src/pkg/cfn/manager/cluster.go:83 +0x619
github.com/weaveworks/eksctl/pkg/ctl/update.doUpdateClusterCmd(0xc00056ed80, 0xb, 0xc00058c000)
        /src/pkg/ctl/update/cluster.go:101 +0x342
github.com/weaveworks/eksctl/pkg/ctl/update.updateClusterCmd.func1(0xc0004c3000, 0xc0006adce0)
        /src/pkg/ctl/update/cluster.go:22 +0x31
github.com/weaveworks/eksctl/pkg/ctl/cmdutils.run(0xc0002c8c60)
        /src/pkg/ctl/cmdutils/cmd.go:105 +0x32
github.com/weaveworks/eksctl/pkg/ctl/cmdutils.(*Cmd).SetRunFuncWithNameArg.func1(0xc000582280, 0xc000594160, 0x0, 0x2)
        /src/pkg/ctl/cmdutils/cmd.go:100 +0x8a
github.com/spf13/cobra.(*Command).execute(0xc000582280, 0xc000594120, 0x2, 0x2, 0xc000582280, 0xc000594120)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:766 +0x2b5
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000cf400, 0xc0002c94f0, 0x1, 0x1)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:850 +0x303
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:800
main.main()
        /src/cmd/eksctl/main.go:73 +0x403
```

Cluster config:

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-cluster
  version: "1.13"
  region: us-east-1

vpc:
  subnets:
    private:
      us-east-1a: { id: subnet-02b9ff1f4af883dd1 }
      us-east-1b: { id: subnet-0d6d0560e8efa73c6 }

nodeGroups:
  - name: test-cluster-nodes
    instanceType: t3.medium
    desiredCapacity: 3
    minSize: 3
    maxSize: 10
    volumeSize: 50
    volumeType: gp2
    privateNetworking: true
```

Created the cluster with `eksctl create cluster --config-file .\test-cluster.yaml`. Changed the `metadata.version` from `"1.12"` to `"1.13"` and got the panic.

**Comment by calebpalmer** [comment]
I'm also seeing the same issue running 0.6.0.  Config:
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks
  region: us-east-1

vpc:
  subnets:
    private:
      us-east-1a: { id: subnet-0c7ec6799214b3edd }
      us-east-1b: { id: subnet-0439f96ad79b2d637 }

nodeGroups:
  - name: workers
    labels: { role: workers }
    instanceType: t3a.medium
    
    desiredCapacity: 1
    minSize: 1
    maxSize: 3
    privateNetworking: true

    iam:
      withAddonPolicies:
        autoscaler: true
        cloudWatch: true
```

I initially created it without the iam section and then added it and ran the update.

```
[!]  NOTE: config file is used for finding cluster name and region
[!]  NOTE: cluster VPC (subnets, routing & NAT Gateway) configuration changes are not yet implemented
[ℹ]  re-building cluster stack "eksctl-eks-cluster"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x15b41e3]

goroutine 1 [running]:
github.com/weaveworks/eksctl/pkg/cfn/builder.(*ClusterResourceSet).addOutputsForVPC(0xc0000d6550)
        /src/pkg/cfn/builder/vpc.go:160 +0x103
github.com/weaveworks/eksctl/pkg/cfn/builder.(*ClusterResourceSet).AddAllResources(0xc0000d6550, 0xc0000d6550, 0xc0006cf868)
        /src/pkg/cfn/builder/cluster.go:49 +0xac
github.com/weaveworks/eksctl/pkg/cfn/manager.(*StackCollection).AppendNewClusterStackResource(0xc0003891d0, 0xc0005e1b01, 0xc0001fa900, 0xc0003891d0, 0x2d71aa0)
        /src/pkg/cfn/manager/cluster.go:83 +0x612
github.com/weaveworks/eksctl/pkg/ctl/update.doUpdateClusterCmd(0xc000370d00, 0xb, 0xc0002ac720)
        /src/pkg/ctl/update/cluster.go:103 +0x33b
github.com/weaveworks/eksctl/pkg/ctl/update.updateClusterCmd.func1(0xc000512d00, 0xc00056dce0)
        /src/pkg/ctl/update/cluster.go:22 +0x2a
github.com/weaveworks/eksctl/pkg/ctl/cmdutils.run(0xc0002aec60)
        /src/pkg/ctl/cmdutils/cmd.go:105 +0x2b
github.com/weaveworks/eksctl/pkg/ctl/cmdutils.(*Cmd).SetRunFuncWithNameArg.func1(0xc0003d0000, 0xc0001d8400, 0x0, 0x4)
        /src/pkg/ctl/cmdutils/cmd.go:100 +0x83
github.com/spf13/cobra.(*Command).execute(0xc0003d0000, 0xc0001d8300, 0x4, 0x4, 0xc0003d0000, 0xc0001d8300)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:766 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000f8c80, 0xc0005f80d0, 0x1, 0x1)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:850 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:800
main.main()
        /src/cmd/eksctl/main.go:73 +0x3fc
caleb@FRD-D000172:~$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.6.0"}
```

**Comment by matti** [comment]
same with 0.7.0 - I tried modifying my config, but it just keeps crashing with updates:

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: test-eks-1
  region: eu-central-1
vpc:
  subnets:
    public:
      eu-central-1a: { id: subnet-03de9c5fb99c7b8d2 }
      eu-central-1b: { id: subnet-04d7bf34c85bc7cb3 }
      eu-central-1c: { id: subnet-0ee5e7942bcfd872c }
nodeGroups:
  - name: m5d-large-public
    instanceType: m5d.large
    ssh:
      publicKeyPath: ~/.ssh/eks-1.pub
    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true
        efs: true
        cloudWatch: true
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
```

**Comment by matti** [comment]
^-- resolved: I had manually changed the nodegroup

**Comment by groner** [comment]
I hit this particular error in v0.7.0 when `c.spec.VPC.NAT` is nil.
```
github.com/weaveworks/eksctl/pkg/cfn/builder.(*ClusterResourceSet).addOutputsForVPC(0xc0000d6550)
        /src/pkg/cfn/builder/vpc.go:160 +0x103
```

**Comment by nriveraonica** [comment]
```
[ℹ]  eksctl version 0.7.0
[ℹ]  using region us-east-1
[!]  NOTE: config file is used for finding cluster name and region
[!]  NOTE: cluster VPC (subnets, routing & NAT Gateway) configuration changes are not yet implemented
[ℹ]  re-building cluster stack "eksctl-shared-services-cluster"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x21babb3]

goroutine 1 [running]:
github.com/weaveworks/eksctl/pkg/cfn/builder.(*ClusterResourceSet).addOutputsForVPC(0xc000766000)
        /src/pkg/cfn/builder/vpc.go:160 +0x103
github.com/weaveworks/eksctl/pkg/cfn/builder.(*ClusterResourceSet).AddAllResources(0xc000766000, 0xc000766000, 0xc0009bb868)
        /src/pkg/cfn/builder/cluster.go:49 +0xac
github.com/weaveworks/eksctl/pkg/cfn/manager.(*StackCollection).AppendNewClusterStackResource(0xc000adc7b0, 0xc000587300, 0xc0003c4b00, 0xc000adc7b0, 0x3981640)
        /src/pkg/cfn/manager/cluster.go:83 +0x612
github.com/weaveworks/eksctl/pkg/ctl/update.doUpdateClusterCmd(0xc0006fce00, 0xb, 0xc000456240)
        /src/pkg/ctl/update/cluster.go:103 +0x2cf
github.com/weaveworks/eksctl/pkg/ctl/update.updateClusterCmd.func1(0xc0000e6600, 0xc0006a1ce0)
        /src/pkg/ctl/update/cluster.go:22 +0x2a
github.com/weaveworks/eksctl/pkg/ctl/cmdutils.run(0xc00023ceb0)
        /src/pkg/ctl/cmdutils/cmd.go:105 +0x2b
github.com/weaveworks/eksctl/pkg/ctl/cmdutils.(*Cmd).SetRunFuncWithNameArg.func1(0xc000606500, 0xc000398db0, 0x0, 0x3)
        /src/pkg/ctl/cmdutils/cmd.go:100 +0x83
github.com/spf13/cobra.(*Command).execute(0xc000606500, 0xc000398d20, 0x3, 0x3, 0xc000606500, 0xc000398d20)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:766 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xc00057a000, 0xc00023d5e0, 0x1, 0x1)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:850 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:800
main.main()
        /src/cmd/eksctl/main.go:73 +0x3fc

```

Version: [ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.7.0"}

Config: Changed  desiredCapacity: 1 to 2
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: shared-services
  region: us-east-1

vpc:
  subnets:
    private:
      us-east-1a: { id:  subnet-057bcec3293752ce4 }
      us-east-1b: { id:  subnet-06805dbd7e5e7f0e4 }

nodeGroups:
  - name: ng-1-workers
    labels: { role: workers }
    instanceType: t3.large
    desiredCapacity: 2
    privateNetworking: true
```

**Comment by whereisaaron** [comment]
Same crash on `eksctl update` with 0.7.0

I had to add `vpc.nat.gateway: Disable` to the config file to stop it crashing.

```
[ℹ]  eksctl version 0.7.0
[ℹ]  using region ap-southeast-2
[!]  NOTE: config file is used for finding cluster name and region
[!]  NOTE: cluster VPC (subnets, routing & NAT Gateway) configuration changes are not yet implemented
[ℹ]  re-building cluster stack "eksctl-cave-cluster"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x15b9f93]

goroutine 1 [running]:
github.com/weaveworks/eksctl/pkg/cfn/builder.(*ClusterResourceSet).addOutputsForVPC(0xc0009ef8b0)
        /src/pkg/cfn/builder/vpc.go:160 +0x103
github.com/weaveworks/eksctl/pkg/cfn/builder.(*ClusterResourceSet).AddAllResources(0xc0009ef8b0, 0xc0009ef8b0, 0xc000541868)
        /src/pkg/cfn/builder/cluster.go:49 +0xac
github.com/weaveworks/eksctl/pkg/cfn/manager.(*StackCollection).AppendNewClusterStackResource(0xc000948ed0, 0xc0003fd401, 0xc0004a6480, 0xc000948ed0, 0x2d81860)
        /src/pkg/cfn/manager/cluster.go:83 +0x612
github.com/weaveworks/eksctl/pkg/ctl/update.doUpdateClusterCmd(0xc0001e6680, 0xb, 0xc000478120)
        /src/pkg/ctl/update/cluster.go:103 +0x2cf
github.com/weaveworks/eksctl/pkg/ctl/update.updateClusterCmd.func1(0xc0005c6e00, 0xc0005a3ce0)
        /src/pkg/ctl/update/cluster.go:22 +0x2a
github.com/weaveworks/eksctl/pkg/ctl/cmdutils.run(0xc0004143e0)
        /src/pkg/ctl/cmdutils/cmd.go:105 +0x2b
github.com/weaveworks/eksctl/pkg/ctl/cmdutils.(*Cmd).SetRunFuncWithNameArg.func1(0xc000627680, 0xc0004539e0, 0x0, 0x2)
        /src/pkg/ctl/cmdutils/cmd.go:100 +0x83
github.com/spf13/cobra.(*Command).execute(0xc000627680, 0xc0004539a0, 0x2, 0x2, 0xc000627680, 0xc0004539a0)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:766 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xc00012a280, 0xc0004805c0, 0x1, 0x1)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:850 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:800
main.main()
        /src/cmd/eksctl/main.go:73 +0x3fc
```

**Comment by cdenneen** [comment]
@whereisaaron thanks for this.
I too had to add that to get around the panic with `0.8.0`:

```
vpc:
  nat:
    gateway: Disable
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
  subnets:
    private:
      us-east-1a: { id: subnet-abc }
      us-east-1b: { id: subnet-def }
      us-east-1d: { id: subnet-ghi }
```

This cluster is in an existing VPC so don't want to be making unnecessary changes.
