### ISSUE TITLE
Existing VPC. Command got stuck at "waiting for at least 4 node(s) to become ready in "XXX". Then timed out.

### ISSUE THREAD

**Issue by logesh-freshworks** [weaveworks/eksctl#1176]
I am using an existing VPC. Control pane and Node groups were created. I can see all 4 ec2 instances up and running. But The command got stuck at  **waiting for at least 4 node(s) to become ready in "ekstest-ng1".** 
Then it's timed out saying 
`timed out (after 25m0s) waiting for at least 4 nodes to join the cluster and become ready in "eksfbots-ng1"`

Here is the command 
`eksctl create cluster -f eks-cluster.yaml`
**Template** 

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: test-eksctl
  region: ap-south-1
  version: "1.13"
vpc:
  id: "vpc-xxx"  
  cidr: "xxx/x"          
  subnets:
    private:
      ap-south-1a:
          id: "subnet-xxx"          
      ap-south-1b:
          id: "subnet-xxx"          
      ap-south-1c:
          id: "subnet-xxx"          
    public:
      ap-south-1a:
          id: "subnet-xxx"          
      ap-south-1b:
          id: "subnet-xxx"        
      ap-south-1c:
          id: "sbnet-xxx"   
nodeGroups:
  - name: eksf-ng1
    desiredCapacity: 4
    instanceType: m5.large
```

**CLI Output** 
```
using region ap-south-1
using existing VPC (vpc-xxx) and subnets (private:[subnet-xxx subnet-xxx subnet-xxx] public:[subnet-xxx subnet-xxx subnet-xxx])
 custom VPC/subnets will be used; if resulting cluster doesn't function as expected, make sure to review the configuration of VPC/subnets
nodegroup "ekstest-ng1" will use "ami-0a9b1c1807b1a40ab" [AmazonLinux2/1.13]
using Kubernetes version 1.13
creating EKS cluster "test-eksctl" in "ap-south-1" region
1 nodegroup (ekstest-ng1) was included
will create a CloudFormation stack for cluster itself and 1 nodegroup stack(s)
if you encounter any issues, check CloudFormation console or try 'eksctl utils describe-stacks --region=ap-south-1 --name=test-eksctl'
2 sequential tasks: { create cluster control plane "test-eksctl", create nodegroup "ekstest-ng1" }
building cluster stack "eksctl-test-eksctl-cluster"
deploying stack "eksctl-test-eksctl-cluster"
building nodegroup stack "eksctl-test-eksctl-nodegroup-ekstest-ng1"
--nodes-min=4 was set automatically for nodegroup ekstest-ng1
--nodes-max=4 was set automatically for nodegroup ekstest-ng1
deploying stack "eksctl-test-eksctl-nodegroup-ekstest-ng1"]  all EKS cluster resource for "test-eksctl" had been created]  saved kubeconfig as "/home/logesh/.kube/config"
adding role "arn:aws:iam::xxx:role/eksctl-test-eksctl-nodegroup-eks-NodeInstanceRole-xxx" to auth ConfigMap
nodegroup "ekstest-ng1" has 0 node(s)
waiting for at least 4 node(s) to become ready in "ekstest-ng1"
timed out (after 25m0s) waiting for at least 4 nodes to join the cluster and become ready in "eksfbots-ng1"
```
