### ISSUE TITLE
Eksctl reports cluster deleted but cloud formation of control plane fails to delete

### ISSUE THREAD

**Issue by jvosantos** [weaveworks/eksctl#1295]
**What happened?**
When trying to delete a cluster, eksctl reports that everything has been deleted, however looking at the cloudformation stacks, the stack of the eks control plane still exists.

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/7671252/64352417-ea838080-cff3-11e9-843c-2497a43b228a.png">

**What you expected to happen?**
I expected to be able to create a cluster with eksctl, delete it, and create it again. I didn't expect eksctl to say everything is deleted and then something fails.

**How to reproduce it?**
Create a cluster with the following config, delete it, and check that cloudformation stack for the control plane still exists
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: k8s-operations
  region: us-west-2

vpc:
  cidr: 10.16.0.0/16
  autoAllocateIPv6: true

nodeGroups:
  - name: general-purpose-2
    instanceType: m5.large
    minSize: 2
    maxSize: 5
    iam:
      withAddonPolicies:
        autoScaler: true
```

**Anything else we need to know?**
downloaded binary
aws environment credentials for a service account

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.5.0"}```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T12:36:28Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
```

**Logs**
```
$ eksctl delete cluster '--name=k8s-staging'
[ℹ]  using region us-west-2
[ℹ]  deleting EKS cluster "k8s-staging"
[✔]  kubeconfig has been updated
[ℹ]  cleaning up LoadBalancer services
[ℹ]  2 sequential tasks: { delete nodegroup "ng-1", delete cluster control plane "k8s-staging" [async] }
[ℹ]  will delete stack "eksctl-k8s-staging-nodegroup-ng-1"
[ℹ]  waiting for stack "eksctl-k8s-staging-nodegroup-ng-1" to get deleted
[ℹ]  will delete stack "eksctl-k8s-staging-cluster"
[✔]  all cluster resources were deleted
```
