### ISSUE TITLE
Support for Flux Kustomize usage in eksctl GitOps

### ISSUE THREAD

**Issue by autarchprinceps** [weaveworks/eksctl#1327]
We really like the idea of eksctl flux integration. I am aware that it is of course that it is experimental and therefore documentation or code might not be completed, so I'm opening this as a FR.

In order for this to be usable for us, we would have to be able to combine this with the use of kustomize in flux and we would like to continue to use fluxcloud. Both require some additional settings to be set, which as of now, I'd be unsure how to integrate into a ClusterConfig file.

We currently follow the [guide ](https://docs.fluxcd.io/en/latest/tutorials/get-started-helm.html) for setting up helm manually first and installing flux with helm. In that case we have a helm-values yaml via a command `helm upgrade -f flux-values.yaml -i flux --namespace flux  fluxcd/flux ` which looks like this:
```yaml
additionalArgs:
- --manifest-generation=true
- --connect=ws://fluxcloud
git:
  url: git@github.com:org/repo.git
  branch: 'verified-deployment'
  path: patches/prod
rbac:
  create: true
helmOperator:
  create: true
  createCRD: false
prometheus:
  enabled: true
```

Is this perhaps already possible to specify, or if not, could it be added?
