### ISSUE TITLE
Only nodes from one zone getting added to cluster

### ISSUE THREAD

**Issue by InAnimaTe** [weaveworks/eksctl#1340]
**What happened?**
Nodes from other AZ's are not being added to the cluster on fresh nodegroup create. In this case, us-east-1a nodes are added, but 1b and 1c are not.

**What you expected to happen?**
I expected all the nodes across all nodegroups to join the cluster when created.

**How to reproduce it?**
```
eksctl create cluster --without-nodegroup -f eksctl.yaml --kubeconfig ./kubeconfig -p sandbox
eksctl create nodegroup -f eksctl.yaml -p sandbox
kubectl get nodes
-> Context: marioloria@mario-sandbox.us-east-1.eksctl.io
-> Namespace: 
NAME                             STATUS   ROLES               AGE   VERSION
ip-192-168-78-190.ec2.internal   Ready    base-nodegroup-1a   11m   v1.14.6-eks-5047ed
ip-192-168-78-76.ec2.internal    Ready    base-nodegroup-1a   11m   v1.14.6-eks-5047ed
```

**Anything else we need to know?**
My `eksctl` file:

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
availabilityZones: ["us-east-1a", "us-east-1b", "us-east-1c"]

metadata:
  name: &clustername "mario-sandbox"
  region: us-east-1
  version: '1.14'

vpc:
  cidr: "192.168.64.0/19"
  nat:
    gateway: HighlyAvailable

nodeGroups:
  - name: &basenodegroup base-nodegroup-1a
    availabilityZones: ["us-east-1a"]
    labels:
      node-role.kubernetes.io/base-nodegroup-1a: worker # Change me
    clusterDNS: &clusterdns 169.254.20.10
    instanceType: &instancetype m5.xlarge
    amiFamily: &amifamily AmazonLinux2
    volumeSize: &volumesize 120
    volumeType: &volumetype gp2
    ssh: &ssh
      allow: false
    privateNetworking: &privatenetworking true
    desiredCapacity: &desiredcapacity 2
    minSize: &minsize 1
    maxSize: &maxsize 3
    iam: &iam
      withAddonPolicies:
        autoScaler: true
        externalDNS: true

  - name: base-nodegroup-1b
    availabilityZones: ["us-east-1b"]
    labels:
      node-role.kubernetes.io/base-nodegroup-1b: worker # Change me
    clusterDNS: *clusterdns
    instanceType: *instancetype
    amiFamily: *amifamily
    volumeSize: *volumesize
    volumeType: *volumetype
    ssh:
      <<: *ssh
    privateNetworking: *privatenetworking
    desiredCapacity: *desiredcapacity
    minSize: *minsize
    maxSize: *maxsize
    iam:
      <<: *iam

  - name: base-nodegroup-1c
    availabilityZones: ["us-east-1c"]
    labels:
      node-role.kubernetes.io/base-nodegroup-1c: worker # Change me
    clusterDNS: *clusterdns
    instanceType: *instancetype
    amiFamily: *amifamily
    volumeSize: *volumesize
    volumeType: *volumetype
    ssh:
      <<: *ssh
    privateNetworking: *privatenetworking
    desiredCapacity: *desiredcapacity
    minSize: *minsize
    maxSize: *maxsize
    iam:
      <<: *iam

```

**Versions**
Please paste in the output of these commands:
```
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.5.2"}

Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T12:36:28Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-eks-5047ed", GitCommit:"5047edce664593832e9b889e447ac75ab104f527", GitTreeState:"clean", BuildDate:"2019-08-21T22:32:40Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**
(will provide later given they're needed)
