### ISSUE TITLE
Allow enabling autoscaler on a nodegroup without needing to set the IAM policy

### ISSUE THREAD

**Issue by rrtj3** [weaveworks/eksctl#1341]
**Why do you want this feature?**
We apply custom Instance roles and profiles to our nodegroups on creation. We also want to enable autoscaling on them, but trying to set the needed config options on the same nodegroup fails:

```
    iam:
        instanceProfileARN: "arn:aws:iam::888888888888:instance-profile/1010-eks-edge-node-role"
        instanceRoleARN: "arn:aws:iam::888888888888:role/1010-eks-edge-node-role"
        withAddonPolicies:
            autoScaler: true
```
with this error:

> [✖]  nodeGroups[0].iam.instanceProfileARN and nodeGroups[0].iam.withAddonPolicies.autoScaler cannot be set at the same time

**What feature/behavior/change do you want?**
We need the autoscaling group to automatically have the needed autoscaling flags that get set on the ASG when the autoScaler IAM policy is added:

https://github.com/weaveworks/eksctl/commit/4d186fe68f04758da213af92bbfc9fcf8370a614

but not have to apply the IAM policy. (We can add the IAM policy ourselves with our custom iam policies we're already using.)

Do not hesitate, when appropriate, to share the exact commands or API you would like, and/or to share a diagram (e.g.: asciiflow.com): "a picture is worth a thousand words".

**Comment by rndstr** [comment]
instead of aborting if both `iam.withAddonPolicies.autoScaler == true` and any instance ARN set, could the tags be added and a log message tells the user to take care of IAM policies themselves?

**Comment by adamjohnson01** [comment]
@rrtj3 

This can be done using tags in the nodegroup config.

```
nodeGroups:
  - name: edge-nodes
    instanceType: m5.xlarge
    desiredCapacity: 1
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/yourClusterName: "owned"
    iam:
        instanceProfileARN: "arn:aws:iam::888888888888:instance-profile/1010-eks-edge-node-role"
        instanceRoleARN: "arn:aws:iam::888888888888:role/1010-eks-edge-node-role"
```

**Comment by artemkv** [comment]
> @rrtj3
> 
> This can be done using tags in the nodegroup config.
> 
> ```
> nodeGroups:
>   - name: edge-nodes
>     instanceType: m5.xlarge
>     desiredCapacity: 1
>     tags:
>       k8s.io/cluster-autoscaler/enabled: "true"
>       k8s.io/cluster-autoscaler/yourClusterName: "owned"
>     iam:
>         instanceProfileARN: "arn:aws:iam::888888888888:instance-profile/1010-eks-edge-node-role"
>         instanceRoleARN: "arn:aws:iam::888888888888:role/1010-eks-edge-node-role"
> ```

I tried to set tags, but they were not applied. Here is my config:
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: xxxxx
  region: eu-west-1

nodeGroups:
  - name: ng-workers-114
    instanceType: m5a.large
    minSize: 1
    maxSize: 20
    desiredCapacity: 4
    tags:
      # EC2 tags required for cluster-autoscaler auto-discovery
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/xxxxx: "owned"
    ssh:
      publicKeyName: eks-ng-workers-key
    labels:
      autoscaling: enabled
      purpose: staging
    iam:
      instanceProfileARN: arn:aws:iam::5780xxxxxxxxxxxx...
      instanceRoleARN: arn:aws:iam::5780xxxxxxxxxxxx...
```

The only tags that were effectively applied were:
```
      Tags:
      - Key: Name
        PropagateAtLaunch: 'true'
        Value: xxxxx-ng-workers-114-Node
      - Key: kubernetes.io/cluster/xxxxx
        PropagateAtLaunch: 'true'
        Value: owned
```
I am not a specialist in GO, so I might be wrong, but looking at the code, it seems that the tags are not passed from the config, but hard-coded, controlled by ```asg-access``` flag:

```
	tags := []map[string]interface{}{
		{
			"Key":               "Name",
			"Value":             fmt.Sprintf("%s-%s-Node", n.clusterSpec.Metadata.Name, n.nodeGroupName),
			"PropagateAtLaunch": "true",
		},
		{
			"Key":               "kubernetes.io/cluster/" + n.clusterSpec.Metadata.Name,
			"Value":             "owned",
			"PropagateAtLaunch": "true",
		},
	}
	if api.IsEnabled(n.spec.IAM.WithAddonPolicies.AutoScaler) {
		tags = append(tags,
			map[string]interface{}{
				"Key":               "k8s.io/cluster-autoscaler/enabled",
				"Value":             "true",
				"PropagateAtLaunch": "true",
			},
			map[string]interface{}{
				"Key":               "k8s.io/cluster-autoscaler/" + n.clusterSpec.Metadata.Name,
				"Value":             "owned",
				"PropagateAtLaunch": "true",
			},
		)
	}

	asg := nodeGroupResource(launchTemplateName, &vpcZoneIdentifier, tags, n.spec)
```
This matches the observed result. But you seem to say that somehow the tags should still be applied. What am I missing?

The reason why we use custom instance roles and profile:
- We use kube2iam, so we have create a custom role for each microservice, e.g. "my-service-role"
- The role "my-service-role" needs to have a policy allowing to assume role that the node runs with
- So, in essense, every microservice references the node role
- When we upgrade the k8s cluster, the suggested sequence is to create a new nodegroup, then delete the old nodegroup
- This creates a new node role and profile, and deletes the old ones
- So if we don't use custom role for the node, every role for every microservice needs to be updated to allow assuming the new node role created with the new node group
- Morover, every service needs to be re-deployed for the changes to take effect
- This has a very disruptive effect on our services

So it seems all we need is to be able to pass tags using config file.
