### ISSUE TITLE
Secondary IPs not being Attached

### ISSUE THREAD

**Issue by mr-karan** [weaveworks/eksctl#1399]
**What happened?**
Created a new cluster with dedicated VPC and Subnet (config is below). Pods are stuck on state **ContainerCreating**. Any deployment on cluster fails with the error:

```
7m43s       Warning   FailedCreatePodSandBox   Pod          Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "de70c507fad8e3d980df32e130c579c6d241488e77c609d3da12acc5a7a6ec75" network for pod "coredns-5fb7747f65-nhxgd": NetworkPlugin cni failed to set up pod "coredns-5fb7747f65-nhxgd_kube-system" network: add cmd: failed to assign an IP address to container
```

![DeepinScreenshot_select-area_20191004161237](https://user-images.githubusercontent.com/5689132/66202050-70ade800-e6c2-11e9-89b0-52ad1c941eb9.png)

**What you expected to happen?**
Pods to be deployed normally.

**How to reproduce it?**
```
eksctl create-cluster -f <config.yml>
```

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: k8s-dev-test
  region: ap-south-1

vpc:
  id: "vpc-xxx"
  subnets:
    public:
      ap-south-1a:
          id: "subnet-xxx"
      ap-south-1b:
          id: "subnet-yyy"
nodeGroups:
  - name: worker-ng1
    labels: { role: worker1 }
    instanceType: t3.medium
    minSize: 2
    maxSize: 3
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        ebs: true
        fsx: true
        efs: true
        albIngress: true
        xRay: true
        cloudWatch: true
    privateNetworking: false
    securityGroups:
      withShared: true
      withLocal: true
      attachIDs: ['sg-xyz'] # extra-sg
    tags:
      'environment': 'dev'
```

**Anything else we need to know?**
There are enough IP Addresses available (around 1000) but even the deployment of CoreDNS fails (which is a part of kube-system).

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.5.3"}
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:18:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.10-eks-5ac0f1", GitCommit:"5ac0f1d9ab2c254ea2b0ce3534fd72932094c6e1", GitTreeState:"clean", BuildDate:"2019-08-20T22:39:46Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
```
