### ISSUE TITLE
Add AWS_PROFILE env to kubeconfig

### ISSUE THREAD

**Issue by mr-karan** [weaveworks/eksctl#1407]
**Why do you want this feature?**
While writing to `~/.kube/config` we can detect the `AWS_PROFILE` value and substitute the same in the section 

```
      command: aws
      env:
      - name: AWS_PROFILE
        value: XYZ
```

**What feature/behavior/change do you want?**
While updating the `kubeconfig` the env section is `NULL`. We can update it with the correct AWS_PROFILE variable
