### ISSUE TITLE
Ipv6 Route table was not created when AutoAllocateIPv6 is set

### ISSUE THREAD

**Issue by VincentCouzij** [weaveworks/eksctl#1464]
**What happened?**
When using the AutoAllocateIPv6 option in the cluster.yml config it creates a cluster with ipv6 subnets but the route table does not contain the ipv6 routing to the internet gateway 

```
Destination         Target
::/0                InternetgatewayName 
```

**What you expected to happen?**
The ipv6 route table route to be added when creating a cluster

**How to reproduce it?**
Use the following config
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-development
  region: eu-central-1


vpc:
  cidr: 10.10.0.0/16
  autoAllocateIPv6: true
  nat:
    gateway: Disable

nodeGroups:
  - name: ng-1
    instanceType: t2.medium 
    minSize: 1
    maxSize: 1
    desiredCapacity: 1
    volumeSize: 20
    volumeType: gp2
    ssh: # use existing EC2 key
      publicKeyName: eks-development 
    iam:
      withAddonPolicies:
        albIngress: true
        autoScaler: true
```

**Anything else we need to know?**
-

**Versions**
Please paste in the output of these commands:
```
$ eksctl version 0.7.0
$ kubectl version v1.16.1
```

**Logs**
-
