### ISSUE TITLE
CertManager: it's supported as a policy but no examples to run it

### ISSUE THREAD

**Issue by genbutsu** [weaveworks/eksctl#1514]
**Why do you want this feature?**
The examples to run cert-manager request that you save a user inside the issuer, but eksctl has a support policy to manage route53 so it's supposed (?) it has different (simpler) management with eksctl (?)

**What feature/behavior/change do you want?**
an example to setup Issuer with Cert-manager using the policy 'certManager: true'

**Comment by whereisaaron** [comment]
Hi @genbutsu. If you enable `certManager: true` then anything running in your cluster can manage your Route53 domains to their heart’s content, so you can then just deploy `cert-manager` and use it with no credentials required. You can restrict that access with `kube2iam` or `kaim` if you wish. That was the way it was done until recently.

If you are using a new 1.14 cluster you don’t need to enable that instance policy. And you can get a secure role delegation without `kube2iam` or `kaim`, using IAM Role Service Accounts instead:

1) Create a Managed Policy ‘Foo’ in IAM similar to below. Copy and paste in the Managed Policy ARN for the Foo policy you created.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "route53:GetChange",
            "Resource": "arn:aws:route53:::change/*"
        },
        {
            "Effect": "Allow",
            "Action": "route53:ChangeResourceRecordSets",
            "Resource": "arn:aws:route53:::hostedzone/*"
        },
        {
            "Effect": "Allow",
            "Action": "route53:ListHostedZonesByName",
            "Resource": "*"
        }
    ]
}
```

2) Configure an IAM Service Account Role in your `eksctl` cluster config file, e.g.

```
iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: cert-manager
        namespace: cert-manager
        labels:
          aws-usage: cluster-ops
      attachPolicyARNs:
      - 'arn:aws:iam::123456789012:policy/Foo'
```

Let `eksctl` create the Role, `NameSpace`, and `ServiceAccount`
```
eksctl create iamserviceaccount --config-file=foo.yaml
```

3) Deploy `cert-manager` to the `cert-manager` namespace with `helm`

`eksctl` will have already create the `ServiceAccount` so configure `helm` to just to use it rather than create another.
```
serviceAccount:
  create: false
  name: cert-manager
```

4) Create a `ClusterIssuer` similar to below. There is no need for credentials, as the IAM Service Account Role will be automatically projected into the `cert-manager` container and `cert-manager` will pick them up as ambient credentials. Only `cert-manager` receives these credentials, and other workloads can’t mess with your DNS 🎉 
```
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: soa@example.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress: {}
    - selector:
        dnsZones:
        - example.com
        - something.org
      dns01:
        route53:
          region: us-east-2
```

Ref:
https://eksctl.io/usage/iamserviceaccounts/
https://docs.cert-manager.io/en/latest/tasks/issuers/setup-acme/dns01/route53.html
https://docs.cert-manager.io/en/latest/getting-started/install/kubernetes.html#installing-with-helm
