### ISSUE TITLE
IAM service account with wildcard name doesn't work

### ISSUE THREAD

**Issue by swoldemi** [weaveworks/eksctl#1526]
I am trying to create a cluster using a ClusterConfig. In this config I have:
```yaml
iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: "*"
        namespace: somenamespace
      attachPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "someawsservice:SomeAction"
            Resource: "*"
```
Is there anyway to wildcard `name` in the config so that all accounts within a namespace can use it? As it stands (using "*"), the CloudFormation stack that is created to apply this service account to the cluster uses the name as the suffix for the stack name. The stack will (and did) fail to create because asterisks are not accepted within the CloudFormation stack name regex.

 It would be really convenient to have this policy be created and applied to the ServiceAccount sequentially after the cluster and node group is created (opposed to having to go back and run another command).

Edit: I have also tried not including name all together, but it is a required parameter.

I apologize if I missed some documentation or an existing issue.
