### ISSUE TITLE
DOCS: Update IAM Policies

### ISSUE THREAD

**Issue by cdenneen** [weaveworks/eksctl#1580]
Current version of the IAM Policies document includes only ImageBuilder and EBS policy descriptions. I think it is useful to have all the policies documented here with up to date information on their purpose.

https://github.com/weaveworks/eksctl/blob/master/site/content/usage/09-iam-policies.md

## Supported IAM add-on policies

Example of all supported add-on policies:

```yaml
nodeGroups:
  - name: ng-1
    instanceType: m5.xlarge
    desiredCapacity: 1
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        ebs: true
        fsx: true
        efs: true
        albIngress: true
        xRay: true
        cloudWatch: true
```

### Image Builder Policy

The `imageBuilder` policy allows for full ECR (Elastic Container Registry) access. This is useful for building, for
example, a CI server that needs to push images to ECR.

### EBS Policy

The `ebs` policy enables the new EBS CSI (Elastic Block Store Container Storage Interface) driver.

[comment]: <> (TODO: One section per addon and brief explanation of what it is )

If you look there is a *comment* (Line 40) for a TODO but you can't visibly see that and I don't see an open issue for this so this Issue should cover tracking for this.

- [X]        imageBuilder: true
- [ ]        autoScaler: true
- [ ]        externalDNS: true
- [ ]        certManager: true
- [ ]        appMesh: true
- [X]        ebs: true
- [ ]        fsx: true
- [ ]        efs: true
- [ ]        albIngress: true
- [ ]        xRay: true
- [ ]        cloudWatch: true
