### ISSUE TITLE
delete nodegroup with --only-missing will delete the nodegroups in my config and not the ones that are not in it

### ISSUE THREAD

**Issue by delpede** [weaveworks/eksctl#1591]
In the process of updating my workernodes, I typically add update the names of the nodegroups in my config, and then create new nodegroups with
eksctl --profile my-aws create nodegroup -f config.yaml
And then I'll delete the old nodegroups with
eksctl --profile my-aws delete nodegroup -f config.yaml --only-missing
That would delete the nodesgroups that are NOT in my config.

What I'm seeing now is this
 eksctl --profile pure-prod delete nodegroup -f eks-pure-prod-west-cluster-config.yaml  --only-missing

> [ℹ]  eksctl version 0.10.2
> [ℹ]  using region eu-west-1
> [ℹ]  comparing 2 nodegroups defined in the given config ("eks-pure-prod-west-cluster-config.yaml") against remote state
> [ℹ]  nodegroup "eks-pure-prod-recordlog-ng-20191121" present in the cluster, but missing from the given config
> [ℹ]  combined include rules: eks-pure-prod-recordlog-ng-20191121
> [ℹ]  no nodegroups present in the current set were included by the filter
> [ℹ]  combined exclude rules: eks-pure-prod-recordlog-ng-20191121b,eks-pure-prod-worker-ng-20191121b
> [ℹ]  2 nodegroups (eks-pure-prod-recordlog-ng-20191121b, eks-pure-prod-worker-ng-20191121b) were excluded (based on the include/exclude rules)
> [ℹ]  (plan) would delete 0 nodegroups from auth ConfigMap in cluster "eks-pure-prod"
> [ℹ]  (plan) would drain 0 nodegroup(s) in cluster "eks-pure-prod"
> [ℹ]  (plan) would delete 0 nodegroups from cluster "eks-pure-prod"
> [ℹ]  (plan) no tasks
> [✔]  (plan) would have deleted 0 nodegroup(s) from cluster "eks-pure-prod"
> 

I would expect it to delete the nodegroup eks-pure-prod-recordlog-ng-20191121 as that is not in the config, but it doesn't select any

If I then do 
eksctl --profile pure-prod delete nodegroup -f eks-pure-prod-west-cluster-config.yaml  --include='*' --only-missing
It will instead delete the nodegroups in my config

> 
> [ℹ]  eksctl version 0.10.2
> [ℹ]  using region eu-west-1
> [ℹ]  comparing 2 nodegroups defined in the given config ("eks-pure-prod-west-cluster-config.yaml") against remote state
> [ℹ]  nodegroup "eks-pure-prod-recordlog-ng-20191121" present in the cluster, but missing from the given config
> [ℹ]  combined include rules: eks-pure-prod-recordlog-ng-20191121,*
> [ℹ]  2 nodegroups (eks-pure-prod-recordlog-ng-20191121b, eks-pure-prod-worker-ng-20191121b) were included (based on the include/exclude rules)
> [ℹ]  combined exclude rules: eks-pure-prod-recordlog-ng-20191121b,eks-pure-prod-worker-ng-20191121b
> [ℹ]  no nodegroups present in the current set were excluded by the filter
> [ℹ]  (plan) would delete 2 nodegroups from auth ConfigMap in cluster "eks-pure-prod"
> [ℹ]  (plan) would drain 2 nodegroup(s) in cluster "eks-pure-prod"
> [ℹ]  (plan) would delete 2 nodegroups from cluster "eks-pure-prod"
> [ℹ]  (plan) 2 parallel tasks: { delete nodegroup "eks-pure-prod-recordlog-ng-20191121b" [async], delete nodegroup "eks-pure-prod-worker-ng-20191121b" [async] }
> [✔]  (plan) would have deleted 2 nodegroup(s) from cluster "eks-pure-prod"
> [!]  no changes were applied, run again with '--approve' to apply the changes
> 

Cluster has the following nodegroups

> eksctl --profile pure-prod get nodegroups --cluster eks-pure-prod
> CLUSTER         NODEGROUP                               CREATED                 MIN SIZE        MAX SIZE        DESIRED CAPACITY        INSTANCE TYPE   IMAGE ID
> eks-pure-prod   eks-pure-prod-recordlog-ng-20191121     2019-11-21T06:36:51Z    3               3               3                       m5.2xlarge      ami-0f2a613c0056a1914
> eks-pure-prod   eks-pure-prod-recordlog-ng-20191121b    2019-11-21T08:04:55Z    3               3               3                       m5.2xlarge      ami-0f2a613c0056a1914
> eks-pure-prod   eks-pure-prod-worker-ng-20191121b       2019-11-21T08:04:55Z    3               3               3                       m5.2xlarge      ami-0f2a613c0056a1914

The config.yaml looks like this

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-pure-prod
  region: eu-west-1

vpc:
  id: "vpc-"
  subnets:
    public:
      eu-north-1a: { id: subnet- }
      eu-north-1b: { id: subnet- }
    private:
      eu-north-1a: { id: subnet- }
      eu-north-1b: { id: subnet- }
      eu-north-1c: { id: subnet- }

nodeGroups:
  - name: eks-pure-prod-worker-ng-20191121b
    labels: { role: workers }
    instanceType: m5.2xlarge
    desiredCapacity: 3
    privateNetworking: true
    volumeSize: 200
    volumeType: gp2
    volumeEncrypted: true
    ami: ami-0f2a613c0056a1914
    amiFamily: AmazonLinux2
    ssh:
      allow: True
      publicKeyName: aws-eks-pure-prod
    securityGroups:
      withShared: true
      withLocal: true
      attachIDs: ["sg-"]
    preBootstrapCommands:
      - "systemctl restart taniumclient"

  - name: eks-pure-prod-recordlog-ng-20191121b
    labels: { role: kafka }
    instanceType: m5.2xlarge
    desiredCapacity: 3
    privateNetworking: true
    volumeSize: 200
    volumeType: gp2
    volumeEncrypted: true
    ami: ami-0f2a613c0056a1914
    amiFamily: AmazonLinux2
    ssh:
      allow: True
      publicKeyName: aws-eks-pure-prod
    securityGroups:
      withShared: true
      withLocal: true
      attachIDs: ["sg-"]
    taints:
      dedicated: "recordlog:NoSchedule"
    preBootstrapCommands:
      - "systemctl restart taniumclient"

```

I'm running Fedora 30

$ eksctl 0.10.2

$ kubectl version
Client Version: v1.15.2"
Server V"v1.14.6-eks-5047ed"
