### ISSUE TITLE
eksctl creates VPC even with existing VPC info provided

### ISSUE THREAD

**Issue by zachahuy02** [weaveworks/eksctl#1595]
**What happened?**
A description of actual behavior (with error messages).

I have a config file with existing VPC configured but eksctl still tries to create a new VPC.

**What you expected to happen?**

It should just use the provided VPC info and not create new VPC.

**How to reproduce it?**
Include the steps to reproduce the bug
1. Create a Config file
```yaml
# An example of ClusterConfig object using an existing VPC:
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: aws-apple-sample-cluster
  region: us-west-2
  version: 1.12

vpc:
  id: vpc-0a08f2002d63c6684  # (optional, must match VPC ID used for each subnet below)
  cidr: 100.71.0.0/16     # (optional, must match CIDR used by the given VPC)
  subnets:
    # must provide 'private' and/or 'public' subnets by availibility zone as shown
    private:
      us-west-2a:
        id: subnet-0c68a25b4c1bb336d
        cidr: 100.71.0.0/18 # (optional, must match CIDR used by the given subnet)

      us-west-2b:
        id: subnet-0a00289e388d4990e
        cidr: 100.71.64.0/18  # (optional, must match CIDR used by the given subnet)

      us-west-2c:
        id: subnet-046e05947a0ed890b
        cidr: 100.71.128.0/18   # (optional, must match CIDR used by the given subnet)
```

2. Create a new cluster `eksctl create cluster --kubeconfig=./eksctl_config.yaml`
3. See the cloudformation template it created

```
[ℹ]  eksctl version 0.10.2
[ℹ]  using region us-west-2
[ℹ]  setting availability zones to [us-west-2b us-west-2d us-west-2a]
[ℹ]  subnets for us-west-2b - public:192.168.0.0/19 private:192.168.96.0/19
[ℹ]  subnets for us-west-2d - public:192.168.32.0/19 private:192.168.128.0/19
[ℹ]  subnets for us-west-2a - public:192.168.64.0/19 private:192.168.160.0/19
[ℹ]  nodegroup "ng-dd5d2da4" will use "ami-05d586e6f773f6abf" [AmazonLinux2/1.14]
[ℹ]  using Kubernetes version 1.14
[ℹ]  creating EKS cluster "hilarious-mushroom-1574406602" in "us-west-2" region
[ℹ]  will create 2 separate CloudFormation stacks for cluster itself and the initial nodegroup
[ℹ]  if you encounter any issues, check CloudFormation console or try 'eksctl utils describe-stacks --region=us-west-2 --cluster=hilarious-mushroom-1574406602'
[ℹ]  CloudWatch logging will not be enabled for cluster "hilarious-mushroom-1574406602" in "us-west-2"
[ℹ]  you can enable it with 'eksctl utils update-cluster-logging --region=us-west-2 --cluster=hilarious-mushroom-1574406602'
[ℹ]  Kubernetes API endpoint access will use default of {publicAccess=true, privateAccess=false} for cluster "hilarious-mushroom-1574406602" in "us-west-2"
[ℹ]  2 sequential tasks: { create cluster control plane "hilarious-mushroom-1574406602", create nodegroup "ng-dd5d2da4" }
[ℹ]  building cluster stack "eksctl-hilarious-mushroom-1574406602-cluster"
[ℹ]  deploying stack "eksctl-hilarious-mushroom-1574406602-cluster"
[✖]  unexpected status "ROLLBACK_IN_PROGRESS" while waiting for CloudFormation stack "eksctl-hilarious-mushroom-1574406602-cluster"
[ℹ]  fetching stack events in attempt to troubleshoot the root cause of the failure
[✖]  AWS::EC2::InternetGateway/InternetGateway: CREATE_FAILED – "API: ec2:CreateInternetGateway You are not authorized to perform this operation."
[✖]  AWS::EC2::EIP/NATIP: CREATE_FAILED – "Resource creation cancelled"
[✖]  AWS::IAM::Role/ServiceRole: CREATE_FAILED – "API: iam:CreateRole User: arn:aws:sts::000890411542:assumed-role/admin/session is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::000890411542:role/eksctl-hilarious-mushroom-1574406602-c-ServiceRole-15B9UVAX2S24B with an explicit deny"
[✖]  AWS::EC2::VPC/VPC: CREATE_FAILED – "API: ec2:CreateVpc You are not authorized to perform this operation."
[ℹ]  1 error(s) occurred and cluster hasn't been created properly, you may wish to check CloudFormation console
[ℹ]  to cleanup resources, run 'eksctl delete cluster --region=us-west-2 --name=hilarious-mushroom-1574406602'
[✖]  waiting for CloudFormation stack "eksctl-hilarious-mushroom-1574406602-cluster": ResourceNotReady: failed waiting for successful resource state
[✖]  failed to create cluster "hilarious-mushroom-1574406602"

```

**Anything else we need to know?**
What OS are you using, are you using a downloaded binary or did you compile eksctl, what type of AWS credentials are you using (i.e. default/named profile, MFA) - please don't include actual credentials though!

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.10.2"}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-19T22:12:47Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"darwin/amd64"}
```
