### ISSUE TITLE
v0.10.2 Not supporting Spot Instances?

### ISSUE THREAD

**Issue by eightlimbed** [weaveworks/eksctl#1600]
**What happened?**
I ran `eksctl create cluster -f cluster.yaml` and got this error:
```
2019-11-23T16:10:03-08:00 [✖]  loading config file "cluster.yaml": error unmarshaling JSON: while decoding JSON: json: unknown field "instancesDistribution"
```

**What you expected to happen?**
I should be able to configure my cluster to use spot instances, as I could in previous versions of eksctl

**How to reproduce it?**
Use this yaml config and do `eksctl create cluster -f cluster.yaml`
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: lee
  region: us-west-2
  version: "1.14"

managedNodeGroups:
  - name: managed-ng-1
    minSize: 2
    maxSize: 5
    volumeSize: 100
    volumeType: gp2
    instancesDistribution:
      instanceTypes: ["m5.large", "m5.xlarge"]
      onDemandPercentageAboveBaseCapacity: 0
      
    ssh:
      allow: true

    kubeletExtraConfig:
      kubeReserved:
        cpu: "300m"
        memory: "300Mi"
        ephemeral-storage: "1Gi"
      kubeReservedCgroup: "/kube-reserved"
      systemReserved:
        cpu: "300m"
        memory: "300Mi"
        ephemeral-storage: "1Gi"
      evictionHard:
        memory.available: "200Mi"
        nodefs.available: "10%"
      featureGates:
        DynamicKubeletConfig: true
        RotateKubeletServerCertificate: true

    tags:
      nodegroup-role: worker
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/lee: "owned"

    iam:
      withAddonPolicies:
        autoScaler: true
```

**Anything else we need to know?**
What OS are you using, are you using a downloaded binary or did you compile eksctl, what type of AWS credentials are you using (i.e. default/named profile, MFA) - please don't include actual credentials though!

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.10.2"}
$ kubectl version
Client Version: v1.16.3
```
