### ISSUE TITLE
eksctl fails on region sa-east-1 when I try create a cluster

### ISSUE THREAD

**Issue by luismoraescielo** [weaveworks/eksctl#1606]
When we try to create an EKS cluster using eksctl it fails if I'm not specific the AMI to be used on region  **sa-east-1**:

Example:

cluster.yaml:
```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: sample-istio-cluster
  region: sa-east-1

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 10
  - name: ng-2
    instanceType: m5.xlarge
    desiredCapacity: 2
```

And the result is:

➜  eks eksctl create cluster -f cluster.yaml
[ℹ]  eksctl version 0.8.0
[ℹ]  using region sa-east-1
[ℹ]  setting availability zones to [sa-east-1a sa-east-1c sa-east-1b]
[ℹ]  subnets for sa-east-1a - public:192.168.0.0/19 private:192.168.96.0/19
[ℹ]  subnets for sa-east-1c - public:192.168.32.0/19 private:192.168.128.0/19
[ℹ]  subnets for sa-east-1b - public:192.168.64.0/19 private:192.168.160.0/19
[✖]  unable to determine AMI to use: unable to determine AMI for region sa-east-1, version 1.14, instance type m5.large and image family AmazonLinux2

This happens only in sa-east-1.

And when I put the AMI its works:

cluster.yaml:
```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: sample-istio-cluster
  region: sa-east-1

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 10
    ami: ami-010ffc66e06c843b2
  - name: ng-2
    instanceType: m5.xlarge
    desiredCapacity: 2
    ami: ami-010ffc66e06c843b2
```
ℹ]  eksctl version 0.8.0
[ℹ]  using region sa-east-1
[ℹ]  setting availability zones to [sa-east-1b sa-east-1a sa-east-1c]
[ℹ]  subnets for sa-east-1b - public:192.168.0.0/19 private:192.168.96.0/19
[ℹ]  subnets for sa-east-1a - public:192.168.32.0/19 private:192.168.128.0/19
[ℹ]  subnets for sa-east-1c - public:192.168.64.0/19 private:192.168.160.0/19
[ℹ]  nodegroup "ng-1" will use "ami-010ffc66e06c843b2" [AmazonLinux2/1.14]
[ℹ]  nodegroup "ng-2" will use "ami-010ffc66e06c843b2" [AmazonLinux2/1.14]
[ℹ]  using Kubernetes version 1.14
[ℹ]  creating EKS cluster ...

**Comment by martina-if** [comment]
Hi @luismoraescielo , Thank you for reporting this issue! The São Paulo region is supported in eksctl but we haven't added the AMI ids for the static resolver yet. 

I submitted a PR to fix this. Here is the link in case you want to track it: 
https://github.com/weaveworks/eksctl/pull/1674

In the meantime, you can use one of the automatic resolvers: `auto` or `auto-ssm` which is newer. 

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: sample-istio-cluster
  region: sa-east-1

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 10
    ami: auto
  - name: ng-2
    instanceType: m5.xlarge
    desiredCapacity: 2
    ami: auto-ssm
```
