### ISSUE TITLE
Ability to cusomize name of nodegroup instance

### ISSUE THREAD

**Issue by mshivaramie22** [weaveworks/eksctl#1639]
Looks like currently there is no way to customise the instances that are created as part of nodegroup for EKS. This is making the EKS worker nodes look differently than the other instances in our organisation. We are trying to follow a naming pattern for these nodes and failing to do so. 

Please let the users choose the naming pattern of instances created by Nodegroups.

*Before creating a feature request, please search existing feature requests to see if you find a similar one. If there is a similar feature request please up-vote it and/or add your comments to it instead*

**Why do you want this feature?**
To make the node group instance name in-line with the existing instances' naming convention.

**What feature/behavior/change do you want?**
An configuration item to set as a prefix or a name pattern for the node group instances.

Do not hesitate, when appropriate, to share the exact commands or API you would like, and/or to share a diagram (e.g.: asciiflow.com): "a picture is worth a thousand words".

**Comment by spaghettifunk** [comment]
Hi @mshivaramie22 

Thanks for opening this issue! I was wondering if it would make sense to ad extra `configuration` parameter in the specs for a `nodeGroup`. Given the example below, we could add the extra flag `instancePrefix: ....`

```yaml
nodeGroups:
  - name: worker-ng-1
    labels:
      role: workers
      autoscaling: enabled
      purpose: ci-worker
    instanceType: m5.large
    instancePrefix: my-prefix
    desiredCapacity: 1
    minSize: 1
    maxSize: 3
    tags:
      environment: development
```
Each instance would then be named`my-prefix-cluster-1-worker-ng-1-Node`
