### ISSUE TITLE
eksctl kube config

### ISSUE THREAD

**Issue by bscott** [weaveworks/eksctl#1650]
I'm having an issue with the kubeconfig that EKSCTL generated, it uses `aws eks get-token` sub-command to use in auth against EKS but the latest AWS CLI does not support `get-token`. 

```
NAME
       eks -

DESCRIPTION
       Amazon  Elastic Container Service for Kubernetes (Amazon EKS) is a man-
       aged service that makes it easy for you to run Kubernetes on AWS  with-
       out  needing to stand up or maintain your own Kubernetes control plane.
       Kubernetes is an open-source  system  for  automating  the  deployment,
       scaling, and management of containerized applications.

       Amazon EKS runs up-to-date versions of the open-source Kubernetes soft-
       ware, so you can use all the existing  plugins  and  tooling  from  the
       Kubernetes community. Applications running on Amazon EKS are fully com-
       patible with applications running on any standard  Kubernetes  environ-
       ment,  whether  running  in  on-premises data centers or public clouds.
       This means that you can easily migrate any standard Kubernetes applica-
       tion to Amazon EKS without any code modification required.

AVAILABLE COMMANDS
       o create-cluster

       o delete-cluster

       o describe-cluster

       o describe-update

       o help

       o list-clusters

       o list-updates

       o update-cluster-version

       o update-kubeconfig

       o wait



                                                                         EKS()
``` 

Kube Config:

```
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - eks
      - get-token
      - --cluster-name
      - eks-cluster
      - --region
      - us-west-2
      command: aws
```
