### ISSUE TITLE
CREATE_FAILED – "Property ManagedPolicyArns contains duplicate values."

### ISSUE THREAD

**Issue by davisford** [weaveworks/eksctl#1686]
**What happened?**
A description of actual behavior (with error messages).

```sh
$ eksctl create cluster -f cluster.yaml
[ℹ]  eksctl version 0.11.1
[ℹ]  using region us-east-1
[ℹ]  setting availability zones to [us-east-1d us-east-1b]
[ℹ]  subnets for us-east-1d - public:192.168.0.0/19 private:192.168.64.0/19
[ℹ]  subnets for us-east-1b - public:192.168.32.0/19 private:192.168.96.0/19
[ℹ]  using Kubernetes version 1.14
[ℹ]  creating EKS cluster "dev-teams-cluster" in "us-east-1" region with managed nodes
[ℹ]  4 nodegroups (managed-ng-apps, managed-ng-dbs-1a, managed-ng-dbs-1b, managed-ng-dbs-1c) were included (based on the include/exclude rules)
[ℹ]  will create a CloudFormation stack for cluster itself and 0 nodegroup stack(s)
[ℹ]  will create a CloudFormation stack for cluster itself and 4 managed nodegroup stack(s)
[ℹ]  if you encounter any issues, check CloudFormation console or try 'eksctl utils describe-stacks --region=us-east-1 --cluster=dev-teams-cluster'
[ℹ]  CloudWatch logging will not be enabled for cluster "dev-teams-cluster" in "us-east-1"
[ℹ]  you can enable it with 'eksctl utils update-cluster-logging --region=us-east-1 --cluster=dev-teams-cluster'
[ℹ]  Kubernetes API endpoint access will use default of {publicAccess=true, privateAccess=false} for cluster "dev-teams-cluster" in "us-east-1"
[ℹ]  2 sequential tasks: { create cluster control plane "dev-teams-cluster", 4 parallel sub-tasks: { create managed nodegroup "managed-ng-apps", create managed nodegroup "managed-ng-dbs-1a", create managed nodegroup "managed-ng-dbs-1b", create managed nodegroup "managed-ng-dbs-1c" } }
[ℹ]  building cluster stack "eksctl-dev-teams-cluster-cluster"
[ℹ]  deploying stack "eksctl-dev-teams-cluster-cluster"
[ℹ]  building managed nodegroup stack "eksctl-dev-teams-cluster-nodegroup-managed-ng-dbs-1c"
[ℹ]  building managed nodegroup stack "eksctl-dev-teams-cluster-nodegroup-managed-ng-apps"
[ℹ]  building managed nodegroup stack "eksctl-dev-teams-cluster-nodegroup-managed-ng-dbs-1a"
[ℹ]  building managed nodegroup stack "eksctl-dev-teams-cluster-nodegroup-managed-ng-dbs-1b"
[ℹ]  deploying stack "eksctl-dev-teams-cluster-nodegroup-managed-ng-dbs-1b"
[ℹ]  deploying stack "eksctl-dev-teams-cluster-nodegroup-managed-ng-dbs-1c"
[ℹ]  deploying stack "eksctl-dev-teams-cluster-nodegroup-managed-ng-dbs-1a"
[ℹ]  deploying stack "eksctl-dev-teams-cluster-nodegroup-managed-ng-apps"
[✖]  unexpected status "ROLLBACK_IN_PROGRESS" while waiting for CloudFormation stack "eksctl-dev-teams-cluster-nodegroup-managed-ng-dbs-1c"
[ℹ]  fetching stack events in attempt to troubleshoot the root cause of the failure
[✖]  AWS::IAM::Role/NodeInstanceRole: CREATE_FAILED – "Property ManagedPolicyArns contains duplicate values."
[ℹ]  1 error(s) occurred and cluster hasn't been created properly, you may wish to check CloudFormation console
[ℹ]  to cleanup resources, run 'eksctl delete cluster --region=us-east-1 --name=dev-teams-cluster'
[✖]  waiting for CloudFormation stack "eksctl-dev-teams-cluster-nodegroup-managed-ng-dbs-1c": ResourceNotReady: failed waiting for successful resource state
[✖]  failed to create cluster "dev-teams-cluster"
```

*cluster.yaml*

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dev-teams-cluster
  region: us-east-1

managedNodeGroups:
  - name: managed-ng-apps
    instanceType: t3.medium
    minSize: 3
    maxSize: 10
    desiredCapacity: 6
    volumeSize: 20
    ssh:
      allow: false
    labels: { role: worker }
    tags:
      nodegroup-role: worker
    iam:
      attachPolicyARNs:
        # EKS worker nodes require the following two policies at least
        # https://github.com/weaveworks/eksctl/issues/1576#issuecomment-555355399
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        ebs: true

  - name: managed-ng-dbs-1a
    instanceType: m4.large
    availabilityZones: ["us-east-1a"]
    desiredCapacity: 1
    labels: { role: db }
    tags:
      nodegroup-role: db
    iam:
      attachPolicyARNs:
        # EKS worker nodes require the following two policies at least
        # https://github.com/weaveworks/eksctl/issues/1576#issuecomment-555355399
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      withAddonPolicies:
        ebs: true
        fsx: true
        efs: true
  - name: managed-ng-dbs-1b
    instanceType: m4.large
    availabilityZones: ["us-east-1b"]
    desiredCapacity: 1
    labels: { role: db }
    tags:
      nodegroup-role: db
    iam:
      attachPolicyARNs:
        # EKS worker nodes require the following two policies at least
        # https://github.com/weaveworks/eksctl/issues/1576#issuecomment-555355399
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      withAddonPolicies:
        ebs: true
        fsx: true
        efs: true
  - name: managed-ng-dbs-1c
    instanceType: m4.large
    availabilityZones: ["us-east-1c"]
    desiredCapacity: 1
    labels: { role: db }
    tags:
      nodegroup-role: db
    iam:
      attachPolicyARNs:
        # EKS worker nodes require the following two policies at least
        # https://github.com/weaveworks/eksctl/issues/1576#issuecomment-555355399
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      withAddonPolicies:
        ebs: true
        fsx: true
        efs: true
```

**What you expected to happen?**
Expected it to deploy.  What happened prior to that was I tried to deploy the same yaml except without the `attachPolicyARNs` section but that failed because of this error:

```
[✖]  unexpected status "ROLLBACK_IN_PROGRESS" while waiting for CloudFormation stack "eksctl-dev-cluster-nodegroup-managed-ng-apps"
[ℹ]  fetching stack events in attempt to troubleshoot the root cause of the failure
[✖]  AWS::IAM::Policy/PolicyEBS: CREATE_FAILED – "Resource creation cancelled"
[✖]  AWS::IAM::Policy/PolicyExternalDNSHostedZones: CREATE_FAILED – "Resource creation cancelled"
[✖]  AWS::IAM::Policy/PolicyAutoScaling: CREATE_FAILED – "Resource creation cancelled"
[✖]  AWS::IAM::Policy/PolicyExternalDNSChangeSet: CREATE_FAILED – "Resource creation cancelled"
[✖]  AWS::EKS::Nodegroup/ManagedNodeGroup: CREATE_FAILED – "The provided role doesn't have the Amazon EKS Managed Policies associated with it. Please ensure the following policies [arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy, arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy, arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly] are attached (Service: AmazonEKS; Status Code: 400; Error Code: InvalidParameterException; Request ID: f7a5b1ef-8bcf-419c-947c-dd457d40814d)"
[ℹ]  1 error(s) occurred and cluster hasn't been created properly, you may wish to check CloudFormation console
[ℹ]  to cleanup resources, run 'eksctl delete cluster --region=us-east-1 --name=dev-cluster'
[✖]  waiting for CloudFormation stack "eksctl-dev-cluster-nodegroup-managed-ng-apps": ResourceNotReady: failed waiting for successful resource state
[✖]  failed to create cluster "dev-cluster"
```

So I found this [github issue possible workaround](https://github.com/weaveworks/eksctl/issues/1576#issuecomment-555355399).

I added in that section and tried again.  However, I'm now noting that `eksctl` did not rollback properly.  I have a half- baked cluster and the IAM policies it generated from the first run are still there.  I'm trying to figure out what it means by the duplicate  values, but I'm guessing maybe it didn't clean itself up from the first failure and now has a conflict with some IAM policy it is trying to create or else one of the policies I've manually attached is a dupe of one of the pre-baked policy names?

**How to reproduce it?**
Include the steps to reproduce the bug

YAML above.  

**Anything else we need to know?**
What OS are you using, are you using a downloaded binary or did you compile eksctl, what type of AWS credentials are you using (i.e. default/named profile, MFA) - please don't include actual credentials though!

Installed via brew weaveworks tap.

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.11.1"}
$ kc version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-13T11:52:32Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Unable to connect to the server: dial tcp: lookup B920E80C19A5597493504736E37E9E68.gr7.us-east-1.eks.amazonaws.com: no such host
```

**Logs**

**Comment by davisford** [comment]
3rd try -- I used `eksctl` to delete the two clusters above, and manually ensured all the resources were gone (vpc, iam, ec2, eks, etc.)

Then I tried again with this yaml:

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dev-teams
  region: us-east-1

managedNodeGroups:
  - name: managed-ng-apps
    instanceType: t3.medium
    availabilityZones:
      - us-east-1a
      - us-east-1b
      - us-east-1c
    minSize: 3
    maxSize: 10
    desiredCapacity: 6
    volumeSize: 20
    ssh:
      allow: false
    labels: { role: worker }
    tags:
      nodegroup-role: worker
    iam:
      attachPolicyARNs:
        # EKS worker nodes require the following two policies at least
        # https://github.com/weaveworks/eksctl/issues/1576#issuecomment-555355399
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        ebs: true

  - name: managed-ng-dbs
    instanceType: m4.large
    availabilityZones:
      - us-east-1a
      - us-east-1b
      - us-east-1c
    minSize: 3
    maxSize: 5
    desiredCapacity: 3
    labels: { role: db }
    tags:
      nodegroup-role: db
    iam:
      attachPolicyARNs:
        # EKS worker nodes require the following two policies at least
        # https://github.com/weaveworks/eksctl/issues/1576#issuecomment-555355399
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      withAddonPolicies:
        ebs: true
        fsx: true
        efs: true
```

Failed again with the same dupe value in a policy:

```sh
$ eksctl create cluster -f cluster.yaml
[ℹ]  eksctl version 0.11.1
[ℹ]  using region us-east-1
[ℹ]  setting availability zones to [us-east-1b us-east-1c]
[ℹ]  subnets for us-east-1b - public:192.168.0.0/19 private:192.168.64.0/19
[ℹ]  subnets for us-east-1c - public:192.168.32.0/19 private:192.168.96.0/19
[ℹ]  using Kubernetes version 1.14
[ℹ]  creating EKS cluster "dev-teams" in "us-east-1" region with managed nodes
[ℹ]  2 nodegroups (managed-ng-apps, managed-ng-dbs) were included (based on the include/exclude rules)
[ℹ]  will create a CloudFormation stack for cluster itself and 0 nodegroup stack(s)
[ℹ]  will create a CloudFormation stack for cluster itself and 2 managed nodegroup stack(s)
[ℹ]  if you encounter any issues, check CloudFormation console or try 'eksctl utils describe-stacks --region=us-east-1 --cluster=dev-teams'
[ℹ]  CloudWatch logging will not be enabled for cluster "dev-teams" in "us-east-1"
[ℹ]  you can enable it with 'eksctl utils update-cluster-logging --region=us-east-1 --cluster=dev-teams'
[ℹ]  Kubernetes API endpoint access will use default of {publicAccess=true, privateAccess=false} for cluster "dev-teams" in "us-east-1"
[ℹ]  2 sequential tasks: { create cluster control plane "dev-teams", 2 parallel sub-tasks: { create managed nodegroup "managed-ng-apps", create managed nodegroup "managed-ng-dbs" } }
[ℹ]  building cluster stack "eksctl-dev-teams-cluster"
[ℹ]  deploying stack "eksctl-dev-teams-cluster"
[ℹ]  building managed nodegroup stack "eksctl-dev-teams-nodegroup-managed-ng-dbs"
[ℹ]  building managed nodegroup stack "eksctl-dev-teams-nodegroup-managed-ng-apps"
[ℹ]  deploying stack "eksctl-dev-teams-nodegroup-managed-ng-apps"
[ℹ]  deploying stack "eksctl-dev-teams-nodegroup-managed-ng-dbs"
[✖]  unexpected status "ROLLBACK_IN_PROGRESS" while waiting for CloudFormation stack "eksctl-dev-teams-nodegroup-managed-ng-dbs"
[ℹ]  fetching stack events in attempt to troubleshoot the root cause of the failure
[✖]  AWS::IAM::Role/NodeInstanceRole: CREATE_FAILED – "Property ManagedPolicyArns contains duplicate values."
[ℹ]  1 error(s) occurred and cluster hasn't been created properly, you may wish to check CloudFormation console
[ℹ]  to cleanup resources, run 'eksctl delete cluster --region=us-east-1 --name=dev-teams'
[✖]  waiting for CloudFormation stack "eksctl-dev-teams-nodegroup-managed-ng-dbs": ResourceNotReady: failed waiting for successful resource state
[✖]  failed to create cluster "dev-teams"
```

**Comment by davisford** [comment]
The cluster was created, and if I query the node groups it says they are there...but I don't see node groups in the EKS console, and no EC2 instances have been spawned.

```
$ eksctl get cluster -n dev-teams -r us-east-1
NAME		VERSION	STATUS	CREATED			VPC			SUBNETS													SECURITYGROUPS
dev-teams	1.14	ACTIVE	2019-12-19T22:39:45Z	vpc-079237f339e39e609	subnet-01d9e49a307658432,subnet-049ca92288ae11845,subnet-04ed64a46d138f2a7,subnet-061e8efdde74c4970	sg-0023c0dd67dcced8b
```

```
$ eksctl get nodegroup --cluster dev-teams -r us-east-1
CLUSTER		NODEGROUP	CREATED			MIN SIZE	MAX SIZE	DESIRED CAPACITY	INSTANCE TYPE	IMAGE ID
dev-teams	managed-ng-apps	2019-12-19T22:50:00Z	3		10		6			t3.medium
dev-teams	managed-ng-dbs	2019-12-19T22:50:00Z	3		5		3			m4.large
```

**Comment by mucceli** [comment]
Hi @davisford,

I had exactly the same problem. I'm quite new with Kubernets and AWS enviroment, so 
I just want share how I skiped this problem. 
The **arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly** was the cause. I'm not sure what this policy does exactly, I was just following blog/tutorials on internet.

After comment this policy in my yaml file the cluster was create without problems. 

Make any sence to you?

**Comment by davisford** [comment]
Hi @mucceli thanks for the feedback.  I think the problem is a bit more fundamental.  The `eksctl` tool generates `CloudFormation` templates from either command line params, or JSON, or YAML configs.  My experience with the tool is that it is not suitable in its current state to define complex infrastructure like managed node groups across multiple AZs with configuration files.  

I ended up hand-crafting those myself with my own `CloudFormation` templates after studying the templates the tool generates and reading the docs on `CloudFormation`.   I think the `eksctl` tool is a great idea, but my feeling is that in its current state, it will end up causing you more frustration than it will help you.  Many times it generated invalid templates that would simply fail validation.  Other times, it generates stacks that don't understand how cloud formation will complain about resources that were already created by other stacks.

If you break it out into stacks -- the following templates make sense:

1. Create VPC and related network resources
2. Create IAM roles and resources needed for EKS
3. Create EKS Cluster resource
4. Create one or more managed node groups as needed

I broke my CloudFormation template stacks out like this, and we now have a reproducible and templated solution where we can spin up a proper cluster consistently.  

Fair warning: CloudFormation is nearly as frustrating... :)

**Comment by cPu1** [comment]
@davisford this is a configuration issue. Your `attachPolicyARNs` config specifies IAM policies that are already attached by eksctl, which is resulting in the duplicate values error:

```yaml
    iam:
      attachPolicyARNs:
        # These policies are already attached by eksctl and don't need to be specified here
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
```

All required worker node policies are attached by eksctl, so you don't need to specify them. If you go through the [documentation](https://eksctl.io/usage/eks-managed-nodegroups/), you'll notice that none of the example configs specify the required worker node policies, because it's handled by eksctl.

To help guard against this configuration issue, eksctl can deduplicate the policies before creating a role using them.
