### ISSUE TITLE
feat: Attaching Classic Load Balancers to NodeGroups

### ISSUE THREAD

**Issue by af12066** [weaveworks/eksctl#1706]
**Why do you want this feature?**

Similar to https://github.com/weaveworks/eksctl/issues/331

eksctl now supports attaching target groups for ALB to nodegroups when creating nodegroups, but CLB has not yet.

**What feature/behavior/change do you want?**

Adding a option for cluster.yaml like below:

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

nodeGroups:
  - name: ng1
    loadBalancerARNs:
      - ...
      - ...
```
