### ISSUE TITLE
Add Support for Auto-Deploying a Default Storage Class

### ISSUE THREAD

**Issue by christopherhein** [weaveworks/eksctl#175]
*Before creating a feature request, please search existing feature requests to see if you find a similar one. If there is a similar feature request please up-vote it and/or add your comments to it instead*

**Why do you want this feature?**
To ease the setup of EKS cluster for production usecases

**What feature/behavior/change do you want?**
When #132  gets merged if we have the possibility it would be nice to add an option to auto deploy a storageclass and make it the default.

The manifest that would need to be applied would be:

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2
  annotations:
    "storageclass.kubernetes.io/is-default-class": "true"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Retain
mountOptions:
  - debug
```
