### ISSUE TITLE
Security groups customization

### ISSUE THREAD

**Issue by etopeter** [weaveworks/eksctl#1773]
I'm trying to customize security group rules for worker nodes. Eksctl creates egress rule that allows all egress to 0.0.0.0/0. I can't have that in my environment and I'm trying to find a way to customize that.
Is there a way to customize that egress rule? If not is there any way to prevent eksctl from creating security group for worker and use provided security group ID? I could first create my custom security group and pass it to the cluster config.

**Comment by sayboras** [comment]
Please take a look on this one https://eksctl.io/examples/reusing-iam-and-vpc. If it's not working for your case, kindly share the config or the cli command so that we can check further.

**Comment by etopeter** [comment]
Thank you @sayboras for providing the link. This is what I was looking for. I made changes to my config and it looks something like this:
```
vpc:
  securityGroup: $ClusterSG
nodeGroups:
  - name: worker
    securityGroups:
      withShared: false
      withLocal: false
      attachIDs: [$WorkerSG]
```

This prevented eksctl from creating new security groups for worker nodes and attached existing ones to cluster and worker. Eksctl created cluster security group and attached existing one as "additional security group" to EKS cluster. Is there any way to prevent eksctl from creating cluster security group?
