### ISSUE TITLE
Using eksctl enable repo times out Waiting for Helm Operator to start, on Fargate

### ISSUE THREAD

**Issue by aksel-bondoe-defa** [weaveworks/eksctl#1789]
Trying to enable gitops for a cluster with:
EKSCTL_EXPERIMENTAL=true eksctl \
        enable repo \
        --git-url git@github.com:aksel-bondoe-defa/kubernetes.git \
        --git-email aksel.bondo@defa.com \
        --cluster cloudcharge \
        --region ap-northeast-1

The result is: Error: timed out waiting for Helm Operator's pod to be created
Just some seconds later, the Helm operator pod is up and running.

Is there some way of making eksctl wait a bit longer before timing out?

**Comment by Shadaeiou** [comment]
I ran into the same issue while following this tutorial: https://eksctl.io/gitops-quickstart/setup-gitops/

If you run `kubectl get pods --all-namespaces` and see that all of the flux pods are stuck in status pending it may be indicative of the node not having enough CPU/memory to run all of the pods. 

In my case, in AWS my node was using a t3.micro and was experiencing the issue. I started a new node with a t3.medium and everything worked smoothly.

**Comment by adamlash** [comment]
Noting this is also a problem using EKS Fargate. It seems the Fargate-based Pods take about a minute or so to spin up so the CLI times out. 

May be a good idea to see if timeouts can be configured to allow more time for the Helm Operator's pod to arrive.

**Comment by gmarchand** [comment]
1. I create a cluster with this config : `eksctl create cluster -f cluster.yml`

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: gma-cluster-demo
  region: eu-west-1
  
vpc:
  subnets:
    private:
      eu-west-1a: { id: subnet-x }
      eu-west-1b: { id: subnet-x }
      eu-west-1c: { id: subnet-x }
    public:
      eu-west-1a: { id: subnet-x }
      eu-west-1b: { id: subnet-x }
      eu-west-1c: { id: subnet-x }

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

# https://github.com/weaveworks/eksctl/blob/master/examples/16-fargate-profile.yaml
# https://eksctl.io/usage/fargate/
fargateProfiles:
  - name: fp-default
    selectors:
      # All workloads in the "default" Kubernetes namespace will be
      # scheduled onto Fargate:
      - namespace: default
      # All workloads in the "kube-system" Kubernetes namespace will be
      # scheduled onto Fargate:
      - namespace: kube-system
  - name: fp-dev
    selectors:
      # All workloads in the "dev" Kubernetes namespace matching the following
      # label selectors will be scheduled onto Fargate:
      - namespace: dev
        labels:
          env: dev
          checks: passed
```

2. enable repo and install Flux : `eksctl enable repo -f cluster.yml --git-url={{.GIT}} --git-email={{.EMAIL}}`

3. All Flux pods are stuck
```
kubectl get pods --all-namespaces
NAMESPACE     NAME                                  READY   STATUS    RESTARTS   AGE
flux          flux-6c478cd775-48vps                 0/1     Pending   0          74m
flux          flux-helm-operator-8687676b89-jz27c   0/1     Pending   0          74m
flux          memcached-5dcd7579-nzfgp              0/1     Pending   0          74m
flux          tiller-deploy-69547b56b4-j2w9z        0/1     Pending   0          74m
```
