### ISSUE TITLE
Bug in validating and defaulting cluster endpoint cluster in `create cluster -f`

### ISSUE THREAD

**Issue by martina-if** [weaveworks/eksctl#1852]
**What happened?**

config file:
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: test-endpoint
  region: ap-southeast-2
iam:
  serviceRolePermissionsBoundary: "arn:aws:iam::XXX:policy/cfn-deploy-boundary-policy"
vpc:
  subnets:
    private:
      ap-southeast-2a:
        id: "subnet-XXX"
      ap-southeast-2b:
        id: "subnet-XXX"
      ap-southeast-2c:
        id: "subnet-XXX"
    public:
      ap-southeast-2a:
        id: "subnet-XXX"
      ap-southeast-2b:
        id: "subnet-XXX"
      ap-southeast-2c:
        id: "subnet-XXX"
managedNodeGroups:
  - name: standard-workers
    instanceType: t3.medium
#    privateNetworking: true
    desiredCapacity: 2
    minSize: 2
    maxSize: 10
```

```
./eksctl create cluster --cfn-role-arn arn:aws:iam::123:role/asd -f test.yaml
[ℹ]  eksctl version 0.14.0-rc.0
[ℹ]  using region ap-southeast-2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1487ba0]
goroutine 1 [running]:
github.com/weaveworks/eksctl/pkg/apis/eksctl.io/v1alpha5.NoAccess(...)
        github.com/weaveworks/eksctl@/pkg/apis/eksctl.io/v1alpha5/validation.go:125
github.com/weaveworks/eksctl/pkg/apis/eksctl.io/v1alpha5.(*ClusterConfig).ValidateClusterEndpointConfig(0xc00067e210, 0xc0004ba360, 0x0)
        github.com/weaveworks/eksctl@/pkg/apis/eksctl.io/v1alpha5/validation.go:114 +0x40
github.com/weaveworks/eksctl/pkg/ctl/create.doCreateCluster(0xc0002dc080, 0xc0005943c0, 0xc0002dc100, 0x0, 0x0)
        github.com/weaveworks/eksctl@/pkg/ctl/create/cluster.go:112 +0x168
github.com/weaveworks/eksctl/pkg/ctl/create.createClusterCmd.func1(0xc0002c2500, 0xc00066a300, 0x0, 0x4, 0x0, 0x0)
        github.com/weaveworks/eksctl@/pkg/ctl/create/cluster.go:36 +0x9b
github.com/spf13/cobra.(*Command).execute(0xc0002c2500, 0xc00066a2c0, 0x4, 0x4, 0xc0002c2500, 0xc00066a2c0)
        github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002c2000, 0xc0002ed9f0, 0x1, 0x1)
        github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
        github.com/weaveworks/eksctl@/cmd/eksctl/main.go:79 +0x407
```

## eksctl version 
`0.14.0-rc.0`

(Submitted through slack by @sayboras )
