### ISSUE TITLE
Set kubernetes version on install

### ISSUE THREAD

**Issue by Staggerlee011** [weaveworks/eksctl#1938]
Hi, after updating to eksctl version 0.15.0, it is still installing kubernetes version 1.14.

## re-create: 
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: EKStestcluster1
  region: us-east-1

nodeGroups:
  - name: eksnodegroup
    instanceType: t3.medium
    desiredCapacity: 2
    ssh: # use existing EC2 key
      publicKeyName: eks-key

cloudWatch:
  clusterLogging:
    enableTypes: ["all"]
```

Running it results in: 

[ℹ]  eksctl version 0.15.0
[ℹ]  using region us-east-1
[ℹ]  setting availability zones to [us-east-1e us-east-1b]
[ℹ]  subnets for us-east-1e - public:192.168.0.0/19 private:192.168.64.0/19
[ℹ]  subnets for us-east-1b - public:192.168.32.0/19 private:192.168.96.0/19
[ℹ]  nodegroup "eksnodegroup" will use "ami-08ac00d99a673bad0" [AmazonLinux2/1.14]
[ℹ]  using EC2 key pair "eks-key"
[ℹ]  using Kubernetes version 1.14
[ℹ]  creating EKS cluster "EKStestcluster1" in "us-east-1" region with un-managed nodes
