### ISSUE TITLE
Creating the FargatePodExecutionRole resource only if a Fargate profile doesn't specify a podExecutionRoleARN

### ISSUE THREAD

**Issue by cpower** [weaveworks/eksctl#1945]
**What happened?**
Attempting to supply pre-created ServiceRoleARN and PodExecutionRoleARN when creating an EKS Fargate cluster, the eksctl tool does not recognize the FargateProfile PodExecutionRoleARN configuration element when supplied, and instead tries to create the PodExecutionRole.

Does not work:
```
    fargateProfiles:
      - name: fp-default
        podExecutionRoleARN: arn:aws:iam:<account>:role/MyEKSFargatePodExecutionRole
```

However, supplying the Cluster.IAM.FargatePodExecutionRoleARN at the same level as the Cluster.IAM.ServiceRoleARN does work, example attached.

Works:
```
     iam:
        serviceRoleARN: "arn:aws:iam::<account>:role/MyEKSServiceRole"
        fargatePodExecutionRoleARN: "arn:aws:iam:<account>:role/MyEKSFargatePodExecutionRole"
```

**What you expected to happen?**
I expected to be able to supply the PodExecutionRoleARN as part of the FargateProfile in the cluster.yaml file when calling cluster create.

**How to reproduce it?**
Use the attached cluster.yaml file and run cluster create, and then validate that that cluster was created with the supplied PodExecutionRoleARN and not a role that was created when cluster create was executed.

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
0.15.0
```

**Comment by cpower** [comment]
Example of configuration that doesn't used the specific PodExecutionRoleARN:

```
# An example of ClusterConfig object creating Fargate profiles.
---
    apiVersion: eksctl.io/v1alpha5
    kind: ClusterConfig
    
    metadata:
        name: eks-fargate-cluster
        region: us-east-1
    
    iam:
        serviceRoleARN: "arn:aws:iam::REDACTED:role/MyEKSServiceRole"

    fargateProfiles:
      - name: fp-default
        podExecutionRoleARN: arn:aws:iam::REDACTED:role/MyEKSFargatePodExecutionRole
        selectors:
          # All workloads in the "default" Kubernetes namespace will be
          # scheduled onto Fargate:
          - namespace: default
          # All workloads in the "kube-system" Kubernetes namespace will be
          # scheduled onto Fargate:
          - namespace: kube-system
```

**Comment by cpower** [comment]
Example on cluster yaml that does used the FargatePodExecutionRoleARN:

```
# An example of ClusterConfig object creating Fargate profiles.
---
    apiVersion: eksctl.io/v1alpha5
    kind: ClusterConfig
    
    metadata:
        name: eks-fargate-cluster
        region: us-east-1
    
    iam:
        serviceRoleARN: "arn:aws:iam::REDACTED:role/MyEKSServiceRole"
        fargatePodExecutionRoleARN: "arn:aws:iam::REDACTED:role/MyEKSFargatePodExecutionRole"

    fargateProfiles:
      - name: fp-default
        selectors:
          # All workloads in the "default" Kubernetes namespace will be
          # scheduled onto Fargate:
          - namespace: default
          # All workloads in the "kube-system" Kubernetes namespace will be
          # scheduled onto Fargate:
          - namespace: kube-system
```

**Comment by cPu1** [comment]
>Attempting to supply pre-created ServiceRoleARN and PodExecutionRoleARN when creating an EKS Fargate cluster, the eksctl tool does not recognize the FargateProfile PodExecutionRoleARN configuration element when supplied, and instead tries to create the PodExecutionRole.

I couldn't reproduce this issue with your config file. The Fargate profile gets created with the _correct_ `podExecutionRoleARN` specified in `fargateProfiles[*].podExecutionRoleARN`. 

Given this config file:
```yaml
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: fargate-test
  region: ap-northeast-1

iam:
  serviceRoleARN: "arn:aws:iam::<redacted>:role/ServiceRole"

fargateProfiles:
- name: fp-default
  podExecutionRoleARN: "arn:aws:iam::<redacted>:role/fargate-test"
  selectors:
    # All workloads in the "default" Kubernetes namespace will be
    # scheduled onto Fargate:
    - namespace: default
    # All workloads in the "kube-system" Kubernetes namespace will be
    # scheduled onto Fargate:
    - namespace: kube-system
```

The `CreateFargateProfile` API request gets invoked with the correct pod execution role ARN:

```
Fargate profile: create request: sending: {
  ClusterName: "<>",
  FargateProfileName: "fp-default",
  PodExecutionRoleArn: "arn:aws:iam::<>:role/fargate-test",
  Selectors: [{
      Namespace: "default"
    },{
      Namespace: "kube-system"
    }]
}
```

I should note that the `FargatePodExecutionRole` does get created as part of the cluster's CloudFormation stack, even if `fargateProfiles[*].podExecutionRoleArn` is set, but it's only used for a Fargate profile if `fargateProfiles[*].podExecutionRoleArn` is not set (as a default value). The `FargatePodExecutionRole` resource is not created if no Fargate profiles are defined. I think this behaviour might have caused the confusion.

We could improve this by creating the `FargatePodExecutionRole` only if a Fargate profile doesn't specify `podExecutionRoleARN.
