### ISSUE TITLE
eksctl version 0.15.0 fails to create managed nodegroup with clusterConfig file

### ISSUE THREAD

**Issue by sarbajitdutta** [weaveworks/eksctl#1958]
**What happened?**
While creating a cluster version 1.15 and a managed node group it failed to create one. The error in Cloudformation was internal failure. I have tried multiple times to create a managed node group with eksctl and it fails every single time with eksctl 0.15.0 creating a cluster 1.15.

Error in Cloudformation - `failed to stabilize: Internal Failure`

**What you expected to happen?**
The managed nodegroup should have been created. Creating a managed group through console works.

**How to reproduce it?**
This is the cluster config file I used is below. Also I should mention there is not way to spawn the managed nodegroup instances in private subnets only of my VPC. Is that intentional? I can do that while creating it through console.

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: appdev
  region: us-east-1
  version : "1.15"

vpc:
  subnets:
    private:
      us-east-1a: { id: subnet-xxxxxx }
      us-east-1b: { id: subnet-xxxxxx }
    public:
      us-east-1a: { id: subnet-xxxxxx }
      us-east-1b: { id: subnet-xxxxxx }

managedNodeGroups:
  - name: appdev-managed-ng-1
    instanceType: t3.small
    minSize: 1
    maxSize: 4
    desiredCapacity: 1
    volumeSize: 20
    ssh:
      allow: true
      #publicKeyPath: ~/.ssh/appdev_ec2_rsa.pub
      publicKeyName: 'xxxxxx'
      # new feature for restricting SSH access to certain AWS security group IDs
      sourceSecurityGroupIds: ["sg-xxxxxx"]
    labels: {role: worker}
    tags:
      nodegroup-role: worker

fargateProfiles:
  - name: fp-default
    selectors:
      # All workloads in the "default" Kubernetes namespace will be
      # scheduled onto Fargate:
      - namespace: default
      # All workloads in the "kube-system" Kubernetes namespace will be
      # scheduled onto Fargate:
      - namespace: kube-system
  - name: fp-generic
    selectors:
      # All workloads in the "generic" Kubernetes namespace matching the following
      # label selectors will be scheduled onto Fargate:
      - namespace: appdev
      - namespace: kubernetes-dashboard

cloudWatch:
  clusterLogging:
    enableTypes:
      - "audit"
      - "authenticator"
      - "api"
```
**Anything else we need to know?**
What OS are you using, are you using a downloaded binary or did you compile eksctl, what type of AWS credentials are you using (i.e. default/named profile, MFA) - please don't include actual credentials though!
OS - MacOS Sierra
Named profile
**Versions**
Please paste in the output of these commands:
```
$ eksctl version
0.15.0
$ kubectl version
Client Version: v1.15.10-eks-bac369
```

**Logs**
Include the output of the command line when running eksctl. If possible, eksctl should be run with debug logs. For example:
`eksctl get clusters -v 4`
Make sure you redact any sensitive information before posting.
If the output is long, please consider a Gist.
