### ISSUE TITLE
eksctl doesn't register iam roles as apart of the system:masters group when using aws-iam-authenticator

### ISSUE THREAD

**Issue by JohnHedman** [weaveworks/eksctl#1975]
**What happened?**
The problem seems to be that when using an IAM Role that is attached to an ec2 instance, that role is not returned as apart of the `system:masters` group from aws-iam-authenticator.  After the cluster is created, the IAM Role is forbidden to use some kubectl commands.  When using IAM User credentials both on my laptop and on the same instance that the role was being used, I don't run into this problem.

Here are example kubectl commands after creating a cluster with an iam role:
This command works fine:
```
kubectl get pods --all-namespaces 
NAMESPACE     NAME                      READY   STATUS    RESTARTS   AGE
kube-system   aws-node-c2qdm            1/1     Running   0          77m
kube-system   aws-node-k82kg            1/1     Running   0          77m
kube-system   coredns-84549585c-9mrhd   1/1     Running   0          81m
kube-system   coredns-84549585c-wtqrl   1/1     Running   0          81m
kube-system   kube-proxy-h7gjp          1/1     Running   0          77m
kube-system   kube-proxy-kdr2j          1/1     Running   0          77m
```

This command doesn't seem to work:
```
$ kubectl get namespaces
Error from server (Forbidden): namespaces is forbidden: User "system:node:ip-10-12-64-210.us-west-2.compute.internal" cannot list resource "namespaces" in API group "" at the cluster scope
```

**What you expected to happen?**
I expected the second command to work similar to the first command above.

**How to reproduce it?**
I tried to create an EKS cluster with a non-managed node group with a config file using the following command (showed logs from command below):
```
$ eksctl create cluster -f cluster.yaml
```
The config file uses already created public subnets, iam roles for eks cluster and the ec2 that belong to the cluster.  Here is the config file:
```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: jhedman-eksctl-config
  region: us-west-2

vpc:
  subnets:
    public:
      us-west-2a: { id: subnet-028494fe57ede80d3 }
      us-west-2b: { id: subnet-0276f0ec725968655 }
      us-west-2c: { id: subnet-0f49a26c0b3354f7b }
  securityGroup: "sg-0c03411158eb72748"
  sharedNodeSecurityGroup: "sg-0c03411158eb72748"

iam:
  serviceRoleARN: "arn:aws:iam::707566951618:role/jhedman-eks-cluster-role"

nodeGroups:
  - name: jhedman-eks-workers
    labels:
      role: workers
    instanceType: t2.micro
    desiredCapacity: 2
    volumeSize: 32
    securityGroups:
      attachIDs:
        - "sg-080f33e18f3d1152d"
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/authorized_keys
    iam:
      instanceProfileARN: "arn:aws:iam::707566951618:instance-profile/jhedman-ec2-role"
      instanceRoleARN: "arn:aws:iam::707566951618:role/jhedman-ec2-role"
```

The cluster is created just fine and the nodes are registered to the cluster as well.  The problem comes from running some kubectl command after the cluster has spun up:

This works fine:
```
kubectl get pods --all-namespaces 
NAMESPACE     NAME                      READY   STATUS    RESTARTS   AGE
kube-system   aws-node-c2qdm            1/1     Running   0          77m
kube-system   aws-node-k82kg            1/1     Running   0          77m
kube-system   coredns-84549585c-9mrhd   1/1     Running   0          81m
kube-system   coredns-84549585c-wtqrl   1/1     Running   0          81m
kube-system   kube-proxy-h7gjp          1/1     Running   0          77m
kube-system   kube-proxy-kdr2j          1/1     Running   0          77m
```

This doesn't seem to work:
```
$ kubectl get namespaces
Error from server (Forbidden): namespaces is forbidden: User "system:node:ip-10-12-64-210.us-west-2.compute.internal" cannot list resource "namespaces" in API group "" at the cluster scope
```

Here is the kube config file (tried to get rid of sensitive information):
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <CERT>
    server: <SERVER>
  name: <NAME>
contexts:
- context:
    cluster: jhedman-eksctl-config-2.us-west-2.eksctl.io
    user: i-00f102c6dbbb6e242@jhedman-eksctl-config-2.us-west-2.eksctl.io
  name: i-00f102c6dbbb6e242@jhedman-eksctl-config-2.us-west-2.eksctl.io
current-context: i-00f102c6dbbb6e242@jhedman-eksctl-config-2.us-west-2.eksctl.io
kind: Config
preferences: {}
users:
- name: i-00f102c6dbbb6e242@jhedman-eksctl-config-2.us-west-2.eksctl.io
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - jhedman-eksctl-config-2
      command: aws-iam-authenticator
      env:
      - name: AWS_STS_REGIONAL_ENDPOINTS
        value: regional
      - name: AWS_DEFAULT_REGION
        value: us-west-2
```

**Versions**
```
$ eksctl version
0.15.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.10-eks-bac369", GitCommit:"bac3690554985327ae4d13e42169e8b1c2f37226", GitTreeState:"clean", BuildDate:"2020-02-21T23:37:18Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.10-eks-bac369", GitCommit:"bac3690554985327ae4d13e42169e8b1c2f37226", GitTreeState:"clean", BuildDate:"2020-02-26T01:12:54Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**
```
eksctl create cluster -f cluster.yaml 
[ℹ]  eksctl version 0.15.0-rc.1
[ℹ]  using region us-west-2
[✔]  using existing VPC (vpc-014947cd6d4d01d30) and subnets (private:[] public:[subnet-028494fe57ede80d3 subnet-0276f0ec725968655 subnet-0f49a26c0b3354f7b])
[!]  custom VPC/subnets will be used; if resulting cluster doesn't function as expected, make sure to review the configuration of VPC/subnets
[ℹ]  nodegroup "jhedman-eks-workers" will use "ami-0cd99c894d101fe9b" [AmazonLinux2/1.14]
[ℹ]  using SSH public key "/home/ec2-user/.ssh/authorized_keys" as "eksctl-jhedman-eksctl-config-nodegroup-jhedman-eks-workers-b6:19:ab:36:04:95:2e:a2:7c:9e:8d:f3:e5:2a:91:51" 
[ℹ]  using Kubernetes version 1.14
[ℹ]  creating EKS cluster "jhedman-eksctl-config" in "us-west-2" region with un-managed nodes
[ℹ]  1 nodegroup (jhedman-eks-workers) was included (based on the include/exclude rules)
[ℹ]  will create a CloudFormation stack for cluster itself and 1 nodegroup stack(s)
[ℹ]  will create a CloudFormation stack for cluster itself and 0 managed nodegroup stack(s)
[ℹ]  if you encounter any issues, check CloudFormation console or try 'eksctl utils describe-stacks --region=us-west-2 --cluster=jhedman-eksctl-config'
[ℹ]  CloudWatch logging will not be enabled for cluster "jhedman-eksctl-config" in "us-west-2"
[ℹ]  you can enable it with 'eksctl utils update-cluster-logging --region=us-west-2 --cluster=jhedman-eksctl-config'
[ℹ]  Kubernetes API endpoint access will use default of {publicAccess=true, privateAccess=false} for cluster "jhedman-eksctl-config" in "us-west-2"
[ℹ]  2 sequential tasks: { create cluster control plane "jhedman-eksctl-config", create nodegroup "jhedman-eks-workers" }
[ℹ]  building cluster stack "eksctl-jhedman-eksctl-config-cluster"
[ℹ]  deploying stack "eksctl-jhedman-eksctl-config-cluster"
[ℹ]  building nodegroup stack "eksctl-jhedman-eksctl-config-nodegroup-jhedman-eks-workers"
[ℹ]  --nodes-min=2 was set automatically for nodegroup jhedman-eks-workers
[ℹ]  --nodes-max=2 was set automatically for nodegroup jhedman-eks-workers
[ℹ]  deploying stack "eksctl-jhedman-eksctl-config-nodegroup-jhedman-eks-workers"
[✔]  all EKS cluster resources for "jhedman-eksctl-config" have been created
[✔]  saved kubeconfig as "/home/ec2-user/.kube/config"
[ℹ]  adding identity "arn:aws:iam::707566951618:role/jhedman-ec2-role" to auth ConfigMap
[ℹ]  nodegroup "jhedman-eks-workers" has 0 node(s)
[ℹ]  waiting for at least 2 node(s) to become ready in "jhedman-eks-workers"
[ℹ]  nodegroup "jhedman-eks-workers" has 2 node(s)
[ℹ]  node "ip-172-31-25-102.us-west-2.compute.internal" is ready
[ℹ]  node "ip-172-31-43-36.us-west-2.compute.internal" is ready
[ℹ]  kubectl command should work with "/home/ec2-user/.kube/config", try 'kubectl get nodes'
[✔]  EKS cluster "jhedman-eksctl-config" in "us-west-2" region is ready
```

**Other Info**
I am fairly new to using eksctl, but it seems like I should be granted system:masters group permission.  I could be wrong, but it seems to be working correctly with IAM Users.  The reason I am using IAM Roles is because I work for a company that has federated roles and IAM Users are not allowed (sadly).  I tried to test this in my own account to see if I could figure out what was wrong and that is when I noticed the difference between using IAM User and IAM Role.
