### ISSUE TITLE
overrideBootstrapCommand doesn't work anymore, all new node failed

### ISSUE THREAD

**Issue by teochenglim** [weaveworks/eksctl#1977]
**What happened?**
A description of actual behavior (with error messages).

overrideBootstrapCommand use to be able to overrideBootstrap but with version 0.15.0 it is executing before the "write_files" and make it impossible to do a lot of things.

suggest to move the "runcmd" to the last block and "write_files" on top.

### now with 0.15.0 (Problem that no CA)

```yaml
#cloud-config
packages: null
runcmd:
- - /bin/bash
  - -c
  - |
. ### Now overrideBootstrapCommand is here
.
write_files:
.
.
.

```

### Please change to 

```yaml
#cloud-config
packages: null
write_files:
.
.
.
runcmd:
- - /bin/bash
  - -c
  - |
. ### Now overrideBootstrapCommand is here
.

```

**What you expected to happen?**

Our in house script all fail because of the latest "0.15.0" version

**How to reproduce it?**
Include the steps to reproduce the bug

in-house "overrideBootstrapCommand" breaks because of the new changes

**Anything else we need to know?**
What OS are you using, are you using a downloaded binary or did you compile eksctl, what type of AWS credentials are you using (i.e. default/named profile, MFA) - please don't include actual credentials though!

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
0.15.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T23:41:24Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

```

**Logs**
Include the output of the command line when running eksctl. If possible, eksctl should be run with debug logs. For example:
`eksctl get clusters -v 4`
Make sure you redact any sensitive information before posting.
If the output is long, please consider a Gist.

When the "overrideBootstrapCommand" failed, it has no log. kubectl get nodes fail.
manually inspecting launchtemplate and found the changes.
