### ISSUE TITLE
eksctl calls do not assume role specified in kubeconfig

### ISSUE THREAD

**Issue by neilharris123** [weaveworks/eksctl#1998]
**What happened?**

I've added a role named eks-admin for a clusters configuration in my kubeconfig using command:

`eksctl utils write-kubeconfig --name CLUSTER_NAME --authenticator-role-arn arn:aws:iam::ACC_NUM:role/eks-admin`

When I look at the kubeconfig file it has been successfully added:

```
- name: my.username@prod-k8s-argocd.eu-west-1.eksctl.io
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - prod-k8s-argocd
      - -r
      - arn:aws:iam::ACC_NUM:role/eks-admin
      command: aws-iam-authenticator
      env:
      - name: AWS_STS_REGIONAL_ENDPOINTS
        value: regional
      - name: AWS_DEFAULT_REGION
        value: eu-west-1
```

When I run eksctl commands, the Cloudtrail events suggest it is running the commands as my user, there is no assumerole taking place. 

**What you expected to happen?**

I expected the authentication chain to be the same as kubectl commands. 

For example, when I run a kubectl command, assumerole takes place automatically and I assume the eks-admin role specified in the kubeconfig. 

With eksctl, the role is not assumed, and my standard user carries out the request. 

**Anything else we need to know?**

The role (eks-admin) is added in the aws-auth configmap to the system:masters group. However, as eksctl request are not assuming this role, this level of authentication (as a member of system:masters groups) is not currently taking place for users who are allowed to assume the eks-admin role.

`eksctl get clusters -v 4` generates:

2020-03-31T13:59:47+02:00 [▶]  role ARN for the current session is "arn:aws:iam::ACC_NUM:user/my.username"

**Versions**

eksctl version 0.16.0
kubectl version v1.15.1
