### ISSUE TITLE
Not able to create a cluster with managed node group

### ISSUE THREAD

**Issue by chaochn-amazon** [weaveworks/eksctl#2008]
**What happened?**
Playing around on the eksworkshop.com 
Created a eks cluster with `eksctl create cluster -f eksworkshop.yaml`, but the managed node group stack failed with `Nodegroup nodegroup failed to stabilize: Internal Failure`

I think it is easy to reproduce.

```
$ aws --version
aws-cli/1.18.36 Python/3.6.10 Linux/4.14.171-105.231.amzn1.x86_64 botocore/1.15.36
$ eksctl version
0.16.0
$ cat eksworkshop.yaml
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksworkshop-eksctl
  region: us-west-2

managedNodeGroups:
- name: nodegroup
  desiredCapacity: 3
  iam:
    withAddonPolicies:
      albIngress: true

secretsEncryption:
  keyARN: arn:aws:kms:us-west-2:<my aws account>:key/<kms key id or name>
```

**What you expected to happen?**
I expected the managed node group with desired capacity 3 is successfully created.

**How to reproduce it?**
Playing around on the eksworkshop.com. Just follow the steps specified in the https://eksworkshop.com/030_eksctl/launcheks/

**Anything else we need to know?**
What OS are you using, are you using a downloaded binary or did you compile eksctl, what type of AWS credentials are you using (i.e. default/named profile, MFA) - please don't include actual credentials though!

I am using downloaded binary. Just following the steps in https://eksworkshop.com/030_eksctl/launcheks/ and any prerequisite specified in the documented doc.

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
0.16.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.10-eks-bac369", GitCommit:"bac3690554985327ae4d13e42169e8b1c2f37226", GitTreeState:"clean", BuildDate:"2020-02-21T23:37:18Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

**Logs**
```
[ℹ]  deploying stack "eksctl-eksworkshop-eksctl-nodegroup-nodegroup"
[✖]  unexpected status "ROLLBACK_IN_PROGRESS" while waiting for CloudFormation stack "eksctl-eksworkshop-eksctl-nodegroup-nodegroup"
[ℹ]  fetching stack events in attempt to troubleshoot the root cause of the failure
[✖]  AWS::EKS::Nodegroup/ManagedNodeGroup: CREATE_FAILED – "Nodegroup nodegroup failed to stabilize: Internal Failure"
[ℹ]  1 error(s) occurred and cluster hasn't been created properly, you may wish to check CloudFormation console
[ℹ]  to cleanup resources, run 'eksctl delete cluster --region=us-west-2 --name=eksworkshop-eksctl'
[✖]  waiting for CloudFormation stack "eksctl-eksworkshop-eksctl-nodegroup-nodegroup": ResourceNotReady: failed waiting for successful resource state
```

**Comment by cPu1** [comment]
I tried this with your config and the cluster and nodegroup creation were successful.

>"Nodegroup nodegroup failed to stabilize: Internal Failure"

The error suggests it might be a temporary failure. Can you retry and see if you still get that error? 
Since you're from Amazon, is it possible you're trying this from an AWS account that's whitelisted for internal/beta features and it's failing because of that?

**Comment by martina-if** [comment]
Since this was probably a temporary failure on AWS' side I am closing this issue but please feel free to reopen it if the issue wasn't resolved.

**Comment by silverberry13** [comment]
I'm having this same problem consistently today. The same YAML config was working several days ago without a hitch. See the redacted file below:

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: MY_SERVICE
  region: us-east-1
managedNodeGroups:
- name: MY_SERVICE-node-group
  instanceType: t3.medium
  desiredCapacity: 2
  minSize: 2
  maxSize: 3
  labels:
    app: MY_SERVICE
    actorSystemName: MY_SERVICE
  ssh:
    allow: true
availabilityZones:
- us-east-1a
- us-east-1f
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: MY_SERVICE
  name: MY_SERVICE
spec:
  replicas: 2
  selector:
    matchLabels:
      app: MY_SERVICE
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: MY_SERVICE
        actorSystemName: MY_SERVICE
    spec:
      containers:
      - name: toh-lagom
        image: MY_ACCT_NO.dkr.ecr.us-east-1.amazonaws.com/MY_SERVICE:1.0.0
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /alive
            port: management
        readinessProbe:
          httpGet:
            path: /ready
            port: management
        ports:
        - name: remoting
          containerPort: 2552
          protocol: TCP
        - containerPort: 8558
          protocol: TCP
        env:
        - name: AKKA_CLUSTER_BOOTSTRAP_SERVICE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: "metadata.labels['app']"
```
