### ISSUE TITLE
route table and network gateway belong to different networks error

### ISSUE THREAD

**Issue by martina-if** [weaveworks/eksctl#2047]
**What happened?**

In integration tests we often have the error mentioned above when creating a cluster for testing:
```
[7] 2020-04-16T03:09:52Z [✖]  AWS::EC2::Route/PublicSubnetRoute: CREATE_FAILED – "route table rtb-0f89b6ca56b593e4c and network gateway igw-02c5d04fe8fa09590 belong to different networks (Service: AmazonEC2; Status Code: 400; Error Code: InvalidParameterValue; Request ID: 3a39cfac-0d96-42cf-8e71-5133229f9bbb)"
```
https://circleci.com/gh/weaveworks/eksctl/7341

**How to reproduce it?**
It seems that it is a race condition internal to CFN so it's hard to reproduce.

**Possible solution**
First,  we should explore why this is happening more in IT than in normal manual tests, and has not been reported by other users.

The generic solution for this is to add a `dependsOn` field in the template from the PublicSubnetRoute to the InternetGatewayAttachment:

```
  PublicSubnetRoute:
    Type: 'AWS::EC2::Route'
    DependsOn: VPCGatewayAttachment
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref PublicRouteTable
```

This is not supported in our fork of the goformation library we are using so it would need to be done manually by writing a marshaller for this object.

Support for `depends on` in goformation: https://github.com/awslabs/goformation/pull/132
