### ISSUE TITLE
PrivateNetworking for worker nodegroup not working when publicAccessCIDRs enabled

### ISSUE THREAD

**Issue by janavenkat** [weaveworks/eksctl#2054]
**What happened?**
Tried to create the cluster with private networking for worker nodes with `publicAccessCIDRs ` 

**What you expected to happen?**
Cluster should be created 
[✔]  all cluster resources were deleted

**How to reproduce it?**
Enable `publicAccessCIDRs` to access only Kubernetes API only through those IP and attach attachPolicyARNs with  `AmazonEKSWorkerNodePolicy` and `AmazonEKS_CNI_Policy`

**Anything else we need to know?**
Actually, private networking is working without `publicAccessCIDRs` even added IAM Policy
```    
iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
```

Here is the config am using 
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-pizza-cluster
  region: eu-west-1
  version: "1.12"

vpc:
 # my ip
  publicAccessCIDRs: ["**.***.***.***/32"]

nodeGroups:
  - name: "ng"
    tags:
      # EC2 tags required for cluster-autoscaler auto-discovery
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/eks-pizza-cluster4: "owned"
    instanceType: m5.large
    minSize: 1
    maxSize: 10
    desiredCapacity: 1
    privateNetworking: true
    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
    kubeletExtraConfig:
      kubeReserved:
        cpu: "300m"
        memory: "300Mi"
        ephemeral-storage: "1Gi"
      kubeReservedCgroup: "/kube-reserved"
      systemReserved:
        cpu: "300m"
        memory: "300Mi"
        ephemeral-storage: "1Gi"
      evictionHard:
        memory.available:  "200Mi"
        nodefs.available: "10%"
      featureGates:
        DynamicKubeletConfig: true
        RotateKubeletServerCertificate: true
```

**Versions**
Please paste in the output of these commands:
```
$ eksctl version: 0.16.0
$ kubectl version: v1.12
```

**Logs**
[ℹ]  nodegroup "ng" has 0 node(s)
[ℹ]  waiting for at least 1 node(s) to become ready in "ng"
Error: timed out (after 25m0s) waiting for at least 1 nodes to join the cluster and become ready in "ng"
