### ISSUE TITLE
Allow more granular control over volume configuration on NodeGroup

### ISSUE THREAD

**Issue by tomhuang12** [weaveworks/eksctl#2115]
**Why do you want this feature?**
In my use case, I would like to attach a second encrypted EBS volume to the nodes due to security requirements. The second volume is coming from a snapshot of the AMI I am using for the nodes. 

**What feature/behavior/change do you want?**
An example cluster configuration yaml would look something like this:

```
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-1
  region: eu-west-1

nodeGroups:
  - name: ng1
    instanceType: m5.xlarge
    desiredCapacity: 1
    volumeMappings:
    - deviceName: "/dev/xvda"
      volumeSize: 100
      volumeType: gp2
      volumeEncrypted: true
      snapshotId: snap-0e1d1928ad4d81a
      volumeKmsKeyID: 36c0b54e-64ed-4f2d-a1c7-96558764311e
    - deviceName: "/dev/sdb"
      volumeSize: 100
      volumeType: gp2
      volumeEncrypted: true
      snapshotId: snap-012d1928ad4abc1
      volumeKmsKeyID: 36c0b54e-64ed-4f2d-a1c7-96558764311e
```
