### ISSUE TITLE
unable to determine AMI ubuntu1804 when deploying nodeGroup

### ISSUE THREAD

**Issue by Vitorspk** [weaveworks/eksctl#2124]
**What happened?**
A description of actual behavior (with error messages).

```
eksctl create nodegroup -f nodeGroup-virginia.yaml 
[ℹ]  eksctl version 0.19.0-rc.0
[ℹ]  using region us-east-1
Error: unable to determine AMI to use: unable to determine AMI for region us-east-1, version 1.16, instance type m5.large and image family Ubuntu1804
```

**What you expected to happen?**

1º I'm using my network vpc and subnets and pass everthing on yaml file, configured and working with cluster version 15 and eksctl 0.18.0. 

2º When i try to create cluster using eksctl version 0.19.0-rc.0 and eks version 16 i found a timeout from command line, when creating nodeGroup with nodegroup AMI AmazonLinux2.

```
eksctl create nodegroup -f nodeGroup-virginia.yaml 
[ℹ]  eksctl version 0.19.0-rc.0
[ℹ]  using region us-east-1
Error: unable to determine AMI to use: unable to determine AMI for region us-east-1, version 1.16, instance type m5.large and image family Ubuntu1804
```

**How to reproduce it?**
Include the steps to reproduce the bug

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: intelipost-eks-qa
  region: us-east-1
  version : "1.15"
vpc:
  id: "vpc-xxx"
  cidr: "10.0.0.0/16"
  subnets:
    private:
      us-east-1a: 
        id: subnet-xxx1
        cidr: "10.0.40.0/21"
      us-east-1b: 
        id: subnet-xxx2
        cidr: "10.0.48.0/21"
    public:
      us-east-1a:
        id: subnet-xxx1
        cidr: "10.0.16.0/21"
      us-east-1b:
        id: subnet-xxx2
        cidr: "10.0.24.0/21"
```
run thins command:
`eksctl create cluster -f cluster-virginia.yaml`

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: aws-eks-qa
  region: us-east-1
  version : "1.16"
nodeGroups:
  - name: ng-agent-01
    instanceType: m5.large
    amiFamily: Ubuntu1804
    minSize: 2
    maxSize: 20
    desiredCapacity: 2
    volumeSize: 20
    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
        certManager: true
        albIngress: true
    kubeletExtraConfig:
        kubeReserved:
            cpu: "300m"
            memory: "300Mi"
            ephemeral-storage: "1Gi"
        kubeReservedCgroup: "/kube-reserved"
        systemReserved:
            cpu: "300m"
            memory: "300Mi"
            ephemeral-storage: "1Gi"
        evictionHard:
            memory.available:  "200Mi"
            nodefs.available: "10%"
        featureGates:
            DynamicKubeletConfig: true
            RotateKubeletServerCertificate: true
    privateNetworking: true
    securityGroups:
      withShared: true
      withLocal: true
    tags:
      nodegroup-role: worker
    labels:
      node-role.kubernetes.io/worker: worker
```

`eksctl create nodegroup -f nodeGroup-virginia.yaml `

**Anything else we need to know?**
What OS are you using, are you using a downloaded binary or did you compile eksctl, what type of AWS credentials are you using (i.e. default/named profile, MFA) - please don't include actual credentials though!

Download eksctl from this repo on github and set him to be used on linux machine.
Version:  eksctl version 0.19.0-rc.0

**Versions**
Please paste in the output of these commands:
```
$  eksctl version
$ kubectl version
```
`0.19.0-rc.0`

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**
Include the output of the command line when running eksctl. If possible, eksctl should be run with debug logs. For example:
`eksctl get clusters -v 4`
Make sure you redact any sensitive information before posting.
If the output is long, please consider a Gist.
