### ISSUE TITLE
0 Node NodeGroup

### ISSUE THREAD

**Issue by bitva77** [weaveworks/eksctl#2146]
**What happened?**
Trying to create a GPU nodegroup with 0 nodes to start with and am getting the following message:

`AWS::EKS::Nodegroup/ManagedNodeGroup: CREATE_FAILED – "Property validation failure: [Value for property {/ScalingConfig/MinSize} is less than minimum allowed value {1.000000}, Value for property {/ScalingConfig/DesiredSize} is less than minimum allowed value {1.000000}]"`

**What you expected to happen?**

I expect the nodegroup to be created.  I can create a nodegroup with a min/desired size of 1 and then I can go into the GUI and scale that nodegroup down to 0.

If I can scale it down to 0 in the GUI I should be able to create it with 0 to begin with.

**How to reproduce it?**

`eks-nodegroup.yaml`:

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-1
  region: us-west-2

availabilityZones: ["us-west-2a", "us-west-2b", "us-west-2c"]

managedNodeGroups:
  - name: eks-1-gpu-ng
    desiredCapacity: 0
    minSize: 0
    maxSize: 10
    instanceType: g3s.xlarge
    iam:
      withAddonPolicies:
        autoScaler: true
```

**Versions**
Please paste in the output of these commands:
```
eksctl version
0.17.0
kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```
