### ISSUE TITLE
create cluster: unable to use "latest" as version

### ISSUE THREAD

**Issue by ldemailly** [weaveworks/eksctl#2154]
Looking at
https://github.com/weaveworks/eksctl/blob/master/pkg/ctl/create/utils.go#L28-L30
I thought I should be able to pass --version="latest" or
```yaml
metadata:
  name: ${USER}-eksctl
  region: ${AWS_REGION}
  version: latest
```
but when I do I get
```
Error: invalid version, supported values: 1.13, 1.14, 1.15, 1.16
```

Any idea what I'm missing?
