### ISSUE TITLE
Migrating from Unmanaged Node groups to Managed Node groups

### ISSUE THREAD

**Issue by tahirali-endurance** [weaveworks/eksctl#2176]
**What happened?**
[✖]  AWS::EKS::Nodegroup/ManagedNodeGroup: CREATE_FAILED –·"One or more subnets are duplicate (Service: AmazonEKS; Status Code: 400; Error Code: InvalidParameterException; Request ID: 4c7820b8-2b52-43e0-892f-eb98fcadfde9)"

**What you expected to happen?**
Unmanaged Node groups are migrated Managed Node groups.

**How to reproduce it?**
This is the yaml file(cluster692999122.yml) being used.

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster-qa-rel
  region: us-east-1

vpc:
  subnets:
    private:
      az1 : {id: subnet-0224b8513894ad11e}
      az2 : {id: subnet-08558b5b3fac8ff37}

    public:
      az3 : {id: subnet-03e635ce827ba3a41}
      az4 : {id: subnet-0ee9845d17971770e}

managedNodeGroups:
  - name: ng-v3
    instanceType: t3.medium
    desiredCapacity: 4
    privateNetworking: true

iam:
  withOIDC: true

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
```

**Step 1:**
```bash
eksctl update cluster -f /tmp/cluster692999122.yml --approve
```
**Step 2:**
At this step, we create new nodegroup ng-v3(for managed node group). 
```bash
eksctl create nodegroup --config-file=/tmp/cluster692999122.yml
```

In this step, we got this error.

[ℹ]  eksctl version 0.19.0
[ℹ]  using region us-east-1
[ℹ]  will use version 1.16 for new nodegroup(s) based on control plane version
[ℹ]  1 nodegroup(s) that already exist (ng-v2) will be excluded
[ℹ]  1 nodegroup (ng-v3) was included (based on the include/exclude rules)
[ℹ]  combined exclude rules: ng-v2
[ℹ]  no nodegroups present in the current set were excluded by the filter
[ℹ]  will create a CloudFormation stack for each of 1 managed nodegroups in cluster "eks-cluster-qa-rel"
[ℹ]  2 sequential tasks: { fix cluster compatibility, 1 task: { 1 task: { create managed nodegroup "ng-v3" } } }
[ℹ]  checking cluster stack for missing resources
[ℹ]  cluster stack has all required resources
[ℹ]  building managed nodegroup stack "eksctl-eks-cluster-qa-rel-nodegroup-ng-v3"
[ℹ]  deploying stack "eksctl-eks-cluster-qa-rel-nodegroup-ng-v3"
[✖]  unexpected status "ROLLBACK_COMPLETE" while waiting for CloudFormation stack "eksctl-eks-cluster-qa-rel-nodegroup-ng-v3"
[ℹ]  fetching stack events in attempt to troubleshoot the root cause of the failure
[!]  AWS::IAM::Role/NodeInstanceRole: DELETE_IN_PROGRESS
[✖]  AWS::EKS::Nodegroup/ManagedNodeGroup: CREATE_FAILED –·"One or more subnets are duplicate (Service: AmazonEKS; Status Code: 400; Error Code: InvalidParameterException; Request ID: 4c7820b8-2b52-43e0-892f-eb98fcadfde9)"
[ℹ]  1 error(s) occurred and nodegroups haven't been created properly, you may wish to check CloudFormation console
[ℹ]  to cleanup resources, run 'eksctl delete nodegroup --region=us-east-1 --cluster=eks-cluster-qa-rel --name=<name>' for each of the failed nodegroup
[✖]  waiting for CloudFormation stack "eksctl-eks-cluster-qa-rel-nodegroup-ng-v3": ResourceNotReady: failed waiting for successful resource state
Error: failed to create nodegroups for cluster "eks-cluster-qa-rel"

**Step 3:**
This step is not executed because we got an error in previous step. This will eventually delete the previous node group (ng-v2) which is unmanaged node group.
```bash
eksctl delete nodegroup --config-file=/tmp/cluster692999122.yml
```

**Anything else we need to know?**
We are testing on AWS Code pipeline. The eksctl version is for Linux

**Versions**
eksctl version : 0.19.0

**Logs**
We checked the CF template and see following error:

**One or more subnets are duplicate (Service: AmazonEKS; Status Code: 400; Error Code: InvalidParameterException; Request ID: 4c7820b8-2b52-43e0-892f-eb98fcadfde9)**

**Comment by tahirali-endurance** [comment]
We found that in our cluster cloud formation template output, the subnets ids were duplicated. Now this error makes sense.  We had been using our EKS cluster for couple of months and it is possible that subnets have been duplicated by some version of eksctl. 

Is it possible in eksctl to validate subnet ids in cloud formation for duplicates values?

**Comment by martina-if** [comment]
Hi @tahirali-endurance I am not sure what you mean by validating for duplicates. Can you explain what you would expect eksctl to do and in which command?

**Comment by tahirali-endurance** [comment]
In our case, for some reason, the provided subnets have duplicate subnet ids. Is it possible to validate subnet duplication in ```eksctl create nodegroup```  command? In our issue, after investigation of cloud formation, we found the provided subnets had duplicate ids.

**Comment by martina-if** [comment]
@tahirali-endurance can you please post the relevants part of your CF template, including those duplications so I can better understand what is happening? Feel free to redact the things you consider confidential.

**Comment by tahirali-endurance** [comment]
This is the part specific to Private/Public Subnet.
 
```yaml
Outputs:
  SubnetsPrivate:
    Export:
        Name: {'Fn::Sub': '${AWS::StackName}::SubnetsPrivate'}
    Value:
        'Fn::Join': [',', [subnet-1, subnet-2,subnet-1, subnet-2]]
  SubnetsPublic:
    Export:
        Name: {'Fn::Sub': '${AWS::StackName}::SubnetsPublic'}
    Value:
        'Fn::Join': [',', [subnet-3, subnet-4,subnet-3, subnet-4]]
```

**Comment by martina-if** [comment]
Hi @tahirali-endurance I wasn't able to reproduce this issue. I see you mentioned that you are running this in a pipeline. Is it possible that you are running several eksctl commands in parallel for the same cluster? Even then... I'm not sure how to explain the duplicates.

Have you managed to reproduce this issue or was it a one off?

**Comment by tahirali-endurance** [comment]
This issue arose when we were migrating our old cluster(created with previous version of eksctl) to managed worker nodes. The main reason was to use latest features in managed nodes(like no public IP to worker node). We recreated the cluster from the scratch and that fixed the problem. 

But now I understand your point if we run eksct in parallel for critical operations like node group updates, it might reproduce duplicates. Ideally only one user should perform these activities but in our case I am still not clear how they ran in parallel. Currently, it is tricky to run eksctl in parallel for us. 

I think we can close this issue but a potential improvement can be disallow parallel cluster upgrades(like node group updates or any other critical updates) for same cluster.

**Comment by martina-if** [comment]
Hi @tahirali-endurance I see, thanks for explaining. I am not sure how we could disallow parallel upgrades if it's not done on the AWS server side but yeah, perhaps it's something we should add to the documentation at least. Thanks again.

**Comment by tzilistgoop** [comment]
@martina-if We are also getting this issue when trying to upgrade from unmanaged to managed node-groups. Seeing the same output in our cloudformation. Would be cool if this could be investigated a little bit more!

**Comment by martina-if** [comment]
@tzilistgoop Thanks for reporting this. To help me reproduce this issue, did you follow exactly the same steps as the ones described above? Did you also run the `eksctl update cluster` command? Did you run several eksctl commands in parallel against the same cluster?

**Comment by martina-if** [comment]
@tahirali-endurance Can you post the initial config file that you used to create the cluster (before you created the nodegroup)?

**Comment by tahirali-endurance** [comment]
@@martina-if Can you check your EKS cluster cloud formation **Output** section. If you look for Private and Subnets, and verify that subnets are duplicated or not. In our case, the subnet IDs were duplicated.

**Comment by martina-if** [comment]
@tahirali-endurance @tzilistgoop can you post step by step instructions on how to reproduce this issue? (including config files with redacted values)

**Comment by martina-if** [comment]
I tried again in us-east-1 but I couldn't reproduce this issue.

**Comment by martina-if** [comment]
@tahirali-endurance @tzilistgoop I've tried several times to reproduce this and another colleague tried as well but we weren't able to. 

I have to close this for now because we can't find the problem. If this is an issue with the update command or the create nodegroup command it would be important for us to fix it so please if you find steps to reproduce it reopen this issue and let us know.

**Comment by karrth** [comment]
I am running into this same issue in the same scenario.  I am adding a manged node group to a cluster that currently has 1 unmanaged group, in an effort to later remove the unmanaged group.
```
2021-07-28 12:52:56 [!]  AWS::EC2::LaunchTemplate/LaunchTemplate: DELETE_IN_PROGRESS
2021-07-28 12:52:56 [!]  AWS::IAM::Role/NodeInstanceRole: DELETE_IN_PROGRESS
2021-07-28 12:52:56 [✖]  AWS::EKS::Nodegroup/ManagedNodeGroup: CREATE_FAILED – "One or more subnets are duplicate (Service: AmazonEKS; Status Code: 400; Error Code: InvalidParameterException; Request ID: 1214d2fb-0553-49da-a749-a80b83499698; Proxy: null)"
```
* eksctl version 0.58.0
* region ap-southeast-2

The yaml for the new node group:
```
managedNodeGroups:
  - name: standard-workers-1
    instanceType: m5.2xlarge
    desiredCapacity: 1
    minSize: 1
    maxSize: 16
    privateNetworking: true
```

The old, already created group:
```
nodeGroups:
  - name: standard-workers-6
    instanceType: m5.2xlarge
    tags: {
      k8s.io/cluster-autoscaler/stage-apps-cluster-nz: "owned",
      k8s.io/cluster-autoscaler/enabled: "true"
    }
    ami: "auto"
    desiredCapacity: 1
    minSize: 1
    maxSize: 16
    privateNetworking: true
```

Let me know what further information I can pull for you to help resolve
