### ISSUE TITLE
eksctl managednodegroup with role arn with addon fails

### ISSUE THREAD

**Issue by lucidprogrammer** [weaveworks/eksctl#2205]
**What happened?**
A description of actual behavior (with error messages).

Following example as in https://eksctl.io/examples/reusing-iam-and-vpc/

```yaml
managedNodeGroups:
  - name: managed-1
   ...
    iam:
      instanceRoleARN: "arn:aws:iam::1111:role/eks-nodes-base-role"
      withAddonPolicies:
        externalDNS: true
        certManager: true
```
Get the following error
```
Error: managedNodeGroups[0].iam.instanceRoleArn and managedNodeGroups[0].iam.withAddonPolicies.autoScaler cannot be set at the same time
```

**What you expected to happen?**

**How to reproduce it?**
Include the steps to reproduce the bug

**Anything else we need to know?**
What OS are you using, are you using a downloaded binary or did you compile eksctl, what type of AWS credentials are you using (i.e. default/named profile, MFA) - please don't include actual credentials though!

**Versions**
Please paste in the output of these commands:
```
$ eksctl version 0.19.0
$ kubectl version 1.16
```

**Logs**
Include the output of the command line when running eksctl. If possible, eksctl should be run with debug logs. For example:
`eksctl get clusters -v 4`
Make sure you redact any sensitive information before posting.
If the output is long, please consider a Gist.

```
Error: managedNodeGroups[0].iam.instanceRoleArn and managedNodeGroups[0].iam.withAddonPolicies.autoScaler cannot be set at the same time
```

**Comment by cPu1** [comment]
This is the expected behaviour. As the error message states, you cannot specify any addon policy (`iam.withAddonPolicies`) when `iam.instanceRoleARN` is set. 

This is because eksctl creates an IAM role to attach to the worker node, with the actions required for  each enabled addon specified in an inline policy that's attached to that IAM role. If you supply your own IAM role for the node, eksctl expects that you attach any required policies.

In order to fix this, you'll have to attach the policies required for any addons you want enabled to your IAM role. Alternatively, you omit `iam.instanceRoleARN`, eksctl will manage creation of the IAM role with all required policies.

**Comment by cPu1** [comment]
I'm closing the issue, but please feel free to reopen it if you have any more questions.

**Comment by lucidprogrammer** [comment]
@cPu1 tks, yes thats understood, ideally change the example which is misleading in the main link
 https://eksctl.io/examples/reusing-iam-and-vpc/

**Comment by cPu1** [comment]
@lucidprogrammer that example is indeed misleading. I wasn't aware of it. Thanks! We'll fix that.

**Comment by jicowan** [comment]
+1 I tried to create a cluster with a managed node group and the following IAM policy

```
iam: 
  withOIDC: true

addons:
- name: vpc-cni
  version: 1.7.5 # optional
  attachPolicyARNs: #optional
  - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
  serviceAccountRoleARN: arn:aws:iam::aws:policy/AmazonEKSCNIAccess # optional
  attachPolicy: # optional
    Statement:
    - Effect: Allow
      Action:
      - ec2:AssignPrivateIpAddresses
      - ec2:AttachNetworkInterface
      - ec2:CreateNetworkInterface
      - ec2:DeleteNetworkInterface
      - ec2:DescribeInstances
      - ec2:DescribeTags
      - ec2:DescribeNetworkInterfaces
      - ec2:DescribeInstanceTypes
      - ec2:DetachNetworkInterface
      - ec2:ModifyNetworkInterfaceAttribute
      - ec2:UnassignPrivateIpAddresses
      Resource: '*'
```

It failed to create the OIDC endpoint, the IAM role, or the node group.  When I removed the addon section, it worked.
