### ISSUE TITLE
"Update cluster VPC endpoint access configuration" and "create managed nodegroup" tasks fail when run in parallel.

### ISSUE THREAD

**Issue by me-viper** [weaveworks/eksctl#2244]
**What happened?**
When I run
```
eksctl create cluster -f cluster.yaml 
```
managed node group creation fails with error.
```
[✖]  AWS::EKS::Nodegroup/ManagedNodeGroup: CREATE_FAILED – "Cluster 'my-cluster' is not in ACTIVE status (Service: AmazonEKS; Status Code: 400; Error Code: InvalidRequestException; Request ID: f6cb277a-b74e-40c4-a931-5908c4f38ace)"
```

When I run 
```
eksctl create cluster -f  cluster.yaml --without-nodegroup 
```
and after "Endpoint access update" completes run 
```
eksctl create nodegroup -f cluster.yaml 
```
everything works fine.

**What you expected to happen?**
Cluster gets created with managed node group without errors.

**How to reproduce it?**
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-cluster
  region: my-region
  version: "1.16"

vpc:
  publicAccessCIDRs: ["1.1.1.1/32", "2.2.2.0/24"]
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
  subnets:
    private:
      eu-west-1a: 
        id: subnet-xxxx
      eu-west-1b: 
        id: subnet-zzzz

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: cluster-autoscaler
      namespace: kube-system
      labels: {aws-usage: "cluster-ops"}
    attachPolicy:
      Version: "2012-10-17"
      Statement:
      - Effect: Allow
        Action:
        - "autoscaling:DescribeAutoScalingGroups"
        - "autoscaling:DescribeAutoScalingInstances"
        - "autoscaling:DescribeLaunchConfigurations"
        - "autoscaling:DescribeTags"
        - "autoscaling:SetDesiredCapacity"
        - "autoscaling:TerminateInstanceInAutoScalingGroup"
        Resource: '*'

managedNodeGroups:
  - name: workers
    instanceType: m5.large
    desiredCapacity: 3
    privateNetworking: true
    volumeSize: 20
```

**Versions**
```
kubectl version: v1.17.0
eksctl version: 0.20.0
```

**Logs**
```
> eksctl.exe create cluster -f .\cluster\cluster.yaml
[ℹ]  eksctl version 0.20.0
[ℹ]  using region my-region
[✔]  using existing VPC (vpc-xxxx) and subnets (private:[subnet-xxxx subnet-zzzz] public:[])
[!]  custom VPC/subnets will be used; if resulting cluster doesn't function as expected, make sure to review the configuration of VPC/subnets
[ℹ]  using EC2 key pair "EUWestStagingEC2Public"
[ℹ]  using Kubernetes version 1.16
[ℹ]  creating EKS cluster "my-cluster" in "my-region" region with managed nodes
[ℹ]  1 nodegroup (workers) was included (based on the include/exclude rules)
[ℹ]  will create a CloudFormation stack for cluster itself and 0 nodegroup stack(s)
[ℹ]  will create a CloudFormation stack for cluster itself and 1 managed nodegroup stack(s)
[ℹ]  if you encounter any issues, check CloudFormation console or try 'eksctl utils describe-stacks --region=my-region --cluster=my-cluster'
[ℹ]  CloudWatch logging will not be enabled for cluster "my-cluster" in "my-region"
[ℹ]  you can enable it with 'eksctl utils update-cluster-logging --region=my-region --cluster=my-cluster'
[ℹ]  Kubernetes API endpoint access will use provided values {publicAccess=true, privateAccess=true} for cluster "my-cluster" in "my-region"
[ℹ]  2 sequential tasks: { create cluster control plane "my-cluster", 2 parallel sub-tasks: { 2 sequential sub-tasks: { update cluster VPC endpoint access configuration, update public access CIDRs }, create managed nodegroup "workers" } }
[ℹ]  building cluster stack "eksctl-my-cluster-cluster"
[ℹ]  deploying stack "eksctl-my-cluster-cluster"
[ℹ]  building managed nodegroup stack "eksctl-my-cluster-nodegroup-workers"
[ℹ]  deploying stack "eksctl-my-cluster-nodegroup-workers"

*** Somewhere here cluster enters "Updating" state with "Endpoint-access-update".

[✖]  unexpected status "ROLLBACK_COMPLETE" while waiting for CloudFormation stack "eksctl-my-cluster-nodegroup-workers"
[ℹ]  fetching stack events in attempt to troubleshoot the root cause of the failure
[!]  AWS::IAM::Role/NodeInstanceRole: DELETE_IN_PROGRESS
[✖]  AWS::EKS::Nodegroup/ManagedNodeGroup: CREATE_FAILED – "Cluster 'my-cluster' is not in ACTIVE status (Service: AmazonEKS; Status Code: 400; Error Code: InvalidRequestException; Request ID: f6cb277a-b74e-40c4-a931-5908c4f38ace)"
[!]  1 error(s) occurred and cluster hasn't been created properly, you may wish to check CloudFormation console
[ℹ]  to cleanup resources, run 'eksctl delete cluster --region=my-region --name=my-cluster'
[✖]  waiting for CloudFormation stack "eksctl-my-cluster-nodegroup-workers": ResourceNotReady: failed waiting for successful resource state
Error: failed to create cluster "my-cluster"
```
