### ISSUE TITLE
Multiple Subnets in AZ and ENI per node

### ISSUE THREAD

**Issue by ArturChe** [weaveworks/eksctl#2293]
**What help do you need?**
Hi all.
I have read that the maximum number of pods deployed on a node can be calculated by formula "# of ENI * (# of IPv4 per ENI - 1)  + 2". And that by default node has only primary ENI.
Is there any way to increase the private IP addresses on the node to deploy more pods with eksctl?
For example, now I have configured the cluster to use existing subnets like:
```
vpc:
  subnets:
    private:
      us-east-1a: { id: subnet-111111 }
      us-east-1b: { id: subnet-222222 }

nodeGroups:
  - name: windows-ng
    instanceType: t3.large
    minSize: 2
    maxSize: 8
    volumeSize: 100
    volumeType: gp2
    amiFamily: WindowsServer2019FullContainer
    privateNetworking: true
```
And now I have two instances running in us-east-1a and us-east-1b with one ENI and 11 private IPv4 addresses.
How can I specify more than one subnets for each AZ with eksctl, so the instance will have 3 ENI and it will be possible to deploy 35 pods on one t3.large machine?
