### ISSUE TITLE
Need help with "Spot Fleet requests" nodegroup

### ISSUE THREAD

**Issue by Rajesh804** [weaveworks/eksctl#2309]
I have been trying to setup "Spot Fleet requests" nodegroup but I cant as it always creates "Spot Instance requests"

What options I need to use for creating spot fleet nodegroups ? Below is my current nodegroup template

```
nodeGroups:
    - name: ng-spot-fleet01
      minSize: 3
      maxSize: 6
      instanceType: mixed
      desiredCapacity: 3
      privateNetworking: true
      securityGroups:
        withShared: true
        withLocal: true
        attachIDs: ['sg-XXXXX', 'sg-XXXX', 'sg-XXXX']
      ssh:
        allow: true
        publicKeyName: 'XXXX'
      instancesDistribution:
        maxPrice: 0.100
        instanceTypes: ["m4.large", "m4.xlarge"]
        onDemandBaseCapacity: 0
        onDemandPercentageAboveBaseCapacity: 0
        spotAllocationStrategy: capacity-optimized
      labels:
        lifecycle: Ec2Spot
        aws.amazon.com/spot: "true"
      tags:
        k8s.io/cluster-autoscaler/enabled: "true"
        k8s.io/cluster-autoscaler/dev-cluster: "owned"
        k8s.io/cluster-autoscaler/node-template/label/lifecycle: Ec2Spot
        k8s.io/cluster-autoscaler/node-template/label/intent: apps
      iam:
        instanceProfileARN: "arn:aws:iam::XXXX:instance-profile/eksctl-dev-nodegroups-NodeInstanceProfile-XXXXXXX"
        instanceRoleARN: "arn:aws:iam::XXXX:role/eksctl-dev-NodeInstanceRole-XXXXX"
```
