### ISSUE TITLE
Error: VPC doesn't have enough subnets for nodegroup AZs

### ISSUE THREAD

**Issue by suppix** [weaveworks/eksctl#2322]
I'm trying to create another one nodegroup inside the same private subnet, but I get: 

```
Error: VPC doesn't have enough subnets for nodegroup AZs (subnets=map[string]v1alpha5.Network(nil) AZs=[]string{"eu-north-1a"})
```

Can you please explain to me what I'm doing wrong?

```
eksctl version
0.21.0
```

Here is my config:

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: EKS-course-cluster
  region: eu-north-1

vpc:
  subnets:
    private:
      eu-north-1a: { id: subnet-085631a95d068ec22 }
      eu-north-1b: { id: subnet-01d1b1e337f94c027 }
      eu-north-1c: { id: subnet-089b645e460dd42bb }

  clusterEndpoints:
    publicAccess:  false
    privateAccess: true

nodeGroups:
  - name: ng-1
    instanceType: t3.small
    privateNetworking: true
    desiredCapacity: 3
    ssh:
      publicKeyName: mykey

  - name: scale-north-1a
    instanceType: t3.small
    desiredCapacity: 1
    maxSize: 10
    availabilityZones: ["eu-north-1a"]
    iam:
      withAddonPolicies:
        autoScaler: true
    labels:
      nodegroup-type: stateful-north-1a
      instance-type: onDemand
    ssh:
      publicKeyName: mykey
```
