### ISSUE TITLE
Add a rule to a SecurityGroup

### ISSUE THREAD

**Issue by setevoy2** [weaveworks/eksctl#2345]
I.d like to embed a rule to a WorkerNodes SecurityGroup during provisioning.

I.e.: 

- I have a LoadBalancer created from a Kubernetes cluster
- for this ALB I have a dedicated SecurityGroup (crated as a part of my CloudFormation stack, from my own template)
- after this dedicated SecurityGroup is attached to an ALB - I need to allow WorkerNodes to allow traffic from this ALB by adding its SecurityGroup to the SecurityGroup of the WorkerNodes

Is it possible?

I was able to google only the `securityGroups` parameter [here](https://eksctl.io/examples/reusing-iam-and-vpc/), but at first - I can find absolutely no information in Google or documentation - what exactly this parameter will do and for what it's intended to be at all, the second is that I can't see any changes after I've added it.

Currently, my config for WorkerNodes looks like this (with some Ansible variables):

```
  - name: "{{ k8s_web_nodegroup_name }}-{{ item }}"
    instanceType: "{{ k8s_web_nodegroup_instance_type }}"
    privateNetworking: true
    labels: { role: web-workers }
    volumeSize: {{ k8s_web_nodegroup_volume_size }}
    volumeType: gp2
    desiredCapacity: {{ k8s_web_nodegroup_desired }}
    minSize: {{ k8s_web_nodegroup_min }}
    maxSize: {{ k8s_web_nodegroup_max }}
    availabilityZones: ["{{ item }}"]
    ssh:
      publicKeyName: "bttrm-eks-nodegroup-{{ region }}"
#    tags:
#      k8s.io/cluster-autoscaler/enabled: "true"
#      k8s.io/cluster-autoscaler/{{ eks_cluster_name }}: "owned"
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true
        albIngress: true
        efs: true
    securityGroups:
      withShared: true
      withLocal: true
      attachIDs: [ {{ office_devops_sg }} ]
```

The `office_devops_sg` has a value like `sg-123444555`.
