### ISSUE TITLE
Create service account using existing role.

### ISSUE THREAD

**Issue by ota42y** [weaveworks/eksctl#2351]
**Why do you want this feature?**
eksctl support IAM roles for service accounts.(IRSA). 
This feature create new IAM role and attach policy.  
So we should manage IAM role by eksctl.  
https://eksctl.io/usage/iamserviceaccounts/

But some user (including me) uses other manage tools like terraform, AWS CDK, ....
And these tools can use other resource's ARN as a variable, so very easy and hard to make a mistake.
So I want to manage IAM role by other tools.
(But I want to manage service account by eksctl :) )

**What feature/behavior/change do you want?**
I would like to propose a feature to create a service account by using an existing IAM Role.
We can manage role and policy by terraform or other tools (AWS CDK) using this feature.

And we can update role's policy  (eksctl doesn't support update IAM policy)

**Comment by barrydobson** [comment]
I've recently found the need to have a similar functionality in eksctl, but propose slightly different approach.
I use terraform to generate all the policies I need in IAM, then use eksctl IAM configuration to define the service account and attach the policy arn that was generated by the terraform.
There are however some cases where I want multiple service accounts to share a role, for instance, when I'm configuring cross account/cluster permissions in aws-auth config map, I need to the role arn for each service account (which is randomly suffixed).
I'd like to be able to specify either the role (as suggested by @ota42y) or at least to attach the generated role to multiple service accounts.

Option 1, specify an existing role:
```yaml
iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: service-name
      namespace: kube-system
    attachRoleARNs:
    - arn:aws:iam::xxxxxxxxxxxxx:role/my-existing-role
```

Option 2, specify multiple accounts:
```yaml
iam:
  withOIDC: true
  serviceAccounts:
  - acccountMetadata:
    - metadata:
         name: service-name-1
         namespace: kube-system
    - metadata:
         name: service-name-2
         namespace: kube-system
    attachPolicyARNs:
    - arn:aws:iam::xxxxxxxxxxxxxx:policy/my-policy
```
