### ISSUE TITLE
CREATE_FAILED -  "Invalid id: \"\tsg-

### ISSUE THREAD

**Issue by ricoms** [weaveworks/eksctl#2405]
**What happened?**
A description of actual behavior (with error messages).

```
$ eksctl create nodegroup --config-file=nodes-spot.yaml
[ℹ]  eksctl version 0.22.0
[ℹ]  using region us-east-1
[ℹ]  will use version 1.16 for new nodegroup(s) based on control plane version
[ℹ]  nodegroup "spot" will use "ami-0d960646974cf9e5b" [AmazonLinux2/1.16]
[ℹ]  using EC2 key pair "research-and-development"
[ℹ]  1 nodegroup (spot) was included (based on the include/exclude rules)
[ℹ]  will create a CloudFormation stack for each of 1 nodegroups in cluster "data-ops"
[ℹ]  2 sequential tasks: { fix cluster compatibility, 1 task: { 1 task: { create nodegroup "spot" } } }
[ℹ]  checking cluster stack for missing resources
[ℹ]  cluster stack has all required resources
[ℹ]  building nodegroup stack "eksctl-data-ops-nodegroup-spot"
[ℹ]  deploying stack "eksctl-data-ops-nodegroup-spot"
[✖]  unexpected status "ROLLBACK_COMPLETE" while waiting for CloudFormation stack "eksctl-data-ops-nodegroup-spot"
[ℹ]  fetching stack events in attempt to troubleshoot the root cause of the failure
[!]  AWS::EC2::SecurityGroup/SG: DELETE_IN_PROGRESS
[!]  AWS::EC2::SecurityGroupEgress/EgressInterClusterAPI: DELETE_IN_PROGRESS
[!]  AWS::EC2::SecurityGroupIngress/IngressInterClusterCP: DELETE_IN_PROGRESS
[!]  AWS::EC2::SecurityGroupIngress/IngressInterCluster: DELETE_IN_PROGRESS
[!]  AWS::EC2::SecurityGroupIngress/IngressInterClusterAPI: DELETE_IN_PROGRESS
[!]  AWS::EC2::SecurityGroupIngress/SSHIPv4: DELETE_IN_PROGRESS
[✖]  AWS::EC2::SecurityGroupIngress/SSHIPv4: CREATE_FAILED – "Resource creation cancelled"
[✖]  AWS::EC2::SecurityGroupIngress/IngressInterCluster: CREATE_FAILED – "Invalid id: \"\tsg-0e4a0bd710cdc07bf\" (expecting \"sg-...\") (Service: AmazonEC2; Status Code: 400; Error Code: InvalidGroupId.Malformed; Request ID: 848268a0-009a-43d5-8056-1007d197ad1b)"
[✖]  AWS::EC2::LaunchTemplate/NodeGroupLaunchTemplate: CREATE_FAILED – "Resource creation cancelled"
[✖]  AWS::EC2::SecurityGroupEgress/EgressInterClusterAPI: CREATE_FAILED – "Resource creation cancelled"
[✖]  AWS::EC2::SecurityGroupEgress/EgressInterCluster: CREATE_FAILED – "Resource creation cancelled"
[✖]  AWS::EC2::SecurityGroupIngress/IngressInterClusterCP: CREATE_FAILED – "Invalid id: \"\tsg-0e4a0bd710cdc07bf\" (expecting \"sg-...\") (Service: AmazonEC2; Status Code: 400; Error Code: InvalidGroupId.Malformed; Request ID: e4494376-a320-4263-84de-fb000c20722e)"
[✖]  AWS::EC2::SecurityGroupIngress/IngressInterClusterAPI: CREATE_FAILED – "Invalid id: \"\tsg-0e4a0bd710cdc07bf\" (expecting \"sg-...\") (Service: AmazonEC2; Status Code: 400; Error Code: InvalidGroupId.Malformed; Request ID: 7e33fbcf-0b2f-48e8-b5e0-e1462bf43d77)"
[ℹ]  1 error(s) occurred and nodegroups haven't been created properly, you may wish to check CloudFormation console
[ℹ]  to cleanup resources, run 'eksctl delete nodegroup --region=us-east-1 --cluster=data-ops --name=<name>' for each of the failed nodegroup
[✖]  waiting for CloudFormation stack "eksctl-data-ops-nodegroup-spot": ResourceNotReady: failed waiting for successful resource state
```
`nodes-spot.yaml` file content is:

```
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: data-ops
  region: us-east-1

nodeGroups:
  - name: spot
    labels: { role: workers }
    tags:
      cost_env: live
      cost_system: eks
      cost_company: gfg
      cost_type: containers
      cost_role: nodes
      cost_country: br
      cost_group: rnd
      k8s.io/cluster-autoscaler/data-ops: owned
      k8s.io/cluster-autoscaler/enabled: "true"
    minSize: 1
    maxSize: 50
    instancesDistribution:
      instanceTypes: ["a1.medium", "t3.small", "t3a.small"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0
      spotAllocationStrategy: lowest-price
    privateNetworking: true
    ssh:
      publicKeyName: "research-and-development"
    iam:
      instanceProfileARN: "arn:aws:iam::<account>:instance-profile/eks-node"
      instanceRoleARN: "arn:aws:iam::<account>:role/eks-node"
    securityGroups:
      attachIDs: ["sg-002ee18a6da0850e9"]
```

**What you expected to happen?**

I expected it would create a proper node group

**How to reproduce it?**
Include the steps to reproduce the bug

```
$ eksctl create cluster -f cluster.yaml
```

`cluster.yaml` file content: 

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: data-ops
  region: us-east-1

vpc:
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
  id: "vpc-049f0e62efc56a4d3"
  cidr: "<cidr>"
  securityGroup: "	sg-0e4a0bd710cdc07bf"
  subnets:
    private:
      us-east-1a: { id: subnet-075d809b75db84df6 }
      us-east-1b: { id: subnet-0842a56e5c657a4d5 }
    public:
      us-east-1a: { id: subnet-0c580418ae4614001 }
      us-east-1b: { id: subnet-0c3b8fca06a7f7df3 }

iam:
  serviceRoleARN: "arn:aws:iam::<account>:role/eks-cluster"

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
```

**Anything else we need to know?**
What OS are you using, are you using a downloaded binary or did you compile eksctl, what type of AWS credentials are you using (i.e. default/named profile, MFA) - please don't include actual credentials though!

OS: Ubuntu 20.04
binary downloaded eksctl
I'm using default AWS keys.

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
0.22.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:41:22Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
