### ISSUE TITLE
How to use a private cluster

### ISSUE THREAD

**Issue by JulianWgs** [weaveworks/eksctl#2441]
Hello, 

this question regards #2384. How do I connect kubectl to a private cluster? I've already read the [documentation](https://github.com/cPu1/eksctl/blob/9463c93f243f37d88821ffb627395b95cabf930e/userdocs/src/usage/eks-private-cluster.md), but there is only help for the configuration step, but not for the actual usage. Do I spin up a EC2 instance in that VPC? I tried, but I didn't get it to work.

My usecase is that I'm using EKS as a compute cluster with Dask. I'm reading and writing a lot of data to and from S3, which can get expensive with a NAT gateway enabled. No other networking is needed. 

Here is my cluster definition file for testing:
```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-cluster-01
  region: eu-central-1
  version: "1.16"

availabilityZones: ["eu-central-1a", "eu-central-1b","eu-central-1c"]

privateCluster:
  enabled: true

nodeGroups:
  - name: compute-nodes
    instanceType: mixed
    volumeSize: 10
    desiredCapacity: 2
    privateNetworking: true
    maxPodsPerNode: 10
    instancesDistribution:
      instanceTypes:
        - c5.2xlarge
      maxPrice: 0.20
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
```

**Versions**
eksctl version:
0.24.0-rc.0

kubectl version:
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"windows/amd64"}

Best regards,
Julian
