### ISSUE TITLE
T3 Unlimited support validation error

### ISSUE THREAD

**Issue by michaelbeaumont** [weaveworks/eksctl#2452]
Should this feature already work in eksctl 0.24.0-rc.1 with AWS Kubernetes? I'm getting the following error 

`Error: cpuCredits option set for nodegroup, but it has no t2/t3 instance types`

when executing

`eksctl create nodegroup -f ./kubernetes/EKS/eksctl-nodegroups.yaml`

with the following content for ./kubernetes/EKS/eksctl-nodegroups.yaml:
 
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: <CLUSTER_NAME>
  region: eu-central-1

nodeGroups:
  - name: small-spot-nodes2
    availabilityZones: ["eu-central-1b"]
    labels:
      pool:     small-spot-nodes2
      disksize: small
      nodesize: small
      nodetype: spot
    instancesDistribution:
      instanceTypes: ["t3.small","t3a.small"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0
      spotAllocationStrategy: "lowest-price"
      spotInstancePools: 2
    cpuCredits: "standard"
    minSize: 1
    maxSize: 20
    desiredCapacity: 1
    volumeSize: 20
    iam:
      withAddonPolicies:
        autoScaler: true
```

NOTE: my goal is to prevent t2/t3 spot instances to generate additional CPUCredits (the default seems to be "unlimited")
NOTE2: it does not matter if the nodegroup exists or not (tested by changing the name)
NOTE3: `cpuCredits` does not work for managedNodeGroups (`error unmarshaling JSON: while decoding JSON: json: unknown field "cpuCredits"`)
NOTE4: I upgraded my Cluster from 1.16 to 1.17 today via the AWS EKS control plane

_Originally posted by @joergrech in https://github.com/weaveworks/eksctl/pull/2391#issuecomment-660134564_

Only affects `rc`.
