### ISSUE TITLE
find out why EKS API doesn't support tags – file a bug

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#25]
https://github.com/weaveworks/eksctl/blob/0a39d1a2c1d107e1da90c27889d43bddba42ab3a/pkg/eks/eks.go#L22

**Comment by errordeveloper** [comment]
I've checked just now, and the [EKS API](https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateCluster.html) still doesn't support tags.

**Comment by gatesjd** [comment]
@errordeveloper, the [EKS API](https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateCluster.html) now shows tag support.

**Comment by mr-karan** [comment]
Maybe we can open this issue now?

**Comment by xmik** [comment]
Using eksctl 0.20.0 and having the following yaml config:
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-testing
  region: eu-west-1
  version: "1.15"
  tags:
    deployment: eks-testing
```

results in the tag `deployment: eks-testing` being set on a CloudFormation AWS resource, but not on AWS EKS resource. 
![eks-cf-tags](https://user-images.githubusercontent.com/8240219/83753925-6f76f580-a66b-11ea-8815-cbafc75f6c0e.png)

**Comment by xmik** [comment]
Using eksctl 0.20.0 and having the following yaml config:
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-testing
  region: eu-west-1
  version: "1.15"
  tags:
    deployment: eks-testing
```

results in the tag `deployment: eks-testing` being set on AWS EKS resource.
