### ISSUE TITLE
--ssh-access=false still creates SSH rule in SG

### ISSUE THREAD

**Issue by qlikmats** [weaveworks/eksctl#2533]
**What happened?**
When creating a cluster like:

`eksctl create cluster --name=foo --ssh-public-key=my_public_key --ssh-access=false`

The resulting nodegroup securitygroup, will have SSH open to the whole world (i.e. 0.0.0.0/0, ::/0) despite setting `--ssh-access=false`

**What you expected to happen?**
I would expect that there is no rule for opening the SSH port, in the generated security group.

**How to reproduce it?**

`eksctl create cluster --name=foo --ssh-public-key=my_public_key --ssh-access=false`
Check the securitygroup rules for the node instance(s), it will have a rule for SSH opened for 0.0.0.0/0, ::/0

Now, in contrast, run:
`eksctl create cluster -f cluster.yaml`

cluster.yaml:
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: foo
  region: us-east-1

nodeGroups:
  - name: ng-1
    availabilityZones: ["us-east-1a", "us-east-1b"]
    ssh:
      allow: false
      publicKeyName: my_public_key

availabilityZones: ["us-east-1a", "us-east-1b"]
```
Check the securitygroup rules for the node instance(s), it will (as expected) not have a rule for SSH

**Anything else we need to know?**

**Versions**

```
$ eksctl version
0.25.0
```
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**

*eksctl create cluster --name=foo --ssh-public-key=my_public_key --ssh-access=false*
```
2020-08-12T13:59:33+02:00 [▶]  cfg.json = \
{
...

    "nodeGroups": [
        {
...
            "ssh": {
                "allow": true,
                "publicKeyPath": "my_public_key",
                "publicKeyName": "my_public_key"
            },
```
*eksctl create cluster -f cluster.yaml*
```
2020-08-12T13:55:15+02:00 [▶]  cfg.json = \
...
    "nodeGroups": [
        {
...
            "ssh": {
                "allow": false,
                "publicKeyName": "my_public_key"
            },
```
