### ISSUE TITLE
Failed to create node group when instance type is set to t2.large

### ISSUE THREAD

**Issue by thwhk** [weaveworks/eksctl#2547]
**What happened?**
Failed to create node group when instance type is set to t2.large. But if I change to t3.medium, node group can be successfully created.

**What you expected to happen?**
Create a new node group, set instance type to t2.large. After a while, error message returned.

**How to reproduce it?**
I use the following config, and then run `eksctl create nodegroup --config-file=eks-config.yaml --include=ng-1-v2`
``` yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: sample-cluster
  region: ap-southeast-1

nodeGroups:
  - name: ng-1-v2
    instanceType: t2.large
    minSize: 1
    maxSize: 2
    desiredCapacity: 1
    ssh:
      allow: true
    labels: { lifecycle: OnDemand }
    volumeSize: 50
    volumeEncrypted: true
    ebsOptimized: true
    asgMetricsCollection:
      - granularity: 1Minute
        metrics:
          - GroupMinSize
          - GroupMaxSize
          - GroupDesiredCapacity
          - GroupInServiceInstances
          - GroupPendingInstances
          - GroupStandbyInstances
          - GroupTerminatingInstances
          - GroupTotalInstances
    iam:
      withAddonPolicies:
        certManager: true
        albIngress: true
        autoScaler: true
        ebs: true
        efs: true
        fsx: true
        cloudWatch: true
    preBootstrapCommands:
      - sudo yum install curl findmnt grep awk blkid lsblk ca-certificates iscsi-initiator-utils openssl11 -y
```

**Anything else we need to know?**
I used the same configuration, and change instance type to t3.medium, node group can be successfully created.

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
0.25.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T00:04:31Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.6-eks-4e7f64", GitCommit:"4e7f642f9f4cbb3c39a4fc6ee84fe341a8ade94c", GitTreeState:"clean", BuildDate:"2020-06-11T13:55:35Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**
```
➜ eksctl create nodegroup --config-file=eks-config.yaml --include=ng-1-v2 --profile=k8s
[ℹ]  eksctl version 0.25.0
[ℹ]  using region ap-southeast-1
[ℹ]  will use version 1.17 for new nodegroup(s) based on control plane version
[ℹ]  nodegroup "ng-1-v2" present in the given config, but missing in the cluster
[ℹ]  nodegroup "ng-1-v1" present in the cluster, but missing from the given config
[ℹ]  2 existing nodegroup(s) (ng-1-v1,ng-2vcpu-8gb-v4) will be excluded
[ℹ]  nodegroup "ng-1-v2" will use "ami-0bcf199e7e0892f8f" [AmazonLinux2/1.17]
[ℹ]  using SSH public key "./access-key/eks-key.pub" as "eksctl-sample-cluster-nodegroup-ng-1-v2-06:25:a0:13:24:e9:6d:86:2f:96:13:e9:73:19:31:f3" 
[ℹ]  combined include rules: ng-1-v2
[ℹ]  1 nodegroup (ng-1-v2) was included (based on the include/exclude rules)
[ℹ]  will create a CloudFormation stack for each of 1 nodegroups in cluster "sample-cluster"
[ℹ]  2 sequential tasks: { fix cluster compatibility, 1 task: { 1 task: { create nodegroup "ng-1-v2" } } }
[ℹ]  checking cluster stack for missing resources
[!]  retryable error (Throttling: Rate exceeded
        status code: 400, request id: 2b165da8-c37c-4c1d-9a55-017006a02d8a) from cloudformation/DescribeStacks - will retry after delay of 831.13628ms
[ℹ]  cluster stack has all required resources
[ℹ]  building nodegroup stack "eksctl-sample-cluster-nodegroup-ng-1-v2"
[ℹ]  deploying stack "eksctl-sample-cluster-nodegroup-ng-1-v2"
[✖]  unexpected status "ROLLBACK_IN_PROGRESS" while waiting for CloudFormation stack "eksctl-sample-cluster-nodegroup-ng-1-v2"
[ℹ]  fetching stack events in attempt to troubleshoot the root cause of the failure
[!]  AWS::IAM::Policy/PolicyCertManagerChangeSet: DELETE_IN_PROGRESS
[!]  AWS::IAM::Policy/PolicyFSX: DELETE_IN_PROGRESS
[!]  AWS::EC2::SecurityGroupIngress/IngressInterClusterCP: DELETE_IN_PROGRESS
[!]  AWS::IAM::Policy/PolicyCertManagerHostedZones: DELETE_IN_PROGRESS
[!]  AWS::EC2::SecurityGroupIngress/SSHIPv6: DELETE_IN_PROGRESS
[!]  AWS::IAM::Policy/PolicyEBS: DELETE_IN_PROGRESS
[!]  AWS::IAM::Policy/PolicyServiceLinkRole: DELETE_IN_PROGRESS
[!]  AWS::IAM::Policy/PolicyEFSEC2: DELETE_IN_PROGRESS
[!]  AWS::IAM::Policy/PolicyAutoScaling: DELETE_IN_PROGRESS
[!]  AWS::AutoScaling::AutoScalingGroup/NodeGroup: DELETE_IN_PROGRESS
[!]  AWS::EC2::SecurityGroupIngress/IngressInterCluster: DELETE_IN_PROGRESS
[!]  AWS::IAM::Policy/PolicyALBIngress: DELETE_IN_PROGRESS
[!]  AWS::EC2::SecurityGroupEgress/EgressInterCluster: DELETE_IN_PROGRESS
[!]  AWS::IAM::Policy/PolicyCertManagerGetChange: DELETE_IN_PROGRESS
[!]  AWS::IAM::Policy/PolicyEFS: DELETE_IN_PROGRESS
[!]  AWS::EC2::SecurityGroupIngress/SSHIPv4: DELETE_IN_PROGRESS
[!]  AWS::EC2::SecurityGroupEgress/EgressInterClusterAPI: DELETE_IN_PROGRESS
[!]  AWS::EC2::SecurityGroupIngress/IngressInterClusterAPI: DELETE_IN_PROGRESS
[✖]  AWS::AutoScaling::AutoScalingGroup/NodeGroup: CREATE_FAILED – "The requested configuration is currently not supported. Please check the documentation for supported configurations. Launching EC2 instance failed."
[ℹ]  1 error(s) occurred and nodegroups haven't been created properly, you may wish to check CloudFormation console
[ℹ]  to cleanup resources, run 'eksctl delete nodegroup --region=ap-southeast-1 --cluster=sample-cluster --name=<name>' for each of the failed nodegroup
[✖]  waiting for CloudFormation stack "eksctl-sample-cluster-nodegroup-ng-1-v2": ResourceNotReady: failed waiting for successful resource state
Error: failed to create nodegroups for cluster "sample-cluster"
```
