### ISSUE TITLE
How do I write the eksctl config so that when provisioning an EKS cluster, it uses a private subnet, and can it be configured for external communication using a NAT gateway?

### ISSUE THREAD

**Issue by BangShinChul** [weaveworks/eksctl#2557]
Please [search existing issues (open & closed)](https://github.com/weaveworks/eksctl/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if there is a similar one. If there is, add comments or vote where appropriate.

If you did not find a similar issue or if it did not help then ask for help in our [slack channel](https://weave-community.slack.com/messages/eksctl/)

**What help do you need?**

Hi, My name is Bang shin chul.
I am simply and surprisingly configuring an EKS cluster using eksctl.
Thank you! :) 
I have some questions while using eksctl.
First of all, the eksctl config contents I used are as follows.

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: bangshinchul-test
  region: ap-northeast-2
  version: "1.16"

vpc:
  cidr: "172.56.0.0/16"
  nat:
    gateway: Single

nodeGroups:
  - name: bangshinchul-test-ng
    instanceType: t3a.large
    privateNetworking: true
    desiredCapacity: 1 # EC2 count
    volumeSize: 20  # GiB
    iam:
      withAddonPolicies:    
        ImageBuilder: true # allow r/w access to ECR
        albIngress: true  # allow alb ingress
    ssh:
      allow: true
      publicKeyName: my-ssh-key
    
```

Basically, when I provisioning an EKS cluster through eksctl, I seen that Internet Gateway and NAT Gateway are provisioned, as well as multiple public and private subnets.
In addition, it was confirmed that the worker node is basically assigned a public IP using a public subnet and communicates with the Internet through the Internet Gateway.

I want to provision an EKS cluster like below using eksctl.
- All worker nodes use a private subnet.
- All worker nodes route 0.0.0.0/0 to the NAT gateway.
- NAT Gateway routes 0.0.0.0/0 to Internet Gateway.

How do I write the eksctl config so that when provisioning an EKS cluster, it uses a private subnet, and can it be configured for external communication using a NAT gateway?
If you don't mind, please give me a reference document or a config example that I can refer to?

Thank you.

**Comment by cPu1** [comment]
Hi. Bang Shin Chul 🙂 

>In addition, it was confirmed that the worker node is basically assigned a public IP using a public subnet and communicates with the Internet through the Internet Gateway.

The worker node will not be assigned a public IP if you set `privateNetworking` to `true`, which you've set in your nodegroup config. Can you double-check your worker node and config?


> I want to provision an EKS cluster like below using eksctl.
> 
> All worker nodes use a private subnet.
> All worker nodes route 0.0.0.0/0 to the NAT gateway.
> NAT Gateway routes 0.0.0.0/0 to Internet Gateway.

If you set `privateNetworking: true`, this will be the behaviour. Your config looks right to me for the behaviour you want.

**Comment by BangShinChul** [comment]
Hello @cPu1 
Thank you for your reply.

I was mistaken.
As you said, worker nodes are deployed on a private subnet.
And I figured out how to write a config file to get the function I want!

The config I added is below. :
```
vpc:
  nat:
    gateway: Single
  clusterEndpoints:   <-- additional config
    publicAccess: true
    privateAccess: true

```

Adding the above, the AWS infrastructure is provisioned according to the 3 requirements I wanted! :+1: 
Thank you for your help :smile:
