### ISSUE TITLE
`eksctl create cluster` results in unstable cluster

### ISSUE THREAD

**Issue by stevenroussey-privicy** [weaveworks/eksctl#2566]
**What happened?**
The cluster is unstable for a time, and doing anything else with it may make it permanently unusable.

While starting up, the kublet is not reporting correctly and the node will be tainted, resulting in coredns (usually) or others to get stopped and hopefully restarted. But starting other services at the same time generally results in the nodes being unreachable forever.

**What you expected to happen?**
No nodes get tainted.

**How to reproduce it?**
cluster.yaml:
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-cluster
  region: us-east-2

cloudWatch:
  clusterLogging:
    enableTypes: ["audit", "authenticator", "controllerManager"]

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: cluster-autoscaler
      namespace: kube-system
      labels: {aws-usage: "cluster-ops"}
    attachPolicy: # inline policy can be defined along with `attachPolicyARNs`
      Version: "2012-10-17"
      Statement:
      - Effect: Allow
        Action:
        - "autoscaling:DescribeAutoScalingGroups"
        - "autoscaling:DescribeAutoScalingInstances"
        - "autoscaling:DescribeLaunchConfigurations"
        - "autoscaling:DescribeTags"
        - "autoscaling:SetDesiredCapacity"
        - "autoscaling:TerminateInstanceInAutoScalingGroup"
        Resource: '*'

nodeGroups:
  - name: ng-1
    tags:
      # EC2 tags required for cluster-autoscaler auto-discovery
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/test-cluster: "owned"
    desiredCapacity: 2
    instanceType: t3.large
    iam:
      withAddonPolicies:
        albIngress: true
        autoScaler: true
        cloudWatch: true
```
`eksctl create cluster -f cluster.yaml`
`sleep 360 & kubectl get events -A  | grep FailedScheduling`
```
kube-system   44m         Warning   FailedScheduling          pod/coredns-67bfd975c5-7whwm                                   no nodes available to schedule pods
kube-system   43m         Warning   FailedScheduling          pod/coredns-67bfd975c5-7whwm                                   0/1 nodes are available: 1 node(s) had taints that the pod didn't tolerate.
kube-system   43m         Warning   FailedScheduling          pod/coredns-67bfd975c5-7whwm                                   0/2 nodes are available: 2 node(s) had taints that the pod didn't tolerate.
kube-system   44m         Warning   FailedScheduling          pod/coredns-67bfd975c5-fl7mc                                   no nodes available to schedule pods
kube-system   43m         Warning   FailedScheduling          pod/coredns-67bfd975c5-fl7mc                                   0/1 nodes are available: 1 node(s) had taints that the pod didn't tolerate.
kube-system   43m         Warning   FailedScheduling          pod/coredns-67bfd975c5-fl7mc                                   0/2 nodes are available: 2 node(s) had taints that the pod didn't tolerate.
```

**Versions**
```
~/C/p/cluster ❯❯❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:40:13Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
~/C/p/cluster ❯❯❯ brew upgrade kubectl
Warning: kubectl 1.18.8 already installed
~/C/p/cluster ❯❯❯ eksctl version 
0.26.0
~/C/p/cluster ❯❯❯ uname -a
Darwin Stevens-iMac-2.lan 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64
```
