### ISSUE TITLE
block service account access to k8s APIs by exposing automountServiceAccountToken flag

### ISSUE THREAD

**Issue by stoiev** [weaveworks/eksctl#2604]
**Why do you want this feature?**
In almost all cases, application service accounts do not need access to kubernetes APIs.
Blocking pods access to those APIs is good practice in terms of security.

**What feature/behavior/change do you want?**
Since kubernetes 1.6, there is a [`automountServiceAccountToken`](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#use-the-default-service-account-to-access-the-api-server) that controls k8s API token generation.
 Actually, there is no way to change it on `eksctl` managed service accounts.

The propose is to export this flag in `eksctl` config files / CLI commands for end user.

Example:
config
```yaml
serviceAccounts:
 - name: my-service-account
   namespace: my-namespace
   attachPolicyARNs:
     - arn:...
   automountServiceAccountToken: false
```
cli
```bash
eksctl create iamserviceaccount \
   --cluster=<clusterName>\
   --name=my-service-account\
   --namespace=my-namespace
   --attach-policy-arn=arn:...\
   --automountServiceAccountToken=false
```

This would create a service account with corresponding flag set:
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      ...
  creationTimestamp: "2020-03-20T12:51:02Z"
  name: my-service-account
  namespace: my-namespace
automountServiceAccountToken: false
```
