### ISSUE TITLE
"tags" doesn't work for "managedNodeGroups"

### ISSUE THREAD

**Issue by sunao-uehara** [weaveworks/eksctl#2607]
**What happened?**
`tags` configuration of "managedNodeGroups" doesn't add tag to ec2 instance. Some tags; it seems they are reserved one are added properly, for example `eks:cluster-name: <cluster_name>`, ` eks:nodegroup-name: <worker_name>`, but none of my own custom tags are added. Is it by design or bug? At least I can see the configuration in official docs https://eksctl.io/usage/schema/.
By the way, It works for normal "nodeGroups".

**What you expected to happen?**
Key:Values pair of the tags should be added to ec2 instance/worker node.

**How to reproduce it?**
```
eksctl create nodegroup -f config.yaml --include=workers-1
```

**Anything else we need to know?**
OSX Mojave,
eksctl installed through Homebrew

**Versions**
```
$ eksctl version
0.23.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.7-eks-bffbac", GitCommit:"bffbacfd13a805a12d10ccc0ca26205ae1ca76e9", GitTreeState:"clean", BuildDate:"2020-07-08T18:30:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-14f01f", GitCommit:"14f01fe8f04411d5e187b220034ca2117d79f7de", GitTreeState:"clean", BuildDate:"2020-05-23T21:32:47Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

Here is my yaml config file.
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: cluster-1
  region: us-east-1
  version: "1.15"
  tags: {Env: dev}
vpc:
  cidr: x.x.x.x/16
  subnets:
    private:
      us-east-1a: { id: subnet-xxxxxxxxx }
      us-east-1b: { id: subnet-xxxxxxxxx }
      us-east-1c: { id: subnet-xxxxxxxxx }
iam:
  serviceRoleARN: "arn:aws:iam::xxxxxxxxx:role/xxxxxxxxx"

cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator", "controllerManager", "scheduler"]

managedNodeGroups:
  - name: workers-1
    instanceType: m5.large
    privateNetworking: true
    minSize: 3
    maxSize: 5
    desiredCapacity: 3
    amiFamily: AmazonLinux2
    ssh:
      allow: true
      publicKeyName: 'xxxxxx'
    tags:
      Env: dev
      Name: workers-1
      cluster-name: cluster-1
      foo: var
    iam:
      attachPolicyARNs:
        - "arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy"
        - "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"
        - "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
      withAddonPolicies:
        autoScaler: true
        imageBuilder: true
    volumeSize: 20
```
