### ISSUE TITLE
eksctl scale nodegroup --config-file --name <nodegroup>: node group <nodegroup> not found

### ISSUE THREAD

**Issue by iAnomaly** [weaveworks/eksctl#2655]
**What happened?**
`eksctl scale nodegroup --config-file config.yaml --name <nodegroup>` results in `node group <nodegroup> not found`

**What you expected to happen?**
1. `eksctl scale nodegroup --config-file config.yaml --name <nodegroup>` should succeed in applying the current desiredCapacity, minSize, maxSize properties of the nodeGroups/managedNodeGroups instance(s) from the config.yaml file.

2. Also would be great if `--name` could be omitted (not required) in which case ALL nodegroups would be scaled to current supplied config spec.

**How to reproduce it?**
1. Launch a cluster using a valid config.yaml with at least one nodegroup and then attempt: `eksctl scale nodegroup --config-file config.yaml --name <nodegroup>` where `config.yaml` is your cluster configuration file and `<nodegroup>` is the name of one of your node groups defined in that cluster config file.

Also note that `eksctl scale nodegroup --cluster <cluster> --name <nodegroup> --minSize 0` works fine even when using the same values that should be read from `config.yaml` if `--config-file config.yaml` were to be used instead. In other words, the bug appears specific to the `--config-file config.yaml` option.

**Anything else we need to know?**
macOS Homebrew eksctl binary

**Versions**
Please paste in the output of these commands:
```
$ eksctl 0.27.0
$ kubectl 1.16.9
```

**Comment by OriHoch** [comment]
I also encounter this bug

config:

eksctl v0.31.0

```
kind: ClusterConfig
apiVersion: eksctl.io/v1alpha5
metadata:
  name: main
  region: eu-west-2
  version: "1.18"
  tags:
    constru-k8s: main
managedNodeGroups:
  - name: ng-2
    instanceType: t3.large
    desiredCapacity: 0
  - name: ng-3
    instanceType: t3.large
    desiredCapacity: 1
    availabilityZones: ["eu-west-2c"]
```

```
$ eksctl scale nodegroup -f config.yaml --name ng-2
Error: node group ng-2 not found
```
