### ISSUE TITLE
No schema check for the property "attachPolicyARNs"

### ISSUE THREAD

**Issue by hassanSRE** [weaveworks/eksctl#2682]
**What happened?**
When creating a simple config file to create a nodegroup that includes the property attachPolicyARNs, if the attach policy arn property is not written exactly like "attachPolicyARNs:", it is ignore. Example:
``` yaml
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-name
  region: ap-southeast-2

nodeGroups:
  - name: ng-name
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::ACCOUNT:policy/SOME_POLICY
```

The above will be ignored and all 3 default node policies will be added instead
**Note** the above property `attachPolicyArns` isn't exactly the same as `attachPolicyARNs`. Changing the above property to the exact described schema `attachPolicyARNs` works fine

**What you expected to happen?**
If the property attachPolicyARNs added is not adhering to the case sensitivity, it should throw a schema validation error instead of just ignoring it 

**How to reproduce it?**
Add the following in the config schema:
nodeGroups:
  - name: ng-name
    ...
    iam:
      attachPolicyArns: ## <----- Note that this isn't exactly like `attachPolicyARNs` 
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::ACCOUNT:policy/NAME_OF_POLIC

**Versions**
Please paste in the output of these commands:
```
$ eksctl version 0.28.1
$ kubectl version v1.15.10-eks-bac369
```
