### ISSUE TITLE
kubelet doesnt start when trying to run user-data in the overrideBootstrapCommand using unmanaged node-groups

### ISSUE THREAD

**Issue by shacharaj** [weaveworks/eksctl#2694]
**What happened?**
A description of actual behavior (with error messages).
I am using unmanaged node-groups for my cluster,
I am trying to run user-data in the **overrideBootstrapCommand** but every time I am running the create node group command the instances are being created in the cloud formation stack but they are not joined to the cluster due to failure in starting the kubelet service.

**The command I used:**
`eksctl create nodegroup -f c:\GitRepos\bitbucket\devops\EKS\Clusters\EV-DevOps-EKS.yaml`

**The command output: (timeout after 25 minutes)**
```
[ℹ]  eksctl version 0.28.1
[ℹ]  using region eu-west-2
[ℹ]  nodegroup "ev-devops-V1-16" present in the given config, but missing in the cluster
[ℹ]  nodegroup "ev-devopsV116" present in the cluster, but missing from the given config
[ℹ]  1 existing nodegroup(s) (ev-devopsV116) will be excluded
[ℹ]  nodegroup "ev-devops-V1-16" will use "ami-060c87ac45f6e8e1f" [AmazonLinux2/1.16]
[ℹ]  using EC2 key pair %!!(MISSING)q(*string=<nil>)
[!]  retryable error (Throttling: Rate exceeded
        status code: 400, request id: 62b51ec3-a977-4e5d-b309-776d784374ee) from cloudformation/DescribeStacks - will retry after delay of 738.07895ms
[!]  retryable error (Throttling: Rate exceeded
        status code: 400, request id: e606b2c8-955e-435c-b82c-11fc7a7d8818) from cloudformation/DescribeStacks - will retry after delay of 1.099335702s
[ℹ]  1 nodegroup (ev-devops-V1-16) was included (based on the include/exclude rules)
[ℹ]  will create a CloudFormation stack for each of 1 nodegroups in cluster "EV-DevOps-EKS"
[ℹ]  2 sequential tasks: { fix cluster compatibility, 1 task: { 1 task: { create nodegroup "ev-devops-V1-16" } } }
[ℹ]  checking cluster stack for missing resources
[!]  retryable error (Throttling: Rate exceeded
        status code: 400, request id: 1d503797-8422-457f-83f7-92766775c6b8) from cloudformation/DescribeStacks - will retry after delay of 539.829444ms
[!]  retryable error (Throttling: Rate exceeded
        status code: 400, request id: ca513e32-e9b0-493f-88b8-1e637ca8838b) from cloudformation/DescribeStacks - will retry after delay of 1.629503854s
[ℹ]  cluster stack has all required resources
[ℹ]  building nodegroup stack "eksctl-EV-DevOps-EKS-nodegroup-ev-devops-V1-16"
[ℹ]  deploying stack "eksctl-EV-DevOps-EKS-nodegroup-ev-devops-V1-16"
[ℹ]  no tasks
[ℹ]  adding identity "arn:aws:iam::157508415698:role/EV-Dev-EKS-Worker-Role" to auth ConfigMap
[ℹ]  nodegroup "ev-devops-V1-16" has 0 node(s)
[ℹ]  waiting for at least 2 node(s) to become ready in "ev-devops-V1-16"
```

when logging in to the instance I see in the cloud-init-output.log that my commands ran successfully:

```
No packages needed for security; 8 packages available
Resolving Dependencies
Cloud-init v. 19.3-3.amzn2 running 'modules:final' at Wed, 30 Sep 2020 13:48:17 +0000. Up 23.20 seconds.
shahar
Cloud-init v. 19.3-3.amzn2 finished at Wed, 30 Sep 2020 13:48:17 +0000. Datasource DataSourceEc2.  Up 23.41 seconds

```
**But I can also see that the nodes are joined to the cluster and kubelet failed to start:**
```
systemctl status kubelet.service
● kubelet.service - Kubernetes Kubelet
   Loaded: loaded (/etc/systemd/system/kubelet.service; disabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-eksclt.al2.conf
   Active: inactive (dead)
     Docs: https://github.com/kubernetes/kubernetes
```
**my eksctl configuration file:**

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: EV-DevOps-EKS
  region: eu-west-2
  version: "1.16"

vpc:
  id: "vpc-092b5c40bxxxxxx"
  cidr: "10.xxx.x.0/16"
  subnets:
    private:
      eu-west-2a:
        id: "subnet-0393bb40ec70cxxx"
        cidr: "10.xxx.x.0/24"
      eu-west-2b:
        id: "subnet-0d81268c2c12cxxx"
        cidr: "10.xxx.x.0/24"
    public:
      eu-west-2a:
        id: "subnet-0ea2b191286634xxx"
        cidr: "10.xxx.x.0/24"
      eu-west-2b:
        id: "subnet-0361209474dc6fxxx"
        cidr: "10.xxx.x.0/24"
iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: rest-service-sa
      namespace: default
      labels: {service-name: "rest-service"}
    attachPolicyARNs:
    - "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"
    - "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
    - "arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy"
	
nodeGroups:
  - name: ev-devops-V1-16
    minSize: 2
    maxSize: 2
    instancesDistribution:
      maxPrice: 0.05
      instanceTypes: ["t3.large"] # At least one instance type should be specified
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 50
      spotInstancePools: 2
    ami: ami-060c87ac45f6e8e1f
    amiFamily: AmazonLinux2
    desiredCapacity: 2
    iam:
      instanceProfileARN: "arn:aws:iam::15750XXX:instance-profile/EV-Dev-EKS-Worker-Instance-Profile"
      instanceRoleARN: "arn:aws:iam::15750XXX:role/EV-Dev-EKS-Worker-Role"
    volumeSize: 25
    volumeType: gp2
    privateNetworking: true
    securityGroups:
      withShared: true
      withLocal: true
      attachIDs: [ sg-0c4f67efXXX, # EV-Dev-DB-Client-SG
                   sg-03c0c980XXX, # EV-Dev-base_sg
      ]
    ssh:
      publicKeyPath: 'EV-Dev-EKS_16-Mar-2020'
    overrideBootstrapCommand: 'echo "shahar" && touch ~/shahar'
    tags:
      'Env': 'EV-Dev'
      'label': 'ev-devops-V1-16'
    labels:
      nodegroup-type: ev-devops-V1-16
      eks.amazonaws.com/nodegroup: ev-devops-V1-16             #<node-group-name>
      eks.amazonaws.com/nodegroup-image: ami-060c87ac45f6e8e1f  #<ami-id>
```

**What you expected to happen?**

I except the my user data script to run and the nodes to be joined to the cluster when running:` kubectl get nodes`

**How to reproduce it?**
Create EKS k8s cluster 1.16 using eksctl and the configuration file above.

**Anything else we need to know?**
I am using Windows so I used latest chocolaty installation of eksctl.
my AWS credentials are taken from ~/.aws/credentials

**Versions**
Please paste in the output of these commands:
```
$ eksctl version - 0.28.1
$ kubectl version 
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-eks-2ba888", GitCommit:"2ba888155c7f8093a1bc06e3336333fbdb27b3da", GitTreeState:"clean", BuildDate:"2020-07-17T18:48:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**

**The command I used:**
`eksctl create nodegroup -f c:\GitRepos\bitbucket\devops\EKS\Clusters\EV-DevOps-EKS.yaml`

**The command output: (timeout after 25 minutes)**
```
[ℹ]  eksctl version 0.28.1
[ℹ]  using region eu-west-2
[ℹ]  nodegroup "ev-devops-V1-16" present in the given config, but missing in the cluster
[ℹ]  nodegroup "ev-devopsV116" present in the cluster, but missing from the given config
[ℹ]  1 existing nodegroup(s) (ev-devopsV116) will be excluded
[ℹ]  nodegroup "ev-devops-V1-16" will use "ami-060c87ac45f6e8e1f" [AmazonLinux2/1.16]
[ℹ]  using EC2 key pair %!!(MISSING)q(*string=<nil>)
[!]  retryable error (Throttling: Rate exceeded
        status code: 400, request id: 62b51ec3-a977-4e5d-b309-776d784374ee) from cloudformation/DescribeStacks - will retry after delay of 738.07895ms
[!]  retryable error (Throttling: Rate exceeded
        status code: 400, request id: e606b2c8-955e-435c-b82c-11fc7a7d8818) from cloudformation/DescribeStacks - will retry after delay of 1.099335702s
[ℹ]  1 nodegroup (ev-devops-V1-16) was included (based on the include/exclude rules)
[ℹ]  will create a CloudFormation stack for each of 1 nodegroups in cluster "EV-DevOps-EKS"
[ℹ]  2 sequential tasks: { fix cluster compatibility, 1 task: { 1 task: { create nodegroup "ev-devops-V1-16" } } }
[ℹ]  checking cluster stack for missing resources
[!]  retryable error (Throttling: Rate exceeded
        status code: 400, request id: 1d503797-8422-457f-83f7-92766775c6b8) from cloudformation/DescribeStacks - will retry after delay of 539.829444ms
[!]  retryable error (Throttling: Rate exceeded
        status code: 400, request id: ca513e32-e9b0-493f-88b8-1e637ca8838b) from cloudformation/DescribeStacks - will retry after delay of 1.629503854s
[ℹ]  cluster stack has all required resources
[ℹ]  building nodegroup stack "eksctl-EV-DevOps-EKS-nodegroup-ev-devops-V1-16"
[ℹ]  deploying stack "eksctl-EV-DevOps-EKS-nodegroup-ev-devops-V1-16"
[ℹ]  no tasks
[ℹ]  adding identity "arn:aws:iam::157508415698:role/EV-Dev-EKS-Worker-Role" to auth ConfigMap
[ℹ]  nodegroup "ev-devops-V1-16" has 0 node(s)
[ℹ]  waiting for at least 2 node(s) to become ready in "ev-devops-V1-16"
```

**journalctl -xe**:

```
-- Unit kubelet.service has begun starting up.
Oct 01 12:31:46 ip-10-171-2-82.ev-dev-vpc dhclient[2835]: XMT: Solicit on eth0, interval 121750ms.
Oct 01 12:31:47 ip-10-171-2-82.ev-dev-vpc systemd[1]: kubelet.service holdoff time over, scheduling restart.
Oct 01 12:31:47 ip-10-171-2-82.ev-dev-vpc systemd[1]: Failed to load environment files: No such file or directory
Oct 01 12:31:47 ip-10-171-2-82.ev-dev-vpc systemd[1]: kubelet.service failed to run 'start-pre' task: No such file or directory
Oct 01 12:31:47 ip-10-171-2-82.ev-dev-vpc systemd[1]: Failed to start Kubernetes Kubelet.
-- Subject: Unit kubelet.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit kubelet.service has failed.

```
