### ISSUE TITLE
invalid capacity 0 on image filesystem

### ISSUE THREAD

**Issue by sk-credify** [weaveworks/eksctl#2707]
**What happened?**

When using `kubectl describe nodes`, the reason was `invalid capacity 0 on image filesystem`

**How to reproduce it?**
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-cluster
  region: <REDACTED>

nodeGroups:
  - name: node-services
    labels: { role: services }
    instanceType: m5a.xlarge
    desiredCapacity: 1
    amiFamily: Bottlerocket
    privateNetworking: true
    volumeSize: 200
    ssh:
      allow: true
      publicKeyName: <REDACTED>
    bottlerocket:
      settings:
        motd: "<REDACTED>"
```

**Versions**
Please paste in the output of these commands:
```
$ eksctl version: 0.29.1
$ kubectl version: v1.19.2
```

**Logs**
Include the output of the command line when running eksctl. If possible, eksctl should be run with debug logs. For example:
`eksctl get clusters -v 4`

```
2020-10-05T18:46:27+07:00 [▶]  role ARN for the current session is "arn:aws:iam::<REDACTED>:<REDACTED>"
NAME					REGION
test-cluster				ap-southeast-1
```
