### ISSUE TITLE
Managed Nodegroup + fully private cluster failed to stabilize + minor documentation bug

### ISSUE THREAD

**Issue by epcim** [weaveworks/eksctl#2735]
```
[ℹ]  eksctl version 0.29.1
[ℹ]  using region eu-central-1
```

**1. Documentation says private/public subnets are being /19 but 0.29.x does different defaults**
```
[ℹ]  subnets for eu-central-1c - public:172.16.128.0/21 private:172.16.152.0/21
[ℹ]  subnets for eu-central-1b - public:172.16.136.0/21 private:172.16.160.0/21
[ℹ]  subnets for eu-central-1a - public:172.16.144.0/21 private:172.16.168.0/21
```

**2. Complex deployments with managed node groups fails**

Configuration example attached below. I have tried multiple times (5x and more) multiple regions (eu, asia), during creation AWS change status of nodegroup and start rollback. 

Deployment fails with:
- `Nodegroup lma-v17 failed to stabilize`
- `Unhealthy nodes in the kubernetes cluster`

Issues:
- Eksctl is missing a way to configure "Rollback configuration" for stack or way how "stability" is measured.
- As rolback start, there is no way to re-try, upgrade. On another "create" eksctl just reports the stack already exist. On "update" that was not found. This is abusing it's declarative approach.

Is there any way how to avoid this AWS behaviour?

```
...
...
[ℹ]  daemonset "kube-system/aws-node" restarted
[ℹ]  building managed nodegroup stack "eksctl-acme-nodegroup-lma-v17"
[ℹ]  building managed nodegroup stack "eksctl-acme-nodegroup-main-v17"
[ℹ]  deploying stack "eksctl-acme-nodegroup-lma-v17"
[ℹ]  deploying stack "eksctl-acme-nodegroup-main-v17"
[✖]  unexpected status "ROLLBACK_IN_PROGRESS" while waiting for CloudFormation stack "eksctl-acme-nodegroup-lma-v17"
[ℹ]  fetching stack events in attempt to troubleshoot the root cause of the failure
[✖]  AWS::EKS::Nodegroup/ManagedNodeGroup: CREATE_FAILED – "Nodegroup lma-v17 failed to stabilize: [{Code: NodeCreationFailure,Message: Unhealthy nodes in the kubernetes cluster,ResourceIds: [i-004c77f25c1282523, i-01df8e25bc70f2726, i-092d1303de2472434]}]"
[!]  1 error(s) occurred and cluster hasn't been created properly, you may wish to check CloudFormation console
[ℹ]  to cleanup resources, run 'eksctl delete cluster --region=eu-central-1 --name=acme'
[✖]  waiting for CloudFormation stack "eksctl-acme-nodegroup-lma-v17": ResourceNotReady: failed waiting for successful resource state
```

config snippet:

```
iam:
  withOIDC: true

managedNodeGroups:
  - name: main-v17
    instanceType: t3.2xlarge
    desiredCapacity: 3
    minSize: 3
    maxSize: 5
    # instancesDistribution: {}
    volumeSize: 100
    privateNetworking: true
    #maxPodsPerNode:
    #securityGroups:
    #labels: {role: worker}
    tags: &tags
      cluster: 'gc01'
    ssh: &ssh
      publicKeyPath: ~/.sshx/id_rsa.pub
    iam: &iam
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM

  - name: lma-v17
    instanceType: m5.large
    desiredCapacity: 3
    volumeSize: 100
    privateNetworking: true
    tags: *tags
    ssh: *ssh
    iam: *iam


```

/kind:bug

**Comment by jwitrick** [comment]
Seems very similar to what I am seeing. If i drop eksctl version down to 0.27.0 i can create my cluster and nodegroups correctly. but any higher version of eksctl the nodegroups fail to stabilize. 

My cluster file contains this:
 `managedNodeGroups:
  - name: ng-us-east1a-m5
    instanceType: m5.2xlarge
    minSize: 1
    desiredCapacity: 1
    maxSize: 10
    availabilityZones: ["us-east-1a"]
    volumeSize: 250
    ssh:
      allow: false
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true
        albIngress: true
        autoScaler: true
        cloudWatch: true
        ebs: true
        fsx: true
        efs: true
    privateNetworking: true`

**Comment by michaelbeaumont** [comment]
@jwitrick Do you have `iam.withOIDC: true`?

**Comment by michaelbeaumont** [comment]
As far as the subnets, have you specified anything in the VPC configuration? The docs mention `/19` subnets only for the default VPC, as far as I can tell, which I just verified does create `/19` subnets.

**Comment by epcim** [comment]
> Seems very similar to what I am seeing. If i drop eksctl version down to 0.27.0 i can create my cluster and nodegroups correctly. but any higher version of eksctl the nodegroups fail to stabilize.
> 
> My cluster file contains this:
> 
> ```
> managedNodeGroups:
>   - name: ng-us-east1a-m5
>     instanceType: m5.2xlarge
>     minSize: 1
>     desiredCapacity: 1
>     maxSize: 10
>     availabilityZones: ["us-east-1a"]
>     volumeSize: 250
>     ssh:
>       allow: false
>     iam:
>       withAddonPolicies:
>         externalDNS: true
>         certManager: true
>         albIngress: true
>         autoScaler: true
>         cloudWatch: true
>         ebs: true
>         fsx: true
>         efs: true
>     privateNetworking: true
> ```
> 
> >

in my case, `0.27.0` didnt work either

**Comment by epcim** [comment]
> As far as the subnets, have you specified anything in the VPC configuration? The docs mention `/19` subnets only for the default VPC, as far as I can tell, which I just verified does create `/19` subnets.

only this  (actually was not an intention but overlook) I wanted to keep subnets not specified at all.
```

vpc:
  subnets:
    public: {}
```

so where it took /21 ? 
```
[ℹ]  subnets for eu-central-1c - public:172.16.128.0/21 private:172.16.152.0/21
```

**Comment by epcim** [comment]
> @jwitrick Do you have `iam.withOIDC: true`?
> 
> @epcim I can't reproduce the behavior with your config. You're right about the CFN rollback behavior, I think that'd be an easy feature to add. (EDIT: feature added)

Full config, maybe `privateCluster` does the thing?

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: gc01
  region: ap-northeast-1
  version: "1.17"

privateCluster:
  enabled: true

iam:
  withOIDC: true

managedNodeGroups:
  - name: main-v17
    instanceType: t3.2xlarge
    desiredCapacity: 3
    minSize: 3
    maxSize: 5
    volumeSize: 100
    privateNetworking: true
    tags: &tags
      cluster: 'gc01'
    ssh: &ssh
      publicKeyPath: ~/.sshx/id_rsa.pub
    iam: &iam
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      preBootstrapCommands: &preBootstrapCommands
      - |
        echo '#install curl,nslookup,dig and nc'
        yum install -y bind-utils nmap-ncat curl
      - |
        echo '#setup journald log rotate, replacing the blank, commented-out versions'
        sed -i 's/\#SystemMaxUse\=/SystemMaxUse\=200M/' /etc/systemd/journald.conf
        sed -i 's/\#SystemKeepFree\=/SystemKeepFree\=200M/' /etc/systemd/journald.conf
        sed -i 's/\#SystemMaxFileSize\=/SystemMaxFileSize\=10M/' /etc/systemd/journald.conf
        #- |
        echo '#SSM > SSH'
        yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
        systemctl start amazon-ssm-agent
      - |
        echo '#begin bootstrap.sh'

  - name: lma-v17
    #instanceType: r5.2xlarge
    instanceType: m5.large
    desiredCapacity: 1
    volumeSize: 100
    privateNetworking: true
    tags: *tags
    ssh: *ssh
    iam: *iam
    preBootstrapCommands: *preBootstrapCommands

```

I am testing without `preBootstrapCommands`
