### ISSUE TITLE
Managed NodeGroup creates only t3.medium instances in ap-northeast-2 

### ISSUE THREAD

**Issue by anamika-avinash** [weaveworks/eksctl#2736]
**What happened?**
Created an EKS cluster and one managed node group  (instance type: m5.8xl) using 0.29.2 version in the ap-northeast-2 region. 
Following which, I added the below lines to the config file for a new managed node group using the same instance type. Instances get created and the console displays m5.8xl instances. However, on the EC2 console the instances for the new managed nodegroup are all launched as t3.medium instances. 

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: aidp2
  region: ap-northeast-2

vpc:
  id: "vpc-xxxx"  # (optional, must match VPC ID used for each subnet below)
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
  subnets:
    # must provide 'private' and/or 'public' subnets by availibility zone as shown
    private:
      vpc-internal-b:
        id: "subnet-xxxx"
      vpc-internal-a:
        id: "subnet-xxxx"

managedNodeGroups:
  - name: ng-1
    instanceType: m5.8xlarge
    desiredCapacity: 5
    privateNetworking: true # if only 'Private' subnets are given, this must be enabled
    ssh: # use existing EC2 key
      publicKeyName: aws-xxx-xxx

  - name: ng-test. # <- New Managed NodeGroup 
    instanceType: m5.8xlarge
    desiredCapacity: 5
    privateNetworking: true # if only 'Private' subnets are given, this must be enabled
    ssh: # use existing EC2 key
      publicKeyName: aws-xxx-xxx

```

**What you expected to happen?**
The worker node instances to be launched in the new managed nodegroup should be launched according to the selected instance type. 

**How to reproduce it?**
- Create an EKS cluster and managed nodegroup using the above config file without the ng-test managed nodegroup in the ap-northeast-2 region. 
- Following this add the new managed nodegroup to the config file and run the command 

```
eksctl create nodegroup --config-file=eksctl --include='ng-test' --exclude='ng-1'
```

- Notice the EKS console . the compute region will indicate that the instances are m5.8xlarge 
- The EC2 console for the same instances will display all the instances as t3.medium instances. 

**Anything else we need to know?**
EKSCTL version 0.29.2
AWS region: ap-northeast-2

I have tested this in eu-west-1 and us-east-1 as well. It works as expected there.

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
0.29.2

```
