### ISSUE TITLE
create cluster fails with SAs after version 0.28 (timeout checking for SA namespace)

### ISSUE THREAD

**Issue by derekwlmscfa** [weaveworks/eksctl#2755]
**What happened?**
`eksctl create cluster` fails when there are `iam.serviceAccounts` in the config - i/o timeout checking if the SA namespace exists. The cluster is created, but eksctl quits early before creating nodegroups and remaining CF stacks.

**What you expected to happen?**
Fully successful cluster creation, including all nodegroups, SA roles, etc.

**How to reproduce it?**
- Use a recent `eksctl` version; for example 0.29.2 or 0.30.1
- Create a cluster config with `iam.serviceAccounts` and `nodeGroups` specified
- Run `eksctl create cluster --configfile ...`

**Anything else we need to know?**
May be related to recent changes where SAs are created before nodegroups.

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
0.30.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-eks-2ba888", GitCommit:"2ba888155c7f8093a1bc06e3336333fbdb27b3da", GitTreeState:"clean", BuildDate:"2020-07-17T18:48:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**
```
[ℹ]  eksctl version 0.30.0
[ℹ]  using region us-east-1
[✔]  using existing VPC (vpc-0...6e) and subnets (private:[subnet-0...e8 subnet-0...79 subnet-0...e2] public:[subnet-0...c subnet-0...9b subnet-0...76 subnet-0...6a])
[!]  custom VPC/subnets will be used; if resulting cluster doesn't function as expected, make sure to review the configuration of VPC/subnets
[ℹ]  nodegroup "ng-2020-10-19a" will use "ami-0b0dffffb5ba92f97" [AmazonLinux2/1.16]
[ℹ]  using Kubernetes version 1.16
[ℹ]  creating EKS cluster "kcp-dev-4" in "us-east-1" region with un-managed nodes
[ℹ]  1 nodegroup (ng-2020-10-19a) was included (based on the include/exclude rules)
[ℹ]  will create a CloudFormation stack for cluster itself and 1 nodegroup stack(s)
[ℹ]  will create a CloudFormation stack for cluster itself and 0 managed nodegroup stack(s)
[ℹ]  if you encounter any issues, check CloudFormation console or try 'eksctl utils describe-stacks --region=us-east-1 --cluster=kcp-dev-4'
[ℹ]  CloudWatch logging will not be enabled for cluster "kcp-dev-4" in "us-east-1"
[ℹ]  you can enable it with 'eksctl utils update-cluster-logging --enable-types={SPECIFY-YOUR-LOG-TYPES-HERE (e.g. all)} --region=us-east-1 --cluster=kcp-dev-4'
[ℹ]  Kubernetes API endpoint access will use default of {publicAccess=true, privateAccess=false} for cluster "kcp-dev-4" in "us-east-1"
[ℹ]  2 sequential tasks: { create cluster control plane "kcp-dev-4", 2 sequential sub-tasks: { 3 sequential sub-tasks: { associate IAM OIDC provider, 5 parallel sub-tasks: { 2 sequential sub-tasks: { create IAM role for serviceaccount "kube-system/external-dns", create serviceaccount "kube-system/external-dns" }, 2 sequential sub-tasks: { create IAM role for serviceaccount "kube-system/kubernetes-external-secrets", create serviceaccount "kube-system/kubernetes-external-secrets" }, 2 sequential sub-tasks: { create IAM role for serviceaccount "kube-system/alb-ingress-controller", create serviceaccount "kube-system/alb-ingress-controller" }, 2 sequential sub-tasks: { create IAM role for serviceaccount "kube-system/cloudformation-operator", create serviceaccount "kube-system/cloudformation-operator" }, 2 sequential sub-tasks: { create IAM role for serviceaccount "kube-system/aws-node", create serviceaccount "kube-system/aws-node" } }, restart daemonset "kube-system/aws-node" }, create nodegroup "ng-2020-10-19a" } }
[ℹ]  building cluster stack "eksctl-kcp-dev-4-cluster"
[ℹ]  deploying stack "eksctl-kcp-dev-4-cluster"
[ℹ]  building iamserviceaccount stack "eksctl-kcp-dev-4-addon-iamserviceaccount-kube-system-aws-node"
[ℹ]  building iamserviceaccount stack "eksctl-kcp-dev-4-addon-iamserviceaccount-kube-system-cloudformation-operator"
[ℹ]  building iamserviceaccount stack "eksctl-kcp-dev-4-addon-iamserviceaccount-kube-system-kubernetes-external-secrets"
[ℹ]  building iamserviceaccount stack "eksctl-kcp-dev-4-addon-iamserviceaccount-kube-system-alb-ingress-controller"
[ℹ]  building iamserviceaccount stack "eksctl-kcp-dev-4-addon-iamserviceaccount-kube-system-external-dns"
[ℹ]  deploying stack "eksctl-kcp-dev-4-addon-iamserviceaccount-kube-system-cloudformation-operator"
[ℹ]  deploying stack "eksctl-kcp-dev-4-addon-iamserviceaccount-kube-system-kubernetes-external-secrets"
[ℹ]  deploying stack "eksctl-kcp-dev-4-addon-iamserviceaccount-kube-system-aws-node"
[ℹ]  deploying stack "eksctl-kcp-dev-4-addon-iamserviceaccount-kube-system-external-dns"
[ℹ]  deploying stack "eksctl-kcp-dev-4-addon-iamserviceaccount-kube-system-alb-ingress-controller"
[!]  1 error(s) occurred and cluster hasn't been created properly, you may wish to check CloudFormation console
[ℹ]  to cleanup resources, run 'eksctl delete cluster --region=us-east-1 --name=kcp-dev-4'
[✖]  checking whether namespace "kube-system" exists: Get "https://CC85184B9BD549ADF6CD06B52B69B0BB.gr7.us-east-1.eks.amazonaws.com/api/v1/namespaces/kube-system": dial tcp 54.156.33.229:443: i/o timeout
```

**Comment by michaelbeaumont** [comment]
I can't reproduce this with `examples/13-iamserviceaccounts.yaml`, can you include a config which fails to create?

**Comment by derekwlmscfa** [comment]
> I can't reproduce this with `examples/13-iamserviceaccounts.yaml` (and `master`), can you include a config which fails to create?

Sure, here's the full config with acct # redacted:
```
apiVersion: eksctl.io/v1alpha5
iam:
  serviceAccounts:
  - attachPolicyARNs:
    - arn:aws:iam::8...9:policy/ExternalDns
    metadata:
      name: external-dns
      namespace: kube-system
  - attachPolicyARNs:
    - arn:aws:iam::8...9:policy/ExternalSecrets
    metadata:
      name: kubernetes-external-secrets
      namespace: kube-system
  - attachPolicyARNs:
    - arn:aws:iam::8...9:policy/AlbIngressController
    metadata:
      name: alb-ingress-controller
      namespace: kube-system
  - attachPolicyARNs:
    - arn:aws:iam::8...9:policy/CloudformationOperator
    metadata:
      name: cloudformation-operator
      namespace: kube-system
  withOIDC: true
kind: ClusterConfig
metadata:
  name: kcp-dev-4
  region: us-east-1
  version: "1.16"
nodeGroups:
- iam:
    attachPolicyARNs:
    - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
    - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
    - arn:aws:iam::8...9:policy/ssm-ec2-policy
    - arn:aws:iam::8...9:policy/AlbIngressController
    - arn:aws:iam::8...9:policy/PrometheusThanos
    withAddonPolicies:
      appMesh: true
      autoScaler: true
      ebs: true
  instanceType: t3.xlarge
  kubeletExtraConfig:
    cgroupRoot: /
    eventRecordQPS: 0
    featureGates:
      DynamicKubeletConfig: true
      RotateKubeletServerCertificate: true
    kubeReserved:
      cpu: 100m
      ephemeral-storage: 1Gi
      memory: 100Mi
    serializeImagePulls: false
    systemReserved:
      cpu: 100m
      ephemeral-storage: 1Gi
      memory: 100Mi
  labels:
    lifecycle: OnDemand
  maxSize: 10
  minSize: 3
  name: ng-2020-10-19a
  preBootstrapCommands:
  - cd /tmp; sudo yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
  privateNetworking: true
  volumeSize: 100
  volumeType: gp2
vpc:
  id: vpc-0aef9924f06fe4e6e
  subnets:
    private:
      us-east-1a:
        id: subnet-0065f6cc0d1507f79
      us-east-1b:
        id: subnet-0a3a8c466e3bc5c23
      us-east-1c:
        id: subnet-0421c323b4b27a2e2
      us-east-1d:
        id: subnet-0989b5bc947524fe8
    public:
      us-east-1a:
        id: subnet-09bd96006bb8a3a8c
      us-east-1b:
        id: subnet-0d904c8345b429b9b
      us-east-1c:
        id: subnet-0f78f91806b6b5676
      us-east-1d:
        id: subnet-03cbf4c06b998a46a

```
