### ISSUE TITLE
Add "arm64" value when updating kube-proxy with the command "eksctl utils update-kube-proxy".

### ISSUE THREAD

**Issue by a2ush** [weaveworks/eksctl#2763]
**Why do you want this feature?**
The commend `eksctl utils update-kube-proxy --cluster <cluster-name> --approve` does not provide "arm64" value.
But these commands `eksctl utils update-aws-node` and `eksctl utils update-codedns` provide "arm64" value.

So if we want to use ARM worker nodes in our cluster, we need to add "arm64" manually to kube-proxy DaemonSet config.

$ kubectl edit -n kube-system daemonset/kube-proxy
```
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            ...
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - amd64
                  - arm64
```
※ This operation is required if our cluster was deployed before August 17,2020.
https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html

**What feature/behavior/change do you want?**

I think the same update method as "aws-nodes" or "coredns" should be introduced to "kube-proxy".
It looks good to have an asset for "kube-proxy", and to reffer it when updating.

[kube-proxy]
https://github.com/weaveworks/eksctl/blob/master/pkg/addons/default/kube_proxy.go#L46
[aws-node]
https://github.com/weaveworks/eksctl/blob/master/pkg/addons/default/aws_node.go#L67
```
	// if DaemonSets is present, go through our list of assets
	list, err := LoadAsset(AWSNode, "yaml")
```
[coredns]
https://github.com/weaveworks/eksctl/blob/master/pkg/addons/default/coredns.go#L27
```
	// if Deployment is present, go through our list of assets
	list, err := loadAssetCoreDNS(controlPlaneVersion)
```
