### ISSUE TITLE
Capability to set the IAM Role path for all created resources

### ISSUE THREAD

**Issue by ryphon** [weaveworks/eksctl#2764]
**Why do you want this feature?**
This is relevant mostly to the setup that I have to work around regarding tag based and path based service separation in one shared AWS Account. I'm required to have a path that follows a certain service name, so if my serivce is "EKSCluster", my IAM roles need to live under `arn:aws:iam::123456789012:role/EKSCluster/*`. 

**What feature/behavior/change do you want?**
CloudFormation stacks already support using the Path in the variables, it just needs to be enabled so that we can set a path in the role creation (including the aws-node service account role if possible, but this seems more hidden away).
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html

Use case is similar to #2351, where my roles require certain settings that aren't on by default, however this would allow the CloudFormation stacks to build out the roles rather than trying to do it externally via TF or similar.

Do not hesitate, when appropriate, to share the exact commands or API you would like, and/or to share a diagram (e.g.: asciiflow.com):

```
iam:
  serviceAccounts:
    - attachPolicyARNs:
        - arn:aws:iam::12345678910:policy/eks/eks-alb-ingress-policy
      rolePath: /eksctltest/asdf/
      metadata:
        name: alb-ingress-controller
        namespace: kube-system
      permissionsBoundary: arn:aws:iam::12345678910:policy/permissions-boundary
      tags:
        Component: eksctl-test
  serviceRolePermissionsBoundary: arn:aws:iam::12345678910/policy/permissions-boundary
  withOIDC: true
```
