### ISSUE TITLE
NodeInstanceProfile CREATE_FAILED: "The specified value for roleName is invalid"

### ISSUE THREAD

**Issue by michaelbeaumont** [weaveworks/eksctl#2768]
**What happened?**
When a nodegroup contains `instanceRoleARN` but not `instanceProfileARN`, the nodegroup fails with the error:
```
CREATE_FAILED - "The specified value for roleName is invalid"
```

**What you expected to happen?**
The instance profile to be created successfully

**How to reproduce it?**
Config contains:
```
nodeGroups:
  - name: ng
    iam:
      instanceRoleARN: arn:aws:iam::123:role/path/rolename
```

Nodegroup stack includes:

```
    "NodeInstanceProfile": {
      "Type": "AWS::IAM::InstanceProfile",
      "Properties": {
        "Path": "/",
        "Roles": [
          "arn:aws:iam::123:role/rolename"
        ]
      }
    },
```
**Anything else we need to know?**
`0.30.0`
