### ISSUE TITLE
create nodegroup creates 2 volumes, the root doesn't honor volumeSize

### ISSUE THREAD

**Issue by derekwlmscfa** [weaveworks/eksctl#2776]
**What happened?**
`create nodegroup` is creating the EC2 nodes with two (not one) attached EBS volumes. The root volume is only 20GB, too small for use. The second volume is 100GB, honoring the `volumeSize` I specified.

**What you expected to happen?**
There should only be the one volume I specified in the config file, honoring the `volumeSize`. Or if two volumes are created, provide a way to control the root volume size.

**How to reproduce it?**
`eksctl create nodegroup --include='ng-2020-10-26b*' --config-file=cfg.yaml`

**Anything else we need to know?**
I did not see this behavior with other nodegroups I created in the past. Differences here are 1) different eksctl version, and 2) using Bottlerocket `amiFamily`.

Relevant config file portion (sensitive data redacted):
```
  - name: ng-2020-10-26br
    amiFamily: Bottlerocket
    ami: auto-ssm
    labels:
      "bottlerocket.aws/updater-interface-version": "1.0.0"
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
      withAddonPolicies:
        appMesh: true
        autoScaler: true
        ebs: true
    instanceType: c5n.4xlarge
    maxSize: 75
    desiredCapacity: 8
    minSize: 8
    privateNetworking: true
    volumeSize: 100
    volumeType: gp2
```

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
0.30.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-065dce", GitCommit:"065dcecfcd2a91bd68a17ee0b5e895088430bd05", GitTreeState:"clean", BuildDate:"2020-07-16T01:44:47Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**
Include the output of the command line when running eksctl. If possible, eksctl should be run with debug logs. For example:
`eksctl get clusters -v 4`
Make sure you redact any sensitive information before posting.
If the output is long, please consider a Gist.
