### ISSUE TITLE
Changing instance type

### ISSUE THREAD

**Issue by danielrmartin** [weaveworks/eksctl#280]
After upgrading from: 
versionInfo = map[string]string{“builtAt”:“2018-08-02T13:58:30Z”, “gitCommit”:“dca39f69e893b89d67156635c483b3f3e8236407", “gitTag”:“0.1.0"}
 to 
versionInfo = map[string]string{“builtAt”:“2018-10-18T09:39:17Z”, “gitCommit”:“42472284809120503270b4401ce07ad26f52ffa4", “gitTag”:“0.1.7"}

I am not longer able to change the instance type the cluster is using, either through the AWS UI, or eckctl. 
In the earlier version of the tool, I could create a changeset and move the cluster t2.medium  to any other instance type.

**Comment by errordeveloper** [comment]
Yes, we have decided to make CloudFormation an implementation detail, because it's hard to support everything that user may do there long term.

We are planning to add nodegroup management (#257), which would allow for what you need as well as upgrades (#100), enabling/disabling SSH access (#144), finer instance role control and more. Not all of those use-cases could be cater for via CloudFormation stack parameters as easily as what you did for instance type, which was another reason we have decided to abandon stack parameters.

**Comment by errordeveloper** [comment]
@richardcase how is the progress on #257, do you need any help there?

**Comment by richardcase** [comment]
@errordeveloper - i'm currently working on #257, still a bit more work to do. Hopefully get something up this week.

**Comment by errordeveloper** [comment]
Closing as this this pre-dates nodegroup management.

**Comment by masterkain** [comment]
hello,
so if I have a default nodegroup running now and I want to change instance types (mostly because c5 seems to have issues with properly mounting EBS) is downgrading to m4 something I can do with eksctl now?

cluster bootstrapped with:

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: bsmart
  region: eu-central-1

nodeGroups:
  - name: default
    instanceType: c5.2xlarge
    volumeSize: 100
    desiredCapacity: 3
    iam:
      withAddonPolicies:
        albIngress: true
        autoScaler: true
        appMesh: true
        xRay: true
        cloudWatch: true
```
