### ISSUE TITLE
Managed Node Group Create Failed - Ec2SubnetInvalidConfiguration Health issue type

### ISSUE THREAD

**Issue by kellen-dunham** [weaveworks/eksctl#2834]
Please [search existing issues (open & closed)](https://github.com/weaveworks/eksctl/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if there is a similar one. If there is, add comments or vote where appropriate.

If you did not find a similar issue or if it did not help then ask for help in our [slack channel](https://weave-community.slack.com/messages/eksctl/)

**What help do you need?**
Describe the type of help you need.
Please include your config, removing any sensitive information, or exact commands you're using.

I have created a new EKS cluster with public and private networking support via a config.yaml and using existing VPC subnets. Managed node groups placed on the public subnets (with Auto Public IP enabled and a route table with default route to IGW) create fine and nodes join cluster OK. However managed node groups placed on the private subnets (with Auto Public IP disabled and a route table with default route to NGW), fail to create. The error received is:

Ec2SubnetInvalidConfiguration - One or more Amazon EC2 Subnets of [subnet-A, subnet-B] for node group the-private-managed-ng-1 does not automatically assign public IP addresses to instances launched into it. If you want your instances to be assigned a public IP address, then you need to enable auto-assign public IP address for the subnet. See IP addressing in VPC guide: https://docs.aws.amazon.com/vpc/latest/userguide/vpc-ip-addressing.html#subnet-public-ip

Also note that I can set the private Auto Public IP to enabled, create a managed node group, then turn public IP off the subnet, terminate an instance, wait for a new instance to come up. In this setup the new instance does not have a public IP and can join the cluster OK, however the node group is now in a "Degraded" state and lists the above health issue.

I have reason to believe that there is something that I am not setting correctly in eksctl config yaml to create the cluster and / or managed node group. I've tried several times yesterday with different configs but each attempt seems to result in the same error - and it takes a while to test each cluster since cluster create / modification takes a long time.

Is there something that I am not setting up properly? Here is an example config I am using:

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: test-eks-cluster-1
  region: us-east-1
  version: "1.18"
vpc:
 id: vpc-A
  subnets:
    private:
      us-east-1c: { id: subnet-A }
      us-east-1e: { id: subnet-B }
    public:
      us-east-1c: { id: subnet-C }
      us-east-1e: { id: subnet-D }
  clusterEndpoints:
    privateAccess: true
    publicAccess: true
managedNodeGroups:
- name: test-public-managed-ng-1
  amiFamily: AmazonLinux2
  instanceType: t3.medium
  desiredCapacity: 2
  volumeSize: 20
  volumeEncrypted: true
  ssh:
    allow: false # will use ~/.ssh/id_rsa.pub as the default ssh key
- name: test-private-managed-ng-1
  amiFamily: AmazonLinux2
  instanceType: t3.medium
  desiredCapacity: 2
  volumeSize: 20
  volumeEncrypted: true
  privateNetworking: true
  ssh:
    allow: false # will use ~/.ssh/id_rsa.pub as the default ssh key
```
