### ISSUE TITLE
fail to create the cluster in ap-northeast-2

### ISSUE THREAD

**Issue by limyc** [weaveworks/eksctl#2853]
**What happened?**
An error occurs while creating eks 1.18 in ap-northeast-2.
Until yesterday there were no problems with creation.

In us-east-1 it is created without problems.
Also, 1.17 is no problem with creation in ap-northeast-2.

**What you expected to happen?**
It should be created without problems.

**How to reproduce it?**
```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ekstest
  region: ap-northeast-2
  version: "1.18"

availabilityZones: ["ap-northeast-2a", "ap-northeast-2c"]

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: external-dns
      namespace: kube-system
      labels: {aws-usage: "application"}
    attachPolicy:
      Version: "2012-10-17"
      Statement:
      - Effect: Allow
        Action:
        - "route53:ChangeResourceRecordSets"
        Resource: 'arn:aws:route53:::hostedzone/*'
      - Effect: Allow
        Action:
        - "route53:ListHostedZones"
        - "route53:ListResourceRecordSets"
        - "route53:ListTagsForResource"
        Resource: '*'
  - metadata:
      name: cluster-autoscaler
      namespace: kube-system
      labels: {aws-usage: "cluster-ops"}
    attachPolicy:
      Version: "2012-10-17"
      Statement:
      - Effect: Allow
        Action:
        - "autoscaling:DescribeAutoScalingGroups"
        - "autoscaling:DescribeAutoScalingInstances"
        - "autoscaling:DescribeLaunchConfigurations"
        - "autoscaling:DescribeTags"
        - "autoscaling:SetDesiredCapacity"
        - "autoscaling:TerminateInstanceInAutoScalingGroup"
        Resource: '*'

managedNodeGroups:
  - name: cpu
    minSize: 1
    maxSize: 20
    instanceType: c5.2xlarge
    desiredCapacity: 4
    volumeSize: 200
    privateNetworking: true
    iam:
      withAddonPolicies:
        albIngress: true
```

```bash
$ eksctl create cluster -f cluster.yaml
```

**Anything else we need to know?**
eksctl - https://github.com/weaveworks/eksctl/releases/download/0.31.0/eksctl_Linux_amd64.tar.gz

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
0.31.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.8-eks-7c9bda", GitCommit:"7c9bda52c425d0d56d7b93f1377a826b4132c05c", GitTreeState:"clean", BuildDate:"2020-08-28T23:07:29Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**

```bash
➜ eksctl create cluster -f cluster.yaml
[ℹ]  eksctl version 0.31.0
[ℹ]  using region ap-northeast-2
[ℹ]  subnets for ap-northeast-2a - public:192.168.0.0/19 private:192.168.64.0/19
[ℹ]  subnets for ap-northeast-2c - public:192.168.32.0/19 private:192.168.96.0/19
[ℹ]  using Kubernetes version 1.18
[ℹ]  creating EKS cluster "ekstest" in "ap-northeast-2" region with managed nodes
[ℹ]  1 nodegroup (cpu) was included (based on the include/exclude rules)
[ℹ]  will create a CloudFormation stack for cluster itself and 0 nodegroup stack(s)
[ℹ]  will create a CloudFormation stack for cluster itself and 1 managed nodegroup stack(s)
[ℹ]  if you encounter any issues, check CloudFormation console or try 'eksctl utils describe-stacks --region=ap-northeast-2 --cluster=ekstest'
[ℹ]  CloudWatch logging will not be enabled for cluster "ekstest" in "ap-northeast-2"
[ℹ]  you can enable it with 'eksctl utils update-cluster-logging --enable-types={SPECIFY-YOUR-LOG-TYPES-HERE (e.g. all)} --region=ap-northeast-2 --cluster=ekstest'
[ℹ]  Kubernetes API endpoint access will use default of {publicAccess=true, privateAccess=false} for cluster "ekstest" in "ap-northeast-2"
[ℹ]  2 sequential tasks: { create cluster control plane "ekstest", 2 sequential sub-tasks: { 3 sequential sub-tasks: { associate IAM OIDC provider, 3 parallel sub-tasks: { 2 sequential sub-tasks: { create IAM role for serviceaccount "kube-system/external-dns", create serviceaccount "kube-system/external-dns" }, 2 sequential sub-tasks: { create IAM role for serviceaccount "kube-system/cluster-autoscaler", create serviceaccount "kube-system/cluster-autoscaler" }, 2 sequential sub-tasks: { create IAM role for serviceaccount "kube-system/aws-node", create serviceaccount "kube-system/aws-node" } }, restart daemonset "kube-system/aws-node" }, create managed nodegroup "cpu" } }
[ℹ]  building cluster stack "eksctl-ekstest-cluster"
[ℹ]  deploying stack "eksctl-ekstest-cluster"
[✖]  unexpected status "ROLLBACK_IN_PROGRESS" while waiting for CloudFormation stack "eksctl-ekstest-cluster"
[ℹ]  fetching stack events in attempt to troubleshoot the root cause of the failure
[!]  AWS::EC2::SubnetRouteTableAssociation/RouteTableAssociationPublicAPNORTHEAST2C: DELETE_IN_PROGRESS
[!]  AWS::EC2::SecurityGroupIngress/IngressInterNodeGroupSG: DELETE_IN_PROGRESS
[!]  AWS::IAM::Policy/PolicyCloudWatchMetrics: DELETE_IN_PROGRESS
[!]  AWS::EC2::NatGateway/NATGateway: DELETE_IN_PROGRESS
[!]  AWS::EC2::Route/PublicSubnetRoute: DELETE_IN_PROGRESS
[!]  AWS::EC2::SubnetRouteTableAssociation/RouteTableAssociationPrivateAPNORTHEAST2A: DELETE_IN_PROGRESS
[!]  AWS::IAM::Policy/PolicyELBPermissions: DELETE_IN_PROGRESS
[!]  AWS::EC2::SubnetRouteTableAssociation/RouteTableAssociationPublicAPNORTHEAST2A: DELETE_IN_PROGRESS
[!]  AWS::EC2::SubnetRouteTableAssociation/RouteTableAssociationPrivateAPNORTHEAST2C: DELETE_IN_PROGRESS
[✖]  AWS::EC2::SubnetRouteTableAssociation/RouteTableAssociationPublicAPNORTHEAST2C: CREATE_FAILED – "Resource creation cancelled"
[✖]  AWS::EC2::NatGateway/NATGateway: CREATE_FAILED – "Resource creation cancelled"
[✖]  AWS::EC2::Route/PublicSubnetRoute: CREATE_FAILED – "Resource creation cancelled"
[✖]  AWS::IAM::Policy/PolicyELBPermissions: CREATE_FAILED – "Resource creation cancelled"
[✖]  AWS::IAM::Policy/PolicyCloudWatchMetrics: CREATE_FAILED – "Resource creation cancelled"
[✖]  AWS::EC2::SubnetRouteTableAssociation/RouteTableAssociationPrivateAPNORTHEAST2C: CREATE_FAILED – "Resource creation cancelled"
[✖]  AWS::EC2::SubnetRouteTableAssociation/RouteTableAssociationPrivateAPNORTHEAST2A: CREATE_FAILED – "Resource creation cancelled"
[✖]  AWS::EC2::SubnetRouteTableAssociation/RouteTableAssociationPublicAPNORTHEAST2A: CREATE_FAILED – "Resource creation cancelled"
[✖]  AWS::EKS::Cluster/ControlPlane: CREATE_FAILED – "unsupported Kubernetes version (Service: AmazonEKS; Status Code: 400; Error Code: InvalidParameterException; Request ID: 10259306-3203-454a-a55d-85f6120c65d0; Proxy: null)"
[!]  1 error(s) occurred and cluster hasn't been created properly, you may wish to check CloudFormation console
[ℹ]  to cleanup resources, run 'eksctl delete cluster --region=ap-northeast-2 --name=ekstest'
[✖]  waiting for CloudFormation stack "eksctl-ekstest-cluster": ResourceNotReady: failed waiting for successful resource state
Error: failed to create cluster "ekstest"
```
