### ISSUE TITLE
Create a cluster in a single Availability Zone for testing

### ISSUE THREAD

**Issue by cucosion** [weaveworks/eksctl#2854]
I see that there was a similar request: https://github.com/weaveworks/eksctl/issues/1142

**Why do you want this feature?**
We perform tests that generate a lot of traffic between nodes and from what I see for all the inter AZ communication we have to pay, the example we found out that we had around a few hundred terabytes of traffic in one week at 0.01 $ per GB.
https://aws.amazon.com/ec2/pricing/on-demand/#Data_Transfer 
https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html -  Amazon EKS requires subnets in at least two Availability Zones.
Other people who complained:
https://www.duckbillgroup.com/blog/aws-cross-az-data-transfer-costs-more-than-aws-says/
https://blog.doit-intl.com/aws-data-transfer-in-is-not-always-free-3c1553234d06 

It's not a blocker but a nice to have a feature to be able fast enough to deploy in a single AZ.

**What feature/behavior/change do you want?**
To be able to deploy all the nodes in the same zone, or to create the cluster in a region with multiple zones but to have a flag that will create the nodes in the same zone. 

Example from GKE command:
gcloud container clusters create <cluster name> --zone us-west1-b --num-nodes=2 --machine-type=c2-standard-8 --image-type ubuntu --cluster-version "1.16.13-gke.1"

Something similar to the below command will be nice:
eksctl create cluster --name <cluster_name> --version 1.16 --region us-west-1 --nodegroup-name ng-1 --node-type c5n.2xlarge --nodes 2 --nodes-min 1 --nodes-max 2 **--single-az true** --managed

**Comment by cPu1** [comment]
Creating a nodegroup in a single AZ is already supported today by specifying a single availability zone, as in:

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster
  region: us-west-2

availabilityZones: ["us-west-2a", "us-west-2b"]

managedNodeGroups:
- name: ng
  availabilityZones: ["us-west-2a"]
```

Using CLI options:

```
$ eksctl create cluster --name=cluster --zones=us-west-2a,us-west-2b --node-zones=us-west-2a
```
