### ISSUE TITLE
Upgrading Cluster to include logging does not work

### ISSUE THREAD

**Issue by kennedy** [weaveworks/eksctl#2862]
**What happened?**
I wanted to upgrade my cluster to have logging with a configuration file

**What you expected to happen?**
Used `eksctl upgrade cluster -f .\cluster.yml` to turn on logging

**How to reproduce it?**
1. Create a cluster config file without logging:
``` yaml
# cluster.yml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dev
  region: us-east-1
  version: "1.18"
  tags: 
    'owner': "kennedy"
managedNodeGroups:
  - name: standard-workers
    instanceType: t3.micro
    desiredCapacity: 3
    minSize: 2
    maxSize: 3
```
2. Create cluster with `eksctl create cluster -f .\cluster.yml`
3. Add logging to config file:
``` yaml
# cluster.yml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dev
  region: us-east-1
  version: "1.18"
  tags: 
    'owner': "kennedy"
cloudWatch:
  clusterLogging:
    enableTypes: ["all"]
managedNodeGroups:
  - name: standard-workers
    instanceType: t3.micro
    desiredCapacity: 3
    minSize: 2
    maxSize: 3
```
4. Upgrade cluster with `eksctl upgrade cluster -f .\cluster.yml`
5. Upgrade was success but logging was not enabled

**Anything else we need to know?**
I am on win10 20H2. I downloaded eksctl from scoop via official msi installer, and kubectl from choco using official msi. I am using my full admin AWS profile with MFA

**Versions**
Please paste in the output of these commands:
```
$ kubectl version --client
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"windows/amd64"}

$ eksctl version
0.31.0

$ aws --version
aws-cli/2.1.2 Python/3.7.7 Windows/10 exe/AMD64
```

**Logs**
```
eksctl upgrade cluster -f .\cluster.yml
[ℹ]  eksctl version 0.31.0
[ℹ]  using region us-east-1
[!]  NOTE: cluster VPC (subnets, routing & NAT Gateway) configuration changes are not yet implemented
[ℹ]  re-building cluster stack "eksctl-dev-cluster"
[✔]  all resources in cluster stack "eksctl-dev-cluster" are up-to-date
[ℹ]  checking security group configuration for all nodegroups
[ℹ]  all nodegroups have up-to-date configuration
```
