### ISSUE TITLE
Support for EBS gp3 volume type/ storage class

### ISSUE THREAD

**Issue by mihaylovmihail** [weaveworks/eksctl#2891]
*Before creating a feature request, please search existing feature requests to see if you find a similar one. If there is a similar feature request please up-vote it and/or add your comments to it instead*

**Why do you want this feature?**
Because the new AWS EBS gp3 volume type provide faster and cheaper disks. Here is the description: https://aws.amazon.com/blogs/aws/new-amazon-ebs-gp3-volume-lets-you-provision-performance-separate-from-capacity-and-offers-20-lower-price/

**What feature/behavior/change do you want?**

Support for AWS EBS gp3 volume type in cluster configuration file. For example:

```
nodeGroups:
  - name: my-ng
    instanceType: m5.xlarge
    desiredCapacity: 20
    privateNetworking: true
    volumeSize: 40
    volumeType: gp3
```

Do not hesitate, when appropriate, to share the exact commands or API you would like, and/or to share a diagram (e.g.: asciiflow.com): "a picture is worth a thousand words".
