### ISSUE TITLE
Cannot create cluster on VPC sharing

### ISSUE THREAD

**Issue by oemdaro** [weaveworks/eksctl#2910]
**What happened?**
I have follow the blog post for managing network for multiple accounts ([VPC sharing: A new approach to multiple accounts and VPC management](https://aws.amazon.com/blogs/networking-and-content-delivery/vpc-sharing-a-new-approach-to-multiple-accounts-and-vpc-management/)"), and I'm using `Terraform` to create a VPC separately.

After VPC is created, I'm try to create cluster using `eksctl`. But it's failed to create cluster with following error:

```
➜ eksctl create cluster -f cluster-fargate.yaml       
[ℹ]  eksctl version 0.33.0
[ℹ]  using region us-east-1
Error: couldn't import subnet subnet-02f40929da636XXXX: subnet ID "subnet-0c1cea405c930XXXX" is not the same as "subnet-02f40929da636XXXX"
```

But if I create it on the VPC owner account, it's success. Failed when create cluster on the consumer account.

**What you expected to happen?**
 It should allow to create cluster on the VPC sharing.

**How to reproduce it?**
The steps to reproduce the bug.

```shell
➜ eksctl create cluster -f cluster-fargate.yaml
```

Config file:

```yaml
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-1
  region: us-east-1

vpc:
  id: "vpc-05771844cd553XXXX"
  subnets:
    private:
      us-east-1a:
        id: "subnet-0c1cea405c930XXXX"
      us-east-1b:
        id: "subnet-02f40929da636XXXX"
      us-east-1c:
        id: "subnet-03ed850729dcbXXXX"
    public:
      us-east-1a:
        id: "subnet-0d0b82ae511dcXXXX"
      us-east-1b:
        id: "subnet-05f92323fe646XXXX"
      us-east-1c:
        id: "subnet-0720b95dc8743XXXX"

fargateProfiles:
  - name: fp-default
    selectors:
      # All workloads in the "default" Kubernetes namespace will be
      # scheduled onto Fargate:
      - namespace: default
      # All workloads in the "kube-system" Kubernetes namespace will be
      # scheduled onto Fargate:
      - namespace: kube-system

```

**Anything else we need to know?**

I'm install `eksctl` using `brew` on macOS Big Sur.

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
0.33.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
```

**Logs**
