### ISSUE TITLE
Add support for specifying imageGCLowThresholdPercent & imageGCHighThresholdPercent

### ISSUE THREAD

**Issue by adnan-kamili** [weaveworks/eksctl#2925]
Hi,

Is it possible to specify imageGCHighThresholdPercent & imageGCLowThresholdPercent values in the eksctl yaml file?

**Comment by Callisto13** [comment]
Hey @adnan-kamili, thanks for opening this feature request. Ideally this could be implemented in a way that would allow users to pass arbitrary args to the kubelet, rather than by specific flags (that could get out of hand the more we add).

Feel free to submit a PR if you would like to pick this up yourself!

**Comment by Callisto13** [comment]
Closing this as I realise it is already possible to set both these things in the `kubeletExtraConfig ` section of the config file:

```
# other config

nodeGroups:
  - name: ng1
    kubeletExtraConfig:
      imageGCHighThresholdPercent: ...
      imageGCLowThresholdPercent: ...
    ...
```
