### ISSUE TITLE
Unencrypted disk when using bottlerocket and `volumeEncrypted: true`

### ISSUE THREAD

**Issue by aclevername** [weaveworks/eksctl#2945]
**What happened?**
If I create a nodegroup as such:
```
nodeGroups:
- name: ng-kms-bottlerocket
  instanceType: m5.xlarge
  amiFamily: Bottlerocket
  desiredCapacity: 1
  volumeSize: 100
  volumeType: gp2
  volumeEncrypted: true
```

and look at the console afterwards, I see that only one of the disks in encrypted
![Screenshot 2020-12-15 at 09 25 54](https://user-images.githubusercontent.com/19669095/102196244-89fe1700-3eb7-11eb-9f79-233eff77114a.png)

**What you expected to happen?**
Both disks to be encrypted

**How to reproduce it?**
`eksctl create cluster -f cluster.yaml`

```
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: jk-kms
  region: us-west-2

nodeGroups:
- name: ng-kms-bottlerocket
  instanceType: m5.xlarge
  amiFamily: Bottlerocket
  desiredCapacity: 1
  volumeSize: 100
  volumeType: gp2
  volumeEncrypted: true
```
**Versions**
Please paste in the output of these commands:
```
$ eksctl version
   0.34.0
$ kubectl version
   v1.19.1
```
