### ISSUE TITLE
YAML parsing: anchor handling incorrect?: "key already set in map"

### ISSUE THREAD

**Issue by jcfj** [weaveworks/eksctl#2956]
**What happened?**
Parsing the following nodegroup specification:
```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-mic-test
  region: ap-northeast-1

nodeGroups:
  - &node-shared
    name: ng-1
    instanceType: t3.medium
    desiredCapacity: 1
  - <<: *node-shared
    name: ng-2
```

yields the error

```
Error: loading config file "ngfoo.yaml": error converting YAML to JSON: yaml: unmarshal errors:
  line 10: key "name" already set in map
```

**What you expected to happen?**
File is parsed as if it were
```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-mic-test
  region: ap-northeast-1
nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 1
  - name: ng-2
    instanceType: t3.medium
    desiredCapacity: 1
```
(which is the output of `yq --yaml-output .`)

**How to reproduce it?**
Ehm. `eksctl create nodegroup  -f ngfoo.yaml` No existing cluster required.

**Anything else we need to know?**
I know nothing. Specifically, I don't know the best place to report this, but I guess this is a bug(?) in your yaml parsing library?

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
0.31.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"archive", BuildDate:"2020-11-25T13:19:56Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

```
