### ISSUE TITLE
Updating control plane version when not specified

### ISSUE THREAD

**Issue by tahirali-endurance** [weaveworks/eksctl#2970]
**What happened?**
Updating the control plan version when not asked. The update stucks and does not complete.

**What you expected to happen?**
Control plane version is not upgraded when not asked.

**How to reproduce it?**
```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster-qa-rel
  region: us-east-1

vpc:
  subnets:
    private:
      az1 : {id: subnet-1}
      az2 : {id: subnet-2}

    public:
      az3 : {id: subnet-3}
      az4 : {id: subnet-4}

managedNodeGroups:
  - name: ng-v4
    instanceType: t3.medium
    desiredCapacity: 4
    privateNetworking: true

iam:
  withOIDC: true

cloudWatch:
  clusterLogging:
```

```bash
eksctl update cluster -f /tmp/cluster285653276.yml --approve
```

**Anything else we need to know?**
This is the output where it stucks 

```bash
eksctl update cluster -f /tmp/cluster285653276.yml --approve
[!]  This command is to be deprecated. Please use 'eksctl upgrade cluster' instead
[ℹ]  eksctl version 0.34.0
[ℹ]  using region us-east-1
[!]  NOTE: cluster VPC (subnets, routing & NAT Gateway) configuration changes are not yet implemented
[ℹ]  will upgrade cluster "eks-cluster-qa-rel" control plane from current version "1.17" to "1.18"
```bash

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
0.34.0
$ kubectl version
v1.20.1
```

**Logs**
Using existing cluster eks-cluster-qa-rel
eksctl update cluster -f /tmp/cluster285653276.yml --approve
[!]  This command is to be deprecated. Please use 'eksctl upgrade cluster' instead
[ℹ]  eksctl version 0.34.0
[ℹ]  using region us-east-1
[!]  NOTE: cluster VPC (subnets, routing & NAT Gateway) configuration changes are not yet implemented
[ℹ]  will upgrade cluster "eks-cluster-qa-rel" control plane from current version "1.17" to "1.18"
