### ISSUE TITLE
make withAddonPolicies reusable

### ISSUE THREAD

**Issue by todd-dsm** [weaveworks/eksctl#2981]
This is an RFE (Request For Enhancement): individual `withAddonPolicies` should be reusable; example: 

I've added ExternalDNS to a cluster with:
```yaml
...
iam:
      withAddonPolicies:
        externalDNS: true
...
```

At this point `eksctl` has authorized the nodes. Now the [xdns docs] require the deployment to be configured witth the ARN.
```yaml
...
  template:
    metadata:
      labels:
        app: external-dns
      # If you're using kiam or kube2iam, specify the following annotation.
      # Otherwise, you may safely omit it.
      annotations:
        iam.amazonaws.com/role: arn:aws:iam::ACCOUNT-ID:role/IAM-SERVICE-ROLE-NAME
...
```

At this point there are only few paths open:
1. use the ARN (created by `eksctl`) for the node: seems a bit much as it is attached to so many other inline policies.
2. document how to use/take advantage of step 1. It's [not apparent] to me but maybe I'm missing something.
3. terraform a new policy and use that ARN. Easy enough but there is the possibility of an unnecessary ARN mismatch at some point.
4. make each policy/role independent and reusable.

reusable legos always seems the best option so I vote for 4.

**Why do you want this feature?**
To make it easier and more secure to configure supporting services like ExternalDNS. 

[xdns docs]:https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/aws.md#deploy-externaldns
[not apparent]:https://eksctl.io/usage/iam-policies/
