### ISSUE TITLE
Cloudwatch not deployed on GPU nodes

### ISSUE THREAD

**Issue by Jboulery** [weaveworks/eksctl#2982]
Hello, thanks for your work first of all.

I was trying to deploy CloudWatch in my EKS cluster and basically followed what's on [the quick start guide](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-setup-EKS-quickstart.html).

Result is that I do get some metrics in CloudWatch, but all resources related to nodes which have a GPU are missing. 

After a quick check, I found out that cloudwatch daemonset hasn't been deployed on these nodes.
```shell
$ kubectl get nodes
# NAME                                            STATUS   ROLES    AGE   VERSION
# <ip1>.<region>.compute.internal   Ready    <none>   28d   v1.17.12-eks-7684af  --> CPU only, ng-CPU
# <ip2>.<region>.compute.internal   Ready    <none>   17h   v1.17.12-eks-7684af  --> CPU only, ng-CPU
# <ip3>.<region>.compute.internal    Ready    <none>   18h   v1.17.12-eks-7684af  --> GPU capability, ng-GPU-1
# <ip4>.<region>.compute.internal    Ready    <none>   18h   v1.17.12-eks-7684af  --> GPU capability, ng-GPU-2
```

```shell
$ kubectl get pods -n amazon-cloudwatch -o wide
# NAME                       READY   STATUS    RESTARTS   AGE   IP                NODE                                            NOMINATED NODE   READINESS GATES
# cloudwatch-agent-9qb8x     1/1     Running   0          17h   <ip>   <ip1>.<region>.compute.internal   <none>           <none>
# cloudwatch-agent-nsq5b     1/1     Running   0          21h   <ip>    <ip2>.<region>.compute.internal   <none>           <none>
# fluentd-cloudwatch-jpp7k   1/1     Running   0          17h   <ip>    <ip1>.<region>.compute.internal   <none>           <none>
# fluentd-cloudwatch-kfq5k   1/1     Running   0          21h   <ip>    <ip2>.<region>.compute.internal   <none>           <none>
```

Here is the configuration I'm using for the node groups. My question is:
Could it be that taint is preventing the daemonset to be deployed on these nodes? Otherwise any idea why it's not deployed on these specific nodes?

```yaml
- name: ng-GPU-<1 or 2>  # Only the instance distribution changes between the two GPU node groups...
    # instance distribution settings...
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      withAddonPolicies:
        autoScaler: true
        ebs: true
        albIngress: true
        cloudWatch: true
    tags:
      k8s.io/cluster-autoscaler/node-template/taint/dedicated: nvidia.com/gpu=true
      k8s.io/cluster-autoscaler/node-template/label/nvidia.com/gpu: 'true'
      k8s.io/cluster-autoscaler/enabled: 'true'
    labels:
      nvidia.com/gpu: 'true'
      k8s.amazonaws.com/accelerator: nvidia-tesla
    privateNetworking: false
    taints:
      nvidia.com/gpu: "true:NoSchedule"
  
- name: ng-CPU
    # instance distribution settings...
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      withAddonPolicies:
        autoScaler: true
        ebs: true
        albIngress: true
        cloudWatch: true
    tags:
      k8s.io/cluster-autoscaler/enabled: 'true'
    privateNetworking: true
```

Thanks for your help!

**Comment by aclevername** [comment]
Hey @Jboulery, thanks for opening the issue!

I think you are correct that the taints are causing this problem, you need to add a toleration to the daemonsets to allow `fluentd` and `cloudwatch` to schedule onto the tainted nodes. The [daemonset docs have an example of adding a toleration](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/). Hope that helps 😄

**Comment by Jboulery** [comment]
> Hey @Jboulery, thanks for opening the issue!
> 
> I think you are correct that the taints are causing this problem, you need to add a toleration to the daemonsets to allow `fluentd` and `cloudwatch` to schedule onto the tainted nodes. The [daemonset docs have an example of adding a toleration](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/). Hope that helps smile

That was it indeed :) Thanks for the link, I added:
```yaml
tolerations:
    - key: "nvidia.com/gpu"
      operator: "Exists"
      effect: "NoSchedule"
```
to the two daemonsets that are parts of the config file and it worked.
