### ISSUE TITLE
Can't see workloads or nodes and receive an error in the AWS Management Console

### ISSUE THREAD

**Issue by mbevc1** [weaveworks/eksctl#2983]
**What happened?**
When deploying a default cluster it doesn't provide access to workloads insight in AWS mgmt console.

**What you expected to happen?**
Using IAM user which deployed cluster, I should be able to see workload in the console.

**How to reproduce it?**
```eksctl create cluster -f x.yaml```
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: xx
  region: eu-west-1
  tags:
    Managed_by: 'eksctl'
  version: '1.18'

iam:
  withOIDC: true

managedNodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 3
    minSize: 2
    maxSize: 3
    availabilityZones:
      - 'eu-west-1a'
      - 'eu-west-1b'
      - 'eu-west-1c'
    labels:
      role: 'xx'
    privateNetworking: true
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
    volumeSize: 20
```

**Versions**
Please paste in the output of these commands:
```
$ eksctl version = 0.35.0
$ kubectl version = 1.20.1
```
