### ISSUE TITLE
EKS Fargate with VPC DNS Hostnames disabled not working using eksctl

### ISSUE THREAD

**Issue by damerakd** [weaveworks/eksctl#2984]
**What happened?**
Hello, trying to create a fargate cluster using eksctl where VPC has DNS Hostnames set to Disabled

**What you expected to happen?**
Cluster to be successfully created

**How to reproduce it?**

```yaml
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: seamless-backend-prod
  region: eu-west-1
  version: "1.18"

iam:  
  withOIDC: true

vpc:
  id: "vpc-0660464f0bc129d0d"
  cidr: "10.35.0.0/22"
  subnets:
    # must provide 'private' and/or 'public' subnets by availibility zone as shown
    public:
      eu-west-1a:
        id: "subnet-0cbcfbd7ace5e43b3"
      eu-west-1b:
        id: "subnet-0c8d6457af3d4918d"
    private:
      eu-west-1a:
        id: "subnet-0b8fb6e05b50f9e11"
      eu-west-1b:
        id: "subnet-034a66e87e6168489"
    privateAccess: true
    publicAccess: true
fargateProfiles:
  - name: fp-default
    selectors:
      - namespace: default
      - namespace: kube-system
      - namespace: kubernetes-dashboard
    subnets: 
      - subnet-0b8fb6e05b50f9e11
      - subnet-034a66e87e6168489
```
----

**Versions**
Please paste in the output of these commands:
```
$ eksctl version - 0.34.0
$ kubectl version - 1.19.3
```

```
[ℹ]  eksctl version 0.34.0
[ℹ]  using region eu-west-1
[✔]  using existing VPC (vpc-0660464f0bc129d0d✠) and subnets (private:[subnet-0b8fb6e05b50f9e11 subnet-034a66e87e6168489] public:[subnet-0cbcfbd7ace5e43b3 subnet-0c8d6457af3d4918d])
[!]  custom VPC/subnets will be used; if resulting cluster doesn't function as expected, make sure to review the configuration of VPC/subnets
[ℹ]  using Kubernetes version 1.18
[ℹ]  creating EKS cluster "seamless-backend-prod-3" in "eu-west-1" region with Fargate profile
[ℹ]  will create a CloudFormation stack for cluster itself and 0 nodegroup stack(s)
[ℹ]  will create a CloudFormation stack for cluster itself and 0 managed nodegroup stack(s)
[ℹ]  if you encounter any issues, check CloudFormation console or try 'eksctl utils describe-stacks --region=eu-west-1 --cluster=seamless-backend-prod-3'
[ℹ]  CloudWatch logging will not be enabled for cluster "seamless-backend-prod-3" in "eu-west-1"
[ℹ]  you can enable it with 'eksctl utils update-cluster-logging --enable-types={SPECIFY-YOUR-LOG-TYPES-HERE (e.g. all)} --region=eu-west-1 --cluster=seamless-backend-prod-3'
[ℹ]  Kubernetes API endpoint access will use provided values {publicAccess=true, privateAccess=true} for cluster "seamless-backend-prod-3" in "eu-west-1"
[ℹ]  2 sequential tasks: { create cluster control plane "seamless-backend-prod-3", 2 sequential sub-tasks: { 5 sequential sub-tasks: { update cluster VPC endpoint access configuration, create fargate profiles, associate IAM OIDC provider, 10 parallel sub-tasks: { 2 sequential sub-tasks: { create IAM role for serviceaccount "default/tenancy-svc", create serviceaccount "default/tenancy-svc" }, 2 sequential sub-tasks: { create IAM role for serviceaccount "default/users-svc", create serviceaccount "default/users-svc" }, 2 sequential sub-tasks: { create IAM role for serviceaccount "default/documents-svc", create serviceaccount "default/documents-svc" }, 2 sequential sub-tasks: { create IAM role for serviceaccount "default/configuration-svc", create serviceaccount "default/configuration-svc" }, 2 sequential sub-tasks: { create IAM role for serviceaccount "default/pricing-svc", create serviceaccount "default/pricing-svc" }, 2 sequential sub-tasks: { create IAM role for serviceaccount "default/sales-svc", create serviceaccount "default/sales-svc" }, 2 sequential sub-tasks: { create IAM role for serviceaccount "default/underwriting-svc", create serviceaccount "default/underwriting-svc" }, 2 sequential sub-tasks: { create IAM role for serviceaccount "default/finance-svc", create serviceaccount "default/finance-svc" }, 2 sequential sub-tasks: { create IAM role for serviceaccount "default/compliance-svc", create serviceaccount "default/compliance-svc" }, 2 sequential sub-tasks: { create IAM role for serviceaccount "kube-system/aws-node", create serviceaccount "kube-system/aws-node" } }, restart daemonset "kube-system/aws-node" }, create addons } }
[ℹ]  building cluster stack "eksctl-seamless-backend-prod-3-cluster"
[ℹ]  deploying stack "eksctl-seamless-backend-prod-3-cluster"
[ℹ]  creating Fargate profile "fp-default" on EKS cluster "seamless-backend-prod-3"
[ℹ]  created Fargate profile "fp-default" on EKS cluster "seamless-backend-prod-3"
[ℹ]  "coredns" is now schedulable onto Fargate
[ℹ]  "coredns" is now scheduled onto Fargate
[ℹ]  "coredns" is now scheduled onto Fargate
[ℹ]  "coredns" is now scheduled onto Fargate
[!]  1 error(s) occurred and cluster hasn't been created properly, you may wish to check CloudFormation console
[ℹ]  to cleanup resources, run 'eksctl delete cluster --region=eu-west-1 --name=seamless-backend-prod-3'
[✖]  failed to schedule core-dns on fargate: Unauthorized
Error: failed to create cluster "seamless-backend-prod-3"
```

Error looks to be coming from [1], which if we follow will call the methods `IsScheduledOnFargate()` --> `arePodsScheduledOnFargate()` --> `isRunningOnFargate()` from the `coredns.go` file [2]

Here [3] from the line:
`strings.HasPrefix(pod.Spec.NodeName, "fargate-ip-")`

I believe it is checking whether node has the prefix `fargate-ip-`

However when VPC DNS hostnames is not enabled, we get the node name as `fargate-<Internal_IP>`

So I think the line in here [3] needs to be modified something like `strings.HasPrefix(pod.Spec.NodeName, "fargate-")` which will work for all the scenarios.

Please also note that this is achievable by creating Fargate profile using Management console and not using eksctl.

References
[1] https://github.com/weaveworks/eksctl/blob/8b129a6e27572e18aa3d6bd98180217387bc93a5/pkg/eks/fargate.go#L46
[2] https://github.com/weaveworks/eksctl/blob/fe1cec814ab7c0101bb1ba11a90f88bc82a5ae10/pkg/fargate/coredns/coredns.go
[3]https://github.com/weaveworks/eksctl/blob/fe1cec814ab7c0101bb1ba11a90f88bc82a5ae10/pkg/fargate/coredns/coredns.go#L103
