### ISSUE TITLE
How to upgrade managed nodegroups with custom AMIs?

### ISSUE THREAD

**Issue by dbluxo** [weaveworks/eksctl#3006]
Hi,

I have created an EKS cluster with managed nodegroups and custom AMIs via a config file.
If I want to upgrade the managed nodegroups now to a new custom AMI, how would I do that?

Example, the cluster was created as follows (simplified):

```
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-15
  region: us-west-2

managedNodeGroups:
  - name: custom-ami-ng-1
    ami: ami-123
    overrideBootstrapCommand: |
      /etc/eks/bootstrap.sh cluster-15
  - name: custom-ami-ng-2
    ami: ami-123
    overrideBootstrapCommand: |
      /etc/eks/bootstrap.sh cluster-15
```

Now I have an updated configuration (with new AMI IDs):

```
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-15
  region: us-west-2

managedNodeGroups:
  - name: custom-ami-ng-1
    ami: ami-abc # NEW
    overrideBootstrapCommand: |
      /etc/eks/bootstrap.sh cluster-15
  - name: custom-ami-ng-2
    ami: ami-abc # NEW
    overrideBootstrapCommand: |
      /etc/eks/bootstrap.sh cluster-15
```

Intuitively I would just like to trigger the upgrade to the new AMI by following: `eksctl upgrade nodegroup -f <config-file>`  Unfortunately not possible.

Also an `eksctl upgrade nodegroup --cluster cluster-15 --name custom-ami-ng-1 -f <config-file>` does not upgrade the nodegroup to the new AMI.

How is the handling with custom AMIs for managed nodegroups intended? Do I really have to create new managed nodegroups with the new AMI ID and delete the old ones? Or is there a nicer way? 😃
