### ISSUE TITLE
How to correctly add GPU node group to existing Cluster

### ISSUE THREAD

**Issue by ajinkya933** [weaveworks/eksctl#3009]
**What help do you need?**
Describe the type of help you need. 
Please include your config, removing any sensitive information, or exact commands you're using.

Hello,

I have a cluster on AWS with autoscaler enabled, under this cluster I have one nodegroup the following yaml file summarizes my cluster info:

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: mycluster
  region: us-east-2
nodeGroups:
  - name: my-nodegroup
    minSize: 1
    maxSize: 5
    iam:
      withAddonPolicies:
        autoScaler: true
    labels: { role: workers }
    instanceType: <instance_name>
    desiredCapacity: 2
    volumeSize: 10
```

The instance That I use for above nodegroup is a CPU instance. I want to add a GPU nodegroup to above cluster. The specs of gpu nodegroups are as follows:

```
  - name: rnd-GPU-nodegroup
    minSize: 0
    maxSize: 1
    iam:
      withAddonPolicies:
        autoScaler: true
    labels: { role: workers }
    instanceType: p2.xlarge
    desiredCapacity: 1
    volumeSize: 20
```

**How do I update my existing cluster but with this new GPU nodegroup ?**

I tried ` eksctl create nodegroup -f rnd_GPU.yaml` where GPU.yaml is the above GPU yaml file but I didnt see any nodes spinning up when I started a pod on GPU node. What is a correct way of doing this ?

**Comment by arjun921** [comment]
If `eksctl get nodegroup` doesn't show your new GPU nodegroup, changes didn't reflect. 

Try this -- 

Add the new nodegroup to the file originally used for creating the cluster. 
and try runing this command 
```
eksctl create nodegroup --config-file=<path> --include='rnd-GPU-nodegroup' --exclude='my-nodegroup'
eksctl get nodegroup # Ideally should show your new nodegroup
```

After that works, if you're not using this already, you'll need this
https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#example-use-cases

To run a workload specifically on the GPU node, you'll need to use a label from the nodes, which can be found from here:
```
kubectl describe node <mynew-gpu-node-name>
```

Add the relevant tolerations and your pod should get scheduled to the GPU nodegroup.

**Comment by DanielAmmar** [comment]
i guess you're missing the tags to discover your node by k8s
try adding this to your yaml file (replace CLUSTER_NAME) :
```
tags:
    k8s.io/cluster-autoscaler/CLUSTER_NAME: "owned"
    k8s.io/cluster-autoscaler/enabled: "true"
    k8s.amazonaws.com/accelerator: "nvidia-tesla-k80"
```
I'll also recommend to add the 'accelerator' tag to manually advertise the GPU resource to the cluster

**Comment by ajinkya933** [comment]
I am able to see the new node group added as follows:

$ eksctl get nodegroup --cluster mygpu
```

CLUSTER	NODEGROUP		STATUS		CREATED			MIN SIZE	MAX SIZE	DESIRED CAPACITY	INSTANCE TYPE	IMAGE ID		ASG NAME
mygpu	rnd-GPU-nodegroup-2	CREATE_COMPLETE	2021-01-07T15:20:00Z	0		2		1			p2.xlarge	ami-07e8aa30939269532	eksctl-mygpu-nodegroup-rnd-GPU-nodegroup-2-NodeGroup-1NC6B8LTCHHOH
mygpu	rnd-nodegroup-2		CREATE_COMPLETE	2021-01-07T15:20:01Z	2		4		2			r5n.xlarge	ami-0516b36ba0c479357	eksctl-mygpu-nodegroup-rnd-nodegroup-2-NodeGroup-1AVDICB4GBUUP

```

However, I get error for

```
$ kubectl describe node rnd-GPU-nodegroup-2
Error from server (NotFound): nodes "rnd-GPU-nodegroup-2" not found

```

My question is right after cluster and before Kubeflow installation, what steps should I take to make GPU scale from 0 ?

**Comment by arjun921** [comment]
These are nodegroups

Nodes ∈ Nodegroups

To see a node that was added you'll need to run this:
```
kubectl get nodes
kubetl describe node ip-241-21...
```

**Comment by arjun921** [comment]
The age should help you identify newly added nodes from a ndoegroup, also labels found in described nodes should help identifying which nodegroup it belongs to.

**Comment by ajinkya933** [comment]
Following up:

Heres my cluster setip.yaml file:

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: mygpu
  region: us-east-2
nodeGroups:
  - name: rnd-nodegroup-2
    minSize: 2
    maxSize: 4
    tags:
      k8s.io/cluster-autoscaler/mygpu: "owned"
      k8s.io/cluster-autoscaler/enabled: "true"
    iam:
      withAddonPolicies:
        autoScaler: true
    labels: { role: workers }
    instanceType: r5n.xlarge
    desiredCapacity: 2
    volumeSize: 80
  - name: rnd-GPU-nodegroup-2
    minSize: 0
    maxSize: 2
    tags:
      k8s.io/cluster-autoscaler/mygpu: "owned"
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.amazonaws.com/accelerator: "nvidia-tesla-k80"
    iam:
      withAddonPolicies:
        autoScaler: true
    labels: { role: workers }
    instanceType: p2.xlarge
    desiredCapacity: 1
    volumeSize: 20
```
I created a cluster from this yaml file using this command : `eksctl create cluster -f rnd_combo.yaml`. After that I enabled autoscaler on this cluster:

```
# install cluster autoscaler
kubectl apply -f https://raw.githubusercontent.com/kubernetes/autoscaler/master/cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml# Edit deployment 
kubectl -n kube-system edit deployment.apps/cluster-autoscaler# Update autoscaler deployment flags
 - --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/kubeflow-us-east-1
 - --balance-similar-node-groups 
 - --skip-nodes-with-system-pods=false

```


I deployed kubeflow using official docs: https://www.kubeflow.org/docs/aws/deploy/install-kubeflow/
Version of Kubeflow : 1.2

So, even after doing this my GPU is not being scaled up from zero, 
My CPU works normally though

GPU not scaling visual:

![gpu](https://user-images.githubusercontent.com/17012391/104156816-e0f00100-540f-11eb-8304-767125db0ab1.png)

Error I get is :
```
1 insufficient cpu, 2 insufficient nvidia.com/gpu
```
Any pointers on how to fix it ? 
@arjun921  @DanielAmmar

**Comment by arjun921** [comment]
Check the logs of your cluster autoscaler or events in AWS console for ec2 ASG 

Highly likely the node you're looking for in the region you're requesting for doesn't have any nodes available.

**Comment by arjun921** [comment]
Also you might want to consider this flag
https://github.com/weaveworks/eksctl/blob/master/examples/23-kubeflow-spot-instance.yaml#L133

This helps prevent AZ mismatch if for volumes while they're created and if you'd like to reattach to the same volume when the notebook is killed and spun up again.

**Comment by ajinkya933** [comment]
I guess the GPU is not working in my specified region:

I tried to install GPU only nodegroup using the below yaml file:
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: rnd-gpu
  region: us-east-2
nodeGroups:
  - name: rnd-GPU-nodegroup-2
    minSize: 1
    maxSize: 4
    tags:
      k8s.io/cluster-autoscaler/mygpu: "owned"
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.amazonaws.com/accelerator: "nvidia-tesla-k80"
    iam:
      withAddonPolicies:
        autoScaler: true
    labels: { role: workers }
    instanceType: p2.xlarge
    desiredCapacity: 1
    volumeSize: 20
 
 ```
 But I get error during cluster creation itself:


```

[✖]  unexpected status "CREATE_IN_PROGRESS" while waiting for CloudFormation stack "eksctl-rnd-gpu-nodegroup-rnd-GPU-nodegroup-2"
[ℹ]  fetching stack events in attempt to troubleshoot the root cause of the failure
[!]  1 error(s) occurred and cluster hasn't been created properly, you may wish to check CloudFormation console
[ℹ]  to cleanup resources, run 'eksctl delete cluster --region=us-east-2 --name=rnd-gpu'
[✖]  waiting for CloudFormation stack "eksctl-rnd-gpu-nodegroup-rnd-GPU-nodegroup-2": RequestCanceled: waiter context canceled
caused by: context deadline exceeded

```

Its strange because AWS mentions us-east-2 supports p2.xlarge instance. Any recommendation on which GPU will surely work in us-east-2 ?

**Comment by michaelbeaumont** [comment]
@ajinkya933 in that specific case, it looks like the create timed out. Did the nodes joined the cluster in the end?

**Comment by ajinkya933** [comment]
@michaelbeaumont The nodes were in pending state for very long time. I had to delete the cluster.

**Comment by arjun921** [comment]
@ajinkya933 try p3.2xlarge
P2 is an older gen and might not be as readily available as current gen.

Px where x is the generation
Higher is newer

**Comment by ajinkya933** [comment]
For p3.2xlarge yaml
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: rnd-gpu
  region: us-east-2
nodeGroups:
  - name: rnd-GPU-nodegroup-2
    minSize: 1
    maxSize: 4
    tags:
      k8s.io/cluster-autoscaler/mygpu: "owned"
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.amazonaws.com/accelerator: "nvidia-tesla-k80"
    iam:
      withAddonPolicies:
        autoScaler: true
    labels: { role: workers }
    instanceType: p3.2xlarge
    desiredCapacity: 1
    volumeSize: 20
 
```

 I get error:

```
[✖]  unexpected status "CREATE_IN_PROGRESS" while waiting for CloudFormation stack "eksctl-rnd-gpu-nodegroup-rnd-GPU-nodegroup-2"
[ℹ]  fetching stack events in attempt to troubleshoot the root cause of the failure
[!]  1 error(s) occurred and cluster hasn't been created properly, you may wish to check CloudFormation console
[ℹ]  to cleanup resources, run 'eksctl delete cluster --region=us-east-2 --name=rnd-gpu'
[✖]  waiting for CloudFormation stack "eksctl-rnd-gpu-nodegroup-rnd-GPU-nodegroup-2": RequestCanceled: waiter context canceled
caused by: context deadline exceeded

```
