### ISSUE TITLE
Creating Managed NodeGroup creates 2 LaunchTemplates strangely configured

### ISSUE THREAD

**Issue by bass4** [weaveworks/eksctl#3021]
i am creating a managed nodegroup but i end up with one auto-scaling group and 2 LaunchTemplates. The 'working' template attached to the auto-scaling group is not seen properly by EKS (at least in the console) and the 'incomplete' template is seen in the console as the 'official' managed nodegroup.
Template Below

```shell
$ eksctl --profile production create nodegroup -f on-20201231
```

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: sf-staging-cluster
  region: us-east-1

iam: 
  serviceRolePermissionsBoundary: arn:aws:iam::<account>:policy/CompanyBoundary
  serviceRoleARN: arn:aws:iam::<account>:role/EKSCTL-Service-Role

managedNodeGroups:
- name: on-20201231
  minSize: 2
  maxSize: 6
  desiredCapacity: 2
  privateNetworking: true
  iam:
    instanceRoleARN: arn:aws:iam::<account>:role/my-node-role
  instanceTypes: ["r5.xlarge","r4.xlarge"]
  spot: true
```
