### ISSUE TITLE
Support for p4d instance type in eksctl

### ISSUE THREAD

**Issue by g-karthik** [weaveworks/eksctl#3026]
I'd like support for the new p4d instance type launched at AWS re:invent a month ago.

**Why do you want this feature?**
I have an EKS-based setup to train large deep learning models (in which I use p3dn nodes) and I want to be able to easily switch to p4d.

**What feature/behavior/change do you want?**

I'd like to be able to specify in my nodegroup YAML, something like the following:
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: <clustername>
  region: us-east-1

nodeGroups:
  - name: p4d
    instanceType: p4d.24xlarge
    desiredCapacity: 8
    amiFamily: AmazonLinux2
    availabilityZones: ["us-east-1a"]
    volumeSize: 500
    volumeType: gp2

```
