### ISSUE TITLE
Support for Bottlerocket as a custom AMI in managed node groups

### ISSUE THREAD

**Issue by mikestef9** [weaveworks/eksctl#3033]
**Why do you want this feature?**
Use Bottlerocket, the AWS container optimized system, as a custom AMI with managed node groups

**What feature/behavior/change do you want?**
I would like to create a Bottlerocket node group through managed node groups using eksctl. Currently, this does not work because eksctl injects MIME metadata into the user data. MIME is not required when using a custom AMI with managed node groups. ekctl should just pass the `overrideBootstrapCommand` field value as is to managed node groups API

I would expect the below config to work with this update

```
managedNodeGroups:
  - name: x86-bottlerocket-mng
    ami: ami-0acfc3fffaaa4e015
    instanceType: m5.large
    minSize: 1
    desiredCapacity: 2
    maxSize: 3
    privateNetworking: true
    disableIMDSv1: true
    volumeSize: 50
    labels: { role: x86-bottlerocket-mng }
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
    overrideBootstrapCommand: |
      [settings.kubernetes]
      api-server = "https://redacted.gr7.us-east-1.eks.amazonaws.com"
      cluster-certificate = "redacted"
      cluster-name = "testing-cluster"
```
