### ISSUE TITLE
Create an IAM Service Account role without creating/annotating the service account

### ISSUE THREAD

**Issue by Legion2** [weaveworks/eksctl#3042]
**What happened?**
I used the IAM role name feature to give the iam role generated by eksctl a predictable name. Then I used the IAM role name in a GitOps setup and attached it with the `eks.amazonaws.com/role-arn` annotation to a service account which is provided by a helm chart.
The service account is generated be the helm chart and only the annotation and the IAM role is provided by me. I don't know the name of the service account generated by the helm chart.

I don't know if this is a bug or feature request but from the description of the PR (#2863) that introduced the feature:
>  For instance, when following a git-ops workflow it might be necessary to include the serviceaccount annotations for the IAM role ARNs in the manifest repo.

I thought that this is the intended use of the IAM role name feature.

**What you expected to happen?**
I created a IAM role using the following cluster config.
The config generates two things: the IAM role and a Service Account.
I don't need the service account, I only want to use the IAM role and attach it to the service account generated by the helm chart.
```yaml
...
iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: some-name
        namespace: default
      roleName: role-for-helm-chart
      attachPolicy: ...
```

The helm chart is managed the `helm.fluxcd.io/v1` `HelmRelease` crd.
In the values section I added the following:
```yaml
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::<redacted>:role/role-for-helm-chart
```

**How to reproduce it?**
1. Create a IAM role with a defined name using the eksctl
2. Attach the `eks.amazonaws.com/role-arn` annotation to a service account different than the one created by eksctl
3. see error `WebIdentityErr: failed to retrieve credentials caused by: AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity` in the application that uses the service account

**Anything else we need to know?**
https://github.com/weaveworks/eksctl/pull/2863#issuecomment-755526414

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
0.36.0-rc.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
