### ISSUE TITLE
 withAddonPolicies albIngress not support GCR ZHY/BJS region

### ISSUE THREAD

**Issue by stevensu1977** [weaveworks/eksctl#3062]
**What were you trying to accomplish?**
I found `statement.go`, only return AWS global partition,  not include GCR ZHY/BJS partition "arn:aws-cn",  I already work for this issue, I can help fix it .

**What happened?**
`eksctl create cluster -f sandbox-cluster-config.yaml` get error :

`Partition \"aws\" is not valid for resource \"arn:aws:ec2:*:*:security-group/*\`

**How to reproduce it?**
you can use my cluster config file ,create eks cluster on AWS GCR Region

sandbox-cluster-config.yaml:

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: SANDBOX-KUBEFLOW-EKS
  region: cn-northwest-1
  version: "1.18"


nodeGroups:
  - name: eks-product-cpu-ng-1
    instanceType: m5.2xlarge
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 50
    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true
        efs: true
        cloudWatch: true
        albIngress: true
```

**Logs**
```
[✖]  AWS::IAM::Policy/PolicyAutoScaling: CREATE_FAILED – "Resource creation cancelled"
[✖]  AWS::IAM::Policy/PolicyEFSEC2: CREATE_FAILED – "Resource creation cancelled"
[✖]  AWS::IAM::Policy/PolicyEBS: CREATE_FAILED – "Resource creation cancelled"
[✖]  AWS::IAM::Policy/PolicyEFS: CREATE_FAILED – "Resource creation cancelled"
[✖]  AWS::IAM::InstanceProfile/NodeInstanceProfile: CREATE_FAILED – "Resource creation cancelled"
[✖]  AWS::IAM::Policy/PolicyAWSLoadBalancerController: CREATE_FAILED – "Partition \"aws\" is not valid for resource \"arn:aws:ec2:*:*:security-group/*\". (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID: eb4ec373-144c-4520-a076-71137c9bab5d; Proxy: null)"
```

**Anything else we need to know?**
mac os
**Versions**
eksctl version
`0.36.0-rc.0`

Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:21:03Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
