### ISSUE TITLE
Node groups not instantiating with `preBootstrapCommands`

### ISSUE THREAD

**Issue by cajual** [weaveworks/eksctl#3065]
eksctl version 0.35
k8s version 1.18.x
ca version 1.18.x

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
nodeGroups:
  - name: my-ng
    <instance details>
    preBootstrapCommands:
      - "mkdir -p /mount/path"
```

The node is created fine, the policies are attached, the capacity is appropriate and everything is as expected in the cf stack, but none of my nodes have the directory `/mount/path`

invariably this causes issues with my new pods since they get stuck in the `Init:0/1` stage with the following error:
`MountVolume.SetUp failed for volume "my-hostpath-1" : hostPath type check failed: /mount/path is not a directory`

Not sure what I am missing and resources about this particular key are scarce.
