### ISSUE TITLE
invalid value in privateCluster.additionalEndpointServices: unsupported endpoint service "log"

### ISSUE THREAD

**Issue by marutiprasad** [weaveworks/eksctl#3124]
When creating a fully private cluster with additional end points as mentioned in the document @ https://eksctl.io/usage/eks-private-cluster/

I am getting the following message: Error: invalid value in privateCluster.additionalEndpointServices: unsupported endpoint service "log"

Here is the sample config:

```
privateCluster:
  enabled: true
  additionalEndpointServices:
  - "autoscaling"
  - "log" 
```

```
$ eksctl version :  0.36.0
$ kubectl version : Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
```
