### ISSUE TITLE
Cannot configure Throughput for managed nodegroup gp3 volumes

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/eksctl#3153]
**What were you trying to accomplish?**
Create a managed nodegroup with `volumeThroughput` set to `500`.

**What happened?**
The nodegroup was created, there were no errors, but the Throughput for the EBS volume is set to `125`.

**How to reproduce it?**

```yaml
... other config

managedNodeGroups:
  - name: my-ng
    instanceType: m5.xlarge
    desiredCapacity: 1
    volumeSize: 40
    volumeThroughput: 500
```

Then navigate to the console, and see that the volume attached to the node instance has Throughput set to 125, not 500.

**Versions**
```
$ eksctl version
0.37.0-rc
```
