### ISSUE TITLE
question on tagging subnets in ConfigFile during create cluster

### ISSUE THREAD

**Issue by sandan** [weaveworks/eksctl#3188]
Is it possible to tag subnets in eksctl when creating a cluster from a config file? I'd like to be able to tag my pre-existing private subnets to enable auto-discovery for elb. Something like:
```
vpc:
  id: "vpc-123abc"
  subnets:
    private:
      tags: "kubernetes.io/role/internal-elb=1"
      us-east-2b:
          id: "subnet-01"
      us-east-2a:
          id: "subnet-02"
```
The ClusterConfig above specifies adding the tag to both subnets. Is there a way to do this with other subcommands in eksctl if not `create cluster`?
