### ISSUE TITLE
upgrading cluster managed nodegroup results in error, showing version mismatch

### ISSUE THREAD

**Issue by brentley** [weaveworks/eksctl#3201]
**What were you trying to accomplish?**
I was running the command: 
```
eksctl upgrade nodegroup --name=nodegroup --cluster=eksworkshop-eksctl --kubernetes-version=1.18 --wait
```

**What happened?**
The upgrade failed. The relevant error appears to be:
```
[ℹ]  AWS::EKS::Nodegroup/ManagedNodeGroup: UPDATE_FAILED – "Requested Nodegroup release version 1.18.9-20210125 is invalid. Allowed release version is 1.18.9-20210127 (Service: AmazonEKS; Status Code: 400; Error Code: InvalidParameterException; Request ID: b7bc4ca6-a68c-4815-ae17-0c46ddc32099; Proxy: null)"
```

**How to reproduce it?**
- Begin by creating a 1.17 cluster, including a managed nodegroup (I was using us-west-2 if that matters)
- Upgrade the control plane
- upgrade the add-ons
- run the command above to upgrade the managed nodegroup
- 
If using a config file, include it here, removing any sensitive information!
```
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eksworkshop-eksctl
  region: us-west-2
  version: "1.17"

availabilityZones: ["us-west-2a", "us-west-2b", "us-west-2c"]

managedNodeGroups:
- name: nodegroup
  desiredCapacity: 3
  ssh:
    allow: true
    publicKeyName: eksworkshop

secretsEncryption:
  keyARN: arn:aws:kms:us-west-2:xxxxxxxxxxx:key/09b590a9-8502-47ad-8098-f9610858483c
```

**Logs**
https://gist.github.com/brentley/4cd71d2dadc81ffc29033fb724fac10c#file-cluster-nodegroup-upgrade-error-L19

**Anything else we need to know?**
I'm running this from a cloud9 instance that uses AmazonLinux2 and has an instance role attached. 

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
0.37.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.11-eks-cfdc40", GitCommit:"cfdc40d4c1b7d14eb60152107963ae41aa2e4804", GitTreeState:"clean", BuildDate:"2020-09-17T17:10:39Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
