### ISSUE TITLE
VPCEndpointS3: CREATE_FAILED – Private DNS can't be enabled because the service com.amazonaws.us-east-1.s3 does not provide a private DNS name

### ISSUE THREAD

**Issue by m1hanick** [weaveworks/eksctl#3214]
Hi,

Trying to create a new fully private EKS cluster with EKSCTL 0.32.0
Got the following error:
```
AWS::EC2::VPCEndpoint/VPCEndpointS3: CREATE_FAILED – "Private DNS can't be enabled because the service com.amazonaws.us-east-1.s3 does not provide a private DNS name. (Service: AmazonEC2; Status Code: 400; Error Code: InvalidParameter; Request ID: 1edf09f7-0572-46db-a6ba-9bac7dcabf18; Proxy: null)"
```

CloudFormation template contains this:
```    
"VPCEndpointS3": {
      "Type": "AWS::EC2::VPCEndpoint",
      "Properties": {
        "PrivateDnsEnabled": true,
        "SecurityGroupIds": [
          {
            "Ref": "ClusterSharedNodeSecurityGroup"
          }
        ],
        "ServiceName": "com.amazonaws.us-east-1.s3",
        "SubnetIds": [
          "subnet-xxxxxxxxxxxxx",
          "subnet-xxxxxxxxxxxxx",
          "subnet-xxxxxxxxxxxxx"
        ],
        "VpcEndpointType": "Interface",
        "VpcId": "vpc-xxxxxxxxxxxxxxx"
      }
    },
```

Firstly, it is surprising that it tries to create S3 endpoint with **VpcEndpointType** = '**Interface**', it was always  '**Gateway**' before.

As I've got, API call DescribeVpcEndpointServices returns two services for the S3

```{
    "ServiceDetails": [
        {
            "ServiceName": "com.amazonaws.us-east-1.s3",
            "ServiceId": "vpce-svc-0aa7c06513d4872d5",
            "ServiceType": [
                {
                    "ServiceType": "Gateway"
                }
            ],
            "AvailabilityZones": [
                "us-east-1a",
                "us-east-1b",
                "us-east-1c",
                "us-east-1d",
                "us-east-1e",
                "us-east-1f"
            ],
            "Owner": "amazon",
            "BaseEndpointDnsNames": [
                "s3.us-east-1.amazonaws.com"
            ],
            "VpcEndpointPolicySupported": true,
            "AcceptanceRequired": false,
            "ManagesVpcEndpoints": false,
            "Tags": []
        },
        {
            "ServiceName": "com.amazonaws.us-east-1.s3",
            "ServiceId": "vpce-svc-081d84efcdc7bac15",
            "ServiceType": [
                {
                    "ServiceType": "Interface"
                }
            ],
            "AvailabilityZones": [
                "us-east-1a",
                "us-east-1b",
                "us-east-1c",
                "us-east-1d",
                "us-east-1e",
                "us-east-1f"
            ],
            "Owner": "amazon",
            "BaseEndpointDnsNames": [
                "s3.us-east-1.vpce.amazonaws.com"
            ],
            "VpcEndpointPolicySupported": true,
            "AcceptanceRequired": false,
            "ManagesVpcEndpoints": false,
            "Tags": []
        }
    ],
    "ServiceNames": [
        "com.amazonaws.us-east-1.s3",
        "com.amazonaws.us-east-1.s3"
    ]
}
```

and maybe because of that EKSCTL chooses to create it with the type Interface, as it goes first in that list.

However, EKSCTL tries to create that Interface endpoint with  `"PrivateDnsEnabled": true` which is not supported.

Could someone explain what's going on? Is it AWS messing with DescribeVpcEndpointServices or what?

My EKSCTL input file

```
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
    name: test-eks-3
    region: us-east-1
    version: "1.18"


privateCluster:
    enabled: true

iam:
    withOIDC: false

vpc:
    id: vpc-xxxxxxxxxxxx
    cidr: 10.198.116.0/22 

    autoAllocateIPv6: false


    subnets:
        private:

            us-east-1a:
                id: subnet-xxxxxxxxxxxxxx

            us-east-1b:
                id: subnet-xxxxxxxxxxxxxxxxxxxx

            us-east-1c:
                id: subnet-xxxxxxxxxxxxxxxxxxxx

nodeGroups: []
```
