### ISSUE TITLE
Introduction of add-ons breaks permissions boundary

### ISSUE THREAD

**Issue by paulbes** [weaveworks/eksctl#3236]
**What were you trying to accomplish?**
Creating a cluster after add-on support was introduced fails when permissions boundaries are set on the AWS account in which the cluster is being created. 

Looking through the source code the problem was introduced by: https://github.com/weaveworks/eksctl/pull/2887/. The problem occurs because the `PermissionsBoundary` isn't added to this code: https://github.com/weaveworks/eksctl/blob/main/pkg/cfn/builder/iam.go#L274-L368

We need to do something similar to this: https://github.com/weaveworks/eksctl/blob/main/pkg/cfn/builder/iam.go#L224. 

One way of achieving this is by introducing a `PermissionsBoundary` field to this struct: https://github.com/weaveworks/eksctl/blob/main/pkg/apis/eksctl.io/v1alpha5/addon.go#L9 and then propagate that permissions boundary to the role when it is created.

Another way is to add the `clusterconfig` to this struct: https://github.com/weaveworks/eksctl/blob/main/pkg/cfn/builder/iam.go#L275, and pass the spec along down, which is comparable to the other IAM entities being created in that file.

I am happy to create a PR for fixing this. Please let me know any thoughts you might have on a preferred solution.

**What happened?**
Get the following error message, which is caused because we are not passing the permissions boundary to the role creation:

```
API: iam:CreateRole User: arn:aws:sts::REDACTED:assumed-role/iamadmin-SAML/REDACTED is not authorized to perform: iam:CreateRole on resource: arn:aws:iam:: REDACTED:role/eksctl-okctl-full-addon-iamserviceaccount-ku-Role1-REDACTED"
```

**How to reproduce it?**
```yaml
kind: ClusterConfig
apiVersion: eksctl.io/v1alpha5
metadata:
  name: okctl-full
  region: eu-west-1
  version: '1.18'
iam:
  serviceRolePermissionsBoundary: arn:aws:iam:: REDACTED:policy/oslokommune/oslokommune-boundary
  fargatePodExecutionRolePermissionsBoundary: arn:aws:iam:: REDACTED:policy/oslokommune/oslokommune-boundary
  withOIDC: true
  vpcResourceControllerPolicy: true
vpc:
  id: vpc-REDACTED
  cidr: 192.168.0.0/20
  subnets:
    private:
      eu-west-1a:
        id: subnet-REDACTED
        az: eu-west-1a
        cidr: 192.168.1.0/24
      eu-west-1b:
        id: subnet-REDACTED
        az: eu-west-1b
        cidr: 192.168.4.0/24
      eu-west-1c:
        id: subnet-REDACTED
        az: eu-west-1c
        cidr: 192.168.7.0/24
    public:
      eu-west-1a:
        id: subnet-REDACTED
        az: eu-west-1a
        cidr: 192.168.0.0/24
      eu-west-1b:
        id: subnet-REDACTED
        az: eu-west-1b
        cidr: 192.168.3.0/24
      eu-west-1c:
        id: subnet-REDACTED
        az: eu-west-1c
        cidr: 192.168.6.0/24
  nat:
    gateway: Disable
  clusterEndpoints:
    privateAccess: true
    publicAccess: true
privateCluster:
  enabled: false
nodeGroups:
- name: ng-generic
  amiFamily: AmazonLinux2
  instanceType: m5.large
  desiredCapacity: 2
  minSize: 1
  maxSize: 10
  volumeSize: 80
  ssh:
    allow: false
  labels:
    alpha.eksctl.io/cluster-name: okctl-full
    alpha.eksctl.io/nodegroup-name: ng-generic
    pool: ng-generic
  privateNetworking: true
  tags:
    k8s.io/cluster-autoscaler/enabled: 'true'
    k8s.io/cluster-autoscaler/okctl-full: owned
  iam:
    instanceRolePermissionsBoundary: arn:aws:iam::REDACTED:policy/oslokommune/oslokommune-boundary
    withAddonPolicies:
      imageBuilder: false
      autoScaler: false
      externalDNS: false
      certManager: false
      appMesh:
      appMeshPreview:
      ebs: false
      fsx: false
      efs: false
      albIngress: false
      xRay: false
      cloudWatch: false
  ami: ami-066fad1ae541d1cf9
  securityGroups:
    withShared: true
    withLocal: true
  volumeType: gp3
  volumeName: "/dev/xvda"
  AdditionalEncryptedVolume: ''
  volumeEncrypted: false
  volumeIOPS: 3000
  volumeThroughput: 125
  disableIMDSv1: false
  disablePodIMDS: false
fargateProfiles:
- name: fp-default
  selectors:
  - namespace: default
  - namespace: kube-system
  status: ''
availabilityZones:
- eu-west-1c
- eu-west-1a
- eu-west-1b
```

**Logs**
Omitting this for now, as the relevant line has been extracted above.

**Anything else we need to know?**
- Darwin Kernel Version 20.3.0
- AWS profile built with saml2aws
- Downloaded binary Darwin amd64 0.37.0 (https://github.com/weaveworks/eksctl/releases/tag/0.37.0)

**Versions**
- eksctl 0.37.0
- kubectl 1.18.9
