### ISSUE TITLE
`eksctl utils schema` generates incorrect schema for IAM ServiceAccounts 

### ISSUE THREAD

**Issue by kreempuff** [weaveworks/eksctl#3278]
**What were you trying to accomplish?**

I was moving all my workloads to use the IAM for service accounts feature. 

**What happened?**

When using the schema generated by `eksctl utils schema` to validate the `iam.serviceAccounts` key, cluster commands fails with this error: 

 ```bash
eksctl create cluster -f eksctl.config.yaml
Error: loading config file "eksctl.config.yaml": error unmarshaling JSON: while decoding JSON: json: unknown field "labels"
```

Looking at the generated schema `ClusterIAMServiceAccount` is defined as:

```json
"ClusterIAMServiceAccount": {
      "properties": {
        "annotations": {
          "additionalProperties": {
            "type": "string"
          },
          "type": "object",
          "default": "{}"
        },
        "attachPolicy": {
          "$ref": "#/definitions/InlineDocument",
          "description": "holds a policy document to attach to this service account",
          "x-intellij-html-description": "holds a policy document to attach to this service account"
        },
        "attachPolicyARNs": {
          "items": {
            "type": "string"
          },
          "type": "array",
          "description": "list of ARNs of the IAM policies to attach",
          "x-intellij-html-description": "list of ARNs of the IAM policies to attach"
        },
        "labels": {
          "additionalProperties": {
            "type": "string"
          },
          "type": "object",
          "default": "{}"
        },
        "name": {
          "type": "string"
        },
        "namespace": {
          "type": "string"
        },
        "permissionsBoundary": {
          "type": "string",
          "description": "ARN of the permissions boundary to associate with the service account",
          "x-intellij-html-description": "ARN of the permissions boundary to associate with the service account"
        },
        "roleName": {
          "type": "string",
          "description": "Specific role name instead of the Cloudformation-generated role name",
          "x-intellij-html-description": "Specific role name instead of the Cloudformation-generated role name"
        },
        "status": {
          "$ref": "#/definitions/ClusterIAMServiceAccountStatus"
        },
        "tags": {
          "additionalProperties": {
            "type": "string"
          },
          "type": "object",
          "description": "AWS tags for the service account",
          "x-intellij-html-description": "AWS tags for the service account",
          "default": "{}"
        }
      },
```

but in the eksctl code: [`ClusterIAMServiceAccount`](https://github.com/weaveworks/eksctl/blob/5ec62b526dc6e6dfd9cc7b2b1e9c11070c011da0/pkg/apis/eksctl.io/v1alpha5/iam.go#L76) has a metadata field [`ClusterIAMMeta`](https://github.com/weaveworks/eksctl/blob/a3ba4a91e48081f669a6a193d0bdc247f3515246/pkg/apis/eksctl.io/v1alpha5/iam.go#L46) that contains the ServiceAccount metadata like `labels` and `name`.

**How to reproduce it?**

This config file reproduces the problem:

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: test-cluster
  region: us-east-1
iam:
  serviceAccounts:
    - name: test-sa
      labels:
        env: test
managedNodeGroups:
  - minSize: 1
    maxSize: 1
    name: default
```

If I adjust it to follow the code instead of the schema, it works:

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: test-cluster
  region: us-east-1
iam:
  serviceAccounts:
    - metadata:
        name: test-sa
        labels:
          env: test
managedNodeGroups:
  - minSize: 1
    maxSize: 1
    name: default
```

**Logs**

No logs with `-v` is given:

```bash
eksctl create cluster -f eksctl.config.yaml -v 4
Error: loading config file "eksctl.config.yaml": error unmarshaling JSON: while decoding JSON: json: unknown field "labels"
```

**Anything else we need to know?**

Downloaded eksctl from Homebrew. It looks to be a bug in the schema generation code but I couldn't figure it out on a first pass 

**Versions**

```bash
$ eksctl version
0.37.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-14T05:14:17Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
