### ISSUE TITLE
Unable to create managed nodegroup with bootstrap commands

### ISSUE THREAD

**Issue by chaitanya-rafay** [weaveworks/eksctl#3281]
**What were you trying to accomplish?**
Create a cluster with managed nodegroup having bootstrap comands

**What happened?**
Control plane comes up but failed to bring up managed nodegroup with bootstrap commands

**How to reproduce it?**
Config File

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: test-cluster
  region: us-west-1
  version: "1.18"
vpc:
  cidr: 192.168.0.0/16
  clusterEndpoints:
    privateAccess: true
    publicAccess: false
  nat:
    gateway: Single
managedNodeGroups:
- amiFamily: AmazonLinux2
  desiredCapacity: 1
  instanceType: t3.small
  maxSize: 1
  minSize: 1
  name: bootstrap
  preBootstrapCommands:
    - curl -o aws-iam-authenticator https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/download/v0.5.0/aws-iam-authenticator_0.5.0_linux_amd64;
    - chmod 755 aws-iam-authenticator
    - mv aws-iam-authenticator /usr/local/bin/ 
    - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.18.8/2020-09-18/bin/linux/amd64/kubectl
    - chmod 755 kubectl
    - mv kubectl /usr/local/bin/
    - rm -rf /usr/bin/kubelet 
```

**Logs**
AWS::EKS::Nodegroup/ManagedNodeGroup: CREATE_FAILED – "Nodegroup bootstrap failed to stabilize: [{Code: InternalFailure,Message: Amazon EKS was unable to process your request. Please try again.,

k8s version : 1.18
eksctl version : 0.32.0

The same configfile works with non-managed nodegroups having bootstrap commands
