### ISSUE TITLE
Problem Creating Cluster with Instance Role

### ISSUE THREAD

**Issue by damogallagher** [weaveworks/eksctl#3290]
**Description**
I am trying to add a custom policy on my node groups
The nodes in question need access to Secrets Manager to grab secrets

**What Happened**
Failed to create new cluster
Message: `AWS::EKS::Nodegroup/ManagedNodeGroup: CREATE_FAILED – "Following required service principals [ec2.amazonaws.com] were not found in the trust relationships of nodeRole arn:aws:iam::735707224535:role/eksctl-instance-role (Service: AmazonEKS; Status Code: 400; Error Code: InvalidParameterException; Request ID: ec734e64-2c71-4c24-858d-a8edd3e34a4c; Proxy: null)"`

**What you expected to happen?**
To create cluster successfully.

**How to reproduce it?**
exec eksctl create cluster -f cluster-config.yaml

cluster-config.yaml is below.
```
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dev-cluster
  region: us-east-1
  version: '1.18'

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: eksctl-service-account
    attachPolicyARNs:
    - "arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy"
    - "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
    attachPolicy: 
      Version: "2012-10-17"
      Statement:
      - Effect: Allow
        Action:
        - "secretsmanager:GetSecretValue"
        Resource: '*'
    roleName: eksctl-instance-role 

privateCluster:
  enabled: false

vpc:
  id: "vpc-077a6b9836e5b0f8a"
  subnets:
    private:
      us-east-1a:
          id: "subnet-0cde1ebd521c4714e"
      us-east-1b:
          id: "subnet-06dc1e3aecf6690fa"
    public:
      us-east-1a:
          id: "subnet-0b7b219f9dd106813"
      us-east-1b:
          id: "subnet-0244c8234b87067dc"        

managedNodeGroups:
  - name: k8s-nodegroup
    instanceType: t3.small
    desiredCapacity: 2
    volumeSize: 1024
    volumeEncrypted: true
    privateNetworking: true
    labels: 
      app: k8s
    securityGroups:
      attachIDs: ["sg-0865eebdc59021a13"]
  - name: server-nodegroup
    instanceType: t3.small
    desiredCapacity: 2
    volumeSize: 1024
    volumeEncrypted: true
    privateNetworking: true
    labels: 
      app: server
    securityGroups:
      attachIDs: ["sg-0865eebdc59021a13"]
    preBootstrapCommands:
      - sed -i '/^KUBELET_EXTRA_ARGS=/a KUBELET_EXTRA_ARGS+=" --register-with-taints=server=true:NoSchedule"' /etc/eks/bootstrap.sh
    iam:
      instanceRoleARN: arn:aws:iam::735707224535:role/eksctl-instance-role 
  - name: fetcher-nodegroup
    instanceType: t3.small
    desiredCapacity: 2
    volumeSize: 1024
    volumeEncrypted: true
    privateNetworking: true
    labels: 
      app: fetcher
    securityGroups:
      attachIDs: ["sg-0865eebdc59021a13"]
    preBootstrapCommands:
      - sed -i '/^KUBELET_EXTRA_ARGS=/a KUBELET_EXTRA_ARGS+=" --register-with-taints=fetcher=true:NoSchedule"' /etc/eks/bootstrap.sh
    iam:
      instanceRoleARN: arn:aws:iam::735707224535:role/eksctl-instance-role        

```
**Versions**
eksctl version 0.37.0
kubectl version 1.19.3

**Logs**
```
[ℹ]  eksctl version 0.37.0
[ℹ]  using region us-east-1
[✔]  using existing VPC (vpc-077a6b9836e5b0f8a) and subnets (private:[subnet-0cde1ebd521c4714e subnet-06dc1e3aecf6690fa] public:[subnet-0b7b219f9dd106813 subnet-0244c8234b87067dc])
[!]  custom VPC/subnets will be used; if resulting cluster doesn't function as expected, make sure to review the configuration of VPC/subnets
[ℹ]  using Kubernetes version 1.18
[ℹ]  creating EKS cluster "dev-cluster" in "us-east-1" region with managed nodes
[ℹ]  3 nodegroups (fetcher-nodegroup, k8s-nodegroup, server-nodegroup) were included (based on the include/exclude rules)
[ℹ]  will create a CloudFormation stack for cluster itself and 0 nodegroup stack(s)
[ℹ]  will create a CloudFormation stack for cluster itself and 3 managed nodegroup stack(s)
[ℹ]  if you encounter any issues, check CloudFormation console or try 'eksctl utils describe-stacks --region=us-east-1 --cluster=dev-cluster'
[ℹ]  CloudWatch logging will not be enabled for cluster "dev-cluster" in "us-east-1"
[ℹ]  you can enable it with 'eksctl utils update-cluster-logging --enable-types={SPECIFY-YOUR-LOG-TYPES-HERE (e.g. all)} --region=us-east-1 --cluster=dev-cluster'
[ℹ]  Kubernetes API endpoint access will use default of {publicAccess=true, privateAccess=false} for cluster "dev-cluster" in "us-east-1"
[ℹ]  2 sequential tasks: { create cluster control plane "dev-cluster", 3 sequential sub-tasks: { 4 sequential sub-tasks: { wait for control plane to become ready, associate IAM OIDC provider, 2 parallel sub-tasks: { 2 sequential sub-tasks: { create IAM role for serviceaccount "default/eksctl-service-account", create serviceaccount "default/eksctl-service-account" }, 2 sequential sub-tasks: { create IAM role for serviceaccount "kube-system/aws-node", create serviceaccount "kube-system/aws-node" } }, restart daemonset "kube-system/aws-node" }, create addons, 3 parallel sub-tasks: { create managed nodegroup "k8s-nodegroup", create managed nodegroup "server-nodegroup", create managed nodegroup "fetcher-nodegroup" } } }
[ℹ]  building cluster stack "eksctl-dev-cluster-cluster"
[ℹ]  deploying stack "eksctl-dev-cluster-cluster"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-cluster"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-cluster"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-cluster"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-cluster"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-cluster"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-cluster"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-cluster"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-cluster"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-cluster"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-cluster"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-cluster"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-cluster"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-cluster"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-cluster"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-cluster"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-cluster"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-cluster"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-cluster"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-cluster"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-cluster"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-cluster"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-cluster"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-cluster"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-cluster"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-cluster"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-cluster"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-cluster"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-cluster"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-cluster"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-cluster"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-cluster"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-cluster"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-cluster"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-cluster"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-cluster"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-cluster"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-cluster"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-cluster"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-cluster"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-cluster"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-cluster"
[ℹ]  building iamserviceaccount stack "eksctl-dev-cluster-addon-iamserviceaccount-kube-system-aws-node"
[ℹ]  building iamserviceaccount stack "eksctl-dev-cluster-addon-iamserviceaccount-default-eksctl-service-account"
[ℹ]  deploying stack "eksctl-dev-cluster-addon-iamserviceaccount-kube-system-aws-node"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-addon-iamserviceaccount-kube-system-aws-node"
[ℹ]  deploying stack "eksctl-dev-cluster-addon-iamserviceaccount-default-eksctl-service-account"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-addon-iamserviceaccount-default-eksctl-service-account"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-addon-iamserviceaccount-default-eksctl-service-account"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-addon-iamserviceaccount-kube-system-aws-node"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-addon-iamserviceaccount-default-eksctl-service-account"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-addon-iamserviceaccount-kube-system-aws-node"
[ℹ]  serviceaccount "kube-system/aws-node" already exists
[ℹ]  updated serviceaccount "kube-system/aws-node"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-addon-iamserviceaccount-default-eksctl-service-account"
[ℹ]  created serviceaccount "default/eksctl-service-account"
[ℹ]  daemonset "kube-system/aws-node" restarted
[ℹ]  building managed nodegroup stack "eksctl-dev-cluster-nodegroup-k8s-nodegroup"
[ℹ]  building managed nodegroup stack "eksctl-dev-cluster-nodegroup-fetcher-nodegroup"
[ℹ]  building managed nodegroup stack "eksctl-dev-cluster-nodegroup-server-nodegroup"
[ℹ]  deploying stack "eksctl-dev-cluster-nodegroup-fetcher-nodegroup"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-nodegroup-fetcher-nodegroup"
[ℹ]  deploying stack "eksctl-dev-cluster-nodegroup-server-nodegroup"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-nodegroup-server-nodegroup"
[ℹ]  deploying stack "eksctl-dev-cluster-nodegroup-k8s-nodegroup"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-nodegroup-k8s-nodegroup"
[ℹ]  waiting for CloudFormation stack "eksctl-dev-cluster-nodegroup-server-nodegroup"
[✖]  unexpected status "ROLLBACK_IN_PROGRESS" while waiting for CloudFormation stack "eksctl-dev-cluster-nodegroup-server-nodegroup"
[ℹ]  fetching stack events in attempt to troubleshoot the root cause of the failure
[✖]  AWS::EKS::Nodegroup/ManagedNodeGroup: CREATE_FAILED – "Following required service principals [ec2.amazonaws.com] were not found in the trust relationships of nodeRole arn:aws:iam::735707224535:role/eksctl-instance-role (Service: AmazonEKS; Status Code: 400; Error Code: InvalidParameterException; Request ID: ec734e64-2c71-4c24-858d-a8edd3e34a4c; Proxy: null)"
[!]  1 error(s) occurred and cluster hasn't been created properly, you may wish to check CloudFormation console
[ℹ]  to cleanup resources, run 'eksctl delete cluster --region=us-east-1 --name=dev-cluster'
[✖]  waiting for CloudFormation stack "eksctl-dev-cluster-nodegroup-server-nodegroup": ResourceNotReady: failed waiting for successful resource state
Error: failed to create cluster "dev-cluster"
```

**Comment by cPu1** [comment]
Hi @damogallagher, the role created by eksctl for IRSA (`iam.serviceAccounts`) is intended to be used by a Kubernetes Pod needing access to AWS resources, and not as a node role. The nodegroup creation is failing because the Managed Nodegroup API requires the supplied IAM role to have a trust relationship with `ec2.amazonaws.com`, but the role created by IRSA does not have it. 

>The nodes in question need access to Secrets Manager to grab secrets

If the node itself needs access to Secrets Manager, you'll have to supply the policies in the node's IAM config, and not with `iam.serviceAccounts`, as in:

```
...
managedNodeGroups:
- name: server
  iam:
    attachPolicyARNs:
    - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
    - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
    - arn:aws:iam::aws:policy/SecretsManagerReadWrite # AWS managed policy for Secrets Manager
# other config
```

If a pod instead requires access to Secrets Manager, you'll have to set the service account for that pod to the eksctl-created one (`eksctl-service-account`).
