### ISSUE TITLE
`utils update-kube-proxy` doesn't update its cluster role in 1.19

### ISSUE THREAD

**Issue by aclevername** [weaveworks/eksctl#3307]
**What were you trying to accomplish?**
Update kube proxy for 1.19 cluster

**What happened?**
It is not following the steps outlined in the aws docs, speciffically:
```
   1. \(For 1.19\) Update the `system:node-proxier` `ClusterRole` to allow `kube-proxy` read permissions for `endpointslices` resources. This is needed for clusters created on EKS 1.17 or earlier versions.
      ```
      kubectl edit clusterrole system:node-proxier
      ```
      and add the following to the rules
      ```
        - apiGroups:
          - "discovery.k8s.io"
          resources:
          - endpointslices
          verbs:
          - list
          - watch
      ```
```
https://github.com/awsdocs/amazon-eks-user-guide/pull/314/files
**How to reproduce it?**
Create 1.17 cluster, upgrade to 1.18, 1.19, run `utils update-kube-proxy` and find the cluster is in a broken state. AWS container roadmap issue: https://github.com/aws/containers-roadmap/issues/1053#issuecomment-781212470

**Comment by aclevername** [comment]
Clusters created in 1.18 already contain this cluster role addition:
```
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - services
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - list
  - watch
```
---

If you create a 1.17 cluster you get the following:
```
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - services
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
  - update
```

Once updated to 1.18 it becomes:

```
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - services
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - list
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - watch
```
