### ISSUE TITLE
Need support for equivalent CLI "--fargate" option in a configuration file

### ISSUE THREAD

**Issue by ZillaG** [weaveworks/eksctl#3311]
**What feature/behavior/change do you want?**
```
$ eksctl version
0.38.0
```
When creating a Fargate-only cluster, this is done on the command line
`$ eksctl create cluster ... --fargate`

However, I can't pass that option when using a config file
```
$ eksctl create cluster ... --fargate -f config.yaml
Error: cannot use --fargate when --config-file/-f is set
```
I don't see an equivalent option in [Config file schema](https://eksctl.io/usage/schema/#latest-schema) doc. Can you please add it?

**Why do you want this feature?**

I created my Fargate-only cluster using a config file, and chased a problem for 2 days on why `coredns` wasn't coming up. It's because, it was set up to `eks.amazonaws.com/compute-type: ec2`. I had to edit it to `fargate` to get it to come up, but this should really be in a configuration if it's not supported on a command line along with a config file option.

**Comment by Callisto13** [comment]
Hey @ZillaG, thanks for raising this issue.

Unfortunately this is a case of crappy docs.

The equivalent of running `create cluster --fargate` is to add a `fargateProfiles` section in the config file (eg [this example](https://github.com/weaveworks/eksctl/blob/main/examples/16-fargate-profile.yaml)). The `fp-default` profile in that config is what the `--fargate` flag creates "behind the scenes".

I will review our docs and make sure that this is clear.

**Comment by ZillaG** [comment]
Here's my config file, taken directly from the example you posted. As you can see I have fargate profiles. However I'm using existing VPC and only private subnets and only enable private endpoints. (I should've added this to my post, my bad.). I can also reproduce the problem even if I let EKS create it's own VPC, but only use private endpoints. If I let EKS create the cluster's VPC using both public and private endpoints, I don't get the issue.

```
kind: ClusterConfig
apiVersion: eksctl.io/v1alpha5

metadata:
  name: sandbox
  region: us-east-1
  version: "1.19"

# The VPC and subnets are for the data plane, where the pods will
# ultimately be deployed.
vpc:
  id: "vpc-xxxxx"
  clusterEndpoints:
    privateAccess: true
    publicAccess: false
  subnets:
    # us-east-1a is full
    private:
      us-east-1b:
        id: "subnet-xxxxx"
      us-east-1c:
        id: "subnet-yyyyy"

fargateProfiles:
  - name: fp-default
    selectors:
      # All workloads in the "default" Kubernetes namespace will be
      # scheduled onto Fargate:
      - namespace: default
  - name: fp-kube
    selectors:
      # All workloads in the "kube-system" Kubernetes namespace will be
      # scheduled onto Fargate:
      - namespace: kube-system

cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator", "controllerManager", "scheduler"]
```
