### ISSUE TITLE
Deviation in behavior of awscli (create-nodegroup) and eksctl managedNodeGroup

### ISSUE THREAD

**Issue by amrragab8080** [weaveworks/eksctl#3312]
**What were you trying to accomplish?**
Create a managed nodegroup in eksctl with a single subnet. This is possible with the aws cli but not possible in eksctl

in awscli:
``` 
aws eks create-nodegroup --cluster-name adorable-rainbow-1613757615 --nodegroup-name p4d-ng --node-role arn:aws:iam::231748552833:role/p4d-efa-eks-NodeInstanceRole-AAIVP4XD88O4 --subnets subnet-05f16de978ef56b90 --launch-template name=NodeLaunchTemplate_1Z0xcongawf1,version=1 --region us-west-2
```

**What happened?**
```
in eksctl you get an error
Error: VPC doesn't have enough subnets for nodegroup AZs or subnets (allSubnets=v1alpha5.AZSubnetMapping(nil) AZs=[]string(nil) subnets=[]string{"p4d-large-one"})
```
**How to reproduce it?**
```
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: adorable-rainbow-1613757615
  region: us-west-2

vpc:
  id: vpc-34f1894c
  subnets:
    private:
      p4d-large-one:
        id: subnet-05f16de978ef56b90

managedNodeGroups:
  - name: p4d-ng
    subnets:
    - p4d-large-one
    launchTemplate:
      id: lt-09cde1d079c8a830c
      version: "1"
```

```
$ 0.38
$ 1.19
```

**Comment by michaelbeaumont** [comment]
Thanks for the report @amrragab8080. The issue here is that there aren't enough subnets specified under `vpc.subnets`. As a workaround, you can specify the other cluster subnets under `vpc.subnets`.

**Comment by amrragab8080** [comment]
Tried that with below file
```
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: adorable-rainbow-1613757615
  region: us-west-2

vpc:
  id: vpc-34f1894c
  subnets:
    public:
      endpoint-one:
        id: subnet-4532e73d
      endpoint-two:
        id: subnet-8f8b7dc5
    private:
      p4d-large-one:
        id: subnet-05f16de978ef56b90

managedNodeGroups:
  - name: p4d-ng
    subnets:
    - p4d-large-one
    launchTemplate:
      id: lt-0d608d841ba6559c2
      version: "1"
```
However now I get a new error:
```
Error: VPC doesn't have subnet with name p4d-large-one (allSubnets=v1alpha5.AZSubnetMapping{"endpoint-one":v1alpha5.AZSubnetSpec{ID:"subnet-4532e73d", AZ:"us-west-2a", CIDR:(*ipnet.IPNet)(0xc000bd2930)}, "endpoint-two":v1alpha5.AZSubnetSpec{ID:"subnet-8f8b7dc5", AZ:"us-west-2b", CIDR:(*ipnet.IPNet)(0xc000bd2990)}} AZs=[]string(nil) subnets=[]string{"p4d-large-one"})
```
