### ISSUE TITLE
Trying to verify --enable-cadvisor-json-endpoints is passed on a 1.18 built cluster

### ISSUE THREAD

**Issue by JayG-EBSCO** [weaveworks/eksctl#3329]
We are deploying EKS clusters with v1.18, which has the cadvisor json endpoint disabled by default. On our clusters, we have one tool that needs this endpoint for the moment, so to enable this, I am trying to use the --enable-cadvisor-json-endpoints kubelet flag.

**What help do you need?**

The nodegroups build successfully, and are functional. Before I deploy the tool needing the flag, I want to verify the flag was actually applied, but I cannot see any reference to it in my kubelet config on any of the nodes. My Eksctl nodegroup config is as follows for the kubelet extra args:

```
    kubeletExtraConfig:
      kubeReserved:
        cpu: "500m"
        memory: "500Mi"
        ephemeral-storage: "1Gi"
      kubeReservedCgroup: "/kube-reserved"
      systemReserved:
        cpu: "500m"
        memory: "500Mi"
        ephemeral-storage: "1Gi"
      evictionHard:
        memory.available:  "600Mi"
        nodefs.available: "10%"
      enable-cadvisor-json-endpoints: true
```

The error thrown is:
`[✖]  validating generated KubeletConfiguration object: error unmarshaling JSON: while decoding JSON: json: unknown field "enable-cadvisor-json-endpoints"`

**Comment by Callisto13** [comment]
Hi @JayG-EBSCO, thanks for opening this issue.

I believe that flag would qualify as a feature gate, could you try adding it like this instead?

```yaml
kubeletExtraConfig:
    ...
    featureGates:
        EnableCadvisorJsonEndpoints: true
```
