### ISSUE TITLE
You must use a valid fully-formed launch template

### ISSUE THREAD

**Issue by ajinkya933** [weaveworks/eksctl#3355]
I have following cluster creation yaml file:

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: multinodegroup-bahrain
  region: me-south-1
nodeGroups:
  - name: node-one
    minSize: 1
    maxSize: 5
    iam:
      withAddonPolicies:
        autoScaler: true
    labels: { role: workers }
    instanceType: r4.xlarge
    desiredCapacity: 1
    volumeSize: 50
```

When I create a cluster from this yaml file using `eksctl create nodegroup -f firstnode.yaml` the cluster is created but nodegroup is not attached to this cluster 

error log:

```
[✖]  unexpected status "ROLLBACK_COMPLETE" while waiting for CloudFormation stack "eksctl-multinodegroup-bahrain-nodegroup-node-one"
[ℹ]  fetching stack events in attempt to troubleshoot the root cause of the failure
[!]  AWS::IAM::Role/NodeInstanceRole: DELETE_IN_PROGRESS
[!]  AWS::EC2::SecurityGroup/SG: DELETE_IN_PROGRESS
[!]  AWS::IAM::InstanceProfile/NodeInstanceProfile: DELETE_IN_PROGRESS
[!]  AWS::EC2::LaunchTemplate/NodeGroupLaunchTemplate: DELETE_IN_PROGRESS
[!]  AWS::EC2::SecurityGroupIngress/IngressInterCluster: DELETE_IN_PROGRESS
[!]  AWS::IAM::Policy/PolicyAutoScaling: DELETE_IN_PROGRESS
[!]  AWS::EC2::SecurityGroupEgress/EgressInterClusterAPI: DELETE_IN_PROGRESS
[!]  AWS::EC2::SecurityGroupEgress/EgressInterCluster: DELETE_IN_PROGRESS
[!]  AWS::EC2::SecurityGroupIngress/IngressInterClusterCP: DELETE_IN_PROGRESS
[!]  AWS::EC2::SecurityGroupIngress/IngressInterClusterAPI: DELETE_IN_PROGRESS
[✖]  AWS::AutoScaling::AutoScalingGroup/NodeGroup: CREATE_FAILED – "You must use a valid fully-formed launch template. The requested configuration is currently not supported. Please check the documentation for supported configurations. (Service: AmazonAutoScaling; Status Code: 400; Error Code: ValidationError; Request ID: df8b4c23-ec3b-48f0-8014-e6f6ba2777c1; Proxy: null)"
[ℹ]  1 error(s) occurred and nodegroups haven't been created properly, you may wish to check CloudFormation console
[ℹ]  to cleanup resources, run 'eksctl delete nodegroup --region=me-south-1 --cluster=multinodegroup-bahrain --name=<name>' for each of the failed nodegroup
[✖]  waiting for CloudFormation stack "eksctl-multinodegroup-bahrain-nodegroup-node-one": ResourceNotReady: failed waiting for successful resource state
```

Note I already have a cluster on Cloud formation created using same yaml file above (with diffrent cluster name & nodegroup name) but during first time it ran good when I retry to create cluster I get this error?

How do I resolve it, Is it related to VPC / sequrity groups ?  if so please suggest lines to add in yaml file.
