### ISSUE TITLE
roleName accidentally deleted from example 16

### ISSUE THREAD

**Issue by darnone** [weaveworks/eksctl#3356]
I was trying to copy some code example and I accidentally deleted the roleName for the autoscaler metadata. I don't know why this change happened since I don't have write permission.  So I simply reporting it.

roleName:  eks-cluster-autoscaler-role

indented to match its metadata.

**Comment by Callisto13** [comment]
Hi @darnone, sorry I don't think I understand what issue you encountered.

> I was trying to copy some code example

Which code example? Could you explain in a bit more detail what you were doing?

> accidentally deleted the roleName for the autoscaler metadata

From where?

> I don't have write permission

Write permission where? On the cluster?

**Comment by darnone** [comment]
@Callisto13,

Sorry about the confusion.  The code example is 13-iamserviceaccounts.yaml and the roleName: eks-cluster-autoscaler-role was removed from line 50. Then empty line is needed after that.

**Comment by Callisto13** [comment]
I still don't understand what the problem is there. From what I can see `roleName` was never in that file, on line 50 or otherwise.

**Comment by darnone** [comment]
Maybe I am mistaken. The example was not originally this?  This is what I captured when I copied it.

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-13
  region: us-west-2

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: s3-reader
      # if no namespace is set, "default" will be used;
      # the namespace will be created if it doesn't exist already
      namespace: backend-apps
      labels: {aws-usage: "application"}
    attachPolicyARNs:
    - "arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess"
    tags:
      Owner: "John Doe"
      Team: "Some Team"
  - metadata:
      name: cache-access
      namespace: backend-apps
      labels: {aws-usage: "application"}
    attachPolicyARNs:
    - "arn:aws:iam::aws:policy/AmazonDynamoDBReadOnlyAccess"
    - "arn:aws:iam::aws:policy/AmazonElastiCacheFullAccess"
 - metadata:
      name: cluster-autoscaler
      namespace: kube-system
      labels: {aws-usage: "cluster-ops"}
    attachPolicy: # inline policy can be defined along with `attachPolicyARNs`
      Version: "2012-10-17"
      Statement:
      - Effect: Allow
        Action:
        - "autoscaling:DescribeAutoScalingGroups"
        - "autoscaling:DescribeAutoScalingInstances"
        - "autoscaling:DescribeLaunchConfigurations"
        - "autoscaling:DescribeTags"
        - "autoscaling:SetDesiredCapacity"
        - "autoscaling:TerminateInstanceInAutoScalingGroup"
        - "ec2:DescribeLaunchTemplateVersions"
        Resource: '*'
    roleName: eksctl-cluster-autoscaler-role

nodeGroups:
  - name: "ng-1"
    tags:
      # EC2 tags required for cluster-autoscaler auto-discovery
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/cluster-13: "owned"
    desiredCapacity: 1
```

**Comment by Callisto13** [comment]
From checking through git history I can see it was never there. But even if it was there and you deleted it, what were you worried had happened?

**Comment by darnone** [comment]
That I had screwed up the example.  If this is my mistake then I am sorry for the noise.  Looking at the eksctl.io documentation on [IAM service accounts](https://eksctl.io/usage/iamserviceaccounts/):
 
```
- metadata:
      name: cluster-autoscaler
      namespace: kube-system
      labels: {aws-usage: "cluster-ops"}
    wellKnownPolicies:
      autoScaler: true
    roleName: eksctl-cluster-autoscaler-role
    roleOnly: true
```
Maybe this is where I go it from?

But then looking at the schema, I see this is optional:
```
roleName:   Specific role name instead of the Cloudformation-generated role name
```
