### ISSUE TITLE
eksctl IAM Service account requires policies

### ISSUE THREAD

**Issue by darnone** [weaveworks/eksctl#3358]
I need to define a OIDC role that has no policies.  The is role is assumed by other roles that do have policies.  Specifically, this is for kubernetes-external-secrets.  When I try to use eksctl to create a role without a policy, I get the following error:
```
Error: iam.serviceAccounts[0].wellKnownPolicies, iam.serviceAccounts[0].attachPolicyARNs or iam.serviceAccounts[0].attachPolicy must be set
```
I there a workaround for this? I there a way to define an "empty policy"?  If this is missing a new feature would allow setting IAM service account roles without policies.

Code is:
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-nrg-qa-cluster
  region: us-east-1

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: kes-eks-nrg-qa-cluster
      namespace: kes-eks-nrg-qa-cluster
      labels: {aws-usage: "cluster-ops", cluster: "eks-nrg-qa-cluster", kms-key-name: "eks-nrg-qa-cluster-key"}
    roleName: kes-eks-nrg-qa-cluster-role
    roleOnly: true
```

Command is:
```
eksctl create iamserviceaccount \
    --approve \
    --config-file=./deploy-iam-kes-service-account-role.yaml
```
eskctl version is 0.38.0, kubectl v1.19, awscli 2.0.38
