### ISSUE TITLE
unknown field "permissionsBoundary" under add-ons section while trying to create cluster via config file.

### ISSUE THREAD

**Issue by cooldudesam** [weaveworks/eksctl#3413]
**What were you trying to accomplish?**

I want to enable add-ons via eksctl while provisiong cluster. Right now since only vpc-cni is available from AWS would like to test it add-on so, eksctl creates this add-on, IAM role and service account to annotate it under kube-system namespace. 

**What happened?**

Iam using the filed permissionsBoundary under add-ons section and as per eksctl schema doc it says you can add permissionsBoundary under addons section but when i do that i get below error

eksctl schema https://eksctl.io/usage/schema/ 

```
% eksctl create cluster  --config-file=/tmp/eksctl-cluster/us-east-1/mw-eksctltest-c0/cluster_config.yaml --without-nodegroup
Error: loading config file "/tmp/eksctl-cluster/us-east-1/mw-eksctltest-c0/cluster_config.yaml": error unmarshaling JSON: while decoding JSON: json: unknown field "permissionsBoundary"
```

Here is how iam giving this in my cluster config file

```yaml
iam:
  serviceRolePermissionsBoundary: "arn:aws:iam::xxxxxxxxx:policy/CreatedRolesPermissionsBoundary"
  withOIDC: true

addons:
- name: vpc-cni
  version: 1.7.5 # optional
  attachPolicyARNs: #optional
  - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
  permissionsBoundary: "arn:aws:iam::xxxxxxxxxxxx:policy/CreatedRolesPermissionsBoundary"
```

Is anyone facing the similar issue?  Can we get this issue fixed so we can use the feature in the addons section?
