### ISSUE TITLE
Required force option in eksctl manifest for addon

### ISSUE THREAD

**Issue by usman-github** [weaveworks/eksctl#3414]
**What feature/behavior/change do you want?**

eksctl manifest file should have "force" property for addon like we have adhoc command for addon.

`eksctl update addon --name vpc-cni --version v1.7.9-eksbuild.1 --cluster <cluster-name> --force`

**Why do you want this feature?**

Recently EKS released the new version of CNI for addon. If we create the cluster using latest CNI version "1.7.9" then cluster get created successfully but addon fail to create with below error in health.

Error :

`Apply failed with 2 conflicts: conflicts with "kubectl-client-side-apply" using apps/v1: - .spec.template.spec.containers[name="aws-node"].image - .spec.template.spec.initContainers[name="aws-vpc-cni-init"].image`

Manifest :

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks19
  region: eu-west-1
  version: "1.19"
  

addons:
  - name: vpc-cni
    version: v1.7.5-eksbuild.1
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy


```

At the moment i am creating this feature request EKS cluster get created with [CNI version 1.7.5](https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html) by default and while creating the addon with version 1.7.9 using above manifest through the conflict error.

As we know a [conflict](https://kubernetes.io/docs/reference/using-api/server-side-apply/#conflicts) is a special status error that occurs when an Apply operation tries to change a field, which another user also claims to manage. This prevents an applier from unintentionally overwriting the value set by another user.

Workaround :

As of now the workaround i am using is below.

1. creating the EKS cluster with CNI version 1.7.5 for addon.

Manifest :

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks19
  region: eu-west-1
  version: "1.19"
  

addons:
  - name: vpc-cni
    version: v1.7.5-eksbuild.1
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
```

2. updating the CNI version in addon to 1.7.9 using adhoc command.

`eksctl update addon --name vpc-cni --version v1.7.9-eksbuild.1 --cluster eks19 --force`
