### ISSUE TITLE
Add support for --dry-run to `create cluster` and `create nodegroup`

### ISSUE THREAD

**Issue by cPu1** [weaveworks/eksctl#3426]
This is outlined in this proposal here: https://github.com/weaveworks/eksctl/blob/main/docs/proposal-007-instance-selector-dry-run.md#dry-run

The gist of the proposal is that when `--dry-run` is supplied to `create cluster` or `create nodegroup`, eksctl will output a ClusterConfig containing the default values and representing the supplied CLI options.

An example invocation would look like this:

```shell
$ eksctl create cluster --dry-run --nodes=1 --nodes-max=2 --node-zones=us-west-2a,us-west-2d --alb-ingress-access --managed --spot --node-volume-size=50
```

```yaml
apiVersion: eksctl.io/v1alpha5
availabilityZones:
- us-west-2b
- us-west-2a
- us-west-2c
cloudWatch:
  clusterLogging: {}
iam:
  vpcResourceControllerPolicy: true
  withOIDC: false
kind: ClusterConfig
managedNodeGroups:
- amiFamily: AmazonLinux2
  availabilityZones:
  - us-west-2a
  - us-west-2d
  desiredCapacity: 1
  disableIMDSv1: false
  disablePodIMDS: false
  iam:
    withAddonPolicies:
      albIngress: true
      appMesh: false
      appMeshPreview: false
      autoScaler: false
      certManager: false
      cloudWatch: false
      ebs: false
      efs: false
      externalDNS: false
      fsx: false
      imageBuilder: false
      xRay: false
  instanceType: m5.large
  labels:
    alpha.eksctl.io/cluster-name: dry-run-cluster
    alpha.eksctl.io/nodegroup-name: ng
  maxSize: 2
  minSize: 1
  name: ng
  privateNetworking: false
  securityGroups:
    withLocal: null
    withShared: null
  spot: true
  ssh:
    allow: false
    enableSsm: false
    publicKeyPath: ""
  tags:
    alpha.eksctl.io/nodegroup-name: ng
    alpha.eksctl.io/nodegroup-type: managed
  volumeIOPS: 3000
  volumeSize: 50
  volumeThroughput: 125
  volumeType: gp3
metadata:
  name: dry-run-cluster
  region: us-west-2
  version: "1.18"
privateCluster:
  enabled: false
vpc:
  autoAllocateIPv6: false
  cidr: 192.168.0.0/16
  clusterEndpoints:
    privateAccess: false
    publicAccess: true
  nat:
    gateway: Single

```

Related to https://github.com/weaveworks/eksctl/issues/633
