### ISSUE TITLE
is r5b supported by aws eks / eksctl ? 

### ISSUE THREAD

**Issue by kushagra391** [weaveworks/eksctl#3440]
**What feature/behavior/change do you want?**
It looks like `r5b` series of instances are not supported by eksctl at the moment. 
When trying to add a nodegroup with `r5b`, the commend times out after 20 min

```yaml
nodeGroups:
  - name: ng-on-demand-nodes-4x
    tags: {...}
    availabilityZones: [ "us-west-2c" ]
    desiredCapacity: 3
    instanceType: r5n.4xlarge
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      withAddonPolicies:
        ebs: true
        autoScaler: true
    volumeSize: 10
    ebsOptimized: true
```

```shell
eksctl create nodegroup --config-file=eks_config.yaml --include='ng-on-demand-nodes-4x'

[ℹ]  nodegroup "ng-on-demand-nodes-4x" has 0 node(s)
[ℹ]  waiting for at least 3 node(s) to become ready in "ng-on-demand-nodes-4x"
```
Although i see them present in https://github.com/awslabs/amazon-eks-ami/blame/master/files/eni-max-pods.txt#L311-L319  and https://github.com/weaveworks/eksctl/blob/main/pkg/nodebootstrap/maxpods.go#L294-L302

ASG and the instances are getting created properly, also see AMIs for EKS v0.17 getting attached.  

Am not sure if this is something that needs to be supported by EKS or eksctl. 

(eksctl v0.30 / EKS 0.17)

**Why do you want this feature?**
We are using EKS for running an OLAP DB that benefits from faster EBS.
