### ISSUE TITLE
Support for multiple AMI release versions in managed node groups

### ISSUE THREAD

**Issue by mikestef9** [weaveworks/eksctl#3506]
**What feature/behavior/change do you want?**
EKS managed node groups now allows you to pass any AMI release version for a managed node group, instead of only the latest version. See https://github.com/aws/containers-roadmap/issues/810. eksctl needs to expose a way to pass through the AMI release version.

Ex.

```
managedNodeGroups:
  - name: managed-ng
    instanceType: m5.large
    releaseVersion: 1.19.6-20210310
```

**Why do you want this feature?**
For consistency between dev/test and prod environments, I want to ensure the same AMI release version is used.
