### ISSUE TITLE
iamidentitymapping command does not honor multiple groups

### ISSUE THREAD

**Issue by mikestef9** [weaveworks/eksctl#3539]
Seeing different behavior based on the cli input format

```
eksctl create iamidentitymapping --cluster staging-cluster --arn arn:aws:iam::123456:role/testing --group group1 --group group2 --username admin

- groups:
  - group1
  - group2
  rolearn: arn:aws:iam::123456:role/testing
  username: admin

```

```
eksctl create iamidentitymapping --cluster staging-cluster --arn arn:aws:iam::123456:role/testing --group "group1,group2" --username admin

- groups:
  - group1,group2
  rolearn: arn:aws:iam::123456:role/testing
  username: admin
```

I'd expect the second command to produce the same output as the first

**Versions**
0.43.0
