### ISSUE TITLE
ManagedNodeGroups Launch without documented default volume size

### ISSUE THREAD

**Issue by gjtempleton** [weaveworks/eksctl#3540]
**What were you trying to accomplish?**

Launch managed node groups with the documented default 80GB root volumes.

**What happened?**

The managed node groups were created with no configuration of storage in the launch template, and therefore launched instead with only 20GB of storage as the default of the launch template.

**How to reproduce it?**

Create a cluster using managed and unmanaged node groups without specifying the `volumeSize` in the specs. As expected node groups will be created with 80GB root volumes by default, MNG instances will instead launch with only 20GB volumes by default.

Note the two distinct groupings here, with all nodes in the unmanaged node groups getting 80GB volumes as expected, and the managed node group volumes getting 20GB.
<img width="1608" alt="Thanos_long_term_storage_Prometheus_solution" src="https://user-images.githubusercontent.com/6452486/113907600-79a6da80-97cd-11eb-839c-3841e48bab5a.png">

Cluster config file:
```yaml
cluster:
  apiVersion: eksctl.io/v1alpha5
  cloudWatch:
    clusterLogging:
      enableTypes:
        - audit
        - authenticator
  iam:
    serviceRoleARN: <custom_role>
  kind: ClusterConfig
  managedNodeGroups:
    - availabilityZones:
        - eu-central-1a
      iam:
        instanceRoleARN: <custom_role>
      instanceTypes:
        - c5.9xlarge
        - c5a.8xlarge
      maxSize: 50
      minSize: 1
      name: mixed-instances-8xl-abcdef
      privateNetworking: true
      securityGroups:
        attachIDs: [-list-of-sg-ids]
        withShared: false
      spot: true
      ssh:
        allow: true
        enableSsm: true
        publicKeyPath: /eks/key.pub
    - availabilityZones:
        - eu-central-1a
      iam:
        instanceRoleARN: <custom_role>
      instanceTypes:
        - c5.2xlarge
        - c5a.2xlarge
      labels:
        role: custom-role
      maxSize: 50
      minSize: 1
      name: nodes-default-gateway-ingress-abcdef
      preBootstrapCommands:
        - sed -i '/^KUBELET_EXTRA_ARGS=/a KUBELET_EXTRA_ARGS+=" --register-with-taints=node-role.kubernetes.io/custom-role=:NoSchedule"'
          /etc/eks/bootstrap.sh
      privateNetworking: true
      securityGroups:
        attachIDs: [-list-of-sg-ids]
        withShared: false
      spot: true
      ssh:
        allow: true
        enableSsm: true
        publicKeyPath: /eks/key.pub
  metadata:
    name: cellsdev-2-eu-central-1a-2
    region: eu-central-1
    version: '1.18'
  nodeGroups:
    - ami: auto-ssm
      availabilityZones:
        - eu-central-1a
      desiredCapacity: 1
      iam:
        instanceRoleARN: <custom_role>
      instancesDistribution:
        instanceTypes:
          - c5.xlarge
          - c5a.xlarge
        onDemandPercentageAboveBaseCapacity: 0
        spotAllocationStrategy: capacity-optimized
      kubeletExtraConfig:
        kubeReserved:
          cpu: 50m
          memory: 500Mi
        kubeReservedCgroup: /kube-reserved
        systemReserved:
          cpu: 50m
          memory: 500Mi
      labels:
        role: ingress
      maxSize: 20
      minSize: 1
      name: nodes-ingress-abcdef
      privateNetworking: true
      securityGroups:
        attachIDs: [-list-of-sg-ids]
        withShared: false
      ssh:
        allow: true
        enableSsm: true
        publicKeyPath: /eks/key.pub
      tags:
        k8s.io/cluster-autoscaler/cluster-name: owned
        k8s.io/cluster-autoscaler/enabled: 'true'
      taints:
        node-role.kubernetes.io/custom-role-2: :NoSchedule
      targetGroupARNs: [-list-of-tg-ARNs]
  vpc:
    clusterEndpoints:
      privateAccess: true
      publicAccess: true
    publicAccessCIDRs: [-list-of-CIDRs]
    subnets:
      private:
        eu-central-1a:
          id: subnet-0123456789
        eu-central-1b:
          id: subnet-9876543210
        eu-central-1c:
          id: subnet-0123456789
      public:
        eu-central-1a:
          id: subnet-1357924680
        eu-central-1b:
          id: subnet-2468013579
        eu-central-1c:
          id: subnet-0864297531
```

**Logs**

**Anything else we need to know?**

We're using a docker image based on `weaveworks/eksctl:0.33.0-rc.0`

**Versions**

```
$ eksctl version
0.33.0-rc.0
$ kubectl version
v1.17.12
```
