### ISSUE TITLE
eksctl update addons supports specifying `latest` version

### ISSUE THREAD

**Issue by aclevername** [weaveworks/eksctl#3573]
**What feature/behavior/change do you want?**
I want to be able to specify updating my addon to the latest version
CLI:
`eksctl update addon --name vpc-cni --version latest`
Config file:
```
cat cluster.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: cluster-25
  region: us-west-2
  version: "1.18"

iam:
  withOIDC: true

addons:
- name: vpc-cni
  version :latest
  
eksctl update addon -f cluster.yaml
```

**Why do you want this feature?**
so I can easily keep my addon up to date
