### ISSUE TITLE
IRSA wellknown policies do not support EBS and EFS controller policies 

### ISSUE THREAD

**Issue by suman10586** [weaveworks/eksctl#3614]
**What were you trying to accomplish?**
Trying to use EBS and EFS controller policies with IRSA using eksctl config file

**What happened?**
Getting error:  error unmarshaling JSON: while decoding JSON: json: unknown field "ebsCSIController"

**How to reproduce it?**

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test
  region: us-east-1
  version: '1.18'

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: aws-load-balancer-controller
      namespace: kube-system
    wellKnownPolicies:
      awsLoadBalancerController: true
  - metadata:
      name: ebs-csi-controller-sa
      namespace: kube-system
    wellKnownPolicies:
      ebsCSIController: true
 
managedNodeGroups:
  - name: test-workers
    instanceType: c5.2xlarge
    desiredCapacity: 2
    maxSize: 3
    privateNetworking: true
    iam:
      withAddonPolicies:
        ebs: true
        efs: true
    ssh:
      allow: true
    volumeSize: 200
    volumeName: /dev/xvda
```

**Logs**

```
Error: loading config file "eksctltest.yaml": error unmarshaling JSON: while decoding JSON: json: unknown field "ebsCSIController"
```
**Anything else we need to know?**
Looking at the Feature only these wellknown policies are supported as of now, When we can expect to have more policies added?

```
 "imageBuilder",
 "autoScaler",
 "awsLoadBalancerController",
 "externalDNS",
 "certManager"
```

**Versions**

```
eksctl version
0.45.0
kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T21:15:16Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
```
