### ISSUE TITLE
refactor status fields

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#363]
We have a few status fields, those should go under `status`.

```
status:
  endpoint: "..."
  certificateAuthorityData: "..."
  arn: "..."
```
