### ISSUE TITLE
annotation in sa is not updated, is this the intended behavior?

### ISSUE THREAD

**Issue by cw-sakamoto** [weaveworks/eksctl#3645]
**What help do you need?**

If you run `create iamserviceaccount --override-existing-serviceaccounts` on a serviceaccount that already has a role listed in the annotation as shown below, the role in the annotation will not be updated.
Is this the intended behavior?

```
  kubectl get sa -n default eksctl-s3-readonly -o yaml | kubectl neat
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::234188972441:role/eksctl-eks-test-addon-iamserviceaccount-Role1-630H9YOYTW
  labels:
    app.kubernetes.io/managed-by: eksctl
  name: eksctl-s3-readonly
  namespace: default
secrets:
- name: eksctl-s3-readonly-token-zpfqq
```

```
% eksctl get iamserviceaccount --cluster eks119-sgskmt --profile sg-test-sso | grep eksctl-s3-readonly
default		eksctl-s3-readonly	arn:aws:iam::234188972441:role/eksctl-eks-test-addon-iamserviceaccount-Role1-1OV5TJSZST5ZU
```

The created role is `arn:aws:iam::234188972441:role/eksctl-eks-test-addon-iamserviceaccount-Role1-1OV5TJSZST5ZU`, but `arn:aws:iam::234188972441:role/eksctl-eks-test-addon-iamserviceaccount-Role1-630H9YOYTW` which was listed in sa's annottion, is still not updated.

```
% eksctl version
0.46.0
```
