### ISSUE TITLE
IRSA well known policies for Amazon EFS CSI dynamic provisioning 

### ISSUE THREAD

**Issue by ruzickap** [weaveworks/eksctl#3671]
**What feature/behavior/change do you want?**
It would be handy to have IRSA well known policies for "Amazon EFS CSI dynamic provisioning" describe here: https://aws.amazon.com/blogs/containers/introducing-efs-csi-dynamic-provisioning/

Policy file: https://raw.githubusercontent.com/kubernetes-sigs/aws-efs-csi-driver/v1.2.0/docs/iam-policy-example.json

Currently I need to configure eksctl this way to have it enabled:

```yaml
iam:
  serviceAccounts:
    - metadata:
        name: efs-csi-controller-sa
        namespace: kube-system
      attachPolicy:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Action:
          - elasticfilesystem:DescribeAccessPoints
          - elasticfilesystem:DescribeFileSystems
          Resource: "*"
        - Effect: Allow
          Action:
          - elasticfilesystem:CreateAccessPoint
          Resource: "*"
          Condition:
            StringLike:
              aws:RequestTag/efs.csi.aws.com/cluster: true
        - Effect: Allow
          Action: elasticfilesystem:DeleteAccessPoint
          Resource: "*"
          Condition:
            StringEquals:
              aws:ResourceTag/efs.csi.aws.com/cluster: true
```

I would be nice to have well known policies instead for example:

```yaml
iam:
  serviceAccounts:
    - metadata:
        name: efs-csi-controller-sa
        namespace: kube-system
      wellKnownPolicies:
        efsCSIController: true
```

**Why do you want this feature?**

To make it easier to configure Amazon EFS CSI dynamic provisioning.
