### ISSUE TITLE
Support Bottlerocket as a node AMI family for managed nodegroups

### ISSUE THREAD

**Issue by cPu1** [weaveworks/eksctl#3709]
Managed nodegroups using Bottlerocket can be created by supplying a custom AMI and a bootstrap script, e.g.,:

```yaml
managedNodeGroups:
  - name: x86-bottlerocket-mng
    ami: ami-0acfc3fffaaa4e015
    instanceType: m5.large
    minSize: 1
    desiredCapacity: 2
    maxSize: 3
    privateNetworking: true
    disableIMDSv1: true
    volumeSize: 50
    labels: { role: x86-bottlerocket-mng }
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
    overrideBootstrapCommand: |
      [settings.kubernetes]
      api-server = "https://redacted.gr7.us-east-1.eks.amazonaws.com"
      cluster-certificate = "redacted"
      cluster-name = "testing-cluster"
```

Unmanaged nodegroups, however, support this via the `amiFamily` field. 

Add native support for Bottlerocket for managed nodegroups so that they can be created by setting `amiFamily` to `Bottlerocket`.
