### ISSUE TITLE
Setup aws-load-balancer-controler prerequisites via eksctl

### ISSUE THREAD

**Issue by steffakasid** [weaveworks/eksctl#3714]
I try to setup my cluster with [aws-load-balancer-controler](https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html). The AWS documentation describes that it would be necessary to attach `curl -o iam_policy_v1_to_v2_additional.json https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.1.3/docs/install/iam_policy_v1_to_v2_additional.json`. I first thought, that this would be done with `awsLoadBalancerController: true` but this only seems to enable the use of the oidc provider.

My current IAM configuration looks like:
```
iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      wellKnownPolicies:
        awsLoadBalancerController: true
```

**What help do you need?**
I'm just wondering what would be the best way to enable my cluster to create the LoadBalancer Resources in AWS? Do I need to create the mentioned policy? If yes: I think I could create and attach the policy via attachPolicy? What would be the recommended way to setup aws-load-balancer-contoler (or the prerequisites via eksctl)?

Regards
Steffen
