### ISSUE TITLE
Automatically add cluster-autoscaler ASG tags without IAM and for `node-template` labels/taints

### ISSUE THREAD

**Issue by cwwarren** [weaveworks/eksctl#3717]
**What feature/behavior/change do you want?**

`eksctl` should automatically generate the appropriate cluster-autoscaler ASG tags for unmanaged node groups.

1. The core cluster/enable flag tags should not be dependent on IAM roles granted. For example we manage cluster-autoscaler's access through IRSA and disable IMDS for all pods.
2. Label/taints should be automatically translated to cluster-autoscaler ASG tags.

Here is an example of the relevant part of our Linux/ARM64 node group configuration.

```
  labels:
    purpose: ci
  taints:
    dedicated: ci:NoSchedule
  tags:
    k8s.io/cluster-autoscaler/enabled: 'true'
    k8s.io/cluster-autoscaler/cluster-name: owned
    k8s.io/cluster-autoscaler/node-template/label/kubernetes.io/os: linux
    k8s.io/cluster-autoscaler/node-template/label/kubernetes.io/arch: arm64
    k8s.io/cluster-autoscaler/node-template/label/purpose: ci
    k8s.io/cluster-autoscaler/node-template/taint/dedicated: "ci:NoSchedule"
```

Ideally, the following would happen:

```
# These are automatically generated for node groups if cluster-autoscaler IAM access is enabled.
# We do not use the autoScaler IAM, so ideally there would be a separate flag (or by default) for these tags
# without the IAM part.
  tags:
    k8s.io/cluster-autoscaler/enabled: 'true'
    k8s.io/cluster-autoscaler/cluster-name: owned
```

```
# These labels should automatically be translated into the following cluster-autoscaler tags so they do not
# have to be defined twice manually (or use another layer to generate the YAML).
# Ideally this would also generate "known" default labels such as os and arch which can be safely assumed
# from the configuration.
  labels:
    purpose: ci
  tags:
    k8s.io/cluster-autoscaler/node-template/label/kubernetes.io/os: linux
    k8s.io/cluster-autoscaler/node-template/label/kubernetes.io/arch: arm64
    k8s.io/cluster-autoscaler/node-template/label/purpose: ci
```

```
# These taints should automatically be translated into the following cluster-autoscaler tags 
  taints:
    dedicated: ci:NoSchedule
  tags:
    k8s.io/cluster-autoscaler/node-template/taint/dedicated: "ci:NoSchedule"
```

**Why do you want this feature?**

We run a matrix of scale-to-zero unmanaged spot node groups for CI and workflow jobs. Each of these has to have cluster-autoscaler node-template tags applied manually for scale-to-zero to function correctly and it would reduce configuration if eksctl generated these.
