### ISSUE TITLE
self managed group via eksctl

### ISSUE THREAD

**Issue by stela-leon** [weaveworks/eksctl#3769]
Hey there,

I am trying to create a self managed nodegroup via eksctl(0.51) as a workaround to support windows nodes. I have a kubernetes cluster running in my backend running linux nodes only. 

What I did was to enable windows successfully like this:

`eksctl utils install-vpc-controllers --cluster ${data.aws_eks_cluster....name} --approve`

Then I was trying to create a nodegroup  following the provided documentation 
`"eksctl create nodegroup --region eu-central-1 --cluster ${data.aws_eks_cluster.....name} --name ng-windows --node-type t2.large --nodes 2 --nodes-min 1 --nodes-max 2 --node-ami-family WindowsServer2019FullContainer" `. 

Unfortunately this fails with:  

`Error: loading VPC spec for cluster "data-ingestion-staging": VPC configuration required for creating nodegroups on clusters not owned by eksctl: vpc.subnets, vpc.id, vpc.securityGroup` either from command line or local-exec provisioner (in terraform). 

My kube cluster is created via terraform and it has a VPC with 2 subnets in eu-central-1 zone (the VPC is not default).

Any information would be of great help, 
Meanwhile I will continue bashing my head against the wall,
Thanks

**Comment by stela-leon** [comment]
hi thank you for your answer. This fails from the command line too, can you please tell me how I can run this via command line?

**Comment by cPu1** [comment]
>How can one pass the vpc to eksctl nodegroup creation command,

You can set the VPC in a ClusterConfig file and pass it as `eksctl create nodegroup -f config.yaml`. 

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster
  region: us-west-2

vpc:
  id: "vpc-11111"
  subnets:
    private:
      us-west-2a:
          id: "subnet-id"
    public:
      us-west-2a:
          id: "subnet-id"
nodeGroups:
  - name: ng-1
```

>as per documentation https://docs.aws.amazon.com/eks/latest/userguide/launch-windows-workers.html this is not required.

It's not required if the cluster was created with eksctl.
