### ISSUE TITLE
attachPolicyARNs without default policies breaks install

### ISSUE THREAD

**Issue by Morriz** [weaveworks/eksctl#3800]
**What were you trying to accomplish?**

Installing using a config file that specifies `attachPolicyARNs`.

**What happened?**

This breaks if the default policies (as described in the bottom of this doc: https://eksctl.io/usage/iam-policies/#attaching-policies-by-arn) are not provided.

But now my real problem is with the lack of eksctl NOT providing those in the installer when the docs say those MUST be provided. Why leave this to the user? What is the rationale? Can this be abstracted away for us?

**How to reproduce it?**

```yaml
---
# Source: eks-template/templates/helm-cluster.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dev
  region: eu-central-1
  version: "1.19"
managedNodeGroups:
  - name: ng-default
    availabilityZones: [eu-central-1a,eu-central-1b,eu-central-1c]
    labels:
      role: worker
      # EC2 tags required for cluster-autoscaler auto-discovery
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/dev: "owned"
    tags:
      nodegroup-role: worker
    instanceType: c5.xlarge
    minSize: 3
    maxSize: 7
    volumeSize: 100
    iam:
      attachPolicyARNs:
        # - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        # - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        # - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        # - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
        - arn:aws:iam::0123456789:policy/custom-pol
      withAddonPolicies:
        externalDNS: true
        certManager: true
        autoScaler: true
```

The node group instances show errors about CNI not working, probably because those policies were commented out.

**Versions**
$ eksctl version 0.52.0
$ kubectl version 1.19
```
