### ISSUE TITLE
When using a pre-existing VPC, a pre-existing security group, and an unmanaged Windows nodeGroup, the CloudFormation Stack for the Windows NodeGroup creates a security group with the same ID as the pre-existing security group, replacing its settings

### ISSUE THREAD

**Issue by kevin-lindsay-1** [weaveworks/eksctl#3811]
**What were you trying to accomplish?**

Creating a cluster with the following requirements:
1. Use a pre-existing VPC, subnets, and security groups (luckily, I happen to be testing this behavior before trying to apply this to a production VPC)
2. Have the VPC use a private endpoint only
3. Use an AWS VPN Client endpoint to reach the VPC and the k8s control plane

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: <cluster-name>
  region: us-east-1
  version: '1.20'

secretsEncryption:
  keyARN: <key>

vpc:
  id: <pre-existing VPC>
  subnets:
    private:
      <pre-existing subnets>
    public:
      <pre-existing subnets>
  securityGroup: <pre-existing SG ID> # not an ARN
  clusterEndpoints:
    privateAccess: true
    publicAccess: false

addons:
- name: coredns
  version: v1.8.3-eksbuild.1
- name: kube-proxy
  version: v1.20.4-eksbuild.2
- name: vpc-cni
  version: v1.7.10-eksbuild.1

managedNodeGroups:
- name: linux
  amiFamily: AmazonLinux2
  ...
  iam:
    instanceRoleARN: <node-role>

nodeGroups:
- name: windows
  amiFamily: WindowsServer2019FullContainer
  ...
  iam:
    instanceRoleARN: <node-role>
```

`eksctl --profile=<profile-name> create cluster -f <cluster-name>.yaml --install-vpc-controllers`

**What happened?**

Most everything went off without a hitch, but specifically when creating the Windows NodeGroup, the rules for allowing to communicate with the control plane _override_ the pre-existing rules in the Security Group, specifically it behaves as a `replace`, not an `add`. This appears to be due to the `iam.securityGroup` parameter for some reason treating that as a _desired_ security group, rather than a _referenced_ security group.

What happened to me when testing this was that it completely removed outbound rules outside of the ones related to Windows communicating with the control plane, which then immediately caused the cluster to lose network access. I've tested this exact behavior about 10 times now in order to pinpoint the exact cause.

**How to reproduce it?**

The steps listed above should be enough to go off of; please let me know if not.

**Logs**

**Anything else we need to know?**

Running on MacOS, latest.

**Versions**

```
$ eksctl version
0.52.0

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:11:29Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-eks-6b7464", GitCommit:"6b746440c04cb81db4426842b4ae65c3f7035e53", GitTreeState:"clean", BuildDate:"2021-03-19T19:33:03Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by kevin-lindsay-1** [comment]
I see my insanely long title and I feel no regrets. Some shame, but no regrets.

**Comment by Callisto13** [comment]
Thanks for the detailed repro @kevin-lindsay-1, we can forgive you for the long title 😉 .

Don't suppose you had ever tried this with an earlier version? No worries if not, just curious if this is a new thing which broke or if it has always been like this.

> This appears to be due to the iam.securityGroup parameter for some reason treating that as a desired security group, rather than a referenced security group.

Just confirming did you mean `vpc.securityGroup` not `iam`?

**Comment by kevin-lindsay-1** [comment]
> Don't suppose you had ever tried this with an earlier version?

I only tested it on `0.52.0`, as I just started using it and have no other baseline. As far as I know, it's not a regression.

> Just confirming did you mean vpc.securityGroup not iam?

I think you're right.

**Comment by Skarlso** [comment]
# Initial investigation for broader reproducing steps

<img width="390" alt="Screenshot 2021-07-08 at 15 52 43" src="https://user-images.githubusercontent.com/182850/124933959-989f4d80-e004-11eb-84af-30858aafa9e6.png">

Using an existing vpc with subnets and a security group with the following configuration:

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-overwriting
  region: us-west-2
  version: '1.20'

vpc:
  id: vpc-0af9f9bdf9623ecc5
  securityGroup: sg-0f615c936eb08b668
  subnets:
    private:
      test-overwrite-1:
        id: subnet-0bd09a3712e886998
      test-overwrite-2:
        id: subnet-0d8d04c4087d7fb09
  clusterEndpoints:
    privateAccess: true
    publicAccess: false
	
  
addons:
- name: coredns
  version: v1.8.3-eksbuild.1
- name: kube-proxy
  version: v1.20.4-eksbuild.2
- name: vpc-cni
  version: v1.7.10-eksbuild.1
```

Trying to not care about nodegroups for a bit.

This created a separate security group and added that to the cluster security group and additional security group correctly. Going for the narrower case now with unmanaged nodegroup but doesn't matter what's the OS.

**Comment by Skarlso** [comment]
@kevin-lindsay-1 quick question... At what point did you notice that it overwrote that security group? Was it immediately or only after a couple minutes when it started to spin up the cluster?

**Comment by kevin-lindsay-1** [comment]
@Skarlso pretty sure it was effectively immediate.

I was using unmanaged windows node groups, which requires special sg entries, which I think is where the problem may be coming from; I think the portion of the CFN output json/yaml for the sg entries for the windows node groups are accidentally creating a new sg with the same name as the one that exists, rather than referencing and adding rules.

**Comment by Skarlso** [comment]
Thanks for the extra info!

**Comment by Skarlso** [comment]
@kevin-lindsay-1 Just to clarify... It didn't create a cluster security group and you didn't have your own security group as `Additional Security Group`? But it only changed your SG right away after hitting create?

**Comment by Skarlso** [comment]
@kevin-lindsay-1 Hi. :) 

So... I tried reproducing this. My current eksctl version:

```
eksctl version
0.57.0-dev+eadbb9b7.2021-07-08T12:01:58Z
```

I'm using a clean build, but it's 2 version after yours. I couldn't notice any commits which should have influenced this. This is the config I was using:

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-overwriting-5
  region: us-west-2
  version: '1.20'

addons:
- name: coredns
  version: v1.8.3-eksbuild.1
- name: kube-proxy
  version: v1.20.4-eksbuild.2
- name: vpc-cni
  version: v1.7.10-eksbuild.1

vpc:
  id: vpc-0af9f9bdf9623ecc5
  securityGroup: sg-0f615c936eb08b668
  subnets:
    private:
      us-west-2b:
        id: subnet-0bd09a3712e886998
      us-west-2a:
        id: subnet-0d8d04c4087d7fb09

managedNodeGroups:
  - name: linux-ng
    amiFamily: AmazonLinux2
    instanceType: t2.large
    minSize: 2
    maxSize: 3

nodeGroups:
  - name: windows-ng
    amiFamily: WindowsServer2019FullContainer
    minSize: 2
    maxSize: 3
```

My original security group was untouched but added as an additional security group to my cluster:

<img width="301" alt="Screenshot 2021-07-09 at 12 23 10" src="https://user-images.githubusercontent.com/182850/125063976-6e0ace80-e0b0-11eb-99a0-ae7284a4dea3.png">

This is the command I run:

```
 eksctl create cluster -f cluster.yaml  --install-vpc-controllers
```

I didn't use a `--profile` but that shouldn't be a problem, unless you think otherwise.

Would you mind trying the same thing with the latest eksctl please to see if there is something I'm missing? Or some kind of setting I'm missing maybe?

Thanks!
