### ISSUE TITLE
Managed nodegroups with bottlerocket AMI are failing

### ISSUE THREAD

**Issue by rverma-nsl** [weaveworks/eksctl#3812]
When we have a policy for strict ebs encryption, 

**What were you trying to accomplish?**
Create a managed nodegroups with taints and encrypted volume and amiFamily bottlerocket. 

**What happened?**
we observe that nodes are not coming up and its fail to launch the instance. On further analysis it was observed that, since bottlerocket uses 2 volume mounts , the default 2GB volume is no longer encrypted i.e /dev/xvda & not included in launch template too. This causes failure.

**How to reproduce it?**
Enforce a scp to deny creation of instance without encryption.
Observer managed nodegroup are not coming up.

If using a config file, include it here, removing any sensitive information!
```
managedNodeGroups:
  - name: system-120-0
    instanceType: "a1.xlarge"
    desiredCapacity: 1
    minSize: 1
    maxSize: 3
    volumeType: gp3
    volumeSize: 10
    volumeEncrypted: true
    volumeKmsKeyID: uuuuu-uuuu-iiiii-ddddd
    privateNetworking: true
    amiFamily: Bottlerocket
    disableIMDSv1: true
    iam:
      instanceRoleARN: arn:aws:iam::xxx:role/EKS-Default-SSM-AD-Role
    labels:
      workload: system
      eks.amazonaws.com/compute-type: ec2
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/services: "owned"
      k8s.io/cluster-autoscaler/node-template/label/workload: system
      k8s.io/cluster-autoscaler/node-template/taint/CriticalAddonsOnly: NoSchedule
    taints:
      - key: "CriticalAddonsOnly"
        value: "true"
        effect: "NoSchedule"
```

**Versions**
```
$ eksctl version : 53-rc
$ kubectl version: 1.20
```
