### ISSUE TITLE
maxPodsPerNode does not work

### ISSUE THREAD

**Issue by bitva77** [weaveworks/eksctl#3818]
**What were you trying to accomplish?**

Trying to increase the number of pods running on a node

**What happened?**

I set `maxPodsPerNode: 110` when creating a `t3.medium` nodegroup.

We have the Weave CNI installed (ripped out the crappy AWS CNI)

**How to reproduce it?**

Create a nodegroup like this:

```
  - name: eks-us-west-2-node-group-rabbitmq-medium-v1
    labels:
      type: medium
      workload: rabbitmq
    taints:
      dedicated: rabbitmq:NoSchedule
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    instanceType: t3.medium
    iam:
      withAddonPolicies:
        cloudWatch: true
        ebs: true
    privateNetworking: true
    tags:
      Environment: UAT
    disableIMDSv1: true
    maxPodsPerNode: 110
    kubeletExtraConfig:
      kubeReserved:
        cpu: "300m"
        memory: "300Mi"
        ephemeral-storage: "1Gi"
      kubeReservedCgroup: "/kube-reserved"
      systemReserved:
        cpu: "300m"
        memory: "300Mi"
        ephemeral-storage: "1Gi"
      evictionHard:
        memory.available: "200Mi"
        nodefs.available: "10%"
```

Then get the node:  `kubectl get nodes -l workload=rabbitmq -o yaml` and observe the capacity is still at 17:

```
  status:
    addresses:
    - address: 10.235.245.153
      type: InternalIP
    - address: ip-10-235-245-153.us-west-2.compute.internal
      type: Hostname
    - address: ip-10-235-245-153.us-west-2.compute.internal
      type: InternalDNS
    allocatable:
      attachable-volumes-aws-ebs: "25"
      cpu: 1400m
      ephemeral-storage: "75150584500"
      hugepages-1Gi: "0"
      hugepages-2Mi: "0"
      memory: 3148920Ki
      pods: "17"
    capacity:
      attachable-volumes-aws-ebs: "25"
      cpu: "2"
      ephemeral-storage: 83873772Ki
      hugepages-1Gi: "0"
      hugepages-2Mi: "0"
      memory: 3968120Ki
      pods: "17"
```

**Logs**

**Anything else we need to know?**

**Versions**

```
$ eksctl version
$ kubectl version
```
eksctl version: `0.49.0`
kubernetes version:  `Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.8-eks-96780e"`
