### ISSUE TITLE
Add additional VPC subnets  for nodegroups after cluster creation

### ISSUE THREAD

**Issue by patstrom** [weaveworks/eksctl#3824]
**What feature/behavior/change do you want?**

AWS explicitly [recommends](https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html) keeping a set of small subnets associated with the EKS cluster when creating it and launching all worker nodes and potential load balancer in separate subnets.

From my understanding this is not what eksctl currently does when setting up.

My request is for eksctl to follow the AWS recommended VPC considerations and create clear distinctions between the subnets dedicated to the cluster itself and the subnets dedicated to worker groups and load balancers. A quick potential example I made in an [issue comment](https://github.com/weaveworks/eksctl/issues/3191#issuecomment-797463007) that represents the general idea can be seen below

```yaml
vpc:
  # These are the cluster subnets and should essentially only support EKS managed ENIs. I.e. be `/28` masked and not necessarily manually managed at all. 
  # I guess these don't need to be under `vpc`, but should probably be under `clusterSubnets` .
  subnets:
    private:
      private-one:
        id: whatever
    
# These are the subnets you should run your nodegroups in. They should be separate from the cluster subnets.
nodeGroupSubnets:
  private:
    private-one:
      id: whatever
  # These are the ones we launch loadbalancers in
  public:
    public-one:
      id: whatever
```

The subnets specified during cluster creation and the subnets that runs node groups and load balancer are fundamentally different and should be treated as such. The idea is then that by specifying the subnets in the `cluster.yaml` eksctl can ensure that they have the correct tags (if applicable) for the cluster and allows you to specify them when creating node groups, but otherwise have no specific requirements from eksctl's point of view.

**Why do you want this feature?**

When faced with the problem of running out of IP addresses in the subnets specified in the `cluster.yaml` I wanted to add new, larger subnets and add them to `cluster.yaml` so I could launch new node groups in those. This isn't something [that is supported](https://github.com/weaveworks/eksctl/issues/3191#issuecomment-797450936) since eksctl creates a large meaning behind the subnets that are first specified during cluster creation. 

Other users have faced [similar issues](https://github.com/weaveworks/eksctl/issues/3432).

In general, it also gives a lot more flexibility if subnets can be added/removed in a more dynamic fashion. For example if some node groups should join an existing cluster but have different routing rules. Then one could simply create a new subnet with an appropriate route table and create the nodegroup in that subnet.
