### ISSUE TITLE
Cannot able to create cluster with KubernetesNetworkConfig ServiceIP CIDR

### ISSUE THREAD

**Issue by vmpowercli** [weaveworks/eksctl#3838]
**What were you trying to accomplish?**
Creating Cluster with ServiceIP CIDR and it wont work
```
KubernetesNetworkConfig:
    ServiceIpv4Cidr: 172.25.0.0/23
```

**What happened?**
EKSCTL created cluster with CIDR `172.20.0.0/16`

**How to reproduce it?**

Created a Config FIle and added `KubernetesNetworkConfig:     ServiceIpv4Cidr: 172.25.0.0/23`
Ran `eksctl create cluster -f configfile`

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

cloudWatch:
    clusterLogging:
        enableTypes: ["*"]

KubernetesNetworkConfig:
    ServiceIpv4Cidr: 172.25.0.0/23

metadata:
    name: xxxxxxxxxx
    region: us-east-1
vpc:
  subnets:
    private:
      us-east-1a: {id: xxxxxxx}
      us-east-1b: {id: xxxxxxx}
```
```
eksctl version 0.53.0
kubectl version 1.19
```
