### ISSUE TITLE
InsufficientCapabilitiesException when trying to upgrade cluster (originally created with CLI version v0.34.0) with a newer CLI version (v0.53.0)

### ISSUE THREAD

**Issue by ben-mccown** [weaveworks/eksctl#3846]
**What were you trying to accomplish?**

I have existing eksctl clusters deployed with version v0.34.0. If I am following the Amazon docs which mention updating the CLI to version v0.53.0 or newer (see link at [1], step 4) for a cluster upgrade, I experience the following problem.

[1] https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html#update-existing-cluster : Updating a cluster - To update the Kubernetes version for your Amazon EKS cluster 

```
$ eksctl upgrade cluster --name test-upgrade --region us-east-2 --approve

2021-06-11 11:43:14 [ℹ]  waiting for requested "VersionUpdate" in cluster "test-upgrade" to succeed
2021-06-11 11:43:33 [ℹ]  waiting for requested "VersionUpdate" in cluster "test-upgrade" to succeed
2021-06-11 11:43:33 [✔]  cluster "test-upgrade" control plane has been upgraded to version "1.18"
2021-06-11 11:43:33 [ℹ]  you will need to follow the upgrade procedure for all of nodegroups and add-ons
2021-06-11 11:43:34 [ℹ]  re-building cluster stack "eksctl-test-upgrade-cluster"
2021-06-11 11:43:34 [ℹ]  updating stack to add new resources [PolicyCloudWatchMetrics PolicyELBPermissions ServiceRole] and outputs []
Error: creating ChangeSet "eksctl-update-cluster-1623429814" for stack "eksctl-test-upgrade-cluster": InsufficientCapabilitiesException: Requires capabilities : [CAPABILITY_IAM]
        status code: 400, request id: 0c405538-567c-4062-964c-2d149cf03f67
```

**How to reproduce it?**

Cluster Config YAML

```YAML
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-upgrade
  region: us-east-2
  version: "1.17"

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

iam:
  serviceRoleARN: arn:aws:iam::012345678912:role/EKS-Service-Role
  
managedNodeGroups:
  - name: workers
    instanceType: m4.large
    amiFamily: AmazonLinux2
    desiredCapacity: 1
    availabilityZones: ["us-east-2a"]
    volumeSize: 100
    volumeType: gp2
    volumeEncrypted: true
    privateNetworking: true
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess
      withAddonPolicies:
        autoScaler: true
        imageBuilder: true
```

EKS-Service-Role has the following policies attached.

AmazonEKSClusterPolicy
AmazonEC2ContainerRegistryFullAccess
AmazonEKSServicePolicy

EKS-Service-Role Trust Relationship

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "eks.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```

Deploy the test cluster using eksctl version 0.34.0 (had the binary in my local folder)

```
./eksctl-v0.34.0 create cluster -f cluster-config.yaml
```

Wait for it to deploy. Then try and upgrade the cluster using v0.53.0

```
./eksctl-v0.53.0 upgrade cluster --name test-upgrade --region us-east-2 --approve
```

This will consistently reproduce the issue.

**Anything else we need to know?**

I have identified why this happens. We see in pkg/cfn/manager/api.go that the doCreateChangeSetRequest function that the capabilities are passed in as an argument for the function.

https://github.com/weaveworks/eksctl/blob/5cf431c8754e05e08eef27dcd0864963ccbaf2fd/pkg/cfn/manager/api.go#L628-L648

We see on lines 253 and 249 that the capabilities being passed in for the change set creation are just the capabilities that have been read from the DescribeStack API call.

https://github.com/weaveworks/eksctl/blob/5cf431c8754e05e08eef27dcd0864963ccbaf2fd/pkg/cfn/manager/api.go#L249-L253

The issue is when creating the stack using eksctl v0.34.0 with the above cluster config, the stack doesn't have any Capabilities set. See the below output of my DescribeStacks CLI call from the start of the JSON response to the "Outputs" section.

```json
{
    "Stacks": [
        {
            "StackId": "arn:aws:cloudformation:us-east-2:012345678912:stack/eksctl-test-upgrade-cluster/ece54de0-cac9-11eb-86d4-065d87e8b934",
            "StackName": "eksctl-test-upgrade-cluster",
            "Description": "EKS cluster (dedicated VPC: true, dedicated IAM: false) [created and managed by eksctl]",
            "CreationTime": "2021-06-11T15:30:17.726000+00:00",
            "RollbackConfiguration": {},
            "StackStatus": "CREATE_COMPLETE",
            "DisableRollback": false,
            "NotificationARNs": [],
            "Outputs": [
                {
                    "OutputKey": "SubnetsPrivate",
                    "OutputValue": "subnet-07746523b018afbae,subnet-02b698d7e2a2f6958,subnet-0a676c71f098371fe",
                    "ExportName": "eksctl-test-upgrade-cluster::SubnetsPrivate"
                }
```

Now see the below response when calling DescribeStacks on the nodegroup stack with Capabilities set.

```json
{
    "Stacks": [
        {
            "StackId": "arn:aws:cloudformation:us-east-2:012345678912:stack/eksctl-test-upgrade-nodegroup-workers/a5c07f00-cacb-11eb-86d8-028ae676abae",
            "StackName": "eksctl-test-upgrade-nodegroup-workers",
            "Description": "EKS Managed Nodes (SSH access: false) [created by eksctl]",
            "CreationTime": "2021-06-11T15:42:37.345000+00:00",
            "RollbackConfiguration": {},
            "StackStatus": "CREATE_COMPLETE",
            "DisableRollback": false,
            "NotificationARNs": [],
            "Capabilities": [
                "CAPABILITY_IAM"
            ],
```

Since the cluster stack doesn't have Capabilities set, capabilities will not be set in the change set creation. However since the CLI version update to v0.53.0, when trying to update the cluster, it is attempting to create the resources PolicyCloudWatchMetrics, PolicyELBPermissions, and ServiceRole, which are obviously having issues since they are IAM resources and require Capabilities "CAPABILITY_IAM".

I am unclear whether this is an edge case with my current cluster-config.yaml or if this is a consistent issue no matter the config, but I am working on testing further to help identify an answer to this question as well.

**Versions**

```
$ ./eksctl-v0.34.0 version
0.34.0

$ ./eksctl-v0.53.0 version
0.53.0

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.16-eks-7737de", GitCommit:"7737de131e58a68dda49cdd0ad821b4cb3665ae8", GitTreeState:"clean", BuildDate:"2021-03-10T21:33:25Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
