### ISSUE TITLE
refactor ng.AllowSSH and related fields into a separate struct

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#386]
At the moment config file filed for SSH are very confusing.

We have `allowSSH`, `sshPublicKeyPath`, `sshPublicKeyName`, and `SSHPublicKey`.

https://github.com/weaveworks/eksctl/blob/ca30d425158b2106a00892cd084f489e09770158/pkg/apis/eksctl.io/v1alpha4/types.go#L361-L369

However, `sshPublicKeyName` and `SSHPublicKey` are effectively ignored, and the only two way you can make it work are these:
```YAML
nodeGroups:
- name: ng-1
  allowSSH: true # will use '~/.ssh/id_rsa'
- name: ng-2
  allowSSH: true
  sshPublicKeyPath: <localPathOrNameOfExistingKeyInEC2>
```

We should turn this to something like:
```YAML
- name: ng-1
  ssh:
    allow: true  # will use '~/.ssh/id_rsa'
- name: ng-2
  ssh:
    sshPublicKeyPath: <localPath>
- name: ng-3
  ssh:
    sshPublicKeyName: <NameOfExistingKeyInEC2>
- name: ng-4
  ssh:
    sshPublicKey: <PublicKeyBody>
```
