### ISSUE TITLE
Cluster DNS does not work with a non-default ServiceIPv4CIDR

### ISSUE THREAD

**Issue by cPu1** [weaveworks/eksctl#3864]
When a custom ServiceIPv4CIDR is set, DNS in the cluster does not work. 

Example config:
```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: test
  region: us-west-2
  version: "1.20"

kubernetesNetworkConfig:
  serviceIPv4CIDR: 172.16.0.0/12
```
