### ISSUE TITLE
What should be the DNS RR for the Load Balancer created by a LoadBalancer service?

### ISSUE THREAD

**Issue by victor-sudakov** [weaveworks/eksctl#3883]
Dear Colleagues,

I create an EKS Fargate cluster in 3 AZs. As written in https://docs.aws.amazon.com/eks/latest/userguide/network-load-balancing.html , I create 3 Elastic IPs and add their IDs to the service I want to publish:

```
apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: dev
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-eip-allocations: eipalloc-0262c16b92673238b,eipalloc-0034ca6db6a8ff872,eipalloc-0920531c430801d47
spec:
  selector:
    app: hello
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
```
When the service starts, after a while, it gets an external DNS name like k8s-dev-hello-91c86b3a33-6383019052ad2797.elb.us-east-2.amazonaws.com which resolves to one of the IPs.

**The question:**

Now I want my "www.domain.example" to point to this service. What value should I publish for the "www.domain.example" RR? I cannot make it a CNAME to k8s-dev-hello-91c86b3a33-6383019052ad2797.elb.us-east-2.amazonaws.com because each time I recreate the service in K8S, the elb name changes and I have to edit "www.domain.example" manually.

I cannot publish an A record with the elastic IPs either, because at any given moment, only 1 of the 3 EIPs is functional (forwards traffic to my service).

What is the correct way please?

**Comment by cPu1** [comment]
>Now I want my "www.domain.example" to point to this service. What value should I publish for the "www.domain.example" RR? I cannot make it a CNAME to k8s-dev-hello-91c86b3a33-6383019052ad2797.elb.us-east-2.amazonaws.com because each time I recreate the service in K8S, the elb name changes and I have to edit "www.domain.example" manually.

This is where [ExternalDNS](https://github.com/kubernetes-sigs/external-dns) comes into play. It dynamically updates records in Route 53 with the address assigned to `LoadBalancer` services. 

After installing ExternalDNS in your cluster, you would add an annotation to your service:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: dev
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-eip-allocations: eipalloc-0262c16b92673238b,eipalloc-0034ca6db6a8ff872,eipalloc-0920531c430801d47
    external-dns.alpha.kubernetes.io/hostname: domain.example.com.
spec:
  selector:
    app: hello
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
```

and ExternalDNS will ensure your Route 53 record is in sync with the LB's address.

**Comment by victor-sudakov** [comment]
> This is where [ExternalDNS](https://github.com/kubernetes-sigs/external-dns) comes into play. It dynamically updates records in Route 53 

Looks unnecessarily complicated to me. I've perused the aws.md tutorial. There are so many preconditions, so much manual work deploying it: creating policies and roles, applying manifests. Are you sure there is no simpler way? Does this ExternalDNS even work with Fargate-based clusters?

PS I've been told many times that K8S is there for us to concentrate on development rather than low-level things. And EKS (managed control plane!) should be even friendlier than a standard K8S installation. Don't you agree?

**Comment by victor-sudakov** [comment]
> Does this ExternalDNS even work with Fargate-based clusters?

I mean, Fargate nodes are tainted with `eks.amazonaws.com/compute-type=fargate:NoSchedule`, do ExternalDNS pods tolerate that? Those of cert-manager don't, so cert-manager does not even start on Fargate.

**Comment by cPu1** [comment]
>There are so many preconditions, so much manual work deploying it: creating policies and roles, applying manifests. Are you sure there is no simpler way?

eksctl helps with creating a role with the right policies for ExternalDNS (and other popular utilities) using IAM Roles for Service Accounts. 

```yaml
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster
  region: us-west-2

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: external-dns
      namespace: kube-system
    wellKnownPolicies:
      externalDNS: true
``` 

This creates a service account named `external-dns` that can be set in the `serviceAccountName` field in the Deployment for external-dns.

**Comment by cPu1** [comment]
>Fargate nodes are tainted with eks.amazonaws.com/compute-type=fargate:NoSchedule, do ExternalDNS pods tolerate that? 

Not by default, but you can configure the pods to tolerate it. If you're using the [Helm chart](https://github.com/bitnami/charts/tree/master/bitnami/external-dns), you can set the `tolerations` field.

**Comment by cPu1** [comment]
Here's a working values file for the ExternalDNS Helm chart that schedules pods on Fargate.

```yaml

# values.yaml
tolerations:
- key: eks.amazonaws.com/compute-type
  operator: Equal
  value: fargate
  effect: NoSchedule

serviceAccount:
  name: external-dns
  create: false

```

```shell
$ helm install external-dns bitnami/external-dns -f values.yaml --namespace=kube-system
```

**Comment by victor-sudakov** [comment]
> 
> This creates a service account named `external-dns` that can be set in the `serviceAccountName` field in the Deployment for external-dns.

How would this config translate info an eksctl command line? Is it the equivalent of `eksctl create iamserviceaccount` ?

**Comment by cPu1** [comment]
> > This creates a service account named `external-dns` that can be set in the `serviceAccountName` field in the Deployment for external-dns.
> 
> How would this config translate info an eksctl command line? Is it the equivalent of `eksctl create iamserviceaccount` ?

Yes, that's the correct command. If you're creating a new cluster, `eksctl create cluster` will also handle creating the service accounts.

**Comment by tanvp112** [comment]
> > There are so many preconditions, so much manual work deploying it: creating policies and roles, applying manifests. Are you sure there is no simpler way?
> 
> eksctl helps with creating a role with the right policies for ExternalDNS (and other popular utilities) using IAM Roles for Service Accounts.
> 
> ```yaml
> ---
> apiVersion: eksctl.io/v1alpha5
> kind: ClusterConfig
> 
> metadata:
>   name: cluster
>   region: us-west-2
> 
> iam:
>   withOIDC: true
>   serviceAccounts:
>   - metadata:
>       name: external-dns
>       namespace: kube-system
>     wellKnownPolicies:
>       externalDNS: true
> ```
> 
> This creates a service account named `external-dns` that can be set in the `serviceAccountName` field in the Deployment for external-dns.

please note apart from command line, you can also use eksctl with a config file like cPu1 demonstrated above. in this case, you do not need to call "eksctl create iamserviceaccount" for externalDNS anymore.

**Comment by victor-sudakov** [comment]
> please note apart from command line, you can also use eksctl with a config file like cPu1 demonstrated above. in this case, you do not need to call "eksctl create iamserviceaccount" for externalDNS anymore.
Do you mean that I can put all cluster creation, iamserviceaccount creation and everything into one eksctl YAML config? That's great news. Is there an example of such a catchall config so that I could adapt it to my needs?

**Comment by victor-sudakov** [comment]
I guess my question about DNS RRs has been answered, thank you @cPu1 and @tanvp112 !

**Comment by victor-sudakov** [comment]
> Is there an example of such a catchall config so that I could adapt it to my needs?

I see I can get this config more or less accurately by running `eksctl create cluster` with all my desired command-line options and 
`--dry-run` which will output the config.

**Comment by victor-sudakov** [comment]
> > 
> > iam:
> >   withOIDC: true
> >   serviceAccounts:
> >   - metadata:
> >       name: external-dns
> >       namespace: kube-system
> >     wellKnownPolicies:
> >       externalDNS: true
> > ```
> > This creates a service account named `external-dns` that can be set in the `serviceAccountName` field in the Deployment for external-dns.
> 
> please note apart from command line, you can also use eksctl with a config file like cPu1 demonstrated above. in this case, you do not need to call "eksctl create iamserviceaccount" for externalDNS anymore.


In this config sample, what is a wellKnownPolicy "externalDNS"? A standard (predefined) policy name? An arbitrary policy name? A policy eksctl will create for me with required statements? A policy I should create manually before running eksctl?

**Comment by cPu1** [comment]
> In this config sample, what is a wellKnownPolicy "externalDNS"? A standard (predefined) policy name? An arbitrary policy name? A policy eksctl will create for me with required statements? A policy I should create manually before running eksctl?

A role eksctl will create for you with the required policies.

**Comment by victor-sudakov** [comment]
> > In this config sample, what is a wellKnownPolicy "externalDNS"? A standard (predefined) policy name? An arbitrary policy name? A policy eksctl will create for me with required statements? A policy I should create manually before running eksctl?
> 
> A role eksctl will create for you with the required policies. You don't need to create it.

Where will eksctl take the definitions of the required policies? The config snippet above does not include any policy definition for the "externalDNS" policy (if this is a policy name).

**Comment by victor-sudakov** [comment]
@cPu1 For some reason I cannot make external-dns work even on an EC2-based cluster. I apply the Helm chart
`helm install extdnstest1 bitnami/external-dns --set provider=aws --namespace=kube-system`
and see that the pod is running
```
$ kubectl --namespace=kube-system get pods -l "app.kubernetes.io/name=external-dns,app.kubernetes.io/instance=extdnstest1"
NAME                                        READY   STATUS    RESTARTS   AGE
extdnstest1-external-dns-674b9975d4-5sjcs   1/1     Running   0          11m
```
But the DNS RRs are never created in Route53. In the pod's logs I see:

```
time="2021-07-01T08:26:08Z" level=error msg="records retrieval failed: failed to list hosted zones: AccessDenied: User: arn:aws:sts::586851294570:assumed-role/eksctl-test3-nodegroup-ng-1-NodeInstanceRole-MST53MSXJQVS/i-0046052a3619d2876 is not authorized to perform: route53:ListHostedZones\n\tstatus code: 403, request id: b1854770-b2f3-40b1-a421-c071dc58aed2"
time="2021-07-01T08:27:09Z" level=error msg="records retrieval failed: failed to list hosted zones: AccessDenied: User: arn:aws:sts::586851294570:assumed-role/eksctl-test3-nodegroup-ng-1-NodeInstanceRole-MST53MSXJQVS/i-0046052a3619d2876 is not authorized to perform: route53:ListHostedZones\n\tstatus code: 403, request id: 44a8fc76-ab92-464f-a014-4ab88e958474"
```

Is there something still wrong with the iam roles/permissions? Attached is my current cluster definition (the role ARN is not real).
[managed_clusterconfig.yaml.txt](https://github.com/weaveworks/eksctl/files/6746679/managed_clusterconfig.yaml.txt)

**Comment by gohmc** [comment]
You can find the IAM user created by eksctl and look at the policy associated; if they match the ExternalDNS required policy [here](https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/aws.md#iam-policy). If they don't, you can supply your own policy via [attachPolicy](https://github.com/weaveworks/eksctl/blob/main/examples/13-iamserviceaccounts.yaml).

**Comment by victor-sudakov** [comment]
Well, I had among other things:

```
iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: external-dns
      namespace: kube-system
    wellKnownPolicies:
      externalDNS: true
```

during cluster creation, so the external-dns role and policy should have been created and associated automatically.
