### ISSUE TITLE
Add tags configuration to created subnets

### ISSUE THREAD

**Issue by rothgar** [weaveworks/eksctl#3893]
**What feature/behavior/change do you want?**
In the [cluster config schema](https://eksctl.io/usage/schema/) it would be useful to have an option to add tags to a subnet on creation. Something like

```
vpc:
  subnets:
    tags:
      kubernetes.io/cluste/mine: true
```

This would allow for better subnet tracking and also help with issues like #3341 

**Why do you want this feature?**
Subnet tags are still needed for some controllers and it would be helpful to do it at provisioning time to avoid missing required settings for clusters and tracking changes in code.
