### ISSUE TITLE
The correct procedure to use K8S persistent volumes in EKS

### ISSUE THREAD

**Issue by victor-sudakov** [weaveworks/eksctl#3911]
Dear Colleagues,

The procedure for enabling the use of EBS volumes for EKS persistent volumes as described here: https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html - does it really have to be so complicated and manual? Or am I going the wrong path all the time?

I've been told that K8S lets you concentrate on development instead of the gory details of the platform. This does not seem to be the case with EKS, or am I following the wrong path? Please set me straight.

PS I've looked at the 06-csi-drivers.yaml example file but it's for nodegroups while I would like to use Fargate. Are there any more good examples or charts in any other place than the Github repo?

**Comment by Callisto13** [comment]
Hi @victor-sudakov thanks for asking. 

I believe you probably want to use EFS rather than EBS, since I don't think the EBS driver is supported on Fargate. https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html

Yeh it is all a bit elaborate, and I am afraid that `eksctl` doesn't have a nice one-command way of doing this.

We can make the first section of the procedure shorter. The "Create an IAM policy and role" part can be skipped by using the following configfile example:
```yaml
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: foobar
  region: us-west-2

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: cluster-efs
      namespace: kube-system
      labels: {aws-usage: "cluster-ops"}
    wellKnownPolicies:
      efsCSIController: true
    roleName: eksctl-cluster-efs-role
    roleOnly: false

fargateProfiles:
  - name: fp-default
    selectors:
      - namespace: default
      - namespace: kube-system
```
and then creating a cluster with `eksctl create cluster -f config.yaml`. This will create the policy and the role required (the fargate profile is just an example).

The rest I am afraid has to be completely manually outside of `eksctl`.

**Comment by victor-sudakov** [comment]
> I believe you probably want to use EFS rather than EBS, since I don't think the EBS driver is supported on Fargate. 

Thanks for pointing this out, perhaps this was the reason of this error? https://github.com/weaveworks/eksctl/issues/3912

I'll remake the cluster with EFS config and try again (though I don't particularly like EFS for its credit system).

> The rest I am afraid has to be completely manually outside of `eksctl`.

Is this https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html a valid document? Do I understand correctly that the configfile above will do the IAM part for me and I can start with the "Install the Amazon EFS driver" (Helm) step?

**Comment by Callisto13** [comment]
> perhaps this was the reason of this error? #3912

Possibly... although I would expect a different error, and that it would fail at different step. Note sure where the labels it is complaining about are.

> Is this https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html a valid document? Do I understand correctly that the configfile above will do the IAM part for me and I can start with the "Install the Amazon EFS driver" (Helm) step?

Yep, I just ran through it on my own cluster and it seems legit. And yes, if you use the config as a baseline example you can start at the "Install the Amazon EFS driver" step.

**Comment by victor-sudakov** [comment]
The examples/13-iamserviceaccounts.yaml gives a simpler role definition

```
 - metadata:
      name: efs-csi-controller-sa
      namespace: kube-system
    wellKnownPolicies:
      efsCSIController: true
```
Are your suggested additional roleName, roleOnly and labels parameters required for correct operation?
