### ISSUE TITLE
Only expose `maxUnavailable` and `maxUnavailablePercentage` fields of `updateConfig`

### ISSUE THREAD

**Issue by nikimanoledaki** [weaveworks/eksctl#3918]
As part of #3613, we want eksctl users to be able to handle parallel upgrades of nodegroups by specifying how many nodegroups can become unavailable using `maxUnavailable` and `maxUnavailablePercentage`. In the EKS API, the console, and our code, these fields belong to `updateConfig`. 

**Problem**
However, the current UX around `udpateConfig` is super confusing because it's actually referring to an **upgrade** config 🤯  We can't rename it to `upgradeConfig` because it would be different from the console. 

**Solution**
Let's not expose `updateConfig` to the user at all and only expose the fields `maxUnavailable` and `maxUnavailablePercentage` in the config file.
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-1
  region: us-west-2

nodeGroups:
  - name: ng-1
    maxUnavailable: 2 // or maxUnavailablePercentage: 80
```

This uses the same logic as the `scalingConfig` struct which only exposes its fields (`minSize`, `maxSize` and `desiredSize`) in the config file to the user.
