### ISSUE TITLE
[BUG] panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by petrukngantuk** [weaveworks/eksctl#3959]
**What were you trying to accomplish?**
```
 eksctl get nodegroup --cluster my-cluster-name
```

**What happened?**
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x103dd8f78]
```

**How to reproduce it?**

```
❯ eksctl get nodegroup --cluster my-cluster-name
2021-07-08 19:56:43 [ℹ]  eksctl version 0.55.0
2021-07-08 19:56:43 [ℹ]  using region us-west-2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x103dd8f78]
```

**Logs**

```
❯ eksctl get nodegroup --cluster my-cluster-name
2021-07-08 19:56:43 [ℹ]  eksctl version 0.55.0
2021-07-08 19:56:43 [ℹ]  using region us-west-2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x103dd8f78]

goroutine 1 [running]:
github.com/weaveworks/eksctl/pkg/actions/nodegroup.(*Manager).GetAll(0x140003e90e0, 0x14000807368, 0x104e9b3d8, 0x140004bbe40, 0x140003e90e0, 0x0)
	/private/tmp/eksctl-20210702-22790-1yuqrj8/pkg/actions/nodegroup/get.go:74 +0x538
github.com/weaveworks/eksctl/pkg/ctl/get.doGetNodeGroup(0x140008c1130, 0x140008aefa0, 0x140008064b0, 0x0, 0x0)
	/private/tmp/eksctl-20210702-22790-1yuqrj8/pkg/ctl/get/nodegroup.go:90 +0x2b4
github.com/weaveworks/eksctl/pkg/ctl/get.getNodeGroupCmd.func1(0x140008a5180, 0x1400068d900, 0x0, 0x2, 0x0, 0x0)
	/private/tmp/eksctl-20210702-22790-1yuqrj8/pkg/ctl/get/nodegroup.go:32 +0x8c
github.com/spf13/cobra.(*Command).execute(0x140008a5180, 0x1400068d8e0, 0x2, 0x2, 0x140008a5180, 0x1400068d8e0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x320
github.com/spf13/cobra.(*Command).ExecuteC(0x14000552f00, 0x1400060de20, 0x1, 0x14000b3ff60)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x258
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
	/private/tmp/eksctl-20210702-22790-1yuqrj8/cmd/eksctl/main.go:77 +0x3a4
```

**Anything else we need to know?**
OS : Macos Big Sur
Arch: darwin-arm64 (Apple Silicon M1)

**Versions**
```
❯ eksctl info
eksctl version: 0.55.0
kubectl version: v1.21.2
OS: darwin
```

**ClusterConfig**
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-cluster-name
  region: us-west-2
  version: "1.20"
  tags:
    project: myproject

vpc:
  clusterEndpoints:
    publicAccess:  true
    privateAccess: true
  publicAccessCIDRs: ["1.2.3.4/32","5.6.7.8/32"]
  subnets:
    public:
      us-west-2a:
        id: subnet-0fcbce7aXXXXXXXX9
      us-west-2b:
        id: subnet-08634a66YYYYYYYY3
      us-west-2c:
        id: subnet-0446d05aZZZZZZZZ2
iam:
  withOIDC: true

managedNodeGroups:
- name: ng-target
  amiFamily: Ubuntu2004
  instanceType: c5a.large
  minSize: 1
  maxSize: 10
  desiredCapacity: 1
  volumeSize: 64
  ssh:
    allow: true
    publicKeyPath: ./ng-target.pub
  labels:
    nodegroup-name: ng-target
  tags:
    nodegroup-name: ng-target
  iam:
    withAddonPolicies:
      imageBuilder: true
      autoScaler: true
      externalDNS: true
      certManager: true
      appMesh: true
      appMeshPreview: true
      ebs: true
      fsx: true
      efs: true
      albIngress: true
      xRay: true
      cloudWatch: true
    attachPolicyARNs:
    - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
    - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
    - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
- name: ng-monitoring
  amiFamily: Ubuntu2004
  instanceType: m5a.large
  minSize: 1
  maxSize: 5
  desiredCapacity: 1
  volumeSize: 64
  ssh:
    allow: true
    publicKeyPath: ./ng-monitoring.pub
  labels:
    nodegroup-name: ng-monitoring
  tags:
    nodegroup-name: ng-monitoring
  taints:
  - key: dedicated
    value: monitoring
    effect: NoSchedule
  iam:
    withAddonPolicies:
      imageBuilder: true
      autoScaler: true
      externalDNS: true
      certManager: true
      appMesh: true
      appMeshPreview: true
      ebs: true
      fsx: true
      efs: true
      albIngress: true
      xRay: true
      cloudWatch: true
    attachPolicyARNs:
    - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
    - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
    - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
```
