### ISSUE TITLE
Automatically create ASG tag from nodegroup's labels and taints

### ISSUE THREAD

**Issue by nikimanoledaki** [weaveworks/eksctl#3961]
### Background
The Autoscaling group (ASG) uses tags to detect and scale a nodegroup. Such tags are required for the ASG to scale a nodegroup from 0, for example if it was created with `desiredCapacity: 0`.

More context:
- #3793
- https://github.com/aws/containers-roadmap/issues/724#issuecomment-859948729
- #1481 
- #2263

### Problem
Currently, [as per the eksctl docs](https://eksctl.io/usage/autoscaling/#scaling-up-from-0), there is a bit of repetition happening in the config file when we define labels/taints and need them to be added as tags:
```    
nodeGroups:
  - name: ng1-public
    ...
    labels:
      my-cool-label: pizza
    taints:
      feaster: "true:NoSchedule"
    tags:
      k8s.io/cluster-autoscaler/node-template/label/my-cool-label: pizza
      k8s.io/cluster-autoscaler/node-template/taint/feaster: "true:NoSchedule"
```

### Proposed Solution
As suggested by @sammort  in https://github.com/weaveworks/eksctl/issues/3793#issuecomment-875470794, it would be great if the ASG tags were created automatically when labels and/or taints have been defined. 

There is a limit of maximum of 50 tags for an ASG, but there is a [proposal](https://github.com/kubernetes/autoscaler/blob/91bc8e3783aca9b1770675944da18b42ae19d96e/cluster-autoscaler/proposals/circumvent-tag-limit-aws.md) to change this for the Kubernetes cluster autoscaler. For the time being, from our side, we might want to validate that the number of labels, taints, and tags in a config are not greater than 50. Not sure if there is an error from EKS if the count is greater than 50 so this would be good to investigate too. 

Another thing to keep in mind is tag duplicates.
