### ISSUE TITLE
--instance-selector-gpus=0 option is not working correctly with eksctl

### ISSUE THREAD

**Issue by ashwinikumar-sa** [weaveworks/eksctl#3983]
**What were you trying to accomplish?**

eksctl create cluster --name my-cluster --managed --instance-selector-vcpus=8 --instance-selector-memory=32 --instance-selector-cpu-architecture=x86_64 **--instance-selector-gpus=0**

eksctl create cluster --name my-cluster --managed --instance-selector-vcpus=8 --instance-selector-memory=32 --instance-selector-cpu-architecture=x86_64 **--instance-selector-gpus=0 --dry-run**

**What happened?**

Getting GPU type instances despite of gpus=0 option

```yaml
 instanceSelector:
    cpuArchitecture: x86_64
    memory: "32"
    vCPUs: 8
  instanceTypes:
  - d3en.2xlarge
  - g4dn.2xlarge     # <-- GPU instance 
  - h1.2xlarge
  - m4.2xlarge
  - m5.2xlarge
  - m5a.2xlarge
  - m5ad.2xlarge
  - m5d.2xlarge
  - m5dn.2xlarge
  - m5n.2xlarge
  - m5zn.2xlarge
  - t2.2xlarge
  - t3.2xlarge
  - t3a.2xlarge
```

**How to reproduce it?**

**Logs**

**Anything else we need to know?**

**Versions**
eksctl version 0.57.0

```
$ eksctl info
eksctl version: 0.57.0
kubectl version: v1.18.12
OS: linux (Amazon Linux2)
```
