### ISSUE TITLE
Command write-kubeconfig still uses aws-iam-authenticator instead of AWS CLI v2

### ISSUE THREAD

**Issue by davivcgarcia** [weaveworks/eksctl#3999]
**What help do you need?**

Using `eksctl` version 0.57.0, I've noticed that `eksctl utils write-kubeconfig` generates a `kubeconfig` differently than `aws eks update-kubeconfig`. The first still uses `aws-iam-authenticator` helper, while the second is already using the native EKS `get-token` API.

To illustrate what I'm saying:

```bash
eksctl utils write-kubeconfig --cluster sandbox --region us-east-1 --profile dev
```

Creates:

```
(...)
users:
- name: 1626800257523602000@sandbox.us-east-1.eksctl.io
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - sandbox
      command: aws-iam-authenticator
      env:
      - name: AWS_STS_REGIONAL_ENDPOINTS
        value: regional
      - name: AWS_DEFAULT_REGION
        value: us-east-1
      - name: AWS_PROFILE
        value: dev
```

But:

```bash
aws eks update-kubeconfig --name sandbox --region us-east-1 --profile dev
```

Generates:

```
(...)
users:
- name: arn:aws:eks:us-east-1:403779000275:cluster/sandbox
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - sandbox
      command: aws
```

Why do we have this discrepancy between the tools? Do we have a roadmap to unify the behavior?
