### ISSUE TITLE
node-role labeling fails

### ISSUE THREAD

**Issue by hryamzik** [weaveworks/eksctl#4007]
I'm trying to apply node labels using the following configuration:

```yaml
  - name: test
    instanceType: m5.large
    minSize: 1
    maxSize: 2
    desiredCapacity: 2
    labels:
      role: test
      node-role.kubernetes.io/test: ok
```

According to #580 and #582 using `node-role` subdomain should the way to apply labels, however I still get a domain error:

```
AWS::EKS::Nodegroup/ManagedNodeGroup: CREATE_FAILED – "Label cannot contain reserved prefixes [kubernetes.io/, k8s.io/, eks.amazonaws.com/] (Service: AmazonEKS; Status Code: 400; Error Code: InvalidParameterException; Request ID: *** Proxy: null)"
```

Here's `eksctl` info:

```
eksctl version: 0.57.0
kubectl version: v1.21.2
OS: darwin
```
