### ISSUE TITLE
can't set instanceProfileARN for managed node groups

### ISSUE THREAD

**Issue by yashvardhan-kukreja** [weaveworks/eksctl#4009]
**What were you trying to accomplish?**
Trying to set `instanceProfileARN` under `managedNodeGroups[*].iam`.
The documentation of eksctl config file schema suggests that this should be possible to do under `managedNodeGroups` field as well.

**What happened?**
On executing `eksctl create nodegroup` command for my eksctl manifest, the following error came:
```sh
╰─ eksctl create nodegroup -f 1-17-nodes-managed.yaml --update-auth-configmap=false
Error: couldn't create cluster provider from options: instanceProfileARN is not supported for Managed Nodes (managedNodeGroups[0].instanceProfileARN)
```

**How to reproduce it?**
I used the following yaml
```yaml
---
    apiVersion: eksctl.io/v1alpha5
    kind: ClusterConfig
    metadata:
      name: test
      region: us-west-2
    managedNodeGroups:
      - name: test-1-17-infra-managed
        ami: ami-xxxxxxxxx
        subnets: ["subnet-xxxxx", "subnet-xxxxxx", "subnet-xxxxx"]
        instanceType: c5.2xlarge
        minSize: 1
        maxSize: 3
        volumeSize: 20
        volumeType: gp3
        volumeEncrypted: true
        ssh:
          publicKeyName: xxxxxx
        iam:
          instanceProfileARN: arn:aws:iam::xxxxxxx:instance-profile/xxxx-Role
          instanceRoleARN: arn:aws:iam::xxxxxx:role/xxxx-xxxx-Role
        privateNetworking: true
        securityGroups:
          #withShared: true
          #withLocal: true
          attachIDs: ["sg-xxxxxxxx"]
        labels:
          'team': 'infra'
          'env': 'test'
        tags:
          'Environment': test
          'Product': infra
          'Role': kubernetes
          'k8s.io/cluster-autoscaler/enabled': 'true'
          'k8s.io/cluster-autoscaler/test': owned
        overrideBootstrapCommand: |
          #!/bin/bash foo bar'        

```

**Logs**

**Anything else we need to know?**

The documentation confirming the possibility of adding `instanceProfileARN` under `managedNodeGroups` section

![image](https://user-images.githubusercontent.com/25801460/126654993-e3343757-11a4-4273-8ba3-2adc3de84084.png)

**Versions**

```
$ eksctl info
```
```sh
╰─ eksctl version 
0.50.0
```
