### ISSUE TITLE
Inconsistent config validation between create and upgrade

### ISSUE THREAD

**Issue by artem-nefedov** [weaveworks/eksctl#4028]
The following cluster config passes check for `eksctl create cluster` (it ignores the fact that you have VPC parameters defined, and instead creates it's own VPC):

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: test-cluster
  region: us-west-2

vpc:
  id: null
  subnets:
    public:
    private:
```

However, re-running `eksctl upgrade cluster` on the same cluster with the same config results in the error:

```
2021-07-27 16:32:15 [ℹ]  re-building cluster stack "eksctl-test-cluster-cluster"
Error: insufficient number of subnets, at least 2x public and/or 2x private subnets are required
```

**How to reproduce it?**

- eksctl create cluster -f config.yaml
- eksctl upgrade cluster -f config.yaml

**Expected behavior**

I'm not sure exactly which behavior is correct, but I believe it should be consistent: either both commands should ignore VPC params when they are null/empty, or both should fail the check.

In our case, failing the check would make more sense, because we had a bug in the code that auto-generates cluster config, and we didn't notice it until we got the failure on upgrade.

**Versions**

```
eksctl 0.57.0
```
