### ISSUE TITLE
Possibility to skip addon creation when nodegroups creation flags are set to false

### ISSUE THREAD

**Issue by kishoregv** [weaveworks/eksctl#4030]
**What feature/behavior/change do you want?**
This is a feature request for `eksctl create cluster` command
Currently, when the clusterconfig contains coredns(which is has a deployment) addon under addons section and nodegroup flags `--without-nodegroup` and `--managed` are set to `false`, eksctl creates the cluster and eventually fails on addon creation.

The Addon will go to degraded state as there are no node to create replicas for coredns deployment. For vpc-cni or kubeproxy addons this is not an issue because they are daemonset as expect replicas would be zero as there no nodes.

It would be nice to have an additional flag(`--without-addons`), so eksctl does not create addons.

**Why do you want this feature?**

We have a need to create nodegroups after cluster creation, this is causing the cluster creations fail as we cannot let eksctl create nodegroup at cluster create time, and eksctl tries to create addons by default.

**Comment by nikimanoledaki** [comment]
Hi @kishoregv, could you share the steps you took so that I can reproduce the error you came across, please?

**Comment by danjo133** [comment]
I'm also very interested in this feature since I'm also running into this.

**Comment by Skarlso** [comment]
I have a hunch that this isn't done by eksctl. In which case, there is nothing we can do about it since EKS is the one installing default addons. Since this also happens with CAPA clusters. But let's see if EKS maybe supports some kind of switch we can pass on that it doesn't install addons.

**Comment by Skarlso** [comment]
Niki's example contains an addon. If not defined like this:

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: addon-bug
  region: us-west-2
  version: "1.22"
```

The cluster is created successfully. 

Wait, hang on. You have a config file which defines an addon but no nodegroups but you would like to have a flag which disabled addons? But you defined the addon in a config file... I'm confused. Just deleted the definition of the addon from the config file?

This is a more interesting example with ipv6:

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: 'test-2'
  region: 'eu-north-1'
  version: '1.22'

addons:
  - name: vpc-cni
  - name: coredns
  - name: kube-proxy
iam:
  withOIDC: true


kubernetesNetworkConfig:
  ipFamily: IPv6
```

This is problematic as addons are required to be defined, but they fail because there are no nodes defined yet. And I believe this used to work at some point....
