### ISSUE TITLE
Containerd for unmanagedGroup

### ISSUE THREAD

**Issue by shinji62** [weaveworks/eksctl#4038]
**What were you trying to accomplish?**
I try to setup a cluster 1.21 with containerd for Unmanaged group.

**What happened?**
The node seems to join the cluster but eksctl is sill waiting for them to be ready

```
2021-07-29 07:17:07 [ℹ]  nodegroup "ng-1-m5large-1-18-ap-ne1a-0d29" has 0 node(s)
2021-07-29 07:17:07 [ℹ]  waiting for at least 1 node(s) to become ready in "ng-1-m5large-1-18-ap-ne1a-0d29"
```

When I remove 
```
--kubelet-extra-args '--node-labels=eks.amazonaws.com/nodegroup=ng-1-m5large-1-18-ap-ne1a-0d29,eks.amazonaws.com/nodegroup-image=ami-02a49655b336f1b47' 
```
the node seems ready but eksctl do not recognize them 

at the contrary when I let this argument the node are not ready even in kubernetes

```
  - name: ng-1-m5large-1-18-ap-ne1a-0d29
    availabilityZones: ["ap-northeast-1a"]
    overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh dev-arene-cluster-gen2  --kubelet-extra-args '--node-labels=eks.amazonaws.com/nodegroup=ng-1-m5large-1-18-ap-ne1a-0d29,eks.amazonaws.com/nodegroup-image=ami-02a49655b336f1b47' --container-runtime containerd
    <<: &node-default
      instanceType: "m5.large"
      ami: ami-02a49655b336f1b47
      desiredCapacity: 1
      minSize: 1
      maxSize: 3
      disableIMDSv1: true
      disablePodIMDS: true
      volumeSize: 500  
      privateNetworking: true
      ssh:
        enableSsm: true
      labels:
        dedicated/tekton: "true"
      tags:
        k8s.io/cluster-autoscaler/node-template/label/dedicated/tekton: "true"
        k8s.io/cluster-autoscaler/node-template/taint/dedicated/tekton: "true:NoSchedule"
        k8s.io/cluster-autoscaler/enabled: "true"
      taints:
        dedicated/tekton: "true:NoSchedule"
```

**How to reproduce it?**
Creating using this configfile

**Logs**

When I run directly

```
/etc/eks/bootstrap.sh dev-arene-cluster-gen2 --container-runtime containerd --kubelet-extra-args '--node-labels=eks.amazonaws.com/nodegroup=ng-1-m5large-1-18-ap-ne1d-208g,eks.amazonaws.com/nodegroup-image=ami-02a49655b336f1b47'
mv: cannot stat ‘/etc/eks/containerd/containerd-config.toml’: No such file or directory
```
seeing this error too
```
Jul 29 07:47:30 ip-10-10-32-60.ap-northeast-1.compute.internal systemd[1]: kubelet.service failed to run 'start-pre' task: No such file or directory
Jul 29 07:47:30 ip-10-10-32-60.ap-northeast-1.compute.internal systemd[1]: Failed to start Kubernetes Kubelet.
Jul 29 07:47:30 ip-10-10-32-60.ap-northeast-1.compute.internal systemd[1]: Unit kubelet.service entered failed state.
Jul 29 07:47:30 ip-10-10-32-60.ap-northeast-1.compute.internal systemd[1]: kubelet.service failed.
```
**Versions**

```
2021-07-29 07:52:18 [ℹ]  eksctl version 0.58.0
```

**Comment by Callisto13** [comment]
Hi @shinji62 thanks for asking.

From the manual run output, it looks like it is failing [here](https://github.com/awslabs/amazon-eks-ami/blob/master/files/bootstrap.sh#L409) which means that [this file](https://github.com/awslabs/amazon-eks-ami/blob/master/files/containerd-config.toml) was not left where it should have been during [image build](https://github.com/awslabs/amazon-eks-ami/blob/master/scripts/install-worker.sh#L144-L150) (maybe?). I should know more when I am able to repro.

I cannot find that AMI when searching for the ID in EC2, are you using a custom one?

**Comment by shinji62** [comment]
Sorry that in tokyo region of this image https://github.com/awslabs/amazon-eks-ami/releases/tag/v20210722

**Comment by Callisto13** [comment]
Notes: _I will edit as I go_

This error
```
mv: cannot stat ‘/etc/eks/containerd/containerd-config.toml’: No such file or directory
```
makes sense if is run a second time: that file has already been moved.

**Comment by shinji62** [comment]
@Callisto13 Ok maybe it works the first time I guess with only ` --container-runtime containerd` but eksctl never detect the nodegroup to be ready so I try to add the kubelet options and this time it's just failing.

**Comment by Callisto13** [comment]
Thank you @shinji62 I saw this in your initial comment. 

> eksctl never detect the nodegroup to be ready

eksctl is not doing the detection here, the kube api server will be doing that. Since you are using the `overrideBootstrapCommand` we are likely to find the issue is in the given config script; eksctl is not doing any bootstrapping with this configuration. The labels you are adding in the extra args flag _look_ fine, but I will play around with them. (It could be that this region has a different domain, or requires more information, but that is just a guess I need to test)

Of course I will still keep looking for a bug in `eksctl`, as well as problems with the `/etc/eks/bootstrap.sh` on the AMI.

**Comment by Callisto13** [comment]
I have not had time to work on this the last couple of days.

We are about to merge a config option to set containerd via config file https://github.com/weaveworks/eksctl/pull/4051 .

There may also be another way to set container in the meantime by using `preBootstrapCommands` to edit [`/var/lib/cloud/scripts/eksctl/bootstrap.al2.sh`](https://github.com/weaveworks/eksctl/blob/main/pkg/nodebootstrap/bindata/assets/bootstrap.al2.sh) with `sed` and add that flag.

**Comment by Callisto13** [comment]
Closing this as we now expose a flag to configure containerd for unmanaged nodegroups:

```yaml
nodeGroups:
  - name: ng-1
    instanceType: m5.xlarge
    desiredCapacity: 2
    amiFamily: AmazonLinux2
    containerRuntime: containerd
```
