### ISSUE TITLE
Missing IAM Permission in Minimum IAM policies page

### ISSUE THREAD

**Issue by SharpThunder** [weaveworks/eksctl#4046]
**What were you trying to accomplish?**
To create Cluster with IAM User using minimum IAM policies.

https://eksctl.io/usage/minimum-iam-policies/

**What happened?**
A permission is missing got an error.

> creating OIDC provider: AccessDenied: User: arn:aws:iam:::user/User is not authorized to perform: iam:TagOpenIDConnectProvider on resource

**How to reproduce it?**

Create IAM User with minimum IAM policies.
Create cluster using eksctl create cluster -f ekscluster.yml

```

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: Cluster
  region: us-east-2
  version: "1.19"

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: aws-load-balancer-controller
      namespace: kube-system
    wellKnownPolicies:
      awsLoadBalancerController: true
  - metadata:
      name: external-dns
      namespace: kube-system
    wellKnownPolicies:
      externalDNS: true
  - metadata:
      name: cert-manager
      namespace: cert-manager
    wellKnownPolicies:
      certManager: true
  - metadata:
      name: cluster-autoscaler
      namespace: kube-system
      labels: {aws-usage: "cluster-ops"}
    wellKnownPolicies:
      autoScaler: true

vpc:
  id: "*****"
  subnets:
    private:
      us-east-2a:
          id: "*****"
      us-east-2b:
          id: "*****"    
      us-east-2c:
          id: "*****"
    public:
      us-east-2a:
          id: "*****"
      us-east-2b:
          id: "*****"
      us-east-2c:
          id: "*****"
  clusterEndpoints:
    publicAccess: true
    privateAccess: true


managedNodeGroups:
  - name:  managed-ng-1
    instanceType: t3.medium
    minSize: 1
    maxSize: 4
    desiredCapacity: 3
    privateNetworking: true
    ssh:
      publicKeyName: *****
      enableSsm: true
    labels: {role: worker}
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
        certManager: true
        albIngress: true
        cloudWatch: true
    updateConfig:
      maxUnavailable: 2    
    volumeSize: 32
    volumeIOPS: 3000
    volumeThroughput: 125
    volumeType: gp3
    volumeEncrypted: true
    disableIMDSv1: true

cloudWatch:
  clusterLogging:
    # enable specific types of cluster control plane logs
    enableTypes: ["audit", "authenticator", "controllerManager", "api", "scheduler"]
    # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
    # supported special values: "*" and "all"


secretsEncryption:
  # KMS key used for envelope encryption of Kubernetes secrets
  keyARN: *****
```

**Versions**

```
$ eksctl info
eksctl version: 0.56.0
kubectl version: v1.21.2
OS: linux
```
