### ISSUE TITLE
wellKnownPolicies for ebsCSIController should use the "latest policy" form the documentation for aws-ebs-csi-driver

### ISSUE THREAD

**Issue by ruzickap** [weaveworks/eksctl#4061]
**What were you trying to accomplish?**
It seems like like the `wellKnownPolicies` for `ebsCSIController` doesn't use the latest policy mentioned in the "official" examples: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/example-iam-policy.json 

```yaml
    - metadata:
        name: ebs-csi-controller
        namespace: kube-system
      wellKnownPolicies:
        ebsCSIController: true
```

Currently it is not possible to use "encryption", "snapshots" with `aws-ebs-csi-driver`, because the eksctl is using older version of this policy: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/e8d21db8f0607a6ef97546e527d13f2052ecf8f0/docs/example-iam-policy.json

It would be great if the policy for `ebsCSIController` can be updated according the latest "example".

**Versions**

```
$ eksctl info
eksctl version: 0.60.0
kubectl version: v1.21.1
OS: darwin
```
