### ISSUE TITLE
Config file Yaml Anchors and references do not allow overrides

### ISSUE THREAD

**Issue by zanven42** [weaveworks/eksctl#4062]
when trying to define nodegroups the below errors

```yaml
nodeGroups:
  - &foo
    name: test
  - <<: *foo
    name: bar
```
```sh
$ eksctl create nodegroup -f ./clusterconfig-dev.eksctl.yaml --dry-run
Error: couldn't create node group filter from command line options: loading config file "./clusterconfig-dev.eksctl.yaml": error converting YAML to JSON: yaml: unmarshal errors:
  line 41: key "name" already set in map
```

example taken from a bigger file than the one provided.

The reason for wanting this is so i can more easily reuse massive definitions to avoid human error on node creation. ( also being able to define extra unused yaml keys would be nice as they come through as undefined )
i.e

```yaml
foo:
  - &node1
    name: foo
nodeGroup:
  - *node1
  ```
  
  ```sh
  $ eksctl create nodegroup -f ./clusterconfig-dev.eksctl.yaml --dry-run
Error: couldn't create node group filter from command line options: loading config file "./clusterconfig-dev.eksctl.yaml": error unmarshaling JSON: while decoding JSON: json: unknown field "node1"
```
