### ISSUE TITLE
update-kube-proxy from 1.17 to 1.18 Image not found error

### ISSUE THREAD

**Issue by composer22** [weaveworks/eksctl#4084]
Using 
```
eksctl version
0.60.0

eksctl utils update-kube-proxy --cluster=k8s-cluster --approve
```

Error - infinite loop in the pod
```
state:
  waiting:
    message: Back-off pulling image "602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/kube-proxy:v1.18.20-eksbuild.2"
    reason: ImagePullBackOff
```

Note: v1.18.20-eksbuild.2

which apparently doesn't exist

Documentation on AWS suggests image id:

https://docs.aws.amazon.com/eks/latest/userguide/managing-kube-proxy.html#kube-proxy-default-versions-table

```
1.18.8-eksbuild.1
```

This doc also outlines the newer approach 
```
eksctl update addon...
```

So, we have a conundrum of questions because docs might be out of date vs code not being correct, or both. And also what should the process be to upgrade from 1.17 old school to new, if at all. Can we use old school still here?

To sum up

Q: How to I patch around this in the daemon set? Which version should I use? 1.18.8-eksbuild.1, v1.18.20-eksbuild**.1**, some other flavour?

Q: Where did v1.18**.20-eksbuild.2** originate from in eksctl? It's clearly wrong.

Q: How can eksctl utils update-kube-proxy command validate this so it doesn't happen in the future, including giving adequate instructions to use a different approach from 1.17 to 1.18 and beyond?

Thanks
