### ISSUE TITLE
Windows custom AMI userdata

### ISSUE THREAD

**Issue by sallwood-pa** [weaveworks/eksctl#4101]
When specifying a custom AMI for a Windows node group the userdata looks like it is encoded, and new nodes never join the cluster. If I manually update the launch template to use the below userdata the nodes do join.

```
<powershell>
[string]$EKSBootstrapScriptFile = "$env:ProgramFiles\Amazon\EKS\Start-EKSBootstrap.ps1"
& $EKSBootstrapScriptFile -EKSClusterName "mycluster" -KubeletExtraArgs "--node-labels=alpha.eksctl.io/cluster-name=mycluster,alpha.eksctl.io/nodegroup-name=mynodegroupname --register-with-taints=mytaint=true:NoSchedule" 3>&1 4>&1 5>&1 6>&1
</powershell>
```

The only change I am making is "amiFamily: WindowsServer2019FullContainer" to "ami: ami-xxxxxxxx" which is the same AMI as the amiFamily plus some software that I want preinstalled. When amiFamily is specified the userdata looks like above.

Here is snippet of the config file

```
  - name: mynodegroupname
    instanceType: m5.xlarge
    ami: ami-xxxxxxxxxxxxxxxxx
    minSize: 1
    maxSize: 10
    privateNetworking: true
    taints:
      win-pp-gmsa: "true:NoSchedule"
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/myclustername: "owned"
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudwatch: true
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
```

eks cluster version = 1.19
eksctl = 0.61.0
