### ISSUE TITLE
M6i instances do no join the cluster

### ISSUE THREAD

**Issue by treyhyde** [weaveworks/eksctl#4106]
**What feature/behavior/change do you want?**

support for the new m6i instances class.

There are no entries for this instance in maxpods.go and reserved_data.go.  (When I added them manually in the `main` branch, it had no effect.  The `make` aliases to update these lists don't actually build, looks like the files moved around.)

The nodes boot and go ready in EC2 but they never join the EKS cluster (let alone go ready).

```
  - name: test-mg-m6i
    instanceType: m6i.4xlarge
    minSize: 3
    desiredCapacity: 10
    maxSize: 50
    availabilityZones: ["us-east-2a","us-east-2b","us-east-2c"]
    volumeSize: 100
    volumeType: gp3
    volumeEncrypted: true
    ssh:
      allow: false
      enableSsm: false
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true
        albIngress: true
        autoScaler: true
        cloudWatch: true
        imageBuilder: true
        ebs: true
        fsx: true
        efs: true
    privateNetworking: false

```

**Why do you want this feature?**
price / performance of the new instance types
