### ISSUE TITLE
withOIDC as false creates OIDC end-point

### ISSUE THREAD

**Issue by chainhead** [weaveworks/eksctl#4107]
**What help do you need?**
Is the OIDC end-point expected to be created with the following YAML?

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: oidc
  region: ap-south-1

iam:
  withOIDC: false

managedNodeGroups:
  - name: ng-oidc
    instanceType: t3.medium
    desiredCapacity: 1
    privateNetworking: false
```

After creating the cluster, I can see an OIDC end-point. It is also seen in `eksctl get cluster --name oidc`.

```bash
aws eks describe-cluster --name oidc --query "cluster.identity.oidc.issuer" --output text
https://oidc.eks.ap-south-1.amazonaws.com/id/8997..............................................CD80
```

But, the same is not seen in `aws iam list-open-id-connect-providers | grep 8997..............................................CD80`

So, what is the expected behavior?
