### ISSUE TITLE
`update-auth-configmap=false` flag not being respected for both create and delete nodegroup commands

### ISSUE THREAD

**Issue by sushanthmangalore** [weaveworks/eksctl#4137]
**What were you trying to accomplish?**
Trying to add/remove node groups to an eksctl created cluster without any updates to the aws-auth configmap

**What happened?**
The `eksctl create nodegroup` command added an entry in aws-auth configmap. The `eksctl delete nodegroup` command removed the entry in aws-auth configmap.

**How to reproduce it?**
Create a new EKS cluster using eksctl version 0.62.0 and Kubernetes version 1.20. Config file below - 

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster
  region: us-west-1

managedNodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 3
    volumeSize: 80
  - name: ng-2
    instanceType: t3.large
    desiredCapacity: 2
    volumeSize: 80

```
Add a new node group to the cluster using the command - 

`eksctl create nodegroup --cluster=basic-cluster --region=us-west-1 --managed --name=ng-new --instance-types=t2.large,t3.large --update-auth-configmap=false -v 4`

**Logs**

**Anything else we need to know?**
OS - Amazon Linux 2, x86

**Versions**

```
$ eksctl info

eksctl version: 0.62.0
kubectl version: v1.22.1
OS: darwin
```
