### ISSUE TITLE
managedNodeGroups define isntanceType in created LaunchTemplate

### ISSUE THREAD

**Issue by jimmyraywv** [weaveworks/eksctl#4147]
I am using `eksctl` with a config file to create a cluster and 1 managed node group.
```
managedNodeGroups:
  - name: mng-1
    labels:
      node-group: mng-1
      owner: jimmy
      role: managed-worker
      env: dev
      billing: lob-cc
    instanceType: t3.small
...
```

I realize that under the covers, a launch template is created, but the `LaunchTemplate:LaunchTemplateData:InstanceType` is missing. Instead, the `ManagedNodeGroup:Properties:InstanceTypes` string array is added, and contains one entry for the instance type that I specified in the `managedNodeGroups` instance element. The end result is a launch template without an instance type.

Is this by design? Is there a way to force the launch template to specify the `LaunchTemplate:LaunchTemplateData:InstanceType` element, short of using a custom launch template?
