### ISSUE TITLE
upgrade nodegroups with launch-template-version errors

### ISSUE THREAD

**Issue by kishoregv** [weaveworks/eksctl#4156]
I am trying to run following command
```
eksctl upgrade nodegroup --cluster test-cluster --name test-node-group --launch-template-version 2 --wait --timeout 120m0s -r us-east-2
```
The nodegroup is using a launch template, as the nodegroup using a custom AMI.

the above command fails with following error.

`Error: launch-template-version is only valid if a nodegroup is using an explicit launch template`

**What were you trying to accomplish?**

I am trying to upgrade a nodegroup with custom AMI

**What happened?**

Upgrade command failed with following error.

`Error: launch-template-version is only valid if a nodegroup is using an explicit launch template`
**How to reproduce it?**

* Create node groups with AMI pinned(custom AMI).
* Create new version of launch template with a different AMI
* run ekctl command to upgrade nodegroup with launch-template-version from above step.

**Logs**

**Anything else we need to know?**

Looking at the codebase, I think there is a bug in following lines.
https://github.com/kishoregv/eksctl/blob/main/pkg/managed/service.go#L212-L220
```
	if options.LaunchTemplateVersion != "" {
		// TODO validate launch template version
		if len(ltResources) == 1 {
			return errors.New("launch-template-version is only valid if a nodegroup is using an explicit launch template")
		}
		if ngResource.LaunchTemplate == nil || ngResource.LaunchTemplate.Id == nil {
			return errors.New("nodegroup does not use a launch template")
		}
	}
```
I think the below line should check if length is zero.
```
if len(ltResources) == 1 {
```

**Versions**

```
$ eksctl info
eksctl version: 0.64.0-rc.3
kubectl version: v1.21.0
OS: linux
```

**Comment by aclevername** [comment]
Thanks for opening the issue @kishoregv . Can you provide the config file used to create the nodegroup originally?

I can see from the commit that @cPu1 worked on this, so might have some clarity around whether this is expected behaviour or not?

**Comment by kishoregv** [comment]
Please find the below config used for creating the nodegroup
```
apiVersion: eksctl.io/v1alpha5
managedNodeGroups:
- ami: ami-054332611f565551e
  desiredCapacity: 4
  disableIMDSv1: true
  iam:
    instanceRoleARN: arn:aws:iam::111111111111:role/EKS_MgmtNode
    withAddonPolicies:
      albIngress: null
      appMesh: null
      appMeshPreview: null
      autoScaler: null
      certManager: null
      cloudWatch: null
      ebs: null
      efs: null
      externalDNS: null
      fsx: null
      imageBuilder: null
      xRay: null
  instanceTypes:
  - c5.xlarge
  - c5n.xlarge
  - c5a.xlarge
  labels:
    mgmt: "true"
  maxSize: 7
  minSize: 4
  name: test-nodegroup-abcdef
  privateNetworking: true
  releaseVersion: ""
  securityGroups:
    attachIDs:
    - sg-1a1db111d111a11d1
    - sg-2f22f22f22ab2fbf2
    withLocal: false
    withShared: null
  spot: true
  ssh:
    allow: false
    publicKeyName: eks_ssh_111111111111_eks-test-cluster_1.19
  tags:
    app: app3
    k8s.io/cluster-autoscaler/eks-test-cluster: owner
    k8s.io/cluster-autoscaler/enabled: "true"
    noshutdown: "true"
    timestamp: "2021-09-01T06:24:35-04:00"
  taints:
  - effect: NoSchedule
    key: mgmt
    value: "true"
  volumeEncrypted: true
  volumeKmsKeyID: arn:aws:kms:us-east-2:111111111111:key/b11111c1-bce1-1111-1111-11b1111a1111
  volumeSize: 75
metadata:
  name: eks-test-cluster
  region: us-east-2
  tags:
    environment: PROD
  version: "1.19"

```
