### ISSUE TITLE
STS Error when using `--config-file` option

### ISSUE THREAD

**Issue by kameshsampath** [weaveworks/eksctl#4237]
I am facing the similar issue like https://github.com/weaveworks/eksctl/issues/1408 but only with `--config-file` option . When I do run the same command without `--config-file` things seem to work.

**What were you trying to accomplish?**
Creating a cluster with `eksctl create cluster --config-file=myconfig-file.yaml`

**What happened?**

With the right credentials set at ~/.aws/credentails and configured with ~/.aws/confing, the EKS cluster creation fails with STS error ,
```
Error: checking AWS STS access – cannot get role ARN for current session: MissingEndpoint: 'Endpoint' configuration is required for this service
```

When I run the same command with without config file and passing the command line options all works as expected.

**How to reproduce it?**

with a config file like with AWS credentials configured with **default** profile do `eksctl create cluster --config-file=my-config.yaml`

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: "kameshs-gloo-demos"
  region: " my-region"
  tags:
    app: gloo
  version: "1.20"
vpc:
  id: "my-vpc"
  cidr: "172.25.0.0/16"
  clusterEndpoints:
    privateAccess: false
    publicAccess: true
  nat:
    gateway: Single
nodeGroups:
- name: "kameshs-gloo-demos-workers-large"
  desiredCapacity: 3
  securityGroups:
    attachIDs:
    - "my-sg"
  volumeIOPS: 3000
  volumeSize: 80
  volumeThroughput: 125
  volumeType: gp3
```

**Logs**
```
Error: checking AWS STS access – cannot get role ARN for current session: MissingEndpoint: 'Endpoint' configuration is required for this service
```

**Anything else we need to know?**

- OS: Fedora 34
- Dowloaded binary v0.67.0 from Github Releases

**Versions**

```
eksctl version: 0.67.0
kubectl version: v1.20.5
OS: linux
```
