### ISSUE TITLE
cn-northwest-1   addon  error

### ISSUE THREAD

**Issue by DevOpserzhao** [weaveworks/eksctl#4239]
1 error(s) occurred and cluster hasn't been created properly, you may wish to check CloudFormation console

region cn-northwest-1

**Logs**
2021-09-22 07:28:41 [ℹ]  daemonset "kube-system/aws-node" restarted
2021-09-22 07:30:42 [ℹ]  using provided ServiceAccountRoleARN "arn:aws:iam::aws:policy/AmazonEKSCNIAccess"
2021-09-22 07:30:42 [ℹ]  creating addon
2021-09-22 07:30:42 [!]  1 error(s) occurred and cluster hasn't been created properly, you may wish to check CloudFormation console
2021-09-22 07:30:42 [ℹ]  to cleanup resources, run 'eksctl delete cluster --region=cn-northwest-1 --name=eksctl-eks-test01-cluster'
2021-09-22 07:30:42 [✖]  failed to create addon "vpc-cni": AccessDeniedException: 
        status code: 403, request id: 98ad6d5d-8ce7-4e19-a96b-98ddbf422726
Error: failed to create cluster "eksctl-eks-test01-cluster"

**Anything else we need to know?**

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksctl-eks-test01-cluster
  region: cn-northwest-1
  version: "1.21"
vpc:
  subnets:
    public:
      cn-northwest-1a: { id: subnet-xxx }
      cn-northwest-1b: { id: subnet-xxx }
iam:
  withOIDC: true

addons:
- name: vpc-cni
  version: 1.7.5 # optional
  attachPolicyARNs: #optional
  - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
  serviceAccountRoleARN: arn:aws:iam::aws:policy/AmazonEKSCNIAccess
- name: coredns
  version: latest # auto discovers the latest available
- name: kube-proxy
  version: latest

managedNodeGroups:
  - name: ng-1-workers-a
    labels: { role: workers }
    instanceType: t3.xlarge
    availabilityZones: ["cn-northwest-1a"]
    desiredCapacity: 1
    volumeSize: 100
    ssh:
      enableSsm: true
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        ebs: true
        fsx: true
        efs: true
```

$ eksctl info
```
eksctl version: 0.67.0
kubectl version: v1.20.4
OS: linux

**Comment by aclevername** [comment]
Thanks for opening the issue @DevOpserzhao . Does the role your using to create the cluster have the correct permissions to interact with the EKS Addons API? The error makes it look like a permissions issue.

**Comment by DevOpserzhao** [comment]
policie  is AdministratorAccess

**Comment by DevOpserzhao** [comment]
> Thanks for opening the issue @DevOpserzhao . Does the role your using to create the cluster have the correct permissions to interact with the EKS Addons API? The error makes it look like a permissions issue.

policie is AdministratorAccess

**Comment by cPu1** [comment]
The ARN for China regions should have the `arn:aws-cn:*` prefix:

```yaml
addons:
- name: vpc-cni
  version: 1.7.5 # optional
  attachPolicyARNs: #optional
  - arn:aws-cn:iam::aws:policy/AmazonEKS_CNI_Policy
```
