### ISSUE TITLE
serviceAccount   CREATE_FAILED

### ISSUE THREAD

**Issue by DevOpserzhao** [weaveworks/eksctl#4242]
`2021-09-23 03:21:39 [✖]  AWS::IAM::Policy/PolicyAWSLoadBalancerController: CREATE_FAILED – "1 validation error detected: Value 'eksctl-eksctl-eks-test01-cluster-addon-iamserviceaccount-kube-system-aws-load-balancer-controller-PolicyAWSLoadBalancerController' at 'policyName' failed to satisfy constraint: Member must have length less than or equal to 128 (Service: AmazonIdentityManagement; Status Code: 400; Error Code: ValidationError; Request ID: e2752483-63be-4336-882b-827170db7911; Proxy: null)"`

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksctl-eks-test01-cluster
  region: cn-northwest-1
  version: "1.21"
vpc:
  subnets:
    public:
      cn-northwest-1a: { id: subnet-00636264cded81f04 }
      cn-northwest-1b: { id: subnet-0103c93766cfd2f13 }
iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: s3-reader
      # if no namespace is set, "default" will be used;
      # the namespace will be created if it doesn't exist already
      namespace: backend-apps
      labels: {aws-usage: "application"}
    attachPolicyARNs:
    - "arn:aws-cn:iam::aws:policy/AmazonS3ReadOnlyAccess"
  - metadata:
      name: aws-load-balancer-controller
      namespace: kube-system
    wellKnownPolicies:
      awsLoadBalancerController: true
  - metadata:
      name: ebs-csi-controller-sa
      namespace: kube-system
    wellKnownPolicies:
      ebsCSIController: true
```

$ eksctl info
```
 eksctl version 0.67.0
