### ISSUE TITLE
Ensure that IPv6 can only be set for k8s >= 1.21

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/eksctl#4261]
Part of https://github.com/weaveworks/eksctl/issues/4255

**Description**
If `ipFamily` is set to `ipv6`, ensure that the version is >= 1.21.

```yaml
metadata:
  name: <cluster-name>
  version: "1.21"

vpc:
   ipFamily: ipv6
```

**Scope**
- Add some validation for when `ipFamily` is set
- Error out if the version is not supported

**Acceptance Criteria**
Story 1
- As an `eksctl` user
- When I set `ipFamily` to `ipv6` and `metadata.version` to `"1.21"`
- I can see in the console that I have created an IPv6 VPC+cluster
- I can learn about this in the docs

Story 2
- As an `eksctl` user
- When I set `ipFamily` to `ipv6` and `metadata.version` to `"1.20"`
- I see an error that this feature is not supported with this version
