### ISSUE TITLE
Is it possible to update metadata tags for a cluster?

### ISSUE THREAD

**Issue by runtman** [weaveworks/eksctl#4337]
So I have 8 EKSCTL clusters, and they are all missing tags in the metadata section of the cluster:

Current

```
metadata:
  name: vz-us-west-1
  region: us-west-1
  version: '1.18'
```

I'd like to change it to:

```
metadata:
  name: vz-us-west-1
  region: us-west-1
  version: '1.18'
  tags: { ae.cloud: "x-us-west-1", ae.environment: "x" }
```

If I understood the docs currently `upgrade` only changes the version, is it possible to upgrade these tags or will they just update on the next upgrade?
