### ISSUE TITLE
Add support for ASG lifecycle hooks

### ISSUE THREAD

**Issue by hintofbasil** [weaveworks/eksctl#4347]
**What feature/behavior/change do you want?**

Add support for [autoscaling lifecycle hooks](https://docs.aws.amazon.com/autoscaling/ec2/userguide/lifecycle-hooks.html) to node groups.

A sample configuration could be the following based on the [cloudformation documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-autoscaling-autoscalinggroup-lifecyclehookspecification.html).  This supports all lifecycle hook configuration options.

```yaml
cluster:
  ...
  nodeGroups:
    - name: spotNodeGroup
      lifecycleHooks:
        - defaultResult: <String>
          heartbeatTimeout: <Integer>
          lifecycleHookName: <String>
          lifecycleTransition: <String>
          notificationMetadata: <String>
          notificationTargetARN: <String>
          roleARN: <String>
      ...
```

**Why do you want this feature?**

Node groups already have support for [capacity rebalance](https://docs.aws.amazon.com/autoscaling/ec2/userguide/ec2-auto-scaling-capacity-rebalancing.html) however this does not automatically drain the nodes before termination.  The [node termination exporter](https://github.com/aws/aws-node-termination-handler), an official solution to this problem from AWS, requires the addition of lifecycle hooks to work.

These shouldn't be required for managed node groups as they will automatically drain workloads on a rebalance event.

**Comment by hintofbasil** [comment]
Lifecycle hooks are something I've never played around with before but AWS support has recommended them for this issue.  As such I can only guess at what sort of configuration we would want.  But this is my best guess

```yaml
cluster:
  ...
  nodeGroups:
    - name: spotNodeGroup
      lifecycleHooks:
        - defaultResult: ABANDON
          lifecycleHookName: node-drain
          lifecycleTransition: EC2_INSTANCE_TERMINATING
      ...
```

It is possible we would also need to set some other values such as `HeartbeatTimeout`, `NotificationTargetARN` or `RoleARN` but I don't see an immediate need for them with my current understanding of the node termination exporter.

I'm not sure there is a strong connection between this and the issue you linked.  The NTH will perform a drain excluding daemonsets just like `eksctl delete nodegroup` will.  Really the NTH is closer to matching `eksctl delete nodegroup` functionality for single node terminations.
