### ISSUE TITLE
cannot create cluster on existing VPC with config file

### ISSUE THREAD

**Issue by taishin** [weaveworks/eksctl#436]
**What happened?**
when i created cluster on exisiting VPC with config files, it failed.

**What you expected to happen?**

**How to reproduce it?**
```
$ eksctl create cluster -f cluster.yaml
[ℹ]  using region ap-northeast-1
[ℹ]  setting availability zones to [ap-northeast-1a ap-northeast-1c ap-northeast-1d]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1d41fb8]

goroutine 1 [running]:
github.com/weaveworks/eksctl/pkg/vpc.SetSubnets(0xc00028c000, 0xc00028c000, 0x0)
        /go/src/github.com/weaveworks/eksctl/pkg/vpc/vpc.go:24 +0x148
github.com/weaveworks/eksctl/pkg/ctl/create.doCreateCluster.func3(0x3042e60, 0xc000a21500)
        /go/src/github.com/weaveworks/eksctl/pkg/ctl/create/cluster.go:301 +0x8d7
github.com/weaveworks/eksctl/pkg/ctl/create.doCreateCluster(0xc000674080, 0xc00028c000, 0x0, 0x0, 0xc0006fc780, 0x4, 0x329d123)
        /go/src/github.com/weaveworks/eksctl/pkg/ctl/create/cluster.go:361 +0x5dc
github.com/weaveworks/eksctl/pkg/ctl/create.createClusterCmd.func1(0xc0006fc780, 0xc000678ce0, 0x0, 0x2)
        /go/src/github.com/weaveworks/eksctl/pkg/ctl/create/cluster.go:53 +0x94
github.com/weaveworks/eksctl/vendor/github.com/spf13/cobra.(*Command).execute(0xc0006fc780, 0xc000678ca0, 0x2, 0x2, 0xc0006fc780, 0xc000678ca0)
        /go/src/github.com/weaveworks/eksctl/vendor/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/weaveworks/eksctl/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x5154c80, 0x1, 0x5b, 0x2b)
        /go/src/github.com/weaveworks/eksctl/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/weaveworks/eksctl/vendor/github.com/spf13/cobra.(*Command).Execute(0x5154c80, 0x0, 0xc0000ac2f0)
        /go/src/github.com/weaveworks/eksctl/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
        /go/src/github.com/weaveworks/eksctl/cmd/eksctl/main.go:65 +0x2d
```

- config.yaml
``` 
apiVersion: eksctl.io/v1alpha3
kind: ClusterConfig

metadata:
  name: cluster-in-existing-vpc
  region: ap-northeast-1

vpc:
  subnets:
    private:
      ap-northeast-1a: {id: subnet-099ab88b723e0xxxx}
      ap-northeast-1c: {id: subnet-0b28a3843856dxxxx}
      ap-northeast-1d: {id: subnet-0c2439e34d6a3xxxx}

nodeGroups:
  - name: ng-1-workers
    instanceType: m5.xlarge
    desiredCapacity: 10
    privateNetworking: true
```

**Anything else we need to know?**

**Versions**
```
$ eksctl version 
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.1.18"}
$ uname -a 
Darwin sasaki-alpaca.local 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
```

**Logs**

**Comment by errordeveloper** [comment]
Thanks for reporting this, @taishin! I'm hoping to fix this in the upcoming release, the umbrella issue is #425.

Could you please confirm if the following command works for you?

```
eksctl create cluster --vpc-private-subnets=subnet-099ab88b723e0xxxx,subnet-0b28a3843856dxxxx,subnet-0c2439e34d6a3xxxx  --node-private-networking <otherFlags>
```

**Comment by taishin** [comment]
thanks for your reply.
above command ( --vpc-private-subnets options) works well.

**Comment by taishin** [comment]
There were 2 results.

(1) `private` -> `Private`
```
vpc:
  subnets:
    Private:
      ap-northeast-1a: {Id: subnet-099ab88b723e0xxxx}
      ap-northeast-1c: {Id: subnet-0b28a3843856dxxxx}
      ap-northeast-1d: {Id: subnet-0c2439e34d6a3xxxx}
```

result
```
$ eksctl create cluster -f cluster.yaml
[ℹ]  using region ap-northeast-1
[✔]  using existing VPC () and subnets (private:[  ] public:[])
[!]  custom VPC/subnets will be used; if resulting cluster doesn't function as expected, make sure to review the configuration of VPC/subnets
[ℹ]  creating EKS cluster "cluster-in-existing-vpc" in "ap-northeast-1" region
[ℹ]  will create a CloudFormation stack for cluster itself and 0 nodegroup stack(s)
[ℹ]  if you encounter any issues, check CloudFormation console or try 'eksctl utils describe-stacks --region=ap-northeast-1 --name=cluster-in-existing-vpc'
[ℹ]  creating cluster stack "eksctl-cluster-in-existing-vpc-cluster"
panic: runtime error: index out of range

goroutine 62 [running]:
github.com/weaveworks/eksctl/pkg/cfn/builder.(*ClusterResourceSet).addResourcesForVPC(0xc0000b44b0)
        /go/src/github.com/weaveworks/eksctl/pkg/cfn/builder/vpc.go:70 +0xa11
github.com/weaveworks/eksctl/pkg/cfn/builder.(*ClusterResourceSet).AddAllResources(0xc0000b44b0, 0xc0000b44b0, 0xc000b0bee0)
        /go/src/github.com/weaveworks/eksctl/pkg/cfn/builder/cluster.go:52 +0x166
github.com/weaveworks/eksctl/pkg/cfn/manager.(*StackCollection).CreateCluster(0xc0005e7620, 0xc00068fda0, 0x0, 0x0, 0x2dde380, 0xc000057748)
        /go/src/github.com/weaveworks/eksctl/pkg/cfn/manager/cluster.go:17 +0x30c
github.com/weaveworks/eksctl/pkg/cfn/manager.(*StackCollection).CreateCluster-fm(0xc00068fda0, 0x0, 0x0, 0x1, 0x1)
        /go/src/github.com/weaveworks/eksctl/pkg/cfn/manager/tasks.go:64 +0x48
github.com/weaveworks/eksctl/pkg/cfn/manager.Run.func1(0xc0009de330, 0xc0009b9040, 0x1, 0x1, 0xc000c37310, 0x0)
        /go/src/github.com/weaveworks/eksctl/pkg/cfn/manager/tasks.go:32 +0x11f
created by github.com/weaveworks/eksctl/pkg/cfn/manager.Run
        /go/src/github.com/weaveworks/eksctl/pkg/cfn/manager/tasks.go:28 +0xa7
```

private is empty?
```
using existing VPC () and subnets (private:[  ] public:[])
```

(2) `public` -> `Public`
```
vpc:
  subnets:
    Public:
      ap-northeast-1a: {id: subnet-06e6ace6301e9xxxx}
      ap-northeast-1c: {id: subnet-092d52f6f5805xxxx}
      ap-northeast-1d: {id: subnet-07ecc8c96d5f5xxxx}
```

result
```
$ eksctl create cluster -f cluster.yaml
[ℹ]  using region ap-northeast-1
[✔]  using existing VPC () and subnets (private:[] public:[subnet-06e6ace6301e9xxxx subnet-092d52f6f5805xxxx subnet-07ecc8c96d5f5xxxx])
[!]  custom VPC/subnets will be used; if resulting cluster doesn't function as expected, make sure to review the configuration of VPC/subnets
[ℹ]  creating EKS cluster "cluster-in-existing-vpc" in "ap-northeast-1" region
[ℹ]  will create a CloudFormation stack for cluster itself and 0 nodegroup stack(s)
[ℹ]  if you encounter any issues, check CloudFormation console or try 'eksctl utils describe-stacks --region=ap-northeast-1 --name=cluster-in-existing-vpc'
[ℹ]  creating cluster stack "eksctl-cluster-in-existing-vpc-cluster"
[✖]  unexpected status "ROLLBACK_IN_PROGRESS" while waiting for CloudFormation stack "eksctl-cluster-in-existing-vpc-cluster" to reach "CREATE_COMPLETE" status
[ℹ]  fetching stack events in attempt to troubleshoot the root cause of the failure
[ℹ]  AWS::CloudFormation::Stack/eksctl-cluster-in-existing-vpc-cluster: ROLLBACK_IN_PROGRESS – "The following resource(s) failed to create: [InternetGateway, ServiceRole, NATIP, VPC]. . Rollback requested by user."
[✖]  AWS::EC2::EIP/NATIP: CREATE_FAILED – "Resource creation cancelled"
[✖]  AWS::IAM::Role/ServiceRole: CREATE_FAILED – "Resource creation cancelled"
[✖]  AWS::EC2::InternetGateway/InternetGateway: CREATE_FAILED – "Resource creation cancelled"
[ℹ]  AWS::EC2::EIP/NATIP: CREATE_IN_PROGRESS – "Resource creation Initiated"
[ℹ]  AWS::IAM::Role/ServiceRole: CREATE_IN_PROGRESS – "Resource creation Initiated"
[ℹ]  AWS::EC2::InternetGateway/InternetGateway: CREATE_IN_PROGRESS – "Resource creation Initiated"
[✖]  AWS::EC2::VPC/VPC: CREATE_FAILED – "Value () for parameter cidrBlock is invalid. This is not a valid CIDR block. (Service: AmazonEC2; Status Code: 400; Error Code: InvalidParameterValue; Request ID: 3592b865-7524-49d3-8626-acdcae63b611)"
[ℹ]  AWS::EC2::EIP/NATIP: CREATE_IN_PROGRESS
[ℹ]  AWS::EC2::InternetGateway/InternetGateway: CREATE_IN_PROGRESS
[ℹ]  AWS::IAM::Role/ServiceRole: CREATE_IN_PROGRESS
[ℹ]  AWS::EC2::VPC/VPC: CREATE_IN_PROGRESS
[ℹ]  AWS::CloudFormation::Stack/eksctl-cluster-in-existing-vpc-cluster: CREATE_IN_PROGRESS – "User Initiated"
[ℹ]  1 error(s) occurred and cluster hasn't been created properly, you may wish to check CloudFormation console
[ℹ]  to cleanup resources, run 'eksctl delete cluster --region=ap-northeast-1 --name=cluster-in-existing-vpc'
[✖]  waiting for CloudFormation stack "eksctl-cluster-in-existing-vpc-cluster" to reach "CREATE_COMPLETE" status: ResourceNotReady: failed waiting for successful resource state
[✖]  failed to create cluster "cluster-in-existing-vpc"
```

```
AWS::EC2::VPC/VPC: CREATE_FAILED – "Value () for parameter cidrBlock is invalid. This is not a valid CIDR block.
```

when i checked CFn Template on Management Console, VPC CiderBlock was `""`.
```
		"VPC": {
			"Type": "AWS::EC2::VPC",
			"Properties": {
				"CidrBlock": "",
				"EnableDnsHostnames": true,
				"EnableDnsSupport": true,
				"Tags": [
					{
						"Key": "Name",
						"Value": {
							"Fn::Sub": "${AWS::StackName}/VPC"
						}
					}
				]
			}
		},
```

**Comment by procyclinsur** [comment]
@taishin 

I have been having various errors with an existing vpc too.   for this you should be able to fix it by adding the vpc-id

```
vpc:
  id: vpc-id123456
  subnets:
    Private:
      us-east-1a:
          id: subnet-id123456
      us-east-1b:
          id: subnet-id123456
    Public:
      us-east-1a:
          id: subnet-id123456
      us-east-1b:
          id: subnet-id123456
```
