### ISSUE TITLE
Support for calico ANNOTATE_POD_IP permissions on aws-node

### ISSUE THREAD

**Issue by rdubya16** [weaveworks/eksctl#4372]
**What feature/behavior/change do you want?**
Support for adding the permission to aws-node cluster role to enable ANNOTATE_POD_IP for calico. This resolves a longstanding issue with calico where pods dont have network access when they first come online

https://github.com/aws/amazon-vpc-cni-k8s#annotate_pod_ip-v193

Requires the following permission on aws-node clusterrole

```
cat << EOF > append.yaml
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - patch
EOF
```

**Why do you want this feature?**
We require this feature to continue to manage aws-node clusterrole with eksctl rather than having to manage it ourselves.
