### ISSUE TITLE
Malformed user data using Windows Server 20H2 AMIs

### ISSUE THREAD

**Issue by harisokanovic** [weaveworks/eksctl#4373]
**What were you trying to accomplish?**
Create a cluster running Windows 20H2 (build x.x.19042) worker nodes. Using image "Windows_Server-20H2-English-Core-EKS_Optimized-1.21", which is "ami-0482bd82359139871" in us-east-2.

**How to reproduce it?**
Run this command:
```
eksctl create nodegroup --config-file /path/to/cluster.yaml
```

With the following node group definition:
```
nodeGroups:
  - name: xxx-broken-node
    labels:
      os: windows
    taints:
      os: windows:NoSchedule
    instanceType: t3a.2xlarge
    ami: ami-0482bd82359139871 # Windows_Server-20H2-English-Core-EKS_Optimized-1.21 in us-east-2
    volumeSize: 300
    preBootstrapCommands:
      - "net user Administrator <omitted>"
      - "cscript C:\\Windows\\System32\\Scregedit.wsf /ar 0"
    privateNetworking: false
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
```

Eksctl hangs after the "waiting for at least 1 node(s) to become ready" message, and eventually times out.

**Workaround**
It seems that generated User Data in launch template is malformed. Eksctl writes some base64 encoded blob which the AMI doesn't seem to understand. The node successfully comes up after I manually change it.

Create new version of launch template and change User Data to the following...
```
<powershell>
[string]$EKSBootstrapScriptFile = "$env:ProgramFiles\Amazon\EKS\Start-EKSBootstrap.ps1"
net user Administrator <omitted>
cscript C:\Windows\System32\Scregedit.wsf /ar 0
& $EKSBootstrapScriptFile -EKSClusterName "besser" -APIServerEndpoint "https://<omitted>.us-east-2.eks.amazonaws.com" -Base64ClusterCA "<omitted>" -DNSClusterIP "<omitted>" -KubeletExtraArgs "--node-labels=os=windows,alpha.eksctl.io/cluster-name=<omitted>,alpha.eksctl.io/nodegroup-name=xxx-broken-node --register-with-taints=os=windows:NoSchedule" 3>&1 4>&1 5>&1 6>&1
</powershell>
```

**Versions**
```
$ eksctl info
eksctl version: 0.70.0
kubectl version: v1.22.2
OS: linux

$ uname -r
5.14.11-arch1-1
```
