### ISSUE TITLE
Deploy fails if S3 enpoint is already present.

### ISSUE THREAD

**Issue by TheNomet** [weaveworks/eksctl#4377]
**What were you trying to accomplish?**
Deploy a fully private EKS cluster withing an already existing VPC.
Given that the AWS account comes already set up with VPC and endpoints, it is not possible to use `eksctl` to deploy a private cluster. Unfortunately, the endpoints and VPC are already configured as per company policy, and it would be great to have the possibility to specify already existing endpoints while deploying.

**What happened?**
The stack creation fails because the endpoint for S3 is already existing.
```
route table rtb-xyz already has a route with destination-prefix-list-id pl-xyz (Service: AmazonEC2; Status Code: 400; Error Code: RouteAlreadyExists; Request ID: 8eb9524a-9cc6-4b78-b5de-a99bd0e24da0; Proxy: null)
```
**How to reproduce it?**
- Create a VPC, and specify the endpoint for S3.
- Substitute the vpc id with the one just created (as well as cidr and subnets)
- run `eksctl create cluster -f file.yaml`
```

--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-4
  region: eu-west-1

vpc:
  id: "vpc-123"
  cidr: "10.0.0.0/24"
  subnets:
    private:
      eu-west-1a:
        id: "subnet-123"
        cidr: "10.0.0.0/26" 

      eu-west-1b:
        id: "subnet-234"
        cidr: "10.0.0.64/26"

      eu-west-1c:
        id: "subnet-345"
        cidr: "10.0.0.128/26"

privateCluster:
  enabled: true
  additionalEndpointServices:
  - "autoscaling"

nodeGroups:
  - name: ng-2
    instanceType: t3.medium
    desiredCapacity: 2
    ami: ami-123
    privateNetworking: true
```

**Logs**
![image](https://user-images.githubusercontent.com/15369570/139249317-c8f72e59-35a4-4ab5-84b5-c88414d68406.png)

**Versions**
eksctl version: 0.70.0
