### ISSUE TITLE
Eksctl Version 0.71.0 Breaks Deploying Linux GPU Spot Instances

### ISSUE THREAD

**Issue by TediPapajorgji** [weaveworks/eksctl#4399]
**What were you trying to accomplish?**
Attempting to deploy a new nodegroup composed of only Linux GPU Spot instances.

**What happened?**
The following error was returned (yes it's cut off at the end, this is exactly what was outputted from eksctl):
`Error: couldn't create cluster provider from options: GPU instance types are not supported for`

**How to reproduce it?**
Using the following config file:

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: resemble-cluster
  region: us-east-1

availabilityZones: 
  - us-east-1c
  - us-east-1d
  - us-east-1f
  - us-east-1b

nodeGroups:
  - name: ng-gpu-spot-free-newstrategy-tier
    labels: { lifecycle: spot-free }
    minSize: 1
    maxSize: 2
    desiredCapacity: 1
    volumeSize: 110
    ami: auto
    instancesDistribution:
      instanceTypes: [ "g4dn.xlarge", "g4dn.2xlarge", "p2.xlarge" ]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0
      spotAllocationStrategy: "capacity-optimized-prioritized"
      maxPrice: 0.50
    asgMetricsCollection:
      - granularity: 1Minute
        metrics:
          - GroupMinSize
          - GroupMaxSize
          - GroupDesiredCapacity
          - GroupInServiceInstances
          - GroupPendingInstances
          - GroupStandbyInstances
          - GroupTerminatingInstances
          - GroupTotalInstances
cloudWatch:
  clusterLogging:
    enableTypes:
      - "controllerManager"
      - "scheduler"
```

And running the following command:
`eksctl create nodegroup --config-file=config.yaml --include=ng-gpu-spot-free-newstrategy-tier`

**Logs**

Output:

```
eksctl create nodegroup --config-file=config.yaml --include=ng-gpu-spot-free-newstrategy-tier
Error: couldn't create cluster provider from options: GPU instance types are not supported for
```

**Anything else we need to know?**
This issue does not occur on version `0.70.0` - i downgraded to this version and was able to successfully run the above commands. 

**Versions**
`0.71.0`

**Comment by cPu1** [comment]
Thanks for the detailed bug report. We'll work on this and make sure a fix is out this week. In the meantime, you can work around this by setting `amiFamily: AmazonLinux2` in your nodegroup config.

**Comment by cPu1** [comment]
The fix is merged. It should be out in the next release.

**Comment by Guillermogsjc** [comment]
Hi, eksctl `0.73.0` here, and obtaining from:

```yaml
- name: gpu
    labels:
      lifecycle: Ec2Spot
      nodegroup_name: gpu
      nodegroup_ratio: gpu-1to4
      aws.amazon.com/spot: "true"
      k8s.amazonaws.com/accelerator: nvidia-tesla-t4
      accelerator: 'nvidia'
    tags:
      k8s.io/cluster-autoscaler/node-template/label/lifecycle: Ec2Spot
      k8s.io/cluster-autoscaler/node-template/label/nodegroup_name: gpu
      k8s.io/cluster-autoscaler/node-template/label/nodegroup_ratio: gpu-1to4
      k8s.io/cluster-autoscaler/node-template/label/k8s.amazonaws.com/accelerator: nvidia-tesla-t4
      k8s.amazonaws.com/accelerator: nvidia-tesla-t4
      k8s.io/cluster-autoscaler/node-template/label/aws.amazon.com/spot: "true"
      k8s.io/cluster-autoscaler/node-template/taint/spotInstance: "true:PreferNoSchedule"
      k8s.io/cluster-autoscaler/node-template/taint/nvidia.com/gpu: 'present:NoSchedule'
      k8s.io/cluster-autoscaler/node-template/resources/cpu: "4"
      k8s.io/cluster-autoscaler/node-template/resources/memory: "16384Mi"
      eks_billing_cluster: {{cluster_name}}
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true
        albIngress: true
    taints:
      spotInstance: true:PreferNoSchedule
      nvidia.com/gpu: present:NoSchedule
    desiredCapacity: 0
    minSize: 0
    maxSize: {{nodegroup_max_size}}
    privateNetworking: true
    instancesDistribution:
      maxPrice: {{gpu_max_price}}
      instanceTypes:
        - g4dn.2xlarge
      #      - p2.xlarge

      onDemandBaseCapacity: {{on_demand_base}}
      onDemandPercentageAboveBaseCapacity: {{on_demand_proportion}
      spotAllocationStrategy: {{spot_allocation_strategy}}
```
(brackets are jinja values out of interest here)

and when performing creation (trhere arare other nodegroups without CPU that are alive in the cluster), I get this log:

```shell
Error: couldn't create cluster provider from options: GPU instance types are not supported for 
NAME                                           STATUS   ROLES    AGE     VERSION               LIFECYCLE
ip-172-82-139-191.eu-west-1.compute.internal   Ready    <none>   155m    v1.20.11-eks-f17b81   Ec2Spot
ip-172-82-141-78.eu-west-1.compute.internal    Ready    <none>   166m    v1.20.11-eks-f17b81   Ec2Spot
ip-172-82-36-163.eu-west-1.compute.internal    Ready    <none>   179m    v1.20.11-eks-f17b81   Ec2Spot
ip-172-82-38-106.eu-west-1.compute.internal    Ready    <none>   5d10h   v1.20.11-eks-f17b81   Ec2Spot
```
Is there some definition that i could be missing?

Regards
