### ISSUE TITLE
Add support for Spot placement score in nodeGroups definition 

### ISSUE THREAD

**Issue by yahavb** [weaveworks/eksctl#4417]
**What feature/behavior/change do you want?**

AWS released https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-placement-score.html 
eksctl users has no way to declare the desired spot placement score hence require to run an AWS CLI command after the node group is provisioned. 

**Why do you want this feature?**

require to add something like `spotPlacmentScore` in below example instead of running AWS CLI 

```
instancesDistribution:
      instanceTypes: ["m5dn.xlarge",...]
      onDemandPercentageAboveBaseCapacity: 0
      onDemandBaseCapacity: 0
      spotAllocationStrategy: "capacity-optimized"
      spotPlacmentScore: 9
```
