### ISSUE TITLE
Managed node group upgrade using Bottlerocket fails

### ISSUE THREAD

**Issue by Anorlondo448** [weaveworks/eksctl#4423]
**What were you trying to accomplish?**
I tried upgrading a bottlerocket instance using `eksctl upgrade nodegroup`.
And I specified `kubernetes-version` as an option.

```
eksctl upgrade nodegroup --name=bottlerocket-nodegroup --cluster=cluster-name --kubernetes-version=1.21
```

**What happened?**
Upgrade fails.
The release version of the AMI that can be obtained from the kubernetes version is output as invalid.
(See below)

**How to reproduce it?**
- Create a managed node group using bottlerocket with `eksctl create nodegroup`.
- Upgrade with `--kubernetes-version` in `eksctl upgrade nodegroup`.
- Specifying the release version of the Bottlerocket AMI with `--release-version` succeeds.

**Logs**
- cli error output:
```
Error: error updating nodegroup stack: waiting for CloudFormation stack "eksctl-cluster-name-nodegroup-bottlerocket-nodegroup": ResourceNotReady: failed waiting for successful resource state
```

- CloudFormation error output:
```
Requested release version 1.21.4-20211013 is not valid for kubernetes version 1.21
```

**Anything else we need to know?**
In the following part, even the Bottlerocket AMI has acquired the AMI release version of Amazon Linux2.

https://github.com/weaveworks/eksctl/blob/7565de70d46cd0930929b834527e5a1368ecb46e/pkg/managed/service.go#L345

**Versions**
```
$ eksctl info
eksctl version: 0.72.0
kubectl version: v1.21.5
OS: darwin
```

**Comment by cPu1** [comment]
> This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 5 days.

Not stale, we need to look into this.

**Comment by Himangini** [comment]
@Anorlondo448 are you still having this issue? does the latest eksctl version help?

**Comment by aclevername** [comment]
I've managed to reproduce this issue:
```yaml
# NOTE: Bottlerocket AMI might not be available in all regions.
# Please check AWS official doc or below link for more details
# https://github.com/bottlerocket-os/bottlerocket/blob/develop/QUICKSTART.md#finding-an-ami
# A simple example of ClusterConfig object with Bottlerocket settings:
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: jk
  region: us-west-2
  version: "1.20"

managedNodeGroups:
  - name: mng1
    instanceType: m5.xlarge
    desiredCapacity: 1
    amiFamily: Bottlerocket
    labels:
      "network-locality.example.com/public": "true"
    bottlerocket:
      enableAdminContainer: true
      settings:
        motd: "Hello, eksctl!"
```

Upgrading this to `1.21` produced the same error, complaing that the `release_version` is invalid. As @Anorlondo448 points out we have hardcoded in AmazonLinux2 as the AMI type when fetching the release version, which is whats causing them problems.

I tried changing https://github.com/weaveworks/eksctl/blob/7565de70d46cd0930929b834527e5a1368ecb46e/pkg/managed/service.go#L345 to query for `bottlerocket` instead, but it appears there isn't a way to fetch the release version. 

For AL2  we query:
```
$ aws ssm get-parameter --name /aws/service/eks/optimized-ami/1.21/amazon-linux-2/recommended/release_version --region us-west-2
{
"Parameter": {
        "Name": "/aws/service/eks/optimized-ami/1.21/amazon-linux-2/recommended/release_version",
        "Type": "String",
        "Value": "1.21.5-20220112",
        "Version": 16,
        "LastModifiedDate": "2022-01-12T23:53:53.136000+00:00",
        "ARN": "arn:aws:ssm:us-west-2::parameter/aws/service/eks/optimized-ami/1.21/amazon-linux-2/recommended/release_version",
        "DataType": "text"
    }
}
```

However I cannot find the equivalent query for bottlerocket:
```
aws ssm get-parameter --name /aws/service/eks/optimized-ami/1.20/bottlerocket/recommended/release_version --region us-west-2

An error occurred (ParameterNotFound) when calling the GetParameter operation:
```

Looking at the docs here https://docs.aws.amazon.com/eks/latest/userguide/retrieve-ami-id-bottlerocket.html it suggests 
>aws ssm get-parameter --name /aws/service/bottlerocket/aws-k8s-1.21/x86_64/latest/image_id --region region-code --query "Parameter.Value" --output text


as a way to query for the `image_id`, it *should be* that you can replace `image_id` with `release_version` to get the release version, but that doesn't work either:
```
aws ssm get-parameter --name /aws/service/bottlerocket/aws-k8s-1.20/x86_64/latest/release_version --region us-west-2

An error occurred (ParameterNotFound) when calling the GetParameter operation:
```


## Why do we fetch the release version?
One thing I don't understand is why we are updating the `release_version` field as the method for updating the nodegroup version. Their is a more appropriate `version` field that is for kubernetes. Docs https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-nodegroup.html#cfn-eks-nodegroup-version

> Version
> The Kubernetes version to use for your managed nodes. By default, the Kubernetes version of the cluster is used, and this is the only accepted specified value. If you specify launchTemplate, and your launch template uses a custom AMI, then don't specify version, or the node group deployment will fail. For more information about using launch templates with Amazon EKS, see Launch template support in the Amazon EKS User Guide.
>
> Required: No
>
> Type: String

>ReleaseVersion
> The AMI version of the Amazon EKS optimized AMI to use with your node group (for example, 1.14.7-YYYYMMDD). By default, the latest available AMI version for the node group's current Kubernetes version is used. For more information, see Amazon EKS optimized Linux AMI Versions in the Amazon EKS User Guide.

> Note: Changing this value triggers an update of the node group if one is available. However, only the latest available AMI release version is valid as an input. You cannot roll back to a previous AMI release version.
>
> Required: No
>
> Type: String


Reading the docs it appears that its much simpler for us to just update `version` to the kubernetes version as a method of upgrading, as I don't see the value in fetching the `release_version`, which only appears to work for AL2.

I've confirmed manually the setting the `version` field in a bottlerocket template to the next version of kubernetes successfully upgrades it.
