### ISSUE TITLE
Add support for installing karpenter as part of eksctl create cluster

### ISSUE THREAD

**Issue by aclevername** [weaveworks/eksctl#4430]
As a user of eksctl
I want to be able to have karpenter pre-installed on my cluster
So that I don't have to go through a complicated manual install (which involves creating various AWS resources and modifying resources created by eksctl)

## Background
[Karpenter](https://karpenter.sh/docs/getting-started/) is a just-in-time node auto-scalling tool from AWS. `Karpenter automatically launches just the right compute resources to handle your cluster's applications. It is designed to let you take full advantage of the cloud with fast and simple compute provisioning for Kubernetes clusters.`. 

Currently if a user wants to install Karpenter onto an eksctl cluster they have to (paraphrasing from https://karpenter.sh/docs/getting-started/):
1. Tag subnets in the created cluster with tags that Karpenter can use to auto-
discover them.
1. Create necessary IAM resources (instance profile, node role, and controller
policy) to allow Karpenter and the nodes it provisions to have permissions they
need.
1. Create IAMIdentityMapping within the cluster created to allow nodes
provisioned to connect to the cluster.
1.  Create an IAM Role for Service Accounts (IRSA) to allow the Karpenter
controller to provision nodes for the cluster.
1. Install the Karpenter Helm chart.

The user would then create a set of `Provisioner` CRDs to setup karpenter, e.g:
```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: node.k8s.aws/capacity-type
      operator: In
      values: ["spot"]
  provider:
    instanceProfile: KarpenterNodeInstanceProfile-${CLUSTER_NAME}
    cluster:
      name: ${CLUSTER_NAME}
      endpoint: $(aws eks describe-cluster --name ${CLUSTER_NAME} --query "cluster.endpoint" --output json)
  ttlSecondsAfterEmpty: 30
```

Of these 5 steps, 4 of them already well-within scope for what eksctl can do (creating AWS resources and updating the iam-identitymapping config). Helm installation is a new mechanism- however pre-installing some resources is not new to eksctl, for example we support pre-installing [flux](https://eksctl.io/usage/gitops-v2/) and various addons (coredns etc).

## Proposal
A user should be able to provide within their cluster config:
```yaml
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-1
  region: eu-north-1
  
karpernter:
  version: 0.1.0 # example semver version
```

This will indicate to eksctl that it needs to create all the AWS resources above, and then install the helm chart at the specific version.

Q: Why is the user providing the version? Shouldn't it just be `karpenter: true/false` and then we install the latest version?
A: Two reasons:
  - Karpenter is a fast-moving-project. They do regular breaking changes between minor versions, so a user will care about a particular Karpenter version they want to install as their `Provisioner` CRDs will be tied to them.
  - Karpenter has also suggested to us that they might at a reasonable frequency change the set of IAM policies required. This means that eksctl will need to be kept up-to-date with the set of policies required for a given version. E.g.:
     - Karpenter `0.1.0` requires policy `x`
     - Karpenter `0.2.0` requires policy `x & y`

## All resources must be created in a separate stack (*IMPORTANT*)
Like with IAMServiceAccounts, and Fargate, lets create any karpenter-related resources in a new cloudformation stack. Not as part of the cluster stack. This is so it can be updated separately from the cluster stack :smile: 

### Version pinning suggestion (just an idea)
We need to pin eksctl to a "max version" of Karpenter, as we know that the set of AWS resources we create will work for version X, but might not work for a newer version. E.g.:
- `eksctl 0.74.0` was created/tested against `karpenter 0.3.0`. Then a new karpernter helm chart `0.4.0` comes along, that requires some new policies. Rather than letting an eksctl user of `0.74.0` install `0.4.0`, we should instead error and suggest the user update to the latest eksctl version.

Karpenter have indicated to us they would be willing to (try as an experiment) open PRs against eksctl when AWS resources change/new version of karpenter are released. This is shifting the cost of knowing what AWS resources we need to create, along with what the max karpenter version is to them. If we go down this route we should document how they can update this, and make the code/tests/integration-tests as easy as possible to contribute to.

## Acceptance Criteria
Happy path :partying_face: 

- As an eksctl user
- Who configured `karpenter.version` to a supported karpenter version
- When I do `eksctl create cluster -f config.yaml`
- I can see that karpenter is installed (pods running successfully) and
- I should be able to successfully deploy a [Provisioner](https://karpenter.sh/docs/provisioner-crd/) (to sanity-check the installation works)
- I should be able to find relevant docs

Sad path :cry: : 

- As an eksctl user
- Who configured `karpenter.version` to an un-supported karpenter version
- When I do `eksctl create cluster -f config.yaml`
- I should get an error telling me that the version it not supported and
- A suggestion of what version I can use instead
- I should be able to find relevant docs

Goes without saying the above criteria should be supported with well-tested performant code.
