### ISSUE TITLE
As a user of Karpenter I want the defaullt provisioner to be pre-installed

### ISSUE THREAD

**Issue by aclevername** [weaveworks/eksctl#4431]
Follow up from https://github.com/weaveworks/eksctl/issues/4430

As a user of eksctl
I want to be able to have the default provisioner pre-installed
So that I don't have to install it myself

Karpenter has a suggested default provisioner. You can indicate it should be installed by setting a helm chart value https://github.com/awslabs/karpenter/issues/784. Lets add a new field to the config:
```yaml
karpenter:
  version: 0.4.0
  installDefaultProvisioner: true # think of a better name
```
