### ISSUE TITLE
eksctl does not use ServiceAccount credentials access to kube-apiserver

### ISSUE THREAD

**Issue by jlandowner** [weaveworks/eksctl#4437]
**What were you trying to accomplish?**

I tried to use docker image `weaveworks/eksctl` in EKS Cluster to create IAM serviceaccount in my automation process.

**What happened?**

After IAM Role creation succeeded, creating the service account failed with checking whether namespace exist: Unauthorized.

I confirmed RBAC properly works by using kubectl in the Pod.

It seems eksctl does not support to use ServiceAccount credentials access to kube-apiserver.

**How to reproduce it?**

- `weaveworks/eksctl` container as Kubernertes Job

First, from the outside of EKS, create iamserviceaccount for eksctl Pod.

```sh
# AdministratorAccess is not good but I just use it to confirm IAM authentication is truely valid.
eksctl create iamserviceaccount --cluster mycluster --name eksctl --namespace kube-system --attach-policy-arn arn:aws:iam::aws:policy/AdministratorAccess
```

Next create eksctl Job, which create iamserviceaccount named `default` in `default` namespace.

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eksctl
rules:
- apiGroups:
  - '*'
  resources:
  - serviceaccounts
  - namespaces
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eksctl
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eksctl
subjects:
- kind: ServiceAccount
  name: eksctl
  namespace: kube-system
---
apiVersion: batch/v1
kind: Job
metadata:
  name: job
spec:
  template:
    spec:
      containers:
      - name: eksctl
        image: weaveworks/eksctl:0.72.0
        args:
        - create
        - iamserviceaccount
        - --cluster=mycluster
        - --name=default
        - --namespace=default
        - --attach-policy-arn=arn:aws:iam::aws:policy/AWSCodeCommitPowerUser
        - --override-existing-serviceaccounts
        - --approve
        env:
        - name: AWS_REGION
          value: ap-northeast-1
      serviceAccountName: eksctl
      restartPolicy: Never
```

After IAM Role is created successfully by CloudFormation stack, Job container failed with error `checking whether namespace exist: Unauthorized`

- Use eksctl binary in the Pod 

I also reproduce by using downloaded eksctl binary in the Pod. 
Without `--override-existing-serviceaccounts`, it failed at pre-check.

```sh
$ ls -l /var/run/secrets/kubernetes.io/serviceaccount/
合計 0
lrwxrwxrwx 1 root coder 13 11月  9 23:00 ca.crt -> ..data/ca.crt
lrwxrwxrwx 1 root coder 16 11月  9 23:00 namespace -> ..data/namespace
lrwxrwxrwx 1 root coder 12 11月  9 23:00 token -> ..data/token

$ eksctl create iamserviceaccount --cluster mycluster --name xxx --namespace default --attach-policy-arn arn:aws:iam::aws:policy/AWSCodeCommitPowerUser 
2021-11-09 22:35:26 [ℹ]  eksctl version 0.72.0
2021-11-09 22:35:26 [ℹ]  using region ap-northeast-1
Error: checking whether serviceaccount "default/xxx" exists: Unauthorized

# kubectl in the same Pod works well so RBAC is probably currect.
$ kubectl get sa -n default
NAME      SECRETS   AGE
default   1         35d
```

**Logs**

```sh
$ eksctl create iamserviceaccount --cluster mycluster --name xxx --namespace default --attach-policy-arn arn:aws:iam::aws:policy/AWSCodeCommitPowerUser -v 4
2021-11-09 23:13:39 [▶]  role ARN for the current session is "arn:aws:sts::ACCOUNT_ID:assumed-role/eksctl-mycluster-addon-iamserviceaccount-kube-Role1-xxxxx"
2021-11-09 23:13:39 [▶]  cluster = {
  Arn: "arn:aws:eks:ap-northeast-1:ACCOUNT_ID:cluster/mycluster",
  CertificateAuthority: {
    Data: "DATA"
  },
  CreatedAt: 2021-10-05 09:23:34.992 +0000 UTC,
  Endpoint: "https://xxxx.gr7.ap-northeast-1.eks.amazonaws.com",
  Identity: {
    Oidc: {
      Issuer: "https://oidc.eks.ap-northeast-1.amazonaws.com/id/xxxxx"
    }
  },
  KubernetesNetworkConfig: {
    ServiceIpv4Cidr: "10.100.0.0/16"
  },
  Logging: {
    ClusterLogging: [{
        Enabled: false,
        Types: [
          "api",
          "audit",
          "authenticator",
          "controllerManager",
          "scheduler"
        ]
      }]
  },
  Name: "mycluster",
  PlatformVersion: "eks.2",
  ResourcesVpcConfig: {
    ClusterSecurityGroupId: "sg-xxx",
    EndpointPrivateAccess: false,
    EndpointPublicAccess: true,
    PublicAccessCidrs: ["0.0.0.0/0"],
    SecurityGroupIds: ["sg-xxx"],
    SubnetIds: [
      "subnet-xxx",
      "subnet-xxx",
      "subnet-xxx",
      "subnet-xxx"
    ],
    VpcId: "vpc-xxx"
  },
  RoleArn: "arn:aws:iam::ACCOUNT_ID:role/eksctl-mycluster-cluster-ServiceRole-xxx",
  Status: "ACTIVE",
  Tags: {

  },
  Version: "1.21"
}
2021-11-09 23:13:39 [ℹ]  eksctl version 0.72.0
2021-11-09 23:13:39 [ℹ]  using region ap-northeast-1
2021-11-09 23:13:40 [▶]  iamserviceaccounts = [{
  Capabilities: ["CAPABILITY_IAM"],
  CreationTime: 2021-11-09 13:33:43.192 +0000 UTC,
  Description: "IAM role for serviceaccount \"default/xxx\" [created and managed by eksctl]",
  DisableRollback: false,
  DriftInformation: {
    StackDriftStatus: "NOT_CHECKED"
  },
  EnableTerminationProtection: false,
  Outputs: [{
      OutputKey: "Role1",
      OutputValue: "arn:aws:iam::ACCOUNT_ID:role/eksctl-mycluster-xxx-Role1-xxx"
    }],
  RollbackConfiguration: {

  },
  StackId: "arn:aws:cloudformation:ap-northeast-1:ACCOUNT_ID:stack/eksctl-mycluster-addon-iamserviceaccount-default-xxx/xxxxxxx",
  StackName: "eksctl-mycluster-addon-iamserviceaccount-cosmo-user-jinu-xxx",
  StackStatus: "CREATE_COMPLETE",
  Tags: [
    {
      Key: "alpha.eksctl.io/cluster-name",
      Value: "mycluster"
    },
    {
      Key: "eksctl.cluster.k8s.io/v1alpha1/cluster-name",
      Value: "mycluster"
    },
    {
      Key: "alpha.eksctl.io/iamserviceaccount-name",
      Value: "cosmo-user-jinu/xxx"
    },
    {
      Key: "alpha.eksctl.io/eksctl-version",
      Value: "0.72.0"
    }
  ]
} {
  Capabilities: ["CAPABILITY_IAM"],
  CreationTime: 2021-10-05 09:51:39.701 +0000 UTC,
  Description: "IAM role for serviceaccount \"kube-system/aws-load-balancer-controller\" [created and managed by eksctl]",
  DisableRollback: false,
  DriftInformation: {
    StackDriftStatus: "NOT_CHECKED"
  },
  EnableTerminationProtection: false,
  Outputs: [{
      OutputKey: "Role1",
      OutputValue: "arn:aws:iam::ACCOUNT_ID:role/eksctl-mycluster-addon-iamserviceaccount-kub-Role1-xxxxx"
    }],
  RollbackConfiguration: {

  },
  StackId: "arn:aws:cloudformation:ap-northeast-1:ACCOUNT_ID:stack/eksctl-mycluster-addon-iamserviceaccount-kube-system-aws-load-balancer-controller/xxxxx",
  StackName: "eksctl-mycluster-addon-iamserviceaccount-kube-system-aws-load-balancer-controller",
  StackStatus: "CREATE_COMPLETE",
  Tags: [
    {
      Key: "alpha.eksctl.io/cluster-name",
      Value: "mycluster"
    },
    {
      Key: "eksctl.cluster.k8s.io/v1alpha1/cluster-name",
      Value: "mycluster"
    },
    {
      Key: "alpha.eksctl.io/iamserviceaccount-name",
      Value: "kube-system/aws-load-balancer-controller"
    },
    {
      Key: "alpha.eksctl.io/eksctl-version",
      Value: "0.68.0"
    }
  ]
} {
  Capabilities: ["CAPABILITY_IAM"],
  CreationTime: 2021-10-05 09:39:20.149 +0000 UTC,
  Description: "IAM role for serviceaccount \"kube-system/aws-node\" [created and managed by eksctl]",
  DisableRollback: false,
  DriftInformation: {
    StackDriftStatus: "NOT_CHECKED"
  },
  EnableTerminationProtection: false,
  Outputs: [{
      OutputKey: "Role1",
      OutputValue: "arn:aws:iam::ACCOUNT_ID:role/eksctl-mycluster-addon-iamserviceaccount-kub-Role1-xxxxx"
    }],
  RollbackConfiguration: {

  },
  StackId: "arn:aws:cloudformation:ap-northeast-1:ACCOUNT_ID:stack/eksctl-mycluster-addon-iamserviceaccount-kube-system-aws-node/xxxxxx",
  StackName: "eksctl-mycluster-addon-iamserviceaccount-kube-system-aws-node",
  StackStatus: "CREATE_COMPLETE",
  Tags: [
    {
      Key: "alpha.eksctl.io/cluster-name",
      Value: "mycluster"
    },
    {
      Key: "eksctl.cluster.k8s.io/v1alpha1/cluster-name",
      Value: "mycluster"
    },
    {
      Key: "alpha.eksctl.io/iamserviceaccount-name",
      Value: "kube-system/aws-node"
    },
    {
      Key: "alpha.eksctl.io/eksctl-version",
      Value: "0.68.0"
    }
  ]
}]
Error: checking whether serviceaccount "default/xxx" exists: Unauthorized
```

**Anything else we need to know?**

**Versions**

```sh
$ eksctl info
eksctl version: 0.72.0
kubectl version: v1.21.2-13+d2965f0db10712
OS: linux
```

### Summary
We need to investigate and try to reproduce this issue to determine if the problem is with eksctl

**Comment by jlandowner** [comment]
@Skarlso 
Yes probably. I tried with [minimum policies](https://eksctl.io/usage/minimum-iam-policies/), and also with even AdministratorAccess as I mentioned above. 

For Kubernetes RBAC, I attached serviceaccount and namespace full access.

**Comment by jlandowner** [comment]
I think here is the code error occured.
https://github.com/weaveworks/eksctl/blob/main/pkg/kubernetes/namespace.go#L52

I think the reason to get error here is kubernetes clientset is invalid. 

The func `CheckNamespaceExist()` is called at here.
https://github.com/weaveworks/eksctl/blob/main/pkg/cfn/manager/create_tasks.go#L145-L147

So I think that I met creating IAM Role in CloudFormation is successful and just creating serviceaccount and annotating `eks.amazonaws.com/role-arn` on serviceaccount (and checking namespace is present) is failed.

**Comment by Skarlso** [comment]
Not stale, we still need to investigate this.

**Comment by benmedapp** [comment]
So I know it's not great (not following least privileged) but you can add the get namespaces permission to system:node and this will work.
`kubectl edit clusterrole system:node`
add this:
`- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get`

**Comment by cPu1** [comment]
What you're trying to achieve does not make much sense with eksctl. You're running eksctl as a pod which is given access to Kubernetes resources via a service account. However, eksctl does not authenticate with Kubernetes via the in-cluster `ServiceAccount` token mounted at `/var/run/secrets/kubernetes.io/serviceaccount`. Instead, it obtains access to Kubernetes resources via the mapping specified in the `aws-auth` ConfigMap, so the IAM role/user being used should map to a Kubernetes group that has access to the required Kubernetes resources. In short, the eksctl pod will use the specified IRSA to access AWS resources, not Kubernetes resources. You can achieve what you're trying to do by following these steps:


**Create IRSA**
```shell
$ eksctl create iamserviceaccount --cluster=<cluster> --name=eksctl --namespace=kube-system --attach-policy-arn=arn:aws:iam::aws:policy/AdministratorAccess --role-name=eksctl-role --override-existing-serviceaccounts --approve
```

**Map ARN to a Kubernetes group**
```shell
$ eksctl create iamidentitymapping --cluster=<cluster> --group=eksctl --arn=arn:aws:iam::<account>:role/eksctl-role
```

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eksctl
rules:
  - apiGroups:
      - '*'
    resources:
      - serviceaccounts
      - namespaces
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eksctl
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eksctl
subjects:
  - kind: Group
    name: eksctl

```
