### ISSUE TITLE
Managed NodeGroups not working properly with VPC CNI addon on cluster creation

### ISSUE THREAD

**Issue by nicogl** [weaveworks/eksctl#4478]
**What were you trying to accomplish?**
I create an EKS cluster with eksctl and a config file schema. It has some managed nodegroups with instance type _t3.small_ and the latest version of _vpc-cni_ addon [in order to increase the maximum quantity of pods per node](https://aws.amazon.com/blogs/containers/amazon-vpc-cni-increases-pods-per-node-limits/).
All cluster requirements are properly set, including IAM permissions, reservations of subnets' CIDR blocks, etc.

**What happened?**
The cluster is successfully created along with its nodegroups and the vpc-cni addon. It works fine and pods get scheduled and keep running without issues. However, when I describe any of the nodes (`kubectl describe node <node_id>`) I see the maximum allocatable pod quantity is 11, which is the [standard limit for the t3.small instance type](https://github.com/awslabs/amazon-eks-ami/blob/master/files/eni-max-pods.txt) instead of 110 which is the increased number obtained with the vpc-cni addon.

The interesting thing is that if I create a new nodegroup with the same settings as the previous one and without touching anything related to the cluster, then when I describe the nodes of the new nodegroup they show a maximum of 110 pods.

It seems that the vpc-cni addon functionality doesn't take effect on the nodegroups that are created at the same moment of the cluster creation. Only the nodegroups that are created after the cluster spin-up process has finished get properly affected.

Note that I even tried with `maxPodsPerNode:` property in the config file but didn't fix the issue.

**How to reproduce it?**
Config file:

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: my-cluster-name
  region: us-west-2
  tags:
    eks-cluster-name: my-cluster-name
    creation-time: 2021-11-19 04:47:21 UTC   
addons:
  - name: vpc-cni
    version: latest
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
iam:
  fargatePodExecutionRoleARN: arn:aws:iam::XXXXXXXXXXXXXXX
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: aws-node
        namespace: kube-system
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
    - metadata:
        name: ebs-csi-controller-sa 
        namespace: kube-system
      attachPolicyARNs:
        - arn:aws:iam::XXXXXXXXXXXXXXX
    - metadata:
        name: efs-csi-controller-sa
        namespace: kube-system
      attachPolicyARNs:
        - arn:aws:iam::XXXXXXXXXXXXXXX
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      attachPolicyARNs:
        - arn:aws:iam::XXXXXXXXXXXXXXX
        - arn:aws:iam::XXXXXXXXXXXXXXX
vpc:
  id: vpc-YYYYYYYYYY
  subnets:
    private:
      private-subnet-XXXXXXXXXX:
        id: subnet-XXXXXXXXXX
      private-subnet-YYYYYYYYYY:
        id: subnet-YYYYYYYYYY
      private-subnet-ZZZZZZZZZ:
        id: subnet-ZZZZZZZZZ
    public:
      public-subnet-AAAAAAAAAA:
        id: subnet-AAAAAAAAAA
      public-subnet-BBBBBBBBBB:
        id: subnet-BBBBBBBBBB
      public-subnet-CCCCCCCCCC:
        id: subnet-CCCCCCCCCC
managedNodeGroups:
  - name: my-managed-ng-us-west-2a
    availabilityZones:
      - us-west-2a
    instanceType: t3.small
    maxPodsPerNode: 110
    volumeSize: 16
    minSize: 0
    maxSize: 2
    iam:
      instanceRoleARN: arn:aws:iam::XXXXXXXXXXXXXXXX
    privateNetworking: true
    ssh:
      allow: true
      publicKeyName: key_name
    desiredCapacity: 2  
  - name: another-managed-ng-west-2a
    availabilityZones:
      - us-west-2a
    instanceType: t3.small
    maxPodsPerNode: 110
    volumeSize: 16
    labels:
      dedicated: apps
    minSize: 0
    maxSize: 2
    iam:
      instanceRoleARN: arn:aws:iam::XXXXXXXXXXXXXXX
    privateNetworking: true
    ssh:
      allow: true
      publicKeyName: key_name
    taints:
      - key: dedicated
        value: apps
        effect: NoSchedule
    desiredCapacity: 2 
fargateProfiles:
  - name: fp-default
    podExecutionRoleARN: arn:aws:iam::XXXXXXXXXXXXXXXXX
    selectors:
      - namespace: default
```

**Versions**
```
eksctl version: 0.73.0
kubectl version: v1.21.2
OS: linux
```
