### ISSUE TITLE
More control over nodegroup SGs

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#448]
This is a follow-up to #419.

We now have:

- control plane SG
- shared SG that allows inter-node traffic on all ports and all protocols, no CIDR-based rules, it lives inside the cluster stack
- per-nodegroup SGs are used to only control the following types of traffic:
  - inter-VPC traffic (e.g. for SSH)
  - access to high ports from outside the cluster
  - bindings for control-plane SG
  - opening any ports to the outside world

One currenly can:
- provide custom control plane SG
- provide custom share node SG
- opt-out from shared node SG
- add extra SGs per-nodegroup

It should be possible to customise per-nodegroup SGs:

- provide a pre-existing SG 
- customise ports used per-nodegroup, e.g.:
  - extend the range of ports that are open
  - do not open any ports to the outside world

**Comment by cdenneen** [comment]
I need this to allow SSH access to nodeGroup workers from machines over Direct Connect. So need option of adding `extraCIDRs` to `nodeGroups` possibly as hash with array of ports:

```
nodeGroups:
  - name: workers
    securityGroups:
      extraCIDRs:
        - 10.1.10.0/24: 
          - 22
          - 3000
        - 10.4.22.0/24: 
          - 22
```

 or at least under the `ssh` struct:
```
nodeGroups:
  - name: workers1
    ssh:
      allow: true
      extraCIDRs:
      - 10.1.10.0/24
      - 10.4.22.0/24
