### ISSUE TITLE
Managed Nodegroup with spot instance using cluster file

### ISSUE THREAD

**Issue by ngoyal16** [weaveworks/eksctl#4517]
We want to create managed nodegroup using file based configuraion but couldn't able to find how to do it.

for unmanaged nodegroup there is options

```
   instancesDistribution:
      instanceTypes:
        - t3.medium
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0
```

but for managed nodes i couldn't find such options.
