### ISSUE TITLE
`kubeletExtraConfig` - `containerLogMaxSize` not working

### ISSUE THREAD

**Issue by lazarkrstic** [weaveworks/eksctl#4518]
**What were you trying to accomplish?**
The goal is getting complete log of Kuberntes job (container stdout). Log can be large, around 200MB.
 **What happened?**
I created EKS using eksctl tool and than added a new node group.  I am using `kubeletExtraConfig` for setting log maximum size of `500MB`, but it's not working. I still get only **tail** of container log. The size of returned log is `2.39MB`.
**How to reproduce it?**
First create the node group:
```` YAML
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: <cluster-name>
  region: eu-central-1

nodeGroups:
  - name: worker-spot-large-log
    labels: { instance-type: spot }
    instanceType: t3.large
    minSize: 2
    maxSize: 30
    desiredCapacity: 2
    availabilityZones: ["eu-central-1a", "eu-central-1b", "eu-central-1c"]
    kubeletExtraConfig:
        containerLogMaxSize: "500Mi"
        containerLogMaxFiles: 5
````
And then apply job (be avare of sheduling job to target node grop). I created demo docker image for genereating random data to stdout based on commnad `head -c $1 </dev/urandom` 
````YAML
apiVersion: batch/v1
kind: Job
metadata:
  name: log-large-data
spec:
  template:
    spec:
      containers:
      - name: log-large-data
        image: krstic94/generate-log
        args: ["10M"]
        resources:
          requests:
            memory: "1.5Gi"
            cpu: "1024m"
          limits:
            memory: "2Gi"
            cpu: "2048m"
      restartPolicy: Never
  backoffLimit: 4
````

**Versions**
```
eksctl version: 0.76.0
kubectl version: v1.21.3
OS: windows
```
