### ISSUE TITLE
No access to worker nodes via SSH when using config file.

### ISSUE THREAD

**Issue by procyclinsur** [weaveworks/eksctl#453]
**What happened?**
Successfully created cluster with options required, but have no SSH access to nodes when using config file.

**What you expected to happen?**
I expect that when I specify `allowSSH: true` and `sshPublicKeyPath: my_key_name` that I will be allowed to access the worker nodes via SSH after creation.

**How to reproduce it?**
1. Create config file as below.

```yaml
apiVersion: eksctl.io/v1alpha3
kind: ClusterConfig

metadata:
  name: kube-cluster
  region: us-east-1
  tags: {environment: staging, creator: scott}

vpc:
  id: vpc-088d4632
  subnets:
    Private:
      us-east-1a:
          id: subnet-0b73f418
      us-east-1b:
          id: subnet-0c92168f
    Public:
      us-east-1a:
          id: subnet-0f960edf
      us-east-1b:
          id: subnet-011a8697

availabilityZones: ["us-east-1a", "us-east-1b"]

nodeGroups:
  - name: kube-cluster-ng-1
    instanceType: m5.large
    desiredCapacity: 2
    minSize: 1
    maxSize: 5
    availabilityZones: ["us-east-1a", "us-east-1b"]
    ami: auto
    volumeSize: 50
    allowSSH: true
    sshPublicKeyPath: my-key.pem
```

2. Create cluster with the following command.

```bash
eksctl create cluster -f atp-kube-cluster.yml
```

3. Attempt to access node.

```bash
ssh -i my-key.pem root@18.212.138.180 -vvv
```

**Anything else we need to know?**
OS: Fedora28
Binary: Downloaded
creds: awscmd configure type

My AWS key name itself includes the .pem extension for some reason.

**Versions**
```bash
[procyclinsur@localhost atp-kube-cluster]$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.1.17"}
[procyclinsur@localhost atp-kube-cluster]$ uname -a
Linux localhost.localdomain 4.19.13-200.fc28.x86_64 #1 SMP Sat Dec 29 23:10:35 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
[procyclinsur@localhost atp-kube-cluster]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"archive", BuildDate:"2018-04-26T09:29:05Z", GoVersion:"go1.10.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-eks-6bad6d", GitCommit:"6bad6d9c768dc0864dab48a11653aa53b5a47043", GitTreeState:"clean", BuildDate:"2018-12-06T23:13:14Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
`heptio-authenticator-aws` not installed.

**Logs**

EKSCTL

```bash
eksctl create cluster -f kube-cluster.yml 
[ℹ]  using region us-east-1
[✔]  using existing VPC (vpc-088d4632821fe0f52) and subnets (private:[subnet-0b73f4183e00d028c subnet-0c92168f3faeed699] public:[subnet-0f960edf42d22b955 subnet-011a8697711f41dd6])
[!]  custom VPC/subnets will be used; if resulting cluster doesn't function as expected, make sure to review the configuration of VPC/subnets
[ℹ]  nodegroup "kube-cluster-ng-1" will use "ami-0c24db5df6badc35a" [AmazonLinux2/1.11]
[ℹ]  SSH public key file "my-key.pem" does not exist; will assume existing EC2 key pair
[ℹ]  found EC2 key pair "my-key.pem"
[ℹ]  creating EKS cluster "kube-cluster" in "us-east-1" region
[ℹ]  will create 2 separate CloudFormation stacks for cluster itself and the initial nodegroup
[ℹ]  if you encounter any issues, check CloudFormation console or try 'eksctl utils describe-stacks --region=us-east-1 --name=kube-cluster'
[ℹ]  creating cluster stack "eksctl-kube-cluster-cluster"
[ℹ]  creating nodegroup stack "eksctl-kube-cluster-nodegroup-kube-cluster-ng-1"
[ℹ]  as --nodes-min=1 and --nodes-max=5 were given, default value of --nodes=2 was kept as it is within the set range
[✔]  all EKS cluster resource for "kube-cluster" had been created
[✔]  saved kubeconfig as "/home/procyclinsur/.kube/config"
[ℹ]  nodegroup "kube-cluster-ng-1" has 0 node(s)
[ℹ]  waiting for at least 1 node(s) to become ready in "kube-cluster-ng-1"
[ℹ]  nodegroup "atp-kube-cluster-ng-1" has 2 node(s)
[ℹ]  node "ip-10-20-102-99.ec2.internal" is ready
[ℹ]  node "ip-10-20-208-54.ec2.internal" is ready
[ℹ]  kubectl command should work with "/home/procyclinsur/.kube/config", try 'kubectl get nodes'
[✔]  EKS cluster "kube-cluster" in "us-east-1" region is ready
```

SSH

```bash
[procyclinsur@localhost Downloads]$ ssh -i my-key.pem root@18.212.138.180 -vvv
OpenSSH_7.8p1, OpenSSL 1.1.0i-fips  14 Aug 2018
debug1: Reading configuration data /home/procyclinsur/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug3: /etc/ssh/ssh_config line 52: Including file /etc/ssh/ssh_config.d/05-redhat.conf depth 0
debug1: Reading configuration data /etc/ssh/ssh_config.d/05-redhat.conf
debug3: /etc/ssh/ssh_config.d/05-redhat.conf line 2: Including file /etc/crypto-policies/back-ends/openssh.config depth 1
debug1: Reading configuration data /etc/crypto-policies/back-ends/openssh.config
debug3: gss kex names ok: [gss-gex-sha1-,gss-group14-sha1-]
debug3: kex names ok: [curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1]
debug1: /etc/ssh/ssh_config.d/05-redhat.conf line 8: Applying options for *
debug2: resolve_canonicalize: hostname 18.212.138.180 is address
debug2: ssh_connect_direct
debug1: Connecting to 18.212.138.180 [18.212.138.180] port 22.
debug1: connect to address 18.212.138.180 port 22: Connection timed out
ssh: connect to host 18.212.138.180 port 22: Connection timed out
```
