### ISSUE TITLE
Nodegroup XXX failed to stabilize: The specified instance type XXXX is not valid

### ISSUE THREAD

**Issue by tdeheurles** [weaveworks/eksctl#4544]
**What were you trying to accomplish?**
```
$ eksctl create nodegroup
```
the configuration uses instanceSelector:
```
instanceSelector:
    vCPUs: 4
    memory: "8"
    cpuArchitecture: x86_64
```

**What happened?**
The provided instance type seems not compatible with eks AMI.

**Logs**
```
2021-12-15 18:46:05 [✖]  AWS::EKS::Nodegroup/ManagedNodeGroup: CREATE_FAILED – "Nodegroup XXXXX failed to stabilize: [{Code: Ec2LaunchTemplateInvalidConfiguration,Message: The specified instance type c6i.xlarge is not valid,ResourceIds: [XXXXXX]}]"
```

**Versions**
```
eksctl info
eksctl version: 0.76.0
kubectl version: v1.22.4
OS: linux
aws region: eu-west-2
```

Note that I'm using eksctl for around 1 year now without problem of this kind.

**Comment by tdeheurles** [comment]
I tried to move instanceSelector to:
```
vCPUs: 2
memory: "4"
cpuArchitecture: x86_64
```
but the result is the same with:
```
Nodegroup XXXX failed to stabilize: [{Code: Ec2LaunchTemplateInvalidConfiguration,Message: The specified instance type c6i.large is not valid,ResourceIds: [XXXX]}]
```

**Comment by Skarlso** [comment]
Hey @tdeheurles!

Thanks for opening an issue.

We are using https://github.com/aws/amazon-ec2-instance-selector/ to select instances, so it might be worth putting this issue there as well and link back to us. We just pass on this, so the selection goes wrong there, I believe.

**Comment by tdeheurles** [comment]
Hey @Skarlso, [there is already an issue on this topic on aws-ec2-instance-selector](https://github.com/aws/amazon-ec2-instance-selector/issues/108).

What seems weird is `suket22's answer`, he is saying that his attempt to start node group with c6i.xlarge did succeed.

*Could it be some configuration or version that are outdated on my side ?*
I'm happy to return you any information you ask.

**Comment by Skarlso** [comment]
Uh, interesting. I'll look into it. Thanks for the link.

**Comment by tdeheurles** [comment]
Those c *6* are not old. Could it be that eksctl 0.76.0 selected AMI is out dated compared to what exepect new c6 instance type ?
(It's surprising but I feel uncompatibility could come from their no ?)

**Comment by Skarlso** [comment]
It's not complaining about the AIM. It's complaining that the actual Type doesn't exist, no?

**Comment by Skarlso** [comment]
Can you try a different region? Just for the heck of it.

**Comment by tdeheurles** [comment]
We are trying to start the node group with the latest AMI.

*Trying another region will be a bit more complex for me atm as we blocked other regions with SCP.*

**Comment by tdeheurles** [comment]
Using the AMI from the [aws official list](https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html) didn't solve the problem.

To me aws-ec2-selector behavior is correct, it returns what is the current expected instance type.

The problem is we have an uncompatibility **somewhere** in our node group configuration. I did hope for the AMI, but maybe that one is not updated yet (maybe latest eks AMI is still uncompatible with c6 instance type).

One option, could be to rollback the version of the aws-selector until that uncompatibility is fixed. But I have no idea of the behavior of the tool. Can we force C5 instead of C6 ?

I don't have much time to spend on this issue at the moment, I will force the use of c5 instance again. And come back to that later.

**Comment by Skarlso** [comment]
Thanks for the update @tdeheurles! I'll try looking into this when I can.

**Comment by cPu1** [comment]
>The problem is we have an uncompatibility somewhere in our node group configuration. I did hope for the AMI, but maybe that one is not updated yet (maybe latest eks AMI is still uncompatible with c6 instance type).

@tdeheurles can you share your nodegroup config to help us debug your issue?

**Comment by tdeheurles** [comment]
sure, here it is:
```
    -   name: xxxxx
        amiFamily: AmazonLinux2
        availabilityZones: ["eu-west-1a","eu-west-1b","eu-west-1c"]
        minSize: 1
        maxSize: 1
        volumeSize: 120
        labels:
            cartel: xxxx
            env: xxxx
            role: xxxx
        privateNetworking: true
        tags:
            cartel: xxxx
            env: xxxx
            role: xxxx
        iam:
          withAddonPolicies:
            cloudWatch: true
        ebsOptimized: true
        volumeType: gp3
        instanceSelector:
            vCPUs: 4
            memory: "8"
            cpuArchitecture: x86_64
        spot: true
        taints:
            -   key: env
                value: xxxx
                effect: "NoSchedule"
            -   key: role
                value: xxxx
                effect: "NoSchedule"
```
