### ISSUE TITLE
Set auto-assign public IP with eksctl config (not at subnet level)

### ISSUE THREAD

**Issue by brsolomon-deloitte** [weaveworks/eksctl#4546]
We are attempting to create a fully-private EKS cluster using an existing VPC.

The public IPv4 addressing attribute for our subnets is set to FALSE (do not auto-assign public IP) and we do not have the ability to change this setting at the subnet level.

We are hoping the ability exists to effectively set this attribute to true only for the nodes provisioned by `eksctl`. Is such a thing configurable through the `eksctl` config file? It is unclear from [this blog post](https://aws.amazon.com/blogs/containers/upcoming-changes-to-ip-assignment-for-eks-managed-node-groups/) and the eksctl reference whether this is configurable through the eksctl YAML config file.

Currently we receive a `CREATE_FAILED` for the managed nodegroup:

> Nodegroup ng-xxxxx-test failed to stabilize: [{Code: Ec2SubnetInvalidConfiguration,Message: One or more Amazon EC2 Subnets of [subnet-zzzzzz] for node group ng-xxxxx-test does not automatically assign public IP addresses to instances launched into it. If you want your instances to be assigned a public IP address, then you need to enable auto-assign public IP address for the subnet. See IP addressing in VPC guide: https://docs.aws.amazon.com/vpc/latest/userguide/vpc-ip-addressing.html#subnet-public-ip,ResourceIds: [subnet-zzzzzz]}]

This results from using the following eksctl config:

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: "xxxxx"
  region: us-east-2
  version: "1.21"

vpc:
  autoAllocateIPv6: false
  clusterEndpoints:
    publicAccess: false
    privateAccess: true
  sharedNodeSecurityGroup: "sg-xxxxx"
  subnets:
    private:
      us-east-2c:
        id: subnet-xxxxx
      us-east-2b:
        id: subnet-xxxxx
      us-east-2a:
        id: subnet-xxxxx

managedNodeGroups:
- name: "xxxxx"
  amiFamily: "AmazonLinux2"
  desiredCapacity: 3
  instanceType: "m5.4xlarge"
  volumeSize: 32
  privateNetworking: true
```
