### ISSUE TITLE
Add Policy ARN list to create nodegroup command

### ISSUE THREAD

**Issue by jimmyraywv** [weaveworks/eksctl#4572]
**What feature/behavior/change do you want?**
The `create nodegroup` command is routinely used in lieu of/without a config file. It would be more functional if a list of policy ARNs could be specified, to override, or at least add to, the default list.

`--policy-arns arn1,arn2`

**Why do you want this feature?**
Without this functionality, custom permissions are not possible when the command is used without a config file. As this command is routinely used when troubleshooting config file issues, I think it would be very helpful for users. Without this policy ARN list, policies can still be added to the CFN stack, but the change then prevents the stack from deleting cleanly.

**Comment by Skarlso** [comment]
Hi @jimmyraywv!

This is already possible through the config file using:

```go
		// list of ARNs of the IAM policies to attach
		// +optional
		AttachPolicyARNs []string `json:"attachPolicyARNs,omitempty"`
```

We are reluctant to further pollute the command line arguments. So usually, new features are added to the configfile only, unless there is a really really good case to add to the command line options as well.

**Comment by Skarlso** [comment]
Relevant documentation on how to use this setting: https://eksctl.io/usage/iam-policies/#attaching-policies-by-arn

**Comment by cPu1** [comment]
@jimmyraywv, eksctl does not aim for feature parity between the config file fields and CLI options.

>Without this functionality, custom permissions are not possible when the command is used without a config file. 

eksctl supports reading ClusterConfig files from STDIN, so you can still use this functionality without creating a temporary `ClusterConfig` file using the heredoc format:

```shell
$ cat <<EOF | eksctl create nodegroup -f -
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: <name>
  region: <region>

managedNodeGroups:
- name: custom-policies
  iam:
    attachPolicyARNs: []

EOF
```

**Comment by jimmyraywv** [comment]
I spent the better part of three days trying to get an Ubuntu nodegroup created, using the `create nodegroup` command. I can create the nodegroup, without the custom permissions, with the command, If I don't use a config file. If I use the config file, there is a race condition introduced somewhere between the Canonical EKS AMI and eksctl, and the node kubelet never starts. So, while this may be a AMI issue (and we have opened a bug there), it looks like eksctl treats the scenarios differently.

The work arounds I have to use are:
- Use a config file, stop the rollback, and remote to each node to run `/etc/eks/bootstrap.sh` a second time
- Don't use a config file, create the nodegroup, and then add the custom policies to the created node role

I understand your desire not to "pollute" the CLI, but I honestly think this is a very valid use case.

**Comment by Skarlso** [comment]
I'm not sure I'm following here, sorry. The config file does the same thing as the command line arguments. Maybe it adds some defaults, but you can specify that via the config file as well.

Sorry, I have zero context on your issue so I'm not sure what the problem is. :)

**Comment by jimmyraywv** [comment]
I am just saying that eksctl seems to behave differently, based on whether or not I supply a config file. I can create EKS clusters with eksctl, using a config file, using AL2 based images. However, with the Canonical Ubuntu images, kubelet never starts. If, however, I used the command without a config file, then the Canonical Ubuntu AMI works, and the kubelet starts.

The command I use, that works without a config file, is:
```
e create nodegroup --cluster log4j --tags owner=jimmyray,env=dev,billing=lob-cc \
--subnet-ids <SUBNET_IDS> \
--node-type m5.large --nodes 3 --nodes-min 3 --nodes-max 3 --node-volume-size 100 \
--node-volume-type gp2 --enable-ssm --node-ami-family Ubuntu2004 --disable-pod-imds \
--instance-name u2004 --node-private-networking --name ubuntu --cfn-disable-rollback
```

The config file that I use that does work with `amiFamily: AmazonLinux2` but not with `amiFamily: Ubuntu2004` is:
```
managedNodeGroups:
  - name: ubuntu
    amiFamily: Ubuntu2004
    labels:
      node-group: ubuntu
      owner: jimmy
      env: dev
      billing: lob-cc
    instanceType: m5.large   
    instanceName: log4j-ubuntu
    subnets:
      - private-1
      - private-2
      - private-3
    minSize: 3
    desiredCapacity: 3
    maxSize: 5
    volumeSize: 100
    volumeType: gp2
    volumeEncrypted: true
    volumeKmsKeyID: <KMS_KEY_ID>
    disableIMDSv1: true
    disablePodIMDS: true
    privateNetworking: true
    tags:
      owner: jimmyray
      env: dev
      billing: lob-cc
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
```

I have work arounds, but I would not consider them production-ready. And, we have opened a bug about the Ubuntu AMI. That being said, I don't know why the `create nodegroup` command would work differently with/without a config file, even though the same AMI is resolved. I guess it could be something in the config (above) that works with AL2 and not Ubuntu. I am still looking into that.
