### ISSUE TITLE
Cluster creation fails when serviceIPv4CIDR is set

### ISSUE THREAD

**Issue by cPu1** [weaveworks/eksctl#4580]
When `kubernetesNetworkConfig.serviceIPv4CIDR` is set, but `ipFamily` is not set, eksctl throws an error. This is in the `main` branch and not in a release yet. 

```yaml
# cluster.yaml
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster
  region: us-west-2
  version: "1.21"

kubernetesNetworkConfig:
  serviceIPv4CIDR: "192.168.1.2/32"

managedNodeGroups:
  - name: mng-1


```

```shell
$ eksctl create cluster -f cluster.yaml
Error: invalid value  for ipFamily; allowed are IPv4 and IPv6
```
