### ISSUE TITLE
Error in reading config.yaml file while creating cluster

### ISSUE THREAD

**Issue by abhishekrathi09** [weaveworks/eksctl#4588]
```
cat << EOF > rasa-x.yaml
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: rasa-x-eksctl
  region: ap-south-1
  version: "1.19"

availabilityZones: ["ap-south-1a", "ap-south-1b"]

managedNodeGroups:
- name: nodegroup
  desiredCapacity: 3
  instanceType: t3.medium

EOF
```

Creating the EKS cluster via eksctl:

`eksctl create cluster -f rasa-x.yaml`

received following error

`Error: loading config file "rasa-x.yaml": error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type v1alpha5.ClusterConfig`

**Comment by Skarlso** [comment]
```yaml
managedNodeGroups:
- name: nodegroup
  desiredCapacity: 3
  instanceType: t3.medium
```

should be

```yaml
managedNodeGroups:
  - name: nodegroup
    desiredCapacity: 3
    instanceType: t3.medium
```
