### ISSUE TITLE
When creating a cluster with 1 node group with no node, timeout waiting for coredns to become active.

### ISSUE THREAD

**Issue by tanvp112** [weaveworks/eksctl#4607]
When I create an EKS cluster with 1 managed node group with `desiredCapacity` equal to zero, the creation failed with:

```
2022-01-11 11:53:59 [ℹ]  no recommended policies found, proceeding without any IAM
2022-01-11 11:53:59 [ℹ]  creating addon
2022-01-11 12:18:59 [!]  1 error(s) occurred while creating addons
2022-01-11 12:18:59 [✖]  timed out waiting for addon "coredns" to become active, status: "DEGRADED"
```

As a result:
- The status for coredns addon is `degraded`.
- kube-proxy addon was not installed. 
- None of the service account declared under iam.serviceAccounts was created.

This is eksctl version 0.77.

In a separate attempt that create another cluster with NO node group, the creation was successful. This cluster can later add node group with zero `desiredCapacity`. Scale the node count up/down also succeeded with no issue.

**Comment by cPu1** [comment]
Can you share your ClusterConfig file? I mainly need to check if you have any managed addons configured.

**Comment by tanvp112** [comment]
Sure, here you go.  Let me know if there's anything I could tweak.

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: 
  region: 

addons:
- name: vpc-cni
  version: latest
- name: coredns
  version: latest
- name: kube-proxy
  version: latest

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: aws-load-balancer-controller
      namespace: kube-system
    wellKnownPolicies:
      awsLoadBalancerController: true

vpc:
  clusterEndpoints:
    privateAccess: true

managedNodeGroups:
- name: spark-00
  amiFamily: Bottlerocket
  instanceType: m6i.2xlarge
  minSize: 0
  maxSize: 48
  desiredCapacity: 0
  privateNetworking: true
```
