### ISSUE TITLE
Cannot create auto scale group with spot instances

### ISSUE THREAD

**Issue by summerisc** [weaveworks/eksctl#4608]
**What were you trying to accomplish?**
Try to create a node group that works with cluster auto scaler to boot up spot instances when needed.
The yaml file I used for this node group:
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: kubeflow-us-east-1
  region: us-east-1
  version: '1.19'
  availabilityZones: ["us-east-1a", "us-east-1b",  "us-east-1d",  "us-east-1f"]
nodeGroups:
  - name: 1-gpu-spot-p2-xlarge
    minSize: 0
    maxSize: 3
    instancesDistribution:
      capacityRebalance: true
      #maxPrice: 1.2
      instanceTypes: [ "p2.xlarge" ]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0
      spotAllocationStrategy: capacity-optimized
    labels:
      lifecycle: Ec2Spot
      aws.amazon.com/spot: "true"
      gpu-count: "1"
    availabilityZones: [ "us-east-1a" ]
    taints:
      spotInstance: "true:PreferNoSchedule"
    tags:
      k8s.io/cluster-autoscaler/node-template/label/lifecycle: Ec2Spot
      k8s.io/cluster-autoscaler/node-template/label/aws.amazon.com/spot: "true"
      k8s.io/cluster-autoscaler/node-template/label/gpu-count: "1"
      k8s.io/cluster-autoscaler/node-template/taint/spotInstance: "true:PreferNoSchedule"
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/kubeflow-us-east-1: "owned"
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true
        albIngress: true
```
It successfully creates an asg like this:
![Screen Shot 2022-01-11 at 2 43 48 PM](https://user-images.githubusercontent.com/21230663/148895375-57a2bbc2-c885-44b1-b220-738146f7e239.png)

When we request a new node, it gives error like this：
![Screen Shot 2022-01-11 at 2 55 55 PM](https://user-images.githubusercontent.com/21230663/148895474-665a6ab5-5513-4a47-82b3-b06fb93979db.png)
Which part might be wrong in terms of the yaml file to create a node group so that it could auto boot up the spot instance.

```
$ eksctl info
eksctl version: 0.77.0
kubectl version: v1.19.9
```
