### ISSUE TITLE
Change ipFamily to lowercase ipv6 to be consistent with API experience

### ISSUE THREAD

**Issue by sheetaljoshi** [weaveworks/eksctl#4612]
**What were you trying to accomplish?**
eksctl schema (https://github.com/weaveworks/eksctl/releases/tag/v0.79.0-rc.0) should align to API standards (https://docs.aws.amazon.com/eks/latest/APIReference/API_KubernetesNetworkConfigRequest.html#AmazonEKS-Type-KubernetesNetworkConfigRequest-ipFamily) and align to change ipFamily to 'ipv6' vs. 'IPv6'. Although this is not a blocker, it is effecting user experience. 

**How to reproduce it?**
```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ipv6-cluster
  version: "1.21"
  region: us-west-2

kubernetesNetworkConfig:
  ipFamily: IPv6

vpc:
  clusterEndpoints:
    publicAccess: true
    privateAccess: true

iam:
  withOIDC: true

addons:
  - name: vpc-cni
    version: v1.10.1-eksbuild.1 # optional
  - name: coredns
    version: v1.8.4-eksbuild.1 # optional
  - name: kube-proxy
    version: v1.21.2-eksbuild.2 # optional
```

**Versions**

```
$ eksctl info
```

```console
eksctl version: 0.79.0-rc.0
kubectl version: v1.22.2
OS: darwin
```
