### ISSUE TITLE
I should be able to create a cluster with a config file specifying a service account with only attachPolicyARNs. I can't.

### ISSUE THREAD

**Issue by doctorpangloss** [weaveworks/eksctl#4614]
**What were you trying to accomplish?**
I cannot create a cluster with a service account only specifying `attachPolicyARNs` [contrary to your config examples](https://github.com/weaveworks/eksctl/blob/d94ce0a26163324cec721397de400ef4cdb85be2/examples/13-iamserviceaccounts.yaml#L61). I should be able to.

**What happened?**
`Error: iam.serviceAccounts[0].wellKnownPolicies, iam.serviceAccounts[0].attachPolicyARNs,iam.serviceAccounts[0].attachRoleARN  or iam.serviceAccounts[0].attachPolicy must be set
`

**How to reproduce it?**
Try to create a cluster with the following config file:
`eksctl create cluster --config-file ekscluster.yaml`

```yaml
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: test-cluster
  region: us-west-2
  version: "1.21"
availabilityZones:
  - us-west-2d
  - us-west-2b
  - us-west-2a
cloudWatch:
  clusterLogging: {}
fargateProfiles:
  - name: fp-default
    selectors:
      - namespace: default
      - namespace: kube-system
    status: ""
iam:
  vpcResourceControllerPolicy: true
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: ack-rds-controller
        namespace: kube-system
      attachPolicyARNS:
        - arn:aws:iam::aws:policy/AmazonRDSFullAccess
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
privateCluster:
  enabled: false
  skipEndpointCreation: false
vpc:
  autoAllocateIPv6: false
  cidr: 192.168.0.0/16
  clusterEndpoints:
    privateAccess: false
    publicAccess: true
  manageSharedNodeSecurityGroupRules: true
  nat:
    gateway: Single
```

Observe the following error message:
`Error: iam.serviceAccounts[2].wellKnownPolicies, iam.serviceAccounts[2].attachPolicyARNs,iam.serviceAccounts[2].attachRoleARN  or iam.serviceAccounts[2].attachPolicy must be set
`

**Logs**
`Error: iam.serviceAccounts[2].wellKnownPolicies, iam.serviceAccounts[2].attachPolicyARNs,iam.serviceAccounts[2].attachRoleARN  or iam.serviceAccounts[2].attachPolicy must be set`
**Anything else we need to know?**
This is contrary to your config example here https://github.com/weaveworks/eksctl/blob/d94ce0a26163324cec721397de400ef4cdb85be2/examples/13-iamserviceaccounts.yaml#L61

**Versions**
```
eksctl version: 0.77.0
kubectl version: v1.23.1
OS: darwin
```
