### ISSUE TITLE
Use existing dual-stack VPC for IPv6 clusters

### ISSUE THREAD

**Issue by jimmyraywv** [weaveworks/eksctl#4628]
**What help do you need?**
I am trying to use an existing dual-stack VPC for IPv6; I am using the `0.80.0-rc.0` release. I tried the below config. This created a VPC instead of using an existing one.
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ipv6
  version: "1.21"
  region: us-east-2

kubernetesNetworkConfig:
  ipFamily: ipv6

...
```
Then I tried the below config.
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ipv6
  version: "1.21"
  region: us-east-2

# kubernetesNetworkConfig:
#   ipFamily: ipv6

vpc:
  ipFamily: ipv6
  id: "<VPC_ID>"
  subnets:
    private:
      private-1:
        id: "<SUBNET_ID>"
      private-2:
        id: "<SUBNET_ID>"
      private-3:
        id: "<SUBNET_ID>"
...
```
With the second config, I get the error:
```
Error: loading config file "blog-cluster.yaml": error unmarshaling JSON: while decoding JSON: json: unknown field "ipFamily"
```
- Is the use case of using an existing dual-stack VPC supported for IPv6? I thought it was, based on this [PR](https://github.com/weaveworks/eksctl/pull/4398).
- If it is supported, is there an example config file?
- Are there docs on the new config file schema items that are RC and not yet officially released?
