### ISSUE TITLE
kubeletExtraConfig not supported with managed nodegroups on AWS EKS

### ISSUE THREAD

**Issue by GeorgeCimpoies** [weaveworks/eksctl#4632]
**What help do you need?**

Recently I have discovered that my nodes are overcommitted:
Total Requests (Memory):95%
Total Limits (Memory): 105%

When the load has increased on the cluster, the pods consumed more memory than available, resulting in a system OOM which crashed the kubelet, which resulted in the node marked as Not Ready, which further resulted in all pods on that node to stop processing requests. In one word: downtime.

```
managedNodeGroups:
  - name: ng-one-az-managed
    labels: { type: small }
    instanceType: t3.small
    desiredCapacity: 4
    availabilityZones: [ "eu-north-1b" ]
  - name: ng-multi-az-managed
    labels: { type: micro }
    instanceType: t3.small
    desiredCapacity: 14
  - name: ng-managed
    labels: { type: medium }
    instanceType: t3.medium
    desiredCapacity: 3
```

I am using managed nodegroups, which don't support the option kubeletExtraConfig, as per [the documentation](https://eksctl.io/usage/eks-managed-nodes/)

```
EKS Managed Nodegroups are managed by AWS EKS and do not offer the same level of configuration as unmanaged nodegroups. The unsupported options are noted below:
Full control over the node bootstrapping process and customization of the kubelet are not supported. This includes the following fields: classicLoadBalancerNames, targetGroupARNs, clusterDNS and kubeletExtraConfig.
```

`Error: couldn't create node group filter from command line options: loading config file "stg-vltv_credit-eks.yaml": error unmarshaling JSON: while decoding JSON: json: unknown field "kubeletExtraConfig"`

[The recommended way seems to be to add cloudformation flags for the kubelet, something which I don't want to do], because all my configuration-as-code for EKS is done with eksctl(https://labs.consol.de/devops/2019/04/16/aws_eks_oom.html). If this is controllable via flags from cloudformation, then it should be possible to achieve the same result from eksctl as well.

I want to keep using managed nodegroups because of the seamless upgrade proccess. However, AWS EKS is clearly not doing a good job at protecting its kubelet from resource starvation and node crash.

What do you recommend in order to avoid system OOM and downtime in the future due to this issue?
