### ISSUE TITLE
CoreDNS does not get an IP with IPv6 cluster on eksctl 0.80.0-rc

### ISSUE THREAD

**Issue by baalajimaestro** [weaveworks/eksctl#4661]
**What were you trying to accomplish?**
I tried to create an IPv6-enabled EKS cluster with VPC CNI, kube-proxy and coredns addons enabled.

**What happened?**
CoreDNS get stuck at ContainerCreating, upon inspection, it provides the logs mentioned below. I havent tested my own applications on IPv6, but I am not sure, if I will need CoreDNS in the cluster, we have been going with it since we enabled it initially :)

Update: Tried to deploy Cluster-Autoscaler and the same issue.

**How to reproduce it?**
Just adding coredns, vpc-cni and single managed ng should do it.

**Logs**
```
 Warning  FailedCreatePodSandBox  89s (x17 over 4m56s)  kubelet            (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "3b789807091ef7b78bdc6330e90955224f0e2df59cbfcad03a17ce8f184478b5": add cmd: failed to assign an IP address to container 
```

**Anything else we need to know?**
Nope

**Versions**
```
$ eksctl info
```
eksctl version: 0.80.0-rc.0
kubectl version: v1.23.1
OS: linux

**Comment by baalajimaestro** [comment]
I dont know how this helped but dont attach this ARN to VPC-CNI, and things would be fine

```
addons:
- name: vpc-cni
  attachPolicyARNs:
    - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
  version: latest
- name: coredns
  version: latest
- name: kube-proxy
  version: latest
  ```
