### ISSUE TITLE
DescribeVpcPeeringConnections missing from PolicyAWSLoadBalancerController

### ISSUE THREAD

**Issue by matti** [weaveworks/eksctl#4672]
managedNodeGroup created with:

```
managedNodeGroups:
  - iam:
      withAddonPolicies:
        albIngress: true
```

creates node policy which is missing "ec2:DescribeVpcPeeringConnections" so helm installed aws load balancer controller fails with:

`AccessDenied: User: arn:aws:sts::254324309357:assumed-role/eksctl-lel-nodegroup-g-1-x-1-pre-NodeInstanceRole-89I0OUCQAB6K/i-0707f449b9e63b921 is not authorized to perform: ec2:DescribeVpcPeeringConnections\n\tstatus code: 403`

adding `ec2:DescribeVpcPeeringConnections` manually to the fixes this immediately and load balancer is created
