### ISSUE TITLE
instance selector fails with the latest eks ami

### ISSUE THREAD

**Issue by matti** [weaveworks/eksctl#4674]
with instance selector vcpus: 2
and instance selector memory: 2 

>Unable to retrieve EKS supported instance types for version vV20220123: Unable to retrieve EKS supported instance types, got non-200 status code: 404

>Error: error expanding instance selector options for nodegroup "g-1-all-1-pre-2022-01-24-11-16-17": error querying instance types for the specified instance selector criteria: Unable to retrieve EKS supported instance types, got non-200 status code: 404

I think this worked just fine last week. that extra `v` in `vV20220123` looks like a bug?

**Comment by matti** [comment]
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: 'k-1'
  region: 'eu-north-1'

managedNodeGroups:
  - name: 'g-1-all-1-pre-2022-01-24-11-16-41'
    instancePrefix: 'g-1'
    instanceName: 'all-1-pre'
    labels:
      others: 'yes'
    instanceSelector:
      vCPUs: 2
      memory: '2'
    volumeType: 'gp3'
    volumeSize: 4
    volumeIOPS: 3000
    volumeThroughput: 125
    minSize: 1
    maxSize: 9
    spot: true
    iam:
      withAddonPolicies:
        autoScaler: true
        imageBuilder: true
        ebs: true
        albIngress: true
```
