### ISSUE TITLE
Ubuntu2004 family logs/exec fails with ipv6

### ISSUE THREAD

**Issue by matti** [weaveworks/eksctl#4680]
logs tries to connect to internal address:

>Error from server: Get "https://192.168.18.188:10250/containerLogs/default/nginx/nginx?follow=true": dial tcp 192.168.18.188:10250: i/o timeout

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: 'a-0'
  region: 'eu-north-1'
  version: '1.21'

kubernetesNetworkConfig:
  ipFamily: IPv6

addons:
  - name: vpc-cni
    version: latest
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest

iam:
  withOIDC: true
```

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: 'a-0'
  region: 'eu-north-1'

managedNodeGroups:
  - name: 'g-1-all-0-pre-2022-01-24-15-18-50'
    instancePrefix: 'g-1'
    instanceName: 'all-0-pre'
    labels:
      other: 'yes'
    volumeType: 'gp3'
    volumeSize: 32
    volumeIOPS: 3000
    volumeThroughput: 125
    minSize: 0
    maxSize: 3
    spot: true
    iam:
      withAddonPolicies:
        autoScaler: true
        imageBuilder: true
        ebs: true
        albIngress: true
    instanceTypes:
      - t3.small
      - t3.medium
      - t3.large
    amiFamily: Ubuntu2004
```

**Comment by matti** [comment]
and works with ipv4:

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: 'b-0'
  region: 'eu-north-1'
  version: '1.21'

addons:
  - name: vpc-cni
    version: latest
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest

iam:
  withOIDC: true
```

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: 'b-0'
  region: 'eu-north-1'

managedNodeGroups:
  - name: 'g-1-all-0-pre-2022-01-24-17-18-24'
    instancePrefix: 'g-1'
    instanceName: 'all-0-pre'
    labels:
      other: 'yes'
    volumeType: 'gp3'
    volumeSize: 32
    volumeIOPS: 3000
    volumeThroughput: 125
    minSize: 0
    maxSize: 3
    spot: true
    iam:
      withAddonPolicies:
        autoScaler: true
        imageBuilder: true
        ebs: true
        albIngress: true
    instanceTypes:
      - t3.small
      - t3.medium
      - t3.large
    amiFamily: Ubuntu2004
```
