### ISSUE TITLE
managedNodeGroup bottlerocket.settings doesn't work

### ISSUE THREAD

**Issue by gohmc** [weaveworks/eksctl#4685]
Extended eksctl examples with sample settings on bottlerocket [description of settings](https://github.com/bottlerocket-os/bottlerocket/blob/develop/README.md#description-of-settings):

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: cluster-20
  region: us-west-2

managedNodeGroups:
- name: mng1
  instanceType: m5.xlarge
  minSize: 0
  desiredCapacity: 0  # WARNING: must be zero and use `eksctl 0.81.0-rc.0` otherwise create cluster will fail because the node will never join the cluster.
  amiFamily: Bottlerocket
  bottlerocket:
    enableAdminContainer: true
    settings:
      motd: "Hello, eksctl!"
      kubernetes:
        allowed-unsafe-sysctls: ["net.core.somaxconn","net.ipv4.ip_local_port_range"]
        system-reserved:
          cpu: "10m"
          memory: "100Mi"
          ephmeral-storage: "1Gi"
        eviction-hard:
          memory:
            available: "15%"
```

Checked the user data created:

```
[settings.host-containers.admin]
"enabled" = true
[settings.kubernetes]
"allowed-unsafe-sysctls" = [
  "net.core.somaxconn",
  "net.ipv4.ip_local_port_range"
]

"api-server" = <redacted>
"cluster-certificate" = <redacted>
"cluster-dns-ip" = <redacted>
"cluster-name" = <redacted>
"max-pods" = 58
[settings.kubernetes.eviction-hard.memory]
"available" = "15%"
[settings.kubernetes.node-labels]
"alpha.eksctl.io/cluster-name" = <redacted>
"alpha.eksctl.io/nodegroup-name" = <redacted>
"eks.amazonaws.com/capacityType" = <redacted>
"eks.amazonaws.com/nodegroup" = <redacted>
"eks.amazonaws.com/nodegroup-image" = "ami-0da3d2971069b5f8b"
"eks.amazonaws.com/sourceLaunchTemplateId" = "lt-04d56ed0814c300f6"
"eks.amazonaws.com/sourceLaunchTemplateVersion" = "1"
[settings.kubernetes.system-reserved]
"cpu" = "10m"
"ephmeral-storage" = "1Gi"
"memory" = "100Mi"
```

Now scale up 1 node: `eksctl scale nodegroup --region us-west-2 --cluster cluster-20 --name mng1 -N 1`

The scaling works; an EC2 was launched and passed all health check. Unfortunately:

1. It failed to join the cluster; neither `kubectl get nodes` nor on the EKS console shown the new node.
2. The `settings.motd` is missing from the user data.
3. SSM connect doesn't work, looks like the control container has failed altogether for unknown reason.
4. The managed node group `mng1` is un-usable when trying to set bottlerocket settings.

Any idea what's missing?

**Comment by etungsten** [comment]
Hi @gohmc ,
The settings passed has a few typos and Bottlerocket is failing to parse the generated userdata.
Specifically, `ephmeral-storage` should be `ephemeral-storage` also:
```
        eviction-hard:
          memory:
            available: "15%"
```
needs to be
```
        eviction-hard:
          "memory.available": "15%"
```

I tried out a config with the above changes and was able to get a mng of bottlerocket nodes to join my clusters. Lemme know if that works for you!

**Comment by gohmc** [comment]
Good catch, indeed it works as expected now. Thanks for the prompt replied!

**Comment by GeorgeCimpoies** [comment]
@gohmc I'm considering using bottlerocket due to default AMI and managed nodegroups not supporting kubeletExtraConfig (https://github.com/weaveworks/eksctl/issues/4632), thus not being able to protect the kubelet if nodes go into resource starvation due to cpu/memory overcommitment. Is this the same usecase for you?

**Comment by gohmc** [comment]
Not quite the same. For the case of `managedNodeGroups` using EKS optimized AMI, you need to specify the AMI ID (eg. `aws ssm get-parameter --name /aws/service/eks/optimized-ami/1.21/amazon-linux-2/recommended/image_id --region <aws region> --query "Parameter.Value" -o text`) then specify your extra kubelet flags using `overrideBootstrapCommand` like:

```
managedNodeGroups:
- name: ...
  ami: <id>
  overrideBootstrapCommand: |
    #!/bin/bash
    /etc/eks/bootstrap.sh <cluster name> ---kubelet-extra-args '--kube-reserved cpu=xxxm,memory=xxxGi,ephemeral-storage=xxGi --system-reserved cpu=xxxm,memory=xxxGi,ephemeral-storage=xxGi'
```
