### ISSUE TITLE
ipv6 cluster outbound connections fail at random

### ISSUE THREAD

**Issue by matti** [weaveworks/eksctl#4714]
**What were you trying to accomplish?**

Run a large scale ipv6 cluster

**What happened?**

Connections from ipv6 pods to internet close randomly. For example `curl google.com` would return no such domain google.com because dns resolving and then work when retried (pods have `DNSPolicy: None` and nameservers set to 8.8.8.8 and 1.1.1.1 so it's not a kube/core-dns issue)

And now plain IP connections also fail at random.

Don't know how to provide more information at this point, but the same setup in Google GKE (ipv4 though) has worked for years and this ipv6 stuff is quite new.

**How to reproduce it?**

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: 'eka-1'
  region: 'eu-north-1'
  version: '1.21'

addons:
  - name: vpc-cni
    version: latest
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest

iam:
  withOIDC: true


kubernetesNetworkConfig:
  ipFamily: IPv6
```

nodegroup:

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: 'eka-1'
  region: 'eu-north-1'

managedNodeGroups:
  - name: 'g-1-bot-1-pre-2022-01-28-15-27-00'
    instancePrefix: 'g-1'
    instanceName: 'g-1-bot-1-pre-2022-01-28-15-27-00'
    labels:
      preemptible: 'yes'
      regular: 'yes'
      bot: 'yes'
      cluster_name: 'eka-1'
      region_name: 'aws'
    volumeType: 'gp3'
    volumeSize: 8
    volumeIOPS: 3000
    volumeThroughput: 125
    minSize: 1
    maxSize: 450
    spot: true
    iam:
      withAddonPolicies:
        autoScaler: true
        imageBuilder: true
        ebs: true
        albIngress: true
    instanceSelector:
      vCPUs: 32
      memory: '64'

    ami: ami-0740245292d53bfa2
    preBootstrapCommands:
      - cd /tmp
      - date > eksler.start
      - echo 'changing root password'
      - echo 'root:badpassword' | sudo chpasswd
      - echo 'password changed'
      - sudo yum install -y htop iotop nano screen
      - sudo amazon-linux-extras install epel -y
      - sudo yum install -y stress
      - date > eksler.done
    overrideBootstrapCommand: |
      #!/bin/bash
      date > /tmp/eksler.overrideBootstrapCommand
      /etc/eks/bootstrap.sh 'eka-1'
```
