### ISSUE TITLE
Multiple subnets per AZ

### ISSUE THREAD

**Issue by rustysys-dev** [weaveworks/eksctl#475]
**Why do you want this feature?**
Assuming this is a feature request and not a bug...

Add support for adding multiple subnets per AZ in config file.

**What feature/behavior/change do you want?**
Given the following configuration snippet..

```
vpc:
  id: vpc-088d4632821fe0f52
  subnets:
    Public:
      us-east-1a:
        id: subnet-0b73f4183e00d028c
      us-east-1a:
        id: subnet-0f960edf42d22b955
      us-east-1b:
        id: subnet-0c92168f3faeed699
      us-east-1b:
        id: subnet-011a8697711f41dd6
```

Log should show:

```
[✔]  using existing VPC (vpc-088d4632821fe0f52) and subnets (private:[] public:[subnet-0b73f4183e00d028c subnet-0f960edf42d22b955 subnet-0c92168f3faeed699 subnet-011a8697711f41dd6])
```

and not:

```
[✔]  using existing VPC (vpc-088d4632821fe0f52) and subnets (private:[] public:[subnet-0f960edf42d22b955 subnet-011a8697711f41dd6])
```

**Comment by errordeveloper** [comment]
I am still not sure what would be a benefit of this. Is this to do with maximising the utilisation of the IP address space or something else?

**Comment by procyclinsur** [comment]
I apologize for the delay in responding to this.  we are still in the development phase for our application so we do not have all of the requirements worked out.  That being said, traditionally subnetting was for segregation of resources within the network... AWS networks arn't really much different utilizing ACLs at the network level for segregation and SecurityGroups at the host/service level.

I wouldn't consider it a defined requirement as segregation of traffic can still be achieved without multiple subnets, just not with that nice fuzzy feeling inside.  

One thing I might be able to say is that its something that might be expected by system architects as you are able to manually create an EKS cluster with multiple subnets in the same availability zone.

**Comment by errordeveloper** [comment]
I don't think it's common to use EC2 subnets for segregation, security groups are the go-to option that give you most flexibility. It's probably somewhat technically possible, but why would you do that? I don't see a reason to provide support for something that is theoretically possible, yet practically of little use, especially if it implies a fundamental change in design. If you must prove practical use-case for such a feature, I'm happy to discuss it more.

**Comment by errordeveloper** [comment]
so let’s consider this topology:
- 2 nodegroup (*A* & *B*) are using same set of private subnets
- *A* is a _regular_ nodegroup; it belongs to a shared SG that lets it talk to any other regular nodegroup, and one more that lets administrator oper ports in that nodegroup (e.g. SSH) and links allows traffic to/from EKS CP
- *B* is an isolated nodegroup, it has the most minimal setup - one SG that lets all nodes in the nodegroup to communicate and allows traffic to/from EKS CP
if *A* and *B* didn’t share subnets, and say *B* had own subnets, what tangible isolation guarantees that will provide?

I think it's possible that you gain extra control over routing, but that's not so much to do with isolation per-se, and I don't know what are the use-cases here exactly, if there is anything prominent - I'm very keen to hear.

Is there a solid use-case where subnets somehow enhance isolation?

**Comment by procyclinsur** [comment]
@errordeveloper I have thought about this again since I have made the initial issue, and with traditional routing you have a bit more control, that being said within an AWS VPC this kind of control isn't really necessary, so I think we can close this.

Thank you!

**Comment by amarrella** [comment]
Hi :) Thanks for this amazing project, it makes EKS cluster management so much easier!

I know this issue is closed but would it be possible to reconsider your decision? Many companies have predefined subnets with different access to resources (some outside AWS) and it is quite common to have multiple subnets with different access levels in the same AZ and refactoring the network structure is a quite delicate task. I know eksctl offers the possibility to run in a separate VPC, but this would still need pairing the subnets at the very least to access resources. 

Maybe this change can be made in a non-breaking way extending the map to support arbitrary values as keys, for example:

Current setup (to check for non-breaking):
```yaml
vpc:
  subnets:
    private:
      us-east-1a:
         id: subnet-123
```

Alternative supported setup:
```yaml
vpc:
  subnets:
    private:
      data-access-subnet:
         id: subnet-123
         az: us-east-1a
      high-level-subnet:
         id: subnet-456
         az: us-east-1a
```

In the first case, if the subnet name is us-east-1a and no value is passed in the `az` parameter, it assumes that the az value is the same as the name.

Then nodegroups can keep referring to the `availabilityZones` parameter if there only one subnet per az, or they can refer to a new parameter `subnets` which specifies which subnet the nodes would run in.

Does this sound reasonable?

Thanks in advance for bearing with me :)

**Comment by errordeveloper** [comment]
Hi Alessandro, thanks for sharing this! A few more folks asked on other
issues about this, and the plan was to do exactly what you described - add
custom topologies. Thanks a lot for detailed feedback and the kind words, I
am glad you fine eksctl useful :)

**Comment by amarrella** [comment]
That's awesome! Thanks a lot for this! :)

**Comment by michaelbeaumont** [comment]
Support for this is now in master and will be released at the end of the week! Please test it out and verify it works for your use cases!

**Comment by k4200** [comment]
I tried the latest head with the following config:
```
vpc:
  id: "vpc-xxxxxxxxxx"
  subnets:
    private:
      subnet-loadtest-a:
        id: "subnet-xxxxxxxxxxxxxxxxx"
      subnet-loadtest-c:
        id: "subnet-xxxxxxxxxxxxxxxxx"
      subnet-loadtest-d:
        id: "subnet-xxxxxxxxxxxxxxxxx"
      subnet-loadtest-a2:
        id: "subnet-xxxxxxxxxxxxxxxxx"
      subnet-loadtest-c2:
        id: "subnet-xxxxxxxxxxxxxxxxx"
      subnet-loadtest-d2:
        id: "subnet-xxxxxxxxxxxxxxxxx"
      subnet-loadtest-a3:
        id: "subnet-xxxxxxxxxxxxxxxxx"
      subnet-loadtest-c3:
        id: "subnet-xxxxxxxxxxxxxxxxx"
      subnet-loadtest-d3:
        id: "subnet-xxxxxxxxxxxxxxxxx"

nodeGroups:
  - name: foo
    instanceType: m5.xlarge
    desiredCapacity: 1
    privateNetworking: true
  - name: bar
    instanceType: m5.xlarge
    desiredCapacity: 15
    privateNetworking: true
    subnets:
      - subnet-loadtest-a
      - subnet-loadtest-a2
      - subnet-loadtest-a3
      - subnet-loadtest-c
      - subnet-loadtest-c2
      - subnet-loadtest-c3
      - subnet-loadtest-d
      - subnet-loadtest-d2
      - subnet-loadtest-d3
```

`eksctl create cluster` successfully created an EKS cluster with 9 subnets, 3 per AZ as planned. However, the nodes were placed only in 3 subnets, 1 per AZ, in other words, 6 out of 9 subnets aren't used.

The reason why I need multiple subnets per AZ is I need to use more subnets and NAT Gateways because of the NAT Gateway's limitations:
https://docs.aws.amazon.com/vpc/latest/userguide/vpc-nat-gateway.html#nat-gateway-limits
