### ISSUE TITLE
Add support for ASG lifecycle hooks

### ISSUE THREAD

**Issue by t0rr3sp3dr0** [weaveworks/eksctl#4774]
Reopens #4347

## Original issue

**What feature/behavior/change do you want?**

Add support for [autoscaling lifecycle hooks](https://docs.aws.amazon.com/autoscaling/ec2/userguide/lifecycle-hooks.html) to node groups.

A sample configuration could be the following based on the [cloudformation documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-autoscaling-autoscalinggroup-lifecyclehookspecification.html). This supports all lifecycle hook configuration options.

```yaml
cluster:
  ...
  nodeGroups:
    - name: spotNodeGroup
      lifecycleHooks:
        - defaultResult: <String>
          heartbeatTimeout: <Integer>
          lifecycleHookName: <String>
          lifecycleTransition: <String>
          notificationMetadata: <String>
          notificationTargetARN: <String>
          roleARN: <String>
      ...
```

**Why do you want this feature?**

Node groups already have support for [capacity rebalance](https://docs.aws.amazon.com/autoscaling/ec2/userguide/ec2-auto-scaling-capacity-rebalancing.html) however this does not automatically drain the nodes before termination. The [node termination exporter](https://github.com/aws/aws-node-termination-handler), an official solution to this problem from AWS, requires the addition of lifecycle hooks to work.

These shouldn't be required for managed node groups as they will automatically drain workloads on a rebalance event.
