### ISSUE TITLE
Karpenter pod craches due to empty CLUSTER_NAME and CLUSTER_ENDPOINT

### ISSUE THREAD

**Issue by ryok-0319** [weaveworks/eksctl#4810]
**What were you trying to accomplish?**
I was trying to deploy Karpenter using eksctl.

**What happened?**
`eksctl create cluster -f cluster.yaml` failed with the error
`Error: failed to install Karpenter: failed to install Karpenter chart: failed to install chart: timed out waiting for the condition`

I checked the cluster and found the Karpenter pod's status was `CrashLoopBackOff` because of empty CLUSTER_NAME and CLUSTER_ENDPOINT

I did `kubectl describe pod` and confirmed the environments `CLUSTER_NAME` and `CLUSTER_ENDPOINT` were both empty.

I manually executed ↓, then the pod started running.

```
helm upgrade --install --namespace karpenter --create-namespace \
  karpenter karpenter/karpenter \
  --version v0.6.3 \
  --set serviceAccount.annotations."eks\.amazonaws\.com/role-arn"=${KARPENTER_IAM_ROLE_ARN} \
  --set clusterName=${CLUSTER_NAME} \
  --set clusterEndpoint=${CLUSTER_ENDPOINT} \
  --set aws.defaultInstanceProfile=KarpenterNodeInstanceProfile-${CLUSTER_NAME} \
  --wait
```

**How to reproduce it?**

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: Development
  region: ap-northeast-1
  version: '1.21'

karpenter:
  version: '0.6.3'
  createServiceAccount: true

vpc:
  subnets:
    private:
      ap-northeast-1a: { id: subnet-XXX }
      ap-northeast-1c: { id: subnet-YYY }
      ap-northeast-1d: { id: subnet-ZZZ }
    public:
      ap-northeast-1a: { id: subnet-XXX }
      ap-northeast-1c: { id: subnet-YYY }
      ap-northeast-1d: { id: subnet-ZZZ }

iam:
  withOIDC: true

managedNodeGroups:
  - name: ng
    instanceType: t3.small
    subnets:
      - subnet-XXX
      - subnet-YYYY
      - subnet-ZZZ
    desiredCapacity: 2
    minSize: 2
    maxSize: 2
    volumeSize: 120
    privateNetworking: true
    ssh:
      allow: false
```

**Logs**
The log from the Karpenter pod
(This log is from `webhook`, but `controller` was almost the same)

```
panic: "" not a valid CLUSTER_ENDPOINT URL; CLUSTER_NAME is required

goroutine 1 [running]:
github.com/aws/karpenter/pkg/utils/options.MustParse()
	github.com/aws/karpenter/pkg/utils/options/options.go:48 +0x52e
main.init()
	github.com/aws/karpenter/cmd/webhook/main.go:42 +0x2e
```

The log from eksctl -v
clusterEndpoint and clusterName are not empty at this moment
```
2022-02-18 13:52:45 [ℹ]  adding Karpenter to cluster Development
2022-02-18 13:52:45 [▶]  cluster endpoint used by Karpenter: https://XXX.gr7.ap-northeast-1.eks.amazonaws.com/
2022-02-18 13:52:45 [▶]  the following values will be applied to the install: map[controller:map[clusterEndpoint:https://XXX.gr7.ap-northeast-1.eks.amazonaws.com/ clusterName:Development] serviceAccount:map[annotations:map[eks.amazonaws.com/role-arn:arn:aws:iam::XXX:role/eksctl-Development-iamservice-role] create:true]]
2022-02-18 14:00:34 [▶]  Deployment is not ready: karpenter/karpenter. 0 out of 1 expected pods are ready
(`Deployment is not ready` follows...)
```

**Versions**

```
$ eksctl info
eksctl version: 0.83.0
kubectl version: v1.23.3
OS: darwin
```
