### ISSUE TITLE
Pin karpenter support to a specific minor

### ISSUE THREAD

**Issue by aclevername** [weaveworks/eksctl#4827]
Karpenter is a fast moving project that might have breaking changes between minors. Lets pin eksctl so that you can only install up to a specific minor. This should prevent users from installing a version of karpenter that doesn't work with eksctl. 

E.g. lets say we support up to `0.6.*`:

The following configs succeed:
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-with-karpenter
  region: us-west-2
  version: '1.20'

iam:
  withOIDC: true

karpenter:
  version: '0.6.6'
  createServiceAccount: true # default is false

managedNodeGroups:
  - name: managed-ng-1
    minSize: 1
    maxSize: 2
    desiredCapacity: 1
```

The following should fail:
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-with-karpenter
  region: us-west-2
  version: '1.20'

iam:
  withOIDC: true

karpenter:
  version: '0.7.0'
  createServiceAccount: true # default is false

managedNodeGroups:
  - name: managed-ng-1
    minSize: 1
    maxSize: 2
    desiredCapacity: 1
```

Summary
- We will add support for pinning to a specific minor
- We will also add some documentation explaining this to the users
