### ISSUE TITLE
Custom ami and overrideBootstrapCommand problem. Fail to create cluster

### ISSUE THREAD

**Issue by AqsaMemon** [weaveworks/eksctl#4852]
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-1
  region: us-east-2

managedNodeGroups:
  - name: ide
    instanceType: m6i.xlarge
    minSize: 2
    maxSize: 3
    disableIMDSv1: false

    volumeSize: 100
    volumeType: gp3
    volumeIOPS: 6000
    volumeThroughput: 500
    ebsOptimized: true

    privateNetworking: true
    ami: ami-0ad574da759c55c17

    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/cluster-1: "owned"
      
    overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh cluster-1

```
I am getting an error when I use a custom ami with overrideBootstrap command. Please help where I am going wrong. Thanks
