### ISSUE TITLE
Cannot create Bottlerocket nodegroup from cli options

### ISSUE THREAD

**Issue by rothgar** [weaveworks/eksctl#4863]
**What were you trying to accomplish?**

Create a cluster with Bottlerocket node group without using a config file.

**What happened?**

I get this error during node group creation
```
2022-02-28 10:45:50 [✖]  AWS::EKS::Nodegroup/ManagedNodeGroup: CREATE_FAILED – "Resource handler returned message: \"[Issue(Code=Ec2LaunchTemplateInvalidConfiguration, Message=User data was not in the MIME multipart format.)] (Service: null, Status Code: 0, Request ID: null, Extended Request ID: null)\" (RequestToken: e723fed3-206e-c209-f13d-df86cd280ee4, HandlerErrorCode: GeneralServiceException)"
```

**How to reproduce it?**

Using `eksctl` 0.86.0-rc.0 use this command 

```
eksctl create cluster --name br-gpu \
    --instance-types g4dn.xlarge \
    --node-ami-family Bottlerocket
```

**Logs**

**Anything else we need to know?**

If I use a config file and don't set any settings for the node group the cluster is created properly. It appears only to be an issue from the CLI. Here's an example config that worked.

```
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: bottlerocket-test
  region: ca-central-1

nodeGroups:
  - name: ng1-public
    instanceType: m5.xlarge
    desiredCapacity: 2
    amiFamily: Bottlerocket
```

**Versions**

```
$ eksctl info

eksctl version: 0.86.0-rc.0
kubectl version: v1.23.4
OS: linux
```
This is related to #4809 and while using a config file for the cluster works it doesn't appear that user-data is sent to the CFN stack (even if no user-data is needed) which causes the issue.
