### ISSUE TITLE
Cannot fetch nodegroups when DesiredCapacity > 0 but no node is registered

### ISSUE THREAD

**Issue by vflaux** [weaveworks/eksctl#4927]
**What were you trying to accomplish?**
Get nodegroups info
```
eksctl get nodegroup --cluster foo
```

**What happened?**

```
$ eksctl get nodegroup --cluster foo
2022-03-10 10:34:40 [ℹ]  eksctl version 0.86.0
2022-03-10 10:34:40 [ℹ]  using region eu-west-3
Error: getting nodegroup's kubernetes version: failed to list nodes: no nodes were found
```

**How to reproduce it?**

Create a nodegroup with DesiredCaapcity > 0 then get nodegroups before the first node is registered in the cluster.
-OR-
Create a nodegroup with a feature gate not enabled on eks apiserver (ex: CustomCPUCFSQuotaPeriod).
Nodes won't be able to register into the cluster and `eksctl get nodegroup` will always fails.
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: foo
  region: eu-west-3
nodeGroups:
  - name: ng-1
    instanceType: m5a.xlarge
    desiredCapacity: 1
    kubeletExtraConfig:
        featureGates:
            RotateKubeletServerCertificate: true
            CustomCPUCFSQuotaPeriod: true
```
**Logs**

**Anything else we need to know?**

If the desired capacity of the asg is 0, eksctl skip the retrieval of this info. It should be safe to ignore the error if there is no nodes even if the desired capacity is > 0.
https://github.com/weaveworks/eksctl/blob/39b891d01cd5c0c9577ef434721438155ecc9f67/pkg/actions/nodegroup/get.go#L169-L174

**Versions**

```
$ eksctl info
eksctl version: 0.86.0
kubectl version: v1.22.5
OS: linux
```
