### ISSUE TITLE
kubelet config overwritten when bootstrapping with containerd and custom AMI (AL2)

### ISSUE THREAD

**Issue by cthrasher** [weaveworks/eksctl#4930]
This is reopening #4206 which was closed for being stale. Essentially when creating a node using a custom AMI and '--container-runtime containerd', the bootstrap script would misconfigure kubelet.service, preventing it from starting.
```
nodeGroups:
  - name: core-al2-custom-ami
    # labels: { role: workers }
    # amiFamily: AmazonLinux2
    ami: ami-REDACTED  # Custom AMI ID
    instanceType: t3.medium
    privateNetworking: true
    minSize: 1
    maxSize: 1
    desiredCapacity: 1
    availabilityZones: ["us-east-1a","us-east-1b","us-east-1c"]
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
    overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh eks-cluster-121 --container-runtime containerd
```

In /var/log/messages there would be a loop of kubelet.service failing to start identical to the logs in #4206. I found this in the kubelet daemon config:

```
sh-4.2$ sudo systemctl cat kubelet.service
# /etc/systemd/system/kubelet.service
[Unit]
Description=Kubernetes Kubelet
Documentation=https://github.com/kubernetes/kubernetes
After=containerd.service sandbox-image.service
Requires=containerd.service sandbox-image.service

[Service]
ExecStartPre=/sbin/iptables -P FORWARD ACCEPT -w 5
ExecStart=/usr/bin/kubelet --cloud-provider aws \
    --config /etc/kubernetes/kubelet/kubelet-config.json \
    --kubeconfig /var/lib/kubelet/kubeconfig \
    --container-runtime remote \
    --container-runtime-endpoint unix:///run/containerd/containerd.sock \
    --network-plugin cni $KUBELET_ARGS $KUBELET_EXTRA_ARGS

Restart=on-failure
RestartForceExitStatus=SIGPIPE
RestartSec=5
KillMode=process

[Install]
WantedBy=multi-user.target

#/etc/systemd/system/kubelet.service.d/10-eksctl.al2.conf
# eksctl-specific systemd drop-in unit for kubelet, for Amazon Linux 2 (AL2)
# TODO Deprecated, will be removed soon

[Service]
# Local metadata parameters: REGION, AWS_DEFAULT_REGION
EnvironmentFile=/etc/eksctl/metadata.env
# Global and static parameters: CLUSTER_DNS, NODE_LABELS, NODE_TAINTS
EnvironmentFile=/etc/eksctl/kubelet.env
# Local non-static parameters: NODE_IP, INSTANCE_ID
EnvironmentFile=/etc/eksctl/kubelet.local.env

ExecStart=
ExecStart=/usr/bin/kubelet \
  --node-ip=${NODE_IP} \
  --node-labels=${NODE_LABELS},alpha.eksctl.io/instance-id=${INSTANCE_ID} \
  --max-pods=${MAX_PODS} \
  --register-node=true --register-with-taints=${NODE_TAINTS} \
  --cloud-provider=aws \
  --container-runtime=docker \
  --network-plugin=cni \
  --cni-bin-dir=/opt/cni/bin \
  --cni-conf-dir=/etc/cni/net.d \
  --pod-infra-container-image=${AWS_EKS_ECR_ACCOUNT}.dkr.ecr.${AWS_DEFAULT_REGION}.${AWS_SERVICES_DOMAIN}/eks/pause:3.3-eksbuild.1 \
  --kubeconfig=/etc/eksctl/kubeconfig.yaml \
  --config=/etc/eksctl/kubelet.yaml
# /etc/systemd/system/kubelet.service.d/10-kubelet-args.conf
[Service]
Environment='KUBELET_ARGS=--node-ip=10.102.11.185 --pod-infra-container-image=602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/pause:3.1-eksbuild.1 --v=2'
# /etc/systemd/system/kubelet.service.d/30-kubelet-extra-args.conf
[Service]
Environment='KUBELET_EXTRA_ARGS=--max-pods=110'
# /etc/systemd/system/kubelet.service.d/environment.conf
[Service]
EnvironmentFile=/etc/environment
```

So there's contradictory ExecStart assignments in the configuration. The second one is coming from /etc/systemd/system/kubelet.service.d/10-eksctl.al2.conf and specifies Docker as the runtime. 

As a workaround, I was able to get the nodes to start successfully by using this custom bootstrap command:
```
    overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh eks-cluster-121 --container-runtime containerd
      rm -f /etc/systemd/system/kubelet.service.d/10-eksctl.al2.conf
      systemctl daemon-reload
      systemctl restart kubelet
      systemctl restart containerd
```

**Versions**

```
$ eksctl info
eksctl version: 0.86.0
kubectl version: v1.20.4-eks-6b7464
OS: darwin
```
