### ISSUE TITLE
Additional IAM policies not being added to NodeInstanceRole when using `attachPolicyARNs`

### ISSUE THREAD

**Issue by f0xtek** [weaveworks/eksctl#4935]
Hi,

I am trying to attach two additional IAM policies to a managed node group's NodeInstanceRole, 1 AWS managed policy `AWSAppMeshEnvoyAccess` and another custom policy, using the following config:

```
managedNodeGroups:
  - name: ng1
     iam:
       attachPolicyArns:
         - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
         - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
         - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
         - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
         - arn:aws:iam::aws:policy/AWSAppMeshEnvoyAccess
         - arn:aws:iam::111111111111:policy/custom-policy
       withAddonPolicies:
         autoScaler: true
         ebs: true
         cloudWatch: true
         externalDNS: true
         imageBuilder: true
         appMesh: true
```

However, when creating the node group, neither the `AWSAppMeshEnvoyAccess` nor `custom-policy` IAM policies are attached to the NodeInstanceRole. The two policies are not being rendered in the CloudFormation stack template:

```
    "NodeInstanceRole": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "AssumeRolePolicyDocument": {
          "Statement": [
            {
              "Action": [
                "sts:AssumeRole"
              ],
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  {
                    "Fn::FindInMap": [
                      "ServicePrincipalPartitionMap",
                      {
                        "Ref": "AWS::Partition"
                      },
                      "EC2"
                    ]
                  }
                ]
              }
            }
          ],
          "Version": "2012-10-17"
        },
        "ManagedPolicyArns": [
          {
            "Fn::Sub": "arn:${AWS::Partition}:iam::aws:policy/AmazonEC2ContainerRegistryPowerUser"
          },
          {
            "Fn::Sub": "arn:${AWS::Partition}:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
          },
          {
            "Fn::Sub": "arn:${AWS::Partition}:iam::aws:policy/AmazonEKSWorkerNodePolicy"
          },
          {
            "Fn::Sub": "arn:${AWS::Partition}:iam::aws:policy/AmazonEKS_CNI_Policy"
          },
          {
            "Fn::Sub": "arn:${AWS::Partition}:iam::aws:policy/AmazonSSMManagedInstanceCore"
          },
          {
            "Fn::Sub": "arn:${AWS::Partition}:iam::aws:policy/CloudWatchAgentServerPolicy"
          }
        ],
        "Path": "/",
        "Tags": [
          {
            "Key": "Name",
            "Value": {
              "Fn::Sub": "${AWS::StackName}/NodeInstanceRole"
            }
          }
        ]
      }
```

According to the [documentation](https://eksctl.io/usage/iam-policies/#attaching-policies-by-arn), simply adding the two policy ARNs to the `attachPolicyARNs` list should be enough when you also include the default EKS node policies in the list.

Am I missing something in my config? I have checked the number of AWS managed policies in the resulting NodeInstanceRole, and the total number is still less than the default limit of 10 per role.

Any help would be greatly appreciated.

Thanks

**Comment by f0xtek** [comment]
Sorry, should mention, my eksctl version is 0.86.0.

**Comment by Skarlso** [comment]
Hi @f0xtek 

I have a hunch that something is getting overwritten before it can be applied. I'll try to reproduce this and see if I can. My hunch is that defining `withAddonPolicies` or at least one of its attributes has an unintended side-effect.

**Comment by Skarlso** [comment]
Huh, that is weird. It's not in there, even using this config:

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-additional-policies-1
  region: us-west-2
  version: '1.21'

managedNodeGroups:
  - name: ng-1
    minSize: 1
    maxSize: 2
    desiredCapacity: 1
    iam:
      attachPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AWSAppMeshEnvoyAccess
```

`AWSAppMeshEnvoyAccess` is nowhere to be seen. Interesting, I'm pretty sure this used to work.
