### ISSUE TITLE
[Bug] instanceSelector can not filter out c5.metal instances

### ISSUE THREAD

**Issue by matti** [weaveworks/eksctl#4956]
While this is not related to eksctl directly, I'm hoping for faster escalation to the AWS EKS team and find some solution to filter out certain instance types (maybe with https://github.com/weaveworks/eksctl/issues/3718)

### What were you trying to accomplish?
run managedInstanceGroup with nodeSelector 96vcpu

### What happened?
I get both c5.24xlarge and c5.metal - c5.metal crashes due to https://github.com/aws/amazon-vpc-cni-k8s/issues/1929

There is no way to keep using instanceSelector as ~half of the instances are crashing.

### How to reproduce it?
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: 'test-3'
  region: 'eu-north-1'

managedNodeGroups:
  - name: 'g-1-test-96-192-pre-1-2022-03-15-15-08-05'
    instancePrefix: 'g-1'
    instanceName: 'g-1-test-96-192-pre-1-2022-03-15-15-08-05'
    labels:
      test: 'yes'
    volumeType: 'gp3'
    volumeSize: 8
    volumeIOPS: 3000
    volumeThroughput: 125
    minSize: 1
    maxSize: 450
    spot: true
    iam:
      withAddonPolicies:
        autoScaler: true
        imageBuilder: true
        ebs: true
        albIngress: true
    instanceSelector:
      vCPUs: 96
      memory: '192'

    ami: ami-0f47e499c06cba4fc
    preBootstrapCommands:
      - echo 'changing root password for serial console access'
      - echo 'root:badpassword' | sudo chpasswd
      - echo 'password changed'
    overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh 'test-3'
```

**Versions**
eksctl 0.87.0

**Comment by aclevername** [comment]
Hey @matti , thanks for raising the issue.

A workaround for now might be to used the [dry-run](https://eksctl.io/usage/dry-run/) feature to generate the list of instances supported by your parameters, and then remove the troublesome types. E.g. ` eksctl create cluster -f cluster.yaml --dry-run` will generate the instances:
```
 apiVersion: eksctl.io/v1alpha5
availabilityZones:
- eu-north-1b
- eu-north-1c
- eu-north-1a
iam:
  vpcResourceControllerPolicy: true
  withOIDC: false
kind: ClusterConfig
managedNodeGroups:
- ami: ami-0f47e499c06cba4fc
  amiFamily: AmazonLinux2
....
  instanceSelector:
    memory: "192"
    vCPUs: 96
  instanceTypes:
  - c5.24xlarge
  - c5.metal
  - c5a.24xlarge
  - c5d.24xlarge
  - c5d.metal
```

you can then remove the types you like and use the generated config
