### ISSUE TITLE
Support adding --max-pods-per-node in cluster config file

### ISSUE THREAD

**Issue by neilharris123** [weaveworks/eksctl#4967]
### What feature/behavior/change do you want?

I've seen it's possible to increase the max number of pods per node, by using the `--max-pods-per-node` flag when creating a managedNodeGroup, for example by running:

`eksctl create nodegroup --cluster my-cluster --max-pods-per-node 110`

But I see no way of configuring this in the cluster config file.

We are defining our managedNodeGroups via a cluster.yaml file, and it would be useful to be able to add this maxPods config there. 

### Why do you want this feature?

It would be useful to control this via IaC.

**Comment by Skarlso** [comment]
@neilharris123 Hi. you mean, like this? https://eksctl.io/usage/schema/#nodeGroups-maxPodsPerNode

**Comment by Skarlso** [comment]
For clarification, that's in the nodegroup base, so it can be defined for either managed or unmanaged nodegroups.

**Comment by Skarlso** [comment]
for example:
```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: managed-cluster
  region: us-west-2

managedNodeGroups:
  - name: custom-ng
    maxPodsPerNode: 80
```
