### ISSUE TITLE
[Bug] coredns addon prevents scaledown because of missing PodDisruptionPolicy and local storage

### ISSUE THREAD

**Issue by matti** [weaveworks/eksctl#4969]
### What were you trying to accomplish?

cluster-autoscaler can not scale an (otherwise) empty node down:

```
Fast evaluation: node ip-192-168-25-147.eu-north-1.compute.internal cannot be removed: non-daemonset, non-mirrored, non-pdb-assigned kube-system pod present: coredns-5bf7669654-l46wf
```

### What happened?

coredns addon does not create PodDisruptionPolicy, creating it:

```
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: coredns
  namespace: kube-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      eks.amazonaws.com/component: coredns
```

fixes this but leads us to the next problem:

```
Fast evaluation: node ip-192-168-25-147.eu-north-1.compute.internal cannot be removed: pod with local storage present: coredns-5bf7669654-l46wf
```

I guess the only way to get this removed would be to label `cluster-autoscaler.kubernetes.io/safe-to-evict: true`
