### ISSUE TITLE
[Bug] eksctl allows creation of ipv6 managedNodeGroups without nitro

### ISSUE THREAD

**Issue by matti** [weaveworks/eksctl#4980]
### What were you trying to accomplish?

create cluster and managed nodegroup with:

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: 'putte-bot-1'
  region: 'us-east-1'
  version: '1.21'

addons:
  - name: vpc-cni
    version: latest     # NOTE: has to be present, otherwise some random version
  - name: coredns
    version: latest     # NOTE: has to be present, otherwise some random version
  - name: kube-proxy
    version: latest     # NOTE: has to be present, otherwise some random version
iam:
  withOIDC: true


kubernetesNetworkConfig:
  ipFamily: IPv6
```

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: 'putte-bot-1'
  region: 'us-east-1'

managedNodeGroups:
  - name: 'g-1-x-1-pre-2022-03-20-19-13-07'
    instancePrefix: 'g-1'
    instanceName: 'g-1-x-1-pre-2022-03-20-19-13-07'
    labels:
      cluster-autoscaler: 'yes'
      metrics-server: 'yes'
      descheduler: 'yes'
    volumeType: 'gp3'
    volumeSize: 8
    volumeIOPS: 3000
    volumeThroughput: 125
    minSize: 2
    maxSize: 32
    spot: true
    iam:
      withAddonPolicies:
        autoScaler: true
        imageBuilder: true
        ebs: true
        albIngress: true
    instanceSelector:
      vCPUs: 2
      memory: '4'

    ami: ami-0e1b6f116a3733fef
    preBootstrapCommands:
      - date > /tmp/eksler.start
      - echo 'changing root password'
      - echo 'root:badpassword' | sudo chpasswd
      - echo 'password changed'
      - sudo yum install -y htop iotop nano screen bind-utils
      - sudo amazon-linux-extras install epel -y
      - sudo yum install -y stress
      - date > /tmp/eksler.done
    overrideBootstrapCommand: |
      #!/bin/bash
      date > /tmp/eksler.bootstrap.start
      /etc/eks/bootstrap.sh putte-bot-1 |& tee /tmp/eksler.bootstrap.output
      echo 0 > /tmp/eksler.bootstrap.status
      date > /tmp/eksler.bootstrap.done
```

### What happened?

https://github.com/aws/amazon-vpc-cni-k8s/issues/1935#issuecomment-1073301371

### How to reproduce it?

if the above configs return t2.small (instance selector cpu: 2, ram: 4) then it's not a nitro instance and ipv6 fails. Also instance selector 48cpu and 96gb ram return instance types which are not nitro.

**Comment by matti** [comment]
my wrapper workaround:
https://github.com/matti/eksler/blob/124ed6943500c797d6a03b121707a87c9a055042/bin/eksler#L328

+ https://github.com/matti/eksler/blob/124ed6943500c797d6a03b121707a87c9a055042/bin/eksler#L378-L380

this also works for #4956, but that's kinda "resolved" now since the real issue is the nitro missing filter

**Comment by Skarlso** [comment]
How or what is the bug here? Please try and leave a comment on the bug instead of linking to an issue in a different repository. I don't really know from this what you would expect or what the expected behaviour here is or what eksctl should do in this case.

Further, please try to be more explicit or more descriptive in your issues. It takes a some time and effort to figure out what you mean / what you want / what the desired out come should be in many, if not all of your issues. We have a format for a reason for bugs. :) Please try to help with as much information for eksctl as possible. Thank you! :)

**Comment by matti** [comment]
sorry, let's try again:

- when eksctl ipv6 cluster is created
- and managedNodeGroup is used with instanceSelector:
- then eksctl instanceSelector returns instances of with hypervisor both `xen` and `nitro`

--> ipv6 cluster nodes **need** to be `nitro`

the bug: there is no way to use eksctl instanceSelector so that instances returned would be `nitro` only.

the workaround: stop using instanceSelector and use `instanceTypes:`

**Comment by Skarlso** [comment]
Thank you! ❤️

**Comment by Himangini** [comment]
Hi, @matti  Thanks for reporting this bug 👍 If you have a fix in mind, we are happy to accept PRs :)

**Comment by matti** [comment]
@Himangini I think the most straightforward fix would be to extend instanceSelector schema.

currently instanceSelector allows following fields:

```
instanceSelector:
  vCPUs: 4
  memory: 4
  cpuArchitecture: amd64
  gpus: 0
```

the minimum would be to add `hypervisor`

```
instanceSelector:
  hypervisor: nitro
```  

and also potentially other fields as discussed in https://github.com/weaveworks/eksctl/issues/3718

then, I think some validation would be in-order so that if user tries to create ipv6 cluster without `instanceSelector.hypervisor: nitro` - eksctl would either turn it on or error
