### ISSUE TITLE
[Feature] carry any IRSA ARN as postbuild substitute vars for gitops flux bootstrap

### ISSUE THREAD

**Issue by jerryjs** [weaveworks/eksctl#4990]
### What feature/behavior/change do you want?
On eksctl create cluster that generates one or more IRSA arn then pass them as gitops flux flags such that they can be used as flux kustomize postbuild substitute vars

### Why do you want this feature?
This feature enhancement will allow a complete flow thru from cluster creation to flux bootstrap with kustomizations.

**Comment by jerryjs** [comment]
@stefanprodan -- Hi Stefan. Nice to meet you. Guessing you will know what I am referring to. Enabling such a capability would greatly assist in complete automation from cluster creation thru flux management. I can dig in the code to cobble something together between eksctl and flux but guessing you might have already considered this kind of feature request/general integration. I am sure you are very busy doing many important projects if you don't have time to consider this. If so, appreciate any pointers. Thanks

**Comment by jerryjs** [comment]
Thanks @stefanprodan for responding and your IRSA example reference. What I am trying to do is "like" that -- but not for flux itself -- and I want it to happen as part of flux initial processing post-bootstrap. 

So I am referring to IAM roles for service accounts that are created by eksctl config for cloudwatch-agent and fluent-bit as part of installing container-insights. I want to be able to capture those role arns from eksctl cfn addon stack generation and pass to flux invocation so that they can be fill-in for substitute vars to annotate the associated k8s service accounts that are created for each in container-insights.

Here is  concrete example of what I have to do now without this enhanced/flow-through integration between eksctl and flux.

Given eksctl create cluster yaml snippet on service accounts role creation and flux invocation --

```
iam:
  vpcResourceControllerPolicy: true
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: fluent-bit
      namespace: amazon-cloudwatch
    attachPolicyARNs:
    - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
  - metadata:
      name: cloudwatch-agent
      namespace: amazon-cloudwatch
    attachPolicyARNs:
    - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
.....
.....
# gitops with flux
gitops:
  flux:
    gitProvider: git
    flags:
      url: xxx
      private-key-file: xxx
      branch: master
      path: ./clusters/test
      silent: "true"
```
and following flux kustomization --

./clusters/test/infrastructure-container-insights.yaml
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure-container-insights
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/container-insights
  prune: true
  validation: client
  patches:
  - patch: |-
      - op: add
        path: "/metadata/annotations"
        value:
          eks.amazonaws.com/role-arn: ${ServiceAccountRoleCloudwatchAgent}
    target:
      kind: ServiceAccount
      name: cloudwatch-agent
      namespace: amazon-cloudwatch
  - patch: |-
      - op: add
        path: "/metadata/annotations"
        value:
          eks.amazonaws.com/role-arn: ${ServiceAccountRoleFluentBit}
    target:
      kind: ServiceAccount
      name: fluent-bit
      namespace: amazon-cloudwatch
  postBuild:
    substitute:
      ServiceAccountRoleCloudwatchAgent: arn:aws:iam::123456789012:role/eksctl-test-addon-iamserviceaccount-amazon-c-Role1-SKCW4VTLQHNH
      ServiceAccountRoleFluentBit: arn:aws:iam::123456789012:role/eksctl-test-addon-iamserviceaccount-amazon-c-Role1-BT93KLDQ6T3I
      ClusterName: "test"
      RegionName: "us-east-2"
      FluentBitHttpPort: '"2020"'
      FluentBitHttpServer: '"On"'
      FluentBitReadFromHead: '"Off"'
      FluentBitReadFromTail: '"On"'
```
As you can see from the above I have to watch eksctl for when the cfn stacks are complete for the service accounts and take the role arns that are generated and commit those to git repo so they can be available by the time flux invocation is initiated by eksctl/gitops. Of course, if I don't do that commit in time before flux invocation then I have to do the commit post flux bootstrap and then delete the associated container-insight pods so they are regenerated with service account role committed.

Instead, what I am asking for in this feature request is a way to not have to do this manual repo interaction/intervention once the cluster create/flux invocation are started -- I want to have my repo configured for each cluster before flux bootstrap is started and thereby have complete "flow-through" on setup with flux for all kustomize and flux kustomize.

So I want to get the generated service account role arns from eksctl as a result of above and pass to gitops/flux as env vars (or flux configmap or ?? ).

If we could have EKSCTL variable generation with well-defined syntax and use those variables for gitops/flux invocation (or maybe there are other like needs for integration between eksctl and other non-flux integrations).

Something like this on flux invocation from gitops maybe --
```
EKSCTL_SERVICEACCOUNTROLE_FLUENT-BIT=arn:aws:iam::123456789012:role/eksctl-test-addon-iamserviceaccount-amazon-c-Role1-SKCW4VTLQHNH     EKSCTL_SERVICEACCOUNTROLE_CLOUDWATCH-AGENT=arn:aws:iam::123456789012:role/eksctl-test-addon-iamserviceaccount-amazon-c-Role1-BT93KLDQ6T3I flux <usual args>
```
So those env vars can be used as postBuild substitute vars below --

./clusters/test/infrastructure-container-insights.yaml
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure-container-insights
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/container-insights
  prune: true
  validation: client
  patches:
  - patch: |-
      - op: add
        path: "/metadata/annotations"
        value:
          eks.amazonaws.com/role-arn: ${ServiceAccountRoleCloudwatchAgent}
    target:
      kind: ServiceAccount
      name: cloudwatch-agent
      namespace: amazon-cloudwatch
  - patch: |-
      - op: add
        path: "/metadata/annotations"
        value:
          eks.amazonaws.com/role-arn: ${ServiceAccountRoleFluentBit}
    target:
      kind: ServiceAccount
      name: fluent-bit
      namespace: amazon-cloudwatch
  postBuild:
    substitute:
      ServiceAccountRoleCloudwatchAgent: ${EKSCTL_SERVICEACCOUNTROLE_CLOUDWATCH-AGENT}
      ServiceAccountRoleFluentBit: ${EKSCTL_SERVICEACCOUNTROLE_FLUENT-BIT}
      ClusterName: "test"
      RegionName: "us-east-2"
      FluentBitHttpPort: '"2020"'
      FluentBitHttpServer: '"On"'
      FluentBitReadFromHead: '"Off"'
      FluentBitReadFromTail: '"On"'
```
Or maybe there is a convention for a configmap that is generated in eksctl instead of env vars and that configmap passed to flux.

I do appreciate your consideration.

Thank you.
