### ISSUE TITLE
[Bug]  Managed Nodegroups are not supported for this cluster version - when running Kubernetes 1.21, Platform eks.2 and eksctl > 0.85

### ISSUE THREAD

**Issue by fbuchmeier-abi** [weaveworks/eksctl#4997]
### What were you trying to accomplish?

Trying to create managed node groups from cluster config file:

```
eksctl create nodegroup --config-file /tmp/ansible.av6vbw8e
```

on a cluster running Kubernetes Version 1.21 and Platform Version eks.2

### What happened?

ekcstl refuses to create new managed node groups because the cluster needs to be "updated" first.

### How to reproduce it?

Use one of the following eksctl versions:

- 0.86
- 0.87
- 0.88

The problem when reproducing this issue is, that you need an existing EKS cluster running eks.1 or eks.2 [Platform Version](https://docs.aws.amazon.com/eks/latest/userguide/platform-versions.html).

At the moment, the problem can not be reproduced when creating a new EKS cluster, since AWS always created new clusters with the latest available Platform Version, which is currently eks.5.

**Logs**

```
STDOUT:

2022-03-21 14:24:34 [ℹ]  eksctl version 0.87.0
2022-03-21 14:24:34 [ℹ]  using region eu-central-1


STDERR:

I0321 14:24:35.975075  134378 request.go:668] Waited for 1.062215492s due to client-side throttling, not priority and fairness, request: GET: https://xxx.gr7.eu-central-1.eks.amazonaws.com/apis/acm.aws.crossplane.io/v1alpha1?timeout=32s

Error: Managed Nodegroups are not supported for this cluster version. Please update the cluster before adding managed nodegroups
```

**Anything else we need to know?**

References to the AWS documentation on the distinction between Kubernetes and Platform versions:

- [Kubernetes Versions](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html)
- [Platform Versions](https://docs.aws.amazon.com/eks/latest/userguide/platform-versions.html)

Note that Platform Versions can not be upgraded by the user:

> Automatic upgrades of existing Amazon EKS platform versions are rolled out incrementally. The roll-out process might take some time. If you need the latest Amazon EKS platform version features immediately, you should create a new Amazon EKS cluster.

Thus, the error message "Please update the cluster before adding managed nodegroups" is misleading, as users can not update the cluster directly.

I have traced the issue to this commit: https://github.com/weaveworks/eksctl/commit/a5be85d96b0effe37d308b0e716e67074e59446c?diff=split

Specifically the changes to `pkg/eks/eks.go` and `pkg/eks/eks_test.go`.

In eksctl <= 0.85, the function `ClusterSupportsManagedNodes` returned `true` when a valid Kubernetes version (1.15+) was found. After the refactoring, `ClusterSupportsManagedNodes` only returns `true` when the Platform Version is greater than 3. The problem with this is, that new Kubernetes feature versions (e.g. 1.22) will be released with the Platform version eks.1:

> When a new Kubernetes minor version is available in Amazon EKS, such as 1.21, the initial Amazon EKS platform version for that Kubernetes minor version starts at eks.1

This means that once Kubernetes 1.22 will be available in EKS, we will no longer be able to create managed node groups until AWS has updated the Platform Version to at least eks.3.

The validation can be found here: https://github.com/weaveworks/eksctl/blob/a5be85d96b0effe37d308b0e716e67074e59446c/pkg/eks/eks.go#L97

**Affected Versions**

- 0.86
- 0.87
- 0.88

**Working Versions**

<= 0.85

**Cluster Config**

```
managedNodeGroups:
  - name: erfurt
    instanceName: erfurt
    instanceType: c5a.2xlarge
    minSize: 1
    maxSize: 3
    availabilityZones: ['eu-central-1a']
    privateNetworking: true
    amiFamily: AmazonLinux2
    securityGroups:
      attachIDs: []
    volumeSize: 50
    volumeName: /dev/xvda
    volumeType: gp3
    volumeEncrypted: true
    volumeKmsKeyID: xxx
    ebsOptimized: True
```
