### ISSUE TITLE
Getting unable to determine AMI in us-east-1 for Bottlerocket

### ISSUE THREAD

**Issue by lanecm** [weaveworks/eksctl#4998]
Hello... I'm getting the following error when trying to create bottlerocket nodegroup in `us-east-1` :

```
$ eksctl create nodegroup --config-file k8s/eksctl/kube.yaml --include=ng-03-24-2022T0809a
2022-03-24 09:45:08 [ℹ]  eksctl version 0.87.0
2022-03-24 09:45:08 [ℹ]  using region us-east-1
2022-03-24 09:45:11 [✖]  unable to determine the account owner for image family Bottlerocket
Error: unable to determine AMI to use: unable to determine AMI for region us-east-1, version 1.20, instance type m5.2xlarge and image family Bottlerocket
```

I've updated a number of other clusters and I haven't seen this error before. I did find this issue:

https://github.com/weaveworks/eksctl/issues/1606

but that's a different region.

Config file snippet:

```
kind: ClusterConfig
metadata:
  name: dttanalytics-cap-sb
  region: us-east-1
  version: "1.20"
nodeGroups:
  - name: ng-03-24-2022T0809a
    instanceType: m5.2xlarge
    labels:
      lifecycle: OnDemand
      bottlerocket.aws/platform-version: "1.0.0"
      bottlerocket.aws/updater-interface-version: "2.0.0"
    maxSize: 15
    minSize: 5
    amiFamily: Bottlerocket
    ami: auto
    privateNetworking: true
    volumeSize: 100
    volumeType: gp2
  - name: ng-03-24-2022T0809f:
    instanceType: p3.2xlarge
    labels:
      lifecycle: OnDemand
      role: workers
      nvidia.com/gpu: "true"
      k8s.amazonaws.com/accelerator: nvidia-tesla
      bottlerocket.aws/platform-version: "1.0.0"
      bottlerocket.aws/updater-interface-version: "2.0.0"
    maxSize: 15
    minSize: 2
    name: ng-03-24-2022T0809f
    amiFamily: Bottlerocket
    ami: auto
    privateNetworking: true
    volumeSize: 100
    volumeType: gp2
    taints:
      feaster: "true:NoSchedule"
    tags:
      k8s.io/cluster-autoscaler/node-template/taint/dedicated: nvidia.com/gpu=true
      k8s.io/cluster-autoscaler/node-template/label/nvidia.com/gpu: "true"
      k8s.io/cluster-autoscaler/enabled: "true"
```

I'm just trying to create the non-gpu nodegroup at the moment. Please let me know if you need more information!

**Comment by cPu1** [comment]
@lanecm, can you post the full `ClusterConfig` that does not have any syntax errors? Please post the contents of `k8s/eksctl/kube.yaml` after redacting any sensitive information.

**Comment by lanecm** [comment]
Hello... Yes, of course, entire file:

```
apiVersion: eksctl.io/v1alpha5
iam:
  serviceAccounts:
    - attachPolicyARNs:
        - arn:aws:iam::****************:policy/ExternalDns
      metadata:
        name: external-dns
        namespace: kube-system
    - attachPolicyARNs:
        - arn:aws:iam::****************:policy/ExternalSecrets
      metadata:
        name: kubernetes-external-secrets
        namespace: kube-system
    - attachPolicyARNs:
        - arn:aws:iam::****************:policy/AlbIngressController
      metadata:
        name: cfa-aws-load-balancer-controller
        namespace: kube-system
    - attachPolicyARNs:
        - arn:aws:iam::****************:policy/CloudformationOperator
      metadata:
        name: cloudformation-operator
        namespace: kube-system
  withOIDC: true
kind: ClusterConfig
metadata:
  name: dttanalytics-cap-sb
  region: us-east-1
  version: "1.20"
nodeGroups:
  - iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess
      withAddonPolicies:
        appMesh: true
        autoScaler: true
        ebs: true
    instanceType: m5.2xlarge
    labels:
      lifecycle: OnDemand
      bottlerocket.aws/platform-version: "1.1.0"
      bottlerocket.aws/updater-interface-version: "2.0.0"
    maxSize: 15
    minSize: 5
    name: ng-03-24-2022T0809a
    amiFamily: Bottlerocket
    ami: auto
    privateNetworking: true
    volumeSize: 100
    volumeType: gp2
  - iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      withAddonPolicies:
        appMesh: true
        autoScaler: true
        ebs: true
    instanceType: p3.2xlarge
    labels:
      lifecycle: OnDemand
      role: workers
      nvidia.com/gpu: "true"
      k8s.amazonaws.com/accelerator: nvidia-tesla
      bottlerocket.aws/platform-version: "1.1.0"
      bottlerocket.aws/updater-interface-version: "2.0.0"
    maxSize: 15
    minSize: 2
    name: ng-03-24-2022T0809f
    amiFamily: Bottlerocket
    ami: auto
    privateNetworking: true
    volumeSize: 100
    volumeType: gp2
    taints:
      feaster: "true:NoSchedule"
    tags:
      k8s.io/cluster-autoscaler/node-template/taint/dedicated: nvidia.com/gpu=true
      k8s.io/cluster-autoscaler/node-template/label/nvidia.com/gpu: "true"
      k8s.io/cluster-autoscaler/enabled: "true"
vpc:
  id: vpc-*****************
  subnets:
    private:
      us-east-1a:
        id: subnet-*****************
      us-east-1b:
        id: subnet-*****************
      us-east-1c:
        id: subnet-*****************
      us-east-1d:
        id: subnet-*****************
    public:
      us-east-1a:
        id: subnet-*****************
      us-east-1b:
        id: subnet-*****************
      us-east-1c:
        id: subnet-*****************
      us-east-1d:
        id: subnet-*****************
```
