### ISSUE TITLE
[Bug] I should be able to create a Windows nodegroup with GPU instances (revert #4243)

### ISSUE THREAD

**Issue by doctorpangloss** [weaveworks/eksctl#5037]
### What were you trying to accomplish?
Create a Windows node group on an NVIDIA GPU instance

### What happened?
The error from https://github.com/cPu1/eksctl/blob/4bcff91151570a1a15a2a0d8d07ae33799500380/pkg/apis/eksctl.io/v1alpha5/validation.go#L286

### How to reproduce it?
```
nodeGroups:
  - name: xxx
    instanceType: g5.2xlarge
    privateNetworking: false
    amiFamily: WindowsServer20H2CoreContainer
```

**Logs**

```
Error: couldn't create cluster provider from options: NVIDIA GPU instance types are not supported for WindowsServer20H2CoreContainer
```
**Anything else we need to know?**

It's my prerogative to install the necessary drivers on these nodes with a DaemonSet.

**Versions**

```
$ eksctl info
eksctl version: 0.89.0
kubectl version: v1.22.5
OS: windows
```
