### ISSUE TITLE
[Bug] Setting custom VPCs generates availabilityZones config, when it should not.

### ISSUE THREAD

**Issue by darrylweaver** [weaveworks/eksctl#5068]
### What were you trying to accomplish?
I am creating an EKS cluster with existing VPCs.
I run the command:
`eksctl create cluster -n darryl-demo-cluster-test --dry-run  --vpc-private-subnets=subnet-0b51d52eb1cc34acc,subnet-090124c9df9ed8b3c,subnet-0847827b4506c74fd --vpc-public-subnets=subnet-04bc97117eac64464,subnet-009824661692a9c65,subnet-08f441b216eaf5506 > eks-management-cluster.yaml`

I then want to deploy the cluster with the file output using:
```
eksctl create cluster -f eks-management-cluster.yaml
```

### What happened?
When I create the cluster it reports:
`Error: vpc.subnets and availabilityZones cannot be set at the same time`

Inspecting the output file I can see:
```
apiVersion: eksctl.io/v1alpha5
availabilityZones:
- eu-west-2b
- eu-west-2c
- eu-west-2a

<IRRELEVANT CONTENT REMOVED FOR BREVITY>

vpc:
  autoAllocateIPv6: false
  cidr: 10.115.80.0/20
  clusterEndpoints:
    privateAccess: false
    publicAccess: true
  id: vpc-05c2c69b5d54a1b47
  manageSharedNodeSecurityGroupRules: true
  nat:
    gateway: Disable
  subnets:
    private:
      eu-west-2a:
        az: eu-west-2a
        cidr: 10.115.81.0/24
        id: subnet-0b51d52eb1cc34acc
      eu-west-2b:
        az: eu-west-2b
        cidr: 10.115.83.0/24
        id: subnet-0847827b4506c74fd
      eu-west-2c:
        az: eu-west-2c
        cidr: 10.115.85.0/24
        id: subnet-090124c9df9ed8b3c
    public:
      eu-west-2a:
        az: eu-west-2a
        cidr: 10.115.80.0/24
        id: subnet-08f441b216eaf5506
      eu-west-2b:
        az: eu-west-2b
        cidr: 10.115.82.0/24
        id: subnet-04bc97117eac64464
      eu-west-2c:
        az: eu-west-2c
        cidr: 10.115.84.0/24
        id: subnet-009824661692a9c65
```
Removing the availabilityZones section allow cluster creation to proceed.

### How to reproduce it?
`eksctl create cluster --dry-run  --vpc-private-subnets=subnet-0b51d52eb1cc34acc,subnet-090124c9df9ed8b3c,subnet-0847827b4506c74fd --vpc-public-subnets=subnet-04bc97117eac64464,subnet-009824661692a9c65,subnet-08f441b216eaf5506 > eks-management-cluster.yaml`

`eksctl create cluster -f eks-management-cluster.yaml`

**Logs**
`Error: vpc.subnets and availabilityZones cannot be set at the same time`

**Anything else we need to know?**
Ubuntu 20.04 using a downloaded binary

**Versions**

```
$ eksctl info
eksctl version: 0.88.0
kubectl version: v1.22.1
OS: linux

```
