### ISSUE TITLE
[Bug] Windows nodegroups cannot be created using custom AMIs

### ISSUE THREAD

**Issue by rawahars** [weaveworks/eksctl#5075]
### What were you trying to accomplish?

I am trying to create Windows nodegroups using a custom AMI.
```
eksctl create nodegroup -f 21-windows-manifest.yaml
```

If the config file does not contain `overrideBootstrapCommand` then we get an error-
```
Error: couldn't create cluster provider from options: nodeGroups[1].overrideBootstrapCommand is required when using a custom AMI (nodeGroups[1].ami)
```

However, if we include `overrideBootstrapCommand` then we get the following error-
```
Error: couldn't create cluster provider from options: overrideBootstrapCommand is not supported for WindowsServer2019FullContainer nodegroups (path=nodeGroups[1].overrideBootstrapCommand)
```

Therefore, in essence, we cannot create a Windows nodegroup with custom AMI IDs.

### What happened?

When using the following config for nodegroup-
```
---
  apiVersion: eksctl.io/v1alpha5
  kind: ClusterConfig
  
  metadata:
    name: rawahars-21-test
    region: us-west-2
    version: '1.21'
  
  nodeGroups:
    - name: windows-ng
      instanceType: m5.2xlarge
      minSize: 2
      volumeSize: 100
      ssh: # use existing EC2 key
        publicKeyName: <Key_PAIR>
      ami: <AMI_ID>
      amiFamily: WindowsServer2019FullContainer
      iam:
        attachPolicyARNs:
          - arn:aws:iam::aws:policy/AmazonSSMFullAccess                 # Required to run on instance test for nodes
          - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess              # Required to run on instance test for nodes
          - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy           # Required EKS Node IAM policy
          - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
          - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy                # Required EKS Node IAM policy
```
we get the following error-
`Error: couldn't create cluster provider from options: nodeGroups[1].overrideBootstrapCommand is required when using a custom AMI (nodeGroups[1].ami)`

When we add the `overrideBootstrapCommand` flag to the config, we get the following error-
`Error: couldn't create cluster provider from options: overrideBootstrapCommand is not supported for WindowsServer2019FullContainer nodegroups (path=nodeGroups[1].overrideBootstrapCommand)`

### How to reproduce it?

The steps to replicate this are-
- Create a new EKS cluster
```
eksctl create cluster \
    --name rawahars-21-test \
    --version 1.21 \
    --without-nodegroup \
    --region us-west-2 \
    --with-oidc \
    --zones us-west-2a,us-west-2b,us-west-2c
```
- Create a new config as provided above
- Launch Windows nodegroups
```
eksctl create nodegroup -f 21-windows-manifest-docker.yaml
```

**Logs**

```
2022-04-05 15:15:34 [ℹ]  eksctl version 0.90.0
2022-04-05 15:15:34 [ℹ]  using region us-west-2
NAME			REGION		EKSCTL CREATED
rawahars-21-test	us-west-2	True
```

**Anything else we need to know?**

**Versions**

```
rawahars@3c22fb665254 tmp % eksctl info
eksctl version: 0.90.0
kubectl version: v1.21.2-13+d2965f0db10712
OS: darwin
```
