### ISSUE TITLE
[Bug/Question] Compatibility testing with EKS-optimized AMI

### ISSUE THREAD

**Issue by cartermckinnon** [weaveworks/eksctl#5092]
### What were you trying to accomplish?
I'm on the EKS team and work on our AMI. When we build a new AMI for release, we run compatibility tests for recent `eksctl` releases. These tests create an unmanaged nodegroup with the AMI release candidate.

I'm having trouble authoring a test that succeeds for `eksctl` versions on both sides of this change: https://github.com/weaveworks/eksctl/pull/4968

### What happened?

0.91.0, the only release that contains this breaking change AFAIU, requires us to use:
```
    overrideBootstrapCommand: |
      #!/bin/bash
      source /var/lib/cloud/scripts/eksctl/bootstrap.helper.sh
      /etc/eks/bootstrap.sh my-cluster --kubelet-extra-args "--node-labels=$NODE_LABELS"
```

But this bootstrap command causes kubelet to fail on <=0.90.0:
```
systemd[1]: Failed to load environment files: No such file or directory
systemd[1]: kubelet.service failed to run 'start-pre' task: No such file or directory
systemd[1]: Failed to start Kubernetes Kubelet.
systemd[1]: Unit kubelet.service entered failed state.
systemd[1]: kubelet.service failed.
```

### How to reproduce it?
```yaml
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: my-cluster
nodeGroups:
  - name: my-nodes
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
    ami: $CUSTOM_AMI
    overrideBootstrapCommand: |
      #!/bin/bash
      source /var/lib/cloud/scripts/eksctl/bootstrap.helper.sh
      /etc/eks/bootstrap.sh my-cluster --kubelet-extra-args "--node-labels=$NODE_LABELS"
```

### What next?

While I can add handling for this, I want to zoom out and reevaluate the purpose of these tests in our AMI release process. Because `eksctl` is now only using our bootstrap process, I don't think these tests are adding value. From my perspective, a change in our AMI that "breaks" unmanaged, custom AMI nodegroups created by `eksctl` will need to be resolved by `eksctl`. Put another way, if these tests fail (and all of our other tests pass), it indicates a problem in `eksctl`, not the AMI. I'm wondering what the `eksctl` maintainers think about us removing these tests. Does `eksctl` do any similar testing?

Or, if you'd like us to continue this testing -- is there a bootstrap command we can use on both sides of the #4968 divide?
