### ISSUE TITLE
Why is there a second launch template?

### ISSUE THREAD

**Issue by tanvp112** [weaveworks/eksctl#5129]
Hi, when creating a cluster with settings like the following:

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: cluster-26
  region: us-west-2
managedNodeGroups:
- name: spot
  instanceTypes: ["c3.large","c4.large","c5.large","c5d.large","c5n.large","c5a.large"]
  spot: true
```

Two launch templates were created:

![image](https://user-images.githubusercontent.com/57385114/163711144-06f249fd-3240-452a-bb18-f9074925538f.png)

The Auto Scaling Groups only refer to the one which is created by the role linked to EKS service:

![image](https://user-images.githubusercontent.com/57385114/163711188-dada58e2-bbc5-4dda-a2ce-87786807c12e.png)

Is this something expected? What is the purpose of the second launch template which is _created under the identity of the IAM user_ who executed the eksctl command?
