### ISSUE TITLE
[Bug] Error: couldn't create cluster provider from options: nodeGroups[0].overrideBootstrapCommand is required when using a custom AMI (nodeGroups[0].ami)

### ISSUE THREAD

**Issue by ravikiran-talluri** [weaveworks/eksctl#5143]
### What were you trying to accomplish?

I am trying to add preBootstrapCommands while creating a windowsnodegroup 
https://github.com/weaveworks/eksctl/issues/3563#issuecomment-888089036
### What happened?

But eksctl is throwing error  "Error: couldn't create cluster provider from options: nodeGroups[0].overrideBootstrapCommand is required when using a custom AMI (nodeGroups[0].ami)"
I am seeing this error only while creating the windows nodegroup. I can able to create linux nodegroup with some preBootstrapCommands without any issue
### How to reproduce it?

```
nodeGroups:
- ami: ami-0a1118e5c76ff2c5c
  amiFamily: WindowsServer2019CoreContainer
  availabilityZones:
  - us-east-1a
  desiredCapacity: 1
  iam:
    instanceProfileARN: arn:aws:iam::XXXXXXXXXX
    instanceRoleARN: arn:aws:iam::XXXXXXXXXX
  instanceType: t3a.xlarge
  maxSize: 2
  minSize: 1
  name: eks-worker-xyz
  preBootstrapCommands:
  - Invoke-WebRequest XXXXXXXX
  - Start-Process XXXXXXX
```

**Logs**

**Anything else we need to know?**

K8s version: 1.21
**Versions**

```
$ eksctl info
```
k8s-devsecops> eksctl info
eksctl version: 0.93.0
kubectl version: v1.23.3
OS: windows
