### ISSUE TITLE
work fine yaml about bottlerocket custom ami in 0.89, but not workable in 0.90+

### ISSUE THREAD

**Issue by panlm** [weaveworks/eksctl#5167]
```
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ekscluster14 
  region: "us-east-2" 
  version: "1.20" 

# REPLACE THIS CODE BLOCK
vpc:
  subnets:
    private:
      us-east-2a:
        id: subnet-03465e22196811a03
      us-east-2b:
        id: subnet-0ba8525e94230e707
    public:
      us-east-2a:
        id: subnet-0319efe4df79e12e1
      us-east-2b:
        id: subnet-05e967f1b05a31965

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

nodeGroups:
- name: ng1
  minSize: 1
  maxSize: 5
  desiredCapacity: 1
  instanceType: m5.xlarge
  privateNetworking: true
  ami: ami-0f425daf07b86350f
  amiFamily: Bottlerocket
```
this ami is built by myself following bottlerocket guide ([LINK](https://github.com/bottlerocket-os/bottlerocket/blob/develop/BUILDING.md))

i could create cluster successfully with `eksctl create cluster -f cluster.yaml`
but cannot create cluster with eksctl 0.94
