### ISSUE TITLE
Windows Nodegroup Bootstrap Override For Custom AMIs [Help] 

### ISSUE THREAD

**Issue by maopei820219** [weaveworks/eksctl#5186]
Buddies,
There is an announcement related to Nodegroup Bootstrap Override For Custom AMIs: https://eksctl.io/usage/nodegroup-override-announcement/. There is a sample configuration for linux. Could anyone share a sample for Windows? The following is the yaml file I used to create the cluster. The Windows machines could not join the cluster. If possible, please help to correct the yaml file below.

Thanks,
Jacky

```
$ eksctl version
0.95.0
```

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-windows
  region: us-east-1
  version: "1.22"

availabilityZones: ["us-east-1a", "us-east-1b", "us-east-1c"]

managedNodeGroups:
- name: spot
  minSize: 2
  maxSize: 3
  desiredCapacity: 2
  instanceTypes: ["m5.large", "m5d.large", "m5a.large", "m5ad.large", "m5n.large", "m5dn.large"]
  spot: true
  ssh:
    allow: true
    publicKeyPath: ./key/id_rsa.pub

nodeGroups:
- name: windows
  amiFamily: WindowsServer2019CoreContainer
  ami: ami-xxxxx
  minSize: 1
  maxSize: 10
  desiredCapacity: 1
  instancesDistribution:
    maxPrice: 1.000
    instanceTypes: ["m5.large", "m5d.large", "m5a.large", "m5ad.large", "m5n.large", "m5dn.large"]
    onDemandBaseCapacity: 0
    onDemandPercentageAboveBaseCapacity: 0
    spotInstancePools: 10
  overrideBootstrapCommand: |
    <powershell>
    [string]$EKSBootstrapScriptFile = "$env:ProgramFiles\Amazon\EKS\Start-EKSBootstrap.ps1"
    & $EKSBootstrapScriptFile -EKSClusterName "eks-windows" -KubeletExtraArgs "--node-labels=alpha.eksctl.io/cluster-name=eks-windows,alpha.eksctl.io/nodegroup-name=windows --register-with-taints=" 3>&1 4>&1 5>&1 6>&1
    </powershell>

secretsEncryption:
  keyARN: arn:aws:kms:us-east-1:xxxxx:key/xxxxx
```
