### ISSUE TITLE
[Bug] Creating unmanaged NodeGroup on non-eksctl created cluster fails with error

### ISSUE THREAD

**Issue by Alan-Sikka** [weaveworks/eksctl#5191]
Using downloaded binary, default profile for AWS credentials.

eksctl version: 0.77.0
kubectl version: v1.22.5
OS: windows

Tested also on 0.95.0

```
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: Main-Cluster
  region: us-east-1

nodeGroups:
- name: build-agent
  instanceType: m6i.large
  amiFamily: WindowsServer2019FullContainer
  desiredCapacity: 1
  minSize: 1
  maxSize: 4
  tags:
    name: build-agent
  taints:
  - key: "build-agent"
    value: "true"
    effect: NoSchedule
  volumeType: gp3
  volumeSize: 40

vpc:
  id: "vpc-12345"
  cidr: "172.30.0.0/16"
  securityGroup: "sg-12345"
  subnets:
    private:
      us-east-1b:
        id: "subnet-12345"
        cidr: "172.30.1.0/24"
      us-east-1a:
        id: "subnet-12345"
        cidr: "172.30.0.0/24"
```

Running `eksctl create nodegroup --config-file=unmanaged-windows-group.yml` results in error: `creating CloudFormation stack "eksctl-xxx" ValidationError: [/Resources/NodeGroup/Type/VPCZoneIdentifier] 'null' values are not allowed in templates`
