### ISSUE TITLE
[Bug] kubeReserved / systemReserved not working

### ISSUE THREAD

**Issue by bitva77** [weaveworks/eksctl#5199]
### What were you trying to accomplish?

Create a node group (`t3.xlarge`) with:

```
    kubeletExtraConfig:
      kubeReserved:
        cpu: "300m"
        memory: "300Mi"
        ephemeral-storage: "1Gi"
      maxPods: 110
      kubeReservedCgroup: "/kube-reserved"
      systemReserved:
        cpu: "300m"
        memory: "300Mi"
        ephemeral-storage: "1Gi"
      evictionHard:
        memory.available: "200Mi"
        nodefs.available: "10%"
```

Then run a pod in that node group that chews up all memory:

`stress-ng --vm-bytes 13890M --vm-keep -m 1`

### What happened?

Node goes `NotReady` and is unresponsive because I ate all the RAM.

**Versions**

```
$ eksctl info

eksctl version: 0.86.0
kubectl version: v1.21.2
OS: linux
```

### What do you expect to happen?

I sort of expect kubelet to protect my dumb ass based on those settings above  :)

**Comment by Skarlso** [comment]
I just noticed that once we deprecated our own override script, `kubeletExtraConfig` is actually only applied for managed nodegroups. If you are using unmanaged nodegroups, this config is basically ignored.

**Comment by bitva77** [comment]
Gotcha.  Here's our config:

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: preprod-eks-sandbox
  region: us-west-2
  version: "1.21"
  tags:
    Environment: UAT
vpc:
  subnets:
    private:
      us-west-2a: {id: subnet-XXX}
      us-west-2b: {id: subnet-XYX}
      us-west-2c: {id: subnet-XXZ}
  clusterEndpoints:
    publicAccess: false
    privateAccess: true
nodeGroups:
  - name: eks-sandbox-observability-us-west-2a-xlarge-v4
    labels:
      type: xlarge
      workload: observability-high
    taints:
      key: observability-high:NoSchedule
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    instanceType: r6i.xlarge
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
        - arn:aws:iam::958833991614:policy/SSM-Management
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true
        ebs: true
    privateNetworking: true
    availabilityZones: ["us-west-2a"]
    tags:
      Environment: UAT
    ami: ami-0ba0e1216bca4b234
    maxPodsPerNode: 110
    kubeletExtraConfig:
      kubeReserved:
        cpu: "300m"
        memory: "300Mi"
        ephemeral-storage: "1Gi"
      maxPods: 110
      kubeReservedCgroup: "/kube-reserved"
      systemReserved:
        cpu: "300m"
        memory: "300Mi"
        ephemeral-storage: "1Gi"
      evictionHard:
        memory.available: "200Mi"
        nodefs.available: "10%"
      ShutdownGracePeriod: "30s"
      ShutdownGracePeriodCriticalPods: "10s"
```

I thought I saw a reply where this would only work with managed nodegroups now (I see it's gone now or I'm going crazy :) and if so, that does make sense.

We have plans to move to managed nodegroups.  I know the `ShutdownGracePeriod` option doesn't work on regular nodegroups I found either.

**Comment by Skarlso** [comment]
Yeah, I was wrong in that regard. :D You aren't going crazy. I just removed it because I realised it was a mistake haha. Sorry about that. :)

**Comment by bitva77** [comment]
So, the nodes have this in `/etc/eksctl/kubelet.yaml`

```
ShutdownGracePeriod: 30s
ShutdownGracePeriodCriticalPods: 10s
address: 0.0.0.0
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
  webhook:
    cacheTTL: 2m0s
    enabled: true
  x509:
    clientCAFile: /etc/eksctl/ca.crt
authorization:
  mode: Webhook
  webhook:
    cacheAuthorizedTTL: 5m0s
    cacheUnauthorizedTTL: 30s
clusterDNS:
- 172.20.0.10
clusterDomain: cluster.local
evictionHard:
  memory.available: 200Mi
  nodefs.available: 10%
featureGates:
  RotateKubeletServerCertificate: true
kind: KubeletConfiguration
kubeReserved:
  cpu: 300m
  ephemeral-storage: 1Gi
  memory: 300Mi
kubeReservedCgroup: /kube-reserved
maxPods: 110
serverTLSBootstrap: true
systemReserved:
  cpu: 300m
  ephemeral-storage: 1Gi
  memory: 300Mi
```
