### ISSUE TITLE
[Bug] Incorrect aws-node volume configuration when using containerd

### ISSUE THREAD

**Issue by semoac** [weaveworks/eksctl#5214]
### What were you trying to accomplish?

Enable support for containerd on `aws-vpc-cni` following the official documentation and the indications of the AWS support team.

For more context: After encounter problems with the startup process of some `aws-node` pods, the support team pointed out to me that the manifest is not mounting the correct directory.

The problem in question is related to aws-node pods getting stuck after printing this output:

```
Getting running pod sandboxes from \"unix:///var/run/dockershim.sock\
```

https://github.com/aws/amazon-vpc-cni-k8s#container-runtime
https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/master/aws-k8s-cni.yaml#L229-L244
https://github.com/aws/amazon-vpc-cni-k8s/blob/314625892e91ce36fba87211694537071b590c92/pkg/cri/cri.go#L68

https://github.com/weaveworks/eksctl/blob/9a3e8e7b943362d09d212f3c9edab7ce58dbbb13/pkg/addons/default/assets/aws-node.yaml#L247

### What happened?

`aws-node` is not using the correct mountPath and hostPath  when using `containerd`.

### How to reproduce it?

Setup a cluster with containerd and look at the DaemonSet manifest.

**Logs**

```
fedora-station:~/infrastructure$ kubectl -n kube-system get ds aws-node -o yaml | kubectl neat
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "1"
  labels:
    k8s-app: aws-node
  name: aws-node
  namespace: kube-system
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: aws-node
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: aws-node
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
              - key: eks.amazonaws.com/compute-type
                operator: NotIn
                values:
                - fargate
      containers:
      - env:
        - name: ADDITIONAL_ENI_TAGS
          value: '{}'
        - name: AWS_VPC_CNI_NODE_PORT_SUPPORT
          value: "true"
        - name: AWS_VPC_ENI_MTU
          value: "9001"
        - name: AWS_VPC_K8S_CNI_CONFIGURE_RPFILTER
          value: "false"
        - name: AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG
          value: "false"
        - name: AWS_VPC_K8S_CNI_EXTERNALSNAT
          value: "false"
        - name: AWS_VPC_K8S_CNI_LOGLEVEL
          value: DEBUG
        - name: AWS_VPC_K8S_CNI_LOG_FILE
          value: /host/var/log/aws-routed-eni/ipamd.log
        - name: AWS_VPC_K8S_CNI_RANDOMIZESNAT
          value: prng
        - name: AWS_VPC_K8S_CNI_VETHPREFIX
          value: eni
        - name: AWS_VPC_K8S_PLUGIN_LOG_FILE
          value: /var/log/aws-routed-eni/plugin.log
        - name: AWS_VPC_K8S_PLUGIN_LOG_LEVEL
          value: DEBUG
        - name: DISABLE_INTROSPECTION
          value: "false"
        - name: DISABLE_METRICS
          value: "false"
        - name: ENABLE_POD_ENI
          value: "false"
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: WARM_ENI_TARGET
          value: "1"
        image: 602401143452.dkr.ecr.us-east-1.amazonaws.com/amazon-k8s-cni:v1.7.5-eksbuild.1
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - /app/grpc-health-probe
            - -addr=:50051
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: aws-node
        ports:
        - containerPort: 61678
          hostPort: 61678
          name: metrics
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /app/grpc-health-probe
            - -addr=:50051
          failureThreshold: 3
          initialDelaySeconds: 1
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 10m
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /host/opt/cni/bin
          name: cni-bin-dir
        - mountPath: /host/etc/cni/net.d
          name: cni-net-dir
        - mountPath: /host/var/log/aws-routed-eni
          name: log-dir
        - mountPath: /var/run/aws-node
          name: run-dir
        - mountPath: /var/run/dockershim.sock
          name: dockershim
        - mountPath: /run/xtables.lock
          name: xtables-lock
      dnsPolicy: ClusterFirst
      hostNetwork: true
      initContainers:
      - env:
        - name: DISABLE_TCP_EARLY_DEMUX
          value: "false"
        image: 602401143452.dkr.ecr.us-east-1.amazonaws.com/amazon-k8s-cni-init:v1.7.5-eksbuild.1
        imagePullPolicy: Always
        name: aws-vpc-cni-init
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /host/opt/cni/bin
          name: cni-bin-dir
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: aws-node
      serviceAccountName: aws-node
      terminationGracePeriodSeconds: 10
      tolerations:
      - operator: Exists
      volumes:
      - hostPath:
          path: /opt/cni/bin
          type: ""
        name: cni-bin-dir
      - hostPath:
          path: /etc/cni/net.d
          type: ""
        name: cni-net-dir
      - hostPath:
          path: /var/run/dockershim.sock
          type: ""
        name: dockershim
      - hostPath:
          path: /run/xtables.lock
          type: ""
        name: xtables-lock
      - hostPath:
          path: /var/log/aws-routed-eni
          type: DirectoryOrCreate
        name: log-dir
      - hostPath:
          path: /var/run/aws-node
          type: DirectoryOrCreate
        name: run-dir
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 10%
    type: RollingUpdate

fedora-station:~/infrastructure$ kubectl get node -o yaml | grep containerd             
      containerRuntimeVersion: containerd://1.4.6
      containerRuntimeVersion: containerd://1.4.6
      containerRuntimeVersion: containerd://1.4.6
      containerRuntimeVersion: containerd://1.4.6
      containerRuntimeVersion: containerd://1.4.6
      containerRuntimeVersion: containerd://1.4.6
      containerRuntimeVersion: containerd://1.4.6
      containerRuntimeVersion: containerd://1.4.6
      containerRuntimeVersion: containerd://1.4.6
      containerRuntimeVersion: containerd://1.4.6
      containerRuntimeVersion: containerd://1.4.6
```

**Versions**
```
fedora-station:~/infrastructure$ eksctl info
eksctl version: 0.93.0
kubectl version: v1.20.15
OS: linux
fedora-station:~/infrastructure$ kubectl  get nodes
NAME                          STATUS   ROLES    AGE     VERSION
ip-10-8-19-250.ec2.internal   Ready    <none>   5d19h   v1.20.11-eks-f17b81
ip-10-8-21-129.ec2.internal   Ready    <none>   5d20h   v1.20.11-eks-f17b81
ip-10-8-28-173.ec2.internal   Ready    <none>   7d      v1.20.11-eks-f17b81
ip-10-8-30-4.ec2.internal     Ready    <none>   5d19h   v1.20.11-eks-f17b81
ip-10-8-32-205.ec2.internal   Ready    <none>   6d      v1.20.11-eks-f17b81
ip-10-8-34-41.ec2.internal    Ready    <none>   22h     v1.20.11-eks-f17b81
ip-10-8-36-212.ec2.internal   Ready    <none>   5d19h   v1.20.11-eks-f17b81
ip-10-8-38-31.ec2.internal    Ready    <none>   5d18h   v1.20.11-eks-f17b81
ip-10-8-41-151.ec2.internal   Ready    <none>   6d      v1.20.11-eks-f17b81
```

**Comment by Skarlso** [comment]
Hello.

Can you please provide a sample cluster configuration or run command which reproduces this bug using `eksctl`? 

thanks!

**Comment by semoac** [comment]
Sure:

````
# eksctl create cluster -f cluster-eksctl-issue.yaml

# cat cluster-eksctl-issue.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksctl-issue
  region: us-east-1
  version: "1.20"

vpc:
  subnets:
    public:
      us-east-1a: { id: subnet-XXX }
      us-east-1b: { id: subnet-XXX }
      us-east-1c: { id: subnet-XXX }
    private:
      us-east-1a: { id: subnet-XXX }
      us-east-1b: { id: subnet-XXX}
      us-east-1c: { id: subnet-XXX }

nodeGroups:
  - name: infrastructure
    instanceType: m5a.xlarge
    minSize: 2
    maxSize: 5
    desiredCapacity: 3
    amiFamily: AmazonLinux2
    ami: auto-ssm
    containerRuntime: containerd
    volumeSize: 100
    volumeType: gp3
    volumeEncrypted: true
    privateNetworking: true
    labels:
      environment: prod
      dedicated: infrastructure
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        ebs: true
```
