### ISSUE TITLE
[Feature] EKSCTL should be able to detect changes on cluster.yml, and act accordingly

### ISSUE THREAD

**Issue by dbgoytia** [weaveworks/eksctl#5226]
### What feature/behavior/change do you want?
I would expect that EKSCTL would be able to detect changes on cluster.yml and create the change according to whatever is there.

### Why do you want this feature?
I think it's problematic that eksctl isn't able to detect changes in the configuration files and act upon it, specially when wanting to run the tool within ci systems.

**Comment by Skarlso** [comment]
Hi.

This needs a bit of explanation. :) What do you mean by "detect"? `eksctl` is a cli which exists after it's done. It doesn't monitor anything. It's not terraform, so it doesn't use apply functionality to detect drift between config and infrastructure. You can use `update` or `upgrade` or `create` with changes in the config and it will try to create/update the changed resource.

Or do you mean something else? :)

**Comment by dbgoytia** [comment]
I feel that that creation/update of features feels a bit incomplete. For example, recently I've tried adding new addons to a cluster.yml file, going from this:

```
addons:
  - name: vpc-cni
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
```

To this:

```
 addons:
  - name: vpc-cni
    tags:
      team: infraeng-compute-platforms
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
  - name: aws-ebs-csi-driver
    tags:
      team: infraeng-compute-platforms 
    wellKnownPolicies:
      ebsCSIController: true
      efsCSIController: true
```


Now, doing a "create" will tell me that the other addons already exist:
```
Error: creating CloudFormation stack "eksctl-<cluster>-addon-vpc-cni": AlreadyExistsException: Stack [eksctl-<cluster>-addon-vpc-cni] already exists
```

While doing an "update" will tell me that the new addon doesn't have any backing CloudFormation stack.

I really like the approach of EKSCTL of having a single cluster.yml configuration file for the entire cluster, however, it feels like doing these small changes outside of the cluster.yml feels like going back to doing manual updates.
