### ISSUE TITLE
[Bug] EKSCTL Write-Kubeconfig fails with Kubectl 1.24 with default aws-iam-authenticator due to v1alpha1 deprecation

### ISSUE THREAD

**Issue by sarasensible** [weaveworks/eksctl#5240]
### What were you trying to accomplish?
Trying to write a working kubeconfig with eksctl utils write-config on the ubuntu-latest Github hosted runner

### What happened?
Got the following error:
```
error: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"
```

### How to reproduce it?
Use the recently released kubectl 1.24 with the most recent eksctl release v0.96.0 and try writing a kubeconfig file for use in a Github Action

```
- name: EKSCTL Get Kubeconfig
  run: eksctl utils write-kubeconfig --cluster=${{ env.CLUSTER_NAME }}
```

**Logs**
N/A

**Anything else we need to know?**
This is related to the same issue that caused https://github.com/aws/aws-cli/issues/6920 

**Versions**

```
$ eksctl info

eksctl version: 0.96.0
kubectl version: v1.24.0
OS: linux
```

**Workaround**
I installed the most recent version of aws-iam-authenticator to get the toggle to v1beta1.  

```
- name: Install AWS IAM Authenticator upgraded version
  run: |
        sudo wget -q -O - https://api.github.com/repos/kubernetes-sigs/aws-iam-authenticator/releases \
            | jq --raw-output 'map( select(.prerelease==false) | .assets[].browser_download_url ) | .[]' \
            | grep inux \
            | head -n 1 \
            | wget -q --show-progress -i - -O /usr/local/bin/aws-iam-authenticator; \
            chmod a+x /usr/local/bin/aws-iam-authenticator
```
Then `eksctl utils write-kubeconfig` worked as expected.

Question:  Is aws-iam-authenticator bundled in eksctl?  If so, it seems that this dependency needs to be upgraded.  This [issue](https://github.com/weaveworks/eksctl/issues/4031) was helpful in understanding that the root cause is the aws-iam-authenticator version.

**Comment by cPu1** [comment]
>Question: Is aws-iam-authenticator bundled in eksctl? If so, it seems that this dependency needs to be upgraded. 

eksctl does not bundle any tool dependencies, you need to download it separately. It's documented in the **[README](https://github.com/weaveworks/eksctl/blob/main/README.md#aws-account).**

**Comment by sarasensible** [comment]
Ok, so it sounds like the workaround is actually the recommended approach to resolving this issue.  Thanks for the clarification @cPu1 !

**Comment by jglick** [comment]
After encountering this error, I deleted `aws-iam-authenticator` as suggested [here](https://docs.aws.amazon.com/eks/latest/userguide/install-aws-iam-authenticator.html) and now `eksctl utils write-kubeconfig` (0.97.0) writes out a `user` running `aws eks get-token`…but still using `client.authentication.k8s.io/v1alpha1`, so broken with `kubectl` 1.24.0. Whereas `aws eks update-kubeconfig` (2.6.4, as in https://github.com/aws/aws-cli/issues/6920#issuecomment-1121390562) writes out a config with `client.authentication.k8s.io/v1beta1` which works. Am I missing something?

**Comment by Skarlso** [comment]
Why did you delete aws-iam-authenticator? Sorry, the link guide doesn't include deleting it. You just need to have an aws-iam-authenticator that is above 0.5.3. :)

**Comment by jglick** [comment]
> If you're running the AWS CLI version 1.16.156 or later, then you don't need to install the authenticator. Instead, you can use the [aws eks get-token](https://docs.aws.amazon.com/cli/latest/reference/eks/get-token.html) command.

**Comment by Skarlso** [comment]
@jglick Ah I see! We default to alpha and we only overwrite it in case of aws-iam-authenticator.

Would you mind please creating a different ticket with the details saying that you are using `aws eks get-token`? Thanks.

**Comment by Skarlso** [comment]
Please also put a link in there to this code https://github.com/weaveworks/eksctl/blob/main/pkg/utils/kubeconfig/kubeconfig.go#L161 :) Thanks

**Comment by autarchprinceps** [comment]
aws iam authenticator is unneccessary in modern EKS login. The aws cli can be used directly now. That is also what aws eks update-kubeconfig generates. This is an issue, because it directly fails inside the eksctl create command, because when eksctl then calls kubectl itself, for example to install addons.
```
2022-05-17 11:45:44 [ℹ]  creating addon
2022-05-17 11:48:15 [ℹ]  addon "aws-ebs-csi-driver" active
2022-05-17 11:48:15 [✖]  parsing kubectl version string  (upstream error: error: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"
) / "0.0.0": Version string empty
```
```yaml
- name: arn:aws:eks:eu-central-1:accid:cluster/dev-mgmt
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - eu-central-1
      - eks
      - get-token
      - --cluster-name
      - dev-mgmt
      command: aws
```
vs
```yaml
- name: email@dev-mgmt.eu-central-1.eksctl.io
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - dev-mgmt
      command: aws-iam-authenticator
      env:
      - name: AWS_STS_REGIONAL_ENDPOINTS
        value: regional
      - name: AWS_DEFAULT_REGION
        value: eu-central-1
      provideClusterInfo: false
```
