### ISSUE TITLE
[Bug] managedNodeGroups: doesn't support taints? 

### ISSUE THREAD

**Issue by bitva77** [weaveworks/eksctl#5246]
Have to imagine this is a bug?  In my `ClusterConfig`:

```
managedNodeGroups:
  - name: azdo-buildagents-2xlarge-v2
    labels:
      workload: azdo-buildagents-2xlarge
      environment: preprod
    taints:
      key: "azdobuild-2xlarge:NoSchedule"
    propagateASGTags: true
    minSize: 0
```

`eksctl create nodegroup -f ./cluster-config.yaml`

```
Error: couldn't create node group filter from command line options: loading config file "./cluster-config.yaml": error unmarshaling JSON: while decoding JSON: json: cannot unmarshal object into Go struct field ManagedNodeGroup.managedNodeGroups.taints of type []v1alpha5.NodeGroupTaint
```

If I remove the `key:` line, it seems to work with nothing defined under `taints:`.

```
eksctl version
0.96.0
```

**Comment by cPu1** [comment]
```yaml
    taints:
      key: "azdobuild-2xlarge:NoSchedule"
```

That is not the correct syntax for defining taints for a managed nodegroup. The `taints` field takes an array of `Taint` objects with the shape `{key, value, effect}`, but you have passed an object. The correct syntax is:


```yaml
    taints:
    - key: "key"
      value: azdobuild-2xlarge
      effect: NoSchedule
```
