### ISSUE TITLE
[Bug] r6g instances stopped working with eksctl 0.96.0

### ISSUE THREAD

**Issue by Legion2** [weaveworks/eksctl#5247]
### What were you trying to accomplish?
We want to use r6g instances for databases.

### What happened?
We updated to eksctl 0.96.0 and now we get the following error:
`Error: ARM GPU instance types are not supported for unmanaged nodegroups with AMIFamily `

### How to reproduce it?
1. create a cluster.yaml file which defines your cluster
2. add a (unmanaged) nodegroup with `r6g.xlarge` instanceType
3. call eksctl with the `-f cluster.yaml` option
4. the error is shown

**Anything else we need to know?**
It worked with eksctl 0.95.0

**Versions**

```
$ eksctl info
eksctl version: 0.96.0
kubectl version: v1.23.6
OS: linux
```
@Skarlso

**Comment by Skarlso** [comment]
Thanks!

**Comment by Himangini** [comment]
Fixed by https://github.com/weaveworks/eksctl/pull/5293

**Comment by lexagigabit** [comment]
Not sure if this is the proper way to report the issue I have, but exactly the same issue still exists in 0.99.0
Tried with the unmanaged node groups and following instance types: `c6gd.large`, `r6gd.medium`
```
$ eksctl info
eksctl version: 0.99.0
kubectl version: v1.24.0
OS: linux
```

```
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: ****
  region: us-east-2
  version: "1.21"
 nodeGroups:
  - name: *****
    minSize: 1
    maxSize: 2
    labels: { role: worker }
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/****: "owned"
    desiredCapacity: 1
    volumeSize: 16
    volumeType: gp2
    amiFamily: AmazonLinux2
    instancesDistribution:      
      instanceTypes: [ "r6gd.medium" ]
    ssh:
      publicKeyName: ****
```

```
$ eksctl create cluster -f eksclusterdops.yaml 
Error: ARM GPU instance types are not supported for unmanaged nodegroups with AMIFamily AmazonLinux2    
```
