### ISSUE TITLE
[Bug] I should be able to create Windows and Ubuntu nodegroups with GPU instances (revert #4243)

### ISSUE THREAD

**Issue by doctorpangloss** [weaveworks/eksctl#5256]
### What were you trying to accomplish?
Create a Windows node group on an NVIDIA GPU instance

### What happened?
I receive an error from the code that prevents me from doing that in `eksctl`. The error appears in https://github.com/cPu1/eksctl/blob/4bcff91151570a1a15a2a0d8d07ae33799500380/pkg/apis/eksctl.io/v1alpha5/validation.go#L286

### How to reproduce it?
```yaml
...
nodeGroups:
  - name: xxx
    instanceType: g5.xlarge
    amiFamily: WindowsServer20H2CoreContainer
```
```sh
eksctl create cluster -f config.yaml
```
**Logs**

```
Error: couldn't create cluster provider from options: NVIDIA GPU instance types are not supported for WindowsServer20H2CoreContainer
```
**Anything else we need to know?**

I provision the nodes the rest of the way to GPU support.

**Versions**

```
$ eksctl info
eksctl version: 0.97.0
kubectl version: v1.22.5
OS: windows
```
