### ISSUE TITLE
current-context in ~/.kube/config not cleaned up

### ISSUE THREAD

**Issue by Jeffwan** [weaveworks/eksctl#527]
**What happened?**
After I delete the cluster, current-context still have the old context `username@cluster-name.us-west-2.eksctl.io` which has not been cleaned up. 

```
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://localhost:6443
  name: docker-desktop
contexts:
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-desktop
current-context: username@cluster-name.us-west-2.eksctl.io
kind: Config
preferences: {}
users:
- name: docker-desktop
  user:

```

if there's only one cluster, result as follow

```
apiVersion: v1
clusters: []
contexts: []
current-context: username@cluster-name.us-west-2.eksctl.io
kind: Config
preferences: {}
users: []

```

**What you expected to happen?**
I expect the cluster context resume to the valid one.

**How to reproduce it?**
create cluster and delete cluster. 

**Anything else we need to know?**

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.1.19"}
$ uname -a
MacOS
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", 
```
Also include your version of `heptio-authenticator-aws`

**Logs**
Include the output of the command line when running eksctl. If possible, eksctl should be run with debug logs. For example:
`eksctl get clusters -v 4`
Make sure you redact any sensitive information before posting.
If the output is long, please consider a Gist.
