### ISSUE TITLE
[Bug] EKS is not integrated with OIDC Provider, but it's doing Get OpenID call 

### ISSUE THREAD

**Issue by shyam-ks** [weaveworks/eksctl#5289]
EKS is not integrated with OIDC Provider, but it's doing Get OpenID call because of which the deletion is failing. The main issue is this role is blocked by the IT team

```
eksctl version 0.97.0
using region us-east-1
deleting EKS cluster "test"
will drain 0 unmanaged nodegroup(s) in cluster "test"
deleted 0 Fargate profile(s)
kubeconfig has been updated
cleaning up AWS load balancers created by Kubernetes objects of Kind Service or Ingress
Error: operation error IAM: GetOpenIDConnectProvider, https response error StatusCode: 403, RequestID: e08bc362-77c7-4aba-a5cb-9e888885b484, api error AccessDenied: User: arn:aws:sts::485443633092:assumed-role/EksctlRole-BCGSSRVAC970/AWSCodeBuild-670ebbbbbbbbbb3d-7a3ba6ee3300 is not authorized to perform: iam:GetOpenIDConnectProvider on resource: arn:aws:iam::00000000:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/4FC3F00000797DAEAF1103D8027 with an explicit deny in a permissions boundary
````

**Comment by Skarlso** [comment]
Thanks for reporting this. Can you please link the config file and the delete command used to try and delete the cluster? thanks!

**Comment by shyam-ks** [comment]
> Thanks for reporting this. Can you please link the config file and the delete command used to try and delete the cluster? thanks!
Config file
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: "${CLUSTER_NAME}"
  region: "${REGION}"
  version: "${VERSION}"
  tags:
    env: "${TARGETENV}"
    role: "${ROLE}"
    uai: "${UAI}"

vpc:
  id: "${VPC_ID}"
  # Addional security group that lets bastion host to connect to EKS control pane private endpoint
  securityGroup: "${CONTROL_PLANE_ADDITIONAL_SG}" 
  subnets:
    private:
      us-east-1a:
        id: "${SUBNET_1}"    
      us-east-1b:
        id: "${SUBNET_2}"
  clusterEndpoints:
    privateAccess: true
    publicAccess: false

cloudWatch:
  clusterLogging:
    enableTypes: ["*"] 

managedNodeGroups:
  - name: "ng-1-workers-${NODEGROUP_NAME}"
    instanceType: "${INSTANCE_TYPE_NG1}"
    desiredCapacity: ${DESIRED_CAPACITY_NG1}    
    ssh:
       publicKeyName: eks-dev
    labels: { role: workers }
    tags:
      env: ${TARGETENV}
      Environment: ${K8S_ENV}
      role: ${ROLE}
      uai: ${UAI}
      nodegroup-role: worker
      instance-type: onDemand
      ssmmanaged: "yes"
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly

      withAddonPolicies:
        autoScaler: true
        imageBuilder: true
        externalDNS: true
        certManager: true
        appMesh: true
        ebs: true
        albIngress: true
        efs: true
        cloudWatch: true
    privateNetworking: true
    volumeSize: 200
    securityGroups:
      attachIDs: ${NODEGROUP_SG}
    ami: ${EKS_NG_AMI}
    overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh ${CLUSTER_NAME}  
```
