### ISSUE TITLE
[Feature] Improvements to the additionalVolumes section and documentation

### ISSUE THREAD

**Issue by pptb-aws** [weaveworks/eksctl#5320]
### What feature/behavior/change do you want?

I would like an option in the [additionalVolumes section](https://eksctl.io/usage/nodegroup-additional-volume-mappings/) that allows for the directory to be named and mounted automatically.  Something like this,

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dev-cluster
  region: eu-north-1

managedNodeGroups:
  - name: ng-1-workers
    labels: { role: workers }
    instanceType: m5.xlarge
    desiredCapacity: 10
    volumeSize: 80
    additionalVolumes:
      - volumeName: '/tmp/mount-1' # required
        volumeSize: 80
        volumeType: 'gp3'
        volumeEncrypted: true
        volumeKmsKeyID: 'id'
        volumeIOPS: 3000
        volumeThroughput: 125
        directoryPath: /data
      - volumeName: '/tmp/mount-2'  # required
        volumeSize: 80
        volumeType: 'gp2'
        snapshotID: 'snapshot-id'
        directoryPath: /tmp/scratch
```

If the above is not viable to implement, then I believe a summary of the solution [provide here](https://github.com/weaveworks/eksctl/issues/1253#issuecomment-1088240572) would be beneficial to users reading the additionalVolumes documentation.

I also think more clarification regarding volumeName would be helpful.  Perhaps a link to [this documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/device_naming.html) regarding device naming with the text, "For details about selecting volumeNames, see the [device naming documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/device_naming.html)."

### Why do you want this feature?

When using the [additionalVolumes section](https://eksctl.io/usage/nodegroup-additional-volume-mappings/) I was able to successfully add another EBS volume, but it did not start mounted.  I also did not initially understand what the volumeName section was until I reviewed the CloudFormation template.  The above requests are intended to improve the user experience when using the additionalVolumes option.
