### ISSUE TITLE
Ability to specify particular, AWS provided AMI without "overrideBootstrapCommand" option

### ISSUE THREAD

**Issue by przemolb** [weaveworks/eksctl#5387]
### What feature/behavior/change do you want?

We would like to be able to use the following config with specific AWS-provided AMI:
```
managedNodeGroups:
  - name: managed-1
      amiFamily: AmazonLinux2
      ami: ami-[original, provided by AWS]
    ...
    ssh:
      allow: true
      enableSsm: true
    ...
```

in the following scenario:
1. we want to use SSM (`ssh.enableSsm: true`)
2. AWS has released new AMI called i.e.: `ami-1`
3. we upgraded workers in our **test cluster** `eks-1` to the `ami-1`
4. [ 2 weeks later (planning/scheduling/executing) ]
5. we upgraded workers in our **test cluster** `eks-2` to the `ami-1`
6. [ 2 weeks later (planning/scheduling/executing) ]
7. AWS has released new AMI called i.e.: `ami-2`
8. [ 2 weeks later (planning/scheduling/executing) ]
9. we would like to upgrade our **production cluster** `eks-3` to `ami-1` (as it has been tested on our test clusters) but we cannot as without specific AMIs `eksctl` will pick the latest available `ami` which is `ami-2`

### Why do you want this feature?
To be able to use the same specific, tested AMIs in long-lasting infrastructure upgrade process.

**Comment by Skarlso** [comment]
Thanks for the issue. As a reference, here is the slack discussion this out from:

https://weave-community.slack.com/archives/CAYBZBWGL/p1654698774086689

**Comment by cPu1** [comment]
@przemolb, this use-case is covered by the `managedNodeGroup.releaseVersion` field, which instructs eksctl to use the specified AMI release version for the nodes. More details on the available versions can be found on [Amazon EKS optimized Amazon Linux AMI versions](https://docs.aws.amazon.com/eks/latest/userguide/eks-linux-ami-versions.html).

**Comment by przemolb** [comment]
@cPu1 
from what I've been told it looks like one cannot use both `enableSsm: true` _and_ specify AMI version in the `eksctl` YAML file.
If this is not true - can you please show me working example of the YAML file which includes both `enableSsm: true` and `managedNodeGroup.releaseVersion` ?

**Comment by cPu1** [comment]
> @cPu1 from what I've been told it looks like one cannot use both `enableSsm: true` _and_ specify AMI version in the `eksctl` YAML file. If this is not true - can you please show me working example of the YAML file which includes both `enableSsm: true` and `managedNodeGroup.releaseVersion` ?

You cannot specify a custom AMI (`ami` field) with `enableSsm` but you can specify a `releaseVersion`. The release version is not the same as an AMI ID. It has the format `k8s_major_version.k8s_minor_version.k8s_patch_version-release_date`. Here's an example config:

```yaml
managedNodeGroups:
  - name: managed-1
    amiFamily: AmazonLinux2
    releaseVersion: "1.22.9-20220725"
    ssh:
      allow: true
      enableSsm: true
```
