### ISSUE TITLE
Example incorrect on how to apply taint to a nodegroup

### ISSUE THREAD

**Issue by cristian-popa** [weaveworks/eksctl#5388]
### What were you trying to accomplish?

Apply taint to a node group

### What happened?

Using the example in the docs here https://eksctl.io/usage/autoscaling/  I get the following error:

```Error: loading config file "not-working-taints.yaml": error unmarshaling JSON: while decoding JSON: json: cannot unmarshal object into Go struct field ManagedNodeGroup.managedNodeGroups.taints of type []v1alpha5.NodeGroupTaint```

### How to reproduce it?

This does not work: 
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-poc
  region: us-east-1

vpc:
  id: vpc-0500965e9cb575cad
  subnets:
    private:
      us-east-1a: { id: subnet-02e979eaf467ae337 }
      us-east-1b: { id: subnet-0e362ef23954ea949 }
      us-east-1c: { id: subnet-0c1d4805e1c15fe6d }
    

managedNodeGroups:
  - name: my-nodes
    labels: { role: workers , nodetype: master}
    propagateASGTags: true
    instanceType: m5.large
    desiredCapacity: 3
    privateNetworking: true
    ssh:
      allow: true
      publicKeyName: my-key
    iam: 
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
        - arn:aws:iam::123456789012:policy/my-s3-policy

    taints:
      feaster: "true:NoSchedule" 
        
```

This taints stanza works. It did distract me for 1 hour, may be worth adjusting the docs here to save time and frustrations for others: https://eksctl.io/usage/autoscaling/ 
```
    taints:
      - key: master
        value: "true"
        effect: NoSchedule
```

**Logs**

**Anything else we need to know?**

MacOS, Monterey 12.4 Chip M1 pro. 
eksctl installed via brew 
**Versions**

```
eksctl info
eksctl version: 0.100.0
kubectl version: v1.24.1
OS: darwin

```

**Comment by Skarlso** [comment]
Hey @cristian-popa.

Nice spot, thanks for the issue! :)

**Comment by cPu1** [comment]
@cristian-popa, the taints example shown [here](https://eksctl.io/usage/autoscaling/) is for unmanaged nodegroups, which support both forms of syntax. The correct syntax for managed nodegroups is

```yaml
taints:
- key: master
  value: "true"
  effect: NoSchedule
```

You're right to point out that it can be confusing because that syntax works only for unmanaged nodegroups. We'll update the example with the aforementioned syntax that works for both managed and unmanaged nodegroups.
