### ISSUE TITLE
[Bug] timed out waiting for at least 3 nodes to join the cluster and become ready

### ISSUE THREAD

**Issue by viktorgoranov** [weaveworks/eksctl#5398]
### What happened?
When creating a new cluster, nodes fail to join the cluster. eksctl times out waiting for nodes after 25minutes.

### What you expected to happen?
A cluster stood up and ready.

### How to reproduce it?
Create new aws account, create iam with admin access and api credentials.
export aws credentials with envvars (aws_access_key... etc).
run following command:

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name:  cluster-name
  region: eu-central-1
  version: "1.21"

vpc:
  id: 
  publicAccessCIDRs: 
  clusterEndpoints:
    publicAccess:  true
    privateAccess: true
  subnets:
    private:
      eu-central-1a:
        id: 
      eu-central-1b:
        id: 
      eu-central-1c:
        id: 
    public:
      eu-central-1a:
        id: 
      eu-central-1b:
        id: 
      eu-central-1c:
        id: 
iam:
  withOIDC: true

nodeGroups:
  - name: 
    ami:
    overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh cluster-name --container-runtime containerd
    instanceType: c5.large
    desiredCapacity: 3
    labels:
      nodegroup-type: nodes
    privateNetworking: true
    availabilityZones: ["eu-central-1a", "eu-central-1b", "eu-central-1c"]
    ssh:
      publicKeyName:
```

### Versions
eksctl version - 0.99

### Logs
 waiting for at least 3 node(s) to become ready in "node-group"
16:12:31  Error: timed out waiting for at least 3 nodes to join the cluster and become ready in "node-group": context deadline exceeded
[Pipeline] }

### Comments
Already tried with removing publicAccessCIDRs:, but i received the same error (also with setup 0.0.0.0/0). Also tried outside from the pipeline and the result was the same. Any ideas?

_edit GB_: fixed formatting
