### ISSUE TITLE
[Help] Node group deletion - Cannot delete entity, must detach all policies first

### ISSUE THREAD

**Issue by shyam-ks** [weaveworks/eksctl#5430]
In our cloud, a policy gets automatically attached to the node group IAM role. its part of Infra security automation. Because it's not part of eksctl creation, while  deleting the node group, it fails due the stack deletion policy 

```
Cannot delete entity, must detach all policies first. (Service: AmazonIdentityManagement; Status Code: 409; Error Code: DeleteConflict; Request ID: ffbfaa5c-a0c3-4ebc-8392-ea1ad29e432e; Proxy: null)
```
Is there a way to force delete this role during node group deletion using eksctl even if there are additional policies attached to it?

![image](https://user-images.githubusercontent.com/88625905/173857997-4ee00cf8-236f-44dc-a1d8-08d5430b917d.png)

**Comment by cPu1** [comment]
eksctl does not support force-deleting a nodegroup's IAM role if it had policies attached outside of eksctl. The recommended way is to use `nodeGroup.iam.attachPolicyARNs` to specify custom policies. Please note that when you use `attachPolicyARNs`, eksctl does not add the default node policies, so you'll have to specify them also, as in:

```yaml
nodeGroups:
  - name: test
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - <custom-policy>
```
