### ISSUE TITLE
authconfigmap: shared roles and duplication

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#544]
Currently, it's possible to create an NG that borrows an IAM role from another NG. This effectively results in duplicated entries. #528 doesn't deal with this, but we should devise a method for that soon enough.

**Comment by errordeveloper** [comment]
Our roles are named as `arn:aws:iam::<account>:role/eksctl-<cluster>-nodegroup-<ng>-NodeInstanceRole-<prefix>`, so we can detect it and only cleanup roles that match the nodegroup in question, but this would still remove roles for other nodegroups.

I am not sure what `mapRoles` API currently allows us to store, perhaps there are useful fields that we can add... but actually, we should be able to add another top-level field in the configmap.

E.g. something like this:

```
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-syste
data:
  mapRoles: |
    - username: 'system:node:{{EC2PrivateDNSName}}'
      groups: [ 'system:bootstrappers', 'system:nodes' ]
      rolearn: 'arn:aws:iam::122333:role/eksctl-cluster-5a-nodegroup-ng1-p-NodeInstanceRole-NNH3ISP12CX'
   eksctlInfo: |
      - rolearn: 'arn:aws:iam::122333:role/eksctl-cluster-5a-nodegroup-ng1-p-NodeInstanceRole-NNH3ISP12CX'
        owned: true
        cluster: cluster-5a
        nodegroups: ['ng1-public']
```
