### ISSUE TITLE
Removing used images from a instance/node.

### ISSUE THREAD

**Issue by yuvansh33** [weaveworks/eksctl#5445]
We need to automate a way via which we can remove the used images from our instance to clear some space for newer images.
i found a way using `kubelet.conifg` file , but i think it will not make any change in existing nodegroup. we used to manually delte the images by ssh in instance and using `docker prune image` command. It'll be good to have an automated system to do so.
please suggest us if there is any other way for deleting used images from our cluster. 
im attaching the kubelte config file i found on internet if it could help --

```
`apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dev-mmc-2022
  region: us-east-2

nodeGroups:
  - name: mng-t3-mi
    instanceType: t3.micro
    desiredCapacity: 1
    kubeletExtraConfig:
        kubeReserved:
            cpu: "300m"
            memory: "300Mi"
            ephemeral-storage: "1Gi"
        #kubeReservedCgroup: "/kube-reserved"
        systemReserved:
            cpu: "300m"
            memory: "300Mi"
        imageMinimumGCAge: "2m0s"
        imageGCHighThresholdPercent": 85
        imageGCLowThresholdPercent": 80`
```
