### ISSUE TITLE
eksctl without IAM:CreateRole permissions

### ISSUE THREAD

**Issue by ecpullen** [weaveworks/eksctl#5452]
### Discussed in https://github.com/weaveworks/eksctl/discussions/5423

<div type='discussions-op-text'>

<sup>Originally posted by **ecpullen** June 14, 2022</sup>
I am trying to setup eksctl for cluster creation using existing service roles and instance profiles.
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name:  eksctl-test
  region: us-west-2

iam:
  serviceRoleArn: arn:aws:iam::***************:role/*********************
```
Whenever I use `eksctl create cluster` it errors with.
```
AWS::IAM::Role/ServiceRole: CREATE_FAILED – "API: iam:CreateRole User: arn:aws:sts::*********:assumed-role/********** is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::*********:role/eksctl-<cluster_name>-cluster-ServiceRole-10FMX3LU9UVU because no identity-based policy allows the iam:CreateRole action"
```
Is it possible to use eksctl without creating a role?</div>
