### ISSUE TITLE
[Bug] ReadString: expects " or n, but found 1, error found in #10

### ISSUE THREAD

**Issue by johnfelipe** [weaveworks/eksctl#5556]
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: xrengineprod
  region: cn-northwest-1
  version: 1.22

nodeGroups:
  - name: ng-1
    instanceType: t3.small
    desiredCapacity: 1
    volumeSize: 30
    # ssh:
      # allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key

managedNodeGroups:
  - name: mng-1
    desiredCapacity: 1
    instanceType: t3.small
    minSize: 1
    maxSize: 3
    
availabilityZones:
- cn-northwest-1c
- cn-northwest-1b
- cn-northwest-1a
```
and show me this

```
root@felipe:~# eksctl create cluster -f cluster.yaml
Error: loading config file "cluster.yaml": v1alpha5.ClusterConfig.Metadata: v1alpha5.ClusterMeta.Version: ReadString: expects " or n, but found 1, error found in #10 byte of ...|version":1.22},"node|..., bigger context ...|rengineprod","region":"cn-northwest-1","version":1.22},"nodeGroups":[{"desiredCapacity":1,"instanceT|...
```

how solve this issue?
