### ISSUE TITLE
[Help] readiness and liveness HttpGet not work

### ISSUE THREAD

**Issue by GDdark** [weaveworks/eksctl#5616]
Readiness config in deployment.yaml:
![AFw4pjmv2M](https://user-images.githubusercontent.com/15982894/184596030-5dabe541-a942-4894-85bf-0c05d977bbf4.jpg)

After applying and I get an error:
![mk8o9ZnNQ7](https://user-images.githubusercontent.com/15982894/184596411-0aeccf2e-acd3-40eb-810b-e5c5e4c3df5f.jpg)

But I access my node and try to curl the URL, and it works:
![image](https://user-images.githubusercontent.com/15982894/184596645-020527c1-9390-40ee-8cdf-a8d0862c3b99.png)

The problem also happens with the liveness.

**Version info:**

eksctl version -o json
```
{"Version":"0.107.0","PreReleaseID":"","Metadata":{"BuildDate":"2022-07-29T08:53:19Z","GitCommit":"b204c3c"},"EKSServerSupportedVersions":["1.19","1.20","1.21","1.22"]}
```

kubectl version -o yaml
```
clientVersion:
  buildDate: "2022-07-13T14:21:56Z"
  compiler: gc
  gitCommit: aef86a93758dc3cb2c658dd9657ab4ad4afc21cb
  gitTreeState: clean
  gitVersion: v1.24.3
  goVersion: go1.18.4
  major: "1"
  minor: "24"
  platform: darwin/amd64
kustomizeVersion: v4.5.4
serverVersion:
  buildDate: "2022-07-06T18:06:23Z"
  compiler: gc
  gitCommit: b9628d6d3867ffd84c704af0befd31c7451cdc37
  gitTreeState: clean
  gitVersion: v1.22.11-eks-18ef993
  goVersion: go1.16.15
  major: "1"
  minor: 22+
  platform: linux/amd64
```

How can I fix this problem?
