### ISSUE TITLE
[Bug] template validation failed when nodegroup maxSize defaults to 0, as minimum required is 1

### ISSUE THREAD

**Issue by wvh** [weaveworks/eksctl#5664]
Hello!

I was trying to create a cluster with two managed node groups. One node group failed template validation because `maxSize` was set to `0` while the minimum seems to be `1`.

This is the node group configuration:

```
- name: large-workers
  labels:
    role: web
    nodegroup: large
  desiredCapacity: 0
  minSize: 0
  instanceSelector:
    memory: "8"
    vCPUs: 4
  privateNetworking: true
```
This generates a template that has `minSize` set to `0` and `maxSize` set to 0. However, `/ManagedNodeGroup/ScalingConfig/MaxSize` needs to be at least 1 (minimum constraint) or cloudformation fails to validate the template. See the details below:

![image](https://user-images.githubusercontent.com/110664232/189852841-f6ba1eb8-b548-40fa-8de0-8c1037a5623b.png)

<img width="965" alt="image" src="https://user-images.githubusercontent.com/110664232/189852475-29716aa1-67a0-4750-9781-149407609475.png">

Manually setting `maxSize` to a large number, e.g. `10`, fixes the issue.

```
eksctl version: 0.108.0-dev
kubectl version: v1.24.4
OS: linux
```
