### ISSUE TITLE
[Bug] EC2 not added to EKS

### ISSUE THREAD

**Issue by maxinfosoft** [weaveworks/eksctl#5665]
I have successfully created a cluster in AWS with this command/file:

eksctl create cluster -f mycluster.yaml

```yaml
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-cluster
  region: eu-central-1
  version: "1.23"

nodeGroups:
  - name: ng-my
    instanceType: t3.xlarge
    desiredCapacity: 3
    minSize: 2
    maxSize: 5
    tags:
      'Name': 'my-cluster'

cloudWatch:
    clusterLogging:
        enableTypes: ["audit", "authenticator", "controllerManager"]

```

ec2 was successfully created, but they were not added to the EKS cluster, so I get this message after the command
kubectl get nodes:
No resources found

Earlier with previous versions of eksctl (before 1.13) and kubernetes 1.21 there was no problem and ec2 was always added to EKS, but with version eksctl 1.15 this problem appeared.
