### ISSUE TITLE
[Bug] Error while creating nodegroup for with Bottlerocket ARM + GPU instances

### ISSUE THREAD

**Issue by arnaldo2792** [weaveworks/eksctl#5728]
### What were you trying to accomplish?
I tried to create a new unmanaged Bottlerocket node group in an existing cluster with ARM + GPU instances

### What happened?
I got an error:

```
eksctl create nodegroup --config-file=<my-file>.yaml

Error: could not create cluster provider from options: ARM GPU instance types are not supported for unmanaged nodegroups with AMIFamily Bottlerocket
```

### How to reproduce it?
Run:

```bash
eskctl create node-group --config-file=test.yaml
```

Where `test.yaml` is:

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-name
  region: us-west-2
  version: '1.22'

nodeGroups:
  - name: test-nvidia-arm
    instanceType: g5g.2xlarge
    desiredCapacity: 1
    amiFamily: Bottlerocket
    iam:
       attachPolicyARNs:
          - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
          - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
          - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
          - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
    ssh:
        allow: true
        publicKeyName: EC2Instance
    bottlerocket:
      settings:
        motd: "Hello from eksctl!"
        host-containers:
          admin:
            enabled: true
```

**Logs**

```
Error: could not create cluster provider from options: ARM GPU instance types are not supported for unmanaged nodegroups with AMIFamily Bottlerocket
```

**Anything else we need to know?**

* What OS are you using? fedora 36
* Are you using a downloaded binary or did you compile eksctl? downloaded binary
* What type of AWS credentials are you using (i.e. default/named profile, MFA)? An instance profile

**Versions**
```
❯ eksctl info
eksctl version: 0.112.0
kubectl version: v1.20.4-eks-6b7464
OS: linux

```
