### ISSUE TITLE
[Help] Cluster creation timeout in eu-central-1

### ISSUE THREAD

**Issue by virenrshah** [weaveworks/eksctl#5737]
eksctl version                                                                                                                                                                                                  
0.110.0-dev+b6664f852.2022-09-02T06:07:17Z

I am trying to create a cluster in eu-central-1. I have used essentially the same cluster config file for us-east regions and they have worked. Any thoughts on what might be happening? Looks like the nodes cannot join the cluster. I have tried by explicitly specifying the iam policies, using an existing VPC, etc. All result in the same timeout.

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: prod-eu-1
  region: eu-central-1
  version: "1.23"

iam:
  withOIDC: true

addons:
- name: vpc-cni
- name: aws-ebs-csi-driver


managedNodeGroups:
- name: dmz-spot
  instanceTypes: ["m5.large","m6a.large","m5a.large","r4.large","t3a.large"]
  spot: true
  amiFamily: AmazonLinux2
  labels: 
    env: dmz.spot
    ntype: spot
  tags:
    PatchGroup: cis
  minSize: 2
  maxSize: 5
  desiredCapacity: 3
  volumeSize: 52
  volumeEncrypted: true
  ssh:
    allow: true
    publicKeyPath: ~/.ssh/prod-eu1.pub
  privateNetworking: true

- name: main-ondemand
  instanceTypes: ["m5a.4xlarge","m6a.4xlarge", "m5.xlarge","t3a.xlarge"]
  spot: false
  amiFamily: AmazonLinux2
  labels: 
    env: private.main
    ntype: ondemand
  tags:
    PatchGroup: cis
  desiredCapacity: 1
  minSize: 1
  maxSize: 6
  volumeSize: 92
  volumeEncrypted: true
  ssh:
    allow: true
    publicKeyPath: ~/.ssh/prod-eu1.pub
  privateNetworking: true
```

Nodegroup CloudFormation events show:
`Resource handler returned message: "[Issue(Code=NodeCreationFailure, Message=Instances failed to join the kubernetes cluster,`
