### ISSUE TITLE
Ubuntu managedNodeGroup creation failed

### ISSUE THREAD

**Issue by uchiha-pain** [weaveworks/eksctl#5739]
### What were you trying to accomplish?
I am trying create Ubuntu managed node in a cluster with no outbound access to the internet.

### What happened?
When I specify amiFamily with Ubuntu2004, it just fails to create the managed node group. As I am working behind the proxy I think I have to add UserData. For this purposes, when I specified overrideBootstrapCommand, I got the following error
`Error: could not create cluster provider from options: managedNodeGroups[0].overrideBootstrapCommand can only be set when a custom AMI (managedNodeGroups[0].ami) is specified`
And when I use custom ami then I get error
`Error: could not create cluster provider from options: cannot set amiFamily to Ubuntu2004 when using a custom AMI`
If I don't specify any of these flags then I end up getting AmazonLinux node instance.

### How to reproduce it?
Create a vpc (VPC_A)with internet access, create another VPC (VPC_B) with no internet access, peer them together. Then in the private subnet of the VPC_B, create a cluster with the following config.
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-cluster
  region: eu-west-2
  version: "1.23"

privateCluster:
  enabled: true

vpc:
  id: vpc-0cbbv4h64g74v5g56b52a
  subnets:
    private:
      hscn-private1-subnet:
        id: subnet-0bd030fs34fd5435e9f
      hscn-private2-subnet:
        id: subnet-092b2d5r43fdf43655f
```
It will successfully create a private cluster.
Then for managed node group use the following config.
```
managedNodeGroups:
  - name: serv-test-1
    amiFamily: Ubuntu2004
    instanceType: m5.xlarge
    desiredCapacity: 1
    volumeType: gp2
    volumeSize: 50
    privateNetworking: true
    subnets:
      - hscn-private2-subnet
    ssh:
      allow: true
```

**Logs**
Whenever I set amiFamily to Ubuntu I get the following logs.
```
2022-09-29 09:55:03 [ℹ]  nodegroup "serv-test-1" will use "ami-0ebb49de26355a371" [Ubuntu2004/1.23]
2022-09-29 09:55:03 [ℹ]  using SSH public key "/home/ubuntu/.ssh/id_rsa.pub" as "eksctl-test-cluster-nodegroup-serv-test-1-56:df:6f:6e:ca:62:a0:f8:7e:4b:18:35:e6:84:85:0a" 
2022-09-29 09:55:03 [ℹ]  1 nodegroup (serv-test-1) was included (based on the include/exclude rules)
2022-09-29 09:55:03 [ℹ]  will create a CloudFormation stack for each of 1 managed nodegroups in cluster "test-cluster"
2022-09-29 09:55:03 [ℹ]  
2 sequential tasks: { fix cluster compatibility, 1 task: { 1 task: { create managed nodegroup "serv-test-1" } } 
}
2022-09-29 09:55:03 [ℹ]  checking cluster stack for missing resources
2022-09-29 09:55:03 [ℹ]  cluster stack has all required resources
2022-09-29 09:55:04 [ℹ]  building managed nodegroup stack "eksctl-test-cluster-nodegroup-serv-test-1"
2022-09-29 09:55:04 [ℹ]  deploying stack "eksctl-test-cluster-nodegroup-serv-test-1"
2022-09-29 09:55:04 [ℹ]  waiting for CloudFormation stack "eksctl-test-cluster-nodegroup-serv-test-1"
2022-09-29 09:55:34 [ℹ]  waiting for CloudFormation stack "eksctl-test-cluster-nodegroup-serv-test-1"
2022-09-29 09:56:11 [ℹ]  waiting for CloudFormation stack "eksctl-test-cluster-nodegroup-serv-test-1"
2022-09-29 09:57:44 [ℹ]  waiting for CloudFormation stack "eksctl-test-cluster-nodegroup-serv-test-1"
2022-09-29 09:58:34 [ℹ]  waiting for CloudFormation stack "eksctl-test-cluster-nodegroup-serv-test-1"
2022-09-29 09:59:46 [ℹ]  waiting for CloudFormation stack "eksctl-test-cluster-nodegroup-serv-test-1"
2022-09-29 10:01:07 [ℹ]  waiting for CloudFormation stack "eksctl-test-cluster-nodegroup-serv-test-1"
2022-09-29 10:02:05 [ℹ]  waiting for CloudFormation stack "eksctl-test-cluster-nodegroup-serv-test-1"
2022-09-29 10:03:20 [ℹ]  waiting for CloudFormation stack "eksctl-test-cluster-nodegroup-serv-test-1"
2022-09-29 10:03:59 [ℹ]  waiting for CloudFormation stack "eksctl-test-cluster-nodegroup-serv-test-1"
2022-09-29 10:04:31 [ℹ]  waiting for CloudFormation stack "eksctl-test-cluster-nodegroup-serv-test-1"
2022-09-29 10:05:02 [ℹ]  waiting for CloudFormation stack "eksctl-test-cluster-nodegroup-serv-test-1"
2022-09-29 10:06:37 [ℹ]  waiting for CloudFormation stack "eksctl-test-cluster-nodegroup-serv-test-1"
2022-09-29 10:07:57 [ℹ]  waiting for CloudFormation stack "eksctl-test-cluster-nodegroup-serv-test-1"
2022-09-29 10:09:27 [ℹ]  waiting for CloudFormation stack "eksctl-test-cluster-nodegroup-serv-test-1"
2022-09-29 10:10:14 [ℹ]  waiting for CloudFormation stack "eksctl-test-cluster-nodegroup-serv-test-1"
2022-09-29 10:11:40 [ℹ]  waiting for CloudFormation stack "eksctl-test-cluster-nodegroup-serv-test-1"
2022-09-29 10:13:21 [ℹ]  waiting for CloudFormation stack "eksctl-test-cluster-nodegroup-serv-test-1"
2022-09-29 10:15:09 [ℹ]  waiting for CloudFormation stack "eksctl-test-cluster-nodegroup-serv-test-1"
2022-09-29 10:17:05 [ℹ]  waiting for CloudFormation stack "eksctl-test-cluster-nodegroup-serv-test-1"
2022-09-29 10:18:48 [ℹ]  waiting for CloudFormation stack "eksctl-test-cluster-nodegroup-serv-test-1"
2022-09-29 10:19:34 [ℹ]  waiting for CloudFormation stack "eksctl-test-cluster-nodegroup-serv-test-1"
2022-09-29 10:19:34 [ℹ]  1 error(s) occurred and nodegroups haven't been created properly, you may wish to check CloudFormation console
2022-09-29 10:19:34 [ℹ]  to cleanup resources, run 'eksctl delete nodegroup --region=eu-west-2 --cluster=test-cluster --name=<name>' for each of the failed nodegroup
2022-09-29 10:19:34 [✖]  exceeded max wait time for StackCreateComplete waiter
Error: failed to create nodegroups for cluster "test-cluster"
```

**Versions**
0.112.0

**Comment by cPu1** [comment]
> And when I use custom ami then I get error
> Error: could not create cluster provider from options: cannot set amiFamily to Ubuntu2004 when using a custom AMI

When you specify a custom AMI, you must leave the `amiFamily` field unset.

**Comment by uchiha-pain** [comment]
> When you specify a custom AMI, you must leave the amiFamily field unset.

This is what exactly I am doing but still I am getting node creation failure error. I have run the troubleshoot script. Results are below
```
HERE IS A SUMMARY OF THE ITEMS THAT REQUIRE YOUR ATTENTION: 

[WARNING]: Worker node's AMI ami-0ebb49de26355a371 differs from the public EKS Optimized AMIs. Ensure that the Kubelet daemon is at the same version as your cluster's version 1.23 or only one minor version behind. Please review this URL for further details: https://kubernetes.io/releases/version-skew-policy/ .
[WARNING]: No secondary private IP addresses are assigned to worker node i-0e775ca75fe57bb70, ensure that the CNI plugin is running properly. Please review this URL for further details: https://docs.aws.amazon.com/eks/latest/userguide/pod-networking.html
[WARNING]: As SSM agent is not reachable on worker node, this document did not check the status of Containerd, Docker and Kubelet daemons. Ensure that required daemons (containerd, docker, kubelet) are running on the worker node using command "systemctl status <daemon-name>".

============================================================================================================================================
Here are the detailed steps of the document execution: 

[X] Checking EKS cluster test-cluster: EKS Cluster: test-cluster is in Active state.
    
1. Checking if the cluster Security Group is allowing traffic from the worker node:
       Passed: The cluster Security Group sg-068d83e5a68aff9c7 is allowing traffic from the worker node.
    
2. Checking DHCP options of the cluster VPC:
       Passed: AmazonProvidedDNS is enabled
    
3. Checking cluster IAM role arn:aws:iam::782534010321:role/eksctl-test-cluster-cluster-ServiceRole-9WPNFE2Q3N2T for the required permissions:
       Passed: IAM role for cluster test-cluster has the required IAM policies attached.
       Passed: The cluster IAM role arn:aws:iam::782534010321:role/eksctl-test-cluster-cluster-ServiceRole-9WPNFE2Q3N2T has the required trust relationship for the EKS service.
    
4. Checking control plane Elastic Network Interfaces(ENIs) in the cluster VPC:
       Passed: The cluster Elastic Network Interfaces(ENIs) exist.
    
5. Cluster Endpoint Private access is disabled for your cluster, checking if the Public CIDR ranges include worker node i-0e775ca75fe57bb70 outbound IP:
       Passed: The cluster allows public access from 0.0.0.0/0
    
 6. Checking cluster VPC for required DNS attributes:
       Passed: Cluster VPC vpc-0cbb4879c588fb52a has the required DNS attributes correctly set.
--------------------------------------------------------------------------------------------------------------------------------------------
[X] Checking worker node i-0e775ca75fe57bb70 state: The instance is Running.
    
1. Checking if the EC2 instance family is supported:
       Passed: EC2 instance family m5.xlarge is supported.
    
2. Checking the worker node network configuration:
       Passed: Worker node is created in a private subnet without a NAT Gateway so VPC endpoints need to be used.
       Passed: Checking VPC Endpoints setup:
        Passed: The VPC Endpoint com.amazonaws.eu-west-2.ec2 exists. Checking its configuration:
           Passed: Security groups [{'GroupId': 'sg-01294c96494e79aaa', 'GroupName': 'eksctl-test-cluster-cluster-ClusterSharedNodeSecurityGroup-1TIY3P78RYQOZ'}] applied to VPC Endpoint com.amazonaws.eu-west-2.ec2 is allowing the worker node to reach the endpoint.
           Passed: The default VPC Endpoint Policy is being used.
        Passed: The VPC Endpoint com.amazonaws.eu-west-2.ecr.api exists. Checking its configuration:
           Passed: Security groups [{'GroupId': 'sg-01294c96494e79aaa', 'GroupName': 'eksctl-test-cluster-cluster-ClusterSharedNodeSecurityGroup-1TIY3P78RYQOZ'}] applied to VPC Endpoint com.amazonaws.eu-west-2.ecr.api is allowing the worker node to reach the endpoint.
           Passed: The default VPC Endpoint Policy is being used.
        Passed: The VPC Endpoint com.amazonaws.eu-west-2.ecr.dkr exists. Checking its configuration:
           Passed: Security groups [{'GroupId': 'sg-01294c96494e79aaa', 'GroupName': 'eksctl-test-cluster-cluster-ClusterSharedNodeSecurityGroup-1TIY3P78RYQOZ'}] applied to VPC Endpoint com.amazonaws.eu-west-2.ecr.dkr is allowing the worker node to reach the endpoint.
           Passed: The default VPC Endpoint Policy is being used.
        Passed: The VPC Endpoint com.amazonaws.eu-west-2.sts exists. Checking its configuration:
           Passed: Security groups [{'GroupId': 'sg-01294c96494e79aaa', 'GroupName': 'eksctl-test-cluster-cluster-ClusterSharedNodeSecurityGroup-1TIY3P78RYQOZ'}] applied to VPC Endpoint com.amazonaws.eu-west-2.sts is allowing the worker node to reach the endpoint.
           Passed: The default VPC Endpoint Policy is being used.
        Passed: S3 gateway endpoint ['vpce-0e01543hg654cf1735', 'vpce-0564h765d01'] is added to the worker's VPC.
        Passed: Worker node's route table rtb-0d26fefe5a613e64f has the required route for the S3 endpoint vpce-0e01febb999cf1735.
        Passed: Worker node's route table rtb-0d26fefe5a613e64f has the required route for the S3 endpoint vpce-08ef7ffac589c3d01.
    
3. Checking the IAM instance Profile of the worker node:
       Passed: The instance profile arn:aws:iam::782534010321:instance-profile/eks-d0c1cede-94e5-c6bc-75fd-2f86043a90eb is used with the worker node i-0e775ca75fe57bb70 .
        Passed: IAM role arn:aws:iam::782534010321:role/eksctl-test-cluster-nodegroup-ser-NodeInstanceRole-12LZWOL4EJAJX is attached to Instance Profile.
        Passed: IAM role arn:aws:iam::7825343254321:role/eksctl-test-cluster-nodegroup-ser-NodeInstanceRole-6512LZWOL4EJAJX has the required IAM policies attached.
        Passed: No issues detected with the trust relationship policy of the arn:aws:iam::782534010321:role/eksctl-test-cluster-nodegroup-ser-NodeInstanceRole-12LZWOL4EJAJX role.
    
4. Checking worker node's UserData bootstrap script:
       Passed: The UserData of the worker node contains the required bootstrap script.
    
5. Checking the worker node i-0e775ca75fe57bb70 tags:
       Passed: Worker node i-0e775ca75fe57bb70 has the required cluster tags.
    
6. Checking the AMI version for EC2 instance i-0e775ca75fe57bb70:
       [WARNING]: Worker node's AMI ami-0ebb49de26355a371 differs from the public EKS Optimized AMIs. Ensure that the Kubelet daemon is at the same version as your cluster's version 1.23 or only one minor version behind. Please review this URL for further details: https://kubernetes.io/releases/version-skew-policy/ .
    
7. Checking worker node i-0e775ca75fe57bb70 Elastic Network Interfaces(ENIs) and Private IP addresses to check if CNI is running:
       [WARNING]: No secondary private IP addresses are assigned to worker node i-0e775ca75fe57bb70, ensure that the CNI plugin is running properly. Please review this URL for further details: https://docs.aws.amazon.com/eks/latest/userguide/pod-networking.html
    
8. Checking the outbound SG rules for worker node i-0e775ca75fe57bb70
       Passed: The Outbound security group rules for worker node i-0e775ca75fe57bb70 are sufficient to allow traffic to the EKS cluster endpoint
    
9. Checking if the worker node is running in AWS Outposts subnet
       Passed: Worker node's subnet subnet-092b2d53a7gd3455f is not running in AWS Outposts
    
10. Checking basic NACL rules
       Passed: NACL acl-0507434ac43g54gb3dc has sufficient rules to allow cluster traffic.
    
11. Checking STS regional endpoint availability:
       Passed: STS endpoint is activated within region eu-west-2.
    
12. Checking if Instance Metadata http endpoint is enabled on the worker node:
       Passed: Instance metadata endpoint is enabled on the worker node.
    
13. Checking if SSM agent is running and reachable on worker node:
       [WARNING]: As SSM agent is not reachable on worker node, this document did not check the status of Containerd, Docker and Kubelet daemons. Ensure that required daemons (containerd, docker, kubelet) are running on the worker node using command "systemctl status <daemon-name>".
============================================================================================================================================
Here is a list of other possible causes that were NOT checked by this document:
 [-] Ensure that Instance IAM role is added to aws-auth configmap, please check: https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html.
 [-] If your account is a part of AWS Organizations Service, confirm that no Service Control Policy (SCP) is denying required permissions, please check: https://aws.amazon.com/premiumsupport/knowledge-center/eks-node-status-ready/. 

```

My cluster config is as below
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-cluster
  region: eu-west-2
  version: "1.23"

privateCluster:
  enabled: true

vpc:
  id: vpc-ID
  subnets:
    private:
      hscn-private1-subnet:
        id: subnet-1
      hscn-private2-subnet:
        id: subnet-2
managedNodeGroups:
  - name: serv-test-1
    ami: ami-0ebb49de26355a371
    instanceType: m5.xlarge
    desiredCapacity: 1
    volumeType: gp2
    volumeSize: 50
    privateNetworking: true
    disableIMDSv1: true
    subnets:
      - hscn-private2-subnet
    ssh:
      allow: true
    tags:
      kubernetes.io/cluster/test-cluster: owned
    overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh test-cluster --kubelet-extra-args '--node-labels=eks.amazonaws.com/nodegroup=serv-test-1,eks.amazonaws.com/nodegroup-image=ami-0ebb49de26355a371' --dns-cluster-ip 10.100.0.10 --apiserver-endpoint {My endpoint} --b64-cluster-ca {My-CA}
```
