### ISSUE TITLE
[Feature]  launching one or various node in a managedNodeGroupe connected to various subnets at the same time

### ISSUE THREAD

**Issue by Lautreck** [weaveworks/eksctl#5763]
Hello,
 i haven't found any way to create nodes connected to various subnets when creating a cluster and ManagedNodeGroupes

Here is the yaml i use, it create a node, but on one of the subnets i gave, instead of creating a node, connected to all the subnets i gave.

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksworkshop-eksctl
  region: eu-west-1
  version: "1.23"

vpc:
  id: "vpc-09147b10407aa1b63"
  cidr: "10.0.0.0/16"
  subnets:
    private:
      private1-eu-west-1a:
        id: "subnet-02a9d98ae2cc9252b"
      private3-eu-west-1a:
        id: "subnet-0c50ea4e5fc4bb5a7"
      private5-eu-west-1a:
        id: "subnet-0d15d58c0ef275a57"
      private2-eu-west-1b:
        id: "subnet-06f049acbabfd3ff4"
      private4-eu-west-1b:
        id: "subnet-08e40c4c3558c402d"
      private6-eu-west-1b:
        id: "subnet-07ba65a606e05d8cc"

    public:
      public1-eu-west-1a:
        id: "subnet-02fb23a3b1d042bc0"
      public2-eu-west-1b:
        id: "subnet-06be5bbc2848ec13d"

managedNodeGroups:
- name: ng-1
  desiredCapacity: 1
  privateNetworking: true
  subnets: 
    - private1-eu-west-1a
    - private3-eu-west-1a
    - private5-eu-west-1a
  instanceType: m5.xlarge
  volumeSize: 40
  ssh:
    publicKeyPath: /home/pablo/.ssh/id_rsa.pub


- name: ng-2        
  desiredCapacity: 1
  privateNetworking: true
  subnets: 
    - private2-eu-west-1b
    - private4-eu-west-1b
    - private6-eu-west-1b
  instanceType: m5.xlarge
  volumeSize: 40
  ssh:
    publicKeyPath: /home/pablo/.ssh/id_rsa.pub
```
