### ISSUE TITLE
Add support to edit cluster tags after cluster creation

### ISSUE THREAD

**Issue by AhmedSa-mir** [weaveworks/eksctl#5784]
## Feature Description
I'm creating several ephemeral clusters using eksctl. Each cluster has a `delete-after` tag that indicates how long should that cluster live. To auto-delete cluster, a job runs daily to check the `delete-after` tag along with the creation time of the clusters.

I need to be able to edit the `delete-after` tag to extend the cluster lifetime.
```
metadata:
  name: ...
  region: ...
  version: ...
  tags:
    environment: "dev"
    delete-after: "10"  # edit this to increase lifetime
```
I ran `eksctl upgrade cluster -f <edited-cluster-config>` but it seems like it updates the cluster version only.

I'm happy to work on that feature if I can get some pointers on where to start :)
