### ISSUE TITLE
[Bug] 'update iamserviceaccount' incorrect include/exclude behavior, doesn't affect create/delete (0.120.0)

### ISSUE THREAD

**Issue by whereisaaron** [weaveworks/eksctl#5843]
### What were you trying to accomplish?

Updating an IAM Service Account in order to trigger the re-annotation of the k8s `ServiceAccount`, using `eksctl` and a config file.

### What happened?

1. I was unable to select a single `iam.ServiceAccount` with `update` and `--include`, I could only get the command to select all accounts or none. The same `--include` with `create` or `delete` worked just fine.
2. When I used the non-config-file approach I found `update` didn't update the k8s `ServiceAccount` like `create`/`delete` do.
3. I had to fall back to deleting and then recreating the `iam.ServiceAccount` in order to reannotate the `ServiceAccount`

While `ekstcl create iamservice` and `ekstcl delete iamservice` work with `--include` and `--exclude` exactly as expected. The `ekstcl update iamservice` include/exclude behavior was inexplicable.

`ekstcl update iamservice` with `--config-file=myconfig.yaml` and

*  `--include=nonmatching/serviceaccount` matches nothing as expected ✅
*  `--include=matching/serviceaccount` should match one account but actually matches *all* IAM Service Accounts in the config ❌
* `'--exclude=*'` matches *all* IAM Service Accounts in the config ❌
* `--exclude=nonmatching` matches *all* IAM Service Accounts in the config ✅

When I worked around the config file problem, I found that 'update' doesn't actually update the ServiceAccount in k8s (as I expected, since create/delete do account on the `ServiceAccount`), just the Cloudformation stack. I had to delete/create in the end.

### How to reproduce it?

1. `eksctl` config file `foo.yaml` with more than one iam.serviceAccount.
2. `ekstcl update iamservice --config-file=foo.yaml --include=amazon-cloudwatch/cloudwatch-agent`
3. Note that the plan is to update all accounts, not just the included one 

```
iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: aws-node
        namespace: kube-system
      attachPolicyARNs:
      - 'arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy'
    - metadata:
        name: cloudwatch-agent
        namespace: amazon-cloudwatch
      attachPolicyARNs:
      - 'arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy'
    - metadata:
        name: fluent-bit
        namespace: amazon-cloudwatch
      attachPolicyARNs:
      - 'arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy'
...   
```

**Anything else we need to know?**

I worked around this by not using the config file. I found that 'update' doesn't actually update the ServiceAccount in k8s (as I expected), just the Cloudformation stack. I had to delete/create as a workaround.

Downloaded Linux binary, default profile.

**Versions**

```
$ eksctl info
eksctl version: 0.102.0
kubectl version: v1.22.6-eks-7d68063
OS: linux
```
