### ISSUE TITLE
[Help] config created with eksctl utils write-kubeconfig vs. aws eks update-kubeconfig

### ISSUE THREAD

**Issue by ecc256** [weaveworks/eksctl#5859]
_kubectl v1.25.0
eksctl 0.116.0
aws-cli/2.8.7 Python/3.9.11 Windows/10 exe/AMD64 prompt/off_

It was long running `eksctl create cluster -f ...`
partial log is below:
```
2022-11-02 12:48:57 [ℹ]  waiting for the control plane to become ready
2022-11-02 12:48:58 [✔]  saved kubeconfig as "C:\\Users\\admin\\.kube\\config"
2022-11-02 12:48:58 [ℹ]  no tasks
2022-11-02 12:48:58 [✔]  all EKS cluster resources for "k8s" have been created
...
2022-11-02 12:50:49 [ℹ]  creating addon
2022-11-02 12:51:42 [ℹ]  addon "aws-ebs-csi-driver" active
2022-11-02 12:51:43 [✖]  unable to use kubectl with the EKS cluster (check 'kubectl version'): WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Unable to connect to the server: getting credentials: decoding stdout: no kind "ExecCredential" is registered for version "client.authentication.k8s.io/v1alpha1" in scheme "pkg/client/auth/exec/exec.go:62"

2022-11-02 12:51:43 [ℹ]  cluster should be functional despite missing (or misconfigured) client binaries
2022-11-02 12:51:43 [✔]  EKS cluster "k8s" in "us-east-1" region is ready
```
turned out, **~/.kube/config** is quite different for:

`eksctl utils write-kubeconfig --cluster=k8s`
```
- name: admin@k8s.us-east-1.eksctl.io
user:
exec:
apiVersion: client.authentication.k8s.io/v1beta1
args:
- token
- -i
- k8s
command: heptio-authenticator-aws
env:
- name: AWS_STS_REGIONAL_ENDPOINTS
value: regional
- name: AWS_DEFAULT_REGION
value: us-east-1
provideClusterInfo: false
```

`aws eks update-kubeconfig --name k8s`
```
name: arn:aws:eks:us-east-1:123456789012:cluster/k8s
user:
exec:
apiVersion: client.authentication.k8s.io/v1beta1
args:
- --region
- us-east-1
- eks
- get-token
- --cluster-name
- k8s
command: aws
```
I wonder, why `eksctl utils write-kubeconfig` uses
_command: heptio-authenticator-aws_
which results in error
**Unable to connect to the server: getting credentials: decoding stdout: no kind "ExecCredential" is registered for version "client.authentication.k8s.io/v1alpha1" in scheme "pkg/client/auth/exec/exec.go:62"**

The config created with `aws eks update-kubeconfig` works fine with `kubectl`

Is there a way for `eksctl utils write-kubeconfig` to create same config as `aws eks update-kubeconfig`?

**Comment by TiberiuGC** [comment]
Hi @ecc256 - Could you try doing the steps suggested [here](https://github.com/weaveworks/eksctl/issues/5689#issuecomment-1253427913) and see if this fixes your issue. Interestingly enough I see `apiVersion: client.authentication.k8s.io/v1beta1` in both `./kube/config`s you've shared, but the error mentions `client.authentication.k8s.io/v1alpha1` 🤔

**Comment by ecc256** [comment]
> Hi @ecc256 - Could you try doing the steps suggested [here](https://github.com/weaveworks/eksctl/issues/5689#issuecomment-1253427913) and see if this fixes your issue. Interestingly enough I see `apiVersion: client.authentication.k8s.io/v1beta1` in both `./kube/config`s you've shared, but the error mentions `client.authentication.k8s.io/v1alpha1` 🤔

I've searched `./kube/config`, there is single `v1alpha1` instance in different EKS:
```
users:
- name: aws-dev-test
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - test
      command: aws
      env:
      - name: AWS_PROFILE
        value: tnet-dev
      interactiveMode: IfAvailable
      provideClusterInfo: false
```

I've replaced it with `v1beta1`, but it's the same error mentioning `v1alpha1` still when I run get nodes...

About versions, they are all latest:
_kubectl v1.25.0
eksctl 0.116.0
aws-cli/2.8.7 Python/3.9.11 Windows/10 exe/AMD64 prompt/off_

**Comment by ecc256** [comment]
I've cleaned up `~/kube/config` and run `eksctl utils write-kubeconfig --cluster=k8s` again.
It generated very same `heptio-authenticator-aws` settings...
Tried for different AWS EKS - got `heptio-authenticator-aws` settings too.

Where they are coming from...? 😕

**Comment by ecc256** [comment]
Tried to uninstall aws-iam-authenticator, it's not even there...
**choco uninstall -y aws-iam-authenticator**
```
Chocolatey v0.11.3
Uninstalling the following packages:
aws-iam-authenticator
aws-iam-authenticator is not installed. Cannot uninstall a non-existent package.

Chocolatey uninstalled 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - aws-iam-authenticator - aws-iam-authenticator is not installed. Cannot uninstall a non-existent package.
```

**Comment by ecc256** [comment]
One more update: I've tried the same steps on WSL on same computer, got **right** `~/.kube/config`
```
- name: k8s
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - eks
      - get-token
      - --cluster-name
      - k8s
      - --region
      - us-east-1
      command: aws
      env:
      - name: AWS_STS_REGIONAL_ENDPOINTS
        value: regional
      provideClusterInfo: false
```
_kubectl v1.25.3
eksctl 0.116.0
aws-cli/2.8.7 Python/3.9.11 Linux/4.4.0-17763-Microsoft exe/x86_64.ubuntu.22 prompt/off_
