### ISSUE TITLE
[Bug] overrideBootstrapCommand corrupting userdata?

### ISSUE THREAD

**Issue by EhsanLunar** [weaveworks/eksctl#5862]
### What were you trying to accomplish?
Deploy an unmanaged nodegroup using `eksctl` pointing to a config file

### What happened?
The bootstrap script never runs

### How to reproduce it?

running `eksctl create nodegroup -f nodegroup.yaml`

nodegroup.yaml:

``` yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: capi-cluster
  region: eu-west-1
  version: "1.23"

nodeGroups:
  - name: capi-cluster-ng-1
    instanceType: m5.large
    instanceName: capi-cluster-node
    desiredCapacity: 3
    minSize: 3
    maxSize: 6
    volumeSize: 128
    volumeType: gp3
    ami: ami-00d221f9868c0a2bf
    overrideBootstrapCommand: | 
      #!/bin/bash
      mkdir -p /etc/docker;
      /etc/eks/bootstrap.sh capi-cluster
    labels:
      nodegroup-type: node
      role: node
    privateNetworking: true
```

**Anything else we need to know?**
The AMI is a flatcar 3227.2.3

When creating the nodegroup, the userdata in the launch template looks like the following:
```
H4sIAAAAAAAA/5RX7XKjOLP+n6vQ8aR2duoMNuA4O8kpV51ghG1s5CCQsNnaSsmgiTEgGJCD42zu/S3byawzX/XuH0CtflpPC6k/3kVZsYmVqBCfk/uzkkUpu+f1NRCbLDurNiLK4+szBSigs0xEZ8nq1RkAClCiw+vvMwAAePc/p5MA5GmcVEApQYfLqBMXUcqr/zvMHAQ8rTvLopC1rFjZrlcgYmWi5Eywe55zIY/LPbCqkyXLzoFfp46qpJT1HhvJ7AS+4lnJq3a9OmuqRPK7z0nG6z3jqBCSC3kN3j89vz8DoGgEr65BVRTyev84A6BkcnX9ldPebrpZ8oxLhW9lxdrruhB7NV7lSV0nhaivQUu9vLhondr/Wzm4hmYmvPNvxsj3+gfBYEo8H+I7E3l9TW1rqtreP49zM7RXhfgOE+SPHdg/7lL8BoluHNj/dnP2Cje34zsPYgrxHcHT/krKsr7udPSrT2rPtG6gpWu9mxsDahfwcvBJtS5vVNMwjPZ99Uebb5SG11LR2jyt2yxnu0Kwpm5HRX6wbVxe3L0SGNz0p54qp542wCS2/cQwMbWJR0LbVS2CD3OqHKSa7RHngaXIdAO6ClWr6xHbCNVs4BJs+KktWNcqmJ6NZvOocVMLR2poYGgFPrVRrFIcEBwQakE8j5sox3MvbyYLXdWWQzyiokTuGi+whW1ONILnMeIpVP0UVzy92C61FaRQ6/kUGzzViOvjGR7KS39tPcRqSDDFyE3pyPUtit3S4FCbLnwUMFouPEFZYNn1oluarmr53jyGhGYTT79iXrDSF2rPIIQO3Mwy8DAWmBoGhsh0qfXg6rHAxDY83SoGAj7OglJ3tJWcdOMFyfB8RsrGy8IvqGtIlNsUQ6thO0tlAWrozpiEu3HjmTbx1shFAYVoh0RMs7W/oxCnZRN1i0lEQhdn410gystlN6wY2VqeGdok395SK3zwR26DtRt9RvCtr1pfmE9hpFmDILeDiRqO2I4KpNseUa9GnjBKfxjPQ7fQlqZd82Allzke0jwccWhPPJWOvRR32XCs4R1sKLEWkRVOkbDMMLmqprp0yNra0serAs8t6JuIRl2oUh9JJwjDwdp2PCuWLkl3DtS0UNXMpXq1ibSYeprTTHSni7rpI1vHpu/jCdKMZNHNirBLkSNw6JDtyBer9WyEMVJXobsbNy6JJiyLdg5MNZrHepxnt0Sv9VjElaPHM1+FOhmFCR8ij2RUTtWQhAP5BQs6WVrIQN1yHqllE2fuhd+FPSfADsksuWjKsTPMdk6WdqO1o7la8RiODLgcashVrS4mlrEgPeaTcB2rWBzO59pwXWqNp6ptEIKNUJWVT+AFVuGWBtiKVToYJFddQkLkEm3gBouLWF3hF+ytm9ohJuEktJDrjGg28+mFn2bNIv30ONmFGg2oE8BsFPoZcrPjeQ0hxYR8mvjE6rkqkrFphUsa9ha5FjhWufB/fF6dr+eV2Ia7xiENtl8Wohzh/Cp0suLBn1PoumWCAy2JdRoss0UvHjqPaDTW+XD8EFB74GeWhoRhLC1jHmR47ur2F2RmgwhKD4/owg006ZmrnAe9NEw1GqlXD1Td+oMMJf46Wy92tuMMo2qRa93FOrPjeXgZ+OOur9prnG8J04seCrJxTMsJyVUV65J5wX2z1MMvS4gW0667debG2qP2Ldo5Ewz3d6k0p49Xtyjf5lhDNs6RwS2Usp3lUViKpU8hzrN0oZaQBWXjwXBMU62Lh1rgePKCWHTujcqdN7K9/drTpmgCayW9PJwsdecC66thbFpm3F1JV40apkrpzl01HEgHm44ek16BArtCOdaCtCQYFhoxceXrPear1hiP7FU0zMggxZiKsibC1iLLqildBbhrL5Zq2KWB2gsf5S1Lt4sQ9pCfw8ql4Sxa00s+N9YOtDe+hRN3hypu2iNHXZkejOsguJ9Qc0Vv3eIQd6eEzvDgJzH5vt//Jy9Nbww49fosK1esfcx17aToRNmmlrxSBMv5t4nm47fKooj5fVVsyh+qK+Je0T/+oyMfS97fDz9WRXb8+pdJuM3Fw3+Rfb+rQA6CmkugFIBXFd8m8lRUJiX/zJLsVCaKjai5fIEWmyriP2ME3oF9iQH21YbkAiwfwddipOTV0cQ7QGoOxo7pPehAFuCeS5BzyWIm2UHBn00g6rfOf482VQYUpU4yLiRQ5uCW+EAZgdZcYU2t8EhXXoGKLFIuFCkzpeZRIeL6Glyqagvs0/91p6NdXrX13kX75d3JmOS17LAy6RyQH1qHpT9vRCSTQuxJ3b3a/v0DeDrMAvANo19QuQbnBz9aoPVrCnuYssd1zrUjieezH9UxrfOnt5Ln1o9Kktb501vJi9oYef4NGsC7sbnf2lP/QCJqyUTElST+8I32dGzBwWIwhT8HZclnrkSPUcZfwKe1Xev86WR4rbywOa0HW+dPJ8OvKs7N/O52Zh7mX7/f4l/u7Sv+OHw+XLMDqQOn/vnT9848f3d/T7bgFDE2n1vHvzEhBpxC/+4GD73+7y1FOS7Dljyr+28ZtD4cEH/+CRQB3nr33AJ//QV+++2Nuf892Kv4fXKIN00iV4pkiZBfDb+CP7xcIEXJ2VYpi7gGrAYMDKZjwKr7zT7WgKQGMS8rHjHJ449ArpJ6L2OgKaqUVcVGxGAjZJKBhv+jCepNWRaVBJ+LCuRse1vE9S2v0DE0nXjz+i9+4coruf6p9oc32wjnPr45bmbr/OnUxJ///9frnr8p9U9O0n78chBekYMZssbD/vtDYNpHpEpwyevX4PS1dzm2cofm5f0PCL0x89O254j0ndu7PfoA6r/vyLx8s8yJ6vcdzd6bb4XXykuf89wC70DMP7NNdvwfLNPBelNLkAgQsZp/BKKQYFPzeC/ZLDdCbn6ZQP51v/hdavmj12ud/ScAAP//ZkEt0xAPAAA=
```

I don't know why, this looks like some sort of encrypted data (it's not base64).

If I manually create a new launch template version and manually change the userdata to reflect the 3 lines in the `overrideBootstrapCommand` than it works fine for some reason

**Versions**
tried both:
```
$ eksctl info
eksctl version: 0.109.0-dev+78243b4c.2022-08-19T12:49:29Z
kubectl version: v1.22.11
OS: linux
```
and
```
$ eksctl info
eksctl version: 0.116.0
kubectl version: v1.23.7
OS: linux
```
