### ISSUE TITLE
[Feature] Support instance types that are only available in a single zone

### ISSUE THREAD

**Issue by dewjam** [weaveworks/eksctl#5933]
### What feature/behavior/change do you want?

If an instance type is only available in a single availability zone in a given region, then randomly select the remaining AZs to meet the minimum AZ count requirement for an EKS cluster.

### Why do you want this feature?

Trn1 instance types are only available in a single zone in us-east-1 and us-west-2.  As a result, when launching a cluster with a Trn1 node group via `eksctl`, an error is returned:
```
Error: getting availability zones: only 1 zones discovered [us-west-2d], at least 2 are required
```
In order to create a cluster successfully, you must discover the zone where Trn1 instance types are supported and then provide at least one additional zone (in the example below, I added us-west-2b). This results in a clusterConfig that looks like this:
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: trainium
  region: us-west-2
availabilityZones:
  - us-west-2b
  - us-west-2d
nodeGroups:
  - name: trainium
    instanceType: trn1.2xlarge
    availabilityZones:
      - us-west-2d
    minSize: 1
    maxSize: 2
    desiredCapacity: 2
    volumeSize: 40
```
I would  like eksctl to handle this case gracefully and just randomly select the remaining AZs (for the cluster only) until the minimum number of AZs is met.
