### ISSUE TITLE
[Bug] KubeletExtraConfig will be ignore when using custom AMI with self-managed node group

### ISSUE THREAD

**Issue by yws-ss** [weaveworks/eksctl#5995]
### What were you trying to accomplish?

Create a self-managed node group with custom AMI. Also, configure the kubeletReserved/SystemReserved through KubeletExtraConfig

### What happened?

According to new [announcement](https://eksctl.io/announcements/nodegroup-override-announcement/), eksctl decided to remove the eksctl's bootstrap script for custom AMI with node group. Therefore, in order to early adopt this change, we follow the guideline to add overrideBootstrapCommand. Following is my current YAML:

```
nodeGroups:
  - instanceType: c5.2xlarge
    overrideBootstrapCommand: |
     #!/bin/bash

      source /var/lib/cloud/scripts/eksctl/bootstrap.helper.sh

      /etc/eks/bootstrap.sh ${CLUSTER_NAME} --container-runtime containerd --kubelet-extra-args "--node-labels=${NODE_LABELS}"
    labels: { role: workers, eks.amazonaws.com/nodegroup: ng-02}
    name: ng-02
    minSize: 2
    maxSize: 10
    desiredCapacity: 2
    volumeSize: 100
    volumeType: gp3
    volumeIOPS: 4500
    volumeThroughput: 300
    privateNetworking: true
    disableIMDSv1: true
    disablePodIMDS: true
    kubeletExtraConfig:
        kubeReserved:
            cpu: "300m"
            memory: "300Mi"
            ephemeral-storage: "1Gi"
        kubeReservedCgroup: "/kube-reserved"
        systemReserved:
            cpu: "300m"
            memory: "300Mi"
            ephemeral-storage: "1Gi"
        evictionHard:
            memory.available:  "200Mi"
            nodefs.available: "10%"
        featureGates:
            RotateKubeletServerCertificate: true
```

However, we found that this behavior would lead the KubeletExtraConfig doesn't merge the extra configuration into kubelet config which EKS Optimized AMI already contain. Which mean, the configuration wouldn't effect. 

### How to reproduce it?

Create a node group with above YAML configuration.

**Logs**

**Anything else we need to know?**

**Versions**

```
$ eksctl info
eksctl version: 0.121.0
kubectl version: v1.22.6-eks-7d68063
OS: linux```
