### ISSUE TITLE
Custom AMI with the standard bootstrap command fails for self-managed nodegroups

### ISSUE THREAD

**Issue by cPu1** [weaveworks/eksctl#6029]
When using a custom AMI for a self-managed nodegroup with the standard bootstrap command, the nodes fail to join the cluster and the command eventually times out.

To reproduce, create a nodegroup with this config. 

```yaml

nodeGroups:
  - name: ng
    ami: ami-0e40b85f2046a3ec9
    desiredCapacity: 1
    maxSize: 2
    minSize: 1
    overrideBootstrapCommand: |
      #!/bin/bash
      source /var/lib/cloud/scripts/eksctl/bootstrap.helper.sh
      /etc/eks/bootstrap.sh ${CLUSTER_NAME} --kubelet-extra-args "--node-labels=${NODE_LABELS}"
```

This was caught in `integration/tests/override_bootstrap/override_bootstrap_test.go` but is also reproducible using the config above. Several runs of this test have failed but there was one instance where it passed, so it's possible this may be a flake.

**Comment by jpmcb** [comment]
I ran into this today. Here's my `eksctl.yaml`:

```
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-test
  region: us-west-2
  version: '1.24'

nodeGroups:
  - name: test-bottlerocket-ng
    instanceType: m5.large
    desiredCapacity: 4
    ami: ami-abc123
    iam:
       attachPolicyARNs:
          - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
          - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
          - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
          - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
    overrideBootstrapCommand: |
      #!/bin/bash
      source /var/lib/cloud/scripts/eksctl/bootstrap.helper.sh
      /etc/eks/bootstrap.sh ${CLUSTER_NAME} --container-runtime containerd --kubelet-extra-args "--node-labels=${NODE_LABELS}"
```

Deployed the cluster with `eksctl` where it eventually times out:
```
$ eksctl create clsuter -f eksctl.yaml
... 
2022-12-12 18:30:58 [ℹ]  nodegroup "test-bottlerocket-ng" has 0 node(s)
2022-12-12 18:30:58 [ℹ]  waiting for at least 4 node(s) to become ready in "test-bottlerocket-ng"
Error: timed out waiting for at least 4 nodes to join the cluster and become ready in "test-bottlerocket-ng": context deadline exceeded
```

And no nodes end up attaching:
```
❯ k get nodes -A
No resources found
❯ k get pods -A
NAMESPACE     NAME                       READY   STATUS    RESTARTS   AGE
kube-system   coredns-799c5565b4-lzxc2   0/1     Pending   0          37m
kube-system   coredns-799c5565b4-zcvgl   0/1     Pending   0          37m
```

Is there a work around for this? I'm attempting to deploy custom builds of bottlerocket for testing
