### ISSUE TITLE
[Bug] Use gp3 instead of gp2 for Bottlerocket OS Volume

### ISSUE THREAD

**Issue by cest-pas-faux** [weaveworks/eksctl#6046]
### What were you trying to accomplish?
Trying to use `gp3` instead of `gp2` for the Bottlerocket OS volume.
This is only for the OS volume, not for the other one.

### What happened?
The 2Gb OS volume for bottlerocket is created using `gp2`, we try to get rid of all `gp2` volumes in our accounts, and I tried to switch to `gp3` without success, it keeps creating `gp2` volumes.

### How to reproduce it?

Here is my sample config, I just updated the commented part and recreated the nodegroup
```Yaml
managedNodeGroups:
  - name: spot-1a
    spot: true
    minSize: 1
    maxSize: 2
    desiredCapacity: 1
    instanceTypes: ["c5.2xlarge", "c5.4xlarge", "c5a.2xlarge", "c5a.4xlarge", "c5a.8xlarge", "c5n.2xlarge", "c5n.4xlarge", "c6a.2xlarge", "c6a.4xlarge", "c6i.2xlarge", "c6i.4xlarge", "m5.2xlarge", "m5.4xlarge", "m5a.2xlarge", "m5a.4xlarge", "m5n.2xlarge", "m5n.4xlarge", "m5zn.2xlarge", "m5zn.3xlarge", "m6a.2xlarge", "m6a.4xlarge", "m6i.2xlarge", "m6i.4xlarge", "r5.2xlarge", "r5a.2xlarge", "r5n.2xlarge", "r6a.2xlarge", "r6i.2xlarge"]
    privateNetworking: true
    amiFamily: Bottlerocket
    volumeType: gp3 # Added this to switch to `gp3`
    subnets:
      - SUBNET-1
    ssh:
      enableSsm: true
```

**Logs**

There is no errors, the volume is created with `gp2`
**Anything else we need to know?**

**Versions**

```
$ eksctl info
eksctl version: 0.120.0
kubectl version: v1.22.15
OS: linux
```
