### ISSUE TITLE
[Help] - Ubuntu2004 custom GPU AMI

### ISSUE THREAD

**Issue by amrragab8080** [weaveworks/eksctl#6058]
I am trying to build ontop of the official Ubuntu2004 images to include GPU support however I am running ton a problem where the bootstrapped AMI does not join the cluster. I traced the issue to a deviation in the userdata used between the official Ubuntu EKS worker AMIs and the documentation.

In the official documentation it recommends using this as the custom `overrideBootstrapCommand`
```
#!/bin/bash
/etc/eks/bootstrap.sh wonderful-gopher-1640015277
```
However in the official EKS Ubuntu AMI it uses the below for the userdata:
```
#!/bin/sh
'/var/lib/cloud/scripts/eksctl/bootstrap.ubuntu.sh'
'/var/lib/cloud/scripts/eksctl/bootstrap.helper.sh'
```
When attempt to use the bootstrap.*.sh files as my overrideBootstrap those files are not found. My question is where is the code is it creating the `/var/lib/cloud/scripts/eksctl/` and `/etc/eksct/` and how do i replicate that since the `/etc/eks/bootstrap` is not creating it either?

K8s 1.23

**Comment by mmerkes** [comment]
The first code sample looks like a command for the EKS optimized AMIs.

**Comment by amrragab8080** [comment]
In the documentation a third options is available here
https://eksctl.io/announcements/nodegroup-override-announcement/
```
#!/bin/bash

source /var/lib/cloud/scripts/eksctl/bootstrap.helper.sh

/etc/eks/bootstrap.sh ridiculous-mushroom-1671037852
```
You get an error:
`/var/lib/cloud/scripts/eksctl/bootstrap.helper.sh: line 7: /etc/eksctl/kubelet.env: No such file or directory`

eksctl 0.122.0

**Comment by yuxiang-zhang** [comment]
The scripts are here: https://github.com/weaveworks/eksctl/tree/main/pkg/nodebootstrap/assets/scripts

The code here add its content to the userdata and then produce a cloud-init config file
https://github.com/weaveworks/eksctl/blob/5709f2bc94efa5111766d5abe15c88b595f5e99f/pkg/nodebootstrap/userdata.go#L114

So the end results look something like this: 
```
#cloud-config
packages: null
runcmd:
- - /var/lib/cloud/scripts/eksctl/bootstrap.ubuntu.sh
- - /var/lib/cloud/scripts/eksctl/bootstrap.helper.sh
write_files:
- content: '{}'
  owner: root:root
  path: /etc/eksctl/kubelet-extra.json
  permissions: "0644"
- content: |-
    API_SERVER_URL=https://DFB6089C2A7E47CEC3E98A9C7548579C.gr7.us-west-2.eks.amazonaws.com
    B64_CLUSTER_CA=LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1USXdOekF3TWpJMU5sb1hEVE15TVRJd05EQXdNakkxTmxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTkpHCmtIWmhPNFk2bUovTXJSZDNRRUN1cTRPNFR1bFhxNTlCSnRINGRxN1lHVmpMME8ycGhDYmwxMVNZRDBlcHRENnEKVUZBS1VXbjVENDIydW5PM0FNTDhYZzJoRDQ2ajV2dEttcUxDcTJMVUlzL2NDVjd2dklxSlQ1L0J1M3pvdzIrSAorRlVwUjUvdExjTXlibWNFQVZaS1RSVzhyN0crWCt1MEppb0Vna1dTaElyS1BaVllLc04zb1ZuK3F3ZldQNmVJCjQ4YzMwU294eEdRNzVINWlXeGFkZEJ1S1JvSVdDY2lYdm9waWplS0NWUVloT0NxRzBZYVpON21tTzdldm14WFUKcG1ndFNTaFFxbFV3VmdpMkliM2JPeiswa0VYZDIyWTNIdEU5T2wyZkptempXTnVXbHpaN0YxZWdQV3E4SVFFbgpTYUpINndJc29mV2ZTR1k2NEFjQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZMTWRabCthbitXb3NiOHk0WTFMdXY4LzlVdFBNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQUZhL0xxT21Xd0FUbXIrclVVawoxSVQxanFCYWNwTiswUHNVM3BIUG00Sy93d2lhVFhXUG00NXZwZWJyN2Rad0Nvd1J4TURremxRNmUrREhTSEJTCncvd1BvMXRYU0lGRHlmRjBnVHowQ1l5aVJOYllXSUFucEttSTJMcDB6TG0zQmRGYkcxbnZROFZnOEhpMzEzb1gKQnFJUVB0aVh2eW81ZEswemxycVFRcDhXeEY5dWtHMXR5eHVpWVpkMmNoSEZZa0FsZkFCdnpBa2VZblFGeEYxSgpabEJ3REtRMzF4TVE3ZGd3M2Qwd0dISzVwc29qVmVZdWcrbThRUjFZVW05N2p0YmpJbWwyckVTUEJWTFJXc2pYCjZsTEMra2JyYUxueVVRdWJaQ0ZxQm5FU1ZqUmkxbEhhZlE3LzVvUm4wOEtoV0I4ZE1pOUxOdncwOUxHaEsxSjMKcFJnPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    NODE_LABELS=nodegroup-type=node,role=node,alpha.eksctl.io/cluster-name=riki,alpha.eksctl.io/nodegroup-name=kid
    NODE_TAINTS=
    CLUSTER_DNS=10.100.0.10
    CLUSTER_NAME=riki
  owner: root:root
  path: /etc/eksctl/kubelet.env
  permissions: "0644"
- content: |
    #!/bin/bash

    set -o errexit
    set -o pipefail
    set -o nounset

    source /var/lib/cloud/scripts/eksctl/bootstrap.helper.sh

    echo "eksctl: running /etc/eks/bootstrap"
    /etc/eks/bootstrap.sh "${CLUSTER_NAME}" \
      --dns-cluster-ip "${CLUSTER_DNS}" \
      --kubelet-extra-args "${KUBELET_EXTRA_ARGS}"

    echo "eksctl: merging user options into kubelet-config.json"
    trap 'rm -f ${TMP_KUBE_CONF}' EXIT
    jq -s '.[0] * .[1]' "${KUBELET_CONFIG}" "${KUBELET_EXTRA_CONFIG}" > "${TMP_KUBE_CONF}"
    mv "${TMP_KUBE_CONF}" "${KUBELET_CONFIG}"

    echo "eksctl: restarting kubelet-eks"
    snap restart kubelet-eks
    echo "eksctl: done"
  owner: root:root
  path: /var/lib/cloud/scripts/eksctl/bootstrap.ubuntu.sh
  permissions: "0755"
- content: |
    #!/bin/bash

    set -o errexit
    set -o pipefail
    set -o nounset

    source /etc/eksctl/kubelet.env # file written by bootstrapper

    # Use IMDSv2 to get metadata
    TOKEN="$(curl --silent -X PUT -H "X-aws-ec2-metadata-token-ttl-seconds: 600" http://169.254.169.254/latest/api/token)"
    function get_metadata() {
      curl --silent -H "X-aws-ec2-metadata-token: $TOKEN" "http://169.254.169.254/latest/meta-data/$1"
    }

    API_SERVER_URL="${API_SERVER_URL}"
    B64_CLUSTER_CA="${B64_CLUSTER_CA}"
    INSTANCE_ID="$(get_metadata instance-id)"
    INSTANCE_LIFECYCLE="$(get_metadata instance-life-cycle)"
    CLUSTER_DNS="${CLUSTER_DNS:-}"
    NODE_TAINTS="${NODE_TAINTS:-}"
    MAX_PODS="${MAX_PODS:-}"
    NODE_LABELS="${NODE_LABELS},node-lifecycle=${INSTANCE_LIFECYCLE},alpha.eksctl.io/instance-id=${INSTANCE_ID}"

    KUBELET_ARGS=("--node-labels=${NODE_LABELS}")
    [[ -n "${NODE_TAINTS}" ]] && KUBELET_ARGS+=("--register-with-taints=${NODE_TAINTS}")
    # --max-pods as a CLI argument is deprecated, this is a workaround until we deprecate support for maxPodsPerNode
    [[ -n "${MAX_PODS}" ]] && KUBELET_ARGS+=("--max-pods=${MAX_PODS}")
    KUBELET_EXTRA_ARGS="${KUBELET_ARGS[@]}"

    CLUSTER_NAME="${CLUSTER_NAME}"
    KUBELET_CONFIG='/etc/kubernetes/kubelet/kubelet-config.json'
    KUBELET_EXTRA_CONFIG='/etc/eksctl/kubelet-extra.json'
    TMP_KUBE_CONF='/tmp/kubelet-conf.json'
    CONTAINER_RUNTIME="${CONTAINER_RUNTIME:-dockerd}" # default for al2 just in case, not used in ubuntu
  owner: root:root
  path: /var/lib/cloud/scripts/eksctl/bootstrap.helper.sh
  permissions: "0755"
```

**Comment by yuxiang-zhang** [comment]
To answer the question, cloud-init config file provided as userdata will create the scripts on the instances, as seen under `write_files:`

**Comment by amrragab8080** [comment]
Thanks however when you set the override bootstrap in the yaml for the nodegroup the write_files:() are removed. So I still get the error that kubelet.env file is not created.

**Comment by yuxiang-zhang** [comment]
> Thanks however when you set the override bootstrap in the yaml for the nodegroup the write_files:() are removed. So I still get the error that kubelet.env file is not created.

I can't reproduce this error. Could you maybe share the yaml you are using?

**Comment by amrragab8080** [comment]
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ridiculous-mushroom-1671037852
  region: us-east-1

vpc:
  id: vpc-285eb355
  subnets:
    public:
      endpoint-one:
        id: subnet-5163b237
      endpoint-two:
        id: subnet-baff22e5

managedNodeGroups:
  - name: g5-ng-1d
    instanceType: g5.8xlarge
    instancePrefix: g5-ng-1d-worker
    ami: ami-0d9751b7984cf5839
    volumeSize: 100
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        ebs: true
        fsx: true
        cloudWatch: true
    ssh:
      allow: true
      publicKeyName: XXX
    subnets:
    - endpoint-two
    minSize: 1
    desiredCapacity: 1
    maxSize: 4
    overrideBootstrapCommand: |
      #!/bin/sh
      '/var/lib/cloud/scripts/eksctl/bootstrap.ubuntu.sh'
      '/var/lib/cloud/scripts/eksctl/bootstrap.helper.sh'
```
