### ISSUE TITLE
[Bug] Error: getting VPC configuration for cluster "test": could not import subnet 

### ISSUE THREAD

**Issue by shyam-ks** [weaveworks/eksctl#6089]
eksctl version - 0.123.0
Getting the following error wile running  eksctl upgrade cluster
Error: getting VPC configuration for cluster "test": could not import subnet subnet-0fd6c30bae9b54b45: subnet ID "subnet-0a21a5a7d90f47f4f" is not the same as "subnet-0fd6c30bae9b54b45"

we have multiple subnets in same zone. 
![image](https://user-images.githubusercontent.com/88625905/208716524-d90f3b8e-0a13-4bca-a4f7-f455f7b3a347.png)

Went through this documentation https://eksctl.io/usage/troubleshooting/. But in our case, there are subnets in the same zone. It should ideally look for availability zone id

Upgrade through AWS console is working fine. but not using eksctl

**Comment by cPu1** [comment]
Can you share your ClusterConfig file? Without it, we can't tell what's wrong.

**Comment by shyam-ks** [comment]
> Can you share your ClusterConfig file? Without it, we can't tell what's wrong.

This is the config file that was used to create it .. same getting used for upgrade
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: "test"
  region: "us-east-1"
  version: "1.24"
  tags:
    app: "xxxxt"
"
vpc:
  id: "vpc-06xx"  
  securityGroup: "sg-0xx"
  subnets:
    private:
      ext-sub-1:
        id: "subnet-0a21a5a7d90f47f4f"
      ext-sub-2:
        id: "subnet-0c8095698d6e8a7cd"
      ext-sub-3:
        id: "subnet-0fd6c30bae9b54b45"
  clusterEndpoints:
    privateAccess: true
    publicAccess: false
```

**Comment by shyam-ks** [comment]
> Can you share your ClusterConfig file? Without it, we can't tell what's wrong.

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: "test"
  region: "us-east-1"
  version: "1.24"
  tags:
    app: "xxx"

vpc:
  id: "vpc-06xxxx"
  # Addional security group that lets bastion host to connect to EKS control pane private endpoint
  securityGroup: "sg-0077c2ffbf8993be3"
  subnets:
    private:
      ext-sub-1:
        id: "subnet-0a21a5a7d90f47f4f"
      ext-sub-2:
        id: "subnet-0c8095698d6e8a7cd"
      ext-sub-3:
        id: "subnet-0fd6c30bae9b54b45"
  clusterEndpoints:
    privateAccess: true
    publicAccess: false
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
managedNodeGroups:
  - name: "ng-1-workers-2022-12-20-15-53-40"
    subnets:
      - ext-sub-2  
    instanceType: "m5.2xlarge"
    desiredCapacity: 1
    labels: { role: workers }
    ssh:
      publicKeyName: eks-dev
    tags:
      app: "xxx"
"
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      withAddonPolicies:
        autoScaler: true
        ebs: true
        cloudWatch: true
    privateNetworking: true
    volumeSize: 200
    volumeEncrypted: true
    securityGroups:
      attachIDs: ["sg-0077c2ffbf8993be3"]
    ami: ami-0e6e307f409b03c29
    overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh test
  - name: "ng-2-workers-2022-12-20-15-53-40"
    subnets:
      - ext-sub-3  
    instanceType: "m5.2xlarge"
    desiredCapacity: 1
    labels: { role: workers }
    ssh:
      publicKeyName: eks-dev
    tags:
      app: "xxx"

    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      withAddonPolicies:
        autoScaler: true
        ebs: true
        cloudWatch: true
    privateNetworking: true
    volumeSize: 200
    volumeEncrypted: true
    securityGroups:
      attachIDs: ["sg-0077c2ffbf8993be3"]
    ami: ami-0e6e307f409b03c29
    overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh test
```
