### ISSUE TITLE
Fully-private clusters support for Outposts

### ISSUE THREAD

**Issue by cPu1** [weaveworks/eksctl#6118]
AWS EKS now supports creating fully-private clusters in Outposts. Today, eksctl has an explicit validation to disallow creating fully-private clusters in Outposts. 

To support this, eksctl will have to create VPC endpoints for the following services. This list contains additional VPC endpoints that are not created for fully-private clusters running in an AWS region. 

```
Service name                           Endpoint type
----------------------------------------------------
com.amazonaws.us-west-2.ssm            Interface
com.amazonaws.us-west-2.ssmmessages    Interface
com.amazonaws.us-west-2.ec2messages    Interface
com.amazonaws.us-west-2.ec2            Interface
com.amazonaws.us-west-2.secretsmanager Interface
com.amazonaws.us-west-2.logs           Interface
com.amazonaws.us-west-2.sts            Interface
com.amazonaws.us-west-2.ecr.api        Interface
com.amazonaws.us-west-2.ecr.dkr        Interface
com.amazonaws.us-west-2.s3             Gateway
```

The following config file should work after this feature is added:

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: outpost
  region: us-west-2
  version: "1.21"

privateCluster:
  enabled: true
  
nodeGroups:
  - name: ng
    # Optional, defaults to the smallest available instance type on the Outpost.
    instanceType: m5d.large
    privateNetworking: true

outpost:
  # Required.
  controlPlaneOutpostARN: "arn:aws:outposts:us-west-2:1234:outpost/op-1234"
  # Optional, defaults to the smallest available instance type on the Outpost.
  controlPlaneInstanceType: m5d.large

  # Optional
  controlPlanePlacement:
    groupName: placement-group-name

```
