### ISSUE TITLE
[Help] How to use allowedUnsafeSysctls with kubeletExtraConfig

### ISSUE THREAD

**Issue by BololZ** [weaveworks/eksctl#6145]
Hello,

I'm trying to use allowedUnsafeSysctls with kubeletExtraConfig in an un-managed node-group called test-pool.
Here my yaml configuration file :

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test
  region: eu-west-3
  version: "1.24"
availabilityZones:
  - eu-west-3a
  - eu-west-3b
  - eu-west-3c

nodeGroups:
  - name: test-pool
    instanceType: i3.2xlarge
    desiredCapacity: 3
    labels:
      pool: test-pool
    privateNetworking: true
    ssh:
      allow: true
      publicKeyName: my-key
    kubeletExtraConfig:
      cpuManagerPolicy: static
      allowedUnsafeSysctls:
        - "fs.aio-max-nr"
    availabilityZones:
      - eu-west-3a
      - eu-west-3b
      - eu-west-3c
```

If l’m not wrong, the kubelet will start with a custom configuration which allow unsafe sysctl.

But I have a timeout waiting node-group creation :

```
2023-01-10 16:21:31 [ℹ]  nodegroup "test-pool" has 0 node(s)
2023-01-10 16:21:31 [ℹ]  waiting for at least 3 node(s) to become ready in "test-pool"
Error: timed out waiting for at least 3 nodes to join the cluster and become ready in "test-pool": context deadline exceeded
```

and the ec2 instances are created but not in the cluster test. It sounds like kubelet doesn't start.

Best regards.
