### ISSUE TITLE
[Help] Custom AMIs for Bottlerocket not supported

### ISSUE THREAD

**Issue by jpmcb** [weaveworks/eksctl#6146]
### What were you trying to accomplish?
I want to be able to provide a custom AMI for bottlerocket nodes.

This is a followup issue to:
- https://github.com/weaveworks/eksctl/issues/6029
- https://github.com/weaveworks/eksctl/pull/6047

and might be related to:
- https://github.com/weaveworks/eksctl/issues/5756

---

When executed with the following config:
```yaml
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: woof-meow-cluster
  region: us-west-2
  version: '1.24'

nodeGroups:
  - name: test-bottlerocket-ng
    instanceType: m5.large
    desiredCapacity: 2
    ami: ami-abc123
    bottlerocket:
      enableAdminContainer: true
      settings:
        motd: "hello world!"
```

I get the following:
```
❯ eksctl create cluster -f eksctl.yaml
Error: nodeGroups[0].overrideBootstrapCommand is required when using a custom AMI (nodeGroups[0].ami)
```

[The documented `overrideBootstrapCommand` is:](https://eksctl.io/announcements/nodegroup-override-announcement/?h=override)
```sh
#!/bin/bash
source /var/lib/cloud/scripts/eksctl/bootstrap.helper.sh
/etc/eks/bootstrap.sh ${CLUSTER_NAME} --kubelet-extra-args "--node-labels=${NODE_LABELS}"
```

_However_, Bottlerocket doesn't have the `/var/lib/cloud/scripts/eksctl/bootstrap.helper.sh` script (or at least it isn't present when building and deploying custom bottlerocket nodes):

```
bash-5.1# ls -la /var/lib/cloud/scripts/eksctl/bootstrap.helper.sh
ls: cannot access '/var/lib/cloud/scripts/eksctl/bootstrap.helper.sh': No such file or directory
```

and it doesn't seem to be used in [the `managed_bottlerocket.go` file.](https://github.com/weaveworks/eksctl/blob/main/pkg/nodebootstrap/managed_bottlerocket.go)

I'm not sure I understand the _purpose_ of the `overrideBootstrapCommand` for bottlerocket would be? We already provide a way via our settings for a user [to designate their own bootstrap-container](https://github.com/bottlerocket-os/bottlerocket#bootstrap-containers-settings) which would look something like this in a the eksctl yaml:
```
nodeGroups:
  - name: test-bottlerocket-ng
    instanceType: m5.large
    desiredCapacity: 2
    ami: ami-abc123
    bottlerocket:
      enableAdminContainer: true
      settings:
        bootstrap-containers
          bootstrap
            source: <MY-CONTAINER-URI>
```

**Versions**
```
❯ eksctl info
eksctl version: 0.122.0
kubectl version: v1.25.2
OS: linux
```

**Comment by stmcginnis** [comment]
I believe including `amiFamily: Bottlerocket` triggers a different path that avoids this error message. Can you give that a shot @jpmcb?

**Comment by Himangini** [comment]
@jpmcb Please see https://eksctl.io/usage/custom-ami-support/ for more details.

**Comment by jpmcb** [comment]
Great suggestion @stmcginnis - adding `amiFamily` succeeded. Tested with `eksctl.yaml`:

```yaml
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-cluster-1
  region: us-west-2
  version: '1.24'

nodeGroups:
  - name: ng-bottlerocket
    instanceType: m5.large
    desiredCapacity: 2
    ami: ami-abc123
    amiFamily: bottlerocket
    iam:
       attachPolicyARNs:
          - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
          - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
          - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
          - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
    bottlerocket:
      settings:
        motd: "Hello from eksctl!"
```

which resulted in

```
❯ k get nodes -A
NAME                                          STATUS   ROLES    AGE     VERSION
ip-192-168-43-76.us-west-2.compute.internal   Ready    <none>   2m48s   v1.24.9-eks-4f83af2
ip-192-168-94-85.us-west-2.compute.internal   Ready    <none>   2m52s   v1.24.9-eks-4f83af2
```

---

Thanks for the reply @Himangini - I'm not seeing any helpful documentation on getting bottlerocket custom AMIs to work on that page or mention of having to _also_ set `amiFamily`. The following:

> In a future as yet undecided release unmanaged nodegroups created with custom AmazonLinux2 or custom Ubuntu images will need to have the overrideBootstrapCommand configuration option set. This is to ensure that nodes are able to join the cluster.

Makes me think that this should still work for bottlerocket since it only mentions AmazonLinux2 and Ubuntu images.

Can the docs be updated to make this more clear?
