### ISSUE TITLE
[Feature] Support external-secets in `nodeGroups.iam.withAddonPolicies`

### ISSUE THREAD

**Issue by brsolomon-deloitte** [weaveworks/eksctl#6149]
### What feature/behavior/change do you want?

Add a supported add-on policy for external-secrets-operator to fetch secrets from AWS Secrets Manager.

```yaml
nodeGroups:
  - name: ng-1
    iam:
      withAddonPolicies:
        externalSecrets: true
```
Links:

- https://external-secrets.io/v0.7.1/
- https://eksctl.io/usage/iam-policies/?h=role#supported-iam-add-on-policies
- https://external-secrets.io/v0.7.1/provider/aws-secrets-manager/
