### ISSUE TITLE
[Help] Managed Windows Node Groups creating Linux nodes?

### ISSUE THREAD

**Issue by dan-tw** [weaveworks/eksctl#6158]
### What help do you need?

I'm currently creating a new cluster to test out Managed Windows Node Groups by doing the following: 

```yaml
# cluster.yaml
# An example of ClusterConfig containing Windows and Linux node groups to support Windows workloads
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: windows-cluster
  region: ap-southeast-2

managedNodeGroups:
  - name: windows-managed-ng
    amiFamily: WindowsServer2022FullContainer
    instanceType: g4dn.2xlarge
    minSize: 1
    maxSize: 1
```

Using the following version of eksctl: `0.125.0`

The result is a cluster with a single Managed Node group that is running an Amazon Linux 2 EKS node (AMI ID: `ami-0760f8e90a1753cfa`) running kubernetes 1.24

I would've thought that the above config would create a Windows Managed Node Group?

eksctl output also states that it is enabling Windows IP addressing, so it must've registered the AMI Family:

```
2023-01-16 15:52:26 [ℹ]  
2 sequential tasks: { create cluster control plane "windows-cluster", 
    2 sequential sub-tasks: { 
        2 sequential sub-tasks: { 
            wait for control plane to become ready,
            enable Windows IP address management,
        },
        create managed nodegroup "windows-managed-ng",
    } 
}
```

Any idea what's gone wrong?
