### ISSUE TITLE
[Bug] VPC Private subnets incorrectly attached to IGW instead of EIGW

### ISSUE THREAD

**Issue by hajdukda** [weaveworks/eksctl#6200]
### What were you trying to accomplish?
eks create cluster -f cluster.yaml

### What happened?
Created private subnets with IPv6 enabled are not real Private Subnets as defined here:
https://aws.amazon.com/premiumsupport/knowledge-center/configure-private-ipv6-subnet/
They have regular IGW attached instead of Egress-only-IGW

### How to reproduce it?
VPC Config:
```
vpc:
  cidr: "10.111.0.0/16"
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
  publicAccessCIDRs: [... w/e ip]
  nat:
    gateway: HighlyAvailable
  autoAllocateIPv6: true
```

**Logs**
N/A

**Anything else we need to know?**
OS - MacOS Ventura

**Versions**
```
eksctl version: 0.125.0
kubectl version: v1.25.2
OS: darwin
```

**Comment by TiberiuGC** [comment]
Hi @hajdukda , please bear with me while I try to reproduce this 🙏 .

Could you share a full config file example? And/or some screenshoots/details of how you configure your subnets on AWS console?

Thanks!

**Comment by hajdukda** [comment]
I have to redact few things but the config looks more or less like this:
```
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: "some-services"
  region: "eu-west-1"
  version: "1.22"

iam:
  withOIDC: true
  serviceAccounts: ....

vpc:
  cidr: "10.211.0.0/16"
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
  publicAccessCIDRs: [".....", "......"]
  nat:
    gateway: HighlyAvailable
  autoAllocateIPv6: true

cloudWatch:
  clusterLogging:
    enableTypes: ["audit", "authenticator", "controllerManager"]

secretsEncryption:
  keyARN: "arn:aws:kms:...."

availabilityZones: ["eu-central-1a", "eu-central-1b", "eu-central-1c"]

nodeGroups:
- name: some-services-default-v3-a
  ...
```
We don't perform any additional setup for VPCs created by EKSCTL. The outcome is like this for created subnets:
![redacted](https://user-images.githubusercontent.com/117656635/215067205-f61e102e-75fb-4a95-9d28-822694588e01.png)

As expected this renders this subnet as useless for manage-node-groups till we manually migrate it to EIGW.
