### ISSUE TITLE
[Feature] support price-capacity-optimized spot allocation strategy

### ISSUE THREAD

**Issue by norby-noah** [weaveworks/eksctl#6203]
### What feature/behavior/change do you want?

https://aws.amazon.com/blogs/compute/introducing-price-capacity-optimized-allocation-strategy-for-ec2-spot-instances/

A new spot allocation strategy has been released, price-capacity-optimized. I would like this to be supported as an option in my cluster config like so:
```yaml
nodeGroups:
  - name: spot-xlarge-v1.0.0
    availabilityZones: ["us-east-1a", "us-east-1b"]
    instanceTypes: ["m6a.xlarge", "m6i.xlarge", "m5.xlarge"]
    instancesDistribution:
      spotAllocationStrategy: price-capacity-optimized
```

### Why do you want this feature?

I would like to use the new allocation strategy provided by AWS. It better suits my spot instance allocation needs.
