### ISSUE TITLE
Enable ASG Metrics Collection for Managed Nodegroups

### ISSUE THREAD

**Issue by trombini77** [weaveworks/eksctl#6224]
### What help do you need?

I´m using the eksctl version `0.127.0` and I see in [documentation](https://eksctl.io/usage/managing-nodegroups/) that unmanaged nodegroup has the option to enable the Auto Scaling Group Metrics. Still, it is possible to enable it in managed nodegroups too as is possible to see in the following screens after created a managed nodegroup:

![image](https://user-images.githubusercontent.com/13336060/215660113-393e00d1-df63-4d38-892d-644a44aa1ed3.png)

![image](https://user-images.githubusercontent.com/13336060/215660139-899a9ef5-0034-49e7-87de-f87411ecfff3.png)

Here is the unmanaged nodegroup block that enables the feature:
```
    asgMetricsCollection:
      - granularity: 1Minute
        metrics:
          - GroupMinSize
          - GroupMaxSize
          - GroupDesiredCapacity
          - GroupInServiceInstances
          - GroupPendingInstances
          - GroupStandbyInstances
          - GroupTerminatingInstances
          - GroupTotalInstances
```

PS. What is possible to see in the screens is a simple flag (turn on/off) without the need to set each metric as unmanaged nodegroup uses. So I believe that this [blog post from AWS](https://aws.amazon.com/pt/blogs/containers/automatically-enable-group-metrics-collection-for-amazon-eks-managed-node-groups/) that shows how to activate it when used `aws eks create-nodegroup` with `--tags ASG_METRICS_COLLLECTION_ENABLED=TRUE` to create a managed nodegroup maybe shows the way where the Golang AWS lib can do it, or not ¨\o/¨
