### ISSUE TITLE
Karpenter: failed to locate chart

### ISSUE THREAD

**Issue by itsironis** [weaveworks/eksctl#6229]
### What were you trying to accomplish?
Provision an EKS cluster with Karpeneter enabled.

### What happened?
Karpenter is failing to be installed.
### How to reproduce it?
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: crossplane-dev
  region: eu-central-1

iam:
  withOIDC: true

karpenter:
  version: 'v0.18.1' # Exact version must be provided
  createServiceAccount: true # default is false

managedNodeGroups:
  - name: managed-ng-1
    minSize: 1
    maxSize: 2
    desiredCapacity: 1
```

**Logs**

`Error: failed to install Karpenter: failed to install Karpenter chart: failed to locate chart: pulling from host public.ecr.aws failed with status code [manifests v0.18.1]: 403 Forbidden
`

**Anything else we need to know?**

**Versions**

```
eksctl version: 0.126.0
kubectl version: v1.25.2
OS: darwin
```
