### ISSUE TITLE
Create IAM role for ServiceAccounts without namespace limitation

### ISSUE THREAD

**Issue by artem-nefedov** [weaveworks/eksctl#6238]
### What were you trying to accomplish?

I am trying to create IAM role for ServiceAccounts (without creating ServiceAccount itself, as I specify `roleOnly: true`) during cluster creation, and I need it to not be limited to a specific namespace in cluster. 

### What happened?

Based on [this](https://github.com/weaveworks/eksctl/blob/main/pkg/cfn/builder/iam.go#L293) code line I assumed that specifying metadata.namespace as an empty string (or not specifying it at all) will achieve the result. The difference between `MakeAssumeRolePolicyDocumentWithServiceAccountConditions()` and `MakeAssumeRolePolicyDocument()` is only in that first one adds additional "subject" line to conditions in trust policy, while second one doesn't, which is exactly what I need.

However, instead the namespace just gets implicitly replaced with "default".

```
                create IAM role for serviceaccount "default/my-sa",
```

IAM role's trust policy will contain this line in conditions (which I don't want):

```
"oidc.eks.us-west-2.amazonaws.com/id/<oidc-issuer>:sub": "system:serviceaccount:default:my-sa"
```

Alternatively, if I don't specify "metadata" section at all in the manifest, it will instead throw an error:

```
Error: iam.serviceAccounts[10].name must be set
```

### How to reproduce it?

Run `eksctl create cluster` command with this manifest:

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: my-cluster
  region: us-west-2
  version: "1.24"

iam:
  withOIDC: true
  serviceAccounts:
  - roleOnly: true
    roleName: "eksctl-my-role-name"
    metadata:
      name: my-sa # not actually created
      namespace: ""
    attachPolicy:
      Version: "2012-10-17"
      Statement:
      - Effect: Allow
        Action:
        - "sts:AssumeRole"
        Resource: "*"
```

**Versions**
```
eksctl version 0.126.0
```

### Note

If trust policy was generated with "StringLike" instead of "StringEquals" in conditions, it would may be possible to specify `namespace: "*"`, and that would probably work too.
