### ISSUE TITLE
authconfigmap: command to manipulate aws auth configmap

### ISSUE THREAD

**Issue by rndstr** [weaveworks/eksctl#625]
PR #623 attempted to add a command to modify the auth configmap but its location and command hierarchy needs a bit more discussion.

The auth ConfigMap is in `kube-system` and named `aws-auth`. It contains various mappings of IAM/AWS entities to Kubernetes groups.

More information at
- https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html
- https://github.com/kubernetes-sigs/aws-iam-authenticator/blob/master/README.md#full-configuration-format

## A. command design
The command should provide the following invocations (with description of current implementation of feature)

- display the current config
- add a role by arn, username, and groups
  - no de-duplication with existing mappings (related to #544)
- remove a role by arn
  - remove a single role even if there are duplicates (see #544)
  - fail if role not found
- add an account number
  - de-duplicate
- remove an account number
  - fail if account number not found

Some ideas and the start of the discussion can be found in #623.

It seems like that the following fulfills most of our constraints:
```
eksctl get aws-auth
eksctl update aws-auth add-role <arn> --username <string> --groups <csv>
eksctl update aws-auth remove-role <arn>
eksctl update aws-auth add-account <number>
eksctl update aws-auth remove-account
```
some variations:
- `add => map && remove => unmap`
- `aws-auth => auth`

## B. command behavior

Further discussion can be had about changing the way commands behave:

- remove a role
  - TBD: remove by role arn only? or match username and groups?

**Comment by errordeveloper** [comment]
For the record, we have a712049 that reverted the first implementation, so that can be reverted back.

**Comment by errordeveloper** [comment]
xref #62

**Comment by rndstr** [comment]
Somre more thoughts on naming 

- the flag `--update-auth-config-map` for `eksctl create|delete nodegroup` describes the same thing
- `iam-auth-bindings` has been [brought up](https://github.com/weaveworks/eksctl/pull/623#issuecomment-472229878) to bring it on par with upcoming IAM features

So more options
- `eksctl update iam-auth-bindings`
- `eksctl update iam-auth`
- `eksctl update auth-config-map`

**Comment by StevenACoffman** [comment]
If it is helpful, our use case is that we have four IAM roles: eksctl, read-only, developer, and admin. Our AWS accounts have no access rights except to assume one (or more) of those roles based on group membership.

When we create a new cluster, we have a horrible bash script that inserts into the aws-auth configmap a few lines after the line: `  mapRoles: |`:
```
    - rolearn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/${EKSCTL_ROLE}
      username: admin:{{AccountID}}:{{SessionName}}
      groups:
        - system:masters
    - rolearn: arn:aws:iam::594813696195:role/${ADMIN_ROLE}
      username: admin:{{AccountID}}:{{SessionName}}
      groups:
        - admins
    - rolearn: arn:aws:iam::594813696195:role/${EDIT_ROLE}
      username: editor:{{AccountID}}:{{SessionName}}
      groups:
        - editors
    - rolearn: arn:aws:iam::594813696195:role/${VIEW_ROLE}
      username: viewer:{{AccountID}}:{{SessionName}}
      groups:
        - viewers
```
The RBAC parts we can manage easily enough, but automated edits to that file are a real pain.
