### ISSUE TITLE
[Bug] max_pod.map does not contain AWS c6i family type breaking kubelet

### ISSUE THREAD

**Issue by ricarhincapie** [weaveworks/eksctl#6269]
### What were you trying to accomplish?

I created a self-managed nodegroup with AWS instance Type c6i.8xlarge and, in general for c6i family, with custom AMI.

### What happened?

The new nodes won't register with the cluster.
Kubelet in the nodes remains in `failed` state with `(code=exited, status=1/FAILURE)` after `systemctl restart kubelet.service`

### How to reproduce it?

Create a file with the following settings (you need to insert some fields yourself) and `eksctl create nodegroup -f foo-nodegroup.yaml`

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: REPLACE
  region: REPLACE

nodeGroups:
- name: REPLACE
  instanceType: c6i.8xlarge
  desiredCapacity: 0
  minSize: 0
  maxSize: 200
  ami: REPLACE(CUSTOM)
  privateNetworking: true
  iam:
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
      - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
    withAddonPolicies:
      autoScaler: true
      efs: true
      ebs: true
      externalDNS: true
  ssh:
    publicKeyName: REPLACE
  kubeletExtraConfig:
    kubeReserved:
      #cpu: "2"
      cpu: "300m"
      memory: "300Mi"
      ephemeral-storage: "1Gi"
    kubeReservedCgroup: "/kube-reserved"
    cpuManagerPolicy: static
    systemReserved:
      #cpu: "2"
      cpu: "300m"
      memory: "300Mi"
      ephemeral-storage: "1Gi"
    evictionHard:
      memory.available:  "200Mi"
      nodefs.available: "10%"
  tags:
    removed for simplicity...
```

**Logs**

```
journalctl -u kubelet

Feb 07 22:05:58 ... kubelet[5953]: E0207 22:05:58.814258    5953 server.go:156] "Failed to parse kubelet flag" err="invalid argument \"\" for \"--max-pods\" flag: strconv.ParseInt: parsing \"\": invalid syntax"
```

**Anything else we need to know?**

This issue happens also with c5n.metal instance type family: https://github.com/weaveworks/eksctl/issues/2563

Fast fix is to ssh into the unregistered machine and
```
sudo sed -i 's/MAX_PODS=/MAX_PODS=110/g /etc/eksctl/kubelet.local.env
```
or to check in the available instances types some other that works for you:
```
cat /etc/eksctl/max_pods.map
```

**Versions**

```
$ eksctl info
eksctl version: 0.88.0
kubectl version: v1.22.3
OS: linux
```
