### ISSUE TITLE
[Bug] scaling nodegroups in supported versions fails with permissions denied on old AMIs 

### ISSUE THREAD

**Issue by doctorpangloss** [weaveworks/eksctl#6319]
### What were you trying to accomplish?
I tried to scale a nodegroup on a cluster created a while ago and it failed.

eksctl has to gracefully deal with AMIs referenced in autoscaling group stacks being deprecated by new builds, even though the actual configuration is still supported.

### What happened?
Eventually, I discovered in the AWS autoscaling group events the following error message:
```
Launching a new EC2 instance. Status Reason: Not authorized for images: [ami-05313a4fc749aa64f]. Launching EC2 instance failed.
```

### How to reproduce it?

 1. Create a cluster with a Windows node group.
 2. Wait 6 months.
 3. Try to scale the node group up.
 4. Observe an AMI error because sometimes AWS deprecates the AMI images without warning, even though the configuration is supported.
 5. Duplicate the node group configuration.
 6. Observe `eksctl create nodegroup -f newgroup.yaml` succeeds.

**Logs**

eksctl actually shows no errors in this event because it never waits for Windows node groups to scale.

**Anything else we need to know?**

Here is an example nodegroup:
```yaml
nodeGroups:
  - name: gpu-windows-ng-03
    instanceType: g5.4xlarge
    privateNetworking: false
    availabilityZones:
      - us-west-2a
      - us-west-2b
      - us-west-2c
    minSize: 0
    desiredCapacity: 0
    maxSize: 8
    volumeSize: 100
    amiFamily: WindowsServer2019CoreContainer
    labels:
      role: gpu-worker
    preBootstrapCommands:
      - "& Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('my-bootstrapping-script.ps1'))"
    ssh:
      allow: true
      publicKey: 'my-publickey'
    containerRuntime: containerd
```
Duplicating this nodegroup worked around the problem.

**Versions**

```
eksctl version: 0.115.0
kubectl version: v1.25.3
OS: windows
```
