### ISSUE TITLE
[help] flux binary is required when gitops configuration is set:

### ISSUE THREAD

**Issue by mkarthiatgithub** [weaveworks/eksctl#6335]
First timer, hence be kind :) 

### What were you trying to accomplish?

enable fluxv2 while creating cluster using eksclt in cloud shell 

### What happened?

```
[cloudshell-user@ip- ~]$ eksctl create cluster --config-file gitops.yml 
2023-02-22 20:31:03 []  eksctl version 0.130.0
2023-02-22 20:31:03 []  using region eu-west-2
Error: flux binary is required when gitops configuration is set: exec: "flux": executable file not found in $PATH
[cloudshell-user@ip-~]$ 
```

### How to reproduce it?
Use this config file 

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name:cluster-test
  region: eu-west-2
iam:
  withOIDC: true
gitops:
  flux:
    gitProvider: "gitlab"
    flags:
      owner: MEME
      repository: MYOWNREPO
      branch: f-eksctl-flux-repo
      namespace: "flux-system"
      path: "k8s/resources/base/default"
      read-write-key: "true"
```
in AWS cloud shell, run 
 eksctl create cluster --config-file gitops.yml 

**Versions**

```
$ eksctl info
[cloudshell-user@ip-~]$ eksctl info
eksctl version: 0.130.0
kubectl version: v1.24.7-eks-fb459a0
OS: linux
```
