### ISSUE TITLE
[Help] GetOpenIDConnectProvider API is called due to addons creation code

### ISSUE THREAD

**Issue by Taehoon-terry-Kim** [weaveworks/eksctl#6395]
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-1-24-test-4
  region: ap-northeast-2
  version: "1.24"
iam:
 withOIDC: false
vpc:
  clusterEndpoints:
    privateAccess: true
    publicAccess: true
addons:
- name: coredns
- name: vpc-cni
- name: kube-proxy
cloudWatch:
  clusterLogging:
    enableTypes: [ "api", "audit", "authenticator", "controllerManager", "scheduler" ]
managedNodeGroups:
  - name: managed-ng-1
    minSize: 2
    maxSize: 4
    desiredCapacity: 3
```

When create a cluster using the above ClusterConfig on the private network that cannot communicate with the IAM endpoint, the cluster creation is failed.

Error
```
operation error IAM: GetOpenIDConnectProvider, https response error StatusCode: 0, RequestID: , request send failed, Post "[https://iam.amazonaws.com/ ](https://iam.amazonaws.com/)": dial tcp 52.94.225.3:443: i/o timeout
```

GetOpenIDConnectProvider API called even though the addon has no policy-related or serviceAccountRoleARN codes.

If there is no add-on creation code, the cluster creation succeeds.

Do I have to create an OIDC Provider to create add-ons using eksctl?
