### ISSUE TITLE
[Bug] Segmentation Fault

### ISSUE THREAD

**Issue by Almenon** [weaveworks/eksctl#6441]
### What were you trying to accomplish?

`eksctl create nodegroup --config-file=cluster.yaml --include='spot-exp-high-mem-1a'`

### What happened?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1072aaa1c]

goroutine 1 [running]:
github.com/weaveworks/eksctl/pkg/apis/eksctl.io/v1alpha5.(*ClusterConfig).GetAllNodeGroupNames(...)
	/private/tmp/eksctlA0.130.0-20230317-25547-1wq5mb5/pkg/apis/eksctl.io/v1alpha5/nodegroups.go:77
github.com/weaveworks/eksctl/pkg/ctl/cmdutils.NewCreateNodeGroupLoader.func2()
	/private/tmp/eksctlA0.130.0-20230317-25547-1wq5mb5/pkg/ctl/cmdutils/configfile.go:414 +0x7c
github.com/weaveworks/eksctl/pkg/ctl/cmdutils.(*commonClusterConfigLoader).Load(0x14000af2d80)
	/private/tmp/eksctlA0.130.0-20230317-25547-1wq5mb5/pkg/ctl/cmdutils/configfile.go:152 +0x248
github.com/weaveworks/eksctl/pkg/ctl/create.createNodeGroupCmd.func1(0x1400003fd40, 0x1400003fe00, {{0x1, 0x1, 0x0}, {0x1, 0x0, {0x0, 0x0, 0x0}}, ...})
	/private/tmp/eksctlA0.130.0-20230317-25547-1wq5mb5/pkg/ctl/create/nodegroup.go:43 +0x1bc
github.com/weaveworks/eksctl/pkg/ctl/create.createNodeGroupCmdWithRunFunc.func1(0x14000808300?, {0x1400036cce0?, 0x0?, 0x2?})
	/private/tmp/eksctlA0.130.0-20230317-25547-1wq5mb5/pkg/ctl/create/nodegroup.go:97 +0xd0
github.com/spf13/cobra.(*Command).execute(0x14000808300, {0x1400036ccc0, 0x2, 0x2})
	/Users/calebparks/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x5c4
github.com/spf13/cobra.(*Command).ExecuteC(0x1400091af00)
	/Users/calebparks/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x340
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/calebparks/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
	/private/tmp/eksctlA0.130.0-20230317-25547-1wq5mb5/cmd/eksctl/main.go:102 +0x508
```

### How to reproduce it?

1. Install eksctl 0.130.0
2. Create the below config file
3. Spin up a EKS Cluster
4. Run `eksctl create nodegroup --config-file=cluster.yaml --include='spot-exp-high-mem-1a'`

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: mystery
  version: "1.21"
  region: us-east-1
  tags:
    DatadogMonitoring: "False"
    Cost-Center: "mystery"
    Service-Type: "eks-cluster"
    Environment: "Dev-Test"
    Owner: "Bob the anonymous mystery man"
    Description: "its a mystery"

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
vpc:
  # Created in "Processing" vpc - vpc-0cf362ace80abe38e
  clusterEndpoints:
    publicAccess: true
  nat:
    gateway: Disable
  subnets:
    public:
      us-east-1a: { id: subnet-07e8ec1ec4e776fe4 }
      us-east-1b: { id: subnet-018a2ac4206c3c6df }
      us-east-1c: { id: subnet-0e41efbcf2d6c92a9 }
      us-east-1d: { id: subnet-0792a01dea97e5093 }

nodeGroups:
  #######################################################################
  # Experiment node-group ondemand-exp-high-mem
  #######################################################################
  -
  - name: ondemand-exp-high-mem-1a
    availabilityZones: ["us-east-1a"]
    minSize: 0
    maxSize: 1000
    desiredCapacity: 0
    volumeSize: 64
    iam:
      withAddonPolicies:
        efs: true
    ssh:
      publicKeyName: ispot-emr
    instancesDistribution:
      instanceTypes: [ "r6in.8xlarge", "r6idn.8xlarge" ]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 100
      spotAllocationStrategy: capacity-optimized
    taints:
    labels:
      nodegroup-name: "ondemand-exp-high-mem-1a"
      on-demand: "true"
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/conversions-dev: "true"
      k8s.io/cluster-autoscaler/node-template/label/on-demand: "true"
      k8s.io/cluster-autoscaler/node-template/label/nodegroup-name: "ondemand-exp-high-mem-1a"
      k8s.io/cluster-autoscaler/node-template/label/DatadogMonitoring: "False"
      k8s.io/cluster-autoscaler/node-template/label/Cost-Center: "Mystery"
      k8s.io/cluster-autoscaler/node-template/label/Service-Type: "eks-node-spot"
      k8s.io/cluster-autoscaler/node-template/label/Environment: "Dev-Test"
      k8s.io/cluster-autoscaler/node-template/label/Owner: "Bob the anonymous mystery man"
      k8s.io/cluster-autoscaler/node-template/label/Description: "its a mystery"

```

**Logs**

No logs, it immediately crashes

**Anything else we need to know?**

macOS, I downloaded via brew

**Versions**

```
$ eksctl info
eksctl version: 0.130.0-dev+6aa905e1a.2023-03-17T23:16:48Z
kubectl version: v1.26.2
OS: darwin
```
I haven't tested the latest version `0.134.0` because that doesn't support our EKS cluster version.
