### ISSUE TITLE
[Bug] Managed nodegroup creation fails with Ubuntu AMIs and GPU instances

### ISSUE THREAD

**Issue by JamesMaki** [weaveworks/eksctl#6499]
### What were you trying to accomplish?
Allow creation of managed nodegroups with Ubuntu AMIs when selecting a GPU instance.

There are two parts of this request:
* Allow creation of Ubuntu managed nodegroups in eksctl for GPU instances. This is supported today for CPU instances.

The [NVIDIA GPU Operator version 23.3.0 now officially supports EKS when using Ubuntu 20.04 AMIs](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/release-notes.html). 

This will provide a quick and easy way to create a managed GPU nodegroup with updated GPU drivers (driver version 525.85.12). The current GPU driver version in the Amazon Linux 2 AMI is 470.161.03.

### How to reproduce it?

NOTE: The below cluster.yaml file works if you change the nodegroup to a CPU instance such as `m5.large`. We request that this be expanded to support all GPU instances as well.

Example cluster.yaml

```yaml
# cluster.yaml
# A cluster with a managed Ubuntu nodegroup.
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-cluster
  region: us-west-2

managedNodeGroups:
  - name: gpu-nodegroup
    instanceType: g4dn.xlarge
    amiFamily: Ubuntu2004
    minSize: 1
    desiredCapacity: 1
    maxSize: 1
```
Currently there is the expected warning that Ubuntu2004 does not ship with NVIDIA GPU drivers installed, but following this warning there is an error and cluster creation is terminated.

**Logs**
```shell
 $ eksctl create cluster --install-nvidia-plugin=false --config-file cluster.yaml 
2023-03-20 20:50:00 [!]  Ubuntu2004 does not ship with NVIDIA GPU drivers installed, hence won't support running GPU-accelerated workloads out of the box
2023-03-20 20:50:00 [ℹ]  eksctl version 0.136.0
2023-03-20 20:50:00 [ℹ]  using region us-west-2
2023-03-20 20:50:00 [ℹ]  skipping us-west-2d from selection because it doesn't support the following instance type(s): g4dn.xlarge
2023-03-20 20:50:00 [ℹ]  setting availability zones to [us-west-2a us-west-2c us-west-2b]
2023-03-20 20:50:00 [✖]  image family Ubuntu2004 doesn't support GPU image class
```

**Anything else we need to know?**
Using downloaded eksctl binary in AWS Cloudshell.

To use the GPU operator in eksctl currently the user must specify an un-managed nodegroup, hard-code the ami-id for the correct Ubuntu 20.04 AMI they want to use, and specify the overrideBootstrapCommand field. 

Below is a working example:

```yaml
# cluster.yaml
# A cluster with a self-managed Ubuntu nodegroup.
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-cluster
  region: us-west-2

nodeGroups:
  - name: gpu-nodegroup
    instanceType: g4dn.xlarge
    amiFamily: Ubuntu2004
    # grab AMI ID for Ubuntu EKS AMI here: https://cloud-images.ubuntu.com/aws-eks/
    # using AMI ID for us-west-2 region: ami-06cd6fdaf5a24b728
    ami: ami-06cd6fdaf5a24b728
    minSize: 1
    desiredCapacity: 1
    maxSize: 1
    overrideBootstrapCommand: |
      #!/bin/bash
      source /var/lib/cloud/scripts/eksctl/bootstrap.helper.sh
      /etc/eks/bootstrap.sh ${CLUSTER_NAME} --container-runtime containerd --kubelet-extra-args "--node-labels=${NODE_LABELS}"
```
```shell
 $ eksctl create cluster --install-nvidia-plugin=false --config-file cluster.yaml 
```
Install the NVIDIA GPU Operator via Helm chart.
```shell 
$ helm install --repo https://helm.ngc.nvidia.com/nvidia --wait --generate-name -n gpu-operator \
      --create-namespace gpu-operator --set driver.version="525.85.12"
NAME: gpu-operator-1670843572
NAMESPACE: gpu-operator
STATUS: deployed
REVISION: 1
TEST SUITE: None
```
Wait until all pods are deployed (~6-7 minutes or so). This will add GPU drivers and the GPU device plugin.

```shell
watch -n 5 kubectl get pods -n gpu-operator

#Completed after about 7 minutes in testing
Every 5.0s: kubectl get pods -n gpu-operator                                                                                                                                                                                                                                                                                       

NAME                                                              READY   STATUS      RESTARTS   AGE                                                                                                                                                                                                                                                                  
gpu-feature-discovery-sk42n                                       1/1     Running     0          6m34s
gpu-operator-1679256184-node-feature-discovery-master-5cfdc2bx9   1/1     Running     0          7m2s
gpu-operator-1679256184-node-feature-discovery-worker-n8k9v       1/1     Running     0          7m2s
gpu-operator-79f94979f9-trnlp                                     1/1     Running     0          7m2s
nvidia-container-toolkit-daemonset-zp8wb                          1/1     Running     0          6m34s
nvidia-device-plugin-daemonset-djjqf                              1/1     Running     0          6m34s
nvidia-driver-daemonset-nw7h7                                     1/1     Running     0          6m43
```
Filename: `nvidia-smi.yaml`
```yaml
# nvidia-smi.yaml
apiVersion: v1
kind: Pod
metadata:
  name: nvidia-smi
spec:
  restartPolicy: OnFailure
  containers:
  - name: nvidia-smi
    image: ubuntu:22.04
    args:
    - "nvidia-smi"
    resources:
      limits:
        nvidia.com/gpu: 1
```

```shell
$ kubectl apply -f nvidia-smi.yaml
$ kubectl logs nvidia-smi
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: N/A      |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:1E.0 Off |                    0 |
| N/A   33C    P8     8W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Versions**
```
$ eksctl info
eksctl version: 0.136.0
kubectl version: v1.24.9-eks-49d8fe8
OS: linux
```
