### ISSUE TITLE
[Bug] Bottlerocket fails to boot if configured with public subnet and private subnet

### ISSUE THREAD

**Issue by robd003** [weaveworks/eksctl#6563]
### What were you trying to accomplish?
Tried to set up a cluster that has a public subnet and private subnet while using Bottlerocket.

### What happened?
Bottlerocket fails to boot with the following error: https://gist.github.com/robd003/7f05a5f76bf241f047a99ab3135f6a03

### How to reproduce it?
Example cluster config (listed only 1 AZ for brevity, probably won't start unless you have 2+):
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: bottlerocket-failure-cluster
  region: us-east-2
  version: '1.26'

vpc:
  clusterEndpoints:
    publicAccess:  true
    privateAccess: true
  id: "vpc-c4f3b4b3"
  subnets:
    public:
      pub-us-east-2a:
        id: "subnet-0000111"
    private:
      priv-us-east-2a:
        id: "subnet-0000222"

iam:
  withOIDC: true

nodeGroups:
  - name: east2a
    instanceType: m7g.xlarge
    amiFamily: Bottlerocket
    privateNetworking: true
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      withAddonPolicies:
        autoScaler: true
        cloudWatch: false
        externalDNS: true
    maxSize: 4
    subnets:
      - pub-us-east-2a
      - priv-us-east-2a
    desiredCapacity: 1
```

The private subnets **do not** have NAT gateways

**Logs**
```
2023-04-30 23:44:50 [ℹ]  waiting for at least 1 node(s) to become ready in "east2a"
Error: timed out waiting for at least 1 nodes to join the cluster and become ready in "east2a": context deadline exceeded
```

When looking at the instances they all fail like this: https://gist.github.com/robd003/7f05a5f76bf241f047a99ab3135f6a03

**Anything else we need to know?**
Downloaded binary from GitHub, running on macOS 13.3.1

**Versions**
0.139.0
```
$ eksctl info
eksctl version: 0.139.0-dev+37584337f.2023-04-28T12:38:17Z
kubectl version: v1.27.1
OS: darwin
```
