### ISSUE TITLE
[Feature] Provision Karpenter node role by including iam section in cluster_config file.

### ISSUE THREAD

**Issue by srikanthgv88** [weaveworks/eksctl#6745]
When new cluster is provisioned through EKSCTL module, karpenter can be installed automatically by enabling few parameters in the cluster config file. In our case karpenter installation failed with eksctl, as permission boundary is not defined on karpenter roles in cluster_config yaml definition.

Currently managed node group can be created via EKSCTL by passing cluster_config file in which required iam policies and permission boundaries can be attached to eksctl Node role[Code block -1 ]. Looking for similar feature to include iam section in Karpenter configuration[Code block -2].

[Code block -1]
```
managedNodeGroups:
- name: "mngtest"
  desiredCapacity: 1
  minSize: 1
  maxSize: 3
  privateNetworking: true
  #EC2 tags required for cluster-autoscaler auto-discovery
  iam:
    attachPolicyARNs:
    - "arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM"
    - "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"
    - "arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy"
    - "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
    - "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
    instanceRolePermissionsBoundary: "arn:aws:iam::xxxxxxx:policy/xxxRolesPermissionsBoundary"]

```
[Code block -2]
```
  karpenter:
  version: 'v0.20.0'
  iam:
    attachPolicyARNs:
    - "arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM"
    - "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"
    - "arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy"
    - "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
    - "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
    instanceRolePermissionsBoundary: "arn:aws:iam::xxxxxxx:policy/xxxxxRolesPermissionsBoundary" 
 ```

It is another git hub issue which talks about installation of karpenter on existing cluster using eksctl.  we would also need this feature request to be enabled in eksctl module. 

https://github.com/weaveworks/eksctl/issues/6494

**Comment by TiberiuGC** [comment]
Hi @srikanthgv88, if setting `permissionsBoundary` is what makes your `Karpenter` installation fail, you can specify it at cluster level and the value will simply be copied at `Karpenter` Role level.

https://github.com/weaveworks/eksctl/blob/e9a6c8a4b68368ed3ee491c005ede225a1e2756d/pkg/cfn/builder/karpenter.go#L132-L134 

As for policies, what `eksctl` does at the moment is, it attaches the following by default

https://github.com/weaveworks/eksctl/blob/e9a6c8a4b68368ed3ee491c005ede225a1e2756d/pkg/cfn/builder/karpenter.go#L116-L122

Could you please help me understand your use case for having the `iam` subsection under `Karpenter` settings in config file? Perhaps provide some practical example?

**Comment by srikanthgv88** [comment]
My use case is, Permission boundary should be exist for any role created in our organization. When eksctl is creating roles for karpenter CFT is failing  with error message "No permission boundary is defined on the role". Hence we are looking for including iam subsection in karpenter. 

Steps to Reproduce the issue:
1) Create permission policy with below content
   ``` {
    "Version": "2012-10-17",
    "Statement": [
       {
            "Condition": {
                "StringEquals": {
                    "iam:PermissionsBoundary": "arn:aws:iam::xxxxx:policy/MiddlewareCreatedRolesPermissionsBoundary"
                }
            },
            "Action": [
                "iam:CreateRole",
                "iam:PutRolePermissionsBoundary"
            ],
            "Resource": [
                "arn:aws:iam::xxxxx:role/eks*NodeInstanceRole*",
                "arn:aws:iam::xxxxx:role/eks*NodeInstanceRole*",
                "arn:aws:iam::xxxxx:role/eksClusterRole",
                "arn:aws:iam::xxxxx:role/eksctl*"
            ],
            "Effect": "Allow",
            "Sid": "Createrole"
        }
    ]
}`

2) Create new eksctl cluster with karpenter enabled section and cloud stack should fail. 
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-with-karpenter
  region: us-west-2
  version: '1.24'
  tags:
    karpenter.sh/discovery: cluster-with-karpenter # here, it is set to the cluster name
iam:
  withOIDC: true # required

karpenter:
  version: 'v0.20.0' # Exact version must be specified

managedNodeGroups:
  - name: managed-ng-1
    minSize: 1
    maxSize: 2
    desiredCapacity: 1
```

**Comment by Himangini** [comment]
@srikanthgv88 Thanks for the info, can you provide the logs you see for Step 2 failing pls?
Also OOC have you tried the following settings under the Karpenter section?
```yaml
karpenter:
  version: 'v0.20.0'
  createServiceAccount: true # default is false
  defaultInstanceProfile: 'KarpenterNodeInstanceProfile' # default is to use the IAM instance profile created by eksctl
```
