### ISSUE TITLE
Authenticator should respect --profile

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#70]
As mentioned by @richardcase in https://github.com/weaveworks/eksctl/pull/66#issuecomment-398318393.

Authenticator doesn't support this at the moment (https://github.com/heptio/authenticator/issues/100), but it should be easy to fix.

**Comment by richardcase** [comment]
An temporary fix would be to set AWS_PROFILE from within eksctl. I'll try this out.

**Comment by richardcase** [comment]
And the error from the logs:
```bash
2018-06-19T20:15:52+01:00 [✖]  creating auth ConfigMap for DefaultNodeGroup: Unauthorized
```

**Comment by richardcase** [comment]
The second part to this is ensuring that if we specify `--profile` that we also write the profile to the kube config file so that kubectl works after cluster creation. This can be accomplished by saving the value of --profile as na env var:
```
apiVersion: v1
clusters:
- cluster:
    server: ${server}
    certificate-authority-data: ${cert}
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: aws
  name: aws
current-context: aws
kind: Config
preferences: {}
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: heptio-authenticator-aws
      env:
      - name: "AWS_PROFILE"
        value: "dev"
      args:
        - "token"
        - "-i"
        - "mycluster"
```
This can be done by a change to `WithExecHeptioAuthenticator`.
