### ISSUE TITLE
EKS v1.12

### ISSUE THREAD

**Issue by MilanDasek** [weaveworks/eksctl#709]
Hello,

how can I deploy EKS v1.12 using eksctl?

Here is my config:

```
apiVersion: eksctl.io/v1alpha4
kind: ClusterConfig

metadata:
  name: eks-production
  region: eu-west-1

tags:
  environment: production

node-volume-size: 100
node-ami: auto

nodeGroups:
  - name: ng1-eks-production
    instanceType: t3.medium
    minSize: 0
    maxSize: 0
    labels:
      lifecycle: Ondemand
      environment: production
      autoscaling: enabled
    iam:
      withAddonPolicies:
        autoScaler: true
        ExternalDNS: true
        ImageBuilder: true
        ebs: true
        fsx: true
        efs: true
    availabilityZones: ["eu-west-1a", "eu-west-1b", "eu-west-1c"]
    privateNetworking: true
    AllowSSH: true

vpc:
  id: "%ID%"
  cidr: "10.2.32.0/20"   
  subnets:
    private:
      eu-west-1a: {id: %ID%}
      eu-west-1b: {id: %ID%}
      eu-west-1c: {id: %ID%}
    public:
      eu-west-1a: {id: %ID%}
      eu-west-1b: {id: %ID%}
      eu-west-1c: {id: %ID%}
```

This deploys 1.11

Also node-volume-size is still 20GB, not 100.

Please advise.

Thank you

**Comment by errordeveloper** [comment]
Yes, but it's not the default yet. What you want is this:
```
apiVersion: eksctl.io/v1alpha4
kind: ClusterConfig

metadata:
  name: eks-production
  region: eu-west-1
  version: 1.12
```

**Comment by romil-punetha** [comment]
```
apiVersion: eksctl.io/v1alpha4
kind: ClusterConfig
metadata:
  name: eks-test
  region: ap-south-1
  version: "1.12"
  tags:
    version: test
    billing: core
    sub-billing : kubernetes
    environment: test
vpc:
  id: "vpc-xxxxxxxx" 
  cidr: "192.168.x.x/16"
  subnets:
    private:
      ap-south-1a:
          id: "subnet-xxxxxxxx"
          cidr: "192.168.x.x/24"
      ap-south-1b:
          id: "subnet-xxxxxxxx"
          cidr: "192.168.x.x/24"
    public:
      ap-south-1a:
          id: "subnet-xxxxxxx"
          cidr: "192.168.x.x/24"
      ap-south-1b:
          id: "subnet-xxxxxxxx"
          cidr: "192.168.x.x/24"
iam: 
  serviceRoleARN: "arn:aws:iam::xxxxxxxxxxx:role/EKS"
nodeGroups:
  - name: eks-spotinst
    labels: 
      applicationType: org,
      machineSize: mixed,
    instanceType: t2.xlarge
    desiredCapacity: 1
    ami: ami-09c3eb35bb3be46a4
    minSize: 1
    maxSize: 1
    volumeSize: 50
    volumeType: gp2
    privateNetworking: true
    maxPodsPerNode: 50
    allowSSH: true
    sshPublicKey: 'eks-bastion'
    availabilityZones: ["ap-south-1a", "ap-south-1b"]
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
```
