### ISSUE TITLE
`eksctl create cluster -f config.yaml` now fails with an error message

### ISSUE THREAD

**Issue by romil-punetha** [weaveworks/eksctl#725]
**What happened?**

Few hours ago, i was able to create a cluster with a yaml file as input. Now, its failing with the error message `loading config file "dev.yaml": error unmarshaling JSON: while decoding JSON: illegal base64 data at input byte 3`

**What you expected to happen?**
The cluster creation succeeds

**How to reproduce it?**
Try creating cluster with below yaml:
```
apiVersion: eksctl.io/v1alpha4
kind: ClusterConfig
metadata:
  name: eks-dev # Dev Cluster
  region: ap-south-1
  version: "1.12"
  tags:
    version: dev
    billing: core
    sub-billing : kubernetes
    environment: dev
vpc:
  id: "vpc-xxxxxxxx"
  cidr: "192.168.0.0/16"
  subnets:
    private:
      ap-south-1a:
          id: "subnet-xxxxxxxx"
          cidr: "192.168.16.0/20"
      ap-south-1b:
          id: "subnet-xxxxxxxx"
          cidr: "192.168.32.0/20"
    public:
      ap-south-1a:
          id: "subnet-xxxxxxxx"
          cidr: "192.168.0.0/24"
      ap-south-1b:
          id: "subnet-xxxxxxx"
          cidr: "192.168.3.0/24"
iam: 
  serviceRoleARN: "arn:aws:iam::xxxxxxxx:role/EKS"
nodeGroups:
  - name: eks-dev-worker-nodegroup
    labels:
      applicationType: dev
    instanceType: t2.xlarge
    desiredCapacity: 1
    ami: ami-09c3eb35bb3be46a4
    minSize: 1
    maxSize: 1
    volumeSize: 50
    volumeType: gp2
    privateNetworking: true
    maxPodsPerNode: 50
    allowSSH: true
    sshPublicKey: 'eks-dev'
    availabilityZones: ["ap-south-1a", "ap-south-1b"]
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
```

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.1.29"}

$ uname -a
Darwin CF-LP00253.local 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-12-06T01:33:57Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}

```

**Logs**
Include the output of the command line when running eksctl. If possible, eksctl should be run with debug logs. For example:
`eksctl get clusters -f dev.yaml`

` loading config file "dev.yaml": error unmarshaling JSON: while decoding JSON: illegal base64 data at input byte 3`
