### ISSUE TITLE
ServiceRole and NodeInstanceRole missing tags

### ISSUE THREAD

**Issue by cdenneen** [weaveworks/eksctl#750]
These roles are created (ServiceRole for cluster and NodeInstanceRole for the nodegroup) but neither has tags propagated to them.

**Comment by errordeveloper** [comment]
This maybe down to CloudFormation, but needs looking into for sure.

**Comment by errordeveloper** [comment]
So I just checked, and it appears that CloudFormation tags majority of the resources that we create, except for the aforementioned as well as EIP. I sort of recall looking into this a while back, it's one of those long-standing "bug".

Just checked the docs and neither [`AWS::EC2::EIP`](https://docs.amazonaws.cn/en_us/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-eip.html) nor [`AWS::IAM::Role`](https://docs.amazonaws.cn/en_us/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html) have `Tags` field exposed to CloudFormation...

**Comment by errordeveloper** [comment]
https://github.com/weaveworks/eksctl/issues/25 is related, but a different story - there the underlying API still doesn't support tags.

**Comment by ma-tty** [comment]
[AWS::IAM::Role](https://docs.amazonaws.cn/en_us/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html) has now Tags property exposed.

**Comment by whereisaaron** [comment]
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html#cfn-iam-role-tags
```
Type: AWS::IAM::Role
Properties: 
  AssumeRolePolicyDocument: Json
  Description: String
  ManagedPolicyArns: 
    - String
  MaxSessionDuration: Integer
  Path: String
  PermissionsBoundary: String
  Policies: 
    - Policy
  RoleName: String
  Tags: 
    - Tag
```

**Comment by jimsmith** [comment]
Hello,

Having deployed CF template using the IAM Roles 'tags' https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html#cfn-iam-role-tags

I have found that the `!Ref` is not being honored.

This below works when it's hardcoded
```
Tags:
        - 
          Key: "keyname1"
          Value: "value1"
        - 
          Key: "keyname2"
          Value: "value2"
```

This below is not working and the same Parameter works for EC2 and Lambda resources.

```
Tags:
        - Key: Application
          Value: !Ref 'Application'
        - Key: Application
          Value: !Ref 'Application'
```
