### ISSUE TITLE
Create S3 endpoints for VPC

### ISSUE THREAD

**Issue by jahpola-futurice** [weaveworks/eksctl#764]
Hi,

It would a nice addition that network creates at least VPC S3 endpoints optionally.

**Comment by errordeveloper** [comment]
hi @jahpola-futurice! I was wondering if we might need to create endpoints for APIs the that are being used by eksctl. S3 is actually not being used by eksctl itself yet, so I'm not sure if it'd be fair to add support for it before other APIs that one might use (DynamoDB, RDS, Lambda ...etc).
Wouldn't you want to add some S3 IAM role to your nodegroup(s) as well?

**Comment by jahpola-futurice** [comment]
Yes, we have either an instance profile or kube2iam setup that allows access to S3 buckets based on naming policy. The s3 bucket contains items which the container stores&reads items .

**Comment by errordeveloper** [comment]
I suppose one option to consider would be something like:

```yaml
vpc:
   withServiceEndpoints: [s3, dynamodb]
```

But I am not sure what to do about `PolicyDocument` here vs a nodegroup-level.

Another option could be this:

```yaml
vpc:
   endpoints:
     dynamodb:
     - "Sid": "Statement"
        "Action": "dynamodb:*"
        "Effect": "Allow"
        "Principal": "*"
```

But that means we will also need to allow inline policy documents in other places. A few things to think about here!
