### ISSUE TITLE
Why is this config failing when we supply "public" subnets?

### ISSUE THREAD

**Issue by kutchar** [weaveworks/eksctl#771]
CloudFormation fails at the ControlPlace step when give the following config but when we remove the "public" subnet it works. In addition, when we build the cluster without a "public" subnet using eksctl and then tag the "public" subnets manually, eksctl seems to work without any issues (creating pods, ...)

```
apiVersion: eksctl.io/v1alpha4
kind: ClusterConfig

metadata:
 name: some-cluster-name
 region: us-east-1
 
 vpc: 
  id: "vpc-XXXXXXXXX"
  cidr: "10.0.0.0/16"
  subnets:
          private:
                  us-east-1a:
                          id: "subnet-XXXXXXXXX"
                          cidr: "10.0.0.0/24"
                  us-east-1b:
                          id: "subnet-XXXXXXXXX"
                          cidr: "10.0.1.0/24"
          public:
                  us-east-1a:
                          id: "subnet-XXXXXXXXX"
                          cidr: "10.0.200.0/24"
                  us-east-1b:
                          id: "subnet-XXXXXXXXX"
                          cidr: "10.0.201.0/24"

nodeGroups:
  - name: some-name
    instanceType: t2.medium
    ami: ami-0528122378918889b
    amiFamily: Ubuntu1804
    privateNetworking: true
    minSize: 2
    maxSize: 4
    desiredCapacity: 2
    allowSSH: true
    volumeSize: 100
    volumeType: gp2 
    availabilityZones: ["us-east-1a","us-east-1b"] 
    labels:
        nodegroup: lg
        cluster: some-cluster-name
    iam:
     withAddonPolicies:
       autoScaler: true
```
