### ISSUE TITLE
[Feature] add nodeadm merge functionality for AL2023 MNG

### ISSUE THREAD

**Issue by youwalther65** [weaveworks/eksctl#8043]
### What feature/behavior/change do you want?

I want to be able to create an AL2023 managed node group (MNG) with custom nodeadm data like
```yaml
managedNodeGroups:
...
- name: mng-custom-AL2023
  minSize: 1
  maxSize: 2
  desiredCapacity: 2
  instanceTypes: [ "m6gd.large", "m7gd.large" ]
  amiFamily: AmazonLinux2023
  ami: ami-xxx
  overrideBootstrapCommand: |
    MIME-Version: 1.0
    Content-Type: multipart/mixed; boundary="BOUNDARY"

    --BOUNDARY
    Content-Type: application/node.eks.aws

    ---
    apiVersion: node.eks.aws/v1alpha1
    kind: NodeConfig
    spec:
      instance:
        localStorage:
          strategy: RAID0

    --BOUNDARY
  updateConfig:
    maxUnavailable: 1
```
Currently I am getting an error stating:
```bash
$ eksctl create nodegroup -f eksctl-NVME-AL2023.yaml
Error: could not create cluster provider from options: managedNodeGroups[1].overrideBootstrapCommand is not supported when using a custom AMI based on AmazonLinux2023 (managedNodeGroups[1].ami)
```
I have expected, that ***eksctl*** would merge the custom nodeadm data with the ones it creates per default (cluster specification).

### Why do you want this feature?

Using advanced nodeadm features allow customization of for example node local storage to move kubelet and containerd related stuff to NVME based devices for segregation and enhanced performance.
