### ISSUE TITLE
cannot unmarshal array into Go struct field ClusterConfig.metadata of type v1alpha5.ClusterMeta

### ISSUE THREAD

**Issue by kiahmed** [weaveworks/eksctl#860]
**What help do you need?**
what is this error about have about..trying to create a node group on an existing cluster with the following yaml ?
 error unmarshaling JSON: while decoding JSON: json: cannot unmarshal array into Go struct field ClusterConfig.metadata of type v1alpha5.ClusterMeta
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  - name: my-clstr
    region: us-east-1
nodeGroups:
  - name: ob-worker-group
    labels: {pool: master-t3-public}
    instanceType: t3.medium
    amiFamily: Ubuntu1804
    desiredCapacity: 1
    minSize: 1
    maxSize: 10
    volumeSize: 50
    volumeType: gp2
    privateNetworking: true
    iam: 
      serviceRoleARN: "arn:aws:iam::xxxxxxxx:role/aw-service-role"
    ssh:
      allow: true
      publicKeyName: 'my-keypair'
    tags:
      'environment:basedomain': 'ss.com'
```

**Comment by errordeveloper** [comment]
Yes, it's not an array. This is what you want to use:
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
    name: my-clstr
    region: us-east-1
```
