### ISSUE TITLE
Update cluster not respecting version in config-file / automatically upgrading control plane

### ISSUE THREAD

**Issue by dhanvi** [weaveworks/eksctl#915]
**What happened?**
eksctl automatically upgraded the control plan version while doing `eksctl update cluster`

**What you expected to happen?**
Not upgrade the control plane version unless asked for.

**How to reproduce it?**
`eksctl create cluster -f eks_config.yaml` with config as 

```yaml
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: us-east-1-prod-eks
  region: us-east-1
  version: "1.12"

vpc:
  cidr: "10.0.0.0/16"
```
and then try to update cluster with `eksctl update cluster -f eks_config.yaml`

```
[ℹ]  using region us-east-1
[!]  NOTE: config file is only used for finding cluster name and region, deep cluster configuration changes are not yet implemented
[ℹ]  re-building cluster stack "eksctl-us-east-1-prod-eks-cluster"
[✔]  all resources in cluster stack "eksctl-us-east-1-prod-eks-cluster" are up-to-date
[ℹ]  (plan) would upgrade cluster "us-east-1-prod-eks" control plane from current version "1.12" to "1.13"
[!]  no changes were applied, run again with '--approve' to apply the changes
```

Related #909
