### ISSUE TITLE
add a CLI option to enable policies on the worker nodes (e.g. for ECR)

### ISSUE THREAD

**Issue by jstrachan** [weaveworks/eksctl#92]
we're using eksctl in `jx create cluster eks` and its working well - many thanks!. 

However it'd be even more awesome if we could add a CLI option to be able to enable the `arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPowerUser` policy on the worker nodes; so that nodes are able to push to ECR. Then we can use ECR OOTB in Jenkins X on clusters created via `eksctl`

**Comment by errordeveloper** [comment]
We don't have a way to augment CloudFormation templates right now, which is also the reason we haven't implemented custom user-data (see #69).

I'm tempted to make this the default.

I initially though it'd be nice to update CloudFormation stack after it gets created, but that's not a good idea as instance profile change in ASG don't propagate until you create a new instance (but please correct me if I'm wrong, cause I know that's certainly the case for user-data).

Perhaps we should customise CloudFormation template to add parameters, I'm not very keen on using  `text/template` over CloudFormation – thoughts?

**Comment by jstrachan** [comment]
yeah - being able to use ECR seems a pretty good default for now ;)

I did try tweaking the `NodeInstanceRole` myself - but then you have to explicitly remove the Policy before CloudFormation is able to delete things again; so having it in the CloudFormation would be good.

I guess longer term it'd be nice to allow a custom list of policies to apply to worker nodes so that [this list](https://github.com/weaveworks/eksctl/blob/3fddae53d227ca85139fe0c4ad60b01db8861803/pkg/eks/assets/1.10.3/2018-06-05/amazon-eks-nodegroup.yaml#L269-L271) could be modified via a CLI argument

**Comment by jstrachan** [comment]
I wonder if a simple fix for now is to add another parameter for a worker node role; something like...
```yaml
  NodeInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - ${WorkerNodeRole}
```
then we can have a single parameter folks can override for the extra role to add to worker nodes which we could then default to `arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPowerUser` but which folks could use some other role of their choice?

I know its not ideal but it'd be a fairly simple change and would let folks have a simple way to add a more suitable role to worker nodes?
