### ISSUE TITLE
Add "metrics" port 9153 to kube-dns service

### ISSUE THREAD

**Issue by dewe** [weaveworks/eksctl#936]
**Why do you want this feature?**
Prometheus operator (kube-prometheus) expects to find metrics on port 9153, and when not found it raises an alert:

> CoreDNSDown: CoreDNS has disappeared from Prometheus target discovery.

The CoreDNS Pods have a metrics port (9153) defined but not the CoreDNS (kube-dns) service.

**What feature/behavior/change do you want?**

When using CoreDNS, I'd like the `kube-dns` service's ports to match the ports exposed by `coredns` pods:

```
[
  {
    "containerPort": 53,
    "name": "dns",
    "protocol": "UDP"
  },
  {
    "containerPort": 53,
    "name": "dns-tcp",
    "protocol": "TCP"
  },
  {
    "containerPort": 9153,
    "name": "metrics",
    "protocol": "TCP"
  }
]
```

Related: https://github.com/coreos/prometheus-operator/issues/2278

**Comment by dewe** [comment]
Should be pretty straightforward to add a new port in the asset files `pkg/addons/default/assets/coredns-*.json`. 

Are there any reasons for not touching these files?

**Comment by errordeveloper** [comment]
At present, we don't modify CoreDNS, the assets are per AWS recommendation (i.e. what EKS clusters come with), and only used for upgrades. So this is a little non-trivial feature request, ideally it should be fixed in EKS, otherwise we will have to own CoreDNS 100%. Something we should discuss.

**Comment by dewe** [comment]
Aha, that explains what I was (not) seeing. Thanks. For now we have patched our service, even though it seems a bit hacky.

I've submitted a support ticket to AWS, we'll see how that goes...

**Comment by micahhausler** [comment]
Hi @dewe, here's what they'll send you if you haven't gotten it already :) 

The reason we didin't initially add the metrics port in EKS is because it is not _technically_ part of the kube-dns service. An http request to http://kube-dns.kube-system.svc.cluster.local:9153/metrics would end up getting load-balanced across the available pods, which would result in some meaningless prometheus metrics across scrapes.

The other reason we didn't add the port is that for every service port, there are 5 additional environment variables added to all the pods in the service's namespace. While 5 variables is not a significant amount, our thinking was that it added bloat that wasn't necessary. 

```
KUBE_DNS_PORT=udp://10.100.0.10:53
KUBE_DNS_PORT_53_TCP=tcp://10.100.0.10:53
KUBE_DNS_PORT_53_TCP_ADDR=10.100.0.10
KUBE_DNS_PORT_53_TCP_PORT=53
KUBE_DNS_PORT_53_TCP_PROTO=tcp
KUBE_DNS_PORT_53_UDP=udp://10.100.0.10:53
KUBE_DNS_PORT_53_UDP_ADDR=10.100.0.10
KUBE_DNS_PORT_53_UDP_PORT=53
KUBE_DNS_PORT_53_UDP_PROTO=udp
KUBE_DNS_SERVICE_HOST=10.100.0.10
KUBE_DNS_SERVICE_PORT=53
KUBE_DNS_SERVICE_PORT_DNS=53
KUBE_DNS_SERVICE_PORT_DNS_TCP=53
# The following env vars are added for each additional port
KUBE_DNS_PORT_9153_TCP=tcp://10.100.0.10:9153
KUBE_DNS_PORT_9153_TCP_ADDR=10.100.0.10      
KUBE_DNS_PORT_9153_TCP_PORT=9153             
KUBE_DNS_PORT_9153_TCP_PROTO=tcp             
KUBE_DNS_SERVICE_PORT_METRICS=9153
```

Fortunately, Prometheus allows you to query a service's endpoints (setting the  `kubernetes_sd_config[0].role` to "endpoints") and override the port with a `relabel_config` rule. The following configuration (copied from the [prometheus helm chart](https://github.com/helm/charts/blob/master/stable/prometheus/values.yaml#L1128-L1171)) will target individual pods behind a service, and will correctly scrape CoreDNS without a service port.

```yaml
    - job_name: kubernetes-service-endpoints
      kubernetes_sd_configs:
      - role: endpoints
      relabel_configs:
      - action: keep
        regex: true
        source_labels:
        - __meta_kubernetes_service_annotation_prometheus_io_scrape
      - action: replace
        regex: (https?)
        source_labels:
        - __meta_kubernetes_service_annotation_prometheus_io_scheme
        target_label: __scheme__
      - action: replace
        regex: (.+)
        source_labels:
        - __meta_kubernetes_service_annotation_prometheus_io_path
        target_label: __metrics_path__
      - action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        source_labels:
        - __address__
        - __meta_kubernetes_service_annotation_prometheus_io_port
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: kubernetes_namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_service_name
        target_label: kubernetes_name
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: kubernetes_node
```

Does that help?
