### ISSUE TITLE
Allow encryption of EBS volumes

### ISSUE THREAD

**Issue by TommyKTheDJ** [weaveworks/eksctl#952]
**Why do you want this feature?**
To be able to adhere to corporate security policies regarding encryption of certain datasets.

**What feature/behavior/change do you want?**
A method by which the CloudFormation that is created for the NodeGroups includes encryption options for the BlockDeviceMappings in the LaunchConfiguration, e.g.:

```
NodeLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ....
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 100
            VolumeType: gp2
            DeleteOnTermination: true
            Encrypted: true
            kmsKeyID: arn:aws:kms:.......
```

I see that `volumeSize` and `volumeType` are already options in a YAML configuration file, perhaps two new options, e.g.:

```
volumeEncryption: <true|false>
volumekmsKeyID: <only required if above is true>
```
