### ISSUE TITLE
Setting comma-separated list of DNS server IP addresses to clusterDNS generates invalid clusterDNS section in kubelet.yaml 

### ISSUE THREAD

**Issue by s-tokutake** [weaveworks/eksctl#987]
**What happened?**

- Setting comma-separated list of DNS server IP addresses to `clusterDNS` in cluster.yaml as below and apply it.
  - [This document says](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/#options) ` --cluster-dns ` accepts ` Comma-separated list of DNS server IP address `. So I suppose setting multiple ip addresses to `clusterDNS `  in cluster.yaml is acceptable.

```
nodeGroups:
  - name: nodegroup1
    clusterDNS: 169.254.20.10,172.20.0.10
```

- But kubelet does not interpret this setting. Error message is below.

```
 kubelet does not have ClusterDNS IP configured and cannot create Pod using \"ClusterFirst\" policy. Falling back to \"Default\" policy.
```

- kubelet.yaml on the node is ↓

```yaml

[ec2-user@ip-xx-xx-xx-xx ~]$ cat /etc/eksctl/kubelet.yaml
address: 0.0.0.0
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
  webhook:
    cacheTTL: 2m0s
    enabled: true
  x509:
    clientCAFile: /etc/eksctl/ca.crt
authorization:
  mode: Webhook
  webhook:
    cacheAuthorizedTTL: 5m0s
    cacheUnauthorizedTTL: 30s
cgroupDriver: cgroupfs
clusterDNS:
- 169.254.20.10,172.20.0.10
clusterDomain: cluster.local
featureGates:
  RotateKubeletServerCertificate: true
kind: KubeletConfiguration
serverTLSBootstrap: true

```

- ` /etc/resolv.conf `  in a pod on the node is ↓ 

```
[ec2-user@ip-xx-xx-xx-xx ~] kubectl exec podname  cat /etc/resolv.conf
nameserver 10.0.0.2
search ap-northeast-1.compute.internal
options timeout:2 attempts:5
``` 

**What you expected to happen?**

- Valid kubelet.yaml is below. 
  - ` clusterDNS ` setting is `  clusterDNS: ["169.254.20.10","172.20.0.10"] `. 

```yaml

[ec2-user@ip-xx-xx-xx-xx ~]$ cat /etc/eksctl/kubelet.yaml
address: 0.0.0.0
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
  webhook:
    cacheTTL: 2m0s
    enabled: true
  x509:
    clientCAFile: /etc/eksctl/ca.crt
authorization:
  mode: Webhook
  webhook:
    cacheAuthorizedTTL: 5m0s
    cacheUnauthorizedTTL: 30s
cgroupDriver: cgroupfs
clusterDNS: ["169.254.20.10","172.20.0.10"]
clusterDomain: cluster.local
featureGates:
  RotateKubeletServerCertificate: true
kind: KubeletConfiguration
serverTLSBootstrap: true

```

- I correct kubelet.yaml manually , reboot kubelet (` systemctl restart kubelet `) and deploy a pod, which's ` 
 /etc/resolv.conf ` is ↓. this is what I expected. 

```
[ec2-user@ip-xx-xx-xx-xx ~]$ kubectl exec podname  cat /etc/resolv.conf
nameserver 169.254.20.10
nameserver 172.20.0.10
search default.svc.cluster.local svc.cluster.local cluster.local ap-northeast-1.compute.internal
options ndots:5
```

**How to reproduce it?**

- Create cluster.yaml as below and apply it using eksctl ( ` eksctl create cluster -f cluster.yaml ` or ` eksctl create nodegroup -f cluster.yaml ` ).

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dev
  region: ap-northeast-1
  version: "1.13"

vpc:
  id: "vpc-xxxxx"
  cidr: "10.0.0.0/16"
  subnets:
    private:
      ap-northeast-1a:
        id: "subnet-xxxxx"
        cidr: "10.0.144.0/24"

      ap-northeast-1c:
        id: "subnet-xxxxx"
        cidr: "10.0.145.0/24"

      ap-northeast-1d:
        id: "subnet-xxxxx"
        cidr: "10.0.146.0/24"

nodeGroups:
  - name: ng1
    clusterDNS: 169.254.20.10,172.20.0.10
    labels: {role: workers}
    tags: {Stack: development, Site: ikyucom, Role: eks-node, k8s.io/cluster-autoscaler/dev: owned, k8s.io/cluster-autoscaler/enabled: "true"}
    instanceType: c5.xlarge
    desiredCapacity: 4
    maxSize: 5
    privateNetworking: true
    securityGroups:
      attachIDs: [sg-xxxxx]
      withShared: true
    ssh:
      allow: true
      publicKeyPath: xxxxx

```

**Anything else we need to know?**

- eks version is 1.13.

**Versions**
```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.1.38"}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-eks-c57ff8", GitCommit:"c57ff8e35590932c652433fab07988da79265d5b", GitTreeState:"clean", BuildDate:"2019-06-07T20:43:03Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by errordeveloper** [comment]
It maybe possible to set it via [`kubeletExtraConfig`](https://eksctl.io/usage/customizing-the-kubelet/), would you mind trying?

**Comment by s-tokutake** [comment]
@errordeveloper  I tried, but not work.

- apply this file↓.

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dev
  region: ap-northeast-1
  version: "1.13"

vpc:
  id: "vpc-xxxxxx"
  cidr: "10.0.0.0/16"
  subnets:
    private:
      ap-northeast-1a:
        id: "subnet-xxxxx"
        cidr: "10.0.144.0/24"

      ap-northeast-1c:
        id: "subnet-xxxxx"
        cidr: "10.0.145.0/24"

      ap-northeast-1d:
        id: "subnet-xxxxx"
        cidr: "10.0.146.0/24"

nodeGroups:
  - name: ng1-ExtraConfig
    labels: {role: workers}
    tags: {Stack: development, Site: ikyucom, Role: eks-node, k8s.io/cluster-autoscaler/dev: owned, k8s.io/cluster-autoscaler/enabled: "true"}
    instanceType: c5.xlarge
    desiredCapacity: 1
    maxSize: 5
    privateNetworking: true
    securityGroups:
      attachIDs: [sg-xxxxx]
      withShared: true
    ssh:
      allow: true
      publicKeyPath: xxxxx
    kubeletExtraConfig:
      clusterDNS: ["169.254.20.10","172.20.0.10"]
```

- kubelet.yaml on the node is ↓

```yaml
[ec2-user@ip-xx-xx-xx-xx ~]$ cat /etc/eksctl/kubelet.yaml       
address: 0.0.0.0                                                 
apiVersion: kubelet.config.k8s.io/v1beta1                        
authentication:                                                  
  anonymous:                                                     
    enabled: false                                               
  webhook:                                                       
    cacheTTL: 2m0s                                               
    enabled: true                                                
  x509:                                                          
    clientCAFile: /etc/eksctl/ca.crt                             
authorization:                                                   
  mode: Webhook                                                  
  webhook:                                                       
    cacheAuthorizedTTL: 5m0s                                     
    cacheUnauthorizedTTL: 30s                                    
cgroupDriver: cgroupfs                                           
clusterDNS:                                                      
- 169.254.20.10                                                  
- 172.20.0.10                                                    
clusterDomain: cluster.local                                     
featureGates:                                                    
  RotateKubeletServerCertificate: true                           
kind: KubeletConfiguration                                       
serverTLSBootstrap: true                                         

```

- ` /etc/resolv.conf ` in a pod on the node is ↓

```
[ec2-user@ip-xx-xx-xx-xx ~]$ docker exec -it k8s_kube-proxy_kube-proxy-xxxx cat  /etc/resolv.conf
nameserver 10.0.0.2
search ap-northeast-1.compute.internal
options timeout:2 attempts:5
```
